### ISSUE TITLE
？？？

### ISSUE THREAD

**Issue by yhy66-yuhy** [BerriAI/litellm#1011]
Provider List: https://docs.litellm.ai/docs/providers

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

        Python Version: 3.11.5
        Pip Version: 23.3.1
        Open-interpreter Version: cmd:Interpreter, pkg: 0.1.16
        OS Version and Architecture: Windows-10-10.0.22631-SP0
        CPU Info: AMD64 Family 25 Model 116 Stepping 1, AuthenticAMD
        RAM Info: 13.71 GB, used: 6.21, free: 7.51

        Interpreter Info
        Vision: False
        Model: gpt-4-1106-preview
        Function calling: True
        Context window: 128000
        Max tokens: 4096

        Auto run: False
        API base: None
        Local: False

        Curl output: Not local

Traceback (most recent call last):
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 300, in completion
    model, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(model=model, custom_llm_provider=custom_llm_provider, api_base=api_base)
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 1821, in get_llm_provider
    raise e
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 1818, in get_llm_provider
    raise ValueError(f"LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/{model}',..)` Learn more: https://docs.litellm.ai/docs/providers")
ValueError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/gpt-4-1106-preview',..)` Learn more: https://docs.litellm.ai/docs/providers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 21, in start_terminal_interface
    start_terminal_interface(self)
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\terminal_interface\start_terminal_interface.py", line 305, in start_terminal_interface
    interpreter.chat()
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 77, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 92, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 115, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 113, in _streaming_chat
    yield from self._respond()
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 148, in _respond
    yield from respond(self)
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\respond.py", line 49, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\llm\setup_openai_coding_llm.py", line 118, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 962, in wrapper
    raise e
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 899, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 1403, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 3574, in exception_type
    raise e
  File "C:\Users\yhy\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 3556, in exception_type
    raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/gpt-4-1106-preview',..)` Learn more: https://docs.litellm.ai/docs/providers

**Comment by ghost** [comment]
This is litellm supported @yhy66-yuhy - i think you should file this as an issue on the openinterpreter github - https://github.com/KillianLucas/open-interpreter/
