### ISSUE TITLE
[Bug]: using Langfuse integration via litellm proxy in streaming mode (similar to #1026)

### ISSUE THREAD

**Issue by CalabiYau14** [BerriAI/litellm#1061]
### What happened?

Bug using Langfuse integration via litellm proxy similar as in #1026:

I still get a similar error as in #1026 when using the langfuse + proxy (custom openai compatible server via vllm) in streaming mode. Without streaming logging of the endpoints (completion + chat) are working perfectly

### Relevant log output

```shell
Traceback (most recent call last):
File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
self.run()
File "/usr/local/lib/python3.9/site-packages/langfuse/task_manager.py", line 86, in run
self.upload()
File "/usr/local/lib/python3.9/site-packages/langfuse/task_manager.py", line 91, in upload
batch = self._next()
File "/usr/local/lib/python3.9/site-packages/langfuse/task_manager.py", line 69, in _next
item_size = len(json.dumps(item, cls=DatetimeSerializer).encode())
File "/usr/local/lib/python3.9/json/init.py", line 234, in dumps
return cls(
File "/usr/local/lib/python3.9/json/encoder.py", line 199, in encode
chunks = self.iterencode(o, _one_shot=True)
File "/usr/local/lib/python3.9/json/encoder.py", line 257, in iterencode
return _iterencode(o, 0)
File "/usr/local/lib/python3.9/site-packages/langfuse/serializer.py", line 14, in default
return json.JSONEncoder.default(self, obj)
File "/usr/local/lib/python3.9/json/encoder.py", line 179, in default
raise TypeError(f'Object of type {o.class.name} '
TypeError: Object of type Message is not JSON serializable
```

**Comment by ghost** [comment]
@CalabiYau14 acknowledging this issue. I'll have this repro'd + fixed on our end by today.

**Comment by ghost** [comment]
@CalabiYau14 investigated - this will be a more involved fix than intended. Hope to have a fix + better langfuse testing over the weekend.

**Comment by CalabiYau14** [comment]
@krrishdholakia Thanks for taking a look at it. Very much appreciated :-)

**Comment by ghost** [comment]
this is now fixed - https://github.com/BerriAI/litellm/commit/f9dfeb502ae14b78ceafbbb7a8e6591d86d43a9e

should be live soon in v`1.13.2`

**Comment by CalabiYau14** [comment]
Cooll thanks a lot :-)
