### ISSUE TITLE
[Bug]: litellm Docker throws error talking to Ollama

### ISSUE THREAD

**Issue by kulbinderdio** [BerriAI/litellm#1066]
### What happened?

I started docker containers for both ollama and litellm with following setup
```
docker run -d --gpus=all -v ./ollama:/root/.ollama -p 11434:11434 --name ollama ollama/ollama
docker exec -it ollama ollama run llama2:13b

docker run -p 6789:6789 ghcr.io/berriai/litellm:main-v1.10.3  --model ollama/llama2:13b --api_base http://192.168.86.23:11434/api/generate --host 0.0.0.0 --port 6789 --debug

```

following curl directly to ollama works
```
curl http://localhost:11434/api/generate -d '{
  "model": "llama2:13b",
  "prompt":"Why is the sky blue?"
}'
```

Used following curl to call litellm (also tried litellm --test --port 6789)
```
curl http://localhost:6789/v1/chat/completions -H "Content-Type: application/json" -d '{ "model": "ollama-2-13b", "messages": [{"role": "user", "content": "Say this is a test!"}],  "temperature": 0.7 }'
```

Stack trace below of errors thrown. I believe litellm call ollama but has issues on returned data

### Relevant log output

```
LiteLLM: Non-Default params passed to completion() {'stream': True}
self.optional_params: {'stream': True}
Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
self.failure_callback: []
Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
An error occurred: Import error - trying to use async for ollama. import async_generator failed. Try 'pip install async_generator'

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
INFO:     172.17.0.1:52414 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 1269, in completion
    async_generator = ollama.async_get_ollama_response_stream(api_base, model, prompt, optional_params, logging_obj=logging)
AttributeError: module 'litellm.llms.ollama' has no attribute 'async_get_ollama_response_stream'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 188, in acompletion
    response =  await loop.run_in_executor(None, func_with_context)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1369, in wrapper
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1298, in wrapper
    result = original_function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 1424, in completion
    raise exception_type(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 4634, in exception_type
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 4486, in exception_type
    raise ImportError("Import error - trying to use async for ollama. import async_generator failed. Try 'pip install async_generator'")
ImportError: Import error - trying to use async for ollama. import async_generator failed. Try 'pip install async_generator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 873, in chat_completion
    response = await litellm.acompletion(**data)
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1465, in wrapper_async
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1411, in wrapper_async
    result = await original_function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 195, in acompletion
    raise exception_type(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 4634, in exception_type
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 4611, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: Import error - trying to use async for ollama. import async_generator failed. Try 'pip install async_generator'
receiving data: {'messages': [{'role': 'user', 'content': 'this is a test request, write a short poem'}], 'model': 'gpt-3.5-turbo', 'stream': True}
litellm.cache: None
kwargs[caching]: False; litellm.cache: None
litellm.caching: False; litellm.caching_with_models: False; litellm.cache: None
kwargs[caching]: False; litellm.cache: None

LiteLLM completion() model= llama2:13b; provider = ollama

LiteLLM: Params passed to completion() {'functions': [], 'function_call': '', 'temperature': None, 'top_p': None, 'stream': True, 'max_tokens': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': '', 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': None, 'custom_llm_provider': 'ollama', 'model': 'llama2:13b', 'n': None, 'stop': None}

LiteLLM: Non-Default params passed to completion() {'stream': True}
self.optional_params: {'stream': True}
Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
self.failure_callback: []
Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
An error occurred: Import error - trying to use async for ollama. import async_generator failed. Try 'pip install async_generator'

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
INFO:     172.17.0.1:48442 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 1269, in completion
    async_generator = ollama.async_get_ollama_response_stream(api_base, model, prompt, optional_params, logging_obj=logging)
AttributeError: module 'litellm.llms.ollama' has no attribute 'async_get_ollama_response_stream'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 188, in acompletion
    response =  await loop.run_in_executor(None, func_with_context)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1369, in wrapper
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1298, in wrapper
    result = original_function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 1424, in completion
    raise exception_type(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 4634, in exception_type
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 4486, in exception_type
    raise ImportError("Import error - trying to use async for ollama. import async_generator failed. Try 'pip install async_generator'")
ImportError: Import error - trying to use async for ollama. import async_generator failed. Try 'pip install async_generator'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 873, in chat_completion
    response = await litellm.acompletion(**data)
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1465, in wrapper_async
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1411, in wrapper_async
    result = await original_function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 195, in acompletion
    raise exception_type(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 4634, in exception_type
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 4611, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: Import error - trying to use async for ollama. import async_generator failed. Try 'pip install async_generator'
receiving data: {'messages': [{'role': 'user', 'content': 'this is a test request, write a short poem'}], 'model': 'gpt-3.5-turbo', 'stream': True}
litellm.cache: None
kwargs[caching]: False; litellm.cache: None
litellm.caching: False; litellm.caching_with_models: False; litellm.cache: None
kwargs[caching]: False; litellm.cache: None

LiteLLM completion() model= llama2:13b; provider = ollama

LiteLLM: Params passed to completion() {'functions': [], 'function_call': '', 'temperature': None, 'top_p': None, 'stream': True, 'max_tokens': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': '', 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': None, 'custom_llm_provider': 'ollama', 'model': 'llama2:13b', 'n': None, 'stop': None}

LiteLLM: Non-Default params passed to completion() {'stream': True}
self.optional_params: {'stream': True}
Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
self.failure_callback: []
Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
An error occurred: Import error - trying to use async for ollama. import async_generator failed. Try 'pip install async_generator'

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
INFO:     172.17.0.1:48452 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
```

**Comment by ghost** [comment]
@kulbinderdio looks like the `async_generator` dependency is missing.

**Comment by ghost** [comment]
can you pip install that in your docker container and see if that fixes it. I'll also update our requirements.txt

**Comment by ghost** [comment]
added - https://github.com/BerriAI/litellm/commit/9494c2cd9e2eddf207f21c4cff07846192cb0cba

**Comment by kulbinderdio** [comment]
Hi @krrishdholakia that install seems to have fixed things
Any idea when the docker will be updated?
cheers

**Comment by ghost** [comment]
yep - we'll update the docker image once we have a published release (passing our ci/cd). Probably by EOD today.

**Comment by ghost** [comment]
Closing as this is now fixed
