### ISSUE TITLE
[Bug]: Too many open files

### ISSUE THREAD

**Issue by ml729** [BerriAI/litellm#1070]
### What happened?

I am calling `litellm.completion` with `gpt-3.5-turbo`. Every 200-300 or so calls, I get an error saying "Too many open files". 
This does not happen when I directly use the OpenAI API.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/tenacity/__init__.py", line 382, in __call__
  File "failure.py", line 57, in gen
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/litellm/utils.py", line 1482, in wrapper
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/litellm/utils.py", line 1411, in wrapper
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/litellm/main.py", line 1425, in completion
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/litellm/utils.py", line 4765, in exception_type
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/litellm/main.py", line 599, in completion
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/litellm/main.py", line 575, in completion
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/litellm/llms/openai.py", line 252, in completion
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/litellm/llms/openai.py", line 247, in completion
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/litellm/llms/openai.py", line 218, in completion
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/openai/_client.py", line 107, in __init__
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/openai/_base_client.py", line 746, in __init__
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/httpx/_client.py", line 672, in __init__
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/httpx/_client.py", line 720, in _init_transport
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/httpx/_transports/default.py", line 126, in __init__
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/httpx/_config.py", line 52, in create_ssl_context
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/httpx/_config.py", line 76, in __init__
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/httpx/_config.py", line 88, in load_ssl_context
  File "/Users/user/miniconda3/envs/my_env/lib/python3.8/site-packages/httpx/_config.py", line 147, in load_ssl_context_verify
OSError: [Errno 24] Too many open files
```

**Comment by ishaan-jaff** [comment]
thanks for the feedack @ml729, this error occurs when there are too any `OpenAI` clients created, you can fix this by passing a client to the completion call 

see example call with `client` 

```python
from openai import OpenAI 
response = await litellm.acompletion(model, messages, client = OpenAI(api_key=), **kwargs)
```

https://github.com/BerriAI/litellm/blob/db51a95a42fcf343f0491020e9c3bf9d1528691b/litellm/router.py#L254C119-L254C119

**Comment by ishaan-jaff** [comment]
@ml729 open to suggestions on how we can deal with this better

**Comment by ghost** [comment]
@ml729 which version of litellm are you on?

**Comment by ghost** [comment]
@ml729  / anyone else facing this issue - it's being caused due to a new OpenAI/Azure client being initialized in every .completion call. 

For better scalability - switch to the Router - it initializes a global client to be used across calls for the same deployment 

https://docs.litellm.ai/docs/routing#quick-start

```python
from litellm import Router

model_list = [{ # list of model deployments 
    "model_name": "gpt-3.5-turbo", # model alias 
    "litellm_params": { # params for litellm completion/embedding call 
        "model": "azure/chatgpt-v-2", # actual model name
        "api_key": os.getenv("AZURE_API_KEY"),
        "api_version": os.getenv("AZURE_API_VERSION"),
        "api_base": os.getenv("AZURE_API_BASE")
    }
}, {
    "model_name": "gpt-3.5-turbo", 
    "litellm_params": { # params for litellm completion/embedding call 
        "model": "azure/chatgpt-functioncalling", 
        "api_key": os.getenv("AZURE_API_KEY"),
        "api_version": os.getenv("AZURE_API_VERSION"),
        "api_base": os.getenv("AZURE_API_BASE")
    }
}, {
    "model_name": "gpt-3.5-turbo", 
    "litellm_params": { # params for litellm completion/embedding call 
        "model": "gpt-3.5-turbo", 
        "api_key": os.getenv("OPENAI_API_KEY"),
    }
}]

router = Router(model_list=model_list)

# openai.ChatCompletion.create replacement
response = await router.acompletion(model="gpt-3.5-turbo", 
                messages=[{"role": "user", "content": "Hey, how's it going?"}])

print(response)
```

**Comment by ghost** [comment]
Tracking an improvement we can make on litellm.completion for this as well @ml729 https://github.com/BerriAI/litellm/issues/1270

I'll update you once it's out.

**Comment by avrecum** [comment]
Any updates on this?

**Comment by ishaan-jaff** [comment]
fixed with this PR: https://github.com/BerriAI/litellm/pull/3956 @avrecum @ml729

**Comment by avrecum** [comment]
Happened to me again just now on version 1.40.2.
