### ISSUE TITLE
[Feature]: Add /chat/completions, /embeddings to OpenAPI spec 

### ISSUE THREAD

**Issue by shuther** [BerriAI/litellm#1132]
### The Feature

As per the [fastapi documentation](https://fastapi.tiangolo.com/tutorial/metadata/), it is possible to extend the shared metadata and provide external documentation links.

### Motivation, pitch

Better API documentation and examples help to build and test litellm within a more complex architecture.

**Comment by shuther** [comment]
the version of litellm I had was a bit outdated; there is just the question of the main description, such as license for the project...

**Comment by shuther** [comment]
Also, some parameters are not captured for some calls, so it is not possible to test them from the fastapi/openapi screen.

```
An error occurred: Expecting value: line 1 column 1 (char 0) Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 954, in chat_completion
    data = await request.json() # type: ignore
          ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/requests.py", line 244, in json
    self._json = json.loads(body)
                 ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
INFO:     127.0.0.1:62724 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
```

<img width="1384" alt="Screenshot 2023-12-14 at 15 25 02" src="https://github.com/BerriAI/litellm/assets/33225407/8df64c71-f1d8-4242-88d6-c8089699a843">

**Comment by ghost** [comment]
acknowledging this feedback

**Comment by ghost** [comment]
closing as the main issue is completed (/chat/completions, and /embeddings is on the openapi spec). @shuther i believe you have another issue opened for improving the openapi docs - i think that's a better place to have the improvement discussion.
