### ISSUE TITLE
Support meta-llama/Llama-2-7b-chat-hf on vLLM: 

### ISSUE THREAD

**Issue by vecorro** [BerriAI/litellm#1134]
### The Feature

vLLM supports meta-llama/Llama-2-7b-chat-hf (and many other LLMs from HF model hub) out of the box. Unfortunately, there seems to be a mismatch between the vLLM's list of supported LLMs and LiteLLM.

In this specific example, I'm using the following config.yaml file

```
model_list:
  - model_name: vllm-model
    litellm_params:
      model: vllm/meta-llama/Llama-2-7b-chat-hf
      api_base: http://localhost:8000
```

Then I ran LiteLLM proxy via

`litellm --config config.yaml --debug`

and then running the following curl

```
url --location 'http://0.0.0.0:8000/chat/completions'     --header 'Content-Type: application/json'     --data ' {
    "model": "vllm/meta-llama/Llama-2-7b-chat-hf",
    "messages": [
        {
        "role": "user",
        "content": "what llm are you"
        }
    ]
    }'
```

I get this error trace

```
LiteLLM completion() model= meta-llama/Llama-2-7b-chat-hf; provider = vllm

LiteLLM: Params passed to completion() {'functions': [], 'function_call': '', 'temperature': None, 'top_p': None, 'stream': None, 'max_tokens': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': None, 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': 0, 'custom_llm_provider': 'vllm', 'model': 'meta-llama/Llama-2-7b-chat-hf', 'n': None, 'stop': None}

LiteLLM: Non-Default params passed to completion() {'max_retries': 0}
self.optional_params: {'max_retries': 0}
2023-12-14 08:49:11,584	WARNING worker.py:1750 -- Failed to set SIGTERM handler, processes mightnot be cleaned up properly on exit.
INFO 12-14 08:49:12 llm_engine.py:72] Initializing an LLM engine with config: model='meta-llama/Llama-2-7b-chat-hf', tokenizer='meta-llama/Llama-2-7b-chat-hf', tokenizer_mode=auto, revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, quantization=None, seed=0)
INFO 12-14 08:49:12 tokenizer.py:30] For some LLaMA V1 models, initializing the fast tokenizer may take a long time. To reduce the initialization time, consider using 'hf-internal-testing/llama-tokenizer' instead of the original tokenizer.
INFO 12-14 08:49:17 llm_engine.py:205] # GPU blocks: 2865, # CPU blocks: 512
Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
LiteLLM.Router: Attempting to add vllm/meta-llama/Llama-2-7b-chat-hf-ModelID-vllm/meta-llama/Llama-2-7b-chat-hfhttp://localhost:8000 to cooldown list. updated_fails: 1; self.allowed_fails: 0
get cache: cache key: 08-49:cooldown_models
get cache: cache result: None
LiteLLM.Router: adding vllm/meta-llama/Llama-2-7b-chat-hf-ModelID-vllm/meta-llama/Llama-2-7b-chat-hfhttp://localhost:8000 to cooldown models
set cache: key: 08-49:cooldown_models; value: ['vllm/meta-llama/Llama-2-7b-chat-hf-ModelID-vllm/meta-llama/Llama-2-7b-chat-hfhttp://localhost:8000']
LiteLLM.Router: 
EXCEPTION FOR DEPLOYMENTS

LiteLLM.Router: {'vllm/meta-llama/Llama-2-7b-chat-hf-ModelID-vllm/meta-llama/Llama-2-7b-chat-hfhttp://localhost:8000': ["<class 'litellm.exceptions.APIConnectionError'>Status: 500Message: NoneSamplingParams.__init__() got an unexpected keyword argument 'max_retries'Full exceptionSamplingParams.__init__() got an unexpected keyword argument 'max_retries'"]}
LiteLLM.Router: Model vllm/meta-llama/Llama-2-7b-chat-hf-ModelID-vllm/meta-llama/Llama-2-7b-chat-hfhttp://localhost:8000 had 1 exception
Custom Logger - final response object: None
self.failure_callback: [<bound method Router.deployment_callback_on_failure of <litellm.router.Router object at 0x7fa0193f6f80>>]
Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
LiteLLM.Router: Attempting to add vllm/meta-llama/Llama-2-7b-chat-hf-ModelID-vllm/meta-llama/Llama-2-7b-chat-hfhttp://localhost:8000 to cooldown list. updated_fails: 1; self.allowed_fails: 0
get cache: cache key: 08-49:cooldown_models
get cache: cache result: ['vllm/meta-llama/Llama-2-7b-chat-hf-ModelID-vllm/meta-llama/Llama-2-7b-chat-hfhttp://localhost:8000']
LiteLLM.Router: adding vllm/meta-llama/Llama-2-7b-chat-hf-ModelID-vllm/meta-llama/Llama-2-7b-chat-hfhttp://localhost:8000 to cooldown models
LiteLLM.Router: 
EXCEPTION FOR DEPLOYMENTS

LiteLLM.Router: {'vllm/meta-llama/Llama-2-7b-chat-hf-ModelID-vllm/meta-llama/Llama-2-7b-chat-hfhttp://localhost:8000': ["<class 'litellm.exceptions.APIConnectionError'>Status: 500Message: NoneSamplingParams.__init__() got an unexpected keyword argument 'max_retries'Full exceptionSamplingParams.__init__() got an unexpected keyword argument 'max_retries'", "<class 'litellm.exceptions.APIConnectionError'>Status: 500Message: NoneSamplingParams.__init__() got an unexpected keyword argument 'max_retries'Full exceptionSamplingParams.__init__() got an unexpected keyword argument 'max_retries'"]}
LiteLLM.Router: Model vllm/meta-llama/Llama-2-7b-chat-hf-ModelID-vllm/meta-llama/Llama-2-7b-chat-hfhttp://localhost:8000 had 2 exception
Custom Logger - final response object: None
LiteLLM.Router: An exception occurs: SamplingParams.__init__() got an unexpected keyword argument 'max_retries'
LiteLLM.Router: Trying to fallback b/w models
An error occurred: SamplingParams.__init__() got an unexpected keyword argument 'max_retries'

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
Traceback (most recent call last):
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/main.py", line 1277, in completion
    model_response = vllm.completion(
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/llms/vllm.py", line 48, in completion
    sampling_params = SamplingParams(**optional_params)
TypeError: SamplingParams.__init__() got an unexpected keyword argument 'max_retries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/main.py", line 193, in acompletion
    response =  await loop.run_in_executor(None, func_with_context)
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/utils.py", line 1612, in wrapper
    raise e
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/utils.py", line 1540, in wrapper
    result = original_function(*args, **kwargs)
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/main.py", line 1473, in completion
    raise exception_type(
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/utils.py", line 5058, in exception_type
    raise e
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/utils.py", line 5035, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: SamplingParams.__init__() got an unexpected keyword argument 'max_retries'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 1004, in chat_completion
    response = await llm_router.acompletion(**data, specific_deployment = True)
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/router.py", line 238, in acompletion
    raise e
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/router.py", line 234, in acompletion
    response = await self.async_function_with_fallbacks(**kwargs)
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/router.py", line 423, in async_function_with_fallbacks
    raise original_exception
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/router.py", line 373, in async_function_with_fallbacks
    response = await self.async_function_with_retries(*args, **kwargs)
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/router.py", line 455, in async_function_with_retries
    raise original_exception
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/router.py", line 435, in async_function_with_retries
    response = await original_function(*args, **kwargs)
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/router.py", line 272, in _acompletion
    raise e
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/router.py", line 266, in _acompletion
    response = await litellm.acompletion(**{**data, "messages": messages, "caching": self.cache_responses, "client": model_client, **kwargs})
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/utils.py", line 1725, in wrapper_async
    raise e
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/utils.py", line 1659, in wrapper_async
    result = await original_function(*args, **kwargs)
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/main.py", line 201, in acompletion
    raise exception_type(
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/utils.py", line 5058, in exception_type
    raise e
  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/utils.py", line 5028, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: SamplingParams.__init__() got an unexpected keyword argument 'max_retries'
INFO:     127.0.0.1:39870 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
```

### Motivation, pitch

vLLM is very popular when developers want to leverage open-source LLMs available from HF and run those LLMs on-premise. A closer integration with vLLM would allow LiteLLM get more traction as the universal LLM gateway between users and cloud-based LLM services, and locally run LLMs.

**Comment by ghost** [comment]
Hey @vecorro vllm also has an openai compatible server, does it work when you call that via the proxy? 

```
model_list:
  - model_name: vllm-model
    litellm_params:
      model: openai/meta-llama/Llama-2-7b-chat-hf
      api_base: http://localhost:8000
```

**Comment by vecorro** [comment]
Thanks @krrishdholakia.

If I use that config.yaml and run the following curl cmd:
```
curl --location 'http://0.0.0.0:8000/chat/completions'     --header 'Content-Type: application/json'     --data ' {
    "model": "openai/meta-llama/Llama-2-7b-chat-hf",
    "messages": [
        {
        "role": "user",
        "content": "what llm are you"
        }
    ]
    }'

```

I get a different error (sounds like related to the lack of a provider):

```
itellm.exceptions.APIError: OpenAIException - Error code: 500 - {'detail': 'LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For \'Huggingface\' inference endpoints pass in `completion(model=\'huggingface/meta-llama/Llama-2-7b-chat-hf\',..)` 
Learn more: https://docs.litellm.ai/docs/providers\n\nTraceback (most recent call last):\n  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/utils.py", line 4205, in exception_type\n    request=original_exception.request\nAttributeError: \'ValueError\' object has no attribute \'request\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  
File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 1008, in chat_completion\n    response = await litellm.acompletion(**data)\n  

File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/utils.py", line 1725, in wrapper_async\n    raise e\n  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/utils.py", line 1659, in wrapper_async\n    result = await original_function(*args, **kwargs)\n  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/main.py", line 201, in acompletion\n    raise exception_type(\n  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/utils.py", line 5060, in exception_type\n    raise original_exception\n  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/main.py", line 169, in acompletion\n    _, custom_llm_provider, _, _ = get_llm_provider(model=model, api_base=kwargs.get("api_base", None))\n  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/utils.py", line 2821, in get_llm_provider\n    raise e\n  File "/home/vmuser/miniconda3/envs/llm-env2/lib/python3.10/site-packages/litellm/utils.py", line 2818, in get_llm_provider\n    

raise ValueError(f"LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For \'Huggingface\' inference endpoints pass in `completion(model=\'huggingface/{model}\',..)` Learn more: https://docs.litellm.ai/docs/providers")\nValueError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For \'Huggingface\' inference endpoints pass in `completion(model=\'huggingface/meta-llama/Llama-2-7b-chat-hf\',..)` Learn more: https://docs.litellm.ai/docs/providers\n'}
INFO:     127.0.0.1:47212 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
```

**Comment by vecorro** [comment]
Actually, wonder how litellm could know that it has to invoque vLLM when looking at the config file @krrishdholakia has kindly proposed:
```
model_list:
  - model_name: vllm-model
    litellm_params:
      model: openai/meta-llama/Llama-2-7b-chat-hf
      api_base: http://localhost:8000
```

**Comment by ghost** [comment]
@vecorro your curl request is incorrect. I should probably have added more details. 

```yaml
model_list:
  - model_name: vllm-model # the client-side model name/alias
    litellm_params:
      model: openai/meta-llama/Llama-2-7b-chat-hf # the model name going into litellm.completions()
      api_base: http://localhost:8000 # wherever your vllm endpoint is hosted
```

so in your case, the curl request would be: 

```curl
curl --location 'http://0.0.0.0:8000/chat/completions'     --header 'Content-Type: application/json'     --data ' {
    "model": "vllm-model",
    "messages": [
        {
        "role": "user",
        "content": "what llm are you"
        }
    ]
    }'
```

LiteLLM knows how to call a model based on the provider name, which is either inferred (e.g. `model: gpt-3.5-turbo` will route to openai or explicitly provided in the litellm model name `model: openai/..` will assume it's an openai-compatible endpoint) 
 

See - https://docs.litellm.ai/docs/providers for provider-specific info

**Comment by ghost** [comment]
@vecorro can you confirm if this solved your problem?

**Comment by ghost** [comment]
closing due to inactivity.
