### ISSUE TITLE
[Bug]: ollama litellm.completion() + stream not working 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1156]
### What happened?

Code to repro:

```python
        response = litellm.completion(model="ollama/llama2", 
                                             messages=[{"role": "user", "content": "Hey, how's it going?"}],
                                             stream=True)
        for chunk in response: 
            print(chunk)
```

### Relevant log output

```shell
LiteLLM: Params passed to completion() {'functions': [], 'function_call': '', 'temperature': None, 'top_p': None, 'stream': True, 'max_tokens': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': None, 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': None, 'custom_llm_provider': 'ollama', 'model': 'llama2', 'n': None, 'stop': None}

LiteLLM: Non-Default params passed to completion() {'stream': True}
self.optional_params: {'stream': True}
PRE-API-CALL ADDITIONAL ARGS: {'api_base': 'http://localhost:11434/api/generate', 'complete_input_dict': {'model': 'llama2', 'prompt': "Hey, how's it going?", 'stream': True}, 'headers': {}, 'acompletion': False}


POST Request Sent from LiteLLM:
curl -X POST \
http://localhost:11434/api/generate \
-d '{'model': 'llama2', 'prompt': "Hey, how's it going?", 'stream': True}'


value of chunk: {'role': 'assistant', 'content': ' Hello'}
PROCESSED CHUNK PRE CHUNK CREATOR: {'role': 'assistant', 'content': ' Hello'}

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Logging Details: logger_fn - None | callable(logger_fn) - False
HITS AN ERROR: the JSON object must be str, bytes or bytearray, not dict

 Traceback (most recent call last):
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 5828, in chunk_creator
    response_obj = self.handle_ollama_stream(chunk)
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 5651, in handle_ollama_stream
    raise e
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 5632, in handle_ollama_stream
    json_chunk = json.loads(chunk)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 5932, in __next__
    response = self.chunk_creator(chunk=chunk)
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 5919, in chunk_creator
    raise exception_type(model=self.model, custom_llm_provider=self.custom_llm_provider, original_exception=e)
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 5192, in exception_type
    raise e
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 5169, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: the JSON object must be str, bytes or bytearray, not dict
```

**Comment by ishaan-jaff** [comment]
i'm on the latest version of the github package

**Comment by ishaan-jaff** [comment]
for this issue please add testing once fixed, so it does not re-occur

**Comment by ghost** [comment]
fixed - https://github.com/BerriAI/litellm/commit/a3c7a340a50f900d85ace1348afffd7aed9df0db

@ishaan-jaff if you can create a separate issue to track setting up a deployed ollama endpoint, that'd be great.
