### ISSUE TITLE
[Bug]: AttributeError: 'Router' object has no attribute 'deployment_latency_map'

### ISSUE THREAD

**Issue by mongolu** [BerriAI/litellm#1166]
### What happened?

A bug happened!

### Relevant log output

```shell
Async Wrapper: Completed Call, calling async_success_handler: <bound method Logging.async_success_handler of <litellm.utils.Logging object at 0x7f2a69866b90>>
Logging Details LiteLLM-Success Call
final response: ModelResponse(id='chatcmpl-3f134703-646e-4c7e-824a-0dd9e6226875', choices=[Choices(finish_reason='stop', index=0, message=Message(content=' Coder1', role='assistant'))], created=1702808095, model='ollama/dolphin-mixtral:8x7b-v2.5-fp16', object='chat.completion', system_fingerprint=None, usage=Usage(prompt_tokens=662, completion_tokens=3, total_tokens=665))
success callbacks: [<bound method Router.deployment_callback of <litellm.router.Router object at 0x7f2a69a0e7a0>>]
INFO:     127.0.0.1:53404 - "POST /chat/completions HTTP/1.1" 200 OK
success callbacks: Running Custom Callback Function
Async success callbacks: []
get cache: cache key: ollama/dolphin-mixtral:8x7b-v2.5-fp16:tpm:10-14
get cache: cache result: None
set cache: key: ollama/dolphin-mixtral:8x7b-v2.5-fp16:tpm:10-14; value: 665
get cache: cache key: ollama/dolphin-mixtral:8x7b-v2.5-fp16:rpm:10-14
get cache: cache result: None
set cache: key: ollama/dolphin-mixtral:8x7b-v2.5-fp16:rpm:10-14; value: 1
Custom Logger Error - Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litellm/integrations/custom_logger.py", line 93, in log_event
    callback_func(
  File "/usr/local/lib/python3.10/dist-packages/litellm/router.py", line 637, in deployment_callback
    self.deployment_latency_map[model_name] = (end_time - start_time).total_seconds()
AttributeError: 'Router' object has no attribute 'deployment_latency_map'
```

**Comment by ghost** [comment]
@mongolu is your model_list empty? 

Any details on how you're initializing the router would be great.

**Comment by ghost** [comment]
also pushed a fix to init the map even if model list is empty. https://github.com/BerriAI/litellm/commit/071283c102e973c4063415f3db0ded466f32664d
