### ISSUE TITLE
Async_generator is not defined

### ISSUE THREAD

**Issue by highcurving** [BerriAI/litellm#1171]
Loaded up litellm and when i go to where its running and try to do /chat/completions 

i get this error

...  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/utils.py", line 1792, in wrapper_async\n    raise e\n  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/utils.py", line 1723, in wrapper_async\n    result = await original_function(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/main.py", line 202, in acompletion\n    raise exception_type(\n          ^^^^^^^^^^^^^^^\n  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/utils.py", line 5192, in exception_type\n    raise e\n  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/utils.py", line 5169, in exception_type\n    raise APIConnectionError(\nlitellm.exceptions.APIConnectionError: name \'async_generator\' is not defined\n'}

I've tried installing async_generator separately as this should be part of python 3.11.5 but its still not working.

**Comment by ishaan-jaff** [comment]
@highcurving how do you start the proxy ?

**Comment by scurving** [comment]
litellm --model ollama/starcoder

**Comment by ghost** [comment]
This is no longer a required dependency. 

Can you share more of the stacktrace? I'm specifically looking for the ollama part. And can you confirm you're on the latest version of liteLLM?

**Comment by scurving** [comment]
Traceback (most recent call last):
  File "/Users/patrick/Main-projects/myteam/test.py", line 90, in <module>
    user_proxy.initiate_chat(
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 556, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 354, in send
    recipient.receive(message, self, request_reply, silent)
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 487, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 962, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/agentchat/groupchat.py", line 340, in run_chat
    reply = speaker.generate_reply(sender=self)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 962, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 631, in generate_oai_reply
    response = client.create(
               ^^^^^^^^^^^^^^
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/oai/client.py", line 260, in create
    response = self._completions_create(client, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/oai/client.py", line 346, in _completions_create
    response = completions.create(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_utils/_utils.py", line 303, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 645, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 1088, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 853, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 916, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 958, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 916, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 958, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 930, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Error code: 500 - {'detail': 'name \'async_generator\' is not defined\n\nTraceback (most recent call last):\n  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/main.py", line 192, in acompletion\n    response = await init_response\n               ^^^^^^^^^^^^^^^^^^^\n  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/llms/ollama.py", line 253, in ollama_acompletion\n    @async_generator\n     ^^^^^^^^^^^^^^^\nNameError: name \'async_generator\' is not defined\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 1014, in chat_completion\n    response = await litellm.acompletion(**data)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/utils.py", line 1792, in wrapper_async\n    raise e\n  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/utils.py", line 1723, in wrapper_async\n    result = await original_function(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/main.py", line 202, in acompletion\n    raise exception_type(\n          ^^^^^^^^^^^^^^^\n  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/utils.py", line 5192, in exception_type\n    raise e\n  File "/Users/patrick/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/utils.py", line 5169, in exception_type\n    raise APIConnectionError(\nlitellm.exceptions.APIConnectionError: name \'async_generator\' is not defined\n'}

**Comment by ghost** [comment]
@highcurving can you please upgrade your liteLLM version and let me know if the issue persists. 

This is also probably solved by just doing `pip install async_generator`

**Comment by oisee** [comment]
> @highcurving can you please upgrade your liteLLM version and let me know if the issue persists.
> 
> This is also probably solved by just doing `pip install async_generator`

did exactly that, but got another error on the ollama/mistral request:

`"'NoneType' object is not subscriptable Traceback (most recent call last):\n  File \"/Users/<myusername>/miniconda3/envs/litellm/lib/python3.11/site-packages/litellm/proxy/proxy_server.py\", line 1010, in chat_completion\n    response = await llm_router.acompletion(**data, specific_deployment = True)\n    `


litellm                   1.15.1 
python 3.11.5

**Comment by ghost** [comment]
Hey @oisee i can repro this, The error seems to be Ollama raising an exception stating you don't have this model. Can you please pull it and run it again. 


<img width="1307" alt="Screenshot 2023-12-19 at 2 55 04 PM" src="https://github.com/BerriAI/litellm/assets/17561003/dddb8e0e-fe5e-49a9-ab54-2b0647cef75c">
<img width="837" alt="Screenshot 2023-12-19 at 2 56 06 PM" src="https://github.com/BerriAI/litellm/assets/17561003/d3ae4aa8-6100-4d38-88ab-c797813d2338">

**Comment by ghost** [comment]
Just pushed a commit to correctly raise this exception as well - https://github.com/BerriAI/litellm/commit/5936664a1671fdda2381b82d29892e794676ca0e
