### ISSUE TITLE
[Bug]: No module named openai.error

### ISSUE THREAD

**Issue by iplayfast** [BerriAI/litellm#1176]
### What happened?

litellm -m ollama/mistral --port 9000 --drop_params&
[2] 2834952
(autogen) chris@FORGE:~/ai/aiprojects/ollamastartservers$ Traceback (most recent call last):
  File "/home/chris/anaconda3/envs/autogen/bin/litellm", line 5, in <module>
    from litellm import run_server
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/__init__.py", line 332, in <module>
    from .timeout import timeout
  File "/home/chris/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/timeout.py", line 20, in <module>
    from openai.error import Timeout
ModuleNotFoundError: No module named 'openai.error'

### Relevant log output

```shell
pip freeze | grep openai
openai==1.5.0
```

**Comment by iplayfast** [comment]
upgraded litellm and the issue is gone.
