### ISSUE TITLE
[Bug]: Unable to invoke the phind model via together.ai

### ISSUE THREAD

**Issue by JacobDu** [BerriAI/litellm#1198]
### What happened?

I am trying to use the proxy server function of litellm to access the `phind` model via `together.ai`.
I tried `/chat/completions` and `/completions`, both returned abnormal responses.
I tried to call the `mixtral` model via `together.ai` and it was successfully response.

following is my config.yaml

```yaml
model_list:
  - model_name: phind
    litellm_params:
      model: together_ai/Phind/Phind-CodeLlama-34B-v2
  - model_name: mixtral
    litellm_params:
      model: together_ai/mistralai/Mixtral-8x7B-Instruct-v0.1
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 298, in text_completion
    return litellm.text_completion(**{**data, "prompt": prompt, "caching": self.cache_responses, **kwargs}) # type: ignore
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 2102, in text_completion
    response = completion(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1579, in wrapper
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1507, in wrapper
    result = original_function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 1431, in completion
    raise exception_type(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 4975, in exception_type
    raise original_exception
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 1053, in completion
    model_response = together_ai.completion(
  File "/usr/local/lib/python3.9/site-packages/litellm/llms/together_ai.py", line 118, in completion
    prompt = prompt_factory(model=model, messages=messages, api_key=api_key, custom_llm_provider="together_ai") # api key required to query together ai model list
  File "/usr/local/lib/python3.9/site-packages/litellm/llms/prompt_templates/factory.py", line 373, in prompt_factory
    return format_prompt_togetherai(messages=messages, prompt_format=prompt_format, chat_template=chat_template)
  File "/usr/local/lib/python3.9/site-packages/litellm/llms/prompt_templates/factory.py", line 286, in format_prompt_togetherai
    prompt = hf_chat_template(model=None, messages=messages, chat_template=chat_template)
  File "/usr/local/lib/python3.9/site-packages/litellm/llms/prompt_templates/factory.py", line 231, in hf_chat_template
    raise Exception("Error rendering template")
Exception: Error rendering template
```

**Comment by ghost** [comment]
Hey @JacobDu what version of litellm are you using? this should be a non-blocking error

**Comment by JacobDu** [comment]
@krrishdholakia 
The proxy server I am running is using a container. The image version is `ghcr.io/berriai/litellm:main-v1.12.3`

**Comment by ghost** [comment]
This is a really old version (for context we're on v`1.15.3` now). 

Can you try running this via the cli tool and let me know if the problem persists @JacobDu 

```
$ pip install litellm[proxy]
```

```
$ litellm --config /path/to/config.yaml
```

```
curl --location 'http://0.0.0.0:8000/chat/completions' \
--header 'Content-Type: application/json' \
--data ' {
      "model": "phind",
      "messages": [
        {
          "role": "user",
          "content": "what llm are you"
        }
      ]
    }
'
```

cc: @ishaan-jaff i believe you were looking into automating the docker releases

**Comment by JacobDu** [comment]
After upgrading litellm to the latest version (1.15.3) in the container, I can access the phind model through together ai normally. I hope a docker image containing the latest version can be released. Thanks for your help. @krrishdholakia
