### ISSUE TITLE
raise better error for misconfigured config.yaml

### ISSUE THREAD

**Issue by Huge** [BerriAI/litellm#1207]
### What happened?

When running the proxy without configuration or likely also with a misconfigured .yaml
and trying ` poetry run litellm --test`  the exception message seems misleading,
even if you run the proxy as suggested `OPENAI_API_KEY=sk-xy  litellm` nothing would change.

Ideal is to have the output without the stack trace and say something about the model list being empty and how to fill it.

### Relevant log output

```shell
LiteLLM: Making a test ChatCompletions request to your proxy
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/huge/.cache/pypoetry/virtualenvs/litellm-ZzSyTc5A-py3.9/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/huge/.cache/pypoetry/virtualenvs/litellm-ZzSyTc5A-py3.9/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/huge/.cache/pypoetry/virtualenvs/litellm-ZzSyTc5A-py3.9/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/huge/.cache/pypoetry/virtualenvs/litellm-ZzSyTc5A-py3.9/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/huge/prog/litellm/litellm/proxy/proxy_cli.py", line 204, in run_server
    response = client.chat.completions.create(model="gpt-3.5-turbo", messages = [
  File "/home/huge/.cache/pypoetry/virtualenvs/litellm-ZzSyTc5A-py3.9/lib/python3.9/site-packages/openai/_utils/_utils.py", line 303, in wrapper
    return func(*args, **kwargs)
  File "/home/huge/.cache/pypoetry/virtualenvs/litellm-ZzSyTc5A-py3.9/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 598, in create
    return self._post(
  File "/home/huge/.cache/pypoetry/virtualenvs/litellm-ZzSyTc5A-py3.9/lib/python3.9/site-packages/openai/_base_client.py", line 1086, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/huge/.cache/pypoetry/virtualenvs/litellm-ZzSyTc5A-py3.9/lib/python3.9/site-packages/openai/_base_client.py", line 846, in request
    return self._request(
  File "/home/huge/.cache/pypoetry/virtualenvs/litellm-ZzSyTc5A-py3.9/lib/python3.9/site-packages/openai/_base_client.py", line 884, in _request
    return self._retry_request(
  File "/home/huge/.cache/pypoetry/virtualenvs/litellm-ZzSyTc5A-py3.9/lib/python3.9/site-packages/openai/_base_client.py", line 956, in _retry_request
    return self._request(
  File "/home/huge/.cache/pypoetry/virtualenvs/litellm-ZzSyTc5A-py3.9/lib/python3.9/site-packages/openai/_base_client.py", line 884, in _request
    return self._retry_request(
  File "/home/huge/.cache/pypoetry/virtualenvs/litellm-ZzSyTc5A-py3.9/lib/python3.9/site-packages/openai/_base_client.py", line 956, in _retry_request
    return self._request(
  File "/home/huge/.cache/pypoetry/virtualenvs/litellm-ZzSyTc5A-py3.9/lib/python3.9/site-packages/openai/_base_client.py", line 898, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Error code: 500 - {'detail': 'The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable\n\nTraceback (most recent call last):\n  File "/home/huge/prog/litellm/litellm/utils.py", line 4501, in exception_type\n    request=original_exception.request\nAttributeError: \'OpenAIError\' object has no attribute \'request\'\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/home/huge/prog/litellm/litellm/proxy/proxy_server.py", line 1009, in chat_completion\n    response = await litellm.acompletion(**data)\n  File "/home/huge/prog/litellm/litellm/utils.py", line 1848, in wrapper_async\n    raise e\n  File "/home/huge/prog/litellm/litellm/utils.py", line 1779, in wrapper_async\n    result = await original_function(*args, **kwargs)\n  File "/home/huge/prog/litellm/litellm/main.py", line 204, in acompletion\n    raise exception_type(\n  File "/home/huge/prog/litellm/litellm/utils.py", line 5362, in exception_type\n    raise original_exception\n  File "/home/huge/prog/litellm/litellm/main.py", line 194, in acompletion\n    response = await init_response\n  File "/home/huge/prog/litellm/litellm/llms/openai.py", line 288, in acompletion\n    raise e\n  File "/home/huge/prog/litellm/litellm/llms/openai.py", line 269, in acompletion\n    openai_aclient = AsyncOpenAI(api_key=api_key, base_url=api_base, http_client=litellm.aclient_session, timeout=timeout, max_retries=max_retries)\n  File "/home/huge/.cache/pypoetry/virtualenvs/litellm-ZzSyTc5A-py3.9/lib/python3.9/site-packages/openai/_client.py", line 303, in __init__\n    raise OpenAIError(\nopenai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable\n'}
```
```


### Twitter / LinkedIn details

https://twitter.com/userhuge

**Comment by ghost** [comment]
@Huge this looks like the test call worked and the proxy server raised an error 

Can you share your config.yaml?

**Comment by Huge** [comment]
IIRC both raised some error, but the one shown here is from the `poetry run litellm --test` command, you should see it if you simply run ` poetry run litellm` in one shell and ` poetry run litellm --test` in another.

**Comment by ishaan-jaff** [comment]
In this case, the proxy was started without specifying a model in config or --model 

Seems like there are two scenarios:
- user passes a config.yaml, but it's missing api_key or api_base for azure 
- user does not set a model using --model
