### ISSUE TITLE
[Bug]: error importing litellm python 3.11 latest openai API

### ISSUE THREAD

**Issue by sid-swirl** [BerriAI/litellm#1215]
### What happened?

The below error occurs when I try to import completions. Mac OS/X, python 3.11, openai 

### Relevant log output

```shell
>>> from litellm import completion
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sid/Library/Python/3.11/lib/python/site-packages/litellm/__init__.py", line 314, in <module>
    from .utils import (
  File "/Users/sid/Library/Python/3.11/lib/python/site-packages/litellm/utils.py", line 42, in <module>
    from openai.openai_object import OpenAIObject
ModuleNotFoundError: No module named 'openai.openai_object'

% pip show openai | grep Version
Version: 1.5.0
```

**Comment by ghost** [comment]
hi @sid-swirl, this seems to be an older version of litellm (pre `1.x`).

Can you let me know if this persists with the latest version of the package

**Comment by sid-swirl** [comment]
That resolved it, thank you
