### ISSUE TITLE
[Bug]: Unable to run the given example for ollama/orca-mini

### ISSUE THREAD

**Issue by prateeksachan** [BerriAI/litellm#1217]
### What happened?

I was trying to add litellm integration for our users in my repo [https://github.com/bolna-ai/bolna](https://github.com/bolna-ai/bolna) and tried to test out the example given for `ollama/orca-mini` from https://docs.litellm.ai/docs/providers/ollama.

You may view the file here https://github.com/bolna-ai/bolna/pull/29/files. It's a simple file taken straight from the docs itself.

I've attached logs by setting `litellm.set_verbose = True`. Please let me know in case I'm missing something on my end. Thanks!

### Relevant log output

```shell
kwargs[caching]: False; litellm.cache: None

LiteLLM completion() model= orca-mini; provider = ollama

LiteLLM: Params passed to completion() {'functions': [], 'function_call': '', 'temperature': None, 'top_p': None, 'stream': True, 'max_tokens': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': None, 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': None, 'custom_llm_provider': 'ollama', 'model': 'orca-mini', 'n': None, 'stop': None}

LiteLLM: Non-Default params passed to completion() {'stream': True}
self.optional_params: {'stream': True}
PRE-API-CALL ADDITIONAL ARGS: {'api_base': 'http://localhost:11434/api/generate', 'complete_input_dict': {'model': 'orca-mini', 'prompt': 'respond in 20 words. who are you?', 'stream': True}, 'headers': {}, 'acompletion': False}


POST Request Sent from LiteLLM:
curl -X POST \
http://localhost:11434/api/generate \
-d '{'model': 'orca-mini', 'prompt': 'respond in 20 words. who are you?', 'stream': True}'


<litellm.utils.CustomStreamWrapper object at 0x105dbcc70>
value of chunk: {'role': 'assistant', 'content': ' I'} 
PROCESSED CHUNK PRE CHUNK CREATOR: {'role': 'assistant', 'content': ' I'}

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Logging Details: logger_fn - None | callable(logger_fn) - False
HITS AN ERROR: the JSON object must be str, bytes or bytearray, not dict

 Traceback (most recent call last):
  File "/Users/xan/.pyenv/versions/3.10.13/envs/bolna/lib/python3.10/site-packages/litellm/utils.py", line 5828, in chunk_creator
    response_obj = self.handle_ollama_stream(chunk)
  File "/Users/xan/.pyenv/versions/3.10.13/envs/bolna/lib/python3.10/site-packages/litellm/utils.py", line 5651, in handle_ollama_stream
    raise e
  File "/Users/xan/.pyenv/versions/3.10.13/envs/bolna/lib/python3.10/site-packages/litellm/utils.py", line 5632, in handle_ollama_stream
    json_chunk = json.loads(chunk)
  File "/Users/xan/.pyenv/versions/3.10.13/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xan/.pyenv/versions/3.10.13/envs/bolna/lib/python3.10/site-packages/litellm/utils.py", line 5932, in __next__
    response = self.chunk_creator(chunk=chunk)
  File "/Users/xan/.pyenv/versions/3.10.13/envs/bolna/lib/python3.10/site-packages/litellm/utils.py", line 5919, in chunk_creator
    raise exception_type(model=self.model, custom_llm_provider=self.custom_llm_provider, original_exception=e)
  File "/Users/xan/.pyenv/versions/3.10.13/envs/bolna/lib/python3.10/site-packages/litellm/utils.py", line 5192, in exception_type
    raise e
  File "/Users/xan/.pyenv/versions/3.10.13/envs/bolna/lib/python3.10/site-packages/litellm/utils.py", line 5169, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: the JSON object must be str, bytes or bytearray, not dict

Logging Details LiteLLM-Failure Call
Traceback (most recent call last):
  File "/Users/xan/.pyenv/versions/3.10.13/envs/bolna/lib/python3.10/site-packages/litellm/utils.py", line 5828, in chunk_creator
    response_obj = self.handle_ollama_stream(chunk)
  File "/Users/xan/.pyenv/versions/3.10.13/envs/bolna/lib/python3.10/site-packages/litellm/utils.py", line 5651, in handle_ollama_stream
    raise e
  File "/Users/xan/.pyenv/versions/3.10.13/envs/bolna/lib/python3.10/site-packages/litellm/utils.py", line 5632, in handle_ollama_stream
    json_chunk = json.loads(chunk)
  File "/Users/xan/.pyenv/versions/3.10.13/lib/python3.10/json/__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not dict

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xan/repos/bolna/demo.py", line 12, in <module>
    for chunk in response:
  File "/Users/xan/.pyenv/versions/3.10.13/envs/bolna/lib/python3.10/site-packages/litellm/utils.py", line 5946, in __next__
    raise e
  File "/Users/xan/.pyenv/versions/3.10.13/envs/bolna/lib/python3.10/site-packages/litellm/utils.py", line 5932, in __next__
    response = self.chunk_creator(chunk=chunk)
  File "/Users/xan/.pyenv/versions/3.10.13/envs/bolna/lib/python3.10/site-packages/litellm/utils.py", line 5919, in chunk_creator
    raise exception_type(model=self.model, custom_llm_provider=self.custom_llm_provider, original_exception=e)
  File "/Users/xan/.pyenv/versions/3.10.13/envs/bolna/lib/python3.10/site-packages/litellm/utils.py", line 5192, in exception_type
    raise e
  File "/Users/xan/.pyenv/versions/3.10.13/envs/bolna/lib/python3.10/site-packages/litellm/utils.py", line 5169, in exception_type
    raise APIConnectionError( 
litellm.exceptions.APIConnectionError: the JSON object must be str, bytes or bytearray, not dict

```

**Comment by ghost** [comment]
Hey @prateeksachan what're you seeing on the ollama server logs? is it showing a successful request

**Comment by ghost** [comment]
@prateeksachan i added a check if the chunk is a dict. this seems odd and i can't repro it when i run other ollama models (for testing i've been using mistral, openorca-mistral and phi). 

https://github.com/BerriAI/litellm/commit/f1270a7c782960c3029d2da1dac7bbf043de7755

Should be live soon in v`1.15.6`

**Comment by ghost** [comment]
Please feel free to re-open the issue if that doesn't solve it.

**Comment by prateeksachan** [comment]
Yes this should resolve it, I had manually added this check for now.

Thanks for fixing it @krrishdholakia
