### ISSUE TITLE
[Bug]: No module named 'proxy_server' 

### ISSUE THREAD

**Issue by iamashwin99** [BerriAI/litellm#1257]
### What happened?

When I run the models based on ollama provider, I get the following error:
```
❯  litellm --model ollama/mistral                                                                        
Traceback (most recent call last):                                                                       
  File "$PYENV/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 21, in <module>
    import orjson                                                                                        
ModuleNotFoundError: No module named 'orjson'                                                            
                                                                                                         
During handling of the above exception, another exception occurred:                                      
                                                                                                         
Traceback (most recent call last):                                                                       
  File "$PYENV/lib/python3.11/site-packages/litellm/proxy/proxy_cli.py", line 206, in run_server
    from .proxy_server import app, save_worker_config, usage_telemetry                                   
  File "$PYENV/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 23, in <module>
    raise ImportError(f"Missing dependency {e}. Run `pip install litellm[proxy]`")                       
ImportError: Missing dependency No module named 'orjson'. Run `pip install litellm[proxy]`               
                                                                                                         
During handling of the above exception, another exception occurred:                                      
                                                                                                         
Traceback (most recent call last):                                                                       
  File "$PYENV/bin/litellm", line 8, in <module>                          
    sys.exit(run_server())                                                                               
             ^^^^^^^^^^^^                                                                                
  File "$PYENV/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)                                                                    
           ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                    
  File "$PYENV/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)                                                                                
         ^^^^^^^^^^^^^^^^                                                                                
  File "$PYENV/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)                                                       
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                       
  File "$PYENV/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)                                                                   
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                   
  File "$PYENV/lib/python3.11/site-packages/litellm/proxy/proxy_cli.py", line 208, in run_server
    from proxy_server import app, save_worker_config, usage_telemetry                                    
ModuleNotFoundError: No module named 'proxy_server'       
```

This works fine when installing via ` pip install "litellm[proxy]==1.14.5"`

**Comment by ishaan-jaff** [comment]
@iamashwin99 it's asking you to `pip install litellm[proxy]` 

- did it work after running the pip install command ? 
- when your missing a dependency, what would be ideal behavior for you ?

**Comment by iamashwin99** [comment]
No, it didn't work even on installing with the recommended flavour:
```
❯ conda activate test-install
❯ pip install "litellm[proxy]"
Collecting litellm[proxy]
  Using cached litellm-1.15.10-py3-none-any.whl.metadata (11 kB)
Collecting aiohttp (from litellm[proxy])
  Using cached aiohttp-3.9.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.4 kB)
Collecting appdirs<2.0.0,>=1.4.4 (from litellm[proxy])
  Using cached appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting backoff (from litellm[proxy])
  Using cached backoff-2.2.1-py3-none-any.whl (15 kB)
Collecting certifi<2024.0.0,>=2023.7.22 (from litellm[proxy])
  Using cached certifi-2023.11.17-py3-none-any.whl.metadata (2.2 kB)
Collecting click (from litellm[proxy])
  Using cached click-8.1.7-py3-none-any.whl.metadata (3.0 kB)
Collecting fastapi<0.105.0,>=0.104.1 (from litellm[proxy])
  Using cached fastapi-0.104.1-py3-none-any.whl.metadata (24 kB)
Collecting importlib-metadata>=6.8.0 (from litellm[proxy])
  Using cached importlib_metadata-7.0.1-py3-none-any.whl.metadata (4.9 kB)
Collecting jinja2<4.0.0,>=3.1.2 (from litellm[proxy])
  Using cached Jinja2-3.1.2-py3-none-any.whl (133 kB)
Collecting openai>=1.0.0 (from litellm[proxy])
  Using cached openai-1.6.1-py3-none-any.whl.metadata (17 kB)
Collecting python-dotenv>=0.2.0 (from litellm[proxy])
  Using cached python_dotenv-1.0.0-py3-none-any.whl (19 kB)
Collecting rq (from litellm[proxy])
  Using cached rq-1.15.1-py2.py3-none-any.whl.metadata (1.6 kB)
Collecting tiktoken>=0.4.0 (from litellm[proxy])
  Using cached tiktoken-0.5.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.6 kB)
Collecting tokenizers (from litellm[proxy])
  Using cached tokenizers-0.15.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.7 kB)
Collecting uvicorn<0.25.0,>=0.24.0.post1 (from litellm[proxy])
  Using cached uvicorn-0.24.0.post1-py3-none-any.whl.metadata (6.4 kB)
Collecting anyio<4.0.0,>=3.7.1 (from fastapi<0.105.0,>=0.104.1->litellm[proxy])
  Using cached anyio-3.7.1-py3-none-any.whl.metadata (4.7 kB)
Collecting pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4 (from fastapi<0.105.0,>=0.104.1->litellm[proxy])
  Using cached pydantic-2.5.3-py3-none-any.whl.metadata (65 kB)
Collecting starlette<0.28.0,>=0.27.0 (from fastapi<0.105.0,>=0.104.1->litellm[proxy])
  Using cached starlette-0.27.0-py3-none-any.whl.metadata (5.8 kB)
Collecting typing-extensions>=4.8.0 (from fastapi<0.105.0,>=0.104.1->litellm[proxy])
  Using cached typing_extensions-4.9.0-py3-none-any.whl.metadata (3.0 kB)
Collecting zipp>=0.5 (from importlib-metadata>=6.8.0->litellm[proxy])
  Using cached zipp-3.17.0-py3-none-any.whl.metadata (3.7 kB)
Collecting MarkupSafe>=2.0 (from jinja2<4.0.0,>=3.1.2->litellm[proxy])
  Using cached MarkupSafe-2.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (3.0 kB)
Collecting distro<2,>=1.7.0 (from openai>=1.0.0->litellm[proxy])
  Using cached distro-1.9.0-py3-none-any.whl.metadata (6.8 kB)
Collecting httpx<1,>=0.23.0 (from openai>=1.0.0->litellm[proxy])
  Using cached httpx-0.26.0-py3-none-any.whl.metadata (7.6 kB)
Collecting sniffio (from openai>=1.0.0->litellm[proxy])
  Using cached sniffio-1.3.0-py3-none-any.whl (10 kB)
Requirement already satisfied: tqdm>4 in /home/karnada/.local/lib/python3.11/site-packages (from openai>=1.0.0->litellm[proxy]) (4.65.0)
Collecting regex>=2022.1.18 (from tiktoken>=0.4.0->litellm[proxy])
  Using cached regex-2023.12.25-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (40 kB)
Collecting requests>=2.26.0 (from tiktoken>=0.4.0->litellm[proxy])
  Using cached requests-2.31.0-py3-none-any.whl.metadata (4.6 kB)
Collecting h11>=0.8 (from uvicorn<0.25.0,>=0.24.0.post1->litellm[proxy])
  Using cached h11-0.14.0-py3-none-any.whl (58 kB)
Collecting attrs>=17.3.0 (from aiohttp->litellm[proxy])
  Using cached attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting multidict<7.0,>=4.5 (from aiohttp->litellm[proxy])
  Using cached multidict-6.0.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (117 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp->litellm[proxy])
  Using cached yarl-1.9.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (31 kB)
Collecting frozenlist>=1.1.1 (from aiohttp->litellm[proxy])
  Using cached frozenlist-1.4.1-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (12 kB)
Collecting aiosignal>=1.1.2 (from aiohttp->litellm[proxy])
  Using cached aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Collecting redis>=4.0.0 (from rq->litellm[proxy])
  Using cached redis-5.0.1-py3-none-any.whl.metadata (8.9 kB)
Collecting huggingface_hub<1.0,>=0.16.4 (from tokenizers->litellm[proxy])
  Using cached huggingface_hub-0.20.1-py3-none-any.whl.metadata (12 kB)
Collecting idna>=2.8 (from anyio<4.0.0,>=3.7.1->fastapi<0.105.0,>=0.104.1->litellm[proxy])
  Using cached idna-3.6-py3-none-any.whl.metadata (9.9 kB)
Collecting httpcore==1.* (from httpx<1,>=0.23.0->openai>=1.0.0->litellm[proxy])
  Using cached httpcore-1.0.2-py3-none-any.whl.metadata (20 kB)
Collecting filelock (from huggingface_hub<1.0,>=0.16.4->tokenizers->litellm[proxy])
  Using cached filelock-3.13.1-py3-none-any.whl.metadata (2.8 kB)
Collecting fsspec>=2023.5.0 (from huggingface_hub<1.0,>=0.16.4->tokenizers->litellm[proxy])
  Using cached fsspec-2023.12.2-py3-none-any.whl.metadata (6.8 kB)
Collecting pyyaml>=5.1 (from huggingface_hub<1.0,>=0.16.4->tokenizers->litellm[proxy])
  Using cached PyYAML-6.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (2.1 kB)
Collecting packaging>=20.9 (from huggingface_hub<1.0,>=0.16.4->tokenizers->litellm[proxy])
  Using cached packaging-23.2-py3-none-any.whl.metadata (3.2 kB)
Collecting annotated-types>=0.4.0 (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi<0.105.0,>=0.104.1->litellm[proxy])
  Using cached annotated_types-0.6.0-py3-none-any.whl.metadata (12 kB)
Collecting pydantic-core==2.14.6 (from pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,!=2.1.0,<3.0.0,>=1.7.4->fastapi<0.105.0,>=0.104.1->litellm[proxy])
  Using cached pydantic_core-2.14.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (6.5 kB)
Collecting charset-normalizer<4,>=2 (from requests>=2.26.0->tiktoken>=0.4.0->litellm[proxy])
  Using cached charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Collecting urllib3<3,>=1.21.1 (from requests>=2.26.0->tiktoken>=0.4.0->litellm[proxy])
  Using cached urllib3-2.1.0-py3-none-any.whl.metadata (6.4 kB)
Using cached certifi-2023.11.17-py3-none-any.whl (162 kB)
Using cached fastapi-0.104.1-py3-none-any.whl (92 kB)
Using cached importlib_metadata-7.0.1-py3-none-any.whl (23 kB)
Using cached openai-1.6.1-py3-none-any.whl (225 kB)
Using cached tiktoken-0.5.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.0 MB)
Using cached uvicorn-0.24.0.post1-py3-none-any.whl (59 kB)
Using cached click-8.1.7-py3-none-any.whl (97 kB)
Using cached aiohttp-3.9.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
Using cached litellm-1.15.10-py3-none-any.whl (1.6 MB)
Using cached rq-1.15.1-py2.py3-none-any.whl (95 kB)
Using cached tokenizers-0.15.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.8 MB)
Using cached anyio-3.7.1-py3-none-any.whl (80 kB)
Using cached distro-1.9.0-py3-none-any.whl (20 kB)
Using cached frozenlist-1.4.1-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (272 kB)
Using cached httpx-0.26.0-py3-none-any.whl (75 kB)
Using cached httpcore-1.0.2-py3-none-any.whl (76 kB)
Using cached huggingface_hub-0.20.1-py3-none-any.whl (330 kB)
Using cached MarkupSafe-2.1.3-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (28 kB)
Using cached pydantic-2.5.3-py3-none-any.whl (381 kB)
Using cached pydantic_core-2.14.6-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.1 MB)
Using cached redis-5.0.1-py3-none-any.whl (250 kB)
Using cached regex-2023.12.25-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (785 kB)
Using cached requests-2.31.0-py3-none-any.whl (62 kB)
Using cached starlette-0.27.0-py3-none-any.whl (66 kB)
Using cached typing_extensions-4.9.0-py3-none-any.whl (32 kB)
Using cached yarl-1.9.4-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (328 kB)
Using cached zipp-3.17.0-py3-none-any.whl (7.4 kB)
Using cached annotated_types-0.6.0-py3-none-any.whl (12 kB)
Using cached charset_normalizer-3.3.2-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (140 kB)
Using cached fsspec-2023.12.2-py3-none-any.whl (168 kB)
Using cached idna-3.6-py3-none-any.whl (61 kB)
Using cached packaging-23.2-py3-none-any.whl (53 kB)
Using cached PyYAML-6.0.1-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (757 kB)
Using cached urllib3-2.1.0-py3-none-any.whl (104 kB)
Using cached filelock-3.13.1-py3-none-any.whl (11 kB)
Installing collected packages: appdirs, zipp, urllib3, typing-extensions, sniffio, regex, redis, pyyaml, python-dotenv, packaging, multidict, MarkupSafe, idna, h11, fsspec, frozenlist, filelock, distro, click, charset-normalizer, certifi, backoff, attrs, annotated-types, yarl, uvicorn, rq, requests, pydantic-core, jinja2, importlib-metadata, httpcore, anyio, aiosignal, tiktoken, starlette, pydantic, huggingface_hub, httpx, aiohttp, tokenizers, openai, fastapi, litellm
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pipx 1.2.0 requires argcomplete>=1.9.4, which is not installed.
Successfully installed MarkupSafe-2.1.3 aiohttp-3.9.1 aiosignal-1.3.1 annotated-types-0.6.0 anyio-3.7.1 appdirs-1.4.4 attrs-23.1.0 backoff-2.2.1 certifi-2023.11.17 charset-normalizer-3.3.2 click-8.1.7 distro-1.9.0 fastapi-0.104.1 filelock-3.13.1 frozenlist-1.4.1 fsspec-2023.12.2 h11-0.14.0 httpcore-1.0.2 httpx-0.26.0 huggingface_hub-0.20.1 idna-3.6 importlib-metadata-7.0.1 jinja2-3.1.2 litellm-1.15.10 multidict-6.0.4 openai-1.6.1 packaging-23.2 pydantic-2.5.3 pydantic-core-2.14.6 python-dotenv-1.0.0 pyyaml-6.0.1 redis-5.0.1 regex-2023.12.25 requests-2.31.0 rq-1.15.1 sniffio-1.3.0 starlette-0.27.0 tiktoken-0.5.2 tokenizers-0.15.0 typing-extensions-4.9.0 urllib3-2.1.0 uvicorn-0.24.0.post1 yarl-1.9.4 zipp-3.17.0
❯ litellm --model ollama/mistral
Traceback (most recent call last):
  File "$PYENV/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 21, in <module>
    import orjson
ModuleNotFoundError: No module named 'orjson'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$PYENV/lib/python3.11/site-packages/litellm/proxy/proxy_cli.py", line 206, in run_server
    from .proxy_server import app, save_worker_config, usage_telemetry
  File "$PYENV/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 23, in <module>
    raise ImportError(f"Missing dependency {e}. Run `pip install litellm[proxy]`")
ImportError: Missing dependency No module named 'orjson'. Run `pip install litellm[proxy]`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "$PYENV/bin/litellm", line 8, in <module>
    sys.exit(run_server())
             ^^^^^^^^^^^^
  File "$PYENV/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$PYENV/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "$PYENV/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$PYENV/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "$PYENV/lib/python3.11/site-packages/litellm/proxy/proxy_cli.py", line 208, in run_server
    from proxy_server import app, save_worker_config, usage_telemetry
ModuleNotFoundError: No module named 'proxy_server'


```

**Comment by bitnom** [comment]
I have confirmed this bug. If you want to reproduce it:

- Deploy a free render.com instance by pointing it to the litellm repo (Or just use `pip3 install litellm[proxy]` I think causes same behavior but easier to clone main repo than make a new one just for the test)
- Set environment variable `PYTHON_VERSION` to `3.8.18`
- Build command: `python3 -m venv .venv && source .venv/bin/activate && pip3 install --upgrade pip && pip3 install '.[proxy]'`
- Start command: `source .venv/bin/activate && litellm --config config.yaml`

---

### Temporary solution

Add to build command: `pip3 install uvicorn fastapi backoff pyyaml rq orjson importlib`

### Note

Oddly, this does not occur locally for me, even with the same Python version and a fresh venv.

**Comment by ishaan-jaff** [comment]
I was able to repro this issue @bitnom @iamashwin99 
Fixed here: https://github.com/BerriAI/litellm/commit/a7305150960dfe3b03784402c3ef35f62ba9b49e 

I've queued a new deploy, thanks for helping me debug this ! 

Would love to give you a shoutout in our daily changelog, what's your linkedin/twitter ?

**Comment by ishaan-jaff** [comment]
in prod - can you try:

`python3 -m pip install 'litellm[proxy]' -U` 

@bitnom @iamashwin99 ?

**Comment by bitnom** [comment]
> I was able to repro this issue @bitnom @iamashwin99 Fixed here: [a730515](https://github.com/BerriAI/litellm/commit/a7305150960dfe3b03784402c3ef35f62ba9b49e)
> 
> I've queued a new deploy, thanks for helping me debug this !
> 
> Would love to give you a shoutout in our daily changelog, what's your linkedin/twitter ?

thanks but I don't use either.  github if anything



> in prod - can you try:
> 
> `python3 -m pip install 'litellm[proxy]' -U`
> 
> @bitnom @iamashwin99 ?

seems to be working, thanks. I doubt the -U was necessary, and actually (Unless I'm misremembering) I think you're not supposed to use it on render, though in this case it didn't hurt.

**Comment by ishaan-jaff** [comment]
closing this issue thanks for the help @bitnom @iamashwin99 

feel free to re-open if it's not solved

**Comment by akashAD98** [comment]
https://github.com/BerriAI/litellm/issues/1662

i am facing the same issue 

```
ModuleNotFoundError: No module named 'proxy_server'
```

**Comment by HarshitSahu8** [comment]
> pip3 install uvicorn fastapi backoff pyyaml rq orjson importlib

pip install jwt

**Comment by FD01143** [comment]
facing same issue

**Comment by Yaoyao202098** [comment]
> ### What happened?
> When I run the models based on ollama provider, I get the following error:
> 
> ```
> ❯  litellm --model ollama/mistral                                                                        
> Traceback (most recent call last):                                                                       
>   File "$PYENV/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 21, in <module>
>     import orjson                                                                                        
> ModuleNotFoundError: No module named 'orjson'                                                            
>                                                                                                          
> During handling of the above exception, another exception occurred:                                      
>                                                                                                          
> Traceback (most recent call last):                                                                       
>   File "$PYENV/lib/python3.11/site-packages/litellm/proxy/proxy_cli.py", line 206, in run_server
>     from .proxy_server import app, save_worker_config, usage_telemetry                                   
>   File "$PYENV/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 23, in <module>
>     raise ImportError(f"Missing dependency {e}. Run `pip install litellm[proxy]`")                       
> ImportError: Missing dependency No module named 'orjson'. Run `pip install litellm[proxy]`               
>                                                                                                          
> During handling of the above exception, another exception occurred:                                      
>                                                                                                          
> Traceback (most recent call last):                                                                       
>   File "$PYENV/bin/litellm", line 8, in <module>                          
>     sys.exit(run_server())                                                                               
>              ^^^^^^^^^^^^                                                                                
>   File "$PYENV/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
>     return self.main(*args, **kwargs)                                                                    
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                    
>   File "$PYENV/lib/python3.11/site-packages/click/core.py", line 1078, in main
>     rv = self.invoke(ctx)                                                                                
>          ^^^^^^^^^^^^^^^^                                                                                
>   File "$PYENV/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
>     return ctx.invoke(self.callback, **ctx.params)                                                       
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                       
>   File "$PYENV/lib/python3.11/site-packages/click/core.py", line 783, in invoke
>     return __callback(*args, **kwargs)                                                                   
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                   
>   File "$PYENV/lib/python3.11/site-packages/litellm/proxy/proxy_cli.py", line 208, in run_server
>     from proxy_server import app, save_worker_config, usage_telemetry                                    
> ModuleNotFoundError: No module named 'proxy_server'       
> ```
> 
> This works fine when installing via ` pip install "litellm[proxy]==1.14.5"`
> 
> ### Relevant log output
> _No response_
> 
> ### Twitter / LinkedIn details
> _No response_



> pip install "litellm[proxy]"

Pls how to fix it

**Comment by JanbertCampos** [comment]
same problem i run it in windows
