### ISSUE TITLE
Open-interpreter error message points here

### ISSUE THREAD

**Issue by InTEGr8or** [BerriAI/litellm#1259]
When I run open-interpreter, I get an error message directing me here.

```
> hello                                                                                                     Give Feedback/Get Help: https://github.com/BerriAI/litellm/issues/new                                     LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Python Version: 3.11.6                                Pip Version: 23.3.2                                   Open-interpreter Version: cmd:Interpreter, pkg: 0.1.17                                                      OS Version and Architecture: Linux-5.15.94-android13-8-27763874-abS918USQS2BWKA-aarch64-with-libc           CPU Info:                                             RAM Info: 10.77 GB, used: 7.17, free: 0.23                                                                                                                        Interpreter Info                                      Vision: False                                         Model: gpt-4                                          Function calling: True                                Context window: None                                  Max tokens: None                                                                                            Auto run: False                                       API base: None                                        Local: False                                                                                                Curl output: Not local                                                                                                                                    Traceback (most recent call last):                      File "/data/data/com.termux/files/home/.venv/bin/interpreter", line 8, in <module>                            sys.exit(start_terminal_interface())                           ^^^^^^^^^^^^^^^^^^^^^^^^^^                 File "/data/data/com.termux/files/home/.venv/lib/python3.11/site-packages/interpreter/core/core.py", line 21, in start_terminal_interface                           start_terminal_interface(self)                      File "/data/data/com.termux/files/home/.venv/lib/python3.11/site-packages/interpreter/terminal_interface/start_terminal_interface.py", line 304, in start_terminal_interface                                              interpreter.chat()
```

**Comment by InTEGr8or** [comment]
I don't know why GitHub is not displaying that whole message, but if you use the copy button it will copy the whole message to your clipboard.

**Comment by ghost** [comment]
looks like no api base was passed in. I think this is probably a better issue for the openinterpreter github - https://github.com/KillianLucas/open-interpreter/
