### ISSUE TITLE
[Feature]: /key/generate - unable to pass model = null on requests 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1325]
### The Feature

docs say this request should work

```
curl 'http://0.0.0.0:8000/key/generate' \
--header 'Authorization: Bearer sk-1234' \
--header 'Content-Type: application/json' \
--data-raw '{"models": null, "duration": "20m","metadata": {"user": "ishaan@berri.ai", "team": "core-infra"}}'
```

### Motivation, pitch

stacktrace
```
LiteLLM Proxy: Backing off... this was attempt #1
LiteLLM Proxy: Backing off... this was attempt #2
Traceback (most recent call last):
  File "/Users/ishaanjaffer/Github/litellm/litellm/proxy/proxy_server.py", line 899, in generate_key_helper_fn
    new_verification_token = await prisma_client.insert_data(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/Users/ishaanjaffer/Github/litellm/litellm/proxy/utils.py", line 456, in insert_data
    raise e
  File "/Users/ishaanjaffer/Github/litellm/litellm/proxy/utils.py", line 406, in insert_data
    new_verification_token = await self.db.litellm_verificationtoken.upsert(  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/prisma/actions.py", line 1735, in upsert
    resp = await self._client._execute(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/prisma/client.py", line 489, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_response_errors(resp, errors_data)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/prisma/engine/utils.py", line 180, in handle_response_errors
    raise prisma_errors.MissingRequiredValueError(error)
prisma.errors.MissingRequiredValueError: Unable to match input value to any allowed input type for the field. Parse errors: [Unable to match input value to any allowed input type for the field. Parse errors: [`create.models`: A value is required but not set, `create.models`: A value is required but not set], Unable to match input value to any allowed input type for the field. Parse errors: [`create.models`: A value is required but not set, `create.models`: A value is required but not set]]
```

**Comment by ishaan-jaff** [comment]
user faced this issue too

**Comment by ghost** [comment]
I believe we expect it to be an empty list
