### ISSUE TITLE
[Bug]: Google Gemini Vision not working as expected - Google AI Studio

### ISSUE THREAD

**Issue by haseeb-heaven** [BerriAI/litellm#1329]
### What happened?

Google Gemini Pro Vision not working as expected saying ** Add an image to use models/gemini-pro-vision**

Python code:
```python
import os
import litellm
from dotenv import load_dotenv

def setup_gemini():
    try:
        load_dotenv()
        gemini_api_key = os.getenv('GEMINI_API_KEY')
        if gemini_api_key is None:
            raise Exception("GEMINI_API_KEY is not set")
        os.environ["GEMINI_API_KEY"] = gemini_api_key
    except Exception as exception:
        raise Exception("An error occurred during setup:", exception)

def generate_text(prompt, image_url):
    try:
        messages = [
            {
                "role": "user",
                "content": [
                    {
                        "type": "text",
                        "text": prompt
                    },
                    {
                        "type": "image_url",
                        "image_url": {
                            "url": image_url
                        }
                    }
                ]
            }
        ]
        response = litellm.completion(model="gemini/gemini-pro-vision", messages=messages)
        return response.text
    except Exception as exception:
        raise Exception("An error occurred during text generation:", exception)

if __name__ == "__main__":
    try:
        print("Gemini Vision Demo")
        setup_gemini()
        image_url = input("Enter the image URL: ")
        prompt = input("Enter the text prompt: ")
        response = generate_text(prompt, image_url)
        print(response)
    except Exception as exception:
        print(f"An error occurred: {exception}")
```

- Output:
```
python GeminiVisionDemo.py
Gemini Vision Demo
Enter the image URL: https://i.pinimg.com/originals/a9/9e/34/a99e34c48753fa2cf4dc04a6b01f746d.jpg
Enter the text prompt: what is this image

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

An error occurred: ('An error occurred during text generation:', APIConnectionError('400 Add an image to use models/gemini-pro-vision, or switch your model to a text model.'))
```

- LiteLLM Package version:
```
Name: litellm
Version: 1.16.12
Summary: Library to easily interface with LLM API providers
Home-page: 
Author: BerriAI
Author-email: 
License: MIT
Location: /opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages
Requires: aiohttp, certifi, click, importlib-metadata, jinja2, openai, python-dotenv, tiktoken, tokenizers
Required-by: 
```

### Relevant log output

```shell
python GeminiVisionDemo.py
Gemini Vision Demo
Enter the image URL: https://storage.googleapis.com/github-repo/img/gemini/intro/landmark3.jpg
Enter the text prompt: What is this image?
kwargs[caching]: False; litellm.cache: None

LiteLLM completion() model= gemini-pro-vision; provider = gemini

LiteLLM: Params passed to completion() {'functions': None, 'function_call': None, 'temperature': None, 'top_p': None, 'stream': None, 'max_tokens': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': None, 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': None, 'logprobs': None, 'top_logprobs': None, 'custom_llm_provider': 'gemini', 'model': 'gemini-pro-vision', 'n': None, 'stop': None}

LiteLLM: Non-Default params passed to completion() {}
self.optional_params: {}
PRE-API-CALL ADDITIONAL ARGS: {'complete_input_dict': {'inference_params': {}}}
{'model': 'gemini-pro-vision', 'messages': [{'role': 'user', 'content': [{'type': 'text', 'text': 'What is this image?'}, {'type': 'image_url', 'image_url': {'url': 'https://storage.googleapis.com/github-repo/img/gemini/intro/landmark3.jpg'}}]}], 'optional_params': {}, 'litellm_params': {'acompletion': False, 'api_key': None, 'force_timeout': 600, 'logger_fn': None, 'verbose': False, 'custom_llm_provider': 'gemini', 'api_base': None, 'litellm_call_id': '51942a02-50ff-43d6-a435-41f079153213', 'model_alias_map': {}, 'completion_call_id': None, 'metadata': None, 'model_info': None, 'proxy_server_request': None, 'preset_cache_key': None, 'stream_response': {}}, 'start_time': datetime.datetime(2024, 1, 5, 3, 22, 27, 918151), 'stream': False, 'user': None, 'call_type': 'completion', 'input': ['What is this image?', 'https://storage.googleapis.com/github-repo/img/gemini/intro/landmark3.jpg'], 'api_key': '', 'additional_args': {'complete_input_dict': {'inference_params': {}}}, 'log_event_type': 'pre_api_call'}


Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
self.failure_callback: []
An error occurred: ('An error occurred during text generation:', APIConnectionError('400 Add an image to use models/gemini-pro-vision, or switch your model to a text model.'))
```
```


### Twitter / LinkedIn details

haseeb_heaven

**Comment by haseeb-heaven** [comment]
You forgot to add `_gemini_vision_convert_messages` method in *Gemini.py* so its not parsing the images from URL.
@krrishdholakia @ishaan-jaff

**Comment by ghost** [comment]
@haseeb-heaven acknowledging the issue, will repro and push a fix

**Comment by ghost** [comment]
Hey @haseeb-heaven just pushed a fix - https://github.com/BerriAI/litellm/commit/5fd2f945f330cbd2f066773b1431dee669f7a510

should be live soon in v`1.16.16`

**Comment by haseeb-heaven** [comment]
Thanks for this

**Comment by haseeb-heaven** [comment]
@krrishdholakia I am still getting error in version `1.16.16`

```python
Python % python GeminiVisionDemo.py
Gemini Vision Demo
Image (Url): https://theromanguy.com/italy-travel-blog/wp-content/uploads/acecba0e05c03897646ce41c254b48b6-3-e1608783354656.jpg
Prompt: Where is this place?
kwargs[caching]: False; litellm.cache: None

LiteLLM completion() model= gemini-pro-vision; provider = gemini

LiteLLM: Params passed to completion() {'functions': None, 'function_call': None, 'temperature': None, 'top_p': None, 'stream': None, 'max_tokens': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': None, 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': None, 'logprobs': None, 'top_logprobs': None, 'custom_llm_provider': 'gemini', 'model': 'gemini-pro-vision', 'n': None, 'stop': None}

LiteLLM: Non-Default params passed to completion() {}
self.optional_params: {}
PRE-API-CALL ADDITIONAL ARGS: {'complete_input_dict': {'inference_params': {}}}
{'model': 'gemini-pro-vision', 'messages': [{'role': 'user', 'content': [{'type': 'text', 'text': 'Where is this place?'}, {'type': 'image_url', 'image_url': {'url': 'https://theromanguy.com/italy-travel-blog/wp-content/uploads/acecba0e05c03897646ce41c254b48b6-3-e1608783354656.jpg'}}]}], 'optional_params': {}, 'litellm_params': {'acompletion': False, 'api_key': None, 'force_timeout': 600, 'logger_fn': None, 'verbose': False, 'custom_llm_provider': 'gemini', 'api_base': None, 'litellm_call_id': '345d9bdb-4e6c-4800-8b1b-9f3556820a2b', 'model_alias_map': {}, 'completion_call_id': None, 'metadata': None, 'model_info': None, 'proxy_server_request': None, 'preset_cache_key': None, 'stream_response': {}}, 'start_time': datetime.datetime(2024, 1, 8, 5, 4, 18, 541000), 'stream': False, 'user': None, 'call_type': 'completion', 'input': ['Where is this place?', <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=260x315 at 0x10C6874F0>], 'api_key': '', 'additional_args': {'complete_input_dict': {'inference_params': {}}}, 'log_event_type': 'pre_api_call'}

RAW RESPONSE:
<google.generativeai.types.generation_types.GenerateContentResponse object at 0x10c6bedd0>


Logging Details Post-API Call: logger_fn - None | callable(logger_fn) - False
Logging Details Post-API Call: LiteLLM Params: {'model': 'gemini-pro-vision', 'messages': [{'role': 'user', 'content': [{'type': 'text', 'text': 'Where is this place?'}, {'type': 'image_url', 'image_url': {'url': 'https://theromanguy.com/italy-travel-blog/wp-content/uploads/acecba0e05c03897646ce41c254b48b6-3-e1608783354656.jpg'}}]}], 'optional_params': {}, 'litellm_params': {'acompletion': False, 'api_key': None, 'force_timeout': 600, 'logger_fn': None, 'verbose': False, 'custom_llm_provider': 'gemini', 'api_base': None, 'litellm_call_id': '345d9bdb-4e6c-4800-8b1b-9f3556820a2b', 'model_alias_map': {}, 'completion_call_id': None, 'metadata': None, 'model_info': None, 'proxy_server_request': None, 'preset_cache_key': None, 'stream_response': {}}, 'start_time': datetime.datetime(2024, 1, 8, 5, 4, 18, 541000), 'stream': False, 'user': None, 'call_type': 'completion', 'input': ['Where is this place?', <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=260x315 at 0x10C6874F0>], 'api_key': '', 'additional_args': {'complete_input_dict': {}}, 'log_event_type': 'post_api_call', 'original_response': <google.generativeai.types.generation_types.GenerateContentResponse object at 0x10c6bedd0>}
raw model_response: <google.generativeai.types.generation_types.GenerateContentResponse object at 0x10c6bedd0>
Wrapper: Completed Call, calling success_handler
Logging Details LiteLLM-Success Call
An error occurred: ('An error occurred during text generation:', AttributeError("'ModelResponse' object has no attribute 'text'"))
success callbacks: []

```

- LiteLLM Version:
```python
 pip show litellm
Name: litellm
Version: 1.16.16
Summary: Library to easily interface with LLM API providers
Home-page: 
Author: BerriAI
Author-email: 
License: MIT
Location: /opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages
Requires: aiohttp, certifi, click, importlib-metadata, jinja2, openai, python-dotenv, tiktoken, tokenizers
Required-by: 
```

- Stacktrace

```python
Gemini Vision Demo

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/litellm/main.py", line 1301, in completion
    model_response = gemini.completion(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/litellm/llms/gemini.py", line 198, in completion
    encoding.encode(model_response["choices"][0]["message"].get("content", ""))
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/tiktoken/core.py", line 116, in encode
    if match := _special_token_regex(disallowed_special).search(text):
TypeError: expected string or buffer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/haseeb-mir/Documents/Code/Python/GeminiVisionDemo.py", line 46, in <module>
    response = generate_text(prompt, image_url)
  File "/Users/haseeb-mir/Documents/Code/Python/GeminiVisionDemo.py", line 34, in generate_text
    response = litellm.completion(model="gemini/gemini-pro-vision", messages=messages)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/litellm/utils.py", line 2118, in wrapper
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/litellm/utils.py", line 2025, in wrapper
    result = original_function(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/litellm/main.py", line 1744, in completion
    raise exception_type(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/litellm/utils.py", line 6570, in exception_type
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/litellm/utils.py", line 6545, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: expected string or buffer
An error occurred: expected string or buffer
```

**Comment by ghost** [comment]
@haseeb-heaven that's a bug in your code: 

you have: 
```
return response.text
```

It should be 
```
response['choices'][0]['message']['content']
```

The error raised was b/c the content was being flagged by google (found during local repro). I pushed some updates to raise the exception better. Should be riding v`1.16.17`

**Comment by haseeb-heaven** [comment]
> @haseeb-heaven that's a bug in your code:
> 
> you have:
> 
> ```
> return response.text
> ```
> 
> It should be
> 
> ```
> response['choices'][0]['message']['content']
> ```
> 
> The error raised was b/c the content was being flagged by google (found during local repro). I pushed some updates to raise the exception better. Should be riding v`1.16.17`

Even i dont return anything its still giving me error.

See the StackTrace.

```python
Traceback (most recent call last):
  File "/Users/haseeb-mir/Documents/Code/Python/GeminiVisionDemo.py", line 47, in <module>
    response = generate_text(prompt, image_url)
  File "/Users/haseeb-mir/Documents/Code/Python/GeminiVisionDemo.py", line 35, in generate_text
    response = litellm.completion(model="gemini/gemini-pro-vision", messages=messages)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/litellm/utils.py", line 2118, in wrapper
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/litellm/utils.py", line 2025, in wrapper
    result = original_function(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/litellm/main.py", line 1744, in completion
    raise exception_type(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/litellm/utils.py", line 6570, in exception_type
    raise e
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/litellm/utils.py", line 6545, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: expected string or buffer
An error occurred: expected string or buffer
```

**Comment by ghost** [comment]
yes, see:

> The error raised was b/c the content was being flagged by google (found during local repro). I pushed some updates to raise the exception better. Should be riding v1.16.17

**Comment by haseeb-heaven** [comment]
> yes, see:
> 
> > The error raised was b/c the content was being flagged by google (found during local repro). I pushed some updates to raise the exception better. Should be riding v1.16.17

Its working for ```https://i.pinimg.com/736x/fb/b7/24/fbb7242470f27c41d3d39d90e641d4dd.jpg``` this image now and handle safety settings for Vision.

And there should be multiple type to upload image.

- Url
- Local storage
- Online storage

Add these features as well

**Comment by haseeb-heaven** [comment]
@krrishdholakia Checkout this [FR for Gemini](https://github.com/BerriAI/litellm/issues/1357) to implement multiple modes for image upload.

**Comment by ghost** [comment]
@haseeb-heaven we already support passing images via URL + local storage for gemini ai studio. 

The missing one is blob, but i don't any code examples of how blob data is processed / passed for ai studio. 

Can you point me to a relevant code example on this?

**Comment by ghost** [comment]
Closing this ticket as I believe the initial issue raised is now fixed.
