### ISSUE TITLE
[Bug]: Consecutive calls failing after 6hrs+ of high-load 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1360]
### What happened?

We ran a 1k request/min. load test on our hosted proxy endpoint. After 6hrs+ we start seeing consecutive requests failing due to timeout errors 

![image](https://github.com/BerriAI/litellm/assets/17561003/fbe74f93-828a-4849-9e87-e7f14162668b)

I think this is related to - https://github.com/BerriAI/litellm/issues/1278

### Relevant log output

```shell
await self._anyio_event.wait()

File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1641, in wait

await self._event.wait()

File "/usr/local/lib/python3.9/asyncio/locks.py", line 226, in wait

await fut

asyncio.exceptions.CancelledError: Cancelled by cancel scope 7febd4623d90

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions

yield

File "/usr/local/lib/python3.9/site-packages/httpcore/_synchronization.py", line 123, in wait

await self._anyio_event.wait()

File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__

self.gen.throw(typ, value, traceback)

File "/usr/local/lib/python3.9/site-packages/anyio/_core/_tasks.py", line 118, in fail_after

raise TimeoutError

TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions

yield

File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 366, in handle_async_request

resp = await self._pool.handle_async_request(req)

File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 248, in handle_async_request

raise exc

File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 239, in handle_async_request

connection = await status.wait_for_connection(timeout=timeout)

File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 36, in wait_for_connection

await self._connection_acquired.wait(timeout=timeout)

File "/usr/local/lib/python3.9/site-packages/httpcore/_synchronization.py", line 123, in wait

await self._anyio_event.wait()

File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__

self.gen.throw(typ, value, traceback)

File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions

raise to_exc(exc) from exc

httpcore.PoolTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1339, in _request

response = await self._client.send(

File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1617, in send

response = await self._send_handling_auth(

File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1645, in _send_handling_auth

response = await self._send_handling_redirects(

File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects

response = await self._send_single_request(request)

File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1719, in _send_single_request

response = await transport.handle_async_request(request)

File "/usr/local/lib/python3.9/site-packages/litellm/llms/custom_httpx/azure_dall_e_2.py", line 66, in handle_async_request

return await super().handle_async_request(request)

File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 366, in handle_async_request

resp = await self._pool.handle_async_request(req)

File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__

self.gen.throw(typ, value, traceback)

File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions

raise mapped_exc(message) from exc

httpx.PoolTimeout

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2244, in wrapper_async

result = await original_function(*args, **kwargs)

File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 210, in acompletion

response = await init_response

File "/usr/local/lib/python3.9/site-packages/litellm/llms/azure.py", line 322, in acompletion

response = await azure_client.chat.completions.create(
```

**Comment by ghost** [comment]
It looks like requests hang and then openai raises timeout errors @ishaan-jaff 

```
File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1617, in send

response = await self._send_handling_auth(

File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1645, in _send_handling_auth

response = await self._send_handling_redirects(

File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects

response = await self._send_single_request(request)

File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1719, in _send_single_request

response = await transport.handle_async_request(request)

File "/usr/local/lib/python3.9/site-packages/litellm/llms/custom_httpx/azure_dall_e_2.py", line 66, in handle_async_request

return await super().handle_async_request(request)

File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 366, in handle_async_request

resp = await self._pool.handle_async_request(req)

File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__

self.gen.throw(typ, value, traceback)

File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions

raise mapped_exc(message) from exc

httpx.PoolTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/litellm/llms/azure.py", line 322, in acompletion

response = await azure_client.chat.completions.create(

File "/usr/local/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 1295, in create

return await self._post(

File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1536, in post

return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)

File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1315, in request

return await self._request(

File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1346, in _request

return await self._retry_request(

File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1418, in _retry_request

return await self._request(

File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1346, in _request

return await self._retry_request(

File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1418, in _retry_request

return await self._request(

File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1355, in _request

raise APITimeoutError(request=request) from err

openai.APITimeoutError: Request timed out.

```

**Comment by ghost** [comment]
I see: 
```
File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions

raise mapped_exc(message) from exc

httpx.PoolTimeout
```

which means there's not enough connections. Going to try the openai recommended approach of increasing the default limits

```
http_client=httpx.Client(
    limits=httpx.Limits(
      max_connections=1000,
      max_keepalive_connections=100
    )
  )
```
https://github.com/openai/openai-python/issues/874#issuecomment-1824966775

**Comment by ghost** [comment]
Just pushed the pool limit fix - https://github.com/BerriAI/litellm/commit/ec83243521a9d18ea597524fb248573b05f57e42

Will run a load test on updated proxy.

**Comment by ghost** [comment]
Resumed load test

**Comment by ghost** [comment]
Looks like the server (1 replica) just got overwhelmed and shut down 2 hrs ago. 

Increasing num replicas to 3

**Comment by ghost** [comment]
A big blocker for me right now is the way we handle `/model/new` -> this updates the local config.yaml, but that breaks when you have >1 replica, since only 1 will actually have the new model. 

This then noisy alerting b/c calls are failing when they shouldn't need to 

cc: @ishaan-jaff

**Comment by ghost** [comment]
I think bumping the pool limits did actually solve it 

cc: @ishaan-jaff 

Ran the 1k queries / min. load test overnight and have 0 dropped requests

**Comment by ghost** [comment]
Pending work - rollout the bumped limits for all clients

**Comment by ghost** [comment]
this is now fixed and in prod
