### ISSUE TITLE
[Bug]: Self-serve UI, AUTH link generation error

### ISSUE THREAD

**Issue by speedyankur** [BerriAI/litellm#1383]
### What happened?

https://dashboard.litellm.ai/admin

on click of SAVE button we get a following error 

### Relevant log output

```shell
Traceback (most recent call last):
  File "/.pyenv/versions/3.10.13/envs/searchgpt/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 534, in _run_script
    exec(code, module.__dict__)
  File "/itellm/ui/admin.py", line 374, in <module>
    admin_page()
  File "/litellm/ui/admin.py", line 365, in admin_page
    proxy_setup()
  File "/litellm/ui/admin.py", line 55, in proxy_setup
    update_config(
TypeError: update_config() got an unexpected keyword argument 'proxy_url'
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/speedyankur/

**Comment by speedyankur** [comment]
<img width="761" alt="Screenshot 2024-01-09 at 13 30 07" src="https://github.com/BerriAI/litellm/assets/1248020/88426f56-99d0-4e6e-abe7-5656c9556c21">

**Comment by speedyankur** [comment]
I fixed it, @krrishdholakia  @ishaan-jaff  

please review https://github.com/BerriAI/litellm/pull/1385

**Comment by ghost** [comment]
Merged @speedyankur let me know if this solves your problem 

Thanks for the quick fix
