### ISSUE TITLE
[Bug]: Error message on start windows 11

### ISSUE THREAD

**Issue by aidanbha79** [BerriAI/litellm#1424]
### What happened?

when I try and run the command to start litellm in the terminal I get this output.

`C:\Users\aidan> litellm --model huggingface/bigcode/starcoder
Traceback (most recent call last):
  File "C:\Users\aidan\AppData\Roaming\Python\Python312\site-packages\litellm\proxy\proxy_cli.py", line 346, in run_server
    import gunicorn.app.base
  File "C:\Python312\Lib\site-packages\gunicorn\app\base.py", line 11, in <module>
    from gunicorn import util
  File "C:\Python312\Lib\site-packages\gunicorn\util.py", line 8, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\aidan\AppData\Roaming\Python\Python312\Scripts\litellm.exe\__main__.py", line 7, in <module>
  File "C:\Users\aidan\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\aidan\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan\AppData\Roaming\Python\Python312\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aidan\AppData\Roaming\Python\Python312\site-packages\litellm\proxy\proxy_cli.py", line 348, in run_server
    raise ImportError(
ImportError: Uvicorn, gunicorn needs to be imported. Run - `pip 'litellm[proxy]'``

**Comment by ghost** [comment]
Did you run 

```
pip install 'litellm[proxy]'
```

Seems like that's what it's saying you need to do

**Comment by kaonick** [comment]
me too.(same error)

**Comment by simonstey** [comment]
this seems to be an [issue with gunicorn itself, which doesnt run on Windows ](https://stackoverflow.com/questions/62788628/modulenotfounderror-no-module-named-fcntl)

**Comment by ghost** [comment]
@simonstey thanks for catching this. 

Ok, so it seems like the change to use gunicorn might be wrong for the default proxy

Will fix

**Comment by aidanbha79** [comment]
Hi I did run the litellm[proxy] command to install.

**Comment by ghost** [comment]
@aidanbha79 should be fixed with #1425 , i'll update this ticket once a release is out

**Comment by ghost** [comment]
This is now live in v`1.17.4`. 

Can you let me know if this solves your problem? @aidanbha79

**Comment by aidanbha79** [comment]
That works perfectly thank you.

**Comment by ishaan-jaff** [comment]
@aidanbha79 @kaonick @simonstey any chance you're free for a call this week / next ? 

We're trying to learn how companies use LiteLLM Proxy 
sharing my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
