### ISSUE TITLE
Running the proxy: FileNotFoundError: [Errno 2] No such file or directory: 'prisma'

### ISSUE THREAD

**Issue by zopyx** [BerriAI/litellm#1430]
### What happened?

Python 3.11, litellm 1.17.3

Running the proxy command fails:

```
ajung@nuc2 ➜  litellm  bin/litellm --model huggingface/bigcode/starcoder
Traceback (most recent call last):
  File "/home/ajung/src/litellm/bin/litellm", line 8, in <module>
    sys.exit(run_server())
             ^^^^^^^^^^^^
  File "/home/ajung/src/litellm/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajung/src/litellm/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/ajung/src/litellm/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajung/src/litellm/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ajung/src/litellm/lib/python3.11/site-packages/litellm/proxy/proxy_cli.py", line 392, in run_server
    subprocess.run(
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/linuxbrew/.linuxbrew/opt/python@3.11/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'prisma'

```

**Comment by ghost** [comment]
@zopyx do you happen to have DATABASE_URL as an environment variable?

**Comment by ghost** [comment]
bump @zopyx @xunx911 ?

**Comment by xunx911** [comment]
> bump @zopyx @xunx911 ?

I'm trying to install prisma using npm to see if that resolves it.

**Comment by zopyx** [comment]
Works with the lastest codebase from `main`.

**Comment by xunx911** [comment]
@zopyx Could you please provide more details on how you resolved this issue? It would be really helpful.

**Comment by zopyx** [comment]
> @zopyx Could you please provide more details on how you resolved this issue? It would be really helpful.

Installation from a fresh repository checkout.

**Comment by ghost** [comment]
Just pushed a fix for this. Should be live soon in v`1.17.5`
