### ISSUE TITLE
[Bug]:  Mistral-tiny gives the error. 

### ISSUE THREAD

**Issue by SharmaSamarth1** [BerriAI/litellm#1471]
### What happened?

Mistral-tiny,mistral-small and mistral-medium are still giving the same error, even after updating to 1.17.13
Please refer to closed issue #1460 
<img width="1512" alt="Screenshot 2024-01-17 at 9 19 10 PM" src="https://github.com/BerriAI/litellm/assets/156169277/01029268-29f1-4a81-97b6-d526f5644e21">

### Relevant log output

```shell
/usr/local/lib/python3.9/site-packages/pydantic/main.py:308: UserWarning: Pydantic serializer warnings:
  Expected `datetime` but got `str` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 270, in acompletion
    response = await init_response
  File "/usr/local/lib/python3.9/site-packages/litellm/llms/openai.py", line 405, in acompletion
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/llms/openai.py", line 390, in acompletion
    response = await openai_aclient.chat.completions.create(
  File "/usr/local/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 1300, in create
    return await self._post(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1691, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1394, in request
    return await self._request(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1485, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Error code: 422 - {'object': 'error', 'message': '{"detail":[{"type":"extra_forbidden","loc":["body","user"],"msg":"Extra inputs are not permitted","input":"ff4b8731-5807-4d0d-aa6a-7e45369fc2ce","url":"https://errors.pydantic.dev/2.5/v/extra_forbidden"}]}', 'type': 'internal_error_proxy', 'param': None, 'code': '1000'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 1632, in chat_completion
    response = await llm_router.acompletion(**data)
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 320, in acompletion
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 316, in acompletion
    response = await self.async_function_with_fallbacks(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 871, in async_function_with_fallbacks
    raise original_exception
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 799, in async_function_with_fallbacks
    response = await self.async_function_with_retries(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 930, in async_function_with_retries
    raise original_exception
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 888, in async_function_with_retries
    response = await original_function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 382, in _acompletion
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 361, in _acompletion
    response = await litellm.acompletion(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2417, in wrapper_async
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2309, in wrapper_async
    result = await original_function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 287, in acompletion
    raise exception_type(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 6741, in exception_type
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 5686, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: OpenAIException - Error code: 422 - {'object': 'error', 'message': '{"detail":[{"type":"extra_forbidden","loc":["body","user"],"msg":"Extra inputs are not permitted","input":"ff4b8731-5807-4d0d-aa6a-7e45369fc2ce","url":"https://errors.pydantic.dev/2.5/v/extra_forbidden"}]}', 'type': 'internal_error_proxy', 'param': None, 'code': '1000'}
192.168.65.1:45439 - "POST /chat/completions HTTP/1.1" 422
```

**Comment by ghost** [comment]
i think i know the issue here. Looking further into this

**Comment by ghost** [comment]
Pushed a fix @SharmaSamarth1, should be live soon in v`1.17.14`. The issue was caused by optional params re-using the openai defaults, not the mistral specific ones (mistral doesn't support the user field) 

<img width="943" alt="Screenshot 2024-01-17 at 9 45 57 AM" src="https://github.com/BerriAI/litellm/assets/17561003/56c71082-52bc-4ef5-958b-00b5da955244">

**Comment by ghost** [comment]
v`1.17.14` is now live. @SharmaSamarth1 let me know if this solves your issue

**Comment by SharmaSamarth1** [comment]
yes it did. Thank you!

**Comment by lolsborn** [comment]
@krrishdholakia it would be useful in the future to link to relevant PRs / commits so that when similar issues come up its easy to reference previous work
