### ISSUE TITLE
[Bug]: Alpine images are failing to build

### ISSUE THREAD

**Issue by ShaunMaher** [BerriAI/litellm#1488]
### What happened?

The Github action fails to build the Alpine Linux based image.

A local build of the Alpine Linux based image also fails with the same error message.

Related bug in pyyaml: yaml/pyyaml#724 (is that how I make it link?).  Updating to pyyaml 6.0.1 resolves the issue.

### Relevant log output

```shell
#13 12.50   × Getting requirements to build wheel did not run successfully.
#13 12.50   │ exit code: 1
#13 12.50   ╰─> [54 lines of output]
#13 12.50       running egg_info
#13 12.50       writing lib/PyYAML.egg-info/PKG-INFO
#13 12.50       writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
#13 12.50       writing top-level names to lib/PyYAML.egg-info/top_level.txt
#13 12.50       Traceback (most recent call last):
#13 12.50         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
#13 12.50           main()
#13 12.50         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
#13 12.50           json_out['return_val'] = hook(**hook_input['kwargs'])
#13 12.50                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#13 12.50         File "/usr/local/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
#13 12.50           return hook(config_settings)
#13 12.50                  ^^^^^^^^^^^^^^^^^^^^^
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
#13 12.50           return self._get_build_requires(config_settings, requirements=['wheel'])
#13 12.50                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
#13 12.50           self.run_setup()
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 311, in run_setup
#13 12.50           exec(code, locals())
#13 12.50         File "<string>", line 288, in <module>
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
#13 12.50           return distutils.core.setup(**attrs)
#13 12.50                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
#13 12.50           return run_commands(dist)
#13 12.50                  ^^^^^^^^^^^^^^^^^^
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
#13 12.50           dist.run_commands()
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
#13 12.50           self.run_command(cmd)
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 963, in run_command
#13 12.50           super().run_command(command)
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
#13 12.50           cmd_obj.run()
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 321, in run
#13 12.50           self.find_sources()
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 329, in find_sources
#13 12.50           mm.run()
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
#13 12.50           self.add_defaults()
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
#13 12.50           sdist.add_defaults(self)
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/command/sdist.py", line 112, in add_defaults
#13 12.50           super().add_defaults()
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
#13 12.50           self._add_defaults_ext()
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
#13 12.50           self.filelist.extend(build_ext.get_source_files())
#13 12.50                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
#13 12.50         File "<string>", line 204, in get_source_files
#13 12.50         File "/tmp/pip-build-env-4yi0q23j/overlay/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
#13 12.50           raise AttributeError(attr)
#13 12.50       AttributeError: cython_sources
#13 12.50       [end of output]
#13 12.50   
#13 12.50   note: This error originates from a subprocess, and is likely not a problem with pip.
#13 12.51 error: subprocess-exited-with-error
#13 12.51 
#13 12.51 × Getting requirements to build wheel did not run successfully.
#13 12.51 │ exit code: 1
#13 12.51 ╰─> See above for output.
#13 12.51 
#13 12.51 note: This error originates from a subprocess, and is likely not a problem with pip.
#13 ERROR: process "/bin/sh -c pip wheel --no-cache-dir --wheel-dir=/wheels/ -r requirements.txt" did not complete successfully: exit code: 1
```

**Comment by ishaan-jaff** [comment]
Fix worked - Our Alpine Image is redeploying now
