### ISSUE TITLE
[Bug]: 'list' object has no attribute 'expires'

### ISSUE THREAD

**Issue by speedyankur** [BerriAI/litellm#1490]
### What happened?

facing this issue with /user/info?user_id={} endpoint?

### Relevant log output

```shell
`Traceback (most recent call last):                                 File "/usr/local/lib/python3.9/site-packages/litellm/proxy/utils.py", line 378, in get_data                                   response.expires = response.expires.isoformat()                               AttributeError: 'list' object has no attribute 'expires'                               Traceback (most recent call last):                                 File "/usr/local/lib/python3.9/site-packages/litellm/proxy/utils.py", line 378, in get_data                                   response.expires = response.expires.isoformat()                               AttributeError: 'list' object has no attribute 'expires'                               Traceback (most recent call last):                                 File "/usr/local/lib/python3.9/site-packages/litellm/proxy/utils.py", line 378, in get_data                                   response.expires = response.expires.isoformat()                               AttributeError: 'list' object has no attribute 'expires'`
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/speedyankur/

**Comment by ishaan-jaff** [comment]
Will take a look and fix this, + will add unit testing for all `/user` endpoints

**Comment by ghost** [comment]
Fix pushed - should be live soon in v`1.18.1`. It was an issue related to handling a list being returned by the prisma client.
