### ISSUE TITLE
[Bug]: success logging fails for text-embedding-3 call

### ISSUE THREAD

**Issue by dhruv-anand-aintech** [BerriAI/litellm#1628]
### What happened?

Embeddings get computed eventually, but a bunch of these error are output.

### Relevant log output

```shell
ception in thread Thread-2 (success_handler):   | 1/10 [00:01<00:17,  1.96s/it]
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/utils.py", line 1070, in _success_handler_helper_fn
    verbose_logger.debug(f"Model={self.model}; result={result}")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/_models.py", line 76, in __str__
    return f'{self.__repr_name__()}({self.__repr_str__(", ")})'  # type: ignore[misc]
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/_internal/_repr.py", line 55, in __repr_str__
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/_internal/_repr.py", line 55, in <genexpr>
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/pydantic/main.py", line 902, in __repr_args__
    for k, v in self.__dict__.items():
RuntimeError: dictionary changed size during iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/utils.py", line 1117, in success_handler
    start_time, end_time, result = self._success_handler_helper_fn(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/utils.py", line 1111, in _success_handler_helper_fn
    raise Exception(f"[Non-Blocking] LiteLLM.Success_Call Error: {str(e)}")
Exception: [Non-Blocking] LiteLLM.Success_Call Error: dictionary changed size during iteration
```

### Twitter / LinkedIn details

https://twitter.com/dhruv___anand

**Comment by dhruv-anand-aintech** [comment]
Code is here: https://github.com/AI-Northstar-Tech/vector-io/pull/32

**Comment by ghost** [comment]
@dhruv-anand-aintech there's a bunch of changes in there. can you share a specific script to repro, i'll add this to our ci/cd as well 

It looks like there was an error in the success handler. did the embedding call fail too or just the success logging?

**Comment by dhruv-anand-aintech** [comment]
Commands:
```
git lfs install && git clone https://huggingface.co/datasets/aintech/vdf_medium_articles
git clone https://github.com/AI-Northstar-Tech/vector-io.git
vector-io/src/reembed.py --dir ../vdf_medium_articles --new_model_name text-embedding-3-small --text_column title
```


Only the success logging seems to have failed, and is leading to a lot of error outputs. Would be nice to know of a way to silence these.

I tried:
```
import warnings
warnings.filterwarnings("ignore", module="litellm")
```

but that didn't work.

**Comment by psykhi** [comment]
Same here, it totally floods our logs. Tried to understand what's going on but couldn't

**Comment by ishaan-jaff** [comment]
will work on this today, @psykhi do you have a code script I can repro with ? 

- are you setting any success_callbacks ?

**Comment by psykhi** [comment]
Yes we do use a sucess callback that we use to track completions, but I believe this comes from our embedding calls

**Comment by ishaan-jaff** [comment]
@psykhi Can you clarify what is happening ? 

My understanding of the problem:
- you can see debugging statements when you're running `embedding()`. And you're unable to switch of these debugging statements ? 

Is this correct ?

**Comment by psykhi** [comment]
Yes! 

```
python3.11/site-packages/litellm/utils.py",  line 1112, in _success_handler_helper_fn
    
raise Exception(f"[Non-Blocking] LiteLLM.Success_Call Error: {str(e)}")
Exception
[Non-Blocking] LiteLLM.Success_Call Error: dictionary changed size during iteration
```

**Comment by dhruv-anand-aintech** [comment]
I'm not seeing any callbacks btw

**Comment by ishaan-jaff** [comment]
Trying to repro the error, 

Unable to with this code
```python
response = litellm.embedding(
            model="text-embedding-3-small",
            input="good morning from litellm"
        )
```

**Comment by ishaan-jaff** [comment]
Tried this too, I see no errors - any suggestion on how to repro @psykhi @dhruv-anand-aintech 
```python
for model in ["text-embedding-3-small", "text-embedding-ada-002"]:
      response = litellm.embedding(
          model=model,
          input=["good morning from litellm", "this is another item"],
      )
      print(f"response:", response)
```

**Comment by ishaan-jaff** [comment]
Fix here: https://github.com/BerriAI/litellm/pull/2378 @dhruv-anand-aintech @psykhi can you help verify it's fixed once a new release is out
