### ISSUE TITLE
[Bug]: ollama + litellm & autogen

### ISSUE THREAD

**Issue by akashAD98** [BerriAI/litellm#1662]
### What happened?

$ installed ollma in my linux ubantu 22.04 machine

im getting 
ollama list
```
NAME                           	ID          	SIZE  	MODIFIED       
codellama:latest               	8fdf8f752f6e	3.8 GB	13 minutes ago	
mistral:7b-instruct-v0.2-q4_K_S	ba00d3a5239e	4.1 GB	2 hours ago   	
mistral:latest                 	61e88e884507	4.1 GB	45 minutes ago	
mistral_akash:latest           	73dc103bd530	4.1 GB	4 hours ago   	
(base) akash@Precision-3580:~/LLMstudio$ 

```

# setup i followed

1.  ollama run mistral
2.  ollama run codellama

then using litellm

```
 litellm --model ollama/mistral   - http://0.0.0.0:8000 
 litellm --model ollama/codellama - http://0.0.0.0:46602 

```

my code is :

```
## Testing out the main version

import autogen

config_list_1 = [
{
'base_url': "http://0.0.0.0:8000",
'api_key': "NULL",
'model': "ollama/mistral",
}
]

config_list_2 = [
{
'base_url': "http://0.0.0.0:46602",
'api_key': "NULL",
'model': "ollama/codellama",
}
]

llm_config_1={
"config_list": config_list_1,
}

llm_config_2={
"config_list": config_list_2,
}

coder = autogen.AssistantAgent(
name="Coder",
llm_config=llm_config_2
)

user_proxy = autogen.UserProxyAgent(
name="user_proxy",
human_input_mode="NEVER",
max_consecutive_auto_reply=10,
is_termination_msg=lambda x: x.get("content", "").rstrip().endswith("TERMINATE"),
code_execution_config={"work_dir": "web"},
llm_config=llm_config_1,
system_message="""Reply TERMINATE if the task has been solved at full satisfaction.
Otherwise, reply CONTINUE, or the reason why the task is not solved yet."""
)

# task="""
# Write a python script to output numbers 1 to 100 and then the user_proxy agent should run the script
# """

task="""
Tell me a joke!
"""

user_proxy.initiate_chat(coder, message=task)

```

### Relevant log output

```shell
im getting error




user_proxy (to Coder):


Tell me a joke!


--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/akash/LLMstudio/ollama/AutogenLangchainPDFchat-main/app_basic_autogen.py", line 53, in <module>
    user_proxy.initiate_chat(coder, message=task)
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 698, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 441, in send
    recipient.receive(message, self, request_reply, silent)
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 599, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 1298, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 813, in generate_oai_reply
    response = client.create(
               ^^^^^^^^^^^^^^
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/oai/client.py", line 283, in create
    response = self._completions_create(client, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/autogen/oai/client.py", line 548, in _completions_create
    response = completions.create(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_utils/_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 659, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 1180, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 869, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/openai/_base_client.py", line 960, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Authentication Error, ', 'type': 'auth_error', 'param': 'None', 'code': 401}}
```

not sure issue with autogen or Litellm
```


### Twitter / LinkedIn details

_No response_

**Comment by akashAD98** [comment]
@krrishdholakia dont know why its asking openai ,im selecting open llm mistral model

**Comment by ghost** [comment]
@akashAD98 
the:
> openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Authentication Error, ', 'type': 'auth_error', 'param': 'None', 'code': 401}}

seems to be coming from the proxy

Can you share the proxy logs?

**Comment by akashAD98** [comment]
@krrishdholakia @ishaan-jaff 
pip install 'litellm[proxy]'

already done this & requirements satisfied. still getting


```
(autogen) akash@Precision-3580:~/LLMstudio/ollama/AutogenLangchainPDFchat-main$ litellm --model ollama/mistral --local 
Traceback (most recent call last):
  File "/home/akash/anaconda3/envs/autogen/bin/litellm", line 8, in <module>
    sys.exit(run_server())
             ^^^^^^^^^^^^
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/akash/anaconda3/envs/autogen/lib/python3.11/site-packages/litellm/proxy/proxy_cli.py", line 193, in run_server
    from proxy_server import app, save_worker_config, usage_telemetry, ProxyConfig
ModuleNotFoundError: No module named 'proxy_server'

```

**Comment by akashAD98** [comment]
here is log when i added --debug 
```
(base) akash@Precision-3580:~/LLMstudio/ollama/AutogenLangchainPDFchat-main$ litellm --model ollama/codellama --debug
LiteLLM Proxy: Starting server on 0.0.0.0:35578 with 1 workers


LiteLLM: Test your local proxy with: "litellm --test" This runs an openai.ChatCompletion request to your proxy [In a new terminal tab]

LiteLLM: Curl Command Test for your local proxy
 curl --location 'http://0.0.0.0:35578/chat/completions' \
                    --header 'Content-Type: application/json' \
                    --data ' {
                    "model": "gpt-3.5-turbo",
                    "messages": [
                        {
                        "role": "user",
                        "content": "what llm are you"
                        }
                    ]
                    }'
                    

                     

Docs: https://docs.litellm.ai/docs/simple_proxy

See all Router/Swagger docs on http://0.0.0.0:35578 

[2024-01-30 18:40:29 +0530] [51791] [INFO] Starting gunicorn 21.2.0
[2024-01-30 18:40:29 +0530] [51791] [INFO] Listening at: http://0.0.0.0:35578 (51791)
[2024-01-30 18:40:29 +0530] [51791] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-01-30 18:40:29 +0530] [51797] [INFO] Booting worker with pid: 51797
[2024-01-30 18:40:29 +0530] [51797] [INFO] Started server process [51797]
[2024-01-30 18:40:29 +0530] [51797] [INFO] Waiting for application startup.

#------------------------------------------------------------#
#                                                            #
#              'I don't like how this works...'               #
#        https://github.com/BerriAI/litellm/issues/new        #
#                                                            #
#------------------------------------------------------------#

 Thank you for using LiteLLM! - Krrish & Ishaan



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new


[2024-01-30 18:40:29 +0530] [51797] [INFO] Application startup complete.
Traceback (most recent call last):
  File "/home/akash/anaconda3/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 249, in user_api_key_auth
    assert api_key.startswith("sk-")  # prevent token hashes from being used
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
127.0.0.1:56730 - "POST /chat/completions HTTP/1.1" 401
[2024-01-30 18:42:14 +0530] [51791] [INFO] Handling signal: winch

```

**Comment by MikeyBeez** [comment]
This is blockware intended to keep developers from getting anywhere with local models.  Use langchains llm module to connect to olllama instead.

**Comment by akashAD98** [comment]
i want endpoint api so i can use it with autogen .thats reason im using litellm

**Comment by ghost** [comment]
@akashAD98 this should be fixed in v`1.20.5`. Can you confirm that?

**Comment by MikeyBeez** [comment]
Litellm uses the openai module.  this module seems to be designed to thwart programmers.  Don't use it.  Use the llms module in langchain to connect to ollama models.

**Comment by YangQiuEric** [comment]
> @akashAD98 this should be fixed in v`1.20.5`. Can you confirm that?

not, not fixed, same error here. also having assert api_key.startswith("sk-") error. Even I pass the openai key, it will have "The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable".

**Comment by akashAD98** [comment]
@MikeyBeez @YangQiuEric its working fine for me

![image](https://github.com/BerriAI/litellm/assets/62583018/a3279010-9870-4d92-9c69-71c6bcf195af)

**Comment by Kuchiriel** [comment]
Just `pip install --upgrade 'litellm[proxy]'`, it will install all missing deps and fix the issue.

You can also install all deps one by one as the run complains, like:
```
 pip install --upgrade backoff --no-binary :all
 pip install --upgrade fastapi --no-binary :all
 pip install --upgrade orjson --no-binary :all
[...]
```
But this is what we call here in Brazil a "cornojob" which can be translated as "hornjob" or "cuckjob", so I prefer the fast way.

I am lazy and I also dont want be a "horn" or a "cuck" ;-;

![image](https://github.com/user-attachments/assets/f6f80a2a-8492-4daf-9a3b-8397e4531d35)
