### ISSUE TITLE
[Bug]: Authentication Error 401 with ollama models running locally

### ISSUE THREAD

**Issue by octopop** [BerriAI/litellm#1679]
### What happened?

I have been a happy camper using LiteLLM and Ollama running locally on my Macbook for several months. Today I decided to `pip install --upgrade litellm` and it appears there have been breaking changes, particularly around authentication.

I reviewed the [LiteLLM - Ollama Documentation](https://litellm.vercel.app/docs/providers/ollama), however did not see any major changes that I may have missed. It suggests to still run locally using `litellm -m ollama/llama2` bash command.

Even though I am setting the proxy to use ollama/llama2, it appears it is expecting authentication?

As a (very bad) band-aid fix; I was able to get it working by replacing `line 249` in `/opt/homebrew/lib/python3.11/site-packages/litellm/proxy/proxy_server.py` as follows:

```python
 if isinstance(api_key, str):
  return UserAPIKeyAuth() # <-- added
  #assert api_key.startswith("sk-")  # prevent token hashes from being used # <-- commented
```

### Relevant log output

```shell
$ litellm -v

LiteLLM: Current Version = 1.20.3

$ litellm --debug -m ollama/llama2-uncensored
LiteLLM Proxy: Starting server on 0.0.0.0:8000 with 1 workers


LiteLLM: Test your local proxy with: "litellm --test" This runs an openai.ChatCompletion request to your proxy [In a new terminal tab]

LiteLLM: Curl Command Test for your local proxy
 curl --location 'http://0.0.0.0:8000/chat/completions' \
                    --header 'Content-Type: application/json' \
                    --data ' {
                    "model": "gpt-3.5-turbo",
                    "messages": [
                        {
                        "role": "user",
                        "content": "what llm are you"
                        }
                    ]
                    }'




Docs: https://docs.litellm.ai/docs/simple_proxy

See all Router/Swagger docs on http://0.0.0.0:8000

[2024-01-29 21:18:17 -0800] [27808] [INFO] Starting gunicorn 21.2.0
[2024-01-29 21:18:17 -0800] [27808] [INFO] Listening at: http://0.0.0.0:8000 (27808)
[2024-01-29 21:18:17 -0800] [27808] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2024-01-29 21:18:17 -0800] [27810] [INFO] Booting worker with pid: 27810
[2024-01-29 21:18:17 -0800] [27810] [INFO] Started server process [27810]
[2024-01-29 21:18:17 -0800] [27810] [INFO] Waiting for application startup.

#------------------------------------------------------------#
#                                                            #
#            'This product would be better if...'             #
#        https://github.com/BerriAI/litellm/issues/new        #
#                                                            #
#------------------------------------------------------------#

 Thank you for using LiteLLM! - Krrish & Ishaan



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new


[2024-01-29 21:18:17 -0800] [27810] [INFO] Application startup complete.
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 249, in user_api_key_auth
    assert api_key.startswith("sk-")  # prevent token hashes from being used
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
127.0.0.1:63165 - "POST /v1/chat/completions HTTP/1.1" 401
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 249, in user_api_key_auth
    assert api_key.startswith("sk-")  # prevent token hashes from being used
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

**Comment by sandros06** [comment]
+1 
I got the same errors after update to 1.20.3

I can't start with older version because I have also this problem #1471 (1.17.3)

**Comment by ishaan-jaff** [comment]
Fixed here: https://github.com/BerriAI/litellm/commit/5d78ec97a74735d7f822a594783f5694cb52915d 

@sandros06 @octopop

**Comment by ishaan-jaff** [comment]
1.20.4 should have the fix

**Comment by ishaan-jaff** [comment]
Fixed here: https://github.com/BerriAI/litellm/releases/tag/v1.20.5 

Can you confirm @sandros06 @octopop ?

**Comment by octopop** [comment]
Confirming its fixed @ishaan-jaff. Thanks!
