### ISSUE TITLE
[Bug]: Stop tokens are not passed onto ollama

### ISSUE THREAD

**Issue by gaardhus** [BerriAI/litellm#1709]
### What happened?

I'm trying to use litellm as a proxy for ollama for an interchangeable llm interface, however I'm having problem with the stop token:

```python
from litellm import completion
import litellm

litellm.set_verbose = True

response = completion(
    model="ollama/mixtral",
    messages=[{"content": "Why is the sky blue?", "role": "user"}],
    stop=[",", "."],
    stream=False,
)
print(response)
```

```console
choices=[Choices(finish_reason='stop', index=0, message=Message(content=" The phenomenon that causes the sky to appear blue is known as Rayleigh scattering. As sunlight passes through the Earth's atmosphere, it interacts with molecules and particles in the air such as nitrogen and oxygen. These particles scatter short-wavelength light, such blue and violet light, to the sides more than other colors like red, yellow, or green, which have longer wavelengths.\n\nHowever, our eyes are more sensitive to blue light and less sensitive to violet light. Additionally, sunlight reaches us with less violet light to begin with. This combination results in the sky appearing blue instead of violet during the daytime.", role='assistant'))], created=1706716539, model='ollama/mixtral', object='chat.completion', system_fingerprint=None, usage=Usage(prompt_tokens=6, completion_tokens=135, total_tokens=141))
```

### Relevant log output

```shell
Request to litellm:
litellm.completion(model='ollama/mixtral', messages=[{'content': 'Why is the sky blue?', 'role': 'user'}], stop=[',', '.'], stream=False)

self.optional_params: {}
kwargs[caching]: False; litellm.cache: None
self.optional_params: {'stop_sequences': [',', '.']}
Looking up model=ollama/mixtral in model_cost_map
ModelResponse(id='chatcmpl-d940205f-b85d-4ae3-aeea-a45f78dcc4fc'
```

**Comment by gaardhus** [comment]
Updated to latest version, now I get the following output.
```
Request to litellm:
litellm.completion(model='ollama/mixtral', messages=[{'content': 'Why is the sky blue?', 'role': 'user'}], stop=[',', '.'], stream=False)


self.optional_params: {}
kwargs[caching]: False; litellm.cache: None
self.optional_params: {'stop_sequences': [',', '.']}


POST Request Sent from LiteLLM:
curl -X POST \
http://localhost:11434/api/generate \
-d '{'model': 'mixtral', 'prompt': 'Why is the sky blue?', 'options': {'stop_sequences': [',', '.']}}'



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
self.failure_callback: []
Traceback (most recent call last):
  File "/scratch/hwl272/miniconda3/envs/litellm/lib/python3.11/site-packages/litellm/main.py", line 1665, in completion
    generator = ollama.get_ollama_response(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/hwl272/miniconda3/envs/litellm/lib/python3.11/site-packages/litellm/llms/ollama.py", line 187, in get_ollama_response
    raise OllamaError(status_code=response.status_code, message=response.text)
litellm.llms.ollama.OllamaError: {"error":"invalid options: stop_sequences"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/scratch/hwl272/Github/ainterview/scripts/test_litellm_interface.py", line 6, in <module>
    response = completion(
               ^^^^^^^^^^^
  File "/scratch/hwl272/miniconda3/envs/litellm/lib/python3.11/site-packages/litellm/utils.py", line 2455, in wrapper
    raise e
  File "/scratch/hwl272/miniconda3/envs/litellm/lib/python3.11/site-packages/litellm/utils.py", line 2358, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/scratch/hwl272/miniconda3/envs/litellm/lib/python3.11/site-packages/litellm/main.py", line 1880, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/scratch/hwl272/miniconda3/envs/litellm/lib/python3.11/site-packages/litellm/utils.py", line 7462, in exception_type
    raise e
  File "/scratch/hwl272/miniconda3/envs/litellm/lib/python3.11/site-packages/litellm/utils.py", line 7430, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: {"error":"invalid options: stop_sequences"}
```

**Comment by japanvik** [comment]
I believe this is causing it
https://github.com/BerriAI/litellm/blob/5a29f362eefbc23baa1605437de7e08b3a75090d/litellm/utils.py#L4361

Ollama expects the stop parameter to be called "stop" and not "stop_sequences". Confirmed by manually POSTing to the ollama endpoint by renaming "stop_sequences" to "stop"

**Comment by oxaronick** [comment]
Just ran into the same problem. I deleted the line @japanvik mentioned and the `if` before it. Requests to Ollama were successful.

**Comment by ghost** [comment]
Fix pushed - should be live soon in the next release - v`1.23.1`+ 

https://github.com/BerriAI/litellm/commit/655fcd4d79b94ec523f62bedc34c17fce7c5b864
