### ISSUE TITLE
[Bug]: Admin UI fails after login

### ISSUE THREAD

**Issue by coolrazor007** [BerriAI/litellm#1756]
### What happened?

I logged in using the username and password I set (just a test user with all lower case character password) and immediately went to page with: "Internal Server Error"  on URL:   http://[ip]:[port]/login 

Docker Image used: ghcr.io/berriai/litellm-database:main-v1.21.0

Docker Run Command:
`
          docker run
          -p  4000:4000
          --name litellm
          --network litellm-net
          --restart always
          -v ./hub/litellm-config.yaml:/app/proxy_server_config.yaml
          -e DATABASE_URL="${{secrets.DEV_POSTGRES_URL}}"
          -e UI_USERNAME=admin
          -e UI_PASSWORD=password
          --add-host host.docker.internal:host-gateway
          -d ghcr.io/berriai/litellm-database:main-v1.21.0 --config proxy_server_config.yaml --port 4000 --num_workers 4
`

### Relevant log output

```shell
Collecting python-multipart
  Downloading python_multipart-0.0.6-py3-none-any.whl (45 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 45.7/45.7 kB 2.0 MB/s eta 0:00:00
Installing collected packages: python-multipart
Successfully installed python-multipart-0.0.6
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip is available: 23.0.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip
INFO:     100.104.38.150:63946 - "POST /login HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 762, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 782, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 3119, in login
    form = await request.form()
  File "/usr/local/lib/python3.9/site-packages/starlette/requests.py", line 260, in _get_form
    assert (
AssertionError: The `python-multipart` library must be installed to use form parsing.
```

**Comment by ishaan-jaff** [comment]
Fixed here: https://github.com/BerriAI/litellm/commit/256070d24f3156554b612b3b05f4863e12750ff5 

What version of litellm are you on @coolrazor007 ?

**Comment by coolrazor007** [comment]
I used your docker image with the tag: v1.21.0

So it would be v1.21.0 I'd imagine

**Comment by ishaan-jaff** [comment]
dependencies fixed here: https://github.com/BerriAI/litellm/releases/tag/v1.21.1 

can you try it there @coolrazor007 ?

**Comment by coolrazor007** [comment]
I just tried v1.22.3 and it worked like a charm!  Great job!

**Comment by ishaan-jaff** [comment]
@coolrazor007 any chance we can hop on a call this week ? I'd love to learn how we can improve LiteLLM for you 

Sharing my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/berriai-1-1-onboarding-litellm-hosted-version?month=2024-02

**Comment by coolrazor007** [comment]
> @coolrazor007 any chance we can hop on a call this week ? I'd love to learn how we can improve LiteLLM for you
> 
> Sharing my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/berriai-1-1-onboarding-litellm-hosted-version?month=2024-02

yeah we met already, but I'd be down for a follow up.  I scheduled it via the link
