### ISSUE TITLE
[Bug]: vllm example in document failed

### ISSUE THREAD

**Issue by wangm23456** [BerriAI/litellm#1757]
### What happened?

[A bug happened!](https://docs.litellm.ai/docs/providers/vllm)

```python
import litellm 

response = litellm.completion(
            model="openai/mistralai/Mistral-7B-Instruct-v0.2", # pass the vllm model name
            messages="hi",
            api_base="http://127.0.0.1:18000",
            temperature=0.2,
            max_tokens=80)

print(response)
```
I run a vllm server in docker:

```text
services:
  vllm:
    image: vllm/vllm-openai:latest
    container_name: vllm
    ports: 
      - 8000:8000
    volumes:
      - ./vllm:/root/.cache/huggingface
      - ./vllm_run.sh:/root/vllm_run.sh
    entrypoint: "/bin/bash /root/vllm_run.sh"
    tty: true
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
```

litellm version: 1.21.0

### Relevant log output

```shell
Traceback (most recent call last):
  File "/data/home/.pyenv/versions/miniconda3-latest/envs/pytorch/bin/litellm", line 5, in <module>
    from litellm import run_server
  File "/data/home/.pyenv/versions/miniconda3-latest/envs/pytorch/lib/python3.9/site-packages/litellm/__init__.py", line 6, in <module>
    from litellm.proxy._types import KeyManagementSystem
  File "/data/home/.pyenv/versions/miniconda3-latest/envs/pytorch/lib/python3.9/site-packages/litellm/proxy/_types.py", line 78, in <module>
    class ModelInfo(LiteLLMBase):
  File "pydantic/main.py", line 197, in pydantic.main.ModelMetaclass.__new__
  File "pydantic/fields.py", line 506, in pydantic.fields.ModelField.infer
  File "pydantic/fields.py", line 436, in pydantic.fields.ModelField.__init__
  File "pydantic/fields.py", line 552, in pydantic.fields.ModelField.prepare
  File "pydantic/fields.py", line 661, in pydantic.fields.ModelField._type_analysis
  File "pydantic/fields.py", line 668, in pydantic.fields.ModelField._type_analysis
  File "/data/home/.pyenv/versions/miniconda3-latest/envs/pytorch/lib/python3.9/typing.py", line 852, in __subclasscheck__
    return issubclass(cls, self.__origin__)
TypeError: issubclass() arg 1 must be a class
```

**Comment by jinnotgin** [comment]
I'm running a VLLM instance (for Deepseek model) as well via the LiteLLM proxy, and the following config helped for me:
<img width="965" alt="image" src="https://github.com/BerriAI/litellm/assets/14935308/ba5187a2-3cde-431b-9970-01f15ef15207">

essentially, i added a /v1 to the `api_base`. 

perhaps you can try that and see if that helps?

**Comment by wangm23456** [comment]
> I'm running a VLLM instance (for Deepseek model) as well via the LiteLLM proxy, and the following config helped for me:我也通过 LiteLLM 代理运行 VLLM 实例（对于 Deepseek 模型），以下配置对我有帮助： <img alt="image" width="965" src="https://private-user-images.githubusercontent.com/14935308/302096923-ba5187a2-3cde-431b-9970-01f15ef15207.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMTY4NTYsIm5iZiI6MTcwOTAxNjU1NiwicGF0aCI6Ii8xNDkzNTMwOC8zMDIwOTY5MjMtYmE1MTg3YTItM2NkZS00MzFiLTk5NzAtMDFmMTVlZjE1MjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDA2NDkxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3OGJiYmFhY2YwNTAzMWQ5ODAwZDNmNzc1NTdlNjhmNjYzMmZiMzQ1NmIyOTRkODYxOTdhNmE5MzUzYjE4NTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g0A7H2IdFPlShOl0cXgxNiZ00d-CU3dpRsIyjGtlMSc">
> 
> essentially, i added a /v1 to the `api_base`.本质上，我在 `api_base` 中添加了 /v1 。
> 
> perhaps you can try that and see if that helps?也许你可以尝试一下，看看是否有帮助？

thanks, it  work
