### ISSUE TITLE
[Bug]: Cohere support is broken?

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1762]
### What happened?

Extremely low priority since Cohere Command works fine through Amazon Bedrock, and we don't use Cohere much anyway.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 2111, in chat_completion
    response = await llm_router.acompletion(**data)
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 365, in acompletion
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 361, in acompletion
    response = await self.async_function_with_fallbacks(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 921, in async_function_with_fallbacks
    raise original_exception
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 844, in async_function_with_fallbacks
    response = await self.async_function_with_retries(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 980, in async_function_with_retries
    raise original_exception
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 938, in async_function_with_retries
    response = await original_function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 427, in _acompletion
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 406, in _acompletion
    response = await litellm.acompletion(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2583, in wrapper_async
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2469, in wrapper_async
    result = await original_function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 283, in acompletion
    raise exception_type(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 7060, in exception_type
    raise original_exception
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 6473, in exception_type
    raise original_exception
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 275, in acompletion
    response = await loop.run_in_executor(None, func_with_context)  # type: ignore
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2339, in wrapper
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2242, in wrapper
    result = original_function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 1873, in completion
    raise exception_type(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 7060, in exception_type
    raise original_exception
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 6473, in exception_type
    raise original_exception
  File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 1136, in completion
    model_response = cohere.completion(
  File "/usr/local/lib/python3.9/site-packages/litellm/llms/cohere.py", line 138, in completion
    prompt = " ".join(message["content"] for message in messages)
TypeError: sequence item 0: expected str instance, list found
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
unable to repro. @Manouchehri can you share the curl used? from the error message, it looks like the message input was malformed (list passed instead of string for message["content"])
<img width="605" alt="Screenshot 2024-02-02 at 4 46 00 PM" src="https://github.com/BerriAI/litellm/assets/17561003/54f77f16-3092-4034-9085-067e299c403a">

**Comment by Manouchehri** [comment]
Oops. You are correct...
