### ISSUE TITLE
[Bug]: `KeyError: 'azure/gpt-35-turbo'` with LITELLM_LOCAL_MODEL_COST_MAP 

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#1767]
### What happened?

After updating to v1.21.0, this error popped up.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1063, in _success_handler_helper_fn
    self.model_call_details["response_cost"] = litellm.completion_cost(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 3213, in completion_cost
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 3199, in completion_cost
    ) = cost_per_token(
  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 3043, in cost_per_token
    f"applying cost={model_cost_ref[model]['input_cost_per_token']} for prompt_tokens={prompt_tokens}"
KeyError: 'azure/gpt-35-turbo'"
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by Manouchehri** [comment]
Setting `LITELLM_LOCAL_MODEL_COST_MAP=False` seems to make the issue go away. 😅

**Comment by ghost** [comment]
@Manouchehri is this still an issue - we recently implemented a precommit check to make sure the local copy is the same as the hosted one.

**Comment by Manouchehri** [comment]
I'm trying now, one moment. =)

**Comment by Manouchehri** [comment]
Seems like it's fixed, didn't get an error after setting `LITELLM_LOCAL_MODEL_COST_MAP=True` again.
