### ISSUE TITLE
httpx.ConnectError: All connection attempts failed

### ISSUE THREAD

**Issue by plsnotracking** [BerriAI/litellm#1789]
Was trying to setup [bionic-gpt](https://bionic-gpt.com/docs/running-locally/apple-silicon/) on my local Apple Silicon and that uses `litellm` while the setup process.

```bash
OS: macOS 14.3 23D56 arm64
Host: MacBookPro18,2
CPU: Apple M1 Max
GPU: Apple M1 Max
Memory: 6869MiB / 65536MiB
```

I've tried 2 different versions and none of them were successful in my attempt to run them.

`ghcr.io/berriai/litellm:main-v1.10.3` resulted in the error trace mentioned here: https://github.com/bionic-gpt/bionic-gpt/issues/354

and the next attempt was using: `ghcr.io/berriai/litellm:main-v1.21.4`, the following stacktrace is from using `1.21.4`.

```bash
llm-api-1         |
llm-api-1         | #------------------------------------------------------------#
llm-api-1         | #                                                            #
llm-api-1         | #           'I get frustrated when the product...'            #
llm-api-1         | #        https://github.com/BerriAI/litellm/issues/new        #
llm-api-1         | #                                                            #
llm-api-1         | #------------------------------------------------------------#
llm-api-1         |
llm-api-1         |  Thank you for using LiteLLM! - Krrish & Ishaan
llm-api-1         |
llm-api-1         |
llm-api-1         |
llm-api-1         | Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
llm-api-1         |
llm-api-1         |
llm-api-1         | INFO:     172.19.0.4:33594 - "POST /v1/chat/completions HTTP/1.1" 200 OK
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 170, in try_connect
llm-api-1         |     stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2258, in connect_tcp
llm-api-1         |     await get_running_loop().create_connection(
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
llm-api-1         |     raise exceptions[0]
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
llm-api-1         |     sock = await self._connect_sock(
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
llm-api-1         |     await self.sock_connect(sock, address)
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
llm-api-1         |     return await fut
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
llm-api-1         |     raise OSError(err, f'Connect call failed {address}')
llm-api-1         | ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.65.254', 11434)
llm-api-1         |
llm-api-1         | The above exception was the direct cause of the following exception:
llm-api-1         |
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
llm-api-1         |     yield
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
llm-api-1         |     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 232, in connect_tcp
llm-api-1         |     raise OSError("All connection attempts failed") from cause
llm-api-1         | OSError: All connection attempts failed
llm-api-1         |
llm-api-1         | The above exception was the direct cause of the following exception:
llm-api-1         |
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
llm-api-1         |     yield
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
llm-api-1         |     resp = await self._pool.handle_async_request(req)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
llm-api-1         |     raise exc
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
llm-api-1         |     response = await connection.handle_async_request(request)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
llm-api-1         |     raise exc
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
llm-api-1         |     stream = await self._connect(request)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 124, in _connect
llm-api-1         |     stream = await self._network_backend.connect_tcp(**kwargs)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
llm-api-1         |     return await self._backend.connect_tcp(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 121, in connect_tcp
llm-api-1         |     stream._raw_socket.setsockopt(*option)  # type: ignore[attr-defined] # pragma: no cover
llm-api-1         |   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
llm-api-1         |     self.gen.throw(typ, value, traceback)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
llm-api-1         |     raise to_exc(exc) from exc
llm-api-1         | httpcore.ConnectError: All connection attempts failed
llm-api-1         |
llm-api-1         | The above exception was the direct cause of the following exception:
llm-api-1         |
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/llms/ollama.py", line 252, in ollama_async_streaming
llm-api-1         |     async with client.stream(
llm-api-1         |   File "/usr/local/lib/python3.9/contextlib.py", line 181, in __aenter__
llm-api-1         |     return await self.gen.__anext__()
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1573, in stream
llm-api-1         |     response = await self.send(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1617, in send
llm-api-1         |     response = await self._send_handling_auth(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
llm-api-1         |     response = await self._send_handling_redirects(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
llm-api-1         |     response = await self._send_single_request(request)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1719, in _send_single_request
llm-api-1         |     response = await transport.handle_async_request(request)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
llm-api-1         |     resp = await self._pool.handle_async_request(req)
llm-api-1         |   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
llm-api-1         |     self.gen.throw(typ, value, traceback)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
llm-api-1         |     raise mapped_exc(message) from exc
llm-api-1         | httpx.ConnectError: All connection attempts failed
oauth2-proxy-1    | 192.168.65.1:32392 - c0ead508-ba04-463a-86e0-5d41d08b4958 - bionicgpt.1fzq6@8alias.com [2024/02/03 02:49:28] localhost:7800 POST / "/completions/37" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 200 14 0.340
oauth2-proxy-1    | 192.168.65.1:32391 - 4328f17e-c1ff-414d-997e-317c32e9d1f2 - bionicgpt.1fzq6@8alias.com [2024/02/03 02:49:29] localhost:7800 POST / "/app/team/1/update_response" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 303 0 0.008
oauth2-proxy-1    | 192.168.65.1:32391 - 498acd5d-e0d9-469f-8484-ae49e379322d - bionicgpt.1fzq6@8alias.com [2024/02/03 02:49:29] localhost:7800 GET / "/app/team/1/console/1" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 200 14429 0.003
llm-api-1         | INFO:     172.19.0.4:33600 - "POST /v1/chat/completions HTTP/1.1" 200 OK
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 170, in try_connect
llm-api-1         |     stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2258, in connect_tcp
llm-api-1         |     await get_running_loop().create_connection(
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
llm-api-1         |     raise exceptions[0]
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
llm-api-1         |     sock = await self._connect_sock(
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
llm-api-1         |     await self.sock_connect(sock, address)
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
llm-api-1         |     return await fut
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
llm-api-1         |     raise OSError(err, f'Connect call failed {address}')
llm-api-1         | ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.65.254', 11434)
llm-api-1         |
llm-api-1         | The above exception was the direct cause of the following exception:
llm-api-1         |
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
llm-api-1         |     yield
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
llm-api-1         |     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 232, in connect_tcp
llm-api-1         |     raise OSError("All connection attempts failed") from cause
llm-api-1         | OSError: All connection attempts failed
llm-api-1         |
llm-api-1         | The above exception was the direct cause of the following exception:
llm-api-1         |
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
llm-api-1         |     yield
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
llm-api-1         |     resp = await self._pool.handle_async_request(req)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
llm-api-1         |     raise exc
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
llm-api-1         |     response = await connection.handle_async_request(request)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
llm-api-1         |     raise exc
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
llm-api-1         |     stream = await self._connect(request)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 124, in _connect
llm-api-1         |     stream = await self._network_backend.connect_tcp(**kwargs)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
llm-api-1         |     return await self._backend.connect_tcp(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 121, in connect_tcp
llm-api-1         |     stream._raw_socket.setsockopt(*option)  # type: ignore[attr-defined] # pragma: no cover
llm-api-1         |   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
llm-api-1         |     self.gen.throw(typ, value, traceback)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
llm-api-1         |     raise to_exc(exc) from exc
llm-api-1         | httpcore.ConnectError: All connection attempts failed
llm-api-1         |
llm-api-1         | The above exception was the direct cause of the following exception:
llm-api-1         |
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/llms/ollama.py", line 252, in ollama_async_streaming
llm-api-1         |     async with client.stream(
llm-api-1         |   File "/usr/local/lib/python3.9/contextlib.py", line 181, in __aenter__
llm-api-1         |     return await self.gen.__anext__()
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1573, in stream
llm-api-1         |     response = await self.send(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1617, in send
llm-api-1         |     response = await self._send_handling_auth(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
llm-api-1         |     response = await self._send_handling_redirects(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
llm-api-1         |     response = await self._send_single_request(request)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1719, in _send_single_request
llm-api-1         |     response = await transport.handle_async_request(request)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
llm-api-1         |     resp = await self._pool.handle_async_request(req)
llm-api-1         |   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
llm-api-1         |     self.gen.throw(typ, value, traceback)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
llm-api-1         |     raise mapped_exc(message) from exc
llm-api-1         | httpx.ConnectError: All connection attempts failed
app-1             | 2024-02-03T02:49:29.796212Z  INFO axum_server::prompt: prompt.name="Default (Exclude All Datasets)"
app-1             | 2024-02-03T02:49:29.796233Z  INFO axum_server::prompt: Retrieved 0 chunks
oauth2-proxy-1    | 192.168.65.1:32391 - 5d6138ad-ac69-4fca-80ed-a44f51db7db6 - bionicgpt.1fzq6@8alias.com [2024/02/03 02:49:29] localhost:7800 POST / "/completions/37" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 200 14 0.565
app-1             | 2024-02-03T02:49:29.797785Z  INFO axum_server::prompt: Retrieved 2 history items
app-1             | 2024-02-03T02:49:29.797800Z  INFO axum_server::prompt: Using context size of 1024
llm-api-1         | INFO:     172.19.0.4:33602 - "POST /v1/chat/completions HTTP/1.1" 200 OK
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 170, in try_connect
llm-api-1         |     stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2258, in connect_tcp
llm-api-1         |     await get_running_loop().create_connection(
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
llm-api-1         |     raise exceptions[0]
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
llm-api-1         |     sock = await self._connect_sock(
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
llm-api-1         |     await self.sock_connect(sock, address)
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
llm-api-1         |     return await fut
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
llm-api-1         |     raise OSError(err, f'Connect call failed {address}')
llm-api-1         | ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.65.254', 11434)
llm-api-1         |
llm-api-1         | The above exception was the direct cause of the following exception:
llm-api-1         |
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
llm-api-1         |     yield
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
llm-api-1         |     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 232, in connect_tcp
llm-api-1         |     raise OSError("All connection attempts failed") from cause
llm-api-1         | OSError: All connection attempts failed
llm-api-1         |
llm-api-1         | The above exception was the direct cause of the following exception:
llm-api-1         |
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
llm-api-1         |     yield
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
llm-api-1         |     resp = await self._pool.handle_async_request(req)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
llm-api-1         |     raise exc
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
llm-api-1         |     response = await connection.handle_async_request(request)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
llm-api-1         |     raise exc
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
llm-api-1         |     stream = await self._connect(request)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 124, in _connect
llm-api-1         |     stream = await self._network_backend.connect_tcp(**kwargs)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
llm-api-1         |     return await self._backend.connect_tcp(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 121, in connect_tcp
llm-api-1         |     stream._raw_socket.setsockopt(*option)  # type: ignore[attr-defined] # pragma: no cover
llm-api-1         |   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
llm-api-1         |     self.gen.throw(typ, value, traceback)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
llm-api-1         |     raise to_exc(exc) from exc
llm-api-1         | httpcore.ConnectError: All connection attempts failed
llm-api-1         |
llm-api-1         | The above exception was the direct cause of the following exception:
llm-api-1         |
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/llms/ollama.py", line 252, in ollama_async_streaming
llm-api-1         |     async with client.stream(
llm-api-1         |   File "/usr/local/lib/python3.9/contextlib.py", line 181, in __aenter__
llm-api-1         |     return await self.gen.__anext__()
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1573, in stream
llm-api-1         |     response = await self.send(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1617, in send
llm-api-1         |     response = await self._send_handling_auth(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
llm-api-1         |     response = await self._send_handling_redirects(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
llm-api-1         |     response = await self._send_single_request(request)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1719, in _send_single_request
llm-api-1         |     response = await transport.handle_async_request(request)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
llm-api-1         |     resp = await self._pool.handle_async_request(req)
llm-api-1         |   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
llm-api-1         |     self.gen.throw(typ, value, traceback)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
llm-api-1         |     raise mapped_exc(message) from exc
oauth2-proxy-1    | 192.168.65.1:32392 - faf79db5-22a2-447b-a78e-b853db8ad090 - bionicgpt.1fzq6@8alias.com [2024/02/03 02:49:29] localhost:7800 POST / "/completions/37" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 200 14 0.703
llm-api-1         | httpx.ConnectError: All connection attempts failed
llm-api-1         | INFO:     172.19.0.4:33606 - "POST /v1/chat/completions HTTP/1.1" 200 OK
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 170, in try_connect
llm-api-1         |     stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2258, in connect_tcp
llm-api-1         |     await get_running_loop().create_connection(
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
llm-api-1         |     raise exceptions[0]
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
llm-api-1         |     sock = await self._connect_sock(
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
llm-api-1         |     await self.sock_connect(sock, address)
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
llm-api-1         |     return await fut
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
llm-api-1         |     raise OSError(err, f'Connect call failed {address}')
llm-api-1         | ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.65.254', 11434)
llm-api-1         |
llm-api-1         | The above exception was the direct cause of the following exception:
llm-api-1         |
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 10, in map_exceptions
llm-api-1         |     yield
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
llm-api-1         |     stream: anyio.abc.ByteStream = await anyio.connect_tcp(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 232, in connect_tcp
llm-api-1         |     raise OSError("All connection attempts failed") from cause
llm-api-1         | OSError: All connection attempts failed
llm-api-1         |
llm-api-1         | The above exception was the direct cause of the following exception:
llm-api-1         |
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 66, in map_httpcore_exceptions
llm-api-1         |     yield
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
llm-api-1         |     resp = await self._pool.handle_async_request(req)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 268, in handle_async_request
llm-api-1         |     raise exc
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 251, in handle_async_request
llm-api-1         |     response = await connection.handle_async_request(request)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
llm-api-1         |     raise exc
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
llm-api-1         |     stream = await self._connect(request)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 124, in _connect
llm-api-1         |     stream = await self._network_backend.connect_tcp(**kwargs)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
llm-api-1         |     return await self._backend.connect_tcp(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 121, in connect_tcp
llm-api-1         |     stream._raw_socket.setsockopt(*option)  # type: ignore[attr-defined] # pragma: no cover
llm-api-1         |   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
llm-api-1         |     self.gen.throw(typ, value, traceback)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
llm-api-1         |     raise to_exc(exc) from exc
llm-api-1         | httpcore.ConnectError: All connection attempts failed
llm-api-1         |
llm-api-1         | The above exception was the direct cause of the following exception:
llm-api-1         |
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/litellm/llms/ollama.py", line 252, in ollama_async_streaming
llm-api-1         |     async with client.stream(
llm-api-1         |   File "/usr/local/lib/python3.9/contextlib.py", line 181, in __aenter__
llm-api-1         |     return await self.gen.__anext__()
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1573, in stream
llm-api-1         |     response = await self.send(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1617, in send
llm-api-1         |     response = await self._send_handling_auth(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
llm-api-1         |     response = await self._send_handling_redirects(
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
llm-api-1         |     response = await self._send_single_request(request)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1719, in _send_single_request
llm-api-1         |     response = await transport.handle_async_request(request)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 366, in handle_async_request
llm-api-1         |     resp = await self._pool.handle_async_request(req)
llm-api-1         |   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
llm-api-1         |     self.gen.throw(typ, value, traceback)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 83, in map_httpcore_exceptions
llm-api-1         |     raise mapped_exc(message) from exc
llm-api-1         | httpx.ConnectError: All connection attempts failed
```

**Comment by ghost** [comment]
this doesn't look related to litellm, since the stack trace has no litellm files 

all i see is bionic gpt : 
> oauth2-proxy-1    | 192.168.65.1:32391 - 4328f17e-c1ff-414d-997e-317c32e9d1f2 - bionicgpt.1fzq6@8alias.com [2024/02/03 02:49:29] localhost:7800 POST / "/app/team/1/update_response" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 303 0 0.008
oauth2-proxy-1    | 192.168.65.1:32391 - 498acd5d-e0d9-469f-8484-ae49e379322d - bionicgpt.1fzq6@8alias.com [2024/02/03 02:49:29] localhost:7800 GET / "/app/team/1/console/1" HTTP/1.1 "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:122.0) Gecko/20100101 Firefox/122.0" 200 14429 0.003
llm-api-1         | INFO:     172.19.0.4:33600 - "POST /v1/chat/completions HTTP/1.1" 200 OK
llm-api-1         | Traceback (most recent call last):
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/anyio/_core/_sockets.py", line 170, in try_connect
llm-api-1         |     stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
llm-api-1         |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 2258, in connect_tcp
llm-api-1         |     await get_running_loop().create_connection(
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1065, in create_connection
llm-api-1         |     raise exceptions[0]
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1050, in create_connection
llm-api-1         |     sock = await self._connect_sock(
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 961, in _connect_sock
llm-api-1         |     await self.sock_connect(sock, address)
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 500, in sock_connect
llm-api-1         |     return await fut
llm-api-1         |   File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 535, in _sock_connect_cb
llm-api-1         |     raise OSError(err, f'Connect call failed {address}')
llm-api-1         | ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.65.254', 11434)

**Comment by ghost** [comment]
would recommend reaching out to the bionicgpt about this 

I see a potential connection issue on port 11434 which is ollama related - and would only happen if you're trying to call an ollama model but it's not running on the port 

> ConnectionRefusedError: [Errno 111] Connect call failed ('192.168.65.254', 11434)
