### ISSUE TITLE
[Bug]: Proxy Config.yaml without litellm_settings fails 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#1848]
### What happened?

Create a proxy config.yaml without a section for `litellm_settings` . Proxy fails when making /chat/completion calls 

for this issue please add a test to ensure this does not happen again 

### Relevant log output

```shell
Internal Server Error (500) · {"error":{"message":"'NoneType' object has no attribute 'get'\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 2132, in chat_completion\n    team_config = await proxy_config.load_team_config(\n  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 1076, in load_team_config\n    all_teams_config = litellm_settings.get("default_team_settings", None)\nAttributeError: 'NoneType' object has no attribute 'get'\n","type":"None","param":"None","code":500}}
```

**Comment by ishaan-jaff** [comment]
fixed: https://github.com/BerriAI/litellm/commit/5a29f362eefbc23baa1605437de7e08b3a75090d
