### ISSUE TITLE
Ollama `format` argument rejected {"error":"invalid options: format"}

### ISSUE THREAD

**Issue by MattyRad** [BerriAI/litellm#1850]
The docs suggest `format` is available for ollama. https://docs.litellm.ai/docs/providers/ollama#example-usage---json-mode

```python
    response = completion(
        model="ollama/mistral",
        messages=[{ "content": content,"role": "user"}],
        api_base="redacted",
        temperature=0.01,
        format="json"
    )
```

```
Traceback (most recent call last):
  File "/home/x/.local/lib/python3.10/site-packages/litellm/main.py", line 1665, in completion
    generator = ollama.get_ollama_response(
  File "/home/x/.local/lib/python3.10/site-packages/litellm/llms/ollama.py", line 187, in get_ollama_response
    raise OllamaError(status_code=response.status_code, message=response.text)
litellm.llms.ollama.OllamaError: {"error":"invalid options: format"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/x/projects/qualendar/core/run.py", line 8, in <module>
    response = completion(
  File "/home/x/.local/lib/python3.10/site-packages/litellm/utils.py", line 2455, in wrapper
    raise e
  File "/home/x/.local/lib/python3.10/site-packages/litellm/utils.py", line 2358, in wrapper
    result = original_function(*args, **kwargs)
  File "/home/x/.local/lib/python3.10/site-packages/litellm/main.py", line 1880, in completion
    raise exception_type(
  File "/home/x/.local/lib/python3.10/site-packages/litellm/utils.py", line 7462, in exception_type
    raise e
  File "/home/x/.local/lib/python3.10/site-packages/litellm/utils.py", line 7430, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: {"error":"invalid options: format"}
```

I'm using 1.22.3:

```
Requirement already satisfied: litellm in /home/x/.local/lib/python3.10/site-packages (1.22.3)
```

**Comment by ghost** [comment]
fix pushed - https://github.com/BerriAI/litellm/commit/d1db67890c7f70b4bd94269e4ffd59d715052783

should be live soon in v`1.22.8`.
