### ISSUE TITLE
[Bug]: Streaming response doesn't work in OpenAI Proxy for the gemini/gemini-pro model

### ISSUE THREAD

**Issue by limcheekin** [BerriAI/litellm#1861]
### What happened?

I re-deployed the latest version of docker image at [main-v1.22.10](https://github.com/berriai/litellm/pkgs/container/litellm/175766005?tag=main-v1.22.10). 
It works when the `"stream": false`, but not `"stream": true`.

You should be able to re-produce the error with the following curl command: 
```
curl --request POST --url https://litellm-f05q.onrender.com/v1/chat/completions -H 'Content-Type: application/json' --data '{ 
  "messages": [
    {
      "role": "user",
      "content": "What is Large Language Model?"
    }
  ],
  "model": "gemini/gemini-pro",
  "stream": true,
  "n": 1,
  "temperature": 0.1,
  "top_p": 0.9,
  "api_key": "Your API key"
}'
```
Please see the log out for the error trace.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 1752, in async_data_generator
    async for chunk in response:
TypeError: 'async for' requires an object with __aiter__ method, got GenerateContentResponse
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 264, in __call__
    await wrap(partial(self.listen_for_disconnect, receive))
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 260, in wrap
    await func()
  File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 237, in listen_for_disconnect
    message = await receive()
  File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 564, in receive
    await self.message_event.wait()
  File "/usr/local/lib/python3.9/asyncio/locks.py", line 226, in wait
    await fut
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f08bc602f10
During handling of the above exception, another exception occurred:
  + Exception Group Traceback (most recent call last):
  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
  |     result = await app(  # type: ignore[func-returns-value]
  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
  |     return await self.app(scope, receive, send)
  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
  |     await super().__call__(scope, receive, send)
  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
  |     raise exc
  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
  |     await self.app(scope, receive, _send)
  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
  |     await self.app(scope, receive, send)
  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
  |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  |   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 758, in __call__
  |     await self.middleware_stack(scope, receive, send)
  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 778, in app
  |     await route.handle(scope, receive, send)
  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 299, in handle
  |     await self.app(scope, receive, send)
  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 79, in app
  |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  |   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
  |     raise exc
  |   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
  |     await app(scope, receive, sender)
  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
  |     await response(scope, receive, send)
  |   File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 264, in __call__
  |     await wrap(partial(self.listen_for_disconnect, receive))
  |   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 678, in __aexit__
  |     raise BaseExceptionGroup(
  | exceptiongroup.ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 1752, in async_data_generator
    |     async for chunk in response:
    | TypeError: 'async for' requires an object with __aiter__ method, got GenerateContentResponse
    | 
    | During handling of the above exception, another exception occurred:
    | 
    | Traceback (most recent call last):
    |   File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 260, in wrap
    |     await func()
    |   File "/usr/local/lib/python3.9/site-packages/starlette/responses.py", line 249, in stream_response
    |     async for chunk in self.body_iterator:
    |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 1792, in async_data_generator
    |     raise ProxyException(
    | litellm.proxy.proxy_server.ProxyException
    +------------------------------------
```

**Comment by bakaraman** [comment]
Same for me

**Comment by ishaan-jaff** [comment]
I can confirm this works for me on latest version 

```
curl --location 'http://localhost:4000/chat/completions' \
    --header 'Authorization: Bearer sk-1234' \
    --header 'Content-Type: application/json' \
    --data '{
    "model": "gemini",
    "user": "yoooo",
    "n": 1,
    "temperature": 0.1,
    "top_p": 0.9,
    "stream": true,
    "messages": [
        {
        "role": "user",
        "content": "gm who are u"
        }
    ]
}'
```
