### ISSUE TITLE
I am getting     raise Exception(f"[Non-Blocking] LiteLLM.Success_Call Error: {str(e)}") Exception: [Non-Blocking] LiteLLM.Success_Call Error: dictionary changed size during iteration

### ISSUE THREAD

**Issue by kedarthakar** [BerriAI/litellm#1889]
I am running Mistral with liteLLM and I get the following error when I ask a query through my code - 

Exception in thread Thread-2 (success_handler):
Traceback (most recent call last):
  File "/home/thakar/nokia_llm_2/lib/python3.11/site-packages/litellm/utils.py", line 1055, in _success_handler_helper_fn
    verbose_logger.debug(f"Model={self.model}; result={result}")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thakar/nokia_llm_2/lib/python3.11/site-packages/openai/_models.py", line 82, in __str__
    return f'{self.__repr_name__()}({self.__repr_str__(", ")})'  # type: ignore[misc]
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thakar/nokia_llm_2/lib/python3.11/site-packages/pydantic/_internal/_repr.py", line 55, in __repr_str__
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thakar/nokia_llm_2/lib/python3.11/site-packages/pydantic/_internal/_repr.py", line 55, in <genexpr>
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thakar/nokia_llm_2/lib/python3.11/site-packages/pydantic/main.py", line 919, in __repr_args__
    for k, v in self.__dict__.items():
RuntimeError: dictionary changed size during iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/thakar/nokia_llm_2/lib/python3.11/site-packages/litellm/utils.py", line 1128, in success_handler
    start_time, end_time, result = self._success_handler_helper_fn(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/thakar/nokia_llm_2/lib/python3.11/site-packages/litellm/utils.py", line 1122, in _success_handler_helper_fn
    raise Exception(f"[Non-Blocking] LiteLLM.Success_Call Error: {str(e)}")
Exception: [Non-Blocking] LiteLLM.Success_Call Error: dictionary changed size during iteration

**Comment by ishaan-jaff** [comment]
Hi @kedarthakar - thanks for raising this issue - can we hop a quick call and debug this together ? 

Sharing my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat?month=2024-02

**Comment by thiswillbeyourgithub** [comment]
I frequently see the same error message. I noticed that it seems to always work if I re run the call for some reason so I'm guessing this has to do with the caching?

**Comment by ishaan-jaff** [comment]
@thiswillbeyourgithub can you share some code to repro this ?

**Comment by ishaan-jaff** [comment]
I'm unable to repro this error on the proxy and on litellm.completion

**Comment by thiswillbeyourgithub** [comment]
Have you tried setting `litellm.set_verbose=True` ?

I don't have a reproduction code. It happens every so often on the first run of scripts I use. Trying again always worked on the first try.

**Comment by thiswillbeyourgithub** [comment]
I have a hunch it might be related to this: https://github.com/pydantic/pydantic/issues/7832


Here's another output log:
```
23:18:06 - LiteLLM:INFO: Wrapper: Completed Call, calling success_handler
Exception in thread Thread-8 (success_handler):
Traceback (most recent call last):
  File "/USER/.pyenv/versions/v2anki311/lib/python3.11/site-packages/litellm/utils.py", line 1059, in _success_handler_helper_fn
    verbose_logger.debug(f"Model={self.model}; result={result}")
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/USER/.pyenv/versions/v2anki311/lib/python3.11/site-packages/openai/_models.py", line 76, in __str__
    return f'{self.__repr_name__()}({self.__repr_str__(", ")})'  # type: ignore[misc]
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/USER/.pyenv/versions/v2anki311/lib/python3.11/site-packages/pydantic/_internal/_repr.py", line 55, in __repr_str__
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/USER/.pyenv/versions/v2anki311/lib/python3.11/site-packages/pydantic/_internal/_repr.py", line 55, in <genexpr>
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/USER/.pyenv/versions/v2anki311/lib/python3.11/site-packages/pydantic/main.py", line 919, in __repr_args__
    for k, v in self.__dict__.items():
RuntimeError: dictionary changed size during iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/USER/.pyenv/versions/3.11.7/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/USER/.pyenv/versions/3.11.7/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/USER/.pyenv/versions/v2anki311/lib/python3.11/site-packages/litellm/utils.py", line 1132, in success_handler
    start_time, end_time, result = self._success_handler_helper_fn(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/USER/.pyenv/versions/v2anki311/lib/python3.11/site-packages/litellm/utils.py", line 1126, in _success_handler_helper_fn
    raise Exception(f"[Non-Blocking] LiteLLM.Success_Call Error: {str(e)}")


```

**Comment by thiswillbeyourgithub** [comment]
Update: this does not happen (or at least not frequently) with mistral-embed but happens on apparently every call to embeddings via openai's text embedding (small and large, I haven't tested ada2).

**Comment by ishaan-jaff** [comment]
Fix PR here: https://github.com/BerriAI/litellm/pull/2378
