### ISSUE TITLE
[Bug]: handle amazon titan null response scenario 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1897]
### What happened?

when amazon titan returns an empty string, it throws an error 

### Relevant log output

```shell
ServiceUnavailableError: BedrockException - Traceback (most recent call last):
  File "/Users/dleen/code/copilot/litellm/litellm/llms/bedrock.py", line 755, in completion
    encoding.encode(
  File "/Users/dleen/mambaforge/envs/jlab4/lib/python3.10/site-packages/tiktoken/core.py", line 116, in encode
    if match := _special_token_regex(disallowed_special).search(text):
TypeError: expected string or buffer
```

**Comment by ghost** [comment]
able to repro error

**Comment by ghost** [comment]
fix pushed - https://github.com/BerriAI/litellm/commit/841639333b3ba0007f686767536a1acc9cfc3b56
