### ISSUE TITLE
[Bug]: promptlayer integration not working 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#1963]
### What happened?

![image](https://github.com/BerriAI/litellm/assets/17561003/1f2a0e5f-d16d-4f8a-ac4a-d9ce99f564c6)

**Comment by lmyslinski** [comment]
Facing the same issue, I've turned verbose mode on and this is what I've found:

```
Prompt Layer Logging - Enters logging function for model kwargs: {'model': 'cv-parser-long', 'messages': ...', role='assistant'))], created=1708446358, model='gpt-35-turbo-16k', object='chat.completion', system_fingerprint=None, usage=Usage(completion_tokens=68, prompt_tokens=400, total_tokens=468))
ModelResponse(id='chatcmpl-8uNEMgT6EQZ05fnK6EpmZPpTd7Dl3', choices=[Choices(finish_reason='stop', index=0, message=Message(content='...'))], created=1708446358, model='gpt-35-turbo-16k', object='chat.completion', system_fingerprint=None, usage=Usage(completion_tokens=68, prompt_tokens=400, total_tokens=468))
error: Prompt Layer Error - Traceback (most recent call last):
  File "/Users/.../app/.venv/lib/python3.11/site-packages/litellm/integrations/prompt_layer.py", line 32, in log_event
  ...
  File "/Users/.../app/.venv/lib/python3.11/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.7/Frameworks/Python.framework/Versions/3.11/lib/python3.11/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Choices is not JSON serializable

```

**Comment by ishaan-jaff** [comment]
we have a PR that fixes this: https://github.com/BerriAI/litellm/pull/1491

**Comment by lmyslinski** [comment]
@ishaan-jaff I was about to cross-reference you over there - I've just worked around this by adding json serialization to `Choices`, but I don't see that in the PR - at a quick glance, you're just sending specific fields instead of the entire kwargs object to the same effect, correct?

Edit: sorry, just noticed you're the reviewer, not the author :)

**Comment by samyxdev** [comment]
Hello @lmyslinski, I am the author of the previously mentioned PR. I was serializing the choices using the following:
https://github.com/BerriAI/litellm/blob/fe9b511e45dcd70d908f70b9821ecac538aff86c/litellm/integrations/prompt_layer.py#L43

Were you thinking about something else ?

**Comment by lmyslinski** [comment]
Hey @samyxdev, sorry but I had other work to complete first and had sidelined this effort - I've tested your PR previously & it worked just fine, let me give it another try now off the main release

**Comment by ishaan-jaff** [comment]
fix PR is merged
