### ISSUE TITLE
[Bug]: KeyError: content

### ISSUE THREAD

**Issue by themrzmaster** [BerriAI/litellm#1987]
### What happened?

When i try to send a request using openai client and the message is a list with a ChatCompletionMessage object that the content equals None, like when it is a function call:

[{'role': 'user', 'content': 'o que tem no meu carrinho'}, ChatCompletionMessage(content=None, role='assistant', function_call=None, tool_calls=[ChatCompletionMessageToolCall(id='call_S14nnNStRl1ZcZrd8XO33GuD', function=Function(arguments='{}', name='get_current_cart'), type='function')]), {'role': 'tool', 'content': '{}', 'tool_call_id': 'call_S14nnNStRl1ZcZrd8XO33GuD', 'name': 'get_current_cart'}]

I get error 500.
standard openai call works

### Relevant log output

```shell
Error calling the API: Error code: 500 - {'error': {'message': '\'content\'\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 2378, in chat_completion\n    response = await llm_router.acompletion(**data)\n  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 368, in acompletion\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 364, in acompletion\n    response = await self.async_function_with_fallbacks(**kwargs)\n  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 1042, in async_function_with_fallbacks\n    raise original_exception\n  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 965, in async_function_with_fallbacks\n    response = await self.async_function_with_retries(*args, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 1101, in async_function_with_retries\n    raise original_exception\n  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 1059, in async_function_with_retries\n    response = await original_function(*args, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 444, in _acompletion\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 423, in _acompletion\n    response = await litellm.acompletion(\n  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2908, in wrapper_async\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2504, in wrapper_async\n    logging_obj, kwargs = function_setup(start_time, *args, **kwargs)\n  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2146, in function_setup\n    raise e\n  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2088, in function_setup\n    input="".join(\n  File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2091, in <genexpr>\n    if isinstance(m["content"], str)\nKeyError: \'content\'\n', 'type': 'None', 'param': 'None', 'code': 500}}
```

**Comment by ishaan-jaff** [comment]
Hi @themrzmaster we can debug this live with you right now: https://meet.google.com/iqu-rrfj-zte

**Comment by themrzmaster** [comment]
@ishaan-jaff any update on this? thanks

**Comment by ghost** [comment]
@themrzmaster can you share a test script for repro

**Comment by themrzmaster** [comment]
sorry guys, i guess the problem is with openai client https://github.com/openai/openai-python/issues/777
