### ISSUE TITLE
[Bug]: LiteLLM Langfuse integration: Image gen API calls render error about mismatched response format

### ISSUE THREAD

**Issue by cwang** [BerriAI/litellm#2000]
### What happened?

Because LiteLLM returns different response format for image gen (and potentially other multi-modal model use) such as DALL-E, the Langfuse integration still expects the same path `response_obj["choices"][0]["message"].json()` which doesn't exist. It should be an easy fix. 

cc @maxdeichmann 

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/cw5d/Projects/5dai/prompt-runner/.venv/lib/python3.11/site-packages/pydantic/main.py", line 753, in __getattr__
    return pydantic_extra[item]
           ~~~~~~~~~~~~~~^^^^^^
KeyError: 'choices'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/cw5d/Projects/5dai/prompt-runner/.venv/lib/python3.11/site-packages/litellm/integrations/langfuse.py", line 66, in log_event
    output = response_obj["choices"][0]["message"].json()
             ~~~~~~~~~~~~^^^^^^^^^^^
  File "/Users/cw5d/Projects/5dai/prompt-runner/.venv/lib/python3.11/site-packages/litellm/utils.py", line 675, in __getitem__
    return getattr(self, key)
           ^^^^^^^^^^^^^^^^^^
  File "/Users/cw5d/Projects/5dai/prompt-runner/.venv/lib/python3.11/site-packages/pydantic/main.py", line 755, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
AttributeError: 'ImageResponse' object has no attribute 'choices'
```

**Comment by ghost** [comment]
acknowledging this

**Comment by ghost** [comment]
This is now merged. Should be out in the next release

**Comment by ghost** [comment]
Live in v`1.24.6`

@cwang can you let me know if this solves your problem?

Would love to do a ~10 mins to chat this/next week, if possible, to learn how you're using litellm 

https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by maxdeichmann** [comment]
FYI, at Langfuse, we filter our base64 strings from the prompts to multimodal models until we support multimodality also in our UI.
