### ISSUE TITLE
[Bug]: PII masking not working

### ISSUE THREAD

**Issue by vchaindz** [BerriAI/litellm#2034]
### What happened?

I wanted to try out the new PII masking feature using version 1.24.6.
Presidio container are running and are responding:
```
9045b49e33ef   mcr.microsoft.com/presidio-anonymizer:latest   "/bin/sh -c 'pipenv …"   5 hours ago      Up 5 hours      0.0.0.0:5002->3000/tcp, :::5002->3000/tcp   crazy_williamson
6766ffccbd1f   mcr.microsoft.com/presidio-analyzer:latest     "/bin/sh -c 'pipenv …"   5 hours ago      Up 5 hours      0.0.0.0:5001->3000/tcp, :::5001->3000/tcp   tender_meitner
```

my settings in the config.yaml:
```
litellm_settings:
  input_callback: ["presidio"]
```
and .env (also manually loaded with export):
```
PRESIDIO_ANALYZER_API_BASE="http://localhost:5002"
PRESIDIO_ANONYMIZER_API_BASE="http://localhost:5001"
```

running a completions:
```
curl --location 'http://0.0.0.0:8000/chat/completions' \ 
    --header 'Authorization: Bearer sk-' \
    --header 'Content-Type: application/json' \
    --data '{
        "model": "gpt-3.5-turbo",
        "messages": [
            {
                "role": "user",
                "content": "hello world, my name is Jane Doe. My number is: 034453334. Reply with my number"
            }
        ]
    }'
```

I would expect that the number and the name are anonymized. I checked the debug output and the number or name are never changed.
Anything that I miss?

### Relevant log output

```shell
{"id":"chatcmpl-8tH1l96dMA3eUaFuPgPIGLTJNZmsm","choices":[{"finish_reason":"stop","index":0,"message":{"content":"Your number is: 034453334","role":"assistant"}}],"created":1708184185,"model":"gpt-3.5-turbo-0125","object":"chat.completion","system_fingerprint":"fp_69829325d0","usage":{"completion_tokens":8,"prompt_tokens":29,"total_tokens":37}}
```

**Comment by ghost** [comment]
@vchaindz It's a callback not an input_callback 

Just change the liteLLM setting and let me know if that works

**Comment by vchaindz** [comment]
thanks @krrishdholakia for the quick reply. Changing it to `callbacks: ["presidio"]` worked, seems I copy/pasted wrong.
But now I get an error running the same curl request:
```
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.11/site-packages/litellm/proxy/hooks/presidio_pii_masking.py", line 91, in check_pii
    for item in redacted_text["items"]:
                ~~~~~~~~~~~~~^^^^^^^^^
KeyError: 'items'
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2422, in chat_completion
    data = await proxy_logging_obj.pre_call_hook(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 129, in pre_call_hook
    raise e
  File "/home/user/.local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 117, in pre_call_hook
    response = await callback.async_pre_call_hook(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/litellm/proxy/hooks/presidio_pii_masking.py", line 145, in async_pre_call_hook
    responses = await asyncio.gather(*tasks)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/.local/lib/python3.11/site-packages/litellm/proxy/hooks/presidio_pii_masking.py", line 109, in check_pii
    raise e
  File "/home/user/.local/lib/python3.11/site-packages/litellm/proxy/hooks/presidio_pii_masking.py", line 91, in check_pii
    for item in redacted_text["items"]:
                ~~~~~~~~~~~~~^^^^^^^^^
```
Any idea?

**Comment by ghost** [comment]
I'm assuming your presidio api response has items, does it not? 

Happy to hop on a quick call to debug this - https://meet.google.com/ait-zbvp-xrh

**Comment by ghost** [comment]
Closing as we debugged this on the call @vchaindz
