### ISSUE TITLE
[Bug]: /model/info fails when user does not use a config.yaml 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2061]
### What happened?

i run it as a command: command: ["--model", "gpt-3.5-turbo", 

### Relevant log output

```shell
litellm_1              | INFO:     192.168.0.72:50876 - "GET /model/info HTTP/1.1" 500 Internal Server Error
litellm_1              | ERROR:    Exception in ASGI application
litellm_1              | Traceback (most recent call last):
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
litellm_1              |     result = await app(  # type: ignore[func-returns-value]
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
litellm_1              |     return await self.app(scope, receive, send)
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
litellm_1              |     await super().__call__(scope, receive, send)
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
litellm_1              |     await self.middleware_stack(scope, receive, send)
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
litellm_1              |     raise exc
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
litellm_1              |     await self.app(scope, receive, _send)
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__
litellm_1              |     await self.app(scope, receive, send)
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
litellm_1              |     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
litellm_1              |     raise exc
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
litellm_1              |     await app(scope, receive, sender)
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 758, in __call__
litellm_1              |     await self.middleware_stack(scope, receive, send)
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 778, in app
litellm_1              |     await route.handle(scope, receive, send)
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 299, in handle
litellm_1              |     await self.app(scope, receive, send)
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 79, in app
litellm_1              |     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
litellm_1              |     raise exc
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
litellm_1              |     await app(scope, receive, sender)
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 74, in app
litellm_1              |     response = await func(request)
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 299, in app
litellm_1              |     raise e
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 294, in app
litellm_1              |     raw_response = await run_endpoint_function(
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
litellm_1              |     return await dependant.call(**values)
litellm_1              |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 4334, in model_info_v1
litellm_1              |     all_models = config["model_list"]
litellm_1              | KeyError: 'model_list'
```

**Comment by ishaan-jaff** [comment]
fixed on /v2/model/info
