### ISSUE TITLE
[Bug]: LiteLLM_VerificationToken Records Keep Growing?

### ISSUE THREAD

**Issue by dkindlund** [BerriAI/litellm#2115]
### What happened?

Every-time a redeploy the LiteLLM OpenAI Proxy container with the same `config.yaml` settings, I'm noticing that the number of `LiteLLM_VerificationToken` records in the PostgreSQL database appears to be growing with no end in sight.

Most of the records are linked to the `user_id` of `litellm-proxy-budget`.

My `config.yaml` consists of:

- 2 model groups
  - 1 group is for GPT-4 completions containing 2 endpoints
  - 1 group is for Embeddings containing 2 endpoints
- Using a `routing_strategy` of `latency-based-routing` with a `routing_strategy_args` of `{"ttl": 10}`

The current total number of `LiteLLM_VerificationToken` records is **85** <-- that seems very high.  Can someone sanity check this for me?  Thanks!

**Comment by ghost** [comment]
I suspect this is causing it - https://github.com/BerriAI/litellm/blob/9f753ab194a302ce4bc52bada37ca9986b7c3624/litellm/proxy/proxy_server.py#L2202

It should be upserting the proxy budget and any mods made during proxy startup (making sure global budget is in the db for tracking) 

Will investigate why it keeps adding new rows @dkindlund

**Comment by dkindlund** [comment]
Thanks, @krrishdholakia .

Every time the container restarts, I see these entries in the logs:
```
[92m22:27:59 - LiteLLM Proxy:INFO[0m: [91mDB User Table - update succeeded user_id='litellm-proxy-budget' team_id=None user_role='app_user' max_budget=100.0 spend=0.0 user_email=None models=[] max_parallel_requests=None tpm_limit=None rpm_limit=None budget_duration='30d' budget_reset_at=datetime.datetime(2024, 3, 19, 20, 3, 23, 71000, tzinfo=TzInfo(UTC)) allowed_cache_controls=[][0m
[92m22:27:59 - LiteLLM Proxy:INFO[0m: Data Inserted into Keys Table
```

It feels like it's just blindly inserting new keys into the DB without checking whether or not any matching keys already exist.

As a mitigation, @krrishdholakia -- please let me know if there's a periodic SQL command I can run to help clean this up -- or if your long-term fix will "clean up" any stale keys.

**Comment by dkindlund** [comment]
I'm also seeing these errors in the logs:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/utils.py", line 564, in get_data
    response = await self.db.litellm_verificationtoken.find_many(
  File "/usr/local/lib/python3.9/site-packages/prisma/actions.py", line 2506, in find_many
    resp = await self._client._execute(
  File "/usr/local/lib/python3.9/site-packages/prisma/client.py", line 495, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
  File "/usr/local/lib/python3.9/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_response_errors(resp, errors_data)
  File "/usr/local/lib/python3.9/site-packages/prisma/engine/utils.py", line 200, in handle_response_errors
    raise prisma_errors.DataError(data[0])
prisma.errors.DataError: Can't reach database server at `10.93.32.3`:`5432`
```
and
```
Please make sure your database server is running at `10.93.32.3`:`5432`.
```
and
```
Giving up get_data(...) after 2 tries (prisma.errors.DataError: Can't reach database server at `10.93.32.3`:`5432`
```
and
```
Please make sure your database server is running at `10.93.32.3`:`5432`.)
```
and
```
Job "reset_budget (trigger: interval[0:09:59], next run at: 2024-02-21 21:49:57 UTC)" raised an exception
```
and
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/utils.py", line 1340, in reset_budget
    keys_to_reset = await prisma_client.get_data(
  File "/usr/local/lib/python3.9/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/utils.py", line 696, in get_data
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/proxy/utils.py", line 564, in get_data
    response = await self.db.litellm_verificationtoken.find_many(
  File "/usr/local/lib/python3.9/site-packages/prisma/actions.py", line 2506, in find_many
    resp = await self._client._execute(
  File "/usr/local/lib/python3.9/site-packages/prisma/client.py", line 495, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
  File "/usr/local/lib/python3.9/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
  File "/usr/local/lib/python3.9/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_response_errors(resp, errors_data)
  File "/usr/local/lib/python3.9/site-packages/prisma/engine/utils.py", line 200, in handle_response_errors
    raise prisma_errors.DataError(data[0])
prisma.errors.DataError: Can't reach database server at `10.93.32.3`:`5432`
```

**Comment by dkindlund** [comment]
When I view the `API Keys` page in the UI, I'm seeing this error in the Google Chrome console:
```
Mixed Content: The page at 'https://llm.fletch.ai/ui/?userID=105366351216706200990&token=ey...' was loaded over HTTPS, but requested an insecure resource 'http://llm.fletch.ai/spend/users?user_id=litellm-proxy-budget'. This request has been blocked; the content must be served over HTTPS.
```

Not sure if that's related as well.

**Comment by ishaan-jaff** [comment]
> When I view the API Keys page in the UI, I'm seeing this error in the Google Chrome console:

This looks like a separate bug on the UI (I suspect it's the same as https://github.com/BerriAI/litellm/issues/2051)

@dkindlund can you confirm you can see your keys on the UI ?

**Comment by dkindlund** [comment]
Hey @ishaan-jaff , yeah, I can see my keys in the UI, but I don't think I can see all the other keys in the UI compared to issuing a direct SQL query in the PostgreSQL DB.  Yes, it looks like I might be encountering the same issue as https://github.com/BerriAI/litellm/issues/2051

**Comment by ishaan-jaff** [comment]
<img width="1070" alt="Screenshot 2024-02-22 at 9 23 20 PM" src="https://github.com/BerriAI/litellm/assets/29436595/afbcfe73-6141-469f-9013-562191bc60b6">

I'm able to repro the bug

**Comment by ishaan-jaff** [comment]
PR for this fix is here: https://github.com/BerriAI/litellm/pull/2150

**Comment by ishaan-jaff** [comment]
Script to delete stale keys @dkindlund 

```sql
DELETE FROM "LiteLLM_VerificationToken"
WHERE user_id = 'litellm-proxy-budget';

```

**Comment by dkindlund** [comment]
@ishaan-jaff , confirmed!  The issue appears resolved in my deployment.  Thanks for the SQL script -- it works perfectly.

**Comment by ishaan-jaff** [comment]
awesome !
