### ISSUE TITLE
[Bug]: Empty LiteLLM_Config on database image deploy

### ISSUE THREAD

**Issue by nxfi777** [BerriAI/litellm#2139]
### What happened?

I created an environment to run the OpenAI proxy with postgres.

Start command: `litellm --model gpt-3.5-turbo`

When I accessed the UI and logged in, the dashboard throws a 500 error.
The tables in postgres are created but due to `LiteLLM_Config` not containing any entries, the `/v2/model/info` endpoint does not work.

I attempted to create a write config with the `/config/update` endpoint, but it threw this error:
```json
{
  "error": {
    "message": "Invalid config passed in",
    "type": "auth_error",
    "param": "None",
    "code": 400
  }
}
```

This is because there is nothing in the table.

**NOTE:** I am in an environment where there is no way to run with `config.yaml` , or use docker compose,

500 error log: 
```shell
ERROR:    Exception in ASGI application

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi

result = await app(  # type: ignore[func-returns-value]

File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__

return await self.app(scope, receive, send)

File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__

await super().__call__(scope, receive, send)

File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__

await self.middleware_stack(scope, receive, send)

File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__

raise exc

File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__

await self.app(scope, receive, _send)

File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 83, in __call__

await self.app(scope, receive, send)

File "/usr/local/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 62, in __call__

await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app

raise exc

File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

await app(scope, receive, sender)

File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 758, in __call__

await self.middleware_stack(scope, receive, send)

File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 778, in app

await route.handle(scope, receive, send)

File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 299, in handle

await self.app(scope, receive, send)

File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 79, in app

await wrap_app_handling_exceptions(app, request)(scope, receive, send)

File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app

raise exc

File "/usr/local/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

await app(scope, receive, sender)

File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 74, in app

response = await func(request)

File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 299, in app

raise e

File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 294, in app

raw_response = await run_endpoint_function(

File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function

return await dependant.call(**values)

File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 4629, in model_info_v2

model_name = model.get("model_name", None)

AttributeError: 'str' object has no attribute 'get'
```

### Twitter / LinkedIn details

[LinkedIn](https://www.linkedin.com/in/rafaelaslanian/)

**Comment by ghost** [comment]
Hey @nxfi777 can you help me repro your environment, why can't you just mount the config?

**Comment by ghost** [comment]
Hey this should now work without needing to mount a confit
