### ISSUE TITLE
how to install greenbone openvas  on ubuntu 22.04

### ISSUE THREAD

**Issue by DaveBarrette** [BerriAI/litellm#2178]
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

        Python Version: 3.10.12
        Pip Version: 22.0.2
        Open-interpreter Version: cmd:Interpreter, pkg: 0.1.18
        OS Version and Architecture: Linux-6.5.0-21-generic-x86_64-with-glibc2.35
        CPU Info: x86_64
        RAM Info: 31.30 GB, used: 10.71, free: 0.92
        

        # Interpreter Info
        
        Vision: False
        Model: gpt-3.5-turbo-1106
        Function calling: True
        Context window: 16000
        Max tokens: 4096

        Auto run: False
        API base: None
        Offline: False

        Curl output: Not local

        # Messages

        System Message: You are Open Interpreter, a world-class programmer that can complete any goal by executing code.
First, write a plan. **Always recap the plan between each code block** (you have extreme short-term memory loss, so you need to recap the plan between each message block to retain it).
When you execute code, it will be executed **on the user's machine**. The user has given you **full and complete permission** to execute any code necessary to complete the task. Execute the code.
If you want to send data between programming languages, save the data to a txt or json.
You can access the internet. Run **any code** to achieve the goal, and if at first you don't succeed, try again and again.
You can install new packages.
When a user refers to a filename, they're likely referring to an existing file in the directory you're currently executing code in.
Write messages to the user in Markdown.
In general, try to **make plans** with as few steps as possible. As for actually executing code to carry out that plan, for *stateful* languages (like python, javascript, shell, but NOT for html which starts from 0 every time) **it's critical not to try to do everything in one code block.** You should try something, print information about it, then continue from there in tiny, informed steps. You will never get it on the first try, and attempting it in one go will often lead to errors you cant see.
You are capable of **any** task.

        {'role': 'user', 'type': 'message', 'content': 'No entry from user - please suggest something to enter.'}

{'role': 'user', 'type': 'message', 'content': 'how to install greenbone openvas  on ubuntu 22.04'}
    
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litellm/main.py", line 747, in completion
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/main.py", line 722, in completion
    response = openai_chat_completions.completion(
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 348, in completion
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 343, in completion
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 271, in completion
    return self.streaming(
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/openai.py", line 436, in streaming
    response = openai_client.chat.completions.create(**data, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/openai/_utils/_utils.py", line 272, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/openai/resources/chat/completions.py", line 645, in create
    return self._post(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 1088, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 853, in request
    return self._request(
  File "/usr/local/lib/python3.10/dist-packages/openai/_base_client.py", line 930, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': 'Incorrect API key provided: x. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/llm/llm.py", line 203, in fixed_litellm_completions
    yield from litellm.completion(**params)
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 2113, in wrapper
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 2020, in wrapper
    result = original_function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/litellm/main.py", line 1743, in completion
    raise exception_type(
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 6507, in exception_type
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 5475, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: OpenAIException - Error code: 401 - {'error': {'message': 'Incorrect API key provided: x. You can find your API key at https://platform.openai.com/account/api-keys.', 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_api_key'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/interpreter", line 8, in <module>
    sys.exit(interpreter.start_terminal_interface())
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 23, in start_terminal_interface
    start_terminal_interface(self)
  File "/usr/local/lib/python3.10/dist-packages/interpreter/terminal_interface/start_terminal_interface.py", line 636, in start_terminal_interface
    interpreter.chat()
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 68, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 80, in _streaming_chat
    yield from terminal_interface(self, message)
  File "/usr/local/lib/python3.10/dist-packages/interpreter/terminal_interface/terminal_interface.py", line 136, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 115, in _streaming_chat
    yield from self._respond_and_store()
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/core.py", line 161, in _respond_and_store
    for chunk in respond(self):
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/respond.py", line 49, in respond
    for chunk in interpreter.llm.run(messages_for_llm):
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/llm/llm.py", line 173, in run
    yield from run_function_calling_llm(self, params)
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/llm/run_function_calling_llm.py", line 44, in run_function_calling_llm
    for chunk in llm.completions(**request_params):
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/llm/llm.py", line 206, in fixed_litellm_completions
    raise first_error
  File "/usr/local/lib/python3.10/dist-packages/interpreter/core/llm/llm.py", line 187, in fixed_litellm_completions
    yield from litellm.completion(**params)
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 2113, in wrapper
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 2020, in wrapper
    result = original_function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/litellm/main.py", line 1743, in completion
    raise exception_type(
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 6507, in exception_type
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 5506, in exception_type
    raise RateLimitError(
litellm.exceptions.RateLimitError: OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

**Comment by ishaan-jaff** [comment]
This issue looks open interpreter specific, please file this there: https://github.com/KillianLucas/open-interpreter
