### ISSUE TITLE
[Bug]: Together_aiException - create() got an unexpected keyword argument 'repetition_penalty'

### ISSUE THREAD

**Issue by zu1k** [BerriAI/litellm#2192]
### What happened?

I'm using together.ai via OpenAI compatibile API, but get `OpenAIError` from openai-python, `Together_aiException - create() got an unexpected keyword argument 'repetition_penalty'`.

litellm version: `v1.27.4`

Here is my config file:

```
model_list:
  - model_name: qwen
    litellm_params:
      model: together_ai/Qwen/Qwen1.5-4B-Chat
      api_key: "my_api_key"

router_settings:
  routing_strategy: simple-shuffle
  timeout: 10

litellm_settings:
  drop_params: True
  set_verbose: True
```

Here is the solution: https://github.com/openai/openai-python/issues/767#issuecomment-1805294985

### Relevant log output

```shell
litellm  | Request to litellm:
litellm  | Traceback (most recent call last):
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/llms/openai.py", line 508, in async_streaming
litellm  |     response = await openai_aclient.chat.completions.create(
litellm  |   File "/usr/local/lib/python3.9/site-packages/openai/_utils/_utils.py", line 275, in wrapper
litellm  |     return func(*args, **kwargs)
litellm  | TypeError: create() got an unexpected keyword argument 'repetition_penalty'
litellm  | 
litellm  | During handling of the above exception, another exception occurred:
litellm  | 
litellm  | Traceback (most recent call last):
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 278, in acompletion
litellm  |     response = await init_response
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/llms/openai.py", line 532, in async_streaming
litellm  |     raise OpenAIError(status_code=500, message=f"{str(e)}")
litellm  | litellm.llms.openai.OpenAIError: create() got an unexpected keyword argument 'repetition_penalty'
litellm  | 
litellm  | During handling of the above exception, another exception occurred:
litellm  | 
litellm  | Traceback (most recent call last):
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 2609, in chat_completion
litellm  |     responses = await asyncio.gather(
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 380, in acompletion
litellm  |     raise e
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 376, in acompletion
litellm  |     response = await self.async_function_with_fallbacks(**kwargs)
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 1054, in async_function_with_fallbacks
litellm  |     raise original_exception
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 977, in async_function_with_fallbacks
litellm  |     response = await self.async_function_with_retries(*args, **kwargs)
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 1164, in async_function_with_retries
litellm  |     raise original_exception
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 1071, in async_function_with_retries
litellm  |     response = await original_function(*args, **kwargs)
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 456, in _acompletion
litellm  |     raise e
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 435, in _acompletion
litellm  |     response = await litellm.acompletion(
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2991, in wrapper_async
litellm  |     raise e
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2834, in wrapper_async
litellm  |     result = await original_function(*args, **kwargs)
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/main.py", line 291, in acompletion
litellm  |     raise exception_type(
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 7602, in exception_type
litellm  |     raise e
litellm  |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 6484, in exception_type
litellm  |     raise APIError(
litellm  | litellm.exceptions.APIError: Together_aiException - create() got an unexpected keyword argument 'repetition_penalty'
```

**Comment by zu1k** [comment]
Caused by https://github.com/BerriAI/litellm/blob/825c7fe3762add0ae98ede649965978e35a5b9fe/litellm/utils.py#L4272-L4275
