### ISSUE TITLE
[Bug]: LiteLLM.Success_Call Error: dictionary changed size during iteratio

### ISSUE THREAD

**Issue by prd-tuong-nguyen** [BerriAI/litellm#2245]
### What happened?

Got this error when testing with high concurrent user:
```
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    | Exception in thread Thread-1538:
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    | Traceback (most recent call last):
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1083, in _success_handler_helper_fn
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |     verbose_logger.debug(f"Model={self.model}; result={result}")
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |   File "/usr/local/lib/python3.9/site-packages/openai/_models.py", line 76, in __str__
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |     return f'{self.__repr_name__()}({self.__repr_str__(", ")})'  # type: ignore[misc]
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |   File "/usr/local/lib/python3.9/site-packages/pydantic/_internal/_repr.py", line 55, in __repr_str__
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |     return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |   File "/usr/local/lib/python3.9/site-packages/pydantic/_internal/_repr.py", line 55, in <genexpr>
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |     return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |   File "/usr/local/lib/python3.9/site-packages/pydantic/main.py", line 963, in __repr_args__
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |     for k, v in self.__dict__.items():
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    | RuntimeError: dictionary changed size during iteration
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    | 
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    | During handling of the above exception, another exception occurred:
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    | 
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    | Traceback (most recent call last):
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |   File "/usr/local/lib/python3.9/threading.py", line 980, in _bootstrap_inner
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |     self.run()
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/threading.py", line 72, in run
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |     reraise(*_capture_exception())
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/_compat.py", line 127, in reraise
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |     raise value
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |   File "/usr/local/lib/python3.9/site-packages/sentry_sdk/integrations/threading.py", line 70, in run
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |     return old_run_func(self, *a, **kw)
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |   File "/usr/local/lib/python3.9/threading.py", line 917, in run
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |     self._target(*self._args, **self._kwargs)
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1159, in success_handler
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |     start_time, end_time, result = self._success_handler_helper_fn(
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 1153, in _success_handler_helper_fn
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    |     raise Exception(f"[Non-Blocking] LiteLLM.Success_Call Error: {str(e)}")
llm_llm-proxy.8.p66u8vtpzcfe@regional-prod-llm-01-use1-1d-098a73af2185c2a3c    | Exception: [Non-Blocking] LiteLLM.Success_Call Error: dictionary changed size during iteratio
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/huytuong010101/

**Comment by ghost** [comment]
This looks like a pydantic error, seems to happen when logging the result.
<img width="946" alt="Screenshot 2024-02-29 at 11 55 41 AM" src="https://github.com/BerriAI/litellm/assets/17561003/981a9c21-4304-4dd8-b8b6-ebaebb68e627">


Do you have a script/way for me to repro?

**Comment by prd-tuong-nguyen** [comment]
@krrishdholakia You can start a proxy with `--num_workers 8`  and try testing with 1000 concurrent users.
I felt when I set the number of workers to 1. The problem was resolved.
Note: After this error is thrown, that worker will earn 100% CPU.

**Comment by ishaan-jaff** [comment]
Fix PR here: https://github.com/BerriAI/litellm/pull/2378
