### ISSUE TITLE
[Bug]: Missing `gpt-3.5-turbo-instruct-0914` in LiteLLM

### ISSUE THREAD

**Issue by CXwudi** [BerriAI/litellm#2272]
### What happened?

It looks like some models in OpenAI are not recognized as OpenAI's model, `gpt-3.5-turbo-instruct-0914` is one of them. 

The proxy server failed with `litellm.exceptions.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=gpt-3.5-turbo-instruct-0914`

Here is the screenshot showing that it is a valid model for chat completion, using a self-hosted LibreChat instance
![image](https://github.com/BerriAI/litellm/assets/17377423/c0cc77bb-7a5f-4dde-a2a0-c31c42e953de)

### Relevant log output
This is the log from docker compose
``` log
2024-02-29 21:35:46 litellm-server    | Traceback (most recent call last):
2024-02-29 21:35:46 litellm-server    |   File "/usr/local/bin/litellm", line 8, in <module>
2024-02-29 21:35:46 litellm-server    |     sys.exit(run_server())
2024-02-29 21:35:46 litellm-server    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
2024-02-29 21:35:46 litellm-server    |     return self.main(*args, **kwargs)
2024-02-29 21:35:46 litellm-server    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1078, in main
2024-02-29 21:35:46 litellm-server    |     rv = self.invoke(ctx)
2024-02-29 21:35:46 litellm-server    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
2024-02-29 21:35:46 litellm-server    |     return ctx.invoke(self.callback, **ctx.params)
2024-02-29 21:35:46 litellm-server    |   File "/usr/local/lib/python3.9/site-packages/click/core.py", line 783, in invoke
2024-02-29 21:35:46 litellm-server    |     return __callback(*args, **kwargs)
2024-02-29 21:35:46 litellm-server    |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_cli.py", line 428, in run_server
2024-02-29 21:35:46 litellm-server    |     _, _, general_settings = asyncio.run(
2024-02-29 21:35:46 litellm-server    |   File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
2024-02-29 21:35:46 litellm-server    |     return loop.run_until_complete(main)
2024-02-29 21:35:46 litellm-server    |   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
2024-02-29 21:35:46 litellm-server    |     return future.result()
2024-02-29 21:35:46 litellm-server    |   File "/usr/local/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 1777, in load_config
2024-02-29 21:35:46 litellm-server    |     router = litellm.Router(**router_params)  # type:ignore
2024-02-29 21:35:46 litellm-server    |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 195, in __init__
2024-02-29 21:35:46 litellm-server    |     self.set_model_list(model_list)
2024-02-29 21:35:46 litellm-server    |   File "/usr/local/lib/python3.9/site-packages/litellm/router.py", line 1898, in set_model_list
2024-02-29 21:35:46 litellm-server    |     ) = litellm.get_llm_provider(
2024-02-29 21:35:46 litellm-server    |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 5145, in get_llm_provider
2024-02-29 21:35:46 litellm-server    |     raise e
2024-02-29 21:35:46 litellm-server    |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 5132, in get_llm_provider
2024-02-29 21:35:46 litellm-server    |     raise litellm.exceptions.BadRequestError(  # type: ignore
2024-02-29 21:35:46 litellm-server    | litellm.exceptions.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=gpt-3.5-turbo-instruct-0914
2024-02-29 21:35:46 litellm-server    |  Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
```

The config file I used is:

``` yaml
model_list:
- model_name: gpt-3.5-turbo-instruct-0914
  litellm_params:
    model: gpt-3.5-turbo-instruct-0914
    api_key: os.environ/OPENAI_API_KEY
```

### Twitter / LinkedIn details

@cxwudi / https://www.linkedin.com/in/charles-chen-cc98/

**Comment by CXwudi** [comment]
Actually, this issue isn't a big deal if I put `model: openai/gpt-3.5-turbo-instruct-0914` in the `litellm_params` to force using OpenAI

**Comment by ishaan-jaff** [comment]
started a PR for this

**Comment by ishaan-jaff** [comment]
@CXwudi sent you a request on Linkedin - will give you a shoutout in our changelog today :)
