### ISSUE TITLE
[Bug]: Proxy Debug logs show confusing stacktrace with very large prompts 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#2296]
### Relevant log output

> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
>     yield
>   File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
>     resp = await self._pool.handle_async_request(req)
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
>     raise exc from None
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
>     response = await connection.handle_async_request(
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
>     return await self._connection.handle_async_request(request)
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 143, in handle_async_request
>     raise exc
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 113, in handle_async_request
>     ) = await self._receive_response_headers(**kwargs)
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 186, in _receive_response_headers
>     event = await self._receive_event(timeout=timeout)
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_async/http11.py", line 224, in _receive_event
>     data = await self._network_stream.read(
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 36, in read
>     return b""
>   File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
>     self.gen.throw(typ, value, traceback)
>   File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
>     raise to_exc(exc) from exc

_No response_

**Comment by ishaan-jaff** [comment]
When this occurs the Slack alerting emits a completely different message:
```
Level: High
Timestamp: 18:29:12

Message: DB read/write call failed:
```
