### ISSUE TITLE
[Bug]: aembedding success handler cannot handle big batches

### ISSUE THREAD

**Issue by 7flash** [BerriAI/litellm#2307]
### What happened?

This works

```
import litellm
from litellm import embedding, aembedding

embedding_model = "openai/text-embedding-3-large"

n = 2
input = ["How are you?"] * n

async def main():
	response_embedding = (
	    await aembedding(
	        model=embedding_model, input=input, caching=False
	    )
	)["data"][0]["embedding"]

	print(len(response_embedding))

if __name__ == "__main__":
	import asyncio
	asyncio.run(main())
```

But if I change from

```
n = 2
```

to

```
n = 3
```

it throws an error

```
Success! 3072
Exception in thread Thread-1 (success_handler):
Traceback (most recent call last):
  File "/Users/gur/miniconda3/envs/feb27/lib/python3.10/site-packages/litellm/utils.py", line 1099, in _success_handler_helper_fn
    verbose_logger.debug(f"Model={self.model}; result={result}")
  File "/Users/gur/miniconda3/envs/feb27/lib/python3.10/site-packages/openai/_models.py", line 76, in __str__
    return f'{self.__repr_name__()}({self.__repr_str__(", ")})'  # type: ignore[misc]
  File "/Users/gur/miniconda3/envs/feb27/lib/python3.10/site-packages/pydantic/_internal/_repr.py", line 55, in __repr_str__
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
  File "/Users/gur/miniconda3/envs/feb27/lib/python3.10/site-packages/pydantic/_internal/_repr.py", line 55, in <genexpr>
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
  File "/Users/gur/miniconda3/envs/feb27/lib/python3.10/site-packages/pydantic/main.py", line 963, in __repr_args__
    for k, v in self.__dict__.items():
RuntimeError: dictionary changed size during iteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gur/miniconda3/envs/feb27/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/Users/gur/miniconda3/envs/feb27/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/gur/miniconda3/envs/feb27/lib/python3.10/site-packages/litellm/utils.py", line 1175, in success_handler
    start_time, end_time, result = self._success_handler_helper_fn(
  File "/Users/gur/miniconda3/envs/feb27/lib/python3.10/site-packages/litellm/utils.py", line 1169, in _success_handler_helper_fn
    raise Exception(f"[Non-Blocking] LiteLLM.Success_Call Error: {str(e)}")
Exception: [Non-Blocking] LiteLLM.Success_Call Error: dictionary changed size during iteration
```

Note that it actually created an embedding, but then fails to trigger success call, which is actually not needed here.

**Comment by ishaan-jaff** [comment]
@7flash do you have any success callbacks set ?

**Comment by ishaan-jaff** [comment]
Trying to repro this but unable to:
```python

async def test_openai_embedding_3():
    try:
        litellm.set_verbose = True
        n = 5
        input = ["How are you?"] * n
        response_embedding = (
            await litellm.aembedding(
                model="openai/text-embedding-3-large", input=input, caching=False
            ))["data"][0]["embedding"]
        print(len(response_embedding))
    except Exception as e:
        pytest.fail(f"Error occurred: {e}")

import asyncio
asyncio.run(test_openai_embedding_3())

```

**Comment by ishaan-jaff** [comment]
<img width="1259" alt="Screenshot 2024-03-06 at 5 35 26 PM" src="https://github.com/BerriAI/litellm/assets/29436595/0c9d8db9-2b7c-4f85-a847-de6fec0244f8">

wohoo able to repro this

**Comment by ishaan-jaff** [comment]
fixed wohooo 

<img width="1251" alt="Screenshot 2024-03-06 at 5 52 11 PM" src="https://github.com/BerriAI/litellm/assets/29436595/cdaaf343-0bee-4a5f-aafb-bfedc0972f48">

**Comment by ishaan-jaff** [comment]
Fix here: https://github.com/BerriAI/litellm/pull/2378
