### ISSUE TITLE
Tiktoken empty string error

### ISSUE THREAD

**Issue by GillesMoyse** [BerriAI/litellm#2312]
When calling the "luminous-supreme-control" from Aleph Alpha, I receive the following error

File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 2588, in wrapper
or isinstance(openai.APIConnectionError)
TypeError: isinstance expected 2 arguments, got 1

so I can't use this model.

I am using the latest version of lite-llm (version 1.28.11)

**Comment by ghost** [comment]
looks like there was an error which got swallowed. 
<img width="1001" alt="Screenshot 2024-03-04 at 8 00 26 AM" src="https://github.com/BerriAI/litellm/assets/17561003/e93d84b5-9b36-452f-8b72-bc9c47a0bbbd">


What's the full stacktrace? @GillesMoyse

**Comment by ghost** [comment]
just pushed a fix for the swallowing issue - https://github.com/BerriAI/litellm/commit/019b9ef6f6c9577d9575aceb2f475defaeec7ded

**Comment by GillesMoyse** [comment]
Juste downloaded the latest version 1.28.13, but still have an exception while using "luminous-supreme-control" while calling "complete". Here is the trace :

```
File "[$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 2621, in wrapper
  raise e
File "[$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 2524, in wrapper
  result = original_function(*args, **kwargs)
File "[$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 1909, in completion
  raise exception_type(
File "[$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 7783, in exception_type
  raise original_exception
File "[$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 7573, in exception_type
  raise original_exception
File "[$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 1124, in completion
  model_response = aleph_alpha.completion(
File "[$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\llms\aleph_alpha.py", line 288, in completion
  encoding.encode(model_response["choices"][0]["message"]["content"])
File "[$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\tiktoken\core.py", line 116, in encode
  if match := _special_token_regex(disallowed_special).search(text):
TypeError: expected string or buffer
```

Here is what I receive when setting litellm.verbose=True :

```
Request to litellm:
litellm.completion(messages=[{'content': '', 'role': 'system'}, {'content': "Qui a inventé le parachute ?  A)  Louis-Sébastien Lenormand B)  Sir George Cayley .\nRépond uniquement avec la lettre. Ne donne qu'une seule réponse.", 'role': 'user'}], model='luminous-supreme-control', temperature=0.0, num_retries=3)


self.optional_params: {}
kwargs[caching]: False; litellm.cache: None
Final returned optional params: {'temperature': 0.0}
self.optional_params: {'temperature': 0.0}
{'model': 'luminous-supreme-control', 'messages': [{'content': '', 'role': 'system'}, {'content': "Qui a inventé le parachute ?  A)  Louis-Sébastien Lenormand B)  Sir George Cayley .\nRépond uniquement avec la lettre. Ne donne qu'une seule réponse.", 'role': 'user'}], 'optional_params': {'temperature': 0.0, 'maximum_tokens': 256}, 'litellm_params': {'acompletion': False, 'api_key': None, 'force_timeout': 600, 'logger_fn': None, 'verbose': False, 'custom_llm_provider': 'aleph_alpha', 'api_base': None, 'litellm_call_id': '452befcd-0e5b-4b7f-8ad2-f155b6cb21ad', 'model_alias_map': {}, 'completion_call_id': None, 'metadata': None, 'model_info': None, 'proxy_server_request': None, 'preset_cache_key': None, 'stream_response': {}}, 'start_time': datetime.datetime(2024, 3, 4, 21, 52, 12, 56072), 'stream': False, 'user': None, 'call_type': 'completion', 'litellm_call_id': '452befcd-0e5b-4b7f-8ad2-f155b6cb21ad', 'completion_start_time': None, 'temperature': 0.0, 'input': "###Instruction: ###Input: Qui a inventé le parachute ?  A)  Louis-Sébastien Lenormand B)  Sir George Cayley .\nRépond uniquement avec la lettre. Ne donne qu'une seule réponse.", 'api_key': 'xxx', 'additional_args': {'complete_input_dict': {'model': 'luminous-supreme-control', 'prompt': "###Instruction: ###Input: Qui a inventé le parachute ?  A)  Louis-Sébastien Lenormand B)  Sir George Cayley .\nRépond uniquement avec la lettre. Ne donne qu'une seule réponse.", 'temperature': 0.0, 'maximum_tokens': 256}}, 'log_event_type': 'pre_api_call'}

RAW RESPONSE:
{"completions":[{"completion":"","finish_reason":"end_of_text"}],"model_version":"20240215","num_tokens_prompt_total":51,"num_tokens_generated":1}


raw model_response: {"completions":[{"completion":"","finish_reason":"end_of_text"}],"model_version":"20240215","num_tokens_prompt_total":51,"num_tokens_generated":1}

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
self.failure_callback: []
```

**Comment by ghost** [comment]
oh - looks like tiktoken raises an error for an empty string. Fixing now.

**Comment by ghost** [comment]
fix pushed. should be live soon in v`1.29.3`. Please reopen the ticket if not fixed.

**Comment by ghost** [comment]
v`1.29.4` is live now. @GillesMoyse please reopen if the issue persists

**Comment by GillesMoyse** [comment]
I just installed 1.31.3. I think there is still an issue, still related to tiktoken, still using "luminous-supreme-control", not on every question though, but on this one for instance:

```
The following exception occurred with prompt meta={} user="Qui a inventé l'ampoule électrique ?  A) Joseph Swan B) Thomas Edison C) Hiram Maxim" system="Répond uniquement avec la lettre. Ne donne qu'une seule réponse."
argument 'text': 'NoneType' object cannot be converted to 'PyString'
Traceback (most recent call last):
  File "{$home}\source\repos\ragtime-package\src\ragtime\generators.py", line 398, in complete
    ans:dict = completion(messages=messages, model=self.name,
  File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 2727, in wrapper
    raise e
  File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 2628, in wrapper
    result = original_function(*args, **kwargs)
  File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 1941, in completion
    raise exception_type(
  File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 8102, in exception_type
    raise original_exception
  File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 7886, in exception_type
    raise original_exception
  File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 1156, in completion
    model_response = aleph_alpha.completion(
  File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\llms\aleph_alpha.py", line 288, in completion
    encoding.encode(
  File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\tiktoken\core.py", line 120, in encode
    return self._core_bpe.encode(text, allowed_special)
TypeError: argument 'text': 'NoneType' object cannot be converted to 'PyString'
```
