### ISSUE TITLE
Traceloop bug - import failed 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#236]
What's the problem? (if there are multiple - list as bullet points)

Just ran the latest version of litellm and got this error:
ishaanjaffer@Ishaans-MacBook-Air tests % python3 test_vertex.py 
```
Traceback (most recent call last):
  File "/Users/ishaanjaffer/Github/litellm/litellm/tests/test_vertex.py", line 8, in <module>
    import litellm
  File "/Users/ishaanjaffer/Github/litellm/litellm/__init__.py", line 274, in <module>
    from .utils import (
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 12, in <module>
    from .integrations.traceloop import TraceloopLogger
  File "/Users/ishaanjaffer/Github/litellm/litellm/integrations/traceloop.py", line 2, in <module>
    from traceloop.tracing import Tracer
ModuleNotFoundError: No module named 'traceloop'
```

**Comment by ishaan-jaff** [comment]
it's this line here:
`from traceloop.tracing import Tracer`

we should def not have traceloop be a required dependency for litellm 

cc @krrishdholakia sharing for visibility

**Comment by ishaan-jaff** [comment]
nvm fix was easy: https://github.com/BerriAI/litellm/commit/5e709732a77437ed15c5d001db6b07640485f00a

**Comment by ishaan-jaff** [comment]
will close by eod if there are no complaints about this
