### ISSUE TITLE
[Bug]: HuggingFace model loading errors out

### ISSUE THREAD

**Issue by ayulockin** [BerriAI/litellm#2396]
### What happened?

While using LiteLLM with HF embedding models, I get the following error `litellm.exceptions.APIError: HuggingfaceException - Model BAAI/bge-large-zh is currently loading`

Interestingly, when I run the script after a while, it works fine. Ideally, LiteLLM should wait for the loading to be completed if no api end point is provided. Is there any way around?

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/litellm/main.py", line 2578, in embedding
    response = huggingface.embedding(
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/litellm/llms/huggingface_restapi.py", line 750, in embedding
    raise HuggingfaceError(status_code=500, message=embeddings["error"])
litellm.llms.huggingface_restapi.HuggingfaceError: Model BAAI/bge-large-zh is currently loading

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/ayushthakur/integrations/wandbot-eval/wandbot/src/wandbot/ingestion/__main__.py", line 39, in <module>
    main(args.config)
  File "/Users/ayushthakur/integrations/wandbot-eval/wandbot/src/wandbot/ingestion/__main__.py", line 25, in main
    vectorstore_artifact = vectorstores.load(
  File "/Users/ayushthakur/integrations/wandbot-eval/wandbot/src/wandbot/ingestion/vectorstores.py", line 93, in load
    chroma.add_documents(batch)
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 139, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/langchain_community/vectorstores/chroma.py", line 275, in add_texts
    embeddings = self._embedding_function.embed_documents(texts)
  File "/Users/ayushthakur/integrations/wandbot-eval/wandbot/src/wandbot/ingestion/utils.py", line 347, in embed_documents
    response = embedding(
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/litellm/utils.py", line 2647, in wrapper
    raise e
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/litellm/utils.py", line 2550, in wrapper
    result = original_function(*args, **kwargs)
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/litellm/main.py", line 2737, in embedding
    raise exception_type(
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/litellm/utils.py", line 7855, in exception_type
    raise e
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/litellm/utils.py", line 7312, in exception_type
    raise APIError(
litellm.exceptions.APIError: HuggingfaceException - Model BAAI/bge-large-zh is currently loading
Traceback (most recent call last):
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/litellm/main.py", line 2578, in embedding
    response = huggingface.embedding(
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/litellm/llms/huggingface_restapi.py", line 750, in embedding
    raise HuggingfaceError(status_code=500, message=embeddings["error"])
litellm.llms.huggingface_restapi.HuggingfaceError: Model BAAI/bge-large-zh is currently loading

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/ayushthakur/integrations/wandbot-eval/wandbot/src/wandbot/ingestion/__main__.py", line 39, in <module>
    main(args.config)
  File "/Users/ayushthakur/integrations/wandbot-eval/wandbot/src/wandbot/ingestion/__main__.py", line 25, in main
    vectorstore_artifact = vectorstores.load(
  File "/Users/ayushthakur/integrations/wandbot-eval/wandbot/src/wandbot/ingestion/vectorstores.py", line 93, in load
    chroma.add_documents(batch)
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/langchain_core/vectorstores.py", line 139, in add_documents
    return self.add_texts(texts, metadatas, **kwargs)
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/langchain_community/vectorstores/chroma.py", line 275, in add_texts
    embeddings = self._embedding_function.embed_documents(texts)
  File "/Users/ayushthakur/integrations/wandbot-eval/wandbot/src/wandbot/ingestion/utils.py", line 347, in embed_documents
    response = embedding(
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/litellm/utils.py", line 2647, in wrapper
    raise e
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/litellm/utils.py", line 2550, in wrapper
    result = original_function(*args, **kwargs)
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/litellm/main.py", line 2737, in embedding
    raise exception_type(
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/litellm/utils.py", line 7855, in exception_type
    raise e
  File "/Users/ayushthakur/miniconda3/envs/wandbot-eval/lib/python3.10/site-packages/litellm/utils.py", line 7312, in exception_type
    raise APIError(
litellm.exceptions.APIError: HuggingfaceException - Model BAAI/bge-large-zh is currently loading
```
```


### Twitter / LinkedIn details

_No response_

**Comment by ghost** [comment]
this isn't an error from litellm. huggingface api is raising this as the model hasn't loaded yet. feel free to make a feature request if there's some way for us to improve here! @ayulockin
