### ISSUE TITLE
[Bug]: litellm won't import on python3.8

### ISSUE THREAD

**Issue by rob-judith** [BerriAI/litellm#2447]
### What happened?

Python 3.8 failes to import on `1.30.7`, see the log message attached.

The last known working version is `1.29.5`. 

### Relevant log output

```shell
Python 3.8.10 (default, Nov 22 2023, 10:22:35) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import litellm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robjudith/iml/products/engines/mr-extraction/venv/lib/python3.8/site-packages/litellm/__init__.py", line 575, in <module>
    from .llms.huggingface_restapi import HuggingfaceConfig
  File "/home/robjudith/iml/products/engines/mr-extraction/venv/lib/python3.8/site-packages/litellm/llms/huggingface_restapi.py", line 12, in <module>
    from .prompt_templates.factory import prompt_factory, custom_prompt
  File "/home/robjudith/iml/products/engines/mr-extraction/venv/lib/python3.8/site-packages/litellm/llms/prompt_templates/factory.py", line 636, in <module>
    def extract_between_tags(tag: str, string: str, strip: bool = False) -> list[str]:
TypeError: 'type' object is not subscriptable
>>>
```

**Comment by ishaan-jaff** [comment]
this should be fixed on the next release coming out

**Comment by ishaan-jaff** [comment]
Fixed here: https://github.com/BerriAI/litellm/releases/tag/v1.31.2 can u confirm @rob-judith ?

**Comment by ishaan-jaff** [comment]
users confirmed this was fixed
