### ISSUE TITLE
Issue with tiktoken while calling "luminous-supreme-control"

### ISSUE THREAD

**Issue by GillesMoyse** [BerriAI/litellm#2467]
I just installed 1.31.3. I think there is still an issue, still related to tiktoken, still using "luminous-supreme-control", not on every question though, but on this one for instance:

```
The following exception occurred with prompt meta={} user="Qui a inventé l'ampoule électrique ?  A) Joseph Swan B) Thomas Edison C) Hiram Maxim" system="Répond uniquement avec la lettre. Ne donne qu'une seule réponse."
argument 'text': 'NoneType' object cannot be converted to 'PyString'
Traceback (most recent call last):
  File "{$home}\source\repos\ragtime-package\src\ragtime\generators.py", line 398, in complete
    ans:dict = completion(messages=messages, model=self.name,
  File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 2727, in wrapper
    raise e
  File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 2628, in wrapper
    result = original_function(*args, **kwargs)
  File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 1941, in completion
    raise exception_type(
  File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 8102, in exception_type
    raise original_exception
  File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 7886, in exception_type
    raise original_exception
  File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 1156, in completion
    model_response = aleph_alpha.completion(
  File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\llms\aleph_alpha.py", line 288, in completion
    encoding.encode(
  File "{$home}\AppData\Local\Programs\Python\Python310\lib\site-packages\tiktoken\core.py", line 120, in encode
    return self._core_bpe.encode(text, allowed_special)
TypeError: argument 'text': 'NoneType' object cannot be converted to 'PyString'
```

_Originally posted by @GillesMoyse in https://github.com/BerriAI/litellm/issues/2312#issuecomment-1991625237_

**Comment by ghost** [comment]
@GillesMoyse the text is none. Can you confirm your calls work when making a direct http call to aleph alpha?

**Comment by GillesMoyse** [comment]
Just ran it on Aleph Alpha playground and it works:
![image](https://github.com/BerriAI/litellm/assets/18755733/f284888f-7479-4eb1-8673-7f86871289d7)
