### ISSUE TITLE
[Bug]:  LiteLLM.Success_Call Error: dictionary changed size during iteration

### ISSUE THREAD

**Issue by jeromeroussin** [BerriAI/litellm#2468]
### What happened?

My proxy logs contain the errors below repeated multiple times. It appears to be related to printing debug output, and how pydantic turns "result" into a string. I dont have much more info to provide.

Interestingly here performance-wise is that the work being performed is ultimately for nothing since debug is not enabled. It may be sensible to wrap expensive calls to .debug() with something like is_debug_enabled() or similar, or some other solution that makes debug calls cheaper.

### Relevant log output

```shell
Exception in thread Thread-107774 (success_handler):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/litellm/utils.py", line 1105, in _success_handler_helper_fn
    verbose_logger.debug(f"Model={self.model}; result={result}")
                                                      ^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/openai/_models.py", line 76, in __str__
    return f'{self.__repr_name__()}({self.__repr_str__(", ")})'  # type: ignore[misc]
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/_internal/_repr.py", line 55, in __repr_str__
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/_internal/_repr.py", line 55, in <genexpr>
    return join_str.join(repr(v) if a is None else f'{a}={v!r}' for a, v in self.__repr_args__())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pydantic/main.py", line 963, in __repr_args__
    for k, v in self.__dict__.items():
RuntimeError: dictionary changed size during iteration
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.12/site-packages/litellm/utils.py", line 1181, in success_handler
    start_time, end_time, result = self._success_handler_helper_fn(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/litellm/utils.py", line 1175, in _success_handler_helper_fn
    raise Exception(f"[Non-Blocking] LiteLLM.Success_Call Error: {str(e)}")
Exception: [Non-Blocking] LiteLLM.Success_Call Error: dictionary changed size during iteration
```

**Comment by ishaan-jaff** [comment]
@jeromeroussin what version are you on ? This is fixed on latest

**Comment by jeromeroussin** [comment]
Ok thanks I'll upgrade

**Comment by ishaan-jaff** [comment]
feel free to re-open if not fixed
