### ISSUE TITLE
Anthropic Claude 2 LLM model does not work with LiteLLM, API not supported

### ISSUE THREAD

**Issue by aabor** [BerriAI/litellm#2492]
I have to use LiteLLM with TruLens to access anthropic API.
 I took an example from official documentation of LiteLLM to try to access Anthropic Claude 2 model and it gives errors.

How to reproduce:

```py
from litellm import completion

messages = [{"role": "user", "content": "Hey! how's it going?"}]
response = completion(model="claude-3-opus-20240229", messages=messages)
print(response)
```

Error message

07:45:17 - LiteLLM:INFO:

POST Request Sent from LiteLLM:
curl -X POST
https://api.anthropic.com/v1/complete
-H 'accept: application/json' -H 'anthropic-version: 2023-06-01' -H 'content-type: application/json' -H 
-d '{'model': 'claude-3-opus-20240229', 'prompt': "\n\nHuman: Hey! how's it going?\n\nAssistant: ", 'max_tokens_to_sample': 256}'

2024-03-13 07:45:17,915:INFO:

POST Request Sent from LiteLLM:
curl -X POST
https://api.anthropic.com/v1/complete
-H 'accept: application/json' -H 'anthropic-version: 2023-06-01' -H 'content-type: application/json' -H 
-d '{'model': 'claude-3-opus-20240229', 'prompt': "\n\nHuman: Hey! how's it going?\n\nAssistant: ", 'max_tokens_to_sample': 256}'

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
File "/Users/aabor/projects/rag/venv/lib/python3.11/site-packages/litellm/main.py", line 1020, in completion
response = anthropic.completion(
^^^^^^^^^^^^^^^^^^^^^
File "/Users/aabor/projects/rag/venv/lib/python3.11/site-packages/litellm/llms/anthropic.py", line 170, in completion
raise AnthropicError(
litellm.llms.anthropic.AnthropicError: {"type":"error","error":{"type":"invalid_request_error","message":""claude-3-opus-20240229" is not supported on this API. Please use the Messages API instead."}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/aabor/projects/rag/venv/lib/python3.11/site-packages/litellm/utils.py", line 2481, in wrapper
raise e
File "/Users/aabor/projects/rag/venv/lib/python3.11/site-packages/litellm/utils.py", line 2384, in wrapper
result = original_function(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/aabor/projects/rag/venv/lib/python3.11/site-packages/litellm/main.py", line 1897, in completion
raise exception_type(
^^^^^^^^^^^^^^^
File "/Users/aabor/projects/rag/venv/lib/python3.11/site-packages/litellm/utils.py", line 7520, in exception_type
raise e
File "/Users/aabor/projects/rag/venv/lib/python3.11/site-packages/litellm/utils.py", line 6478, in exception_type
raise BadRequestError(
litellm.exceptions.BadRequestError: AnthropicException - {"type":"error","error":{"type":"invalid_request_error","message":""claude-3-opus-20240229" is not supported on this API. Please use the Messages API instead."}}

This model works when I use other packages to access, for example, llama_index

```py
from llama_index.llms.anthropic import Anthropic as LlamaIndexAnthropic
```

**Comment by ishaan-jaff** [comment]
@aabor what version of litellm are you on? Can you make sure you're on latest and let me know if you still see this

**Comment by aabor** [comment]
I was on 1.23.x version. Then I upgraded to the most recent one which is 1.31.6.
It works well with direct completion function call, but when I use TruLens to estimate performance the following error appears:

2024-03-13 08:14:01,351:INFO:HTTP Request: POST https://api.anthropic.com/v1/messages "HTTP/1.1 200 OK"
2024-03-13 08:14:01,566:INFO:Context impl SQLiteImpl.
2024-03-13 08:14:01,566:INFO:Will assume non-transactional DDL.
2024-03-13 08:14:01,706:INFO:✅ added record record_hash_d250bdf66726f7230a6ed74cff868ffc
2024-03-13 08:14:01,711:INFO:Context impl SQLiteImpl.
2024-03-13 08:14:01,712:INFO:Will assume non-transactional DDL.
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.
2024-03-13 08:14:02,052:ERROR:litellm request failed <class 'litellm.exceptions.APIConnectionError'>=list index out of range. Retries remaining=3.
2024-03-13 08:14:02,061:ERROR:litellm request failed <class 'litellm.exceptions.APIConnectionError'>=list index out of range. Retries remaining=3.
2024-03-13 08:14:02,077:ERROR:litellm request failed <class 'litellm.exceptions.APIConnectionError'>=list index out of range. Retries remaining=3.
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

**Comment by nischalj10** [comment]
hey @ishaan-jaff,  I am getting the following error when trying to use  claude-3-opus-20240229 and it's function calling capabilities via litellm. I am on v1.31.6

AttributeError: 'NoneType' object has no attribute 'strip' 

Logs -  
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/Users/namanjain/Library/Python/3.9/lib/python/site-packages/litellm/main.py", line 1132, in completion
    response = anthropic.completion(
  File "/Users/namanjain/Library/Python/3.9/lib/python/site-packages/litellm/llms/anthropic.py", line 142, in completion
    messages = prompt_factory(
  File "/Users/namanjain/Library/Python/3.9/lib/python/site-packages/litellm/llms/prompt_templates/factory.py", line 956, in prompt_factory
    return anthropic_messages_pt(messages=messages)
  File "/Users/namanjain/Library/Python/3.9/lib/python/site-packages/litellm/llms/prompt_templates/factory.py", line 628, in anthropic_messages_pt
    new_messages[last_assistant_message_idx]["content"] = new_messages[
AttributeError: 'NoneType' object has no attribute 'strip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/namanjain/Desktop/repos/openai-agent-demo/main.py", line 330, in <module>
    run_conversation()
  File "/Users/namanjain/Desktop/repos/openai-agent-demo/main.py", line 272, in run_conversation
    response = completion(
  File "/Users/namanjain/Library/Python/3.9/lib/python/site-packages/litellm/utils.py", line 2727, in wrapper
    raise e
  File "/Users/namanjain/Library/Python/3.9/lib/python/site-packages/litellm/utils.py", line 2628, in wrapper
    result = original_function(*args, **kwargs)
  File "/Users/namanjain/Library/Python/3.9/lib/python/site-packages/litellm/main.py", line 2056, in completion
    raise exception_type(
  File "/Users/namanjain/Library/Python/3.9/lib/python/site-packages/litellm/utils.py", line 8146, in exception_type
    raise e
  File "/Users/namanjain/Library/Python/3.9/lib/python/site-packages/litellm/utils.py", line 8121, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: 'NoneType' object has no attribute 'strip'

**Comment by ghost** [comment]
@aabor are you able to share more verbose logs for your issue? 

@Nischalj10 why is the content None for your final assistant message? can you share what you sent in? 

Just pushed a fix to raise the right exception here (invalid message error).

**Comment by aabor** [comment]
This issue is connected with TruLens. I use LiteLLM package to access different LLM APIs to estimate performance of Q&A systems.

Here is the issue:
https://github.com/truera/trulens/issues/992

**Comment by ghost** [comment]
oh @aabor  - i'd recommend just using the litellm proxy, we'd be able to fix any issues on our end in that way

**Comment by ghost** [comment]
closing as this is not a litellm issue
