### ISSUE TITLE
[Bug]: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte

### ISSUE THREAD

**Issue by Politas380** [BerriAI/litellm#2537]
### What happened?

A bug happened! When using anything with litellm, for example using open inetrpreter, writing litellm code for AI or justa nything i always get this error and its now about a month that happened and couldnt fix, I tried to reninstall python, pip, litellm, even use in conda enviroment, nothing helps so please help me fix this bug.

### Relevant log output

```shell
writed code:

from litellm import LiteralLMClient

client = LiteralLMClient(model_name="olllama")

def generate_text(prompt, max_tokens=100, temperature=0.7, top_p=0.9, top_k=50):
    response = client.generate(
        prompt=prompt,
        max_tokens=max_tokens,
        temperature=temperature,
        top_p=top_p,
        top_k=top_k,
    )
    return response.generated_text

prompt = "The quick brown fox jumps over the lazy dog."
generated_text = generate_text(prompt)
print(generated_text)

error:

Traceback (most recent call last):
  File "d:\Programming\Ollama\test.py", line 1, in <module>
    from litellm import LiteralLMClient
  File "C:\Users\Matas\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\__init__.py", line 10, in <module>
    dotenv.load_dotenv()
  File "C:\Users\Matas\AppData\Local\Programs\Python\Python312\Lib\site-packages\dotenv\main.py", line 356, in load_dotenv
    return dotenv.set_as_environment_variables()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matas\AppData\Local\Programs\Python\Python312\Lib\site-packages\dotenv\main.py", line 92, in set_as_environment_variables
    if not self.dict():
           ^^^^^^^^^^^
  File "C:\Users\Matas\AppData\Local\Programs\Python\Python312\Lib\site-packages\dotenv\main.py", line 76, in dict
    self._dict = OrderedDict(resolve_variables(raw_values, override=self.override))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matas\AppData\Local\Programs\Python\Python312\Lib\site-packages\dotenv\main.py", line 238, in resolve_variables
    for (name, value) in values:
  File "C:\Users\Matas\AppData\Local\Programs\Python\Python312\Lib\site-packages\dotenv\main.py", line 84, in parse
    for mapping in with_warn_for_invalid_lines(parse_stream(stream)):
  File "C:\Users\Matas\AppData\Local\Programs\Python\Python312\Lib\site-packages\dotenv\main.py", line 26, in with_warn_for_invalid_lines
    for mapping in mappings:
  File "C:\Users\Matas\AppData\Local\Programs\Python\Python312\Lib\site-packages\dotenv\parser.py", line 173, in parse_stream
    reader = Reader(stream)
             ^^^^^^^^^^^^^^
  File "C:\Users\Matas\AppData\Local\Programs\Python\Python312\Lib\site-packages\dotenv\parser.py", line 64, in __init__
    self.string = stream.read()
                  ^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 0: invalid start byte
```

**Comment by ghost** [comment]
> LiteralLMClient

what is this? 

>   File "C:\Users\Matas\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\__init__.py", line 10, in <module>
    dotenv.load_dotenv()
  File "C:\Users\Matas\AppData\Local\Programs\Python\Python312\Lib\site-packages\dotenv\main.py", line 356, in load_dotenv
    return dotenv.set_as_environment_variables()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matas\AppData\Local\Programs\Python\Python312\Lib\site-packages\dotenv\main.py", line 92, in set_as_environment_variables
    if not self.dict():
           ^^^^^^^^^^^

this looks like a corrupted .env 


---
converting to a discussion, as this isn't a litellm bug
