### ISSUE TITLE
[Bug]: Redis Caching w/ `Cache()` Does not Work

### ISSUE THREAD

**Issue by s-jse** [BerriAI/litellm#2564]
### What happened?

I'm trying the code from the documentation at https://docs.litellm.ai/docs/caching/redis_cache:

```
import litellm
from litellm.caching import Cache
from litellm import completion


litellm.cache = Cache(type="redis", host="redis://localhost", port="5003")

response1 = completion(
    model="gpt-3.5-turbo", 
    messages=[{"role": "user", "content": "Tell me a joke."}]
)
response2 = completion(
    model="gpt-3.5-turbo", 
    messages=[{"role": "user", "content": "Tell me a joke."}]
)
```

But I see the following error. I have redis installed and running on port 5003 of the same machine.
Am I using `Cache()` incorrectly? I've tried setting `url="redis://localhost"`, with and without appending `:5003` to the url and host and with `localhost` and `127.0.0.1`. But none of them work.

```
Python=3.8
LiteLLM=1.32.1
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "test_litellm.py", line 7, in <module>
    litellm.cache = Cache(type="redis", host="redis://localhost", port="5003")
  File "/home/user/anaconda3/envs/test_litellm/lib/python3.8/site-packages/litellm/caching.py", line 900, in __init__
    self.cache: BaseCache = RedisCache(host, port, password, **kwargs)
  File "/home/user/anaconda3/envs/test_litellm/lib/python3.8/site-packages/litellm/caching.py", line 112, in __init__
    self.async_redis_conn_pool = get_redis_connection_pool()
  File "/home/user/anaconda3/envs/test_litellm/lib/python3.8/site-packages/litellm/_redis.py", line 121, in get_redis_connection_pool
    redis_kwargs = _get_redis_client_logic(**env_overrides)
  File "/home/user/anaconda3/envs/test_litellm/lib/python3.8/site-packages/litellm/_redis.py", line 92, in _get_redis_client_logic
    raise ValueError("Either 'host' or 'url' must be specified for redis.")
ValueError: Either 'host' or 'url' must be specified for redis.
```

**Comment by ghost** [comment]
testing now

**Comment by ghost** [comment]
able to repro - fixing now

**Comment by ghost** [comment]
this only happens when the redis value is not in env, but passed in dynamically.

**Comment by ghost** [comment]
merged fix. live in next release - v`1.32.2`+
