### ISSUE TITLE
[Bug]: AttributeError: module 'jwt' has no attribute '__version__' jwt version is 1.3.1

### ISSUE THREAD

**Issue by griftt** [BerriAI/litellm#2621]
### What happened?

(autogen) PS D:\anacondaEnev\envs\autogen>  litellm --model  ollama/gemma
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\anacondaEnev\envs\autogen\Scripts\litellm.exe\__main__.py", line 7, in <module>
  File "D:\anacondaEnev\envs\autogen\Lib\site-packages\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anacondaEnev\envs\autogen\Lib\site-packages\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "D:\anacondaEnev\envs\autogen\Lib\site-packages\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anacondaEnev\envs\autogen\Lib\site-packages\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\anacondaEnev\envs\autogen\Lib\site-packages\litellm\proxy\proxy_cli.py", line 231, in run_server
    from .proxy_server import (
  File "D:\anacondaEnev\envs\autogen\Lib\site-packages\litellm\proxy\proxy_server.py", line 109, in <module>
    from litellm.proxy.auth.handle_jwt import JWTHandler
  File "D:\anacondaEnev\envs\autogen\Lib\site-packages\litellm\proxy\auth\handle_jwt.py", line 12, in <module>
    print(jwt.__version__)  # noqa
          ^^^^^^^^^^^^^^^
AttributeError: module 'jwt' has no attribute '__version__'

**Comment by ghost** [comment]
This should be fixed

**Comment by ghost** [comment]
please bump me if this issue persists @griftt
