### ISSUE TITLE
asyncio.exceptions.CancelledError

### ISSUE THREAD

**Issue by xuyc07** [BerriAI/litellm#2636]
window 11 ，docker desktop 4.27.2
the informationi is ：
2024-03-22 16:53:41 INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
2024-03-22 16:53:41 ERROR:    Traceback (most recent call last):
2024-03-22 16:53:41   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 743, in lifespan
2024-03-22 16:53:41     await receive()
2024-03-22 16:53:41   File "/usr/local/lib/python3.11/site-packages/uvicorn/lifespan/on.py", line 137, in receive
2024-03-22 16:53:41     return await self.receive_queue.get()
2024-03-22 16:53:41            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-03-22 16:53:41   File "/usr/local/lib/python3.11/asyncio/queues.py", line 158, in get
2024-03-22 16:53:41     await getter
2024-03-22 16:53:41 asyncio.exceptions.CancelledError
2024-03-22 16:53:41 
2024-03-22 16:52:06 No WEBUI_SECRET_KEY provided
2024-03-22 16:52:06 Generating WEBUI_SECRET_KEY
2024-03-22 16:52:06 Loading WEBUI_SECRET_KEY from .webui_secret_key
2024-03-22 16:53:41 
2024-03-22 16:53:41 #------------------------------------------------------------#
2024-03-22 16:53:41 #                                                            #
2024-03-22 16:53:41 #            'This product would be better if...'             #
2024-03-22 16:53:41 #        https://github.com/BerriAI/litellm/issues/new        #
2024-03-22 16:53:41 #                                                            #
2024-03-22 16:53:41 #------------------------------------------------------------#
2024-03-22 16:53:41 
2024-03-22 16:53:41  Thank you for using LiteLLM! - Krrish & Ishaan
2024-03-22 16:53:41 
2024-03-22 16:53:41 
2024-03-22 16:53:41 
2024-03-22 16:53:41 Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
2024-03-22 16:53:41 
2024-03-22 16:53:41 
2024-03-22 16:53:43 No WEBUI_SECRET_KEY provided
2024-03-22 16:53:43 Loading WEBUI_SECRET_KEY from .webui_secret_key
2024-03-22 16:56:42 INFO:     Started server process [1]

**Comment by xuyc07** [comment]
update the docker。it‘s ok
