### ISSUE TITLE
[Bug]: Router calls throws unclear exception

### ISSUE THREAD

**Issue by eliorc** [BerriAI/litellm#2673]
### What happened?

Since I'm dealing with [this bug](https://github.com/BerriAI/litellm/issues/1070) I have implemented my chat completion calls through `Router`. This is how my LLM interface looks like (using [`instructor`](https://github.com/jxnl/instructor))

```python3
@cache
def _get_router() -> Router:
    """
    Helper method to always get the same router instance, helps solve the issue mentioned here
    https://github.com/BerriAI/litellm/issues/1070

    :return:
    """
    return Router()


def completion(model: str,
               messages: list[dict[str, str]],
               response_model: BaseModel | type | CustomResponseModel | None = None,
               **llm_backend_kwargs) -> ChatCompletion | CustomStreamWrapper | CustomResponseModel:
    """
    Complete the given messages using the specified LLM model

    :param model: Name of the LLM model
    :param messages: List of messages to complete
    :param response_model: Pydantic model to use for response validation
    :param llm_backend_kwargs: Additional keyword arguments to pass to the LLM backend
    :return: Completed messages
    """

    # Validate defining response model is possible
    if response_model is not None and not supports_function_calling(model):
        raise ValueError(f"LLM model '{model}' does not support function calling "
                         f"which is necessary for response validation.")

    # noinspection PyTypeChecker
    client = instructor.patch(_get_router())

    # noinspection PyArgumentList
    return client.chat.completions.create(model=model,
                                          messages=messages,
                                          response_model=response_model,
                                          **llm_backend_kwargs)


```

After aprox. 470 calls which ar aprox. 31.5K tokens (of which 6K~ are output`) I get this error:

> RuntimeError: Could not convert data into a valid instance of typing.Optional[typing.List]

Now since this always happens after the mentioned number of tokens, I thought maybe under the hood it's an API Limit error, so I tried doing `Router(num_retries=5)` to maybe see a different amount of tokens/requests before the error appears - but still the error appears after the same amount of tokens.

Can't really tell why this is happening, I'm pretty sure it's a hidden bug

### Relevant log output

```shell
OpenAIException - Traceback (most recent call last):
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/litellm/llms/openai.py", line 376, in completion
    raise e
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/litellm/llms/openai.py", line 335, in completion
    response = openai_client.chat.completions.create(**data, timeout=timeout)  # type: ignore
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 667, in create
    return self._post(
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_base_client.py", line 1208, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_base_client.py", line 897, in request
    return self._request(
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_base_client.py", line 990, in _request
    return self._process_response(
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_base_client.py", line 1084, in _process_response
    return api_response.parse()
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_response.py", line 307, in parse
    parsed = self._parse(to=to)
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_response.py", line 253, in _parse
    return self._client._process_response_data(
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_base_client.py", line 565, in _process_response_data
    return cast(ResponseT, construct_type(type_=cast_to, value=data))
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_models.py", line 359, in construct_type
    return type_.construct(**value)  # type: ignore
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_models.py", line 122, in construct
    fields_values = _construct_field(value=values, field=field, key=key)
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_models.py", line 272, in _construct_field
    return construct_type(value=value, type_=type_)
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_models.py", line 368, in construct_type
    return
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_models.py", line 368, in <listcomp>
    return
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_models.py", line 359, in construct_type
    return type_.construct(**value)  # type: ignore
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_models.py", line 122, in construct
    fields_values = _construct_field(value=values, field=field, key=key)
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_models.py", line 272, in _construct_field
    return construct_type(value=value, type_=type_)
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_models.py", line 359, in construct_type
    return type_.construct(**value)  # type: ignore
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_models.py", line 122, in construct
    fields_values = _construct_field(value=values, field=field, key=key)
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_models.py", line 272, in _construct_field
    return construct_type(value=value, type_=type_)
  File "/home/elior/.cache/pypoetry/virtualenvs/my_project-kQGE4s5Y-py3.10/lib/python3.10/site-packages/openai/_models.py", line 344, in construct_type
    raise RuntimeError(f"Could not convert data into a valid instance of {type_}")
RuntimeError: Could not convert data into a valid instance of typing.Optional[typing.List]
```

**Comment by eliorc** [comment]
After further debugging, it does seem to be rate limiting. Could this be wrapped with a better eror message?

**Comment by eliorc** [comment]
Issue cause by `instructor` package... When switching off `instructor`, all worked fine
