### ISSUE TITLE
[Bug]: Cannot call `acompletion` on SageMaker with explicit credentials

### ISSUE THREAD

**Issue by bachya** [BerriAI/litellm#2737]
### What happened?

The docs mention that AWS credentials can be explicitly passed to `completion` ([source](https://litellm.vercel.app/docs/providers/aws_sagemaker#passing-credentials-as-parameters---completion)). The same is not true for `acompletion`. This example:

```python
import asyncio

from litellm import acompletion


async def test_get_response():
    response = await acompletion(
        model="sagemaker/my-model",
        messages=[{"content": "Hello, how are you?", "role": "user"}],
        aws_access_key_id="REDACTED",
        aws_secret_access_key="REDACTED",
        aws_region_name="us-west-2",
    )
    return response


response = asyncio.run(test_get_response())
print(response)
```

...produces the stacktrace below.

### Relevant log output

```shell
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/litellm/llms/sagemaker.py", line 478, in async_completion
    response = await client.invoke_endpoint(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/aiobotocore/client.py", line 388, in _make_api_call
    http, parsed_response = await self._make_request(
                            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/aiobotocore/client.py", line 416, in _make_request
    return await self._endpoint.make_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/aiobotocore/endpoint.py", line 96, in _send_request
    request = await self.create_request(request_dict, operation_model)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/aiobotocore/endpoint.py", line 84, in create_request
    await self._event_emitter.emit(
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/aiobotocore/hooks.py", line 66, in _emit
    response = await resolve_awaitable(handler(**kwargs))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/aiobotocore/_helpers.py", line 15, in resolve_awaitable
    return await obj
           ^^^^^^^^^
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/aiobotocore/signers.py", line 24, in handler
    return await self.sign(operation_name, request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/aiobotocore/signers.py", line 88, in sign
    auth.add_auth(request)
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/botocore/auth.py", line 418, in add_auth
    raise NoCredentialsError()
botocore.exceptions.NoCredentialsError: Unable to locate credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/litellm/main.py", line 313, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/litellm/llms/sagemaker.py", line 485, in async_completion
    raise SagemakerError(status_code=500, message=f"{str(e)}")
litellm.llms.sagemaker.SagemakerError: Unable to locate credentials

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/bachya/Downloads/t.py", line 17, in <module>
    response = asyncio.run(test_get_response())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/bachya/Downloads/t.py", line 7, in test_get_response
    response = await acompletion(
               ^^^^^^^^^^^^^^^^^^
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/litellm/utils.py", line 3267, in wrapper_async
    raise e
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/litellm/utils.py", line 3099, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/litellm/main.py", line 326, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/litellm/utils.py", line 8294, in exception_type
    raise e
  File "/Users/bachya/Downloads/.venv/lib/python3.12/site-packages/litellm/utils.py", line 7444, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: SagemakerException - Unable to locate credentials
```

**Comment by bachya** [comment]
After examination, I think I see what may be going on. `acompletion` starts with a call to `litellm.llms.sagemaker.completion`, which pops the AWS credentials for the creation of its client: https://github.com/BerriAI/litellm/blob/359ca003ad24cae2ca8e4ed22c030802ab7eb393/litellm/llms/sagemaker.py#L166-L168

Then, it passes `optional_parameters` (which have had the AWS credentials popped) to `litellm.llms.sagemaker.async_completion`: https://github.com/BerriAI/litellm/blob/359ca003ad24cae2ca8e4ed22c030802ab7eb393/litellm/llms/sagemaker.py#L258-L267

Then, `litellm.llms.sagemaker.async_completion` attempts to pop the AWS credentials from `optional_parameters` _again_: https://github.com/BerriAI/litellm/blob/359ca003ad24cae2ca8e4ed22c030802ab7eb393/litellm/llms/sagemaker.py#L430-L432

This means that the boto3 client creation with explicit credentials: https://github.com/BerriAI/litellm/blob/359ca003ad24cae2ca8e4ed22c030802ab7eb393/litellm/llms/sagemaker.py#L434-L442

...will always fail, leading to an attempt to create the client from the environment. If that isn't set (which, in my case, it isn't), we get the error observed.

**Comment by ghost** [comment]
acknowledging this issue @bachya thanks for catching this. 

Looks like we were missing a test here. Will work on a fix, and add to our ci/cd. 

Curious - how're you trying to use litellm?

**Comment by bachya** [comment]
> acknowledging this issue @bachya thanks for catching this. 

Happy to help!

> Curious - how're you trying to use litellm? 

Mostly as an async framework for chatting with various LLMs; currently playing around with multi-LLM conversations.

**Comment by ghost** [comment]
Fixed - https://github.com/BerriAI/litellm/commit/109cd93a397806f77feba0b20d92cbab885d4e51

@bachya during testing i also noticed sagemaker now requires an `InferenceComponentParam` to be passed in - specifying the model on the endpoint. 

Added support for that too - using the `model_id` param (same as on bedrock for provisioned throughput). 

Not sure if you're seeing it too, but here's how to use it

```python
import os 
from litellm import completion

os.environ["AWS_ACCESS_KEY_ID"] = ""
os.environ["AWS_SECRET_ACCESS_KEY"] = ""
os.environ["AWS_REGION_NAME"] = ""

response = completion(
            model="sagemaker/<your-endpoint-name>", 
            model_id="<your-model-name",
            messages=[{ "content": "Hello, how are you?","role": "user"}],
            temperature=0.2,
            aws_region_name=os.getenv("AWS_REGION_NAME"),
            aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
            aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
            max_tokens=80
        )
```

**Comment by bachya** [comment]
Awesome—thanks, @krrishdholakia! I'll test and post back here.

**Comment by ghost** [comment]
waiting on release - will update you once it's out

**Comment by ghost** [comment]
v`1.34.13` just came out @bachya

**Comment by bachya** [comment]
Had a chance to confirm that this is working. Thank you!
