### ISSUE TITLE
[Bug]: Inconsistency in responses when model's max tokens exceeded 

### ISSUE THREAD

**Issue by gagarinfan** [BerriAI/litellm#2745]
### What happened?

Hi!

It is not a super urgent issue, but during some tests we have discovered interesting behaviour, that when calling OpenAI Proxy for a `gpt-4` Azure OpenAI model (tokens limit: 8192) with `max_tokens: 4000` parameter and prompt message having ~6000 tokens we don't get error for all requests, as expected (and tested when calling Azure OpenAI Endpoint directly).
The error we get when calling Azure directly is:
```
openai.BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, you requested 10152 tokens (6152 in the messages, 4000 in the completion). Please reduce the length of the messages or completion.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}
```

but when calling gpt-4 models via OpenAI Proxy, sometimes we receive positive responses when using exactly the same prompt. (see attached logs)

All gpt-4 models are in the same 0613 version.

Is this behaviour somehow related to this PR? https://github.com/BerriAI/litellm/pull/2520

Docker image: `main-v1.34.12`
Proxy config:
```yaml
general_settings:
  master_key: os.environ/PROXY_MASTER_KEY
litellm_settings:
  add_function_to_prompt: true
  allowed_fails: 0
  drop_params: true
  num_retries: 0
  set_verbose: true
  timeout: 600
model_list:
- litellm_params:
    api_base: https://region-a.openai.azure.com
    api_key: os.environ/redacted
    model: azure/gpt-4
  model_name: gpt-4
- litellm_params:
    api_base: https://region-b.openai.azure.com
    api_key: os.environ/redacted
    model: azure/gpt-4
  model_name: gpt-4
- litellm_params:
    api_base: https://region-c.openai.azure.com
    api_key: os.environ/redacted
    model: azure/gpt-4
  model_name: gpt-4
```

### Relevant log output

```shell
{'error': {'message': 'AzureException - Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 8192 tokens. However, you requested 10152 tokens (6152 in the messages, 4000 in the completion). Please reduce the length of the messages or completion.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}', 'type': None, 'param': None, 'code': 400}}

{'error': {'message': 'AzureException - Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 8192 tokens. However, you requested 10152 tokens (6152 in the messages, 4000 in the completion). Please reduce the length of the messages or completion.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}', 'type': None, 'param': None, 'code': 400}}

{'error': {'message': 'AzureException - Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 8192 tokens. However, you requested 10152 tokens (6152 in the messages, 4000 in the completion). Please reduce the length of the messages or completion.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}', 'type': None, 'param': None, 'code': 400}}

{'id': 'chatcmpl-987XMGSR376vKvGwdLoz2cSr6Fuqa', 'choices': [{'finish_reason': 'stop', 'index': 0, 'message': {'content': '<<< redacted >>>', 'role': 'assistant'}}], 'created': 1711722624, 'model': 'gpt-4', 'object': 'chat.completion', 'system_fingerprint': 'fp_2f57f81c11', 'usage': {'completion_tokens': 125, 'prompt_tokens': 6152, 'total_tokens': 6277}}
```

**Comment by ghost** [comment]
Hey @gagarinfan can you share your server logs for a successful call vs. failed one? 

I don't think it's related to that PR since you don't enable it in your `litellm_settings`. 

Could also debug this over call if you'd rather not share logs over github - https://meet.google.com/quq-rvkr-pge


Also attaching a cal: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by gagarinfan** [comment]
Hi, sure. 
Failed:
server log:
```
POST Request Sent from LiteLLM:
curl -X POST \
https://redacted.openai.azure.com/openai/ \
-H 'Authorization: Bearer ********************' \
-d '{'model': 'gpt-4', 'messages': [{'role': 'user', 'content': ' <<< redacted >>> '}], 'temperature': 0, 'max_tokens': 4000, 'user': 'admin', 'seed': 1234, 'extra_body': {}}'

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 314, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/azure.py", line 380, in acompletion
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/azure.py", line 368, in acompletion
    response = await azure_client.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1334, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1738, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1441, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1532, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'message': "This model's maximum context length is 8192 tokens. However, you requested 10152 tokens (6152 in the messages, 4000 in the completion). Please reduce the length of the messages or completion.", 'type': 'invalid_request_error', 'param': 'messages', 'code': 'context_length_exceeded'}}

Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
get cache: cache key: 16-44:cooldown_models; local_only: False
in_memory_result: None
get cache: cache result: None
set cache: key: 16-44:cooldown_models; value: ['ebe61f8b-db36-4f06-8191-4197f3f72999']
InMemoryCache: set_cache
get cache: cache key: 16-44:cooldown_models; local_only: False
in_memory_result: None
get cache: cache result: None
set cache: key: 16-44:cooldown_models; value: ['ebe61f8b-db36-4f06-8191-4197f3f72999']
InMemoryCache: set_cache
Inside Max Parallel Request Failure Hook
user_api_key: ---
get cache: cache key: ---::2024-03-29-16-44::request_count; local_only: False
in_memory_result: None
get cache: cache result: None
updated_value in failure call: {'current_requests': 0, 'current_tpm': 0, 'current_rpm': 0}
set cache: key: ---::2024-03-29-16-44::request_count; value: {'current_requests': 0, 'current_tpm': 0, 'current_rpm': 0}
InMemoryCache: set_cache
INFO:     192.168.75.154:39310 - "POST /chat/completions HTTP/1.1" 400 Bad Request
```
response from client's site:
```
{'error': {'message': 'AzureException - Error code: 400 - {\'error\': {\'message\': "This model\'s maximum context length is 8192 tokens. However, you requested 10152 tokens (6152 in the messages, 4000 in the completion). Please reduce the length of the messages or completion.", \'type\': \'invalid_request_error\', \'param\': \'messages\', \'code\': \'context_length_exceeded\'}}', 'type': None, 'param': None, 'code': 400}}
```

and well. No trace for successful one :D the last log is the one above, while client received:
```
{'id': 'chatcmpl-989fkcTlIuPjXauoZVYwLA55O3UTC', 'choices': [{'finish_reason': 'stop', 'index': 0, 'message': {'content': ' <<< redacted >>> ', 'role': 'assistant'}}], 'created': 1711730832, 'model': 'gpt-4', 'object': 'chat.completion', 'system_fingerprint': 'fp_2f57f81c11', 'usage': {'completion_tokens': 1637, 'prompt_tokens': 6152, 'total_tokens': 7789}}
```

Please note I wasn't able to reproduce the issue while calling Azure directly

**Comment by gagarinfan** [comment]
Ok, looks like there was some issue on our site. Sorry for bothering you 🙏
