### ISSUE TITLE
Error when trying to use Langfuse [Bug]: 

### ISSUE THREAD

**Issue by JacobGoldenArt** [BerriAI/litellm#2767]
### What happened?

Hi, I followed the docs to setup langfuse, but when I send a request, with verbose set to true, I see that there is an error.
Here's my simple test page:

```python
import litellm
from litellm import completion

litellm.set_verbose = True  # 👈 print DEBUG LOGS
# set langfuse as a callback, litellm will send the data to langfuse
litellm.success_callback = ["langfuse"]
litellm.failure_callback = ["langfuse"]  # logs errors to langfuse

openai_model_alias = {
    "gpt-3": "gpt-3.5-turbo-0125",
    "gpt-4": "gpt-4-turbo-preview",
}

litellm.model_alias_map = openai_model_alias


response = completion(
    model="gpt-3",
    messages=[
        {
            "role": "user",
            "content": "Hi, Please explain the concept of Non-dualism to a 5th grader.",
        },
    ],
    stream=False,
)

print(print(response.choices[0].message.content))
```

### Relevant log output

```shell
Instantiates langfuse client
LiteLLM.LoggingError: [Non-Blocking] Exception occurred while success logging with integrations Traceback (most recent call last):
  File "/Users/jacob.akerson/_Dev/jacobgoldenart/projects/em/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1495, in success_handler
    langFuseLogger = LangFuseLogger(
                     ^^^^^^^^^^^^^^^
  File "/Users/jacob.akerson/_Dev/jacobgoldenart/projects/em/.venv/lib/python3.12/site-packages/litellm/integrations/langfuse.py", line 28, in __init__
    self.Langfuse = Langfuse(
                    ^^^^^^^^^
  File "/Users/jacob.akerson/_Dev/jacobgoldenart/projects/em/.venv/lib/python3.12/site-packages/langfuse/client.py", line 204, in __init__
    self.task_manager = TaskManager(**args)
                        ^^^^^^^^^^^^^^^^^^^
  File "/Users/jacob.akerson/_Dev/jacobgoldenart/projects/em/.venv/lib/python3.12/site-packages/langfuse/task_manager.py", line 215, in __init__
    self.init_resources()
  File "/Users/jacob.akerson/_Dev/jacobgoldenart/projects/em/.venv/lib/python3.12/site-packages/langfuse/task_manager.py", line 234, in init_resources
    consumer.start()
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/threading.py", line 992, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't create new thread at interpreter shutdown

LiteLLM.Logging: is sentry capture exception initialized None
```

**Comment by ghost** [comment]
> RuntimeError: can't create new thread at interpreter shutdown

This seems like an error specific to your environment. 

I can confirm this works fine on my local machine + google colab 


<img width="948" alt="Screenshot 2024-03-30 at 11 41 05 AM" src="https://github.com/BerriAI/litellm/assets/17561003/c0caed3e-ff87-4419-9435-7de64ebdb285">



---
Would recommend filing an issue on langfuse's github and seeing if they can help here 

link: https://github.com/langfuse/langfuse
