### ISSUE TITLE
[Bug]: Error when trying to use LangSmith

### ISSUE THREAD

**Issue by JacobGoldenArt** [BerriAI/litellm#2768]
### What happened?

When trying to use Langsmith, I'm getting an error. Here is my test request page:

import litellm
from litellm import completion

litellm.set_verbose = True  # 👈 print DEBUG LOGS
# set langfuse as a callback, litellm will send the data to langfuse
litellm.success_callback = ["langsmith"]

openai_model_alias = {
    "gpt-3": "gpt-3.5-turbo-0125",
    "gpt-4": "gpt-4-turbo-preview",
}

litellm.model_alias_map = openai_model_alias

response = completion(
    model="gpt-3",
    messages=[
        {
            "role": "user",
            "content": "Hi, Please explain the concept of Non-dualism to a 5th grader.",
        },
    ],
)

print(print(response.choices[0].message.content))

### Relevant log output

```shell
Request to litellm:
litellm.completion(model='gpt-3', messages=[{'role': 'user', 'content': 'Hi, Please explain the concept of Non-dualism to a 5th grader.'}])


callback: langsmith
self.optional_params: {}
kwargs[caching]: False; litellm.cache: None
UNMAPPED PROVIDER, ASSUMING IT'S OPENAI/AZURE
Final returned optional params: {'extra_body': {}}
self.optional_params: {'extra_body': {}}


POST Request Sent from LiteLLM:
curl -X POST \
https://api.openai.com/v1/ \
-d '{'model': 'gpt-3.5-turbo-0125', 'messages': [{'role': 'user', 'content': 'Hi, Please explain the concept of Non-dualism to a 5th grader.'}], 'extra_body': {}}'


RAW RESPONSE:
{"id": "chatcmpl-98XDKikuexeiIwRFlMI4YCWWuNIfN", "choices": [{"finish_reason": "stop", "index": 0, "logprobs": null, "message": {"content": "Sure! Non-dualism is a belief that everything in the world is connected and part of the same thing. It is the idea that there is no separation between things like good and bad, right and wrong, or me and you. Instead, everything is seen as one big interconnected and harmonious system.", "role": "assistant", "function_call": null, "tool_calls": null}}], "created": 1711821326, "model": "gpt-3.5-turbo-0125", "object": "chat.completion", "system_fingerprint": "fp_3bc1b5746c", "usage": {"completion_tokens": 62, "prompt_tokens": 26, "total_tokens": 88}}


Logging Details LiteLLM-Success Call: None
Sure! Non-dualism is a belief that everything in the world is connected and part of the same thing. It is the idea that there is no separation between things like good and bad, right and wrong, or me and you. Instead, everything is seen as one big interconnected and harmonious system.
Looking up model=gpt-3.5-turbo-0125 in model_cost_map
None
Success: model=gpt-3.5-turbo-0125 in model_cost_map
prompt_tokens=26; completion_tokens=62
Returned custom cost for model=gpt-3.5-turbo-0125 - prompt_tokens_cost_usd_dollar: 1.3e-05, completion_tokens_cost_usd_dollar: 9.3e-05
final cost: 0.000106; prompt_tokens_cost_usd_dollar: 1.3e-05; completion_tokens_cost_usd_dollar: 9.3e-05
success callbacks: ['langsmith']
reaches langsmith for logging!
Langsmith Logging - project_name: litellm-completion, run_name LLMRun
Langsmith Logging - Enters logging function for model {'model': 'gpt-3.5-turbo-0125', 'messages': [{'role': 'user', 'content': 'Hi, Please explain the concept of Non-dualism to a 5th grader.'}], 'optional_params': {'extra_body': {}}, 'litellm_params': {'acompletion': False, 'api_key': None, 'force_timeout': 600, 'logger_fn': None, 'verbose': False, 'custom_llm_provider': 'openai', 'api_base': None, 'litellm_call_id': 'f5fc6082-907e-400a-bfc5-19e2a249b60f', 'model_alias_map': {'gpt-3': 'gpt-3.5-turbo-0125', 'gpt-4': 'gpt-4-turbo-preview'}, 'completion_call_id': None, 'metadata': None, 'model_info': None, 'proxy_server_request': None, 'preset_cache_key': None, 'no-log': False, 'stream_response': {}}, 'start_time': datetime.datetime(2024, 3, 30, 10, 55, 24, 609108), 'stream': False, 'user': None, 'call_type': 'completion', 'litellm_call_id': 'f5fc6082-907e-400a-bfc5-19e2a249b60f', 'completion_start_time': datetime.datetime(2024, 3, 30, 10, 55, 26, 955464), 'extra_body': {}, 'input': [{'role': 'user', 'content': 'Hi, Please explain the concept of Non-dualism to a 5th grader.'}], 'api_key': 'removed for issue report', 'additional_args': {'complete_input_dict': {'model': 'gpt-3.5-turbo-0125', 'messages': [{'role': 'user', 'content': 'Hi, Please explain the concept of Non-dualism to a 5th grader.'}], 'extra_body': {}}}, 'log_event_type': 'successful_api_call', 'original_response': '{"id": "chatcmpl-98XDKikuexeiIwRFlMI4YCWWuNIfN", "choices": [{"finish_reason": "stop", "index": 0, "logprobs": null, "message": {"content": "Sure! Non-dualism is a belief that everything in the world is connected and part of the same thing. It is the idea that there is no separation between things like good and bad, right and wrong, or me and you. Instead, everything is seen as one big interconnected and harmonious system.", "role": "assistant", "function_call": null, "tool_calls": null}}], "created": 1711821326, "model": "gpt-3.5-turbo-0125", "object": "chat.completion", "system_fingerprint": "fp_3bc1b5746c", "usage": {"completion_tokens": 62, "prompt_tokens": 26, "total_tokens": 88}}', 'end_time': datetime.datetime(2024, 3, 30, 10, 55, 26, 955464), 'cache_hit': None, 'response_cost': 0.000106}
Langsmith Layer Error - Traceback (most recent call last):
  File "/Users/jacob.akerson/_Dev/jacobgoldenart/projects/em/.venv/lib/python3.12/site-packages/litellm/integrations/langsmith.py", line 59, in log_event
    requests.post(
  File "/Users/jacob.akerson/_Dev/jacobgoldenart/projects/em/.venv/lib/python3.12/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacob.akerson/_Dev/jacobgoldenart/projects/em/.venv/lib/python3.12/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacob.akerson/_Dev/jacobgoldenart/projects/em/.venv/lib/python3.12/site-packages/requests/sessions.py", line 575, in request
    prep = self.prepare_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jacob.akerson/_Dev/jacobgoldenart/projects/em/.venv/lib/python3.12/site-packages/requests/sessions.py", line 486, in prepare_request
    p.prepare(
  File "/Users/jacob.akerson/_Dev/jacobgoldenart/projects/em/.venv/lib/python3.12/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Users/jacob.akerson/_Dev/jacobgoldenart/projects/em/.venv/lib/python3.12/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type datetime is not JSON serializable
```

**Comment by ghost** [comment]
this is now fixed! @JacobGoldenArt - https://github.com/BerriAI/litellm/commit/9e3514fd24fb1d257bd6b0fd2ef5d6bc7ef88a03

will be live in the next release - v`1.35.21+`
