### ISSUE TITLE
API KEY client issue

### ISSUE THREAD

**Issue by TUTULEMAN** [BerriAI/litellm#2773]
finished installing everything, currently using Open AI's API Key, but I encountered an error. Please help. This is what it returned:
`Error condensing thoughts: OpenAIException - Traceback (most recent call last):`
` openai.openaiError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable`

**Comment by ishaan-jaff** [comment]
Can I see some code on how you're using litellm.

**Comment by TUTULEMAN** [comment]
**Back End**
_PS C:\Users\max\opendevin> set OPEN_API_KEY="i_inserted_my_api_key"
PS C:\Users\max\opendevin> set LLM_BASE_URL="https://localhost:3001"
PS C:\Users\max\opendevin> set LLM_MODEL="gpt-4-32k-0613"
PS C:\Users\max\opendevin> python -m pipenv install -v
Installing dependencies from Pipfile.lock (5563c0)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
PS C:\Users\max\opendevin> python -m pipenv shell
Launching subshell in virtual environment...
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\max\OpenDevin> uvicorn opendevin.server.listen:app --port 3000
INFO:     Started server process [28312]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:3000 (Press CTRL+C to quit)_

**Front End**
_Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS C:\Users\max> cd opendevin
PS C:\Users\max\opendevin> cd frontend
PS C:\Users\max\opendevin\frontend> npm install

> opendevin-frontend@0.1.0 prepare
> cd .. && husky install frontend/.husky

husky - Git hooks installed

up to date, audited 826 packages in 3s

209 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
PS C:\Users\max\opendevin\frontend> npm start

> opendevin-frontend@0.1.0 start
> vite

Port 3001 is in use, trying another one...
Port 3002 is in use, trying another one...

  VITE v5.1.6  ready in 1330 ms

  ➜  Local:   http://localhost:3003/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help_

**Results**

_During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\max\OpenDevin\opendevin\controller\agent_controller.py", line 88, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\OpenDevin\agenthub\langchains_agent\langchains_agent.py", line 124, in step
    self._add_event(prev_action.to_dict())
  File "C:\Users\max\OpenDevin\agenthub\langchains_agent\langchains_agent.py", line 74, in _add_event
    self.monologue.condense(self.llm)
  File "C:\Users\max\OpenDevin\agenthub\langchains_agent\utils\monologue.py", line 35, in condense
    raise RuntimeError(f"Error condensing thoughts: {e}")
RuntimeError: Error condensing thoughts: OpenAIException - Traceback (most recent call last):
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\llms\openai.py", line 376, in completion
    raise e
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\llms\openai.py", line 312, in completion
    openai_client = openai(
                    ^^^^^^^
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\openai\_client.py", line 98, in __init__
    raise openaiError(
openai.openaiError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable


        OBSERVATION:
        Error condensing thoughts: OpenAIException - Traceback (most recent call last):
          File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\llms\openai.py", line 376, in completion
            raise e
          File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\llms\openai.py", line 312, in completion
            openai_client = openai(
                            ^^^^^^^
          File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\openai\_client.py", line 98, in __init__
            raise openaiError(
        openai.openaiError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

Exited before finishing_

**Comment by TUTULEMAN** [comment]
the front end works but everytime I try to write something it keeps on returning **Results** as seen above

**Comment by ghost** [comment]
@TUTULEMAN your code looks like you're using litellm with langchain? 

> File "C:\Users\max\OpenDevin\agenthub\langchains_agent\utils\monologue.py", line 35, in condense
raise RuntimeError(f"Error condensing thoughts: {e}")
RuntimeError: Error condensing thoughts: OpenAIException - Traceback (most recent call last):
File "C:\Users\max.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\llms\openai.py", line 376, in completion
raise e


I'm not sure how this is running, but it just looks like the value isn't being set in litellm

You can check if this is a litellm issue by running this script: 

```python
from litellm import completion
import os

## set ENV variables
os.environ["OPENAI_API_KEY"] = "your-api-key"

response = completion(
  model="gpt-3.5-turbo",
  messages=[{ "content": "Hello, how are you?","role": "user"}]
)
```

**Comment by ghost** [comment]
closing as this seems not related to litellm. but please @ me if that doesn't seem to be the case @TUTULEMAN

**Comment by TUTULEMAN** [comment]
idk if this is what ou are looking for but  heres what I got:

C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Scripts\python.exe C:\Users\max\OpenDevin\new\yes\yy.py 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\llms\openai.py", line 376, in completion
    raise e
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\llms\openai.py", line 335, in completion
    response = openai_client.chat.completions.create(**data, timeout=timeout)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\openai\_utils\_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\openai\resources\chat\completions.py", line 667, in create
    return self._post(
           ^^^^^^^^^^^
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\openai\_base_client.py", line 1208, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\openai\_base_client.py", line 897, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\openai\_base_client.py", line 973, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\openai\_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\openai\_base_client.py", line 973, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\openai\_base_client.py", line 1021, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\openai\_base_client.py", line 988, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.RateLimitError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\main.py", line 989, in completion
    raise e
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\main.py", line 962, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\llms\openai.py", line 382, in completion
    raise OpenAIError(status_code=e.status_code, message=str(e))
litellm.llms.openai.OpenAIError: Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\max\OpenDevin\new\yes\yy.py", line 7, in <module>
    response = completion(
               ^^^^^^^^^^^
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\utils.py", line 2819, in wrapper
    raise e
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\utils.py", line 2717, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\main.py", line 2093, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\utils.py", line 8311, in exception_type
    raise e
  File "C:\Users\max\.virtualenvs\OpenDevin-wJ2ztY-k\Lib\site-packages\litellm\utils.py", line 7150, in exception_type
    raise RateLimitError(
litellm.exceptions.RateLimitError: OpenAIException - Error code: 429 - {'error': {'message': 'You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.', 'type': 'insufficient_quota', 'param': None, 'code': 'insufficient_quota'}}

Process finished with exit code 1

**Comment by TUTULEMAN** [comment]
is there a video or recording that goes through the process of installing opendevin? i feel like it would help a lot of people who are also encountering bugs

**Comment by ghost** [comment]
@TUTULEMAN unfortunately can't help as i'm not the maintainer of opendevin. 

here's their github - https://github.com/OpenDevin/OpenDevin

seems like a better place to make the issue
