### ISSUE TITLE
litellm.set_verbose=True

### ISSUE THREAD

**Issue by Dr-Mohamed-Elkholy** [BerriAI/litellm#2812]
Hello, Has anyone faced a problem like this?

**Comment by ghost** [comment]
What's the problem?

**Comment by Dr-Mohamed-Elkholy** [comment]
while generating the task, it give me this error in the background and stops generating. I use claude 3 API for Haiku LLM (They gave 5 dollar offer for testing the API)

**Comment by ghost** [comment]
can you share the full stacktrace?

**Comment by Dr-Mohamed-Elkholy** [comment]
it runs unlimited steps with the same error 
==============
STEP 99

PLAN:
build calculator for python on ios application 

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.


Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\main.py", line 1773, in completion
    response = bedrock.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\llms\bedrock.py", line 1102, in completion
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\llms\bedrock.py", line 712, in completion
    client = init_bedrock_client(
             ^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\llms\bedrock.py", line 561, in init_bedrock_client
    raise BedrockError(
litellm.llms.bedrock.BedrockError: AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 1436, in function_with_retries
    response = original_function(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 386, in _completion
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 369, in _completion
    response = litellm.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\utils.py", line 2870, in wrapper
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\utils.py", line 2768, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\main.py", line 2094, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\utils.py", line 8362, in exception_type
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\utils.py", line 7487, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: BedrockException - AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\main.py", line 1773, in completion
    response = bedrock.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\llms\bedrock.py", line 1102, in completion
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\llms\bedrock.py", line 712, in completion
    client = init_bedrock_client(
             ^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\llms\bedrock.py", line 561, in init_bedrock_client
    raise BedrockError(
litellm.llms.bedrock.BedrockError: AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\agenthub\monologue_agent\utils\monologue.py", line 31, in condense
    resp = llm.completion(messages=messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 328, in completion
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 325, in completion
    response = self.function_with_fallbacks(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 1419, in function_with_fallbacks
    raise original_exception
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 1344, in function_with_fallbacks
    response = self.function_with_retries(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 1496, in function_with_retries
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 1462, in function_with_retries
    response = original_function(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 386, in _completion
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 369, in _completion
    response = litellm.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\utils.py", line 2870, in wrapper
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\utils.py", line 2768, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\main.py", line 2094, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\utils.py", line 8362, in exception_type
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\utils.py", line 7487, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: BedrockException - AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file

ERROR:
Error condensing thoughts: BedrockException - AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file
Traceback (most recent call last):
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\main.py", line 1773, in completion
    response = bedrock.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\llms\bedrock.py", line 1102, in completion
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\llms\bedrock.py", line 712, in completion
    client = init_bedrock_client(
             ^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\llms\bedrock.py", line 561, in init_bedrock_client
    raise BedrockError(
litellm.llms.bedrock.BedrockError: AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 1436, in function_with_retries
    response = original_function(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 386, in _completion
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 369, in _completion
    response = litellm.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\utils.py", line 2870, in wrapper
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\utils.py", line 2768, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\main.py", line 2094, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\utils.py", line 8362, in exception_type
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\utils.py", line 7487, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: BedrockException - AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\main.py", line 1773, in completion
    response = bedrock.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\llms\bedrock.py", line 1102, in completion
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\llms\bedrock.py", line 712, in completion
    client = init_bedrock_client(
             ^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\llms\bedrock.py", line 561, in init_bedrock_client
    raise BedrockError(
litellm.llms.bedrock.BedrockError: AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\agenthub\monologue_agent\utils\monologue.py", line 31, in condense
    resp = llm.completion(messages=messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 328, in completion
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 325, in completion
    response = self.function_with_fallbacks(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 1419, in function_with_fallbacks
    raise original_exception
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 1344, in function_with_fallbacks
    response = self.function_with_retries(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 1496, in function_with_retries
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 1462, in function_with_retries
    response = original_function(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 386, in _completion
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\router.py", line 369, in _completion
    response = litellm.completion(
               ^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\utils.py", line 2870, in wrapper
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\utils.py", line 2768, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\main.py", line 2094, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\utils.py", line 8362, in exception_type
    raise e
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\od\Lib\site-packages\litellm\utils.py", line 7487, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: BedrockException - AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\opendevin\controller\agent_controller.py", line 112, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\agenthub\monologue_agent\agent.py", line 153, in step
    self._add_event(prev_action.to_dict())
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\agenthub\monologue_agent\agent.py", line 96, in _add_event
    self.monologue.condense(self.llm)
  File "E:\Projects\AgentsV1.0\OpenDevin\OpenDevin\agenthub\monologue_agent\utils\monologue.py", line 36, in condense
    raise RuntimeError(f"Error condensing thoughts: {e}")
RuntimeError: Error condensing thoughts: BedrockException - AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file

OBSERVATION:
Error condensing thoughts: BedrockException - AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file
Exited before finishing

**Comment by ghost** [comment]
> Error condensing thoughts: BedrockException - AWS region not set: set AWS_REGION_NAME or AWS_REGION env variable or in .env file


This is the error. Are you trying to call bedrock? @Dr-Mohamed-Elkholy 

-- 
Would file this issue on opendevin, as litellm seems to raise the right error here. https://github.com/OpenDevin/OpenDevin
