### ISSUE TITLE
[Bug]: KeyError: 'content' when sending message without content to LightLLM proxy

### ISSUE THREAD

**Issue by repko-artem** [BerriAI/litellm#2858]
### What happened?

If I send message, that doesn't contain any content, i.e.
![image](https://github.com/BerriAI/litellm/assets/8638351/755cd90d-ea07-4e93-8fad-423038d82a52)

```
{
    'role': 'assistant',
    'tool_calls': [{
        'id': 'call_Bl78zSziAZlRvngHr3wI80Uu',
        'type': 'function',
        'function': {
            'name': 'get_current_datetime',
            'arguments': '{}'
        }
    }]
}
```
which is absolutely ok for OpenAI API:
![image](https://github.com/BerriAI/litellm/assets/8638351/3d407dc7-45eb-4a27-a2b1-dc01eab57512)

Then I get error 
**KeyError: 'content'**

That's because code src\litellm\utils.py, method **function_setup**:
```
rules_obj.pre_call_rules(
	input="".join(
		m["content"]
		for m in messages
		if isinstance(m["content"], str)
	),
	model=model,
)
```

It's enough to replace
```
isinstance(m["content"], str)
```
with
```
hasattr(m, "content") and isinstance(m["content"], str)
```

### Relevant log output

```shell
docker-compose-litellm-1  | INFO:LiteLLM Router:litellm.acompletion(model=openai/gpt-4-1106-preview) Exception 'content'
docker-compose-litellm-1  | 13:57:03 - LiteLLM Router:DEBUG: router.py:1146 - TracebackTraceback (most recent call last):
docker-compose-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 1142, in async_function_with_fallbacks
docker-compose-litellm-1  |     response = await self.async_function_with_retries(*args, **kwargs)
docker-compose-litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-compose-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 1280, in async_function_with_retries
docker-compose-litellm-1  |     raise original_exception
docker-compose-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 1238, in async_function_with_retries
docker-compose-litellm-1  |     response = await original_function(*args, **kwargs)
docker-compose-litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-compose-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 484, in _acompletion
docker-compose-litellm-1  |     raise e
docker-compose-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 460, in _acompletion
docker-compose-litellm-1  |     response = await litellm.acompletion(
docker-compose-litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-compose-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 3376, in wrapper_async
docker-compose-litellm-1  |     raise e
docker-compose-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 2939, in wrapper_async
docker-compose-litellm-1  |     logging_obj, kwargs = function_setup(start_time, *args, **kwargs)
docker-compose-litellm-1  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
docker-compose-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 2537, in function_setup
docker-compose-litellm-1  |     raise e
docker-compose-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 2473, in function_setup
docker-compose-litellm-1  |     input="".join(
docker-compose-litellm-1  |           ^^^^^^^^
docker-compose-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 2476, in <genexpr>
docker-compose-litellm-1  |     if isinstance(m["content"], str)
docker-compose-litellm-1  |                   ~^^^^^^^^^^^
docker-compose-litellm-1  | KeyError: 'content'
```

**Comment by ghost** [comment]
Thanks for this @repko-artem - just pushed the fix https://github.com/BerriAI/litellm/commit/7b30e5ae381823b44bfc95beb8c2ac504d012981

Will be live in v`1.34.31`

**Comment by arkadiy-telegin** [comment]
Hey @krrishdholakia, the bug persists in `v1.35.12`. The fix doesn't work and the example provided by @repko-artem still throws a KeyError

```python
  File "XXX/lib/python3.11/site-packages/litellm/utils.py", line 2525, in <genexpr>
    if isinstance(m["content"], str)
                  ~^^^^^^^^^^^
KeyError: 'content'
```

Changing the line 2525 to the one proposed by @repko-artem should fix the issue.

**Comment by ghost** [comment]
hey @repko-artem @arkadiy-telegin what is a situation in which the content would not be passed in? 

Will try and incorporate this in our testing as well

**Comment by ghost** [comment]
fixed - https://github.com/BerriAI/litellm/commit/6eb8fe35c8e0642c3efd9427b596d113d5697de1

also added unit testing for this scenario. Should be live soon in v`1.35.13+`

**Comment by repko-artem** [comment]
> hey @repko-artem @arkadiy-telegin what is a situation in which the content would not be passed in?
> 
> Will try and incorporate this in our testing as well

@krrishdholakia Hi. As I've mentioned in the top message, 'content' is not required when assistant queries function calling with function_call (deprecated) or tool_calls specified in its message. That's due to OpenAI Api documentation.

**Comment by repko-artem** [comment]
Hi, @krrishdholakia. The bug is still there (used ghcr.io/berriai/litellm:main-latest)
If content is null, the same error at the same place.
![image](https://github.com/BerriAI/litellm/assets/8638351/d9a63d70-1031-4fa1-93b4-d2866539d7fd)

To reproduce you just need to pass the message without content.
I.e.
```
{
	'role': 'assistant',
	'tool_call_id': 'call_e4a7fe41-c39b-45f2-94a0-fc6077a263c6',
	'tool_calls': [{
		'id': 'call_e4a7fe41-c39b-45f2-94a0-fc6077a263c6',
		'type': 'function',
		'function': {
			'name': 'VacationIntent_intent',
			'arguments': '{}'
		}
	}]
}
```

**Comment by repko-artem** [comment]
Made some additional debugging and found out that it's code related to Bedrock:
![image](https://github.com/BerriAI/litellm/assets/8638351/06ffbd60-37f9-45db-a08c-38a79fefdf0d)

**Comment by ghost** [comment]
Fix pushed @repko-artem - https://github.com/BerriAI/litellm/commit/54c31e5af785340f85062b68a1032ac7898fe22e
