### ISSUE TITLE
[Bug]: Error LLM Provider NOT provided when using groq/mixtral-8x7b-32768 in the cli mode

### ISSUE THREAD

**Issue by therohitdas** [BerriAI/litellm#2863]
### What happened?

I am trying to use litellm as proxy to groq. I want to use it with [twinny vscode extension.](https://github.com/rjmacarthy/twinny)

I am getting the error : `An error occurred: LLM Provider NOT provided.`

My config:
```yaml
model_list:
  - model_name: groq-mixtral # user-facing model alias
    litellm_params:
      model: groq/mixtral-8x7b-32768
      api_base: https://api.groq.com/openai/v1/
      api_key: gsk_<redacted groq api key>
      max_tokens: 32000
      rpm: 30
```
Command I use to run the proxy:
```bash
litellm --config config.yaml --debug  
```

Command I used to test the proxy
```bash
litellm --model groq-mixtral --test
```

I used documentation from https://docs.litellm.ai/docs/providers/groq and https://docs.litellm.ai/docs/proxy/quick_start

I get the error : `An error occurred: LLM Provider NOT provided.`

What I have tried:
1. Removing `api_base`
2. Changing `model_name`
3. Using `model: openai/mixtral-8x7b-32768` , a different error happens when using this:
```bash
INFO:     127.0.0.1:64291 - "POST /chat/completions HTTP/1.1" 200 OK
user sent model not in config, using default config model
litellm.caching: False; litellm.caching_with_models: False; litellm.cache: None
kwargs[caching]: False; litellm.cache: None

LiteLLM completion() model= mixtral-8x7b-32768

LiteLLM: Params passed to completion() {'functions': [], 'function_call': '', 'temperature': None, 'top_p': None, 'n': None, 'stream': True, 'stop': None, 'max_tokens': 32000, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': {}, 'user': '', 'model': 'mixtral-8x7b-32768', 'custom_llm_provider': 'openai', 'rpm': 30}

LiteLLM: Non-Default params passed to completion() {'stream': True, 'max_tokens': 32000}
self.optional_params: {'stream': True, 'max_tokens': 32000, 'rpm': 30}
Logging Details Pre-API Call for call id 8c0280c2-a7d3-4bc2-9949-68b734cad3ea
MODEL CALL INPUT: {'model': 'mixtral-8x7b-32768', 'messages': [{'role': 'user', 'content': 'this is a test request, write a short poem'}], 'optional_params': {'stream': True, 'max_tokens': 32000, 'rpm': 30}, 'litellm_params': {'return_async': False, 'api_key': 'gsk_<redacted>', 'force_timeout': 600, 'logger_fn': None, 'verbose': False, 'custom_llm_provider': 'openai', 'api_base': 'https://api.groq.com/openai/v1/', 'litellm_call_id': '8c0280c2-a7d3-4bc2-9949-68b734cad3ea', 'model_alias_map': {}, 'completion_call_id': None, 'metadata': None, 'stream_response': {}}, 'start_time': datetime.datetime(2024, 4, 5, 23, 37, 4, 444908), 'input': [{'role': 'user', 'content': 'this is a test request, write a short poem'}], 'api_key': 'gsk_<redacted>', 'additional_args': {'headers': {'content-type': 'application/json', 'Authorization': 'Bearer gsk_<redacted>'}, 'api_base': 'https://api.groq.com/openai/v1//chat/completions', 'acompletion': False, 'data': {'model': 'mixtral-8x7b-32768', 'messages': [{'role': 'user', 'content': 'this is a test request, write a short poem'}], 'stream': True, 'max_tokens': 32000, 'rpm': 30}}, 'log_event_type': 'pre_api_call'}


RAW RESPONSE: {'model': 'mixtral-8x7b-32768', 'messages': [{'role': 'user', 'content': 'this is a test request, write a short poem'}], 'optional_params': {'stream': True, 'max_tokens': 32000, 'rpm': 30}, 'litellm_params': {'return_async': False, 'api_key': 'gsk_<redacted>', 'force_timeout': 600, 'logger_fn': None, 'verbose': False, 'custom_llm_provider': 'openai', 'api_base': 'https://api.groq.com/openai/v1/', 'litellm_call_id': '8c0280c2-a7d3-4bc2-9949-68b734cad3ea', 'model_alias_map': {}, 'completion_call_id': None, 'metadata': None, 'stream_response': {}}, 'start_time': datetime.datetime(2024, 4, 5, 23, 37, 4, 444908), 'input': [{'role': 'user', 'content': 'this is a test request, write a short poem'}], 'api_key': 'gsk_<redacted>', 'additional_args': {'headers': None}, 'log_event_type': 'post_api_call', 'original_response': <generator object OpenAIChatCompletion.streaming at 0x10ca2d1c0>}


Logging Details Post-API Call: logger_fn - None | callable(logger_fn) - False
INFO:     127.0.0.1:64291 - "POST /chat/completions HTTP/1.1" 200 OK
inside generator
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/opt/homebrew/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/routing.py", line 69, in app
    await response(scope, receive, send)
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/responses.py", line 270, in __call__
    async with anyio.create_task_group() as task_group:
  File "/opt/homebrew/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/responses.py", line 273, in wrap
    await func()
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/responses.py", line 262, in stream_response
    async for chunk in self.body_iterator:
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/concurrency.py", line 63, in iterate_in_threadpool
    yield await anyio.to_thread.run_sync(_next, iterator)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/starlette/concurrency.py", line 53, in _next
    return next(iterator)
           ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 411, in data_generator
    for chunk in response:
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/llms/openai.py", line 279, in streaming
    raise OpenAIError(status_code=response.status_code, message=response.text()) # type: ignore
                                                                ^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/httpx/_models.py", line 573, in text
    content = self.content
              ^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/httpx/_models.py", line 567, in content
    raise ResponseNotRead()
httpx.ResponseNotRead: Attempted to access streaming response content, without having called `read()`.
```

### Relevant log output

```shell
(base) therohitdas:litellm/ $ litellm --config config.yaml --debug                                                                                                                           [23:35:36]
INFO:     Started server process [38090]
INFO:     Waiting for application startup.

#------------------------------------------------------------#
#                                                            #
#           'It would help me if you could add...'            #
#        https://github.com/BerriAI/litellm/issues/new        #
#                                                            #
#------------------------------------------------------------#

 Thank you for using LiteLLM! - Krrish & Ishaan



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new

Docs: https://docs.litellm.ai/docs/simple_proxy

LiteLLM: Test your local endpoint with: "litellm --test" [In a new terminal tab]


Configs passed in, loaded config YAML
{'model_list': [{'model_name': 'groq-mixtral', 'litellm_params': {'model': 'groq/mixtral-8x7b-32768', 'api_base': 'https://api.groq.com/openai/v1/', 'api_key': 'gsk_<redacted>', 'max_tokens': 32000, 'rpm': 30}}]}
LiteLLM: Proxy initialized with Config, Set models:
    groq-mixtral

INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
user sent model not in config, using default config model
litellm.caching: False; litellm.caching_with_models: False; litellm.cache: None
kwargs[caching]: False; litellm.cache: None

Provider List: https://docs.litellm.ai/docs/providers

Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
self.failure_callback: []
An error occurred: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/groq/mixtral-8x7b-32768',..)` Learn more: https://docs.litellm.ai/docs/providers

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
INFO:     127.0.0.1:64243 - "POST /chat/completions HTTP/1.1" 200 OK
user sent model not in config, using default config model
litellm.caching: False; litellm.caching_with_models: False; litellm.cache: None
kwargs[caching]: False; litellm.cache: None

Provider List: https://docs.litellm.ai/docs/providers

Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
self.failure_callback: []
An error occurred: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/groq/mixtral-8x7b-32768',..)` Learn more: https://docs.litellm.ai/docs/providers

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
INFO:     127.0.0.1:64243 - "POST /chat/completions HTTP/1.1" 200 OK
user sent model not in config, using default config model

Provider List: https://docs.litellm.ai/docs/providers

An error occurred: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/groq/mixtral-8x7b-32768',..)` Learn more: https://docs.litellm.ai/docs/providers

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/groq/mixtral-8x7b-32768',..)` Learn more: https://docs.litellm.ai/docs/providers

Traceback (most recent call last):
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 515, in completion
    return litellm_completion(
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 449, in litellm_completion
    response = litellm.text_completion(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/main.py", line 1941, in text_completion
    _, custom_llm_provider, dynamic_api_key, api_base = get_llm_provider(model=model, custom_llm_provider=custom_llm_provider, api_base=api_base)
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/utils.py", line 2098, in get_llm_provider
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/utils.py", line 2095, in get_llm_provider
    raise ValueError(f"LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/{model}',..)` Learn more: https://docs.litellm.ai/docs/providers")
ValueError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/groq/mixtral-8x7b-32768',..)` Learn more: https://docs.litellm.ai/docs/providers

INFO:     127.0.0.1:64243 - "POST /completions HTTP/1.1" 200 OK
```

**Comment by ishaan-jaff** [comment]
@therohitdas what litellm version are you running this on ? Can you try bumping to latest and trying 

 can you share the request you're sending to litellm proxy (eg a curl command would help)

**Comment by therohitdas** [comment]
Hi Ishaan,
I was using LiteLLM: Current Version = 1.34.27.

I bumped to the latest version and everything works now. Sorry for this noob mistake, thanks for the support.
