### ISSUE TITLE
[Bug]: Litellm was not starting, now it starts but Admin UI not working (update)

### ISSUE THREAD

**Issue by benahmedadel** [BerriAI/litellm#2922]
### What happened?

I am unable to start litellm
Can you give me please full procdure to init prisma schema
I do every thing:
prisma init
prisma db pull
prisma generate

But when it starts, i have following errors.
I am completely blocked.
Please help me.

### Relevant log output

```shell
The database is already in sync with the Prisma schema.

1 validation error for PythonData
  Value error, Prisma Client Python expected Prisma version: ac9d7041ed77bcc8a8dbd2ab6616b39013829574 but got: 0a83d8541752d7582de2ebc1ece46519ce72a
848
  If this is intentional, set the PRISMA_PY_DEBUG_GENERATOR environment variable to 1 and try again.
  If you are using the Node CLI then you must switch to v5.4.2, e.g. npx prisma@5.4.2 generate
  or generate the client using the Python CLI, e.g. python3 -m prisma generate [type=value_error, input_value={'datamodel': 'datasource...debian-ope
nssl-3.0.x'}}}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/value_error

ERROR:    Traceback (most recent call last):
  File "/appli/litellm/venv/lib/python3.10/site-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/appli/litellm/venv/lib/python3.10/site-packages/starlette/routing.py", line 608, in __aenter__
    await self._router.startup()
  File "/appli/litellm/venv/lib/python3.10/site-packages/starlette/routing.py", line 709, in startup
    await handler()
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 2966, in startup_event
    prisma_setup(database_url=os.getenv("DATABASE_URL"))
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 1149, in prisma_setup
    raise e
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 1145, in prisma_setup
    prisma_client = PrismaClient(
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 601, in __init__
    from prisma import Prisma  # type: ignore
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/__init__.py", line 50, in __getattr__
    raise RuntimeError(
RuntimeError: The Client hasn't been generated yet, you must run `prisma generate` before you can use the client.
See https://prisma-client-py.readthedocs.io/en/stable/reference/troubleshooting/#client-has-not-been-generated-yet
```

**Comment by benahmedadel** [comment]
@krrishdholakia It is not related to azure as you think for this bug.
It is related to prisma

After i migrate to Litellm 1.34.38, API and proxy are working but not admin UI
`Traceback (most recent call last):
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 2670, in generate_key_helper_fn
    user_row = await prisma_client.update_data(
  File "/appli/litellm/venv/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 1460, in update_data
    raise e
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 1335, in update_data
    update_user_row = await self.db.litellm_usertable.upsert(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/actions.py", line 4826, in upsert
    resp = await self._client._execute(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/client.py", line 510, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_response_errors(resp, errors_data)
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/utils.py", line 192, in handle_response_errors
    raise exc(error)
prisma.errors.FieldNotFoundError: Could not find field at `upsertOneLiteLLM_UserTable.create.organization_id`
Task exception was never retrieved
future: <Task finished name='Task-10' coro=<generate_key_helper_fn() done, defined at /appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py:2521> exception=HTTPException(status_code=500, detail={'error': 'Internal Server Error.'})>
Traceback (most recent call last):
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 2670, in generate_key_helper_fn
    user_row = await prisma_client.update_data(
  File "/appli/litellm/venv/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 1460, in update_data
    raise e
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 1335, in update_data
    update_user_row = await self.db.litellm_usertable.upsert(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/actions.py", line 4826, in upsert
    resp = await self._client._execute(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/client.py", line 510, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_response_errors(resp, errors_data)
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/utils.py", line 192, in handle_response_errors
    raise exc(error)
prisma.errors.FieldNotFoundError: Could not find field at `upsertOneLiteLLM_UserTable.create.organization_id`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 2714, in generate_key_helper_fn
    raise HTTPException(
fastapi.exceptions.HTTPException: 500: {'error': 'Internal Server Error.'}
Traceback (most recent call last):
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 2670, in generate_key_helper_fn
    user_row = await prisma_client.update_data(
  File "/appli/litellm/venv/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 1460, in update_data
    raise e
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 1335, in update_data
    update_user_row = await self.db.litellm_usertable.upsert(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/actions.py", line 4826, in upsert
    resp = await self._client._execute(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/client.py", line 510, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_response_errors(resp, errors_data)
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/utils.py", line 192, in handle_response_errors
    raise exc(error)
prisma.errors.FieldNotFoundError: Could not find field at `upsertOneLiteLLM_UserTable.create.organization_id`
Task exception was never retrieved
future: <Task finished name='Task-11' coro=<generate_key_helper_fn() done, defined at /appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py:2521> exception=HTTPException(status_code=500, detail={'error': 'Internal Server Error.'})>
Traceback (most recent call last):
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 2670, in generate_key_helper_fn
    user_row = await prisma_client.update_data(
  File "/appli/litellm/venv/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 1460, in update_data
    raise e
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 1335, in update_data
    update_user_row = await self.db.litellm_usertable.upsert(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/actions.py", line 4826, in upsert
    resp = await self._client._execute(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/client.py", line 510, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_response_errors(resp, errors_data)
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/utils.py", line 192, in handle_response_errors
    raise exc(error)
prisma.errors.FieldNotFoundError: Could not find field at `upsertOneLiteLLM_UserTable.create.organization_id`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 2714, in generate_key_helper_fn
    raise HTTPException(
fastapi.exceptions.HTTPException: 500: {'error': 'Internal Server Error.'}`

**Comment by benahmedadel** [comment]
It is little better as it starts right now but i am unable to go on UI admin or manage tokens.


`Traceback (most recent call last):
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 2670, in generate_key_helper_fn
    user_row = await prisma_client.update_data(
  File "/appli/litellm/venv/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 1460, in update_data
    raise e
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 1335, in update_data
    update_user_row = await self.db.litellm_usertable.upsert(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/actions.py", line 4826, in upsert
    resp = await self._client._execute(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/client.py", line 510, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_response_errors(resp, errors_data)
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/utils.py", line 192, in handle_response_errors
    raise exc(error)
prisma.errors.FieldNotFoundError: Could not find field at `upsertOneLiteLLM_UserTable.create.organization_id`
Task exception was never retrieved
future: <Task finished name='Task-10' coro=<generate_key_helper_fn() done, defined at /appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py:2521> exception=HTTPException(status_code=500, detail={'error': 'Internal Server Error.'})>
Traceback (most recent call last):
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 2670, in generate_key_helper_fn
    user_row = await prisma_client.update_data(
  File "/appli/litellm/venv/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 1460, in update_data
    raise e
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 1335, in update_data
    update_user_row = await self.db.litellm_usertable.upsert(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/actions.py", line 4826, in upsert
    resp = await self._client._execute(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/client.py", line 510, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_response_errors(resp, errors_data)
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/utils.py", line 192, in handle_response_errors
    raise exc(error)
prisma.errors.FieldNotFoundError: Could not find field at `upsertOneLiteLLM_UserTable.create.organization_id`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 2714, in generate_key_helper_fn
    raise HTTPException(
fastapi.exceptions.HTTPException: 500: {'error': 'Internal Server Error.'}
Traceback (most recent call last):
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 2670, in generate_key_helper_fn
    user_row = await prisma_client.update_data(
  File "/appli/litellm/venv/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 1460, in update_data
    raise e
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 1335, in update_data
    update_user_row = await self.db.litellm_usertable.upsert(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/actions.py", line 4826, in upsert
    resp = await self._client._execute(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/client.py", line 510, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_response_errors(resp, errors_data)
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/utils.py", line 192, in handle_response_errors
    raise exc(error)
prisma.errors.FieldNotFoundError: Could not find field at `upsertOneLiteLLM_UserTable.create.organization_id`
Task exception was never retrieved
future: <Task finished name='Task-11' coro=<generate_key_helper_fn() done, defined at /appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py:2521> exception=HTTPException(status_code=500, detail={'error': 'Internal Server Error.'})>
Traceback (most recent call last):
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 2670, in generate_key_helper_fn
    user_row = await prisma_client.update_data(
  File "/appli/litellm/venv/lib/python3.10/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 1460, in update_data
    raise e
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/utils.py", line 1335, in update_data
    update_user_row = await self.db.litellm_usertable.upsert(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/actions.py", line 4826, in upsert
    resp = await self._client._execute(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/client.py", line 510, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_response_errors(resp, errors_data)
  File "/appli/litellm/venv/lib/python3.10/site-packages/prisma/engine/utils.py", line 192, in handle_response_errors
    raise exc(error)
prisma.errors.FieldNotFoundError: Could not find field at `upsertOneLiteLLM_UserTable.create.organization_id`

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/appli/litellm/venv/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 2714, in generate_key_helper_fn
    raise HTTPException(
fastapi.exceptions.HTTPException: 500: {'error': 'Internal Server Error.'}`

**Comment by ghost** [comment]
Hey @benahmedadel 

> prisma.errors.FieldNotFoundError: Could not find field atupsertOneLiteLLM_UserTable.create.organization_id

can you share your server startup logs. I believe the db schema might be out of sync. 

You should see something like this: 

```
Prisma schema loaded from schema.prisma
Datasource "client": PostgreSQL database "test3", schema "public" at "ep-bitter-fog-a573fgz9.us-east-2.aws.neon.tech"

The database is already in sync with the Prisma schema.

Running generate... - Prisma Client Python (v0.11.0)

Some types are disabled by default due to being incompatible with Mypy, it is highly recommended
to use Pyright instead and configure Prisma Python to use recursive types. To re-enable certain types:

generator client {
  provider             = "prisma-client-py"
  recursive_type_depth = -1
}

If you need to use Mypy, you can also disable this message by explicitly setting the default value:

generator client {
  provider             = "prisma-client-py"
  recursive_type_depth = 5
}

For more information see: https://prisma-client-py.readthedocs.io/en/stable/reference/limitations/#default-type-limitations

✔ Generated Prisma Client Python (v0.11.0) to ./../../prisma in 136ms
```

**Comment by benahmedadel** [comment]
I updated prisma client and everything is ok.
Thank you very much.
