### ISSUE TITLE
litellm.exceptions.APIConnectionError: 'eval_count'

### ISSUE THREAD

**Issue by katmai** [BerriAI/litellm#2960]
hi, i am running opendevin and i ran into this error. putting it here.
cheers,

```
==============
STEP 13

PLAN:
write a bash script that prints hi

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.


ERROR:
'eval_count'
Traceback (most recent call last):
  File "/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/litellm/main.py", line 1904, in completion
    generator = ollama.get_ollama_response(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/litellm/llms/ollama.py", line 232, in get_ollama_response
    completion_tokens = response_json["eval_count"]
                        ~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'eval_count'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/atlas/OpenDevin/opendevin/controller/agent_controller.py", line 135, in step
    action = self.agent.step(self.state)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atlas/OpenDevin/agenthub/monologue_agent/agent.py", line 215, in step
    resp = self.llm.completion(messages=messages)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atlas/OpenDevin/opendevin/llm/llm.py", line 38, in wrapper
    resp = completion_unwrapped(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 2947, in wrapper
    raise e
  File "/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 2845, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/litellm/main.py", line 2119, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 8526, in exception_type
    raise e
  File "/home/atlas/.cache/pypoetry/virtualenvs/opendevin-WmySEtCI-py3.11/lib/python3.11/site-packages/litellm/utils.py", line 8501, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: 'eval_count'

OBSERVATION:
'eval_count'

```

**Comment by ishaan-jaff** [comment]
I believe this PR fixes it https://github.com/BerriAI/litellm/pull/2892/files

**Comment by ishaan-jaff** [comment]
PR merged and fixed

**Comment by katmai** [comment]
thanks, bubba
