### ISSUE TITLE
[Bug]: Empty model_list prevents the loading of new models that are added via the ui

### ISSUE THREAD

**Issue by zJuuu** [BerriAI/litellm#2979]
### What happened?

A fresh installation of litellm with database and no configured model_list prevents the loading of new models that are added via the ui.
It requires a restart to load the model data from the database.

### Relevant log output

```shell
On first start:
litellm-1    | 08:29:23 - LiteLLM Proxy:ERROR: proxy_server.py:2509 - 'Router' object has no attribute 'model_list'
litellm-1    | Traceback:Traceback (most recent call last):
litellm-1    |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2485, in add_deployment
litellm-1    |     llm_model_list = llm_router.get_model_list()
litellm-1    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1    |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2255, in get_model_list
litellm-1    |     return self.model_list
litellm-1    |            ^^^^^^^^^^^^^^^
litellm-1    | AttributeError: 'Router' object has no attribute 'model_list'


After adding model through ui:

litellm-1    | 08:32:23 - LiteLLM Proxy:ERROR: proxy_server.py:2509 - 'Router' object has no attribute 'model_list'
litellm-1    | Traceback:Traceback (most recent call last):
litellm-1    |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2485, in add_deployment
litellm-1    |     llm_model_list = llm_router.get_model_list()
litellm-1    |                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1    |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2255, in get_model_list
litellm-1    | Traceback:Traceback (most recent call last):
litellm-1    |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2477, in add_deployment
litellm-1    |     llm_router.add_deployment(
litellm-1    |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2222, in add_deployment
litellm-1    |     if deployment.model_info.id in self.get_model_ids():
litellm-1    |                                    ^^^^^^^^^^^^^^^^^^^^
litellm-1    |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2245, in get_model_ids
litellm-1    |     for model in self.model_list:
litellm-1    |                  ^^^^^^^^^^^^^^^
litellm-1    | AttributeError: 'Router' object has no attribute 'model_list'
```

**Comment by ghost** [comment]
Able to repro

**Comment by ghost** [comment]
pushed fix - https://github.com/BerriAI/litellm/commit/43c37c31ea4e88fd91bb85f66e188507e2b3e8b2

**Comment by ghost** [comment]
should be live soon in v`1.35.6`
