### ISSUE TITLE
[Bug]: Claude 2 in async stopped working

### ISSUE THREAD

**Issue by joch** [BerriAI/litellm#3027]
### What happened?

Hi,

Calling `completion` with claude-2 works fine, but I'm getting an error with the async `acompletion` call. Could this be a bug in litellm?

### Relevant log output

```shell
import asyncio
import litellm

response = litellm.completion(
    model="claude-2",
    api_key="sk-ant-xx",
    messages=[{"role": "user", "content": "hello from litellm"}],
)
print(response)


async def fetch_completion():
    response = await litellm.acompletion(
        model="claude-2",
        api_key="sk-ant-xx",
        messages=[{"role": "user", "content": "hello from litellm"}],
        stream=True,
    )
    async for data in response:
        print(data)


if __name__ == "__main__":
    asyncio.run(fetch_completion())

#### output below ####

ModelResponse(id='chatcmpl-8b364e6c-c522-4198-b338-2128e251d509', choices=[Choices(finish_reason='stop_sequence', index=0, message=Message(content=" Hello! I'm Claude, an AI assistant created by Anthropic.", role='assistant'))], created=1713188552, model='claude-2', object='chat.completion', system_fingerprint=None, usage=Usage(prompt_tokens=12, completion_tokens=14, total_tokens=26))

Traceback (most recent call last):
  File "/app4.py", line 24, in <module>
    asyncio.run(fetch_completion())
  File "/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/lib/python3.12/asyncio/base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/app4.py", line 19, in fetch_completion
    async for data in response:
  File "/.venv/lib/python3.12/site-packages/litellm/utils.py", line 10168, in __anext__
    raise e
  File "/.venv/lib/python3.12/site-packages/litellm/utils.py", line 10052, in __anext__
    async for chunk in self.completion_stream:
TypeError: 'async for' requires an object with __aiter__ method, got generator
```

**Comment by ghost** [comment]
able to repro. working on a fix. 

seems like this was impacted by the claude 3 transition.

**Comment by ghost** [comment]
Merged into main - testing now added for sync + async claude 2 completion + streaming calls to prevent future regressions. 

Will be live in next release - `v1.35.6+`

**Comment by ghost** [comment]
@joch did this work for you?

**Comment by joch** [comment]
@krrishdholakia Just confirmed this morning, and it works. Thanks for the quick turnaround!
