### ISSUE TITLE
[Bug]: Bedrock x Mistral-Large

### ISSUE THREAD

**Issue by Extremys** [BerriAI/litellm#3037]
### What happened?

Hello team!
It seems that depending on how you submit a completion there is a buggy behaviour. I don't have any issue with claude models.
Any idea?
Commit used 816c925bdd955d58415a7b4e06eac40f70e58762 (so almost version https://github.com/BerriAI/litellm/releases/tag/v1.35.5 )
My config.yml :
```yaml
  - model_name: mistral-large-v1
    litellm_params:
      model: bedrock/mistral.mistral-large-2402-v1:0
      aws_region_name: eu-west-3
```
Thank for your help!

### Relevant log output

```shell
18:39:56 - LiteLLM Router:INFO: router.py:509 - litellm.acompletion(model=bedrock/mistral.mistral-large-2402-v1:0) 200 OK
18:39:56 - LiteLLM Router:ERROR: router.py:2813 - Error in _track_deployment_metrics: 'CustomStreamWrapper' object has no attribute 'get'
Initialized litellm callbacks, Async Success Callbacks: [<litellm.proxy.hooks.parallel_request_limiter._PROXY_MaxParallelRequestsHandler object at 0x7ffbbda00b20>, <litellm.proxy.hooks.tpm_rpm_limiter._PROXY_MaxTPMRPMLimiter object at 0x7ffbbda17880>, <litellm.proxy.hooks.max_budget_limiter._PROXY_MaxBudgetLimiter object at 0x7ffbbda177f0>, <litellm.proxy.hooks.cache_control_check._PROXY_CacheControlCheck object at 0x7ffbbda17790>, <bound method ProxyLogging.response_taking_too_long_callback of <litellm.proxy.utils.ProxyLogging object at 0x7ffbbda00e20>>]
self.optional_params: {}
litellm.cache: None
kwargs[caching]: False; litellm.cache: None
Final returned optional params: {'max_tokens': 8092, 'temperature': 0.6, 'top_p': 0.95, 'stop': ['</s>'], 'stream': True, 'aws_region_name': 'eu-west-3'}
self.optional_params: {'max_tokens': 8092, 'temperature': 0.6, 'top_p': 0.95, 'stop': ['</s>'], 'stream': True, 'aws_region_name': 'eu-west-3'}
RAW RESPONSE:
<litellm.utils.CustomStreamWrapper object at 0x7ffb89727370>


INFO:     192.24.25.16:8750 - "POST /v1/chat/completions HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/code/litellm/litellm/proxy/proxy_server.py", line 2981, in async_data_generator
    async for chunk in response:
  File "/code/litellm/litellm/utils.py", line 10202, in __anext__
    raise e
  File "/code/litellm/litellm/utils.py", line 10134, in __anext__
    chunk = next(self.completion_stream)
  File "/usr/local/lib/python3.10/dist-packages/botocore/eventstream.py", line 603, in __iter__
    parsed_event = self._parse_event(event)
  File "/usr/local/lib/python3.10/dist-packages/botocore/eventstream.py", line 619, in _parse_event
    raise EventStreamError(parsed_response, self._operation_name)
botocore.exceptions.EventStreamError: An error occurred (validationException) when calling the InvokeModelWithResponseStream operation: Validation Error
Traceback (most recent call last):
  File "/code/litellm/litellm/proxy/proxy_server.py", line 2981, in async_data_generator
    async for chunk in response:
  File "/code/litellm/litellm/utils.py", line 10202, in __anext__
    raise e
  File "/code/litellm/litellm/utils.py", line 10134, in __anext__
    chunk = next(self.completion_stream)
  File "/usr/local/lib/python3.10/dist-packages/botocore/eventstream.py", line 603, in __iter__
    parsed_event = self._parse_event(event)
  File "/usr/local/lib/python3.10/dist-packages/botocore/eventstream.py", line 619, in _parse_event
    raise EventStreamError(parsed_response, self._operation_name)
botocore.exceptions.EventStreamError: An error occurred (validationException) when calling the InvokeModelWithResponseStream operation: Validation Error
Inside Max Parallel Request Failure Hook
```

**Comment by ghost** [comment]
Hey @Extremys unable to repro this behaviour for either streaming or non-streaming responses 
<img width="1000" alt="Screenshot 2024-04-15 at 3 54 05 PM" src="https://github.com/BerriAI/litellm/assets/17561003/54f9b8fe-bcf4-4aca-a440-9fa61266e4ba">

<img width="1256" alt="Screenshot 2024-04-15 at 3 54 37 PM" src="https://github.com/BerriAI/litellm/assets/17561003/d60207a7-1fe2-473f-b59a-31ed2f1411b7">

**Comment by ghost** [comment]
Do you have a consistent repro for this? @Extremys

**Comment by ghost** [comment]
closing as no-op, as this works fine on our end. 

@Extremys i've added this model on our staging environment - staging.litellm.ai (on main-latest)

API: https://staging.litellm.ai/
Key: sk-d908hmdz8jtobD-M883_lg


```bash

curl --location 'https://staging.litellm.ai/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer sk-d908hmdz8jtobD-M883_lg' \
--data '{
  "model": "mistral-large-v1",
  "messages": [
    { "role": "user", "content": "Hey!" }
    ],
"stream": true
}'

```

Let me know if you're able to repro the error on this 

P.S.: the key has a max budget, to limit abuse.

**Comment by ghost** [comment]
Curious, would you ever want to use a hosted-LiteLLM proxy? 

- What would a good solution here look like for you?
