### ISSUE TITLE
[Bug]: High Traffic error -  Can't reach database server at

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#3110]
### What happened?

How to repro:

- send 100 concurrent requests to the proxy from a key not in cache 
- The proxy had been running for 30 mins - 1 hour 
- had slack alerting on 

### Relevant log output

```shell
Message: DB read/write call failed: Can't reach database server at ep-icy-snow-a***

Please make sure your database server is running at ep-icy-*****2.LiteLLM Prisma Client Exception: Error with get_data. Args passed in: {'self': <litellm.proxy.utils.PrismaClient object at 0x7fbc2c69b950>, 'token': '*****', 'user_id': None, 'user_id_list': None, 'team_id': None, 'team_id_list': None, 'key_val': None, 'table_name': 'combined_view', 'query_type': 'find_unique', 'expires': None, 'reset_at': None, 'offset': None, 'limit': None}Can't reach database server at ep-ic
Please make sure your database server is running at e2.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 1098, in get_data
    response = await self.db.query_first(query=sql_query)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/client.py", line 374, in query_first
    results = await self.quer
```

**Comment by ishaan-jaff** [comment]
I also got 100+ alerts on slack for this 1 exception

**Comment by ishaan-jaff** [comment]
closing since this occurred one time - did not see it after
