### ISSUE TITLE
start yaml ,  then get error after add line for health           

### ISSUE THREAD

**Issue by wac81** [BerriAI/litellm#3201]
### What happened?

get error after add line for health          

model_list:
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/openchat-gpu01
      api_key: sk-1234
      api_base: http://192.168.1.14:8001/v1
    model_info:
      mode: completion #  ADD THIS
  - model_name: gpt-3.5-turbo
    litellm_params:
      model: openai/openchat-gpu02
      api_key: sk-1234
      api_base: http://192.168.1.100:8001/v1
    model_info:
      mode: completion #  ADD THIS

router_settings:
    routing_strategy: "least-busy"
general_settings:
    background_health_checks: True # enable background health checks
    health_check_interval: 30 # frequency of background health checks

start litellm use
litellm --config multi_llama.cpp.yaml

### Relevant log output

```shell
Traceback (most recent call last):
  File "/data/miniconda3/envs/py311/lib/python3.11/site-packages/litellm/main.py", line 3790, in ahealth_check
    response = await openai_chat_completions.ahealth_check(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda3/envs/py311/lib/python3.11/site-packages/litellm/llms/openai.py", line 942, in ahealth_check
    completion = await client.completions.with_raw_response.create(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda3/envs/py311/lib/python3.11/site-packages/openai/_legacy_response.py", line 353, in wrapped
    return cast(LegacyAPIResponse[R], await func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda3/envs/py311/lib/python3.11/site-packages/openai/resources/completions.py", line 1036, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/data/miniconda3/envs/py311/lib/python3.11/site-packages/openai/_base_client.py", line 1782, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda3/envs/py311/lib/python3.11/site-packages/openai/_base_client.py", line 1485, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/data/miniconda3/envs/py311/lib/python3.11/site-packages/openai/_base_client.py", line 1576, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: File Not Found
```

**Comment by wac81** [comment]
LiteLLM: Current Version = 1.35.4
