### ISSUE TITLE
[Bug]: UI ignoring master key

### ISSUE THREAD

**Issue by VfBfoerst** [BerriAI/litellm#3206]
### What happened?

In the UI, I login via Username: admin and password: master key which is set in the config.yaml:  
```yaml
general_settings:
  master_key: sk-1234
```
But I receive a lot of unauthorized messages from the ui which stat that master key must be used:  
![image](https://github.com/BerriAI/litellm/assets/64251549/d4943d3c-1f75-4bff-91a0-b8958ab49ac6)
  
I already use it.  
 

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 1057, in user_api_key_auth
    raise Exception(
Exception: Only master key can be used to generate, delete, update info for new keys/users/teams. Route=/user/get_requests
INFO:     10.89.11.62:46552 - "GET /user/get_requests HTTP/1.1" 401 Unauthorized
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 1057, in user_api_key_auth
    raise Exception(
Exception: Only master key can be used to generate, delete, update info for new keys/users/teams. Route=/user/get_requests
INFO:     10.89.11.62:46552 - "GET /user/get_requests HTTP/1.1" 401 Unauthorized
INFO:     10.89.11.62:33724 - "GET /ui/?userID=admin&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYWRtaW4iLCJrZXkiOiJzay12VFVueXA5dVBKZk5EMDJCZzdiRkx3IiwidXNlcl9lbWFpbCI6ImFkbWluIiwidXNlcl9yb2xlIjoiYXBwX2FkbWluIiwibG9naW5fbWV0aG9kIjoidXNlcm5hbWVfcGFzc3dvcmQifQ.34sD4gpoS4ExX48TpMV6ooz0KFyUzU4bNDsHWk3J-p4 HTTP/1.1" 304 Not Modified
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 1057, in user_api_key_auth
    raise Exception(
Exception: Only master key can be used to generate, delete, update info for new keys/users/teams. Route=/global/spend
INFO:     10.89.11.62:33724 - "GET /global/spend HTTP/1.1" 401 Unauthorized
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 1040, in user_api_key_auth
    raise HTTPException(
fastapi.exceptions.HTTPException: 403: key not allowed to access this user's info
```

**Comment by mprinceb** [comment]
- admin ui link on swagger docs does not respect SERVER_ROOT_PATH as well

**Comment by ghost** [comment]
@VfBfoerst unable to repro. 

Do you have a UI Username + Password also set as well? we have all 3 and still don't see the problem. 


Here's a sample demo app i spun up with just master key, and i don't see the problem:

UI: https://demo-litellm.onrender.com/ui

Admin Credentials:
- Username: admin
- Password: sk-1234

<img width="1708" alt="Screenshot 2024-04-23 at 1 26 00 PM" src="https://github.com/BerriAI/litellm/assets/17561003/b640c7ec-2696-4c41-932b-1856de04f898">


@VfBfoerst let me know if there's any changes i need to make, to repro your flow

**Comment by ghost** [comment]
@PrinceBaghel258025 please create a separate issue to track the server_root_path problem

**Comment by corticalstack** [comment]
@krrishdholakia I have the exact same issue as reported by @VfBfoerst . @VfBfoerst  do you still experience this?

I have UI_USERNAME and UI_PASSWORD configured in environment variables, and general_settings.master_key in config.yaml. I get repeated messages regards "key not allowed to access" and "Only master key can" on every UI page.

![image](https://github.com/BerriAI/litellm/assets/3995321/d000fe98-2c7e-49e3-af4d-72304b2ecb89)


```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 1062, in user_api_key_auth
    raise Exception(
Exception: Only master key can be used to generate, delete, update info for new keys/users/teams. Route=/global/spend
INFO:     192.168.1.132:55379 - "GET /global/spend HTTP/1.1" 401 Unauthorized
INFO:     192.168.1.132:55380 - "GET /models HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 1040, in user_api_key_auth
    raise HTTPException(
fastapi.exceptions.HTTPException
INFO:     192.168.1.132:55381 - "GET /user/info HTTP/1.1" 403 Forbidden
```

**Comment by ghost** [comment]
@corticalstack what does it say when you hover on your user id on the corner right - are you an admin or an app owner? 
<img width="260" alt="Screenshot 2024-04-28 at 2 10 08 PM" src="https://github.com/BerriAI/litellm/assets/17561003/f8bba3f3-e4ed-4fd3-a012-3f010df78dc3">


Happy to help debug over a call - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by corticalstack** [comment]
@krrishdholakia role: admin, id: admin. I checked in the proxy_server.py code, which checks for the user having the admin role, so....

**Comment by ghost** [comment]
Modified to return a more detailed error message - https://github.com/BerriAI/litellm/commit/7b617e666decde16b86473875c5cc570ca69bb07

You seem to be entering the non-admin condition block of the auth check

**Comment by ashutoshsaboo** [comment]
> * admin ui link on swagger docs does not respect SERVER_ROOT_PATH as well

Bumped into the same issue, created this here - https://github.com/BerriAI/litellm/issues/4691 . @krrishdholakia @PrinceBaghel258025

**Comment by VfBfoerst** [comment]
for me, it seems to be fixed. :) I can't reproduce it anymore.

**Comment by Justin-12138** [comment]
I got the same issue!
