### ISSUE TITLE
proxy-server: Error on first request

### ISSUE THREAD

**Issue by johnd0e** [BerriAI/litellm#324]
`"model": "gpt-3.5-turbo",`

```
Either an env variable `SLACK_BOT_TOKEN` or `token` argument in the constructor is required.
got error'NoneType' object has no attribute 'failure_handler'
calling model gpt-3.5-turbo
ERROR:waitress:Exception while serving /chat/completions
Traceback (most recent call last):
  File "D:\AI\litellm\proxy-server\venv\lib\site-packages\waitress\channel.py", line 428, in service
    task.service()
  File "D:\AI\litellm\proxy-server\venv\lib\site-packages\waitress\task.py", line 168, in service
    self.execute()
  File "D:\AI\litellm\proxy-server\venv\lib\site-packages\waitress\task.py", line 472, in execute
    self.write(chunk)
  File "D:\AI\litellm\proxy-server\venv\lib\site-packages\waitress\task.py", line 316, in write
    towrite += data + b"\r\n"
TypeError: unsupported operand type(s) for +: 'OpenAIObject' and 'bytes'
```

But subsequent requests are without problems.

**Comment by ishaan-jaff** [comment]
https://github.com/BerriAI/litellm/blob/main/proxy-server/main.py#L20-L25

**Comment by ishaan-jaff** [comment]
you can remove the callbacks from there and it should work

**Comment by johnd0e** [comment]
Thanks

**Comment by ishaan-jaff** [comment]
closing this, feel free to re-open if it's not working @johnd0e
