### ISSUE TITLE
[Bug]: an unknown error was encountered while running the model

### ISSUE THREAD

**Issue by arsaboo** [BerriAI/litellm#3316]
### What happened?

I was trying call `ollama_chat\command-r:35b` through `phidata`. Here's the complete code:
```python
import json
import os
from pathlib import Path
from phi.assistant.duckdb import DuckDbAssistant
from phi.llm.openai import OpenAIChat

llm_litellm=OpenAIChat(model="command-r", temperature=0.3, api_key="REDACTED",base_url="http://192.168.2.162:4001")

duckdb_assistant = DuckDbAssistant(
    semantic_model=json.dumps(
        {
            "tables": [
                {
                    "name": "movies",
                    "description": "Contains information about movies from IMDB.",
                    "path": "https://phidata-public.s3.amazonaws.com/demo_data/IMDB-Movie-Data.csv",
                }
            ]
        }
    ),
    llm=llm_litellm,
    markdown=True,
    show_tool_calls=True,
    base_dir=base_dir,
)

duckdb_assistant.print_response("What is the average rating of the movies?")
```
However, the code does not produce any output (the same code works fine with `ollama_chat\llama3`). I see the following in the logs:

### Relevant log output

```shell
INFO:     192.168.65.1:53824 - "POST /chat/completions HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 9998, in chunk_creator
    response_obj = self.handle_ollama_chat_stream(chunk)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 9666, in handle_ollama_chat_stream
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 9641, in handle_ollama_chat_stream
    raise Exception(f"Ollama Error - {json_chunk}")
Exception: Ollama Error - {'error': 'an unknown error was encountered while running the model '}
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/ollama_chat.py", line 371, in ollama_async_streaming
    async for transformed_chunk in streamwrapper:
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 10529, in __anext__
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 10427, in __anext__
    processed_chunk: Optional[ModelResponse] = self.chunk_creator(
                                               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 10282, in chunk_creator
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 8823, in exception_type
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 8798, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: Ollama Error - {'error': 'an unknown error was encountered while running the model '}
```

**Comment by ghost** [comment]
> litellm.exceptions.APIConnectionError: Ollama Error - {'error': 'an unknown error was encountered while running the model 

hi @arsaboo this doesn't look like a litellm error, instead it seems to come from ollama

> File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 9641, in handle_ollama_chat_stream
    raise Exception(f"Ollama Error - {json_chunk}")
Exception: Ollama Error - {'error': 'an unknown error was encountered while running the model '}

Since this is the error text coming from ollama, i'm not sure how we could be more descriptive here. let me know if there's anything we can do to help. 


Closing as no-op.
