### ISSUE TITLE
HuggingfaceException - Pipeline cannot infer suitable model classes from TheBloke/Llama-2-13B-chat-GGUF

### ISSUE THREAD

**Issue by CodeAKrome** [BerriAI/litellm#333]
What's the problem? (if there are multiple - list as bullet points)
Just found this on rpi4b. Going through possible models that will run there, potentially.
```python
from litellm import completion
import os
import sys

if len(sys.argv) > 1:
    model = "huggingface/" + sys.argv[1]
else:
    model = "huggingface/cerebras/btlm-3b-8k-base"

print(f"model:\t{model}\n")
messages = [{ "content": "Hello, how are you?","role": "user"}]
response = completion(model, messages=messages)
print(f"{type(response)}")
```

```
model:	huggingface/TheBloke/Llama-2-13B-chat-GGUF

Traceback (most recent call last):
  File "/home/kyle/srcLocal/llm/.venv/lib/python3.11/site-packages/litellm/main.py", line 559, in completion
    model_response = huggingface_restapi.completion(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyle/srcLocal/llm/.venv/lib/python3.11/site-packages/litellm/llms/huggingface_restapi.py", line 108, in completion
    raise HuggingfaceError(
litellm.llms.huggingface_restapi.HuggingfaceError: Pipeline cannot infer suitable model classes from TheBloke/Llama-2-13B-chat-GGUF

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kyle/srcLocal/llm/./lite-llm.py", line 13, in <module>
    response = completion(model, messages=messages)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyle/srcLocal/llm/.venv/lib/python3.11/site-packages/litellm/utils.py", line 584, in wrapper
    raise e
  File "/home/kyle/srcLocal/llm/.venv/lib/python3.11/site-packages/litellm/utils.py", line 544, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyle/srcLocal/llm/.venv/lib/python3.11/site-packages/litellm/timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/kyle/srcLocal/llm/.venv/lib/python3.11/site-packages/litellm/timeout.py", line 33, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyle/srcLocal/llm/.venv/lib/python3.11/site-packages/litellm/main.py", line 870, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/home/kyle/srcLocal/llm/.venv/lib/python3.11/site-packages/litellm/utils.py", line 1959, in exception_type
    raise e
  File "/home/kyle/srcLocal/llm/.venv/lib/python3.11/site-packages/litellm/utils.py", line 1829, in exception_type
    raise APIError(
litellm.exceptions.APIError: HuggingfaceException - Pipeline cannot infer suitable model classes from TheBloke/Llama-2-13B-chat-GGUF
```

**Comment by CodeAKrome** [comment]
Takes special call.

**Comment by ishaan-jaff** [comment]
@CodeAKrome what was the fix ? 

is there something better we can do for hugging face api calls ?

**Comment by ghost** [comment]
closing due to inactivity.
