### ISSUE TITLE
[Bug]: Login Error

### ISSUE THREAD

**Issue by lalineanegra** [BerriAI/litellm#3367]
### What happened?

when trying to use the UI feature, after setting the environment variables `UI_USERNAME` and `UI_PASWORD`, when entering the credentials an exception is raised (the browser shows: 'Internal Server Error'). It seems to be a problem with the jwt library. I tried removing and and reinstalling, even installing PyJWT. Nothing worked

### Relevant log output

```shell
INFO:     127.0.0.1:64354 - "POST /login HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 428, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 91, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 146, in simple_response
    await self.app(scope, receive, send)
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 62, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/starlette/routing.py", line 758, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/starlette/routing.py", line 778, in app
    await route.handle(scope, receive, send)
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/starlette/routing.py", line 299, in handle
    await self.app(scope, receive, send)
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/starlette/routing.py", line 79, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 299, in app
    raise e
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 294, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/imagemaker/work/latam/littlellm/.venv/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 8058, in login
    jwt_token = jwt.encode(
                ^^^^^^^^^^
AttributeError: module 'jwt' has no attribute 'encode'
```

**Comment by ishaan-jaff** [comment]
@lalineanegra is this on the litellm docker image ?

**Comment by lalineanegra** [comment]
> @lalineanegra is this on the litellm docker image ?

It happens locally too

**Comment by ishaan-jaff** [comment]
> It happens locally too

Can you confirm you see this on your docker image ? I'm unable to repro the issue you're seeing it works fine for us

**Comment by RexWzh** [comment]
I use the latest docker image, and get the same problem:

```yaml
version: "3.9"
services:
  litellm:
    build:
      context: .
      args:
        target: runtime
    # same problem for ghcr.io/berriai/litellm:main-latest
    image: ghcr.io/berriai/litellm-database:main-latest 
    ports:
      - "4000:4000" # Map the container port to the host, change the host port if necessary
    volumes:
      - ./litellm-config.yaml:/app/config.yaml # Mount the local configuration file
    # You can change the port or number of workers as per your requirements or pass any new supported CLI augument. Make sure the port passed here matches with the container port defined above in `ports` value
    command: [ "--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8", "--detailed_debug" ]
```

and the `litellm-config.toml`

```bash
model_list:
  - model_name: bce-embedding-base_v1
    litellm_params: 
      # no api_base set, sends request to hugging face free inference api https://api-inference.huggingface.co/models/
      model: huggingface/maidalun1020/bce-embedding-base_v1 # add huggingface prefix so it routes to hugging face
      api_key: hf_mytoken                          # api key for hugging face                     

general_settings: 
  master_key: sk-litellm
```

Logging in by `admin`, I get the error:

```bash
{"error":{"message":"Authentication Error, Not connected to DB!","type":"auth_error","param":"None","code":400}}
```

**Comment by RexWzh** [comment]
It works finally.

Add `postgres` to `docker-compose.yml`

```yml
version: "3.9"

services:
  db:
    image: postgres:latest
    container_name: litellm_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: litellm
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  litellm:
    build:
      context: .
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-latest
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./litellm-config.yaml:/app/config.yaml
    command: [ "--config", "/app/config.yaml", "--port", "4000", "--num_workers", "8", "--detailed_debug" ]
    env_file:
      - .env
```

And set the `.env` file:

```bash
LITELLM_MASTER_KEY="sk-1234" # this is your master key for using the proxy server
UI_USERNAME="..."   # username to sign in on UI
UI_PASSWORD="..."      # password to sign in on UI
DATABASE_URL=postgresql://user:passwd@db:5432/litellm
```

Note that **the environment variables are working only when you specify the .env file.**

Relate issue: https://github.com/BerriAI/litellm/issues/2532

**Comment by ghost** [comment]
@lalineanegra do you see this with the docker image? 

I suspect this is an environment-specific issue 

Try running it with docker: 

1. Setup YAML 
```yaml
model_list:
  - model_name: azure-gpt-3.5
    litellm_params:
      model: azure/<your-azure-model-deployment>
      api_base: os.environ/AZURE_API_BASE
      api_key: os.environ/AZURE_API_KEY
      api_version: "2023-07-01-preview"
```

2. Run Docker  
```bash
docker run \
    -v $(pwd)/litellm_config.yaml:/app/config.yaml \
    -e AZURE_API_KEY=d6*********** \
    -e AZURE_API_BASE=https://openai-***********/ \
    -p 4000:4000 \
    ghcr.io/berriai/litellm:main-latest \
    --config /app/config.yaml --detailed_debug
```

3. Test 

```
 curl --location 'http://0.0.0.0:4000/chat/completions' \
      --header 'Content-Type: application/json' \
      --data '{
      "model": "azure-gpt-3.5",
      "messages": [
          {
          "role": "user",
          "content": "what llm are you"
          }
      ]
  }'
```


---

Happy to help debug this https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

Attaching my linkedin if you want to setup a direct support channel - https://www.linkedin.com/in/krish-d/

**Comment by lalineanegra** [comment]
It seems to work ok running in Docker, so I guess is an issue with my Mac environment. Thanks!

**Comment by ishaan-jaff** [comment]
closing since it was an env issue. @lalineanegra we'd love to onboard you to the proxy over a call this week. If you can share your email I can send an invite. If it's easier he's our calendly: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

If you want to dm us, linkedin https://www.linkedin.com/in/krish-d/

**Comment by lalineanegra** [comment]
> closing since it was an env issue. @lalineanegra we'd love to onboard you to the proxy over a call this week. If you can share your email I can send an invite. If it's easier he's our calendly: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
> 
> If you want to dm us, linkedin https://www.linkedin.com/in/krish-d/

Scheduled a meeting, thanks!
