### ISSUE TITLE
[Bug]: TypeError in litellm/utils.py

### ISSUE THREAD

**Issue by paul-gauthier** [BerriAI/litellm#3381]
### What happened?

I am seeing uncaught TypeErrors coming out of `litellm.completion()` when using model `openrouter/anthropic/claude-3-opus`.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/openai.py", line 414, in completion
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/openai.py", line 381, in completion
    return convert_to_model_response_object(
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 7071, in convert_to_model_response_object
    raise Exception(f"Invalid response object {traceback.format_exc()}")
Exception: Invalid response object Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 6951, in convert_to_model_response_object
    for idx, choice in enumerate(response_object["choices"]):
TypeError: 'NoneType' object is not iterable
```

```
$ pip list | grep litellm
litellm                       1.35.17
```
```


### Twitter / LinkedIn details

_No response_

**Comment by ghost** [comment]
@paul-gauthier what do you see as the raw response when running the call with `litellm.set_verbose=True`?

**Comment by paul-gauthier** [comment]
Unfortunately the error is not deterministically reproducible. I am seeing it occasionally during large scale eval/benchmarking runs. My code normally runs without setting that verbose flag.

**Comment by ghost** [comment]
got it, we already have a check here, for response_object being none 
<img width="678" alt="Screenshot 2024-05-01 at 10 44 30 AM" src="https://github.com/BerriAI/litellm/assets/17561003/664be8af-6d33-4b58-8047-ecf3b7244440">

https://github.com/BerriAI/litellm/blob/a24f32fb5ad4a2f861765f73cae5f44e0dd0e912/litellm/utils.py#L7179

Can you try bumping to latest and let me know if it persists. 


I've also update the error message to return the received args, if this happens again - https://github.com/BerriAI/litellm/commit/e96ccb8edfaaa822eabdc628cfa045f17f472642

Should be live in the next release (by EOD)

**Comment by paul-gauthier** [comment]
I think the error is caused by `response_object["choices"]` being None, not `response_object`?

**Comment by ghost** [comment]
good point - i've added a check to make sure response_object["choices"] is not none and iterable - https://github.com/BerriAI/litellm/commit/608fef60a645e31bf82de2498286b3bcc530f4ab

I'd ideally like stricter checks on the values of response_object (which is a dictionary), open to suggestions here

**Comment by ghost** [comment]
live now in v`1.35.35`.

**Comment by paul-gauthier** [comment]
Well, now the assertion is firing and rising out of the `completions()` call. That's probably not desirable?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 7196, in convert_to_model_response_object
    assert response_object["choices"] is not None and isinstance(
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/openai.py", line 414, in completion
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/openai.py", line 381, in completion
    return convert_to_model_response_object(
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 7321, in convert_to_model_response_object
    raise Exception(
Exception: Invalid response object Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 7196, in convert_to_model_response_object
    assert response_object["choices"] is not None and isinstance(
AssertionError
```

**Comment by paul-gauthier** [comment]
Note the `received_args` info at the bottom of this error report. This is a request to `openrouter/anthropic/claude-3-opus` apparently tripping a content filtering policy.

> received_args={'response_object': {'id': None, 'choices': None, 'created': None, 'model': None, 'object': None, 'system_fingerprint': None, 'usage': None, 'error': {'message': '{"type":"error","error":{"type":"invalid_request_error","message":"Output blocked by content filtering policy"}}', 'code': 400}}, 'model_response_object': ModelResponse(id='chatcmpl-6cc4cb20-3f9d-49d1-91c4-6d47af74e45e', choices=[Choices(finish_reason='stop', index=0, message=Message(content='default', role='assistant'))], created=1715474457, model='None/anthropic/claude-3-opus', object='chat.completion', system_fingerprint=None, usage=Usage()), 'response_type': 'completion', 'stream': False, 'start_time': None, 'end_time': None, 'hidden_params': None}


```
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/Users/gauthier/Projects/dirname/.venv/lib/python3.11/site-packages/litellm/utils.py", line 7498, in convert_to_model_response_object
    assert response_object["choices"] is not None and isinstance(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gauthier/Projects/dirname/.venv/lib/python3.11/site-packages/litellm/llms/openai.py", line 427, in completion
    raise e
  File "/Users/gauthier/Projects/dirname/.venv/lib/python3.11/site-packages/litellm/llms/openai.py", line 394, in completion
    return convert_to_model_response_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/dirname/.venv/lib/python3.11/site-packages/litellm/utils.py", line 7623, in convert_to_model_response_object
    raise Exception(
Exception: Invalid response object Traceback (most recent call last):
  File "/Users/gauthier/Projects/dirname/.venv/lib/python3.11/site-packages/litellm/utils.py", line 7498, in convert_to_model_response_object
    assert response_object["choices"] is not None and isinstance(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError


received_args={'response_object': {'id': None, 'choices': None, 'created': None, 'model': None, 'object': None, 'system_fingerprint': None, 'usage': None, 'error': {'message': '{"type":"error","error":{"type":"invalid_request_error","message":"Output blocked by content filtering policy"}}', 'code': 400}}, 'model_response_object': ModelResponse(id='chatcmpl-b10c01e3-0644-4f2e-884a-bffdd4720440', choices=[Choices(finish_reason='stop', index=0, message=Message(content='default', role='assistant'))], created=1715474420, model='None/anthropic/claude-3-opus', object='chat.completion', system_fingerprint=None, usage=Usage()), 'response_type': 'completion', 'stream': False, 'start_time': None, 'end_time': None, 'hidden_params': None}

Retry in 0.5 seconds.

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/Users/gauthier/Projects/dirname/.venv/lib/python3.11/site-packages/litellm/utils.py", line 7498, in convert_to_model_response_object
    assert response_object["choices"] is not None and isinstance(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gauthier/Projects/dirname/.venv/lib/python3.11/site-packages/litellm/llms/openai.py", line 427, in completion
    raise e
  File "/Users/gauthier/Projects/dirname/.venv/lib/python3.11/site-packages/litellm/llms/openai.py", line 394, in completion
    return convert_to_model_response_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/dirname/.venv/lib/python3.11/site-packages/litellm/utils.py", line 7623, in convert_to_model_response_object
    raise Exception(
Exception: Invalid response object Traceback (most recent call last):
  File "/Users/gauthier/Projects/dirname/.venv/lib/python3.11/site-packages/litellm/utils.py", line 7498, in convert_to_model_response_object
    assert response_object["choices"] is not None and isinstance(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError


received_args={'response_object': {'id': None, 'choices': None, 'created': None, 'model': None, 'object': None, 'system_fingerprint': None, 'usage': None, 'error': {'message': '{"type":"error","error":{"type":"invalid_request_error","message":"Output blocked by content filtering policy"}}', 'code': 400}}, 'model_response_object': ModelResponse(id='chatcmpl-6cc4cb20-3f9d-49d1-91c4-6d47af74e45e', choices=[Choices(finish_reason='stop', index=0, message=Message(content='default', role='assistant'))], created=1715474457, model='None/anthropic/claude-3-opus', object='chat.completion', system_fingerprint=None, usage=Usage()), 'response_type': 'completion', 'stream': False, 'start_time': None, 'end_time': None, 'hidden_params': None}
```

**Comment by ghost** [comment]
Ok great - I'm really glad we finally caught what was causing this 

How would you want this raised to you @paul-gauthier 

i would think this would be raised as an exception (maybe 400?) - so we could do retries on it, but what would you want/

**Comment by ghost** [comment]
> Well, now the assertion is firing and rising out of the completions() call. That's probably not desirable?

I think, before it was failing at a similar spot, because it expected content to not be null, but that wasn't happening. 

What we can do is move the check before this inside the openai.py file, to check if content is None - then we can raise the error appropriately, since it will fail in the response processing b/c choices is None 

Thoughts? @paul-gauthier
