### ISSUE TITLE
[Bug]: Litellm not starting if connection to redis down

### ISSUE THREAD

**Issue by shuther** [BerriAI/litellm#3400]
### What happened?

If the connection to redis is down, litellm refuses to work.
Maybe litellm should raise a warning/error and keep working instead? The best would be to dump in a log a script with the redis instruction that failed so they can be loaded later on manually if needed.
might be connected to #3056 
We want to avoid the trace error in this situation as well as the restart of the docker/service

### Relevant log output

```shell
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 259, in connect
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 260, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 585, in _connect
    for res in socket.getaddrinfo(
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Temporary failure in name resolution

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 654, in startup
    await handler()
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 3192, in startup_event
    await initialize(**worker_config)
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 3036, in initialize
    ) = await proxy_config.load_config(router=llm_router, config_file_path=config)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2433, in load_config
    router = litellm.Router(**router_params, semaphore=semaphore)  # type:ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 204, in __init__
    redis_cache = RedisCache(**cache_config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/caching.py", line 184, in __init__
    self.redis_client.ping()
  File "/usr/local/lib/python3.11/site-packages/redis/commands/core.py", line 1216, in ping
    return self.execute_command("PING", **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/client.py", line 505, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 1073, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.11/site-packages/redis/connection.py", line 265, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error -3 connecting to redis:6379. Temporary failure in name resolution.

09:03:02 - LiteLLM:DEBUG: caching.py:22 - Pinging Async Redis Cache
ERROR:    Application startup failed. Exiting.
```

**Comment by shuther** [comment]
To add on the topic, litellm restarted (could be because the docker compose restart field was set to always, but redis did not). Restarting litellm in a loop in such a situation could be a problem, it would be better if litellm could degrade its functionality instead.

**Comment by ghost** [comment]
i don't think this is an error - if you connect the proxy to a db and cache and they don't work at startup, then it seems like we're correctly raising the error here. 

redis calls failing while the service is running won't cause it to stop

**Comment by ghost** [comment]
this was done to solve a user problem:
- user would connect proxy to redis
- their credentials were incorrectly set, so redis would fail
- but the proxy would run

**Comment by ghost** [comment]
leaving open for now - @shuther open to suggestions on a better approach here. Shared context on why we do this ^

**Comment by shuther** [comment]
The redis credentials were ok. In the docker compose we had for litellm (restart always) but the statement was missing for redis. So it worked until the VM rebooted or litellm decided to restart by itself.
My recommendation would be to log the error (i.e. fail to connect to redis service) and move on (maybe redis is just restarting and it is temporary, maybe it failed to start). I would recommend to print one message each time there is a connection issue (due to [timeout](https://stackoverflow.com/questions/14784385/how-to-set-redis-connection-timeout), not reachable...) but litellm should not restart by itself (risk of Denial-of-service) and still works in degraded mode as it is critical that the gateway is up.
