### ISSUE TITLE
[Bug]: Key errors baseten llama3 models 

### ISSUE THREAD

**Issue by joelr45** [BerriAI/litellm#3404]
### What happened?

A bug happened! Testing inferencing Llama 3 8B - 70B models

Internal Server Error

Traceback (most recent call last):
  File "/app/model_wrapper.py", line 437, in inner
    return func(*args, **kwargs)
  File "/app/model/model.py", line 89, in predict
    messages = request.pop("messages")
KeyError: 'messages'

**Comment by ghost** [comment]
> Traceback (most recent call last):
File "/app/model_wrapper.py", line 437, in inner
return func(*args, **kwargs)
File "/app/model/model.py", line 89, in predict
messages = request.pop("messages")
KeyError: 'messages'


this stacktrace doesn't have litellm in it @joelr45

**Comment by ghost** [comment]
please re-open or bump me if you see litellm in this trace
