### ISSUE TITLE
[Bug]: Gemini 1.5 Pro streaming response chunks end prematurely with error

### ISSUE THREAD

**Issue by pchalasani** [BerriAI/litellm#3468]
### What happened?

```
from litellm import completion
import os, traceback

def completion_call():
    try:
        print("test completion + streaming")
        messages=[{"role": "user","content": "what is the capital of congo?"}]
        response = completion(
            model="gemini/gemini-1.5-pro-latest", 
            messages=messages, 
            stream=True,
            max_tokens=10, 
        )
        print(f"response: {response}")
        for chunk in response:
            print(chunk)
    except:
        print(f"error occurred: {traceback.format_exc()}")
        pass

completion_call()

```
Notice that `max_tokens=10`, which apparently is too small to generate the answer, which stops after generating "the" (this token-counting is a separate issue I believe being tracked #2876 ). But regardless of what this number is, the streaming response should not cause an error.

### Relevant log output

```shell
In [26]: completion_call()
test acompletion + streaming
response: <litellm.utils.CustomStreamWrapper object at 0x168728090>
ModelResponse(id='chatcmpl-7d3bc027-37af-4e09-a041-7399d29399fd', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='The', role='assistant', function_call=None, tool_calls=None), logprobs=None)], created=1714951341, model='gemini-1.5-pro-latest', object='chat.completion.chunk', system_fingerprint=None)

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.


Provider List: https://docs.litellm.ai/docs/providers


Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.


Provider List: https://docs.litellm.ai/docs/providers

error occurred: Traceback (most recent call last):
  File "/Users/pchalasani/Git/langroid/.venv/lib/python3.11/site-packages/litellm/utils.py", line 10190, in chunk_creator
    if hasattr(chunk.parts[0], "finish_reason"):
               ~~~~~~~~~~~^^^
  File "/Users/pchalasani/Git/langroid/.venv/lib/python3.11/site-packages/proto/marshal/collections/repeated.py", line 125, in __getitem__
    return self._marshal.to_python(self._pb_type, self.pb[key])
                                                  ~~~~~~~^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pchalasani/Git/langroid/.venv/lib/python3.11/site-packages/litellm/utils.py", line 10195, in chunk_creator
    if chunk.parts[0].finish_reason.name == "SAFETY":
       ~~~~~~~~~~~^^^
  File "/Users/pchalasani/Git/langroid/.venv/lib/python3.11/site-packages/proto/marshal/collections/repeated.py", line 125, in __getitem__
    return self._marshal.to_python(self._pb_type, self.pb[key])
                                                  ~~~~~~~^^^^^
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/pchalasani/Git/langroid/.venv/lib/python3.11/site-packages/litellm/utils.py", line 10691, in __next__
    response: Optional[ModelResponse] = self.chunk_creator(chunk=chunk)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/pchalasani/Git/langroid/.venv/lib/python3.11/site-packages/litellm/utils.py", line 10622, in chunk_creator
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/pchalasani/Git/langroid/.venv/lib/python3.11/site-packages/litellm/utils.py", line 9120, in exception_type
    raise e
  File "/Users/pchalasani/Git/langroid/.venv/lib/python3.11/site-packages/litellm/utils.py", line 9095, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<ipython-input-23-e1ade0f6246c>", line 11, in completion_call
    for chunk in response:
  File "/Users/pchalasani/Git/langroid/.venv/lib/python3.11/site-packages/litellm/utils.py", line 10728, in __next__
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/pchalasani/Git/langroid/.venv/lib/python3.11/site-packages/litellm/utils.py", line 9120, in exception_type
    raise e
  File "/Users/pchalasani/Git/langroid/.venv/lib/python3.11/site-packages/litellm/utils.py", line 9088, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: list index out of range
```

**Comment by ghost** [comment]
> error occurred: Traceback (most recent call last):
  File "/Users/pchalasani/Git/langroid/.venv/lib/python3.11/site-packages/litellm/utils.py", line 10190, in chunk_creator
    if hasattr(chunk.parts[0], "finish_reason"):
               ~~~~~~~~~~~^^^
  File "/Users/pchalasani/Git/langroid/.venv/lib/python3.11/site-packages/proto/marshal/collections/repeated.py", line 125, in __getitem__
    return self._marshal.to_python(self._pb_type, self.pb[key])
                                                  ~~~~~~~^^^^^
IndexError: list index out of range


@pchalasani this error isn't being raised by litellm. but google's sdk. What would you want us to do here?

**Comment by ghost** [comment]
Running this locally, i think i see it being triggered with this received chunk - 

> GenerateContentResponse(
    done=True,
    iterator=None,
    result=glm.GenerateContentResponse({'candidates': [{'finish_reason': 2, 'index': 0, 'safety_ratings': [{'category': 9, 'probability': 1, 'blocked': False}, {'category': 8, 'probability': 1, 'blocked': False}, {'category': 7, 'probability': 1, 'blocked': False}, {'category': 10, 'probability': 1, 'blocked': False}], 'token_count': 0, 'grounding_attributions': []}]}),
); custom_llm_provider: gemini


Working on the fix

**Comment by ghost** [comment]
Chunk that fails: 

> GenerateContentResponse(
    done=True,
    iterator=None,
    result=glm.GenerateContentResponse({'candidates': [{'finish_reason': 2, 'index': 0, 'safety_ratings': [{'category': 9, 'probability': 1, 'blocked': False}, {'category': 8, 'probability': 1, 'blocked': False}, {'category': 7, 'probability': 1, 'blocked': False}, {'category': 10, 'probability': 1, 'blocked': False}], 'token_count': 0, 'grounding_attributions': []}]}),
)

Chunk that works: 

> GenerateContentResponse(
    done=True,
    iterator=None,
    result=glm.GenerateContentResponse({'candidates': [{'content': {'parts': [{'text': 'The'}], 'role': 'model'}, 'finish_reason': 1, 'index': 0, 'safety_ratings': [], 'token_count': 0, 'grounding_attributions': []}]}),
)

**Comment by ghost** [comment]
Fixed - https://github.com/BerriAI/litellm/commit/4b5cf26c1beaafcbf67e85eaec124315280edbda

Will be live in next release (by EOD) @pchalasani
