### ISSUE TITLE
Encountered this error on the first message uising chat gpt 3.5

### ISSUE THREAD

**Issue by kotasudhakar** [BerriAI/litellm#3605]
INFO:     172.17.0.1:56602 - "GET /site.webmanifest HTTP/1.1" 200 OK
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/app/.venv/lib/python3.12/site-packages/uvicorn/protocols/websockets/websockets_impl.py", line 240, in run_asgi
    result = await self.app(self.scope, self.asgi_receive, self.asgi_send)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/.venv/lib/python3.12/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/app/.venv/lib/python3.12/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/errors.py", line 151, in __call__
    await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/cors.py", line 77, in __call__
    await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.12/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 373, in handle
    await self.app(scope, receive, send)
  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 96, in app
    await wrap_app_handling_exceptions(app, session)(scope, receive, send)
  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/app/.venv/lib/python3.12/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/app/.venv/lib/python3.12/site-packages/starlette/routing.py", line 94, in app
    await func(session)
  File "/app/.venv/lib/python3.12/site-packages/fastapi/routing.py", line 348, in app
    await dependant.call(**values)
  File "/app/opendevin/server/listen.py", line 49, in websocket_endpoint
    await session_manager.loop_recv(sid, agent_manager.dispatch)
  File "/app/opendevin/server/session/manager.py", line 40, in loop_recv
    await self._sessions[sid].loop_recv(dispatch)
  File "/app/opendevin/server/session/session.py", line 37, in loop_recv
    await dispatch(self.sid, action, data)
  File "/app/opendevin/server/agent/manager.py", line 35, in dispatch
    await self.sid_to_agent[sid].dispatch(action, data)
  File "/app/opendevin/server/agent/agent.py", line 92, in dispatch
    await self.event_stream.add_event(action_obj, EventSource.USER)
  File "/app/opendevin/events/stream.py", line 49, in add_event
    await fn(event)
  File "/app/opendevin/controller/agent_controller.py", line 178, in on_event
    await self.add_history(event, NullObservation(''), add_to_stream=False)
  File "/app/opendevin/controller/agent_controller.py", line 117, in add_history
    raise ValueError('Added history while state was None')
ValueError: Added history while state was None
INFO:     connection closed
INFO:     ('172.17.0.1', 50896) - "WebSocket /ws?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzaWQiOiIyNDMxMWFjYy1mMWM0LTQ2MWEtOWJiNC03NjNlZjFjNWU1MWEifQ.6SfEEZsbSz8AHZZVW85K3rua3JVnKlS1g_t-sfZJnks" [accepted]
INFO:     connection open
Starting loop_recv for sid: 24311acc-f1c4-461a-9bb4-763ef1c5e51a
INFO:     172.17.0.1:50900 - "GET /api/messages/total HTTP/1.1" 200 OK

**Comment by ghost** [comment]
i don't see litellm in this stacktrace @kotasudhakar 

closing as this seems opendevin related (not litellm) https://github.com/OpenDevin/OpenDevin

**Comment by ghost** [comment]
> await self.add_history(event, NullObservation(''), add_to_stream=False)
File "/app/opendevin/controller/agent_controller.py", line 117, in add_history
raise ValueError('Added history while state was None')
ValueError: Added history while state was None
INFO: connection closed

this might be what's causing it btw
