### ISSUE TITLE
[Bug]: Promptlayer integration not working 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#362]
### What happened?

https://github.com/nsbradford/VimGPT is facing an issue re sending data to promptlayer 

### Relevant log output

```shell
}
LiteLLM: Prompt Layer Logging - Response obj type : <class 'dict'> Response from llm :{'choices': [<Choices at 0x1058794f0> JSON: {
  "finish_reason": "stop",
  "index": 0,
  "message": {
    "content": " I'm not OpenAI, my name is Claude.",
    "role": "assistant",
    "logprobs": null
  }
}], 'created': 1694634317.3145, 'model': 'claude-instant-1.2', 'usage': {'prompt_tokens': 16, 'completion_tokens': 11, 'total_tokens': 27}}
LiteLLM: Prompt Layer Error - Traceback (most recent call last):
  File "/Users/ishaanjaffer/Github/litellm/litellm/integrations/prompt_layer.py", line 30, in log_event
    request_response = requests.post(
  File "/Users/ishaanjaffer/Library/Python/3.9/lib/python/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/Users/ishaanjaffer/Library/Python/3.9/lib/python/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/ishaanjaffer/Library/Python/3.9/lib/python/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Users/ishaanjaffer/Library/Python/3.9/lib/python/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Users/ishaanjaffer/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 371, in prepare
    self.prepare_body(data, files, json)
  File "/Users/ishaanjaffer/Library/Python/3.9/lib/python/site-packages/requests/models.py", line 511, in prepare_body
    body = complexjson.dumps(json, allow_nan=False)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/__init__.py", line 234, in dumps
    return cls(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type Logging is not JSON serializable
```

**Comment by ishaan-jaff** [comment]
Fixed 

<img width="329" alt="Screenshot 2023-09-13 at 12 58 22 PM" src="https://github.com/BerriAI/litellm/assets/29436595/75630f12-8068-4d1c-a107-3e7584b0679b">


the problem was because `kwargs` included `litellm_logging_obj` which was not serializable

**Comment by ishaan-jaff** [comment]
fix here: https://github.com/BerriAI/litellm/commit/1913d36e053cc1d6cd8d26b70d6a175d88a1f42c

**Comment by ishaan-jaff** [comment]
<img width="324" alt="Screenshot 2023-09-13 at 1 24 06 PM" src="https://github.com/BerriAI/litellm/assets/29436595/cb1be132-e012-43b9-9f31-efe158ed3d04">


works with gpt-4, claude-2

**Comment by ishaan-jaff** [comment]
cc @nsbradford thanks for raising waiting for a new litellm version to deploy

**Comment by ishaan-jaff** [comment]
also added testing for promptlayer logging in the commit - which should ensure this integration is well maintained

**Comment by ishaan-jaff** [comment]
litellm 0.1.618 has the fix, will leave this issue open if @nsbradford runs into any issues with the integration

**Comment by ishaan-jaff** [comment]
fixed confirmed
