### ISSUE TITLE
devin run error

### ISSUE THREAD

**Issue by rgtourism** [BerriAI/litellm#3650]
15:41:48 - opendevin:ERROR: agent_controller.py:147 - Error in loop
2024-05-15 21:11:48 Traceback (most recent call last):
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/litellm/llms/openai.py", line 427, in completion
2024-05-15 21:11:48     raise e
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/litellm/llms/openai.py", line 386, in completion
2024-05-15 21:11:48     response = openai_client.chat.completions.create(**data, timeout=timeout)  # type: ignore
2024-05-15 21:11:48                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/openai/_utils/_utils.py", line 277, in wrapper
2024-05-15 21:11:48     return func(*args, **kwargs)
2024-05-15 21:11:48            ^^^^^^^^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 590, in create
2024-05-15 21:11:48     return self._post(
2024-05-15 21:11:48            ^^^^^^^^^^^
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1240, in post
2024-05-15 21:11:48     return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
2024-05-15 21:11:48                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 921, in request
2024-05-15 21:11:48     return self._request(
2024-05-15 21:11:48            ^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1020, in _request
2024-05-15 21:11:48     raise self._make_status_error_from_response(err.response) from None
2024-05-15 21:11:48 openai.NotFoundError: Error code: 404 - {'error': {'message': 'The model `gpt-4-0125-preview` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-05-15 21:11:48 
2024-05-15 21:11:48 During handling of the above exception, another exception occurred:
2024-05-15 21:11:48 
2024-05-15 21:11:48 Traceback (most recent call last):
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 1053, in completion
2024-05-15 21:11:48     raise e
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 1026, in completion
2024-05-15 21:11:48     response = openai_chat_completions.completion(
2024-05-15 21:11:48                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/litellm/llms/openai.py", line 433, in completion
2024-05-15 21:11:48     raise OpenAIError(status_code=e.status_code, message=str(e))
2024-05-15 21:11:48 litellm.llms.openai.OpenAIError: Error code: 404 - {'error': {'message': 'The model `gpt-4-0125-preview` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}
2024-05-15 21:11:48 
2024-05-15 21:11:48 During handling of the above exception, another exception occurred:
2024-05-15 21:11:48 
2024-05-15 21:11:48 Traceback (most recent call last):
2024-05-15 21:11:48   File "/app/opendevin/controller/agent_controller.py", line 142, in _run
2024-05-15 21:11:48     finished = await self.step(i)
2024-05-15 21:11:48                ^^^^^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/app/opendevin/controller/agent_controller.py", line 256, in step
2024-05-15 21:11:48     action = self.agent.step(self.state)
2024-05-15 21:11:48              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/app/agenthub/codeact_agent/codeact_agent.py", line 223, in step
2024-05-15 21:11:48     response = self.llm.completion(
2024-05-15 21:11:48                ^^^^^^^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 330, in wrapped_f
2024-05-15 21:11:48     return self(f, *args, **kw)
2024-05-15 21:11:48            ^^^^^^^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 467, in __call__
2024-05-15 21:11:48     do = self.iter(retry_state=retry_state)
2024-05-15 21:11:48          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 368, in iter
2024-05-15 21:11:48     result = action(retry_state)
2024-05-15 21:11:48              ^^^^^^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 390, in <lambda>
2024-05-15 21:11:48     self._add_action_func(lambda rs: rs.outcome.result())
2024-05-15 21:11:48                                      ^^^^^^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 449, in result
2024-05-15 21:11:48     return self.__get_result()
2024-05-15 21:11:48            ^^^^^^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
2024-05-15 21:11:48     raise self._exception
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/tenacity/__init__.py", line 470, in __call__
2024-05-15 21:11:48     result = fn(*args, **kwargs)
2024-05-15 21:11:48              ^^^^^^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/app/opendevin/llm/llm.py", line 188, in wrapper
2024-05-15 21:11:48     resp = completion_unwrapped(*args, **kwargs)
2024-05-15 21:11:48            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 3222, in wrapper
2024-05-15 21:11:48     raise e
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 3116, in wrapper
2024-05-15 21:11:48     result = original_function(*args, **kwargs)
2024-05-15 21:11:48              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 2226, in completion
2024-05-15 21:11:48     raise exception_type(
2024-05-15 21:11:48           ^^^^^^^^^^^^^^^
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 9233, in exception_type
2024-05-15 21:11:48     raise e
2024-05-15 21:11:48   File "/app/.venv/lib/python3.12/site-packages/litellm/utils.py", line 7978, in exception_type
2024-05-15 21:11:48     raise NotFoundError(
2024-05-15 21:11:48 litellm.exceptions.NotFoundError: OpenAIException - Error code: 404 - {'error': {'message': 'The model `gpt-4-0125-preview` does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}} 
2024-05-15 21:11:48 Model: gpt-4-0125-preview
2024-05-15 21:11:48 API Base: https://api.openai.com
2024-05-15 21:11:48 Messages: [{'role': 'system', 'content': 'A chat between a curious user and an artificial intelligence assista
2024-05-15 21:11:48 15:41:48 - opendevin:INFO: agent_controller.py:190 - Setting agent(CodeActAgent) state from AgentState.RUNNING to AgentState.ERROR

**Comment by ghost** [comment]
> 2024-05-15 21:11:48 litellm.llms.openai.OpenAIError: Error code: 404 - {'error': {'message': 'The model gpt-4-0125-preview does not exist or you do not have access to it.', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}

I believe this indicates you might not have access to this model, since i can confirm it exists on openai's side - https://platform.openai.com/docs/models/gpt-4-turbo-and-gpt-4
