### ISSUE TITLE
[Bug]: Replicate -> 'ModelResponse' object has no attribute 'ended'

### ISSUE THREAD

**Issue by edwinjosegeorge** [BerriAI/litellm#3707]
## What happened?
A bug happened!

I was tying to call replicate model as per https://litellm.vercel.app/docs/providers/replicate#example-call and it resulted in a error

## How to replicate?
```python
import os
os.environ["REPLICATE_API_KEY"] = "<secret-key>"

from litellm import completion

if __name__ == '__main__':

    # replicate llama-3 call
    response = completion(
        model="replicate/meta/meta-llama-3-8b-instruct",
        messages = [{ "content": "Hello, how are you?", "role": "user"}]
    )
    print(response)
```

## StackTrace
```
ModelResponse(id='chatcmpl-e1e614b3-481d-4797-98aa-32d5f2871bbd', choices=[Choices(finish_reason='stop', index=0, message=Message(content="I'm doing well, thank you for asking! I'm a helpful assistant, here to assist you with any questions or tasks you may have. How can I help you today? Do you have a specific topic in mind that you'd like to discuss or a question you'd like answered?", role='assistant'))], created=1715910547, model='replicate/meta/meta-llama-3-8b-instruct', object='chat.completion', system_fingerprint=None, usage=Usage(prompt_tokens=47, completion_tokens=58, total_tokens=105))
Exception in thread Thread-1 (success_handler):
Traceback (most recent call last):
  File "...\virtualenvs\litellm-Bwe27PKk-py3.11\Lib\site-packages\pydantic\main.py", line 803, in __getattr__
    return pydantic_extra[item]
           ~~~~~~~~~~~~~~^^^^^^
KeyError: 'ended'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "...\litellm\litellm\utils.py", line 1485, in _success_handler_helper_fn
    litellm.completion_cost(
  File "...\litellm\litellm\utils.py", line 4555, in completion_cost
    raise e
  File "...\litellm\litellm\utils.py", line 4536, in completion_cost
    return get_replicate_completion_pricing(completion_response, total_time)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\litellm\litellm\utils.py", line 3849, in get_replicate_completion_pricing
    end_time = completion_response["ended"]
               ~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "...\litellm\litellm\utils.py", line 727, in __getitem__
    return getattr(self, key)
           ^^^^^^^^^^^^^^^^^^
  File "...\virtualenvs\litellm-Bwe27PKk-py3.11\Lib\site-packages\pydantic\main.py", line 805, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
AttributeError: 'ModelResponse' object has no attribute 'ended'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...\anaconda3\...\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "...\anaconda3\...\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "...\litellm\litellm\utils.py", line 1522, in success_handler
    start_time, end_time, result = self._success_handler_helper_fn(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\litellm\litellm\utils.py", line 1516, in _success_handler_helper_fn
    raise Exception(f"[Non-Blocking] LiteLLM.Success_Call Error: {str(e)}")
Exception: [Non-Blocking] LiteLLM.Success_Call Error: 'ModelResponse' object has no attribute 'ended'
```

**Comment by edwinjosegeorge** [comment]
To file this issue, I tried setting 'verbose=True' to get a detailed report, and the issue is not appearing?!

## Steps to replicate
```python
import os
os.environ["REPLICATE_API_KEY"] = "<secret-key>"

from litellm import completion
import litellm
litellm.set_verbose=True

if __name__ == '__main__':

    # replicate llama-3 call
    response = completion(
        model="replicate/meta/meta-llama-3-8b-instruct",
        messages = [{ "content": "Hello, how are you?", "role": "user"}]
    )
    print(response)
```

## Output
```


Request to litellm:
litellm.completion(model='replicate/meta/meta-llama-3-8b-instruct', messages=[{'content': 'Hello, how are you?', 'role': 'user'}])


self.optional_params: {}
SYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache')['no-cache']: False
Final returned optional params: {}
self.optional_params: {}


POST Request Sent from LiteLLM:
curl -X POST \
https://api.replicate.com/v1/models/meta/meta-llama-3-8b-instruct \
-H 'Authorization: Token r8_SnHqE8KFPTIbEEEEE********************' -H 'Content-Type: application/json' \
-d '{'input': {'prompt': '<|begin_of_text|><|start_header_id|>user<|end_header_id|>\n\nHello, how are you?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\n'}}'


https://api.replicate.com/v1/predictions/z1w4z5kpy9rgg0cfgh2b4aq3rc
replicate: polling endpoint: https://api.replicate.com/v1/predictions/z1w4z5kpy9rgg0cfgh2b4aq3rc
Non-streamed output:I'm doing well, thank you for asking! I'm a helpful assistant, here to assist you with any questions or tasks you may have. How can I help you today?
RAW RESPONSE:
I'm doing well, thank you for asking! I'm a helpful assistant, here to assist you with any questions or tasks you may have. How can I help you today?


raw model_response: I'm doing well, thank you for asking! I'm a helpful assistant, here to assist you with any questions or tasks you may have. How can I help you today?
Logging Details LiteLLM-Success Call: None
ModelResponse(id='chatcmpl-7769f91f-614d-44bb-aab2-de80468b3821', choices=[Choices(finish_reason='stop', index=0, message=Message(content="I'm doing well, thank you for asking! I'm a helpful assistant, here to assist you with any questions or tasks you may have. How can I help you today?", role='assistant'))], created=1715911029, model='replicate/meta/meta-llama-3-8b-instruct', object='chat.completion', system_fingerprint=None, usage=Usage(prompt_tokens=47, completion_tokens=36, total_tokens=83))
success callbacks: []
```

Now the program completed successfully!

**Comment by hieuminh65** [comment]
I just did this and had the same error

**Comment by edwinjosegeorge** [comment]
I am working on this and I feel that there is some race condition involved here! When I try to debug by having breakpoints, the issue seems resolved. But when i run without any breakpoints, it still breaks. This might explain why the issue is not appearing when setting `verbose=True`.

**Comment by edwinjosegeorge** [comment]
The bug is raised at line 3856, when a key `ended` is tried to call.

https://github.com/BerriAI/litellm/blob/4b3551abfc761324131fc24846801707c8b62bac/litellm/utils.py#L3847-L3859

The issue is only raised when the `total_time==0`, i.e then the code runs too fast? Do we need a case for that?

@ishaan-jaff  @krrishdholakia

**Comment by ghost** [comment]
> ModelResponse(id='chatcmpl-e1e614b3-481d-4797-98aa-32d5f2871bbd', choices=[Choices(finish_reason='stop', index=0, message=Message(content="I'm doing well, thank you for asking! I'm a helpful assistant, here to assist you with any questions or tasks you may have. How can I help you today? Do you have a specific topic in mind that you'd like to discuss or a question you'd like answered?", role='assistant'))], created=1715910547, model='replicate/meta/meta-llama-3-8b-instruct', object='chat.completion', system_fingerprint=None, usage=Usage(prompt_tokens=47, completion_tokens=58, total_tokens=105))


So it looks like your code runs 

I think the background thread for success callback is throwing this issue

**Comment by edwinjosegeorge** [comment]
> > ModelResponse(id='chatcmpl-e1e614b3-481d-4797-98aa-32d5f2871bbd', choices=[Choices(finish_reason='stop', index=0, message=Message(content="I'm doing well, thank you for asking! I'm a helpful assistant, here to assist you with any questions or tasks you may have. How can I help you today? Do you have a specific topic in mind that you'd like to discuss or a question you'd like answered?", role='assistant'))], created=1715910547, model='replicate/meta/meta-llama-3-8b-instruct', object='chat.completion', system_fingerprint=None, usage=Usage(prompt_tokens=47, completion_tokens=58, total_tokens=105))
> 
> So it looks like your code runs
> 
> I think the background thread for success callback is throwing this issue

Yes!... a fix is proposed. This should resolve the issue

**Comment by ghost** [comment]
fixed - https://github.com/BerriAI/litellm/commit/1cecdc46903897b8f5c5b9056d484277c134bdfe

i think your pr had some good ideas @edwinjosegeorge, can definitely look at using the logging object's time calc instead of the replicate specific implementation
