### ISSUE TITLE
[Bug]: add api to zhipu/chatglm with openai OpenAI-Compatible Endpoints

### ISSUE THREAD

**Issue by flyfox666** [BerriAI/litellm#3736]
### What happened?

External: OpenAIException - Error Code: 400 - {'error': {'code': '1214', 'message': 'messages[4]:content and tool_calls fields can't both be empty'}}.

### Relevant log output

```shell
2024-05-20 21:18:06 ERROR:apps.litellm.main:400 Client Error: Bad Request for url: http://localhost:14365/v1/chat/completions
2024-05-20 21:18:06 Traceback (most recent call last):
2024-05-20 21:18:06   File "/app/backend/apps/litellm/main.py", line 354, in proxy
2024-05-20 21:18:06     r.raise_for_status()
2024-05-20 21:18:06   File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
2024-05-20 21:18:06     raise HTTPError(http_error_msg, response=self)
2024-05-20 21:18:06 requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:14365/v1/chat/completions
2024-05-20 21:18:06 INFO:     172.17.0.1:60394 - "POST /litellm/api/v1/chat/completions HTTP/1.1" 500 Internal Server Error
2024-05-20 21:18:06 ERROR:apps.litellm.main:500 Server Error: Internal Server Error for url: http://localhost:14365/v1/chat/completions
2024-05-20 21:18:06 Traceback (most recent call last):
2024-05-20 21:18:06   File "/app/backend/apps/litellm/main.py", line 354, in proxy
2024-05-20 21:18:06     r.raise_for_status()
2024-05-20 21:18:06   File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
2024-05-20 21:18:06     raise HTTPError(http_error_msg, response=self)
2024-05-20 21:18:06 requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http://localhost:14365/v1/chat/completions
2024-05-20 21:18:06 INFO:     172.17.0.1:60394 - "POST /litellm/api/v1/chat/completions HTTP/1.1" 500 Internal Server Error
```

### Twitter / LinkedIn details

@flyfox666

**Comment by NeverOccurs** [comment]
Same here, looks like using Moonshot via litellm proxy server also raises error. But I think it might be something with the proxy server since I get decent response directly calling chatglm API. Can't find where the problem is.

Directly calling with
`import litellm
import os

response = litellm.completion(
    model="openai/glm-3-turbo",                           
    api_key=os.environ["API_KEY"], 
    api_base="https://open.bigmodel.cn/api/paas/v4/", 
    messages=[
                {
                    "role": "user",
                    "content": "Hey, how's it going?",
                }
    ],
    extra_headers={
        "Content-Type": "application/json",
        }

)
print(response)`

seemes fine

**Comment by ghost** [comment]
hey @flyfox666 @NeverOccurs i can't see the litellm specific error here. 

i see this 
> File "/app/backend/apps/litellm/main.py", line 354, in proxy
2024-05-20 21:18:06     r.raise_for_status()

but the corresponding line doesn't exist in our codebase - https://github.com/BerriAI/litellm/blob/0cd25c250d75ebdb26955338ba2d2a178257e93e/litellm/main.py#L354


> ERROR:apps.litellm.main:400 Client Error: Bad Request for url: http://localhost:14365/v1/chat/completions

line 400 on main.py is also not doing http calls. Is this a fork? 
https://github.com/BerriAI/litellm/blob/0cd25c250d75ebdb26955338ba2d2a178257e93e/litellm/main.py#L400
