### ISSUE TITLE
[Bug]: clarifai provider in litellm[proxy] not work

### ISSUE THREAD

**Issue by ytpk** [BerriAI/litellm#3796]
### What happened?

the clarifai provider does not work in proxy mode
below I have attached a log with streaming enabled and without streaming

### Relevant log output

```shell
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi/encoders.py", line 324, in jsonable_encoder
    data = dict(obj)
TypeError: 'coroutine' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi/encoders.py", line 329, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 296, in app
    content = await serialize_response(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 180, in serialize_response
    return jsonable_encoder(response_content)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/encoders.py", line 332, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [TypeError("'coroutine' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]
INFO:     127.0.0.1:50596 - "POST /v1/chat/completions HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litellm/proxy/proxy_server.py", line 3392, in async_data_generator
    async for chunk in response:
TypeError: 'async for' requires an object with __aiter__ method, got coroutine
```

**Comment by ishaan-jaff** [comment]
@ytpk 

- Can i see your config.yaml
- Curl sent to the proxy 
- what litellm version are you on ?

**Comment by ytpk** [comment]
@ishaan-jaff
I think it will be easier for me to write how to reproduce my problem, at the end of the text I have attached my current version of Litellm.

I performed all the actions on a clean ubuntu 22
first, I added my token to env

export CALRIFAI_API_KEY=Token?

 then launched the proxy
litellm --model clarifai/openai.chat-completion.GPT-4

next i make simple curl
curl http://127.0.0.1:4000/v1/chat/completions \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer $OPENAI_API_KEY" \
  -d '{
     "model": "gpt-4",
     "messages": [{"role": "user", "content": "test!"}],
     "temperature": 0.7
   }'
   
Internal Server Error
log:
```
INFO:     127.0.0.1:39548 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi/encoders.py", line 324, in jsonable_encoder
    data = dict(obj)
TypeError: 'coroutine' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/fastapi/encoders.py", line 329, in jsonable_encoder
    data = vars(obj)
TypeError: vars() argument must have __dict__ attribute

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/httptools_impl.py", line 435, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 296, in app
    content = await serialize_response(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 180, in serialize_response
    return jsonable_encoder(response_content)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/encoders.py", line 332, in jsonable_encoder
    raise ValueError(errors) from e
ValueError: [TypeError("'coroutine' object is not iterable"), TypeError('vars() argument must have __dict__ attribute')]

```

litellm --version

LiteLLM: Current Version = 1.38.0

**Comment by ytpk** [comment]
this problem only occurs when using litellm as a proxy server, when using litellm in python code (from the example in google colab), there are no problems and I successfully receive an answer
edit:
and no, I also executed the clarify request directly via curl on the same vps and it also passed without problems

**Comment by ishaan-jaff** [comment]
@mogith-pn can you please take a look at this issue - I believe you added this provider

**Comment by ishaan-jaff** [comment]
@ytpk can you set the api key as `CLARIFAI_API_KEY` and try again ?

**Comment by ytpk** [comment]
same error log, nothing has changed
 I assume that the proxy is trying to cause streaming from the response or something like that, this provider does not have such a function.  since if I run a query through litellm in python, there is no problem

**Comment by tuanlv14** [comment]
I confirmed that I have same issue. The team, pls fix it. Thanks.

**Comment by mogith-pn** [comment]
> I confirmed that I have same issue. The team, pls fix it. Thanks.

I'm looking into this, thanks for notifying !

**Comment by edwinjosegeorge** [comment]
After debugging, I believe the issue is at https://github.com/BerriAI/litellm/blob/deb87f71e330dcaf56574a477d9457d589754cd3/litellm/llms/clarifai.py#L247-L262

Where the sync function `completion` returns a coroutine, that is not yet evaluated. The fix could be running the async part of the code in another thread and return the result. 

This `coroutine` is passed back into the FastAPI, where it tries to resolve it by calling `dict(response)`, leading to the error

@krrishdholakia  @mogith-pn  @ishaan-jaff

**Comment by ishaan-jaff** [comment]
Fix PR here: https://github.com/BerriAI/litellm/pull/4158 @tuanlv14 @ytpk

**Comment by ishaan-jaff** [comment]
@ytpk  any chance we can hop on a call ? I'd love to learn how how we can improve litellm for you.

My linkedin if you prefer DM: https://www.linkedin.com/in/reffajnaahsi/
Sharing a link to my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by ytpk** [comment]
> any chance we can hop on a call ?

zero chance, i'm fucking social anxiety psycho
