### ISSUE TITLE
[Bug]: Cost Tracking for (imagegeneration@006) from Vertex doesn't work 

### ISSUE THREAD

**Issue by lalineanegra** [BerriAI/litellm#3801]
### What happened?

Using Litellm Proxy, when trying to query the imagegeneration@006 model, an `LiteLLM.Success_Call Error: Model=1024-x-1024/imagegeneration@006 not found in completion cost model map`appears, despite a 200OK code

Client code:

```
client = openai.OpenAI(
    api_key = token, 
    base_url = api_base # litellm-proxy-base url
)

response = client.images.generate(
    model="imagegeneration@006",
      prompt="a white siamese cat",
)

print(response)
```

### Relevant log output

```shell
15:39:03 - LiteLLM Router:INFO: router.py:752 - litellm.aimage_generation(model=vertex_ai/imagegeneration@006) 200 OK
INFO:     127.0.0.1:49736 - "POST /images/generations HTTP/1.1" 200 OK
Task exception was never retrieved
future: <Task finished name='Task-82' coro=<Logging.async_success_handler() done, defined at /Users/imagemaker/work/latam/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/utils.py:2066> exception=Exception('[Non-Blocking] LiteLLM.Success_Call Error: Model=1024-x-1024/imagegeneration@006 not found in completion cost model map')>
Traceback (most recent call last):
  File "/Users/imagemaker/work/latam/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/utils.py", line 1413, in _success_handler_helper_fn
    litellm.completion_cost(
  File "/Users/imagemaker/work/latam/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/utils.py", line 4453, in completion_cost
    raise e
  File "/Users/imagemaker/work/latam/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/utils.py", line 4416, in completion_cost
    raise Exception(
Exception: Model=1024-x-1024/imagegeneration@006 not found in completion cost model map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/imagemaker/work/latam/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/utils.py", line 2073, in async_success_handler
    start_time, end_time, result = self._success_handler_helper_fn(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/imagemaker/work/latam/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/utils.py", line 1460, in _success_handler_helper_fn
    raise Exception(f"[Non-Blocking] LiteLLM.Success_Call Error: {str(e)}")
Exception: [Non-Blocking] LiteLLM.Success_Call Error: Model=1024-x-1024/imagegeneration@006 not found in completion cost model map
    litellm.completion_cost(
  File "/Users/imagemaker/work/latam/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/utils.py", line 4453, in completion_cost
    raise e
  File "/Users/imagemaker/work/latam/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/utils.py", line 4416, in completion_cost
    raise Exception(
Exception: Model=1024-x-1024/imagegeneration@006 not found in completion cost model map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python@3.11/3.11.8/Frameworks/Python.framework/Versions/3.11/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/imagemaker/work/latam/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/utils.py", line 1466, in success_handler
    start_time, end_time, result = self._success_handler_helper_fn(
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/imagemaker/work/latam/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/utils.py", line 1460, in _success_handler_helper_fn
    raise Exception(f"[Non-Blocking] LiteLLM.Success_Call Error: {str(e)}")
Exception: [Non-Blocking] LiteLLM.Success_Call Error: Model=1024-x-1024/imagegeneration@006 not found in completion cost model map
```

**Comment by ishaan-jaff** [comment]
@lalineanegra are you getting the response client side? it looks like the cost tracking is raising an error since it's not in our model cost map

**Comment by lalineanegra** [comment]
Correct, is client side

**Comment by ishaan-jaff** [comment]
okay so you're responses are returning - you're only seeing an error on the server saying cost tracking is not working @lalineanegra ?

**Comment by NFuentesC** [comment]
hello!, i am working with @lalineanegra and the bug occurs in the logs of the litellm proxy and although we see that it generates the image on the server,  because we see the long base64, it does not return to the client.

we are using the version 1.38.1.

![Captura de pantalla 2024-05-23 a la(s) 6 44 40 p  m](https://github.com/BerriAI/litellm/assets/72422205/788d05ff-5e24-45ad-bfb6-44c0deb0c355)

as you can see there is not response

but in the server side we have this result...

<img width="1255" alt="Captura de pantalla 2024-05-23 a la(s) 6 45 35 p  m" src="https://github.com/BerriAI/litellm/assets/72422205/5ec2730a-ac9a-4c17-bb13-0fa1bfc4825b">

Thanks.

**Comment by ishaan-jaff** [comment]
@NFuentesC - in your collab -can you please print response and see what gets printed 

and please check if you see any exceptions

**Comment by NFuentesC** [comment]
there it is! for some reason it does not appear in the cell, it may be because of the length of the text. but unlike dalle, the vertex model comes with the parameter b64_json and dall-e uses 'url'.

I see that even defining the parameter response_format with url, it arrives as b64_json.

![Captura de pantalla 2024-05-23 a la(s) 7 10 57 p  m](https://github.com/BerriAI/litellm/assets/72422205/ea80413e-d3a2-4d6a-b57a-49440e0e9750)

![Captura de pantalla 2024-05-23 a la(s) 7 12 00 p  m](https://github.com/BerriAI/litellm/assets/72422205/488e12aa-3471-432a-b853-2f21b93970c5)

**Comment by ishaan-jaff** [comment]
cost tracking fixed here too: https://github.com/BerriAI/litellm/pull/3809
