### ISSUE TITLE
[Bug]: Bedrock Provisioned Throughput not working after 1.37.16

### ISSUE THREAD

**Issue by i3zxu** [BerriAI/litellm#3805]
### What happened?

After 1.37.16, request to Bedrock Provisioned Throughput models fail with 400 error.

"Request Sent from LiteLLM" used to be a `Boto3` call like the following, but it was changed to a `curl` call after 1.37.16.

```
Request Sent from LiteLLM:

            response = client.invoke_model(
                body={"inputText": "\n\nUser: What's AWS?\n\nBot: ", "textGenerationConfig": {}},
                modelId=<arn>,
                accept=accept,
                contentType=contentType
            )
```

### Relevant log output

```shell
Request to litellm:
litellm.completion(model='bedrock/amazon.titan-text-lite-v1', model_id='<arn>', messages=[{'role': 'user', 'content': "What's AWS?"}])


self.optional_params: {}
SYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache')['no-cache']: False
Final returned optional params: {'model_id': '<arn>'}
self.optional_params: {'model_id': '<arn>'}


POST Request Sent from LiteLLM:
curl -X POST \
https://bedrock-runtime.us-west-2.amazonaws.com/model/amazon.titan-text-lite-v1/invoke \
-H 'Content-Type: application/json' -H 'X-Amz-Date: 20240523T222327Z' -H 'X-Amz-Security-Token: <token>' -H 'Authorization: <auth>' -H 'Content-Length: 184' \
-d '{"inputText": "\n\nUser: What's AWS?\n\nBot: ", "textGenerationConfig": {"model_id": "<arn>"}}'



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call: []
self.failure_callback: []
Traceback (most recent call last):
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/llms/bedrock_httpx.py", line 864, in completion
    response.raise_for_status()
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://bedrock-runtime.us-west-2.amazonaws.com/model/amazon.titan-text-lite-v1/invoke'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/main.py", line 2025, in completion
    response = bedrock_chat_completion.completion(
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/llms/bedrock_httpx.py", line 867, in completion
    raise BedrockError(status_code=error_code, message=response.text)
litellm.llms.bedrock.BedrockError: {"message":"Malformed input request: extraneous key [model_id] is not permitted, please reformat your input and try again."}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/utils.py", line 3412, in wrapper
    raise e
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/utils.py", line 3305, in wrapper
    result = original_function(*args, **kwargs)
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/main.py", line 2370, in completion
    raise exception_type(
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/utils.py", line 9882, in exception_type
    raise e
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/utils.py", line 8854, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: BedrockException - {"message":"Malformed input request: extraneous key [model_id] is not permitted, please reformat your input and try again."}
```

**Comment by ishaan-jaff** [comment]
We recently moved bedrock to be httpx async - this might be related cc @krrishdholakia

**Comment by ghost** [comment]
it looks like we missed the `model_id` param mapping in the httpx call (being sent nested in request body) - https://docs.litellm.ai/docs/providers/bedrock#provisioned-throughput-models

Thanks for the catch @i3zxu will have this fixed asap

**Comment by ghost** [comment]
we should also add a test for this in our ci/cd. Seems like we were missing it

**Comment by ghost** [comment]
Fixed in v1.38.4 @i3zxu, also added testing to prevent future regressions!

**Comment by i3zxu** [comment]
Thanks for the fast response! Unfortunately it's still not working, error message did change.

The ARN is in a format like:
- `arn:aws:bedrock:us-west-2:<12-digit-number>:provisioned-model/<12-char-alphanumeric>`

I'm not sure whether the extra slash when used as POST request path parameter changed the semantics.

```
Request to litellm:
litellm.completion(model='bedrock/amazon.titan-text-lite-v1', model_id='<arn>', messages=[{'role': 'user', 'content': 'What is AWS?'}])


self.optional_params: {}
SYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache')['no-cache']: False
Final returned optional params: {'model_id': '<arn>'}
self.optional_params: {'model_id': '<arn>'}


POST Request Sent from LiteLLM:
curl -X POST \
https://bedrock-runtime.us-west-2.amazonaws.com/model/<arn>/invoke \
-H 'Content-Type: application/json' -H 'X-Amz-Date: 20240525T064307Z' -H 'X-Amz-Security-Token: <token>' -H 'Authorization: <auth>' -H 'Content-Length: 76' \
-d '{"inputText": "\n\nUser: What is AWS?\n\nBot: ", "textGenerationConfig": {}}'


RAW RESPONSE:
{"Output":{"__type":"com.amazon.coral.service#UnknownOperationException"},"Version":"1.0"}


raw model_response: {"Output":{"__type":"com.amazon.coral.service#UnknownOperationException"},"Version":"1.0"}

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call: []
self.failure_callback: []
Traceback (most recent call last):
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/llms/bedrock_httpx.py", line 444, in process_response
    outputText = completion_response.get("results")[0].get("outputText")
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/main.py", line 2088, in completion
    response = bedrock_chat_completion.completion(
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/llms/bedrock_httpx.py", line 872, in completion
    return self.process_response(
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/llms/bedrock_httpx.py", line 446, in process_response
    raise BedrockError(
litellm.llms.bedrock.BedrockError: Error processing={"Output":{"__type":"com.amazon.coral.service#UnknownOperationException"},"Version":"1.0"}, Received error='NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/test-pt/test-pt.py", line 7, in <module>
    resp = litellm.completion(model=model, model_id=model_id, messages=[{"role": "user", "content": "What is AWS?"}])
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/utils.py", line 3421, in wrapper
    raise e
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/utils.py", line 3314, in wrapper
    result = original_function(*args, **kwargs)
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/main.py", line 2433, in completion
    raise exception_type(
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/utils.py", line 9972, in exception_type
    raise e
  File "/home/ubuntu/test-pt/venv/lib/python3.10/site-packages/litellm/utils.py", line 9029, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: BedrockException - Error processing={"Output":{"__type":"com.amazon.coral.service#UnknownOperationException"},"Version":"1.0"}, Received error='NoneType' object is not subscriptable
```

**Comment by ghost** [comment]
hmm i can see the modelId param being used in the url 

> https://bedrock-runtime.us-west-2.amazonaws.com/model/<arn>/invoke \


can you share what a curl to bedrock ptu needs to look like? @i3zxu my understanding was that the key change was in the url

**Comment by ghost** [comment]
i see a way to test it - https://docs.aws.amazon.com/bedrock/latest/userguide/prov-thru-code-samples.html

Let me try that

**Comment by i3zxu** [comment]
> hmm i can see the modelId param being used in the url
> 
> > https://bedrock-runtime.us-west-2.amazonaws.com/model//invoke \
> 
> can you share what a curl to bedrock ptu needs to look like? @i3zxu my understanding was that the key change was in the url

I used litellm and/or boto3, never tried the REST interface before.

**Comment by ghost** [comment]
Ok, i was able to repro the issue - it was caused b/c of not url encoding the model id. 

Fixed + added testing @i3zxu should be live soon in v`1.38.5`.

**Comment by ghost** [comment]
Can we do a ~10min call to learn how you're using litellm? @i3zxu 

Attaching my calendly, for convenience - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by shanbin** [comment]
> Can we do a ~10min call to learn how you're using litellm? @i3zxu 
> 
> 
> 
> Attaching my calendly, for convenience - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

I mainly use litellm because it has better AWS IAM support than langchain and way easier to use than boto3.

**Comment by i3zxu** [comment]
> Ok, i was able to repro the issue - it was caused b/c of not url encoding the model id.
> 
> Fixed + added testing @i3zxu should be live soon in v`1.38.5`.

Verified, thanks!

**Comment by ghost** [comment]
Bump on request to chat? @i3zxu 

would love to learn how you're using litellm! 

Attaching my calendly, for convenience - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by i3zxu** [comment]
> Bump on request to chat? @i3zxu
> 
> would love to learn how you're using litellm!
> 
> Attaching my calendly, for convenience - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

Sure, I'll try to find a time later this week, am traveling in a not-so-convenient time zone.
