### ISSUE TITLE
[Bug]: Cohere error when streaming

### ISSUE THREAD

**Issue by toniengelhardt** [BerriAI/litellm#385]
### What happened?

When I use a Cohere model in the `completion` method it works, but an error is logged (see log output).

```python
content = ''

response = completion(
    model,
    messages,
    api_key=api_key,
    stream=True,
    mock_response=None,
    **model_settings,  # pylint: disable=not-a-mapping
)

for idx, chunk in enumerate(response):
    content += chunk['choices'][0]['delta'].get('content') or ''
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/toni/Developer/Promptmetheus/promptmetheus-core/env/lib/python3.11/site-packages/litellm/utils.py", line 2455, in handle_cohere_chunk
    return data_json["text"]
           ~~~~~~~~~^^^^^^^^
KeyError: 'text'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/toni/Developer/Promptmetheus/promptmetheus-core/env/lib/python3.11/site-packages/litellm/utils.py", line 2555, in __next__
    completion_obj["content"] = self.handle_cohere_chunk(chunk)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/toni/Developer/Promptmetheus/promptmetheus-core/env/lib/python3.11/site-packages/litellm/utils.py", line 2457, in handle_cohere_chunk
    raise ValueError(f"Unable to parse response. Original response: {chunk}")
ValueError: Unable to parse response. Original response: {"is_finished":true,"finish_reason":"COMPLETE","response":{"id":"b5d1f66b-e238-49a1-a73b-55cad23d2fc2","generations":[{"id":"b0ec59bc-8172-41eb-a157-ad818a7c2c88","text":" Seperti apakah Anda dari sekitaran kota atau daerah?","finish_reason":"COMPLETE"}],"prompt":"You are a helpful assistant. Translate the following sentence to Indonesian:\n\nWhere are you from?"}}
```

**Comment by ghost** [comment]
I believe this is caused by the end of the generator. 

We'd put a traceback.print_exc() here (which is printing the error) - https://github.com/BerriAI/litellm/blob/c829798e04c47049bcbe93b365668692b2f40e98/litellm/utils.py#L2577

to catch issues as we were fixing some formatting errors with the stream. I'll remove it and update this thread.

**Comment by ghost** [comment]
removed traceback.print_exc() in `v0.1.688` 

@toniengelhardt let me know if this works, I'll reopen the issue if it doesn't.
