### ISSUE TITLE
[Bug]: KeyError when using ollama function call. (inconsistent ollama api response) 

### ISSUE THREAD

**Issue by cdoneshot** [BerriAI/litellm#3912]
# What happened?

When making function calls using litellm+ollama+autogen, KeyError are occasionally encountered because LLM does not return data in the required format

# Relevant log output

All of the following examples use litellm+ollama(model:llama3:8b)+autogen

#### request send from litellm
```
curl -X POST \
http://10.10.20.96:11434/api/chat \
-d '{'model': 'llama3', 'messages': [{'content': 'For currency exchange tasks,\n        only use the functions you have been provided with.\n        Output \'TERMINATE\' when an answer has been provided.\n        Do not include the function name or result in the JSON.\n        Example of the return JSON is:\n        {\n            "parameter_1_name": 100.00,\n            "parameter_2_name": "ABC",\n            "parameter_3_name": "DEF",\n        }.\n        Another example of the return JSON is:\n        {\n            "parameter_1_name": "GHI",\n
 "parameter_2_name": "ABC",\n            "parameter_3_name": "DEF",\n            "parameter_4_name": 123.00,\n        }.  Produce JSON OUTPUT ONLY! Adhere to this format {"name": "function_name", "arguments":{"argument_name": "argument_value"}} The following functions are available to you:\n{\'type\': \'function\', \'function\': {\'description\': \'Currency exchange calculator.\', \'name\': \'currency_calculator\', \'parameters\': {\'type\': \'object\', \'properties\': {\'base_amount\': {\'type\': \'number\', \'description\': \'Amount of currency in base_currency\'}, \'base_currency\': {\'enum\': [\'USD\', \'EUR\'], \'type\': \'string\', \'default\': \'USD\', \'description\': \'Base currency\'}, \'quote_currency\': {\'enum\': [\'USD\', \'EUR\'], \'type\': \'string\', \'default\': \'EUR\', \'description\': \'Quote currency\'}}, \'required\': [\'base_amount\']}}}\n', 'role': 'system'}, {'content': 'How much is 123.45 EUR in USD?', 'role': 'user'}, {'tool_calls': [{'id': 'call_4ac911d5-1034-415a-ad73-929c5355fc57', 'function': {'arguments': '{"base_amount": 123.45, "base_currency": "EUR", "quote_currency": "USD"}', 'name': 'currency_calculator'}, 'type': 'function'}], 'content': None, 'role': 'assistant'}, {'tool_call_id': 'call_4ac911d5-1034-415a-ad73-929c5355fc57', 'role': 'assistant', 'content': '135.80 USD'}], 'options': {}, 'stream': False, 'format': 'json'}'
```
#### response received by litellm
```
 {'name': 'currency_calculator', 'arguments': {'base_amount': '123.45', 'quote_currency': 'EUR'}}
```
#### request send from litellm
```
curl -X POST \
http://10.10.20.96:11434/api/chat \
-d '{'model': 'llama3', 'messages': [{'content': 'For currency exchange tasks,\n        only use the functions you have been provided with.\n        Output \'TERMINATE\' when an answer has been provided.\n        Do not include the function name or result in the JSON.\n        Example of the return JSON is:\n        {\n            "parameter_1_name": 100.00,\n            "parameter_2_name": "ABC",\n            "parameter_3_name": "DEF",\n        }.\n        Another example of the return JSON is:\n        {\n            "parameter_1_name": "GHI",\n
 "parameter_2_name": "ABC",\n            "parameter_3_name": "DEF",\n            "parameter_4_name": 123.00,\n        }.  Produce JSON OUTPUT ONLY! Adhere to this format {"name": "function_name", "arguments":{"argument_name": "argument_value"}} The following functions are available to you:\n{\'type\': \'function\', \'function\': {\'description\': \'Currency exchange calculator.\', \'name\': \'currency_calculator\', \'parameters\': {\'type\': \'object\', \'properties\': {\'base_amount\': {\'type\': \'number\', \'description\': \'Amount of currency in base_currency\'}, \'base_currency\': {\'enum\': [\'USD\', \'EUR\'], \'type\': \'string\', \'default\': \'USD\', \'description\': \'Base currency\'}, \'quote_currency\': {\'enum\': [\'USD\', \'EUR\'], \'type\': \'string\', \'default\': \'EUR\', \'description\': \'Quote currency\'}}, \'required\': [\'base_amount\']}}}\n', 'role': 'system'}, {'content': 'How much is 123.45 EUR in USD?', 'role': 'user'}, {'tool_calls': [{'id': 'call_fb5775df-6c2c-4cca-bd6d-638424b87db5', 'function': {'arguments': '{"base_amount": 123.45, "quote_currency": "USD", "base_currency": "EUR"}', 'name': 'currency_calculator'}, 'type': 'function'}], 'content': None, 'role': 'assistant'}, {'tool_call_id': 'call_fb5775df-6c2c-4cca-bd6d-638424b87db5', 'role': 'assistant', 'content': '135.80 USD'}], 'options': {}, 'stream': False, 'format': 'json'}'
```
#### response received by litellm
```
 {'base_amount': 123.45, 'quote_currency': 'USD'}
```

#### exception
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.10/site-packages/litellm/llms/ollama_chat.py", line 481, in ollama_acompletion
    "function": {"name": function_call["name"], "arguments": json.dumps(function_call["arguments"])},
KeyError: 'name'
```
```

**Comment by edwinjosegeorge** [comment]
Here is how i replicated it, following the example from https://microsoft.github.io/autogen/docs/topics/non-openai-models/local-litellm-ollama/

#### Start chat with ollama on local
```bash
ollama run dolphincoder
```

#### Start LiteLLM server with this model with debug enabled
```bash
litellm --model ollama_chat/dolphincoder --debug
```

#### Run the following file
```bash
import autogen
from typing import Literal
from typing_extensions import Annotated

local_llm_config={
    "config_list": [
        {
            "model": "NotRequired", # Loaded with LiteLLM command
            "api_key": "NotRequired", # Not needed
            "base_url": "http://localhost:4000"  # Your LiteLLM URL
        }
    ],
    "cache_seed": None # Turns off caching, useful for testing different models
}

# Create the agent and include examples of the function calling JSON in the prompt
# to help guide the model
chatbot = autogen.AssistantAgent(
    name="chatbot",
    system_message="""For currency exchange tasks,
        only use the functions you have been provided with.
        Output 'TERMINATE' when an answer has been provided.
        Do not include the function name or result in the JSON.
        Example of the return JSON is:
        {
            "parameter_1_name": 100.00,
            "parameter_2_name": "ABC",
            "parameter_3_name": "DEF",
        }.
        Another example of the return JSON is:
        {
            "parameter_1_name": "GHI",
            "parameter_2_name": "ABC",
            "parameter_3_name": "DEF",
            "parameter_4_name": 123.00,
        }. """,

    llm_config=local_llm_config,
)

user_proxy = autogen.UserProxyAgent(
    name="user_proxy",
    is_termination_msg=lambda x: x.get("content", "") and "TERMINATE" in x.get("content", ""),
    human_input_mode="NEVER",
    max_consecutive_auto_reply=1,
    code_execution_config={"use_docker": False}
)


CurrencySymbol = Literal["USD", "EUR"]

# Define our function that we expect to call
def exchange_rate(base_currency: CurrencySymbol, quote_currency: CurrencySymbol) -> float:
    if base_currency == quote_currency:
        return 1.0
    elif base_currency == "USD" and quote_currency == "EUR":
        return 1 / 1.1
    elif base_currency == "EUR" and quote_currency == "USD":
        return 1.1
    else:
        raise ValueError(f"Unknown currencies {base_currency}, {quote_currency}")

# Register the function with the agent
@user_proxy.register_for_execution()
@chatbot.register_for_llm(description="Currency exchange calculator.")
def currency_calculator(
    base_amount: Annotated[float, "Amount of currency in base_currency"],
    base_currency: Annotated[CurrencySymbol, "Base currency"] = "USD",
    quote_currency: Annotated[CurrencySymbol, "Quote currency"] = "EUR",
) -> str:
    quote_amount = exchange_rate(base_currency, quote_currency) * base_amount
    return f"{format(quote_amount, '.2f')} {quote_currency}"

# start the conversation


if __name__ == '__main__':
    res = user_proxy.initiate_chat(
        chatbot,
        message="How much is 123.45 EUR in USD?",
        summary_method="reflection_with_llm",
    )
    print(res)
```

#### Program response
```bash

How much is 123.45 EUR in USD?

--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "...\file.py", line 78, in <module>
    res = user_proxy.initiate_chat(
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 1007, in initiate_chat
    self.send(msg2send, recipient, silent=silent)
  File "...venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 645, in send
    recipient.receive(message, self, request_reply, silent)
  File "...venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 808, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 1949, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 1315, in generate_oai_reply
    extracted_response = self._generate_oai_reply_from_client(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...venv\Lib\site-packages\autogen\agentchat\conversable_agent.py", line 1334, in _generate_oai_reply_from_client
    response = llm_client.create(
               ^^^^^^^^^^^^^^^^^^
  File "...venv\Lib\site-packages\autogen\oai\client.py", line 638, in create
    response = client.create(params)
               ^^^^^^^^^^^^^^^^^^^^^
  File "...venv\Lib\site-packages\autogen\oai\client.py", line 285, in create
    response = completions.create(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...venv\Lib\site-packages\openai\_utils\_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "...venv\Lib\site-packages\openai\resources\chat\completions.py", line 579, in create
    return self._post(
           ^^^^^^^^^^^
  File "...venv\Lib\site-packages\openai\_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...venv\Lib\site-packages\openai\_base_client.py", line 921, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "...venv\Lib\site-packages\openai\_base_client.py", line 1005, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "...venv\Lib\site-packages\openai\_base_client.py", line 1053, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "...venv\Lib\site-packages\openai\_base_client.py", line 1005, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "...venv\Lib\site-packages\openai\_base_client.py", line 1053, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "...venv\Lib\site-packages\openai\_base_client.py", line 1020, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Error code: 500 - {'error': {'message': "'name'", 'type': None, 'param': None, 'code': 500}}

Process finished with exit code 1
```

#### LiteLLM server response
```bash
litellm.json_logs: False
INFO:     Started server process [4796]
INFO:     Waiting for application startup.

#------------------------------------------------------------#
#                                                            #
#       'This feature doesn't meet my needs because...'       #
#        https://github.com/BerriAI/litellm/issues/new        #
#                                                            #
#------------------------------------------------------------#

 Thank you for using LiteLLM! - Krrish & Ishaan



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new


INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:4000 (Press CTRL+C to quit)
14:44:26 - LiteLLM:INFO: utils.py:1307 - 

POST Request Sent from LiteLLM:
curl -X POST \
http://localhost:11434/api/chat \
-d '{'model': 'dolphincoder', 'messages': [{'content': 'For currency exchange tasks,\n        only use the functions you have been provided with.\n        Output \'TERMINATE\' when
 an answer has been provided.\n        Do not include the function name or result in the JSON.\n        Example of the return JSON is:\n        {\n            "parameter_1_name": 1
00.00,\n            "parameter_2_name": "ABC",\n            "parameter_3_name": "DEF",\n        }.\n        Another example of the return JSON is:\n        {\n            "paramete
r_1_name": "GHI",\n            "parameter_2_name": "ABC",\n            "parameter_3_name": "DEF",\n            "parameter_4_name": 123.00,\n        }.  Produce JSON OUTPUT ONLY! Ad
here to this format {"name": "function_name", "arguments":{"argument_name": "argument_value"}} The following functions are available to you:\n{\'type\': \'function\', \'function\':
 {\'description\': \'Currency exchange calculator.\', \'name\': \'currency_calculator\', \'parameters\': {\'type\': \'object\', \'properties\': {\'base_amount\': {\'type\': \'numbe
r\', \'description\': \'Amount of currency in base_currency\'}, \'base_currency\': {\'enum\': [\'USD\', \'EUR\'], \'type\': \'string\', \'default\': \'USD\', \'description\': \'Bas
e currency\'}, \'quote_currency\': {\'enum\': [\'USD\', \'EUR\'], \'type\': \'string\', \'default\': \'EUR\', \'description\': \'Quote currency\'}}, \'required\': [\'base_amount\']}}}\n', 'role': 'system'}, {'content': 'How much is 123.45 EUR in USD?', 'role': 'user'}], 'options': {}, 'stream': False, 'format': 'json'}'


Traceback (most recent call last):
  File "...venv\litellm\litellm\llms\ollama_chat.py", line 479, in ollama_acompletion
    "function": {"name": function_call["name"], "arguments": json.dumps(function_call["arguments"])},
                         ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'name'
Traceback (most recent call last):
  File "...venv\litellm\litellm\main.py", line 344, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "...venv\litellm\litellm\llms\ollama_chat.py", line 506, in ollama_acompletion
    raise e
  File "...venv\litellm\litellm\llms\ollama_chat.py", line 479, in ollama_acompletion
    "function": {"name": function_call["name"], "arguments": json.dumps(function_call["arguments"])},
                         ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "...venv\litellm\litellm\proxy\proxy_server.py", line 4082, in chat_completion
    responses = await llm_responses
                ^^^^^^^^^^^^^^^^^^^
  File "...venv\litellm\litellm\utils.py", line 3907, in wrapper_async
    raise e
  File "...venv\litellm\litellm\utils.py", line 3735, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...venv\litellm\litellm\main.py", line 365, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "...venv\litellm\litellm\utils.py", line 9964, in exception_type
    raise e
  File "...venv\litellm\litellm\utils.py", line 9939, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: 'name'
```
