### ISSUE TITLE
[Bug]: LiteLLM proxy get error when "stream_options" is in JSON

### ISSUE THREAD

**Issue by anbatista-com** [BerriAI/litellm#3980]
### What happened?

I'm testing Dify.ai with LiteLLM and I could see response fails because when "stream_options" is part of JSON request, LiteLLM get a pydantic error:

`
{"messages": [{"role": "system", "content": "you are a helpful assistant.\n"}, {"role": "user", "content": "bom dia"}], "model": "gpt-3.5-turbo-0125", "stream": true, "stream_options": {"include_usage": true}, "user": "ebf6fa53-7b28-4f0b-abb8-770e22c6a655"}
`

`Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 3622, in async_data_generator
    chunk = chunk.model_dump_json(exclude_none=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 398, in model_dump_json
    return self.__pydantic_serializer__.to_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^`

### Relevant log output

```shell
Raw OpenAI Chunk
ChatCompletionChunk(id='chatcmpl-9Vxs9b8Py8J4wJXgVPq2P6nfGTnOo', choices=[], created=1717405345, model='gpt-3.5-turbo-0125', object='chat.completion.chunk', system_fingerprint=None, usage=CompletionUsage(completion_tokens=13, prompt_tokens=20, total_tokens=33))
 
completion obj content:  
completion obj content:  
model_response finish reason 3: stop; response_obj={'text': '', 'is_finished': False, 'finish_reason': None, 'logprobs': None, 'original_chunk': ChatCompletionChunk(id='chatcmpl-9Vxs9b8Py8J4wJXgVPq2P6nfGTnOo', choices=[], created=1717405345, model='gpt-3.5-turbo-0125', object='chat.completion.chunk', system_fingerprint=None, usage=CompletionUsage(completion_tokens=13, prompt_tokens=20, total_tokens=33)), 'usage': CompletionUsage(completion_tokens=13, prompt_tokens=20, total_tokens=33)} 
model_response finish reason 3: stop; response_obj={'text': '', 'is_finished': False, 'finish_reason': None, 'logprobs': None, 'original_chunk': ChatCompletionChunk(id='chatcmpl-9Vxs9b8Py8J4wJXgVPq2P6nfGTnOo', choices=[], created=1717405345, model='gpt-3.5-turbo-0125', object='chat.completion.chunk', system_fingerprint=None, usage=CompletionUsage(completion_tokens=13, prompt_tokens=20, total_tokens=33)), 'usage': CompletionUsage(completion_tokens=13, prompt_tokens=20, total_tokens=33)} 
PROCESSED ASYNC CHUNK POST CHUNK CREATOR: ModelResponse(id='chatcmpl-9Vxs9b8Py8J4wJXgVPq2P6nfGTnOo', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=None, role=None, function_call=None, tool_calls=None), logprobs=None)], created=1717405345, model='gpt-3.5-turbo-0125', object='chat.completion.chunk', system_fingerprint=None, usage=CompletionUsage(completion_tokens=13, prompt_tokens=20, total_tokens=33)) 
PROCESSED ASYNC CHUNK POST CHUNK CREATOR: ModelResponse(id='chatcmpl-9Vxs9b8Py8J4wJXgVPq2P6nfGTnOo', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=None, role=None, function_call=None, tool_calls=None), logprobs=None)], created=1717405345, model='gpt-3.5-turbo-0125', object='chat.completion.chunk', system_fingerprint=None, usage=CompletionUsage(completion_tokens=13, prompt_tokens=20, total_tokens=33)) 
Logging Details LiteLLM-Success Call: None 
Logging Details LiteLLM-Success Call: None 
final returned processed chunk: ModelResponse(id='chatcmpl-9Vxs9b8Py8J4wJXgVPq2P6nfGTnOo', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=None, role=None, function_call=None, tool_calls=None), logprobs=None)], created=1717405345, model='gpt-3.5-turbo-0125', object='chat.completion.chunk', system_fingerprint=None, usage=CompletionUsage(completion_tokens=13, prompt_tokens=20, total_tokens=33)) 
Model=gpt-3.5-turbo-0125; 
final returned processed chunk: ModelResponse(id='chatcmpl-9Vxs9b8Py8J4wJXgVPq2P6nfGTnOo', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content=None, role=None, function_call=None, tool_calls=None), logprobs=None)], created=1717405345, model='gpt-3.5-turbo-0125', object='chat.completion.chunk', system_fingerprint=None, usage=CompletionUsage(completion_tokens=13, prompt_tokens=20, total_tokens=33)) 
Model=gpt-3.5-turbo-0125; 
success callbacks: [<litellm.proxy.hooks.parallel_request_limiter._PROXY_MaxParallelRequestsHandler object at 0x7f61a45cdc50>, <litellm.proxy.hooks.max_budget_limiter._PROXY_MaxBudgetLimiter object at 0x7f61a45cdc90>, <litellm.proxy.hooks.cache_control_check._PROXY_CacheControlCheck object at 0x7f61a45cdcd0>, <litellm._service_logger.ServiceLogging object at 0x7f61a3c450d0>] 
success callbacks: [<litellm.proxy.hooks.parallel_request_limiter._PROXY_MaxParallelRequestsHandler object at 0x7f61a45cdc50>, <litellm.proxy.hooks.max_budget_limiter._PROXY_MaxBudgetLimiter object at 0x7f61a45cdc90>, <litellm.proxy.hooks.cache_control_check._PROXY_CacheControlCheck object at 0x7f61a45cdcd0>, <litellm._service_logger.ServiceLogging object at 0x7f61a3c450d0>] 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 3622, in async_data_generator
    chunk = chunk.model_dump_json(exclude_none=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 398, in model_dump_json
    return self.__pydantic_serializer__.to_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by ghost** [comment]
able to repro - working on a fix

**Comment by ghost** [comment]
i have a fix out @anbatista-com should be live in prod by tomorrow
