### ISSUE TITLE
[Bug]: Error using LiteLLM Proxy with Continue Autocomplete

### ISSUE THREAD

**Issue by mtrevin93** [BerriAI/litellm#4026]
### What happened?

I am running a LiteLLM Proxy with [Continue](https://www.continue.dev/). My LiteLLM models from AWS Bedrock work for chat, but for Autocomplete, I get an exception.
 Here is my Continue Config
`{
  "models": [],
  "customCommands": [
    {
      "name": "test",
      "prompt": "{{{ input }}}\n\nWrite a comprehensive set of unit tests for the selected code. It should setup, run tests that check for correctness including important edge cases, and teardown. Ensure that the tests are complete and sophisticated. Give the tests just as chat output, don't edit any file.",
      "description": "Write unit tests for highlighted code"
    }
  ],
  "tabAutocompleteModel": {
    "title": "mistral-7b",
    "provider": "openai",
    "model": "bedrock/mistral.mistral-7b-instruct-v0:2",
    "apiKey": "my-proxy-api-key",
    "apiBase": "my-proxy-api-base"
  }
}
`

### Relevant log output

```shell
Cloudwatch logs-----------------------------------------------------------------
INFO:     192.168.0.223:26816 - "POST /v1/completions HTTP/1.1" 200 OK
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 3615, in async_data_generator
    async for chunk in response:
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 11987, in __anext__
    async for chunk in self.completion_stream:
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 387, in _async_streaming
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 383, in _async_streaming
    async for line in response:
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 11925, in __anext__
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 11809, in __anext__
    async for chunk in self.completion_stream:
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/bedrock_httpx.py", line 1169, in aiter_bytes
    message = self._parse_message_from_event(event)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/bedrock_httpx.py", line 1178, in _parse_message_from_event
    raise ValueError(f"Bad response code, expected 200: {response_dict}")
ValueError: Bad response code, expected 200: {'status_code': 400, 'headers': {':exception-type': 'validationException', ':content-type': 'application/json', ':message-type': 'exception'}, 'body': b'{"message":"Validation Error"}'}
received response in _async_streaming: <coroutine object BedrockLLM.async_streaming at 0x7f0fb4623780>
Inside Max Parallel Request Failure Hook
------------------------------------------------------------------------------------------
```

**Comment by ghost** [comment]
hey @mtrevin93 this looks like bedrock raised a bad request error 
>     raise ValueError(f"Bad response code, expected 200: {response_dict}")
ValueError: Bad response code, expected 200: {'status_code': 400, 'headers': {':exception-type': 'validationException', ':content-type': 'application/json', ':message-type': 'exception'}, 'body': b'{"message":"Validation Error"}'}

can you share the raw call for repro? i believe if you run the proxy with `--detailed_debug` you should see this

**Comment by mtrevin93** [comment]
### LiteLLM Debug Log
Timestamp: 21:56:56
File: utils.py:1280
Pre-API Call Additional Args:
```
{
    "complete_input_dict": "{\"messages\": [{\"role\": \"user\", \"content\": [{\"type\": \"text\", \"text\": \"You are a HOLE FILLER. You are provided with a file containing holes, formatted as '{{HOLE_NAME}}'. Your TASK is to complete with a string to replace this hole with, inside a <COMPLETION/> XML tag, including context-aware indentation, if needed.  All completions MUST be truthful, accurate, well-written and correct.\\n\\n## EXAMPLE QUERY:\\n\\n<QUERY>\\nfunction sum_evens(lim) {\\n  var sum = 0;\\n  for (var i = 0; i < lim; ++i) {\\n    {{FILL_HERE}}\\n  }\\n  return sum;\\n}\\n</QUERY>\\n\\nTASK: Fill the {{FILL_HERE}} hole.\\n\\n## CORRECT COMPLETION\\n\\n<COMPLETION>if (i % 2 === 0) {\\n      sum += i;\\n    }</COMPLETION>\\n\\n## EXAMPLE QUERY:\\n\\n<QUERY>\\ndef sum_list(lst):\\n  total = 0\\n  for x in lst:\\n  {{FILL_HERE}}\\n  return total\\n\\nprint sum_list([1, 2, 3])\\n</QUERY>\\n\\n## CORRECT COMPLETION:\\n\\n<COMPLETION>  total += x</COMPLETION>\\n\\n## EXAMPLE QUERY:\\n\\n<QUERY>\\n// data Tree a = Node (Tree a) (Tree a) \\| Leaf a\\n\\n// sum :: Tree Int -> Int\\n// sum (Node lft rgt) = sum lft + sum rgt\\n// sum (Leaf val)     = val\\n\\n// convert to TypeScript:\\n{{FILL_HERE}}\\n</QUERY>\\n\\n## CORRECT COMPLETION:\\n\\n<COMPLETION>type Tree<T>\\n  = {$:\\\"Node\\\", lft: Tree<T>, rgt: Tree<T>}\\n  \\| {$:\\\"Leaf\\\", val: T};\\n\\nfunction sum(tree: Tree<number>): number {\\n  switch (tree.$) {\\n    case \\\"Node\\\":\\n      return sum(tree.lft) + sum(tree.rgt);\\n    case \\\"Leaf\\\":\\n      return tree.val;\\n  }\\n}</COMPLETION>\\n\\n## EXAMPLE QUERY:\\n\\nThe 4th {{FILL_HERE}} is Jupiter.\\n\\n## CORRECT COMPLETION:\\n\\n<COMPLETION>the 4th planet after Mars</COMPLETION>\\n\\n## EXAMPLE QUERY:\\n\\nfunction hypothenuse(a, b) {\\n  return Math.sqrt({{FILL_HERE}}b ** 2);\\n}\\n\\n## CORRECT COMPLETION:\\n\\n<COMPLETION>a ** 2 + </COMPLETION>\\n\\n<QUERY>\\nconst calculateC{{FILL_HERE}}\\n</QUERY>\\nTASK: Fill the {{FILL_HERE}} hole. Answer only with the CORRECT completion, and NOTHING ELSE. Do it now.\\n<COMPLETION>\"}]}], \"temperature\": 0.01, \"stop_sequences\": [\"</COMPLETION>\", \"\\n\\n\", \"\\r\\n\\r\\n\", \"/src/\", \"#- coding: utf-8\", \"```\", \"\\nfunction\", \"\\nclass\", \"\\nmodule\", \"\\nexport\", \"\\nimport\"], \"max_tokens\": 1024, \"anthropic_version\": \"bedrock-2023-05-31\"}",
    "api_base": "https://bedrock-runtime.us-east-1.amazonaws.com/model/anthropic.claude-3-sonnet-20240229-v1:0/invoke-with-response-stream",
```
### POST Request Sent from LiteLLM:
```
curl -X POST \
https://bedrock-runtime.us-east-1.amazonaws.com/model/anthropic.claude-3-sonnet-20240229-v1:0/invoke-with-response-stream \
-d '{
    "messages": [
        {
            "role": "user",
            "content": [
                {
                    "type": "text",
                    "text": "You are a HOLE FILLER. You are provided with a file containing holes, formatted as '{{HOLE_NAME}}'. Your TASK is to complete with a string to replace this hole with, inside a <COMPLETION/> XML tag, including context-aware indentation, if needed.  All completions MUST be truthful, accurate, well-written and correct.\n\n## EXAMPLE QUERY:\n\n<QUERY>\nfunction sum_evens(lim) {\n  var sum = 0;\n  for (var i = 0; lim < ++i; ++i) {\n    {{FILL_HERE}}\n  }\n  return sum;\n}\n</QUERY>\n\nTASK: Fill the {{FILL_HERE}} hole.\n\n## CORRECT COMPLETION\n\n<COMPLETION>if (i % 2 === 0) {\n      sum += i;\n    }</COMPLETION>\n\n## EXAMPLE QUERY:\n\n<QUERY>\ndef sum_list(lst):\n  total = 0\n  for x in lst:\n  {{FILL_HERE}}\n  return total\n\nprint sum_list([1, 2, 3])\n</QUERY>\n\n## CORRECT COMPLETION:\n\n<COMPLETION>  total += x</COMPLETION>\n\n## EXAMPLE QUERY:\n\n<QUERY>\n// data Tree a = Node (Tree a) (Tree a) \| Leaf a\n\n// sum :: Tree Int -> Int\n// sum (Node lft rgt) = sum lft + sum rgt\n// sum (Leaf val)     = val\n\n// convert to TypeScript:\n{{FILL_HERE}}\n</QUERY>\n\n## CORRECT COMPLETION:\n\n<COMPLETION>type Tree<T>\n  = {$:\"Node\", lft: Tree<T>, rgt: Tree<T>}\n  \| {$:\"Leaf\", val: T};\n\nfunction sum(tree: Tree<number>): number {\n  switch (tree.$) {\n    case \"Node\":\n      return sum(tree.lft) + sum(tree.rgt);\n    case \"Leaf\":\n      return tree.val;\n  }\n}</COMPLETION>\n\n## EXAMPLE QUERY:\n\nThe 4th {{FILL_HERE}} is Jupiter.\n\n## CORRECT COMPLETION:\n\n<COMPLETION>the 4th planet after Mars</COMPLETION>\n\n## EXAMPLE QUERY:\n\nfunction hypothenuse(a, b) {\n  return Math.sqrt({{FILL_HERE}}b ** 2);\n}\n\n## CORRECT COMPLETION:\n\n<COMPLETION>a ** 2 + </COMPLETION>\n\n<QUERY>\nconst calculateC{{FILL_HERE}}\n</QUERY>\nTASK: Fill the {{FILL_HERE}} hole. Answer only with the CORRECT completion, and NOTHING ELSE. Do it now.\n<COMPLETION>"
                }
            ]
        }
    ],
    "temperature": 0.01,
    "stop_sequences": [
        "</COMPLETION>",
        "\n\n",
        "\r\n\r\n",
        "/src/",
        "#- coding: utf-8",
        "```",
        "\nfunction",
        "\nclass",
        "\nmodule",
        "\nexport",
        "\nimport"
    ],
    "max_tokens": 1024,
    "anthropic_version": "bedrock-2023-05-31"
}'
```
### LiteLLM Proxy Final Data:
```
{
    "model": "bedrock/anthropic.claude-3-sonnet-20240229-v1:0",
    "max_tokens": 1024,
    "temperature": 0.01,
    "stop": [
        "</COMPLETION>",
        "\n\n",
        "\r\n\r\n",
        "/src/",
        "#- coding: utf-8",
        "```",
        "\nfunction",
        "\nclass",
        "\nmodule",
        "\nexport",
        "\nimport"
    ],
    "prompt": "You are a HOLE FILLER. You are provided with a file containing holes, formatted as '{{HOLE_NAME}}'. Your TASK is to complete with a string to replace this hole with, inside a <COMPLETION/> XML tag, including context-aware indentation, if needed.  All completions MUST be truthful, accurate, well-written and correct.\n\n## EXAMPLE QUERY:\n\n<QUERY>\nfunction sum_evens(lim) {\n  var sum = 0;\n  for (var i = 0; lim < ++i; ++i) {\n    {{FILL_HERE}}\n  }\n  return sum;\n}\n</QUERY>\n\nTASK: Fill the {{FILL_HERE}} hole.\n\n## CORRECT COMPLETION\n\n<COMPLETION>if (i % 2 === 0) {\n      sum += i;\n    }</COMPLETION>\n\n## EXAMPLE QUERY:\n\n<QUERY>\ndef sum_list(lst):\n  total = 0\n  for x in lst:\n  {{FILL_HERE}}\n  return total\n\nprint sum_list([1, 2, 3])\n</QUERY>\n\n## CORRECT COMPLETION:\n\n<COMPLETION>  total += x</COMPLETION>\n\n## EXAMPLE QUERY:\n\n<QUERY>\n// data Tree a = Node (Tree a) (Tree a) | Leaf a\n\n// sum :: Tree Int -> Int\n// sum (Node lft rgt) = sum lft + sum rgt\n// sum (Leaf val)     = val\n\n// convert to TypeScript:\n{{FILL_HERE}}\n</QUERY>\n\n## CORRECT COMPLETION:\n\n<COMPLETION>type Tree<T>\n  = {$:\"Node\", lft: Tree<T>, rgt: Tree<T>}\n  | {$:\"Leaf\", val: T};\n\nfunction sum(tree: Tree<number>): number {\n  switch (tree.$) {\n    case \"Node\":\n      return sum(tree.lft) + sum(tree.rgt);\n    case \"Leaf\":\n      return tree.val;\n  }\n}</COMPLETION>\n\n## EXAMPLE QUERY:\n\nThe 4th {{FILL_HERE}} is Jupiter.\n\n## CORRECT COMPLETION:\n\n<COMPLETION>the 4th planet after Mars</COMPLETION>\n\n## EXAMPLE QUERY:\n\nfunction hypothenuse(a, b) {\n  return Math.sqrt({{FILL_HERE}}b ** 2);\n}\n\n## CORRECT COMPLETION:\n\n<COMPLETION>a ** 2 + </COMPLETION>\n\n<QUERY>\nconst calculateC{{FILL_HERE}}\n</QUERY>\nTASK: Fill the {{FILL_HERE}} hole. Answer only with the CORRECT completion, and NOTHING ELSE. Do it now.\n<COMPLETION>",
    "stream": true,
        "endpoint": "my-proxy/v1/completions"
    },
    "request_timeout": 600
}
```

**Comment by jamestenglish** [comment]
This PR checks for new lines: https://github.com/BerriAI/litellm/commit/0b9fa53e3e6da6fbe0c965fa77917f919210fa2c

but continue dev also seems to send carriage returns: https://github.com/continuedev/continue/blob/a565519425a06a0c3add3406713362d694c032f5/core/autocomplete/completionProvider.ts#L90
