### ISSUE TITLE
[Bug]: try Logging Proxy Input/Output - Langfuse but  langfuse UnauthorizedError

### ISSUE THREAD

**Issue by syGOAT** [BerriAI/litellm#4034]
### What happened?

I tried using langfuse by referring to the doc:
https://docs.litellm.ai/docs/proxy/logging#logging-proxy-inputoutput---langfuse
But occured an error:

### Relevant log output

```
received error response: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."}
received error response: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."}
received error response: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."}
Giving up execute_task_with_backoff(...) after 3 tries (langfuse.request.APIError: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."} (401): None)
Giving up execute_task_with_backoff(...) after 3 tries (langfuse.request.APIError: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."} (401): None)
error uploading: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."} (401): None
Traceback (most recent call last):
  File "/root/autodl-tmp/miniconda3/envs/litellm/lib/python3.11/site-packages/langfuse/task_manager.py", line 160, in upload
    self._upload_batch(batch)
  File "/root/autodl-tmp/miniconda3/envs/litellm/lib/python3.11/site-packages/langfuse/task_manager.py", line 187, in _upload_batch
    execute_task_with_backoff(batch)
  File "/root/autodl-tmp/miniconda3/envs/litellm/lib/python3.11/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/miniconda3/envs/litellm/lib/python3.11/site-packages/langfuse/task_manager.py", line 185, in execute_task_with_backoff
    return self._client.batch_post(batch=batch, metadata=metadata)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/miniconda3/envs/litellm/lib/python3.11/site-packages/langfuse/request.py", line 56, in batch_post
    return self._process_response(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/autodl-tmp/miniconda3/envs/litellm/lib/python3.11/site-packages/langfuse/request.py", line 120, in _process_response
    raise APIError(res.status_code, payload)
langfuse.request.APIError: {'error': 'UnauthorizedError', 'message': "Invalid public key. Confirm that you've configured the correct host."} (401): None
```

I have fixed the problem and will send a PR.

**Comment by syGOAT** [comment]
Reference to the doc of langfuse:
https://langfuse.com/docs/get-started
We should  set 3 env variables for logging to langfuse:
```shell
export LANGFUSE_PUBLIC_KEY="pk_kk"
export LANGFUSE_SECRET_KEY="sk_ss"
export LANGFUSE_HOST="https://cloud.langfuse.com" # 🇪🇺 EU region
# LANGFUSE_HOST="https://us.cloud.langfuse.com" # 🇺🇸 US region

**Comment by syGOAT** [comment]
Branch has been merged.
