### ISSUE TITLE
[Feature]: UI for viewing failed requests

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#405]
### The Feature

When a request fails (either litellm missing param or llm-provider related) i'm often trying to figure out what the exact inputs were. 

I think Stripe has a good implementation of this: 
- When I hit an error -> i get linked to a request_log_url 
- The url contains a split screen showing me the input and output 

v1 have this for a failed llm exceptions for huggingface models (providers - huggingface, togetherai, vllm). 

<img width="1296" alt="Screenshot 2023-09-19 at 8 52 16 AM" src="https://github.com/BerriAI/litellm/assets/17561003/2252310f-3d33-4387-a2ef-ec3ebe94f527">

<img width="1558" alt="Screenshot 2023-09-19 at 8 52 24 AM" src="https://github.com/BerriAI/litellm/assets/17561003/459ff98d-c5f0-4299-88da-a8e0e030f9a9">

-- 
Notes: don't store responses to a server. Have this sent locally via encoding the url 

### Motivation, pitch

better debugging

**Comment by ishaan-jaff** [comment]
nicely !

**Comment by ishaan-jaff** [comment]
# Types of errors:
- Passing in an incorrect model to litellm example: 
-  Getting an error from the provider:


## Passing in an incorrect model to litellm example: 
```python   
response = completion(
            model="chatgpt-v-2",
            messages=messages,
        )
```

### Error:
```shell
  File "/Users/ishaanjaffer/Github/litellm/litellm/tests/test_completion.py", line 142, in hf_test_completion
    response = completion(
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 638, in wrapper
    raise e
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 598, in wrapper
    result = original_function(*args, **kwargs)
  File "/Users/ishaanjaffer/Github/litellm/litellm/timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/ishaanjaffer/Github/litellm/litellm/timeout.py", line 33, in async_func
    return func(*args, **kwargs)
  File "/Users/ishaanjaffer/Github/litellm/litellm/main.py", line 1048, in completion
    raise exception_type(
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 2397, in exception_type
    raise original_exception
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 2377, in exception_type
    raise original_exception
  File "/Users/ishaanjaffer/Github/litellm/litellm/main.py", line 237, in completion
    model, custom_llm_provider = get_llm_provider(model=model, custom_llm_provider=custom_llm_provider)
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 1141, in get_llm_provider
    raise e
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 1138, in get_llm_provider
    raise ValueError(f"LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/{model}',..)` Learn more: https://docs.litellm.ai/docs/providers")
ValueError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface//roneneldan/TinyStories-3M',..)` Learn more: https://docs.litellm.ai/docs/providers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ishaanjaffer/Github/litellm/litellm/tests/test_completion.py", line 154, in <module>
    hf_test_completion()
  File "/Users/ishaanjaffer/Github/litellm/litellm/tests/test_completion.py", line 152, in hf_test_completion
    pytest.fail(f"Error occurred: {e}")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/outcomes.py", line 198, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: Error occurred: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface//roneneldan/TinyStories-3M',..)` Learn more: https://docs.litellm.ai/docs/providers
```

## Getting an error from the provider:
```python
user_message = "My name is Merve and my favorite"
        messages = [{ "content": user_message,"role": "user"}]
        response = completion(
            model="huggingface/roneneldan/TinyStories-3M", 
            messages=messages,
            api_base="https://p69xlsj6rpno5drq.us-east-1.aws.endpoints.huggingface.cloud",
            # task=None,
        )
        # Add any assertions here to check the response
        print(response)
```


### Error Traceback:
```shell
Traceback (most recent call last):
  File "/Users/ishaanjaffer/Github/litellm/litellm/main.py", line 668, in completion
    model_response = huggingface_restapi.completion(
  File "/Users/ishaanjaffer/Github/litellm/litellm/llms/huggingface_restapi.py", line 166, in completion
    raise HuggingfaceError(
litellm.llms.huggingface_restapi.HuggingfaceError: The following `model_kwargs` are not used by the model: ['details'] (note: typos in the generate arguments will also show up in this list)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ishaanjaffer/Github/litellm/litellm/tests/test_completion.py", line 142, in hf_test_completion
    response = completion(
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 638, in wrapper
    raise e
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 598, in wrapper
    result = original_function(*args, **kwargs)
  File "/Users/ishaanjaffer/Github/litellm/litellm/timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/ishaanjaffer/Github/litellm/litellm/timeout.py", line 33, in async_func
    return func(*args, **kwargs)
  File "/Users/ishaanjaffer/Github/litellm/litellm/main.py", line 1048, in completion
    raise exception_type(
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 2395, in exception_type
    raise e
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 2129, in exception_type
    raise InvalidRequestError(
litellm.exceptions.InvalidRequestError: HuggingfaceException - The following `model_kwargs` are not used by the model: ['details'] (note: typos in the generate arguments will also show up in this list)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ishaanjaffer/Github/litellm/litellm/tests/test_completion.py", line 154, in <module>
    hf_test_completion()
  File "/Users/ishaanjaffer/Github/litellm/litellm/tests/test_completion.py", line 152, in hf_test_completion
    pytest.fail(f"Error occurred: {e}")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/outcomes.py", line 198, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: Error occurred: HuggingfaceException - The following `model_kwargs` are not used by the model: ['details'] (note: typos in the generate arguments will also show up in this list)

```

**Comment by ishaan-jaff** [comment]
<img width="1274" alt="Screenshot 2023-09-20 at 2 14 10 PM" src="https://github.com/BerriAI/litellm/assets/29436595/f63f8ad9-32e7-4e19-837a-1752ae8dbfd9">


here's a local v0 - deploying this to the litellm package now

**Comment by ghost** [comment]
@ishaan-jaff can we close this? as i believe this is now added when i set 'litellm.set_verbose=True`

**Comment by ishaan-jaff** [comment]
yes done - going to add this to docs and then close
