### ISSUE TITLE
[Bug]: Helicone callback is not working

### ISSUE THREAD

**Issue by krishna-cant** [BerriAI/litellm#4062]
## Describe the bug
LiteLLM Python SDK integration with Helicone throws an error.

## To Reproduce
Follow the exact tutorial on the official docs: https://docs.litellm.ai/docs/observability/helicone_integration
Set up the callback using:
```
litellm.success_callback=["helicone"]
```

## Error
```
LiteLLM.LoggingError: [Non-Blocking] Exception occurred while success logging with integrations Traceback (most recent call last):
  File "...lib/python3.10/site-packages/litellm/utils.py", line 1804, in success_handler
    messages = kwargs["input"]
KeyError: 'input'
```

## Expected behavior
The logs should show up in Helicone.

## Versions
LiteLLM Python SDK version 1.40.1

## Code
```
import asyncio
from typing import Dict, Optional, Type
import instructor
import litellm
from pydantic import BaseModel


class LiteLLMWrapper:
    def __init__(self):
        litellm.success_callback=["helicone"]
        litellm.set_verbose=True
        self.litellm_client = instructor.from_litellm(litellm.acompletion)

    async def get_llm_response_async(
        self,
        system_prompt: str,
        user_message: str,
        response_model: Type[BaseModel],
        llm_model: str = "gpt-4-turbo-preview",
        max_tokens: int = 4000,
        properties_to_log: Optional[Dict[str, str]] = None,
    ) -> BaseModel:
        if properties_to_log is None:
            headers = {}
        else:
            headers = {
                f"Helicone-Property-{key}": value
                for key, value in properties_to_log.items()
            }
        response = await self.litellm_client.chat.completions.create(
            model=llm_model,
            response_model=response_model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_message},
            ],
            extra_headers=headers,
            max_tokens=max_tokens,
        )
        return response


async def main():
    class StringResponseModel(BaseModel):
        response: str

    litellm_wrapper = LiteLLMWrapper()
    entered_prompt = "help me with math"
    output = await litellm_wrapper.get_llm_response_async(
        system_prompt="What is 2+2?",
        user_message=entered_prompt,
        response_model=StringResponseModel,
    )
    print(f"Generated text: {output}")


if __name__ == "__main__":
    asyncio.run(main())
```

### Relevant log output

```shell
Request to litellm:
litellm.acompletion(messages=[{'role': 'system', 'content': 'What is 2+2?'}, {'role': 'user', 'content': 'help me with math'}], model='gpt-4-turbo-preview', extra_headers={}, max_tokens=4000, tools=[{'type': 'function', 'function': {'name': 'StringResponseModel', 'description': 'Correctly extracted `StringResponseModel` with all the required parameters with correct types', 'parameters': {'properties': {'response': {'title': 'Response', 'type': 'string'}}, 'required': ['response'], 'type': 'object'}}}], tool_choice={'type': 'function', 'function': {'name': 'StringResponseModel'}})


init callback list: helicone
self.optional_params: {}
ASYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache'): None
Final returned optional params: {'max_tokens': 4000, 'tools': [{'type': 'function', 'function': {'name': 'StringResponseModel', 'description': 'Correctly extracted `StringResponseModel` with all the required parameters with correct types', 'parameters': {'properties': {'response': {'title': 'Response', 'type': 'string'}}, 'required': ['response'], 'type': 'object'}}}], 'tool_choice': {'type': 'function', 'function': {'name': 'StringResponseModel'}}, 'extra_headers': {}, 'extra_body': {}}
self.optional_params: {'max_tokens': 4000, 'tools': [{'type': 'function', 'function': {'name': 'StringResponseModel', 'description': 'Correctly extracted `StringResponseModel` with all the required parameters with correct types', 'parameters': {'properties': {'response': {'title': 'Response', 'type': 'string'}}, 'required': ['response'], 'type': 'object'}}}], 'tool_choice': {'type': 'function', 'function': {'name': 'StringResponseModel'}}, 'extra_headers': {}, 'extra_body': {}}


POST Request Sent from LiteLLM:
curl -X POST \
https://api.openai.com/v1/ \
-H 'Authorization: HIDDEN' \
-d '{'model': 'gpt-4-turbo-preview', 'messages': [{'role': 'system', 'content': 'What is 2+2?'}, {'role': 'user', 'content': 'help me with math'}], 'max_tokens': 4000, 'tools': [{'type': 'function', 'function': {'name': 'StringResponseModel', 'description': 'Correctly extracted `StringResponseModel` with all the required parameters with correct types', 'parameters': {'properties': {'response': {'title': 'Response', 'type': 'string'}}, 'required': ['response'], 'type': 'object'}}}], 'tool_choice': {'type': 'function', 'function': {'name': 'StringResponseModel'}}, 'extra_headers': {}, 'extra_body': {}}'


RAW RESPONSE:
{"id": "chatcmpl-9XByr4r363scREk9XN9HIg1hM4LHB", "choices": [{"finish_reason": "stop", "index": 0, "logprobs": null, "message": {"content": null, "role": "assistant", "function_call": null, "tool_calls": [{"id": "call_RSToka1xWogT7xWqqwOZU6n4", "function": {"arguments": "{\"response\":\"Sure, I'd be happy to help with your math question. What do you need assistance with?\"}", "name": "StringResponseModel"}, "type": "function"}]}}], "created": 1717697905, "model": "gpt-4-0125-preview", "object": "chat.completion", "system_fingerprint": null, "usage": {"completion_tokens": 24, "prompt_tokens": 81, "total_tokens": 105}}


Async Wrapper: Completed Call, calling async_success_handler: <bound method Logging.async_success_handler of <litellm.utils.Logging object at 0x102fbce80>>
Logging Details LiteLLM-Success Call: None
Looking up model=gpt-4-0125-preview in model_cost_map
Success: model=gpt-4-0125-preview in model_cost_map
prompt_tokens=81; completion_tokens=24
Returned custom cost for model=gpt-4-0125-preview - prompt_tokens_cost_usd_dollar: 0.0008100000000000001, completion_tokens_cost_usd_dollar: 0.00072
final cost: 0.0015300000000000001; prompt_tokens_cost_usd_dollar: 0.0008100000000000001; completion_tokens_cost_usd_dollar: 0.00072
success callbacks: ['helicone']
reaches helicone for logging!
Generated text: response="Sure, I'd be happy to help with your math question. What do you need assistance with?"
Logging Details LiteLLM-Async Success Call
Looking up model=gpt-4-0125-preview in model_cost_map
Success: model=gpt-4-0125-preview in model_cost_map
prompt_tokens=81; completion_tokens=24
Returned custom cost for model=gpt-4-0125-preview - prompt_tokens_cost_usd_dollar: 0.0008100000000000001, completion_tokens_cost_usd_dollar: 0.00072
final cost: 0.0015300000000000001; prompt_tokens_cost_usd_dollar: 0.0008100000000000001; completion_tokens_cost_usd_dollar: 0.00072
LiteLLM.LoggingError: [Non-Blocking] Exception occurred while success logging with integrations Traceback (most recent call last):
  File "<directory name hidden>/lib/python3.10/site-packages/litellm/utils.py", line 1804, in success_handler
    messages = kwargs["input"]
KeyError: 'input'

LiteLLM.Logging: is sentry capture exception initialized None
```

**Comment by ghost** [comment]
Able to repro - working on a fix @krishna-cant
