### ISSUE TITLE
[Feature]: For unmapped exceptions include traceback 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#4201]
### The Feature

For unmapped exceptions include traceback in error string. 

This is useful in the slack alert to understand what caused the call to fail 

### Motivation, pitch

better slack debugging 

### Twitter / LinkedIn details

cc: @lolsborn

**Comment by lishtys** [comment]
Starting from LiteLLM version 1.7.2, we observed that calling the Whisper endpoints on Groq results in unmapped exceptions. As mentioned in the documentation (https://github.com/BerriAI/litellm/issues/4201), such exceptions should ideally be raised with a traceback. We would appreciate any guidance on how to proceed or whether this is being addressed in upcoming updates.

Below is the trackback log.

```
Traceback (most recent call last):
2025-06-23T08:40:06.816435130Z   File "/app/app/routes/audio_stt.py", line 64, in _transcribe_groq
2025-06-23T08:40:06.816436777Z     response = await litellm.atranscription(
2025-06-23T08:40:06.816439183Z   File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 1494, in wrapper_async
2025-06-23T08:40:06.816440911Z     raise e
2025-06-23T08:40:06.816442341Z   File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 1355, in wrapper_async
2025-06-23T08:40:06.816444006Z     result = await original_function(*args, **kwargs)
2025-06-23T08:40:06.816445540Z   File "/usr/local/lib/python3.10/site-packages/litellm/main.py", line 4755, in atranscription
2025-06-23T08:40:06.816449570Z     raise exception_type(
2025-06-23T08:40:06.816451142Z   File "/usr/local/lib/python3.10/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2271, in exception_type
2025-06-23T08:40:06.816452884Z     raise e
2025-06-23T08:40:06.816454373Z   File "/usr/local/lib/python3.10/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 369, in exception_type
2025-06-23T08:40:06.816456060Z     raise BadRequestError(
2025-06-23T08:40:06.816457611Z litellm.exceptions.BadRequestError: litellm.BadRequestError: GroqException - unknown param `GROQ_TRANSCRIPTION_PARAMS[]`
```
Thanks for your time.
