### ISSUE TITLE
[Bug]: 429 error when using vertex_ai/gemini-1.5-pro-preview-0514 with file url as image_url. Probably mimetype

### ISSUE THREAD

**Issue by GautierT** [BerriAI/litellm#4262]
### What happened?

Hi ! Thanks for this awesome lib !

When I use openAI sdk with litellm proxy version 1.40.16 with this message payload : 

```
{
  model: "vertex_ai/gemini-1.5-pro-preview-0514",
  temperature: 0.05,
  messages: [
    {
      role: "system",
      content: ".",
    },
    {
      role: "user",
      content: [
        {
          type: "text",
          text: "<instructions>Utilise les documents lié (si il y en a) pour synthétiser très précisément et de manière exhaustif les informations.</instructions>",
        },
        {
          type: "image_url",
          image_url: {
            url: "https://S3_SIGNED_URL_REDACTED",
          },
        }
      ],
    }
  ],
}
```

I have an error : `429 No deployments available for selected model, Try again in 60 seconds. Passed model=vertex_ai/gemini-1.5-pro-preview-0514. pre-call-checks=False, allowed_model_region=n/a`

If I use base64 it's working (url: `data:${file.mimetype};base64,${arrayBufferToBase64(await wretch(file.url).get().arrayBuffer())}`)

Is this a litellm bug or something with vertex ? should I use google cloud hosting to host the file ? Thanks.

P.S : I think the problem is Litellm fail to get the mimetype of the downloaded file. (see logs.)

### Relevant log output

```shell
429 No deployments available for selected model, Try again in 60 seconds. Passed model=vertex_ai/gemini-1.5-pro-preview-0514. pre-call-checks=False, allowed_model_region=n/a


15:28:57 - LiteLLM:ERROR: main.py:399 - litellm.acompletion(): Exception occured - cannot identify image file <_io.BytesIO object at 0x7fcd64482480>
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_ai.py", line 950, in async_completion
    content = _gemini_convert_messages_with_history(messages=messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_ai.py", line 380, in _gemini_convert_messages_with_history
    _part = _process_gemini_image(image_url=image_url)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_ai.py", line 351, in _process_gemini_image
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_ai.py", line 328, in _process_gemini_image
    _blob = BlobType(data=image.data, mime_type=image._mime_type)
                                                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vertexai/generative_models/_generative_models.py", line 2212, in _mime_type
    return _FORMAT_TO_MIME_TYPE[self._pil_image.format.lower()]
                                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vertexai/generative_models/_generative_models.py", line 2205, in _pil_image
    self._loaded_image = PIL_Image.open(io.BytesIO(self._image_bytes))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PIL/Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fcd64482480>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 378, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_ai.py", line 1150, in async_completion
    raise VertexAIError(status_code=500, message=str(e))
litellm.llms.vertex_ai.VertexAIError: cannot identify image file <_io.BytesIO object at 0x7fcd64482480>

15:28:57 - LiteLLM:DEBUG: main.py:404 - Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_ai.py", line 950, in async_completion
    content = _gemini_convert_messages_with_history(messages=messages)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_ai.py", line 380, in _gemini_convert_messages_with_history
    _part = _process_gemini_image(image_url=image_url)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_ai.py", line 351, in _process_gemini_image
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_ai.py", line 328, in _process_gemini_image
    _blob = BlobType(data=image.data, mime_type=image._mime_type)
                                                ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vertexai/generative_models/_generative_models.py", line 2212, in _mime_type
    return _FORMAT_TO_MIME_TYPE[self._pil_image.format.lower()]
                                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/vertexai/generative_models/_generative_models.py", line 2205, in _pil_image
    self._loaded_image = PIL_Image.open(io.BytesIO(self._image_bytes))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/PIL/Image.py", line 3339, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fcd64482480>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 378, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_ai.py", line 1150, in async_completion
    raise VertexAIError(status_code=500, message=str(e))
litellm.llms.vertex_ai.VertexAIError: cannot identify image file <_io.BytesIO object at 0x7fcd64482480>

15:28:57 - LiteLLM:DEBUG: utils.py:236 - Logging Details: logger_fn - None | callable(logger_fn) - False
15:28:57 - LiteLLM:DEBUG: litellm_logging.py:1391 - Logging Details LiteLLM-Failure Call: [<bound method Router.deployment_callback_on_failure of <litellm.router.Router object at 0x7fcd8f96f450>>, <litellm.proxy.hooks.parallel_request_limiter._PROXY_MaxParallelRequestsHandler object at 0x7fcd8f208810>, <litellm.proxy.hooks.max_budget_limiter._PROXY_MaxBudgetLimiter object at 0x7fcd8f209410>, <litellm.proxy.hooks.cache_control_check._PROXY_CacheControlCheck object at 0x7fcd8fa33610>, <litellm._service_logger.ServiceLogging object at 0x7fcd8d206510>]
15:28:57 - LiteLLM Router:DEBUG: router.py:2834 - Attempting to add c618ef0147672b3d71ead9eac7b8e645e62f6d73aec596ad2904a2cd426e6e7e to cooldown list. updated_fails: 1; self.allowed_fails: 0
```

**Comment by ghost** [comment]
oh interesting, i see this: 

> PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7fcd64482480>

testing on my end now

**Comment by ghost** [comment]
@GautierT dm'ed on linkedin to start a support channel on this

**Comment by GautierT** [comment]
Hi @krrishdholakia 
Thanks for this.

But this is still not working for pdf files : 
And gemini 1.5 pro should accept pdf files.

"responseBody": "{\"error\":{\"message\":\"No deployments available for selected model, Try again in 60 seconds. Passed model=vertex_ai/gemini-1.5-pro-preview-0514. pre-call-checks=False, allowed_model_region=n/a, cooldown_list=[('c618ef0147672b3d71ead9eac7b8e645e62f6d73aec596ad2904a2cd426e6e7e', {'Exception Received': 'litellm.InternalServerError: VertexAIException InternalServerError - Image url not in expected format. Example Expected input - \\\"image_url\\\": \\\"data:image/jpeg;base64,{base64_image}\\\". Supported formats - [\\\\'image/jpeg\\\\', \\\\'image/png\\\\', \\\\'image/gif\\\\', \\\\'image/webp\\\\'] ', 'Status Code': '500'})]\",\"type\":\"None\",\"param\":\"None\",\"code\":429}}"

where input is like this : 

```
{
          "role": "user",
          "content": [
            {
              "type": "text",
              "text": "Que vois tu sur l'image ?"
            },
            {
              "type": "image_url",
              "image_url": {
                "url": "data:application/pdf;base64,JVBERi0xLjcKNCAwIG9iago8PAovVHlwZSAvUGFnZQovUmVzb3..........
```

**Comment by ghost** [comment]
@GautierT i don't think you can give a base64 pdf to vertex ai 

based on their docs it needs to be a gs:// url

**Comment by ghost** [comment]
<img width="846" alt="Screenshot 2024-07-06 at 1 09 17 PM" src="https://github.com/BerriAI/litellm/assets/17561003/39d49d43-4a5e-4e81-a01e-df7dc49c6c8f">


https://cloud.google.com/vertex-ai/generative-ai/docs/multimodal/document-understanding#single_pdf

**Comment by ghost** [comment]
curious - what would you expect to happen here? @GautierT

**Comment by GautierT** [comment]
Thanks @krrishdholakia . Indeed, with an gs:// file it's working !
