### ISSUE TITLE
[Bug]: Long Azure OpenAI streaming errors not logged on Langfuse (`incomplete chunked read`)

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#4312]
### What happened?

This one is really hard to reproduce. For prompts that take several minutes while streaming, sometimes LiteLLM seems to disconnect from Azure. Not sure why.. leaving this ticket open so others can report if they've also ran into this as well.

### Relevant log output

```shell
proxy_server.py:2546 - litellm.proxy.proxy_server.async_data_generator(): Exception occured - peer closed connection without sending complete message body (incomplete chunked read)
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ishaan-jaff** [comment]
this is from azure not litellm

**Comment by ishaan-jaff** [comment]
we've seen this issue before - is there something we can do better / raise a better exception

**Comment by Manouchehri** [comment]
It's not logged to langfuse at all for starters. 😅

**Comment by ishaan-jaff** [comment]
hmm wdym - you just see it client side ?

**Comment by Manouchehri** [comment]
Yes. Nothing ever in langfuse.

**Comment by ishaan-jaff** [comment]
hmm perhaps lets track this issue as streaming errors not logged in langfuse

**Comment by Manouchehri** [comment]
Semi related, I see this in my logs:

<img width="934" alt="image" src="https://github.com/BerriAI/litellm/assets/7232674/18140e62-9ac4-4bec-9d98-942afc186200">

**Comment by Manouchehri** [comment]
This is also a bug with OpenAI too. Ran into it today.

**Comment by ArnaudNorel95** [comment]
Hey I just have the same issue since yesterday, no change in my code, just big stream trigger this error with Azure-Openai
Did you find a solution @Manouchehri  ?

**Comment by inigoml** [comment]
Same problem here since last friday also with OpenAI (not Azure).

**Comment by ashwin153** [comment]
We're having this problem with Anthropic. @ishaan-jaff Is there something we can do to workaround this? It impacts maybe 1 in 4 requests.

**Comment by ishaan-jaff** [comment]
Is this just for streaming on Azure + langfuse @ashwin153 ?

**Comment by ashwin153** [comment]
Actually we also get these errors when hitting Anthropic directly. I think it must be something with our networking setup or with Anthropic itself and not something that LiteLLM is doing.

**Comment by ndrsfel** [comment]
Experiencing the same issue with our Azure OpenAI + LiteLLM `main-v1.67.0-stable` setup, no Langfuse configured. We're experiencing this error several times a day observed via our Slack Alerts. Sharing one for context with you:

```
Level: High
Timestamp: 15:38:02
Message: LLM API call failed: `litellm.APIConnectionError: AzureException APIConnectionError - peer closed connection without sending complete message body (incomplete chunked read)
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/lib/python3.13/site-packages/httpx/_transports/default.py", line 254, in __aiter__
    async for part in self._httpcore_stream:
        yield part
  File "/usr/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 407, in __aiter__
    raise exc from None
  File "/usr/lib/python3.13/site-packages/httpcore/_async/connection_pool.py", line 403, in __aiter__
    async for part in self._stream:
        yield part
  File "/usr/lib/python3.13/site-packages/httpcore/_async/http11.py", line 342, in __aiter__
    raise exc
  File "/usr/lib/python3.13/site-packages/httpcore/_async/http11.py", line 334, in __aiter__
    async for chunk in self._connection._receive_response_body(**kwargs):
        yield chunk
  File "/usr/lib/python3.13/site-packages/httpcore/_async/http11.py", line 203, in _receive_response_body
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/httpcore/_async/http11.py", line 213, in _receive_event
    with map_exceptions({h11.RemoteProtocolError: RemoteProtocolError}):
         ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/contextlib.py", line 162, in __exit__
    self.gen.throw(value)
    ~~~~~~~~~~~~~~^^^^^^^
  File "/usr/lib/python3.13/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/litellm/litellm_core_utils/streaming_handler.py", line 1656, in __anext__
    async for chunk in self.completion_stream:
    ...<48 lines>...
        return processed_chunk
  File "/usr/lib/python3.13/site-packages/openai/_streaming.py", line 147, in __aiter__
    async for item in self._iterator:
        yield item
  File "/usr/lib/python3.13/site-packages/openai/_streaming.py", line 160, in __stream__
    async for sse in iterator:
    ...<38 lines>...
            yield process_data(data={"data": data, "event": sse.event}, cast_to=cast_to, response=response)
  File "/usr/lib/python3.13/site-packages/openai/_streaming.py", line 151, in _iter_events
    async for sse in self._decoder.aiter_bytes(self.response.aiter_bytes()):
        yield sse
  File "/usr/lib/python3.13/site-packages/openai/_streaming.py", line 302, in aiter_bytes
    async for chunk in self._aiter_chunks(iterator):
    ...<5 lines>...
                yield sse
  File "/usr/lib/python3.13/site-packages/openai/_streaming.py", line 313, in _aiter_chunks
    async for chunk in iterator:
    ...<4 lines>...
                data = b""
  File "/usr/lib/python3.13/site-packages/httpx/_models.py", line 929, in aiter_bytes
    async for raw_bytes in self.aiter_raw():
    ...<2 lines>...
            yield chunk
  File "/usr/lib/python3.13/site-packages/httpx/_models.py", line 987, in aiter_raw
    async for raw_stream_bytes in self.stream:
    ...<2 lines>...
            yield chunk
  File "/usr/lib/python3.13/site-packages/httpx/_client.py", line 149, in __aiter__
    async for chunk in self._stream:
        yield chunk
  File "/usr/lib/python3.13/site-packages/httpx/_transports/default.py", line 253, in __aiter__
    with map_httpcore_exceptions():
         ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/usr/lib/python3.13/contextlib.py", line 162, in __exit__
    self.gen.throw(value)
~~~~~~~~~~~~~~^^^^^^^
  File "/usr/lib/python3.13/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.RemoteProtocolError: peer closed connection without sending complete message body (incomplete chunked read)
Model: gpt-4o-2024-11-20
API Base: https://api.openai.com`
:knot: Langfuse Trace: https://cloud.langfuse.com/trace/None
```
Even though, we don't use api.openai.com nor Langfuse nor `gpt-4o-2024-11-20` but `azure/gpt-4o` in our proxy config yaml.

I've found this [recent thread](https://community.openai.com/t/remoteprotocolerror-peer-closed-connection-without-sending-complete-message-body-incomplete-chunked-read/1109063/4) at OpenAI Community which is not related to Azure OpenAI but maybe helps with debugging on LiteLLM end.

Happy to provide more context if helpful.
