### ISSUE TITLE
[Bug]: acompletion - Object of type ClientSession is not JSON serializable

### ISSUE THREAD

**Issue by sauravpanda** [BerriAI/litellm#4384]
### What happened?

I was trying out acompletion on litellm SDK and got this error:

`Object of type ClientSession is not JSON serializable`

### Relevant log output

```shell
File "/Users/sauravpanda/Github/cloudcode-OSS/applicant-screening/main.py", line 83, in process_applicant_with_model
    response = await acompletion(model=model, messages=messages, session=session)
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/litellm/utils.py", line 1441, in wrapper_async
    raise e
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/litellm/utils.py", line 1269, in wrapper_async
    result = await original_function(*args, **kwargs)
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/litellm/main.py", line 406, in acompletion
    raise exception_type(
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/litellm/utils.py", line 7442, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: Object of type ClientSession is not JSON serializable
Traceback (most recent call last):
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/litellm/main.py", line 378, in acompletion
    response = await init_response
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/litellm/llms/openai.py", line 887, in acompletion
    raise e
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/litellm/llms/openai.py", line 872, in acompletion
    response = await openai_aclient.chat.completions.create(
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1283, in create
    return await self._post(
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/openai/_base_client.py", line 1805, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/openai/_base_client.py", line 1503, in request
    return await self._request(
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/openai/_base_client.py", line 1529, in _request
    request = self._build_request(options)
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/openai/_base_client.py", line 485, in _build_request
    return self._client.build_request(  # pyright: ignore[reportUnknownMemberType]
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/httpx/_client.py", line 357, in build_request
    return Request(
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/httpx/_models.py", line 340, in __init__
    headers, stream = encode_request(
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/httpx/_content.py", line 212, in encode_request
    return encode_json(json)
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/httpx/_content.py", line 175, in encode_json
    body = json_dumps(json).encode("utf-8")
  File "/Users/sauravpanda/.pyenv/versions/3.10.1/lib/python3.10/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/Users/sauravpanda/.pyenv/versions/3.10.1/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/sauravpanda/.pyenv/versions/3.10.1/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/sauravpanda/.pyenv/versions/3.10.1/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ClientSession is not JSON serializable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sauravpanda/Library/Caches/pypoetry/virtualenvs/applicant-screening-Ce_lHkbb-py3.10/lib/python3.10/site-packages/litellm/utils.py", line 5912, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: APIConnectionError: AnyscaleException - Object of type ClientSession is not JSON serializable
```

**Comment by ghost** [comment]
how do i repro this? @sauravpanda

**Comment by ghost** [comment]
> session=session)


seems like this is being caused by a param in your client code 

closing as this doesn't seem to be a litellm error
