### ISSUE TITLE
[Bug]: Return OpenAIResponse Object

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#455]
### What happened?

The response object is not an openai response object

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/krrishdholakia/miniconda3/bin/aider", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/krrishdholakia/miniconda3/lib/python3.11/site-packages/aider/main.py", line 508, in main
    coder.run()
  File "/Users/krrishdholakia/miniconda3/lib/python3.11/site-packages/aider/coders/base_coder.py", line 324, in run
    new_user_message = self.run_loop()
                       ^^^^^^^^^^^^^^^
  File "/Users/krrishdholakia/miniconda3/lib/python3.11/site-packages/aider/coders/base_coder.py", line 407, in run_loop
    return self.send_new_user_message(inp)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krrishdholakia/miniconda3/lib/python3.11/site-packages/aider/coders/base_coder.py", line 440, in send_new_user_message
    interrupted = self.send(messages, functions=self.functions)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krrishdholakia/miniconda3/lib/python3.11/site-packages/aider/coders/base_coder.py", line 560, in send
    hash_object, completion = send_with_retries(model, messages, functions, self.stream)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krrishdholakia/miniconda3/lib/python3.11/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krrishdholakia/miniconda3/lib/python3.11/site-packages/aider/sendchat.py", line 64, in send_with_retries
    res = openai.ChatCompletion.create(**kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krrishdholakia/miniconda3/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/krrishdholakia/miniconda3/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 165, in create
    assert not isinstance(response, OpenAIResponse)
AssertionError
```

**Comment by ghost** [comment]
@abhinavkulkarni i see the problem you encountered. working on a fix now.

**Comment by ghost** [comment]
fixed the streaming response object error - was an issue in proxy not package

**Comment by Nikita-Sherstnev** [comment]
I have the same issue with version 0.13.2.
