### ISSUE TITLE
[Bug]: Error accessing Prisma Engine after setting up http_proxy

### ISSUE THREAD

**Issue by Huyueeer** [BerriAI/litellm#4552]
### What happened?

I found an interesting thing, our isolated environment needs a proxy to access openai, but when I use litellm-database, well I think I need to access Prisma Engine internally (I don't know Prisma Engine very well), but because of the proxy, it can't be accessed resulting in an error report, if I remove the proxy, the If I remove the proxy, I can access Prisma Engine, but not openai, what should I do?

Repeat: I run in docker-compose.yml and configure environment:
      - LITELLM_MASTER_KEY=sk-1234
      - DATABASE_URL=postgresql://XXXX
      - UI_USERNAME=llm 
      - UI_PASSWORD=llm
      - http_proxy=http://xxxxx
      - https_proxy=http://xxxxx

### Relevant log output

```shell
litellm-1  | INFO:     Started server process [1]
litellm-1  | INFO:     Waiting for application startup.
litellm-1  | ERROR:    Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 786, in check_view_exists
litellm-1  |     await self.db.query_raw(
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/prisma/client.py", line 421, in query_raw
litellm-1  |     resp = await self._execute(
litellm-1  |            ^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/prisma/client.py", line 525, in _execute
litellm-1  |     return await self._engine.query(builder.build(), tx_id=self._tx_id)
litellm-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/prisma/engine/query.py", line 244, in query
litellm-1  |     return await self.request(
litellm-1  |            ^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/prisma/engine/http.py", line 149, in request
litellm-1  |     raise errors.EngineRequestError(resp, await resp.text())
litellm-1  | prisma.engine.errors.EngineRequestError: 503: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
litellm-1  | <html>
litellm-1  | <head>
litellm-1  | <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
litellm-1  | <title>ERROR: The requested URL could not be retrieved</title>
litellm-1  | <style type="text/css">
litellm-1  | <!--
litellm-1  | #content {
litellm-1  |    width: 600px;
litellm-1  |    margin: auto;
litellm-1  |    padding: 8px 8px 8px 8px;
litellm-1  | }
litellm-1  | #content h2 {
litellm-1  |    margin: 20px 0;
litellm-1  | }
litellm-1  | hr {
litellm-1  |    margin: 0;
litellm-1  | }
litellm-1  | -->
litellm-1  | </style>
litellm-1  | </head>
litellm-1  |
litellm-1  | <body bgcolor="#666666">
litellm-1  | <hr>
litellm-1  | <div id="content">
litellm-1  | <h2>ERROR<br>The requested URL could not be retrieved.</h2><br>
litellm-1  | URL: <a href="http://localhost:48285/">http://localhost:48285/</a><br>
litellm-1  | Error Code: [0x09]<br>
litellm-1  | Time: 05/Jul/2024:10:16:12 +0800<br>
litellm-1  | <br>
litellm-1  | </div>
litellm-1  | <hr>
litellm-1  |
litellm-1  | <!--
litellm-1  | Request Header:
litellm-1  | POST / HTTP/1.1
litellm-1  | Accept-Encoding: gzip, deflate
litellm-1  | User-Agent: python-httpx/0.27.0
litellm-1  | Accept: application/json
litellm-1  | Content-Length: 203
litellm-1  | Host: localhost:48285
litellm-1  |
litellm-1  | -->
litellm-1  |
litellm-1  | </body>
litellm-1  | </html>
litellm-1  |
litellm-1  |
litellm-1  |
litellm-1  | During handling of the above exception, another exception occurred:
litellm-1  |
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 732, in lifespan
litellm-1  |     async with self.lifespan_context(app) as maybe_state:
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 608, in __aenter__
litellm-1  |     await self._router.startup()
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 709, in startup
litellm-1  |     await handler()
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2567, in startup_event
litellm-1  |     create_view_response = await prisma_client.check_view_exists()
litellm-1  |                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
litellm-1  |     ret = await target(*args, **kwargs)
litellm-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 792, in check_view_exists
litellm-1  |     value = await self.health_check()
litellm-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 1870, in health_check
litellm-1  |     raise e
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 1852, in health_check
litellm-1  |     response = await self.db.query_raw(sql_query)
litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/prisma/client.py", line 421, in query_raw
litellm-1  |     resp = await self._execute(
litellm-1  |            ^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/prisma/client.py", line 525, in _execute
litellm-1  |     return await self._engine.query(builder.build(), tx_id=self._tx_id)
litellm-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/prisma/engine/query.py", line 244, in query
litellm-1  |     return await self.request(
litellm-1  |            ^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/prisma/engine/http.py", line 149, in request
litellm-1  |     raise errors.EngineRequestError(resp, await resp.text())
litellm-1  | prisma.engine.errors.EngineRequestError: 503: <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
litellm-1  | <html>
litellm-1  | <head>
litellm-1  | <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
litellm-1  | <title>ERROR: The requested URL could not be retrieved</title>
litellm-1  | <style type="text/css">
litellm-1  | <!--
litellm-1  | #content {
litellm-1  |    width: 600px;
litellm-1  |    margin: auto;
litellm-1  |    padding: 8px 8px 8px 8px;
litellm-1  | }
litellm-1  | #content h2 {
litellm-1  |    margin: 20px 0;
litellm-1  | }
litellm-1  | hr {
litellm-1  |    margin: 0;
litellm-1  | }
litellm-1  | -->
litellm-1  | </style>
litellm-1  | </head>
litellm-1  |
litellm-1  | <body bgcolor="#666666">
litellm-1  | <hr>
litellm-1  | <div id="content">
litellm-1  | <h2>ERROR<br>The requested URL could not be retrieved.</h2><br>
litellm-1  | URL: <a href="http://localhost:48285/">http://localhost:48285/</a><br>
litellm-1  | Error Code: [0x09]<br>
litellm-1  | Time: 05/Jul/2024:10:16:12 +0800<br>
litellm-1  | <br>
litellm-1  | </div>
litellm-1  | <hr>
litellm-1  |
litellm-1  | <!--
litellm-1  | Request Header:
litellm-1  | POST / HTTP/1.1
litellm-1  | Accept-Encoding: gzip, deflate
litellm-1  | User-Agent: python-httpx/0.27.0
litellm-1  | Accept: application/json
litellm-1  | Content-Length: 273
litellm-1  | Host: localhost:48285
litellm-1  |
litellm-1  | -->
litellm-1  |
litellm-1  | </body>
litellm-1  | </html>
litellm-1  |
litellm-1  |
litellm-1  |
litellm-1  | ERROR:    Application startup failed. Exiting.
litellm-1  |
litellm-1  | #------------------------------------------------------------#
litellm-1  | #                                                            #
litellm-1  | #            'The thing I wish you improved is...'            #
litellm-1  | #        https://github.com/BerriAI/litellm/issues/new        #
litellm-1  | #                                                            #
litellm-1  | #------------------------------------------------------------#
litellm-1  |
litellm-1  |  Thank you for using LiteLLM! - Krrish & Ishaan
litellm-1  |
litellm-1  |
litellm-1  |
litellm-1  | Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
litellm-1  |
litellm-1  |
litellm-1  | LiteLLM: Proxy initialized with Config, Set models:
litellm-1  |     gpt-4o
litellm-1  |     gpt-35-turbo-16k
litellm-1  |     gpt-4
litellm-1  | Intialized router with Routing strategy: simple-shuffle
litellm-1  |
litellm-1  | Routing enable_pre_call_checks: False
litellm-1  |
litellm-1  | Routing fallbacks: None
litellm-1  |
litellm-1  | Routing content fallbacks: None
litellm-1  |
litellm-1  | Routing context window fallbacks: None
litellm-1  |
litellm-1  | Router Redis Caching=None
litellm-1  |
litellm-1 exited with code 3
```

**Comment by ghost** [comment]
how do you add the proxy? 


Prisma uses httpx under-the-hood so any standard proxy env var settings should work for it too

**Comment by ghost** [comment]
can you make these upper case and test again

```
- http_proxy=http://xxxxx/
- https_proxy=http://xxxxx/
```

reference - https://www.python-httpx.org/environment_variables/#http_proxy-https_proxy-all_proxy

**Comment by ghost** [comment]
> litellm-database

You can also try with the standard litellm dockerfile and see if that works 

https://github.com/BerriAI/litellm/pkgs/container/litellm

**Comment by ghost** [comment]
bump on this @Huyueeer

**Comment by Huyueeer** [comment]
> 你能把这些改成大写然后再测试一下吗
> 
> ```
> - http_proxy=http://xxxxx/
> - https_proxy=http://xxxxx/
> ```
> 
> 参考-https: [//www.python-httpx.org/environment_variables/#http_proxy-https_proxy-all_proxy](https://www.python-httpx.org/environment_variables/#http_proxy-https_proxy-all_proxy)

@krrishdholakia No, he has no effect.

**Comment by ghost** [comment]
Hey @Huyueeer i was able to fix this by using litellm's dockerfile as a base image and running prisma generate as part of my dockerfile - 

```Dockerfile
# Use the provided base image
FROM ghcr.io/berriai/litellm:main-latest

# Set the working directory to /app
WORKDIR /app

### [👇 KEY STEP] ###
# Install Prisma CLI and generate Prisma client
RUN pip install prisma 
RUN prisma generate
### FIN #### 


# Expose the necessary port
EXPOSE 4000

# Override the CMD instruction with your desired command and arguments
# WARNING: FOR PROD DO NOT USE `--detailed_debug` it slows down response times, instead use the following CMD
# CMD ["--port", "4000", "--config", "config.yaml"]

# Define the command to run your app
ENTRYPOINT ["litellm"]

CMD ["--port", "4000"]
```

Docs: https://docs.litellm.ai/docs/proxy/deploy#litellm-without-internet-connection

---

This should be solved by [dockerfile.database](https://github.com/BerriAI/litellm/blob/main/Dockerfile.database), but i could see it raising errors when running the image without an internet connection. I'm unsure why the prisma generate files aren't stored correctly. It might be getting removed somehow. Any help debugging the issue would be great!

**Comment by hizzd** [comment]
For me, adding the binaries.prisma.sh domain to NO_PROXY solved the problem. 

This allows downloading Prisma's binary files without going through HTTPS_PROXY.

Example:
```bash
NO_PROXY="binaries.prisma.sh,localhost,127.0.0.1"
```

**Comment by jamesljl** [comment]
> For me, adding the binaries.prisma.sh domain to NO_PROXY solved the problem.
> 
> This allows downloading Prisma's binary files without going through HTTPS_PROXY.
> 
> Example:
> 
> NO_PROXY="binaries.prisma.sh,localhost,127.0.0.1"

yes, this worked for my docker compose yaml file
