### ISSUE TITLE
[Bug]: vertex_httpx.py breaks on missing `usageMetadata` keys

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#4559]
### What happened?

https://cloud.google.com/vertex-ai/generative-ai/docs/reference/nodejs/latest/vertexai/usagemetadata

These fields in `usageMetadata` are optional and cannot be assumed to be present.

### Relevant log output

```shell
litellm.APIConnectionError: 'promptTokenCount'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 9668, in __anext__
    async for chunk in self.completion_stream:
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_httpx.py", line 1416, in __anext__
    return self.chunk_parser(chunk=json_chunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_httpx.py", line 1346, in chunk_parser
    prompt_tokens=processed_chunk["usageMetadata"]["promptTokenCount"],
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'promptTokenCount'
```

### Twitter / LinkedIn details

https://twitter.com/DaveManouchehri

**Comment by ghost** [comment]
Fixed - https://github.com/BerriAI/litellm/commit/015a398713502d5b84c210b87bf106db277cdf3d
