### ISSUE TITLE
[Feature]: Enable local proxy - maps openai calls to any hosted model 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#456]
### The Feature

<img width="993" alt="Screenshot 2023-09-26 at 1 33 33 PM" src="https://github.com/BerriAI/litellm/assets/17561003/18a0f0b0-5998-46f1-a948-e24909824c57">

### Motivation, pitch

user request: 
- user tries multiple open source repos 
- for each repo, if they don't support tgi, user clones -> modifies to add litellm -> reruns to then point to their local tgi instance 

would be easier if they could just have an openai api base which receives the call, translates to tgi and sends to their local tgi model

**Comment by ghost** [comment]
cc: @abhinavkulkarni

**Comment by ghost** [comment]
Pushed in a72880925c0234bacc14a81e8899864fe1005e83

Will update docs once this is pushed. Roughly this is how it'll work: 

```
$ litellm --model <your-model-name> --api_base <your-api-base>
```

**Comment by ghost** [comment]
How it looks for me, using ollama 
<img width="1179" alt="Screenshot 2023-09-26 at 1 36 24 PM" src="https://github.com/BerriAI/litellm/assets/17561003/0030c8f5-64f2-4dd4-aef8-f37fca7efb76">

**Comment by ghost** [comment]
Using it with aider 
<img width="1157" alt="Screenshot 2023-09-26 at 1 36 52 PM" src="https://github.com/BerriAI/litellm/assets/17561003/855e66a9-bc79-4fd7-b59f-dc766a0076cc">

**Comment by ghost** [comment]
This is now supported - https://docs.litellm.ai/docs/proxy_server#advanced-setting-api-base

**Comment by abhinavkulkarni** [comment]
Hey @krrishdholakia,

I get the following error:

```bash
$ pip install litellm --upgrade
$ litellm --model codellama/CodeLlama-7b-Instruct-hf --api_base http://localhost:8080/generate
Traceback (most recent call last):
  File "/home/abhinav/miniconda3/envs/tgi/bin/litellm", line 8, in <module>
    sys.exit(run_server())
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/litellm/proxy_server/proxy_cli.py", line 10, in run_server
    from proxy_server import app, initialize
ModuleNotFoundError: No module named 'proxy_server'
```

Thanks!

**Comment by abhinavkulkarni** [comment]
Thanks, it worked after installing from the GitHub repo.

**Comment by ishaan-jaff** [comment]
Awesome - it was probably because the proxy is on the latest version of litellm

**Comment by ghost** [comment]
Hey @abhinavkulkarni if you're on v`0.1.781` it should be working. 

Can you let me know if that's not the case?

**Comment by abhinavkulkarni** [comment]
Hey @krrishdholakia,

I get the following error for TGI:

```bash
$ curl -s http://origin.concentricai.com:8000/chat/completions --header 'Content-Type: application/json' --data '{
  "model": "codellama/CodeLlama-7b-Instruct-hf-w4-g128-awq",
  "messages": [
    { 
      "role": "user",
      "content": "what do you know?"
    }
  ],
}'
```

```bash
INFO:     10.0.21.22:53896 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 30, in completion
    data = await request.json()
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/requests.py", line 244, in json
    self._json = json.loads(body)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 1 (char 173)
```

**Comment by abhinavkulkarni** [comment]
Hey @krrishdholakia,

I get the following error for TGI:

```bash
$ curl -s http://localhost:8000/chat/completions --header 'Content-Type: application/json' --data '{
  "model": "codellama/CodeLlama-7b-Instruct-hf",
  "messages": [
    { 
      "role": "user",
      "content": "what do you know?"
    }
  ],
}'
```

```bash
INFO:     10.0.21.22:53896 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/litellm/proxy/proxy_server.py", line 30, in completion
    data = await request.json()
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/starlette/requests.py", line 244, in json
    self._json = json.loads(body)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 1 (char 173)
```

**Comment by ghost** [comment]
hey @abhinavkulkarni thanks for sharing the code for repro. I'll run this and see what the error is.

**Comment by ghost** [comment]
Hey @abhinavkulkarni it looks like that's an error in the curl request. 

Can you try running this instead? 
```shell
curl --location 'http://0.0.0.0:8000/chat/completions' \
--header 'Content-Type: application/json' \
--data '{
  "model": "claude-2",
  "messages": [
    {
      "role": "user", 
      "content": "what do you know?"
    }
  ], 
  "temperature": 0.001
}'
```

**Comment by ghost** [comment]
I get a successful result when running the command for a deployed tgi model (phind codellama) 
<img width="847" alt="Screenshot 2023-09-26 at 10 47 32 PM" src="https://github.com/BerriAI/litellm/assets/17561003/417d9b2a-7210-4f5d-83b2-b2442a3364ea">

**Comment by abhinavkulkarni** [comment]
Hey @krrishdholakia,

I am still unable to get a correct response. Here's how I'm running my TGI:

```bash
text-generation-launcher \
--model-id abhinavkulkarni/codellama-CodeLlama-7b-Instruct-hf-w4-g128-awq \
--trust-remote-code --port 8080 \
--max-input-length 5376 --max-total-tokens 6144 --max-batch-prefill-tokens 6144 \
--quantize awq
```

If you have a 8GiB GPU, you should be able to run this command.

Here's how I'm running LiteLLM server:

```bash
litellm \
--model huggingface/abhinavkulkarni/codellama-CodeLlama-7b-Instruct-hf-w4-g128-awq \
--api_base http://localhost:8080/generate
```

And here's how I'm calling the API:

```bash
curl --location 'http://0.0.0.0:8000/chat/completions' --header 'Content-Type: application/json' --data '{
  "model": "huggingface/abhinavkulkarni/codellama-CodeLlama-7b-Instruct-hf-w4-g128-awq",
  "messages": [
    {
      "role": "user", 
      "content": "what do you know?"
    }
  ], 
  "temperature": 0.001
}'
```

I get the following error:

```bash
INFO:     127.0.0.1:52514 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/litellm/main.py", line 724, in completion
    model_response = huggingface_restapi.completion(
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/litellm/llms/huggingface_restapi.py", line 180, in completion
    ] = completion_response[0]["generated_text"]
KeyError: 0
```

**Comment by ghost** [comment]
Can you try removing '/generate' from your api_base and rerun the command?

**Comment by abhinavkulkarni** [comment]
Thanks @krrishdholakia, everything works after removing `/generate` from API_BASE.

I have opened a couple of other issues:

https://github.com/BerriAI/litellm/issues/476

https://github.com/BerriAI/litellm/issues/477

Thanks again!
