### ISSUE TITLE
Getting a Traceback issue

### ISSUE THREAD

**Issue by AshishJaimon** [BerriAI/litellm#461]
While I'm using the open interpreter, I'm encountering the following error:

Traceback (most recent call last):
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\litellm\main.py", line 251, in completion
    model, custom_llm_provider = get_llm_provider(model=model, custom_llm_provider=custom_llm_provider)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\litellm\utils.py", line 1204, in get_llm_provider
    raise e
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\litellm\utils.py", line 1201, in get_llm_provider
    raise ValueError(f"LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/{model}',..)` Learn more: https://docs.litellm.ai/docs/providers")
ValueError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/gpt-4',..)` Learn more: https://docs.litellm.ai/docs/providers

During the handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\interpreter\core\core.py", line 21, in cli
    cli(self)
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\interpreter\cli\cli.py", line 146, in cli
    interpreter.chat()
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\interpreter\core\core.py", line 65, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\interpreter\core\core.py", line 86, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 50, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\interpreter\core\core.py", line 94, in _streaming_chat
    yield from self._respond()
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\interpreter\core\core.py", line 120, in _respond
    yield from respond(self)
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\interpreter\core\respond.py", line 56, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\interpreter\llm\convert_to_coding_llm.py", line 19, in coding_llm
    for chunk in text_llm(messages):
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\interpreter\llm\setup_text_llm.py", line 119, in base_llm
    return litellm.completion(**params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\litellm\utils.py", line 671, in wrapper
    raise e
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\litellm\utils.py", line 630, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\litellm\main.py", line 1194, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\litellm\utils.py", line 2702, in exception_type
    raise e
  File "C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\litellm\utils.py", line 2684, in exception_type
    raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/gpt-4',..)` Learn more: https://docs.litellm.ai/docs/providers

**Comment by ghost** [comment]
You need to pass in the model. I can't tell which model you're trying to pass in here, though. 

For example if I was trying to call meta-llama/llama-2 on Huggingface inference endpoints

I'd do:
`huggingface/meta-llama/llama-2`

**Comment by ghost** [comment]
@AshishJaimon did this fix your issue?

**Comment by AshishJaimon** [comment]
The error occurs because the Language Learning Model (LLM) provider has not been provided. This provider is necessary to specify where the LLM should make requests to. For example, if using the Huggingface inference endpoints, a correct function call may look like `completion(model='huggingface/gpt-4',..)`. The error is raised in the `get_llm_provider` function called in the `completion` function. Without specifying a valid provider, the model cannot make requests and throws a `ValueError`.

The error then propagates up throughout the function calls, until it eventually reaches the `_respond` function, which calls the `base_llm` function that leads to the `completion` which raises the initial error. At each point where the error is being caught and raised again, a new traceback is created leading to the overlapping traceback messages.
.............................................................................................
The error originates from the `get_llm_provider` function located in the `"C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\litellm\utils.py"` file.

It then propagates up through the following files:

1. `"C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\litellm\main.py"` in the `completion` function.
2. `"C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\interpreter\llm\setup_text_llm.py"` in the `base_llm` function.
3. `"C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\interpreter\core\core.py"` in the `_respond` function.
4. `"C:\Users\Ashish Jaimon George\anaconda3\envs\Rock\Lib\site-packages\interpreter\core\core.py"` in the `_streaming_chat` function.

**Comment by AshishJaimon** [comment]
Please have look to the above issue

**Comment by ghost** [comment]
closing as this is openinterpreter related, not litellm
