### ISSUE TITLE
[Bug]: bedrock/mixtral-7b (and a few other models on bedrock) error out with 1.41.15

### ISSUE THREAD

**Issue by srail** [BerriAI/litellm#4679]
### What happened?

When I make a call using the format below format using  1.4??, calling `bedrock/mistral.mixtral-8x7b-instruct-v0:1` things break. It may be worth adding a test for this format - with a system message, and text content passed as a dict instead of a string. (OpenAI supports this format and uses it in some of their code samples; it's pretty convenient for multimodal stuff).

Note that the message below now also seems to throw errors for `bedrock/meta.llama3-70b-instruct-v1:0` and `bedrock/anthropic.claude-v2`; all of these previously worked. 

**Payload**:
`messages=[{'role': 'system', 'content': [{'type': 'text', 'text': 'Can you tell me which language model you are and what are the specific features or capabilities that distinguish you from other models?'}]}]`

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/.conda/envs/user/lib/python3.10/site-packages/litellm/main.py", line 2335, in completion
    response = bedrock_chat_completion.completion(
  File "/home/.conda/envs/user/lib/python3.10/site-packages/litellm/llms/bedrock_httpx.py", line 847, in completion
    prompt, chat_history = self.convert_messages_to_prompt(
  File "/home/.conda/envs/user/lib/python3.10/site-packages/litellm/llms/bedrock_httpx.py", line 300, in convert_messages_to_prompt
    prompt = prompt_factory(
  File "/home/.conda/envs/user/lib/python3.10/site-packages/litellm/llms/prompt_templates/factory.py", line 2447, in prompt_factory
    return mistral_instruct_pt(messages=messages)
  File "/home/.conda/envs/user/lib/python3.10/site-packages/litellm/llms/prompt_templates/factory.py", line 209, in mistral_instruct_pt
    prompt = custom_prompt(
  File "/home/.conda/envs/user/lib/python3.10/site-packages/litellm/llms/prompt_templates/factory.py", line 2396, in custom_prompt
    prompt += pre_message_str + message["content"] + post_message_str
TypeError: can only concatenate str (not "list") to str
, 'additional_args': {'exception_mapping_worked': True, 'original_exception': TypeError('can only concatenate str (not "list") to str')}}
```

**Comment by ghost** [comment]
interesting, i don't see this on their api reference - 
<img width="1445" alt="Screenshot 2024-07-12 at 6 50 18 PM" src="https://github.com/user-attachments/assets/95d7adc3-87a4-4a44-86d7-e3b45c882455">

**Comment by ghost** [comment]
is system always just text? or can i pass an image to it as well?
