### ISSUE TITLE
[Bug]: Instructor does not support multiple tool calls

### ISSUE THREAD

**Issue by agamm** [BerriAI/litellm#4699]
### What happened?

A bug happened! When using instructor and deepifra with pydantic and litellm.
versions:
```
litellm = "^1.41.19"
python = "^3.10"
instructor = "^1.3.3"
```

Code to reproduce:
```
import litellm
litellm.drop_params = True

from pydantic import BaseModel

    class Test(BaseModel):
        page: int
        text: str

    model = "deepinfra/Qwen/Qwen2-72B-Instruct"  

    # Structure the answer
    messages = [
        {
            "role": "system",
            "content": "You take text as input and structure it as valid JSON output.",
        },
        {
            "role": "user",
            "content": "Something unrelated",
        },
    ]

    a = client.chat.completions.create(
        model=model,
        messages=messages,
        response_model=Test,
    )
    print("Structured response:", a)
    
```

It seems like when the text sent to the llm to strucutre isn't easily structurable, it fails with this error.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/user/dev/myproject/src/src/core/analyzer/llm.py", line 87, in <module>
    a = client.chat.completions.create(
  File "/home/user/dev/myproject/src/.venv/lib/python3.10/site-packages/instructor/client.py", line 91, in create
    return self.create_fn(
  File "/home/user/dev/myproject/src/.venv/lib/python3.10/site-packages/instructor/patch.py", line 143, in new_create_sync
    response = retry_sync(
  File "/home/user/dev/myproject/src/.venv/lib/python3.10/site-packages/instructor/retry.py", line 162, in retry_sync
    for attempt in max_retries:
  File "/home/user/dev/myproject/src/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 443, in __iter__
    do = self.iter(retry_state=retry_state)
  File "/home/user/dev/myproject/src/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
  File "/home/user/dev/myproject/src/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
  File "/home/user/dev/myproject/src/.venv/lib/python3.10/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
  File "/home/user/.pyenv/versions/3.10.6/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/user/.pyenv/versions/3.10.6/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/user/dev/myproject/src/.venv/lib/python3.10/site-packages/instructor/retry.py", line 168, in retry_sync
    return process_response(
  File "/home/user/dev/myproject/src/.venv/lib/python3.10/site-packages/instructor/process_response.py", line 144, in process_response
    model = response_model.from_response(
  File "/home/user/dev/myproject/src/.venv/lib/python3.10/site-packages/instructor/function_calls.py", line 125, in from_response
    return cls.parse_tools(completion, validation_context, strict)
  File "/home/user/dev/myproject/src/.venv/lib/python3.10/site-packages/instructor/function_calls.py", line 263, in parse_tools
    assert (
AssertionError: Instructor does not support multiple tool calls, use List[Model] instead.
```

### Twitter / LinkedIn details

agamm

**Comment by ghost** [comment]
i don't see litellm anywhere in this stacktrace - what is the litellm error here?

**Comment by ghost** [comment]
ran this locally with `litellm.set_verbose=True`. 

LiteLLM returns: 
```
Structured response: ModelResponse(id='chatcmpl-a7c8832ce4874617a949d14b90e2461f', choices=[Choices(finish_reason='stop', index=0, message=Message(content='{\n  "text": "Something unrelated"\n}', role='assistant', tool_calls=None, function_call=None))], created=1720908923, model='deepinfra/Qwen/Qwen2-72B-Instruct', object='chat.completion', system_fingerprint=None, usage=Usage(completion_tokens=10, prompt_tokens=28, total_tokens=38))
```

Instructor expects there to be a tool call in the response. It doesn't seem to support a scenario where content is not null 

<img width="1337" alt="Screenshot 2024-07-13 at 3 17 47 PM" src="https://github.com/user-attachments/assets/de9a807b-1f72-4f45-b320-126fa7a0e2f4">

**Comment by ghost** [comment]
@agamm i'm closing this issue as this doesn't seem related to litellm. But i'm open to suggestions on how we could handle this better on our end.

**Comment by agamm** [comment]
I'll try to open an issue with instructor and see.

**Comment by antonkulaga** [comment]
I had the same problem
