### ISSUE TITLE
[Bug]: /user/delete fails with 500 error

### ISSUE THREAD

**Issue by nhoffman** [BerriAI/litellm#4740]
### What happened?

The /user/delete API endpoint fails with a 500 Internal Server Error.

litellm version is 1.41.14 installed using the official docker image (ghcr.io/berriai/litellm-database:main-v1.41.14).

### Relevant log output

```shell
2024-07-16T15:41:31 INFO:     10.64.9.61:55666 - "GET /user/info?user_id=2465c1f6-b027-461a-b9f1-13e17e2f360b HTTP/1.1" 200 OK
2024-07-16T15:41:31 INFO:     10.64.9.61:55676 - "POST /user/delete HTTP/1.1" 500 Internal Server Error
2024-07-16T15:41:31 ERROR:    Exception in ASGI application
2024-07-16T15:41:31 Traceback (most recent call last):
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
2024-07-16T15:41:31     result = await app(  # type: ignore[func-returns-value]
2024-07-16T15:41:31              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
2024-07-16T15:41:31     return await self.app(scope, receive, send)
2024-07-16T15:41:31            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
2024-07-16T15:41:31     await super().__call__(scope, receive, send)
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
2024-07-16T15:41:31     await self.middleware_stack(scope, receive, send)
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
2024-07-16T15:41:31     raise exc
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
2024-07-16T15:41:31     await self.app(scope, receive, _send)
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
2024-07-16T15:41:31     await self.app(scope, receive, send)
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
2024-07-16T15:41:31     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-16T15:41:31     raise exc
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-16T15:41:31     await app(scope, receive, sender)
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
2024-07-16T15:41:31     await self.middleware_stack(scope, receive, send)
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
2024-07-16T15:41:31     await route.handle(scope, receive, send)
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
2024-07-16T15:41:31     await self.app(scope, receive, send)
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
2024-07-16T15:41:31     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
2024-07-16T15:41:31     raise exc
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
2024-07-16T15:41:31     await app(scope, receive, sender)
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
2024-07-16T15:41:31     response = await func(request)
2024-07-16T15:41:31                ^^^^^^^^^^^^^^^^^^^
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
2024-07-16T15:41:31     raw_response = await run_endpoint_function(
2024-07-16T15:41:31                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
2024-07-16T15:41:31     return await dependant.call(**values)
2024-07-16T15:41:31            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/management_endpoints/internal_user_endpoints.py", line 770, in delete_user
2024-07-16T15:41:31     deleted_users = await prisma_client.db.litellm_usertable.delete_many(
2024-07-16T15:41:31                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/prisma/actions.py", line 6101, in delete_many
2024-07-16T15:41:31     resp = await self._client._execute(
2024-07-16T15:41:31            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/prisma/client.py", line 525, in _execute
2024-07-16T15:41:31     return await self._engine.query(builder.build(), tx_id=self._tx_id)
2024-07-16T15:41:31            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/prisma/engine/query.py", line 244, in query
2024-07-16T15:41:31     return await self.request(
2024-07-16T15:41:31            ^^^^^^^^^^^^^^^^^^^
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/prisma/engine/http.py", line 141, in request
2024-07-16T15:41:31     return utils.handle_response_errors(resp, errors_data)
2024-07-16T15:41:31            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-07-16T15:41:31   File "/usr/local/lib/python3.11/site-packages/prisma/engine/utils.py", line 192, in handle_response_errors
2024-07-16T15:41:31     raise exc(error)
2024-07-16T15:41:31 prisma.errors.ForeignKeyViolationError: Foreign key constraint failed on the field: `LiteLLM_InvitationLink_user_id_fkey (index)`
```

**Comment by ghost** [comment]
able to repro

**Comment by ghost** [comment]
this happens when an invite link is generated for the user
