### ISSUE TITLE
[Feature]: Support instruct model `prompt` keyword argument in `openai.ChatCompletion.create` for LiteLLM proxy server

### ISSUE THREAD

**Issue by abhinavkulkarni** [BerriAI/litellm#477]
Hi,

Thanks a ton for the great work!

I have a local TGI installation.

```bash
$ text-generation-launcher 
  --model-id abhinavkulkarni/codellama-CodeLlama-7b-Instruct-hf-w4-g128-awq \
  --trust-remote-code --port 8080 \
  --max-input-length 5376 --max-total-tokens 6144 --max-batch-prefill-tokens 6144 \
  --quantize awq
```

I have a LiteLLM proxy server on top of that.

```python
$ litellm \
  --model huggingface/abhinavkulkarni/codellama-CodeLlama-7b-Instruct-hf-w4-g128-awq \
  --api_base http://localhost:8080
```

I am able to successfully obtain responses from openai.ChatCompletion.create endpoint as follows:

```python
>>> import openai
>>> openai.api_key = "xyz"
>>> openai.api_base = "http://0.0.0.0:8000"
>>> model = "huggingface/abhinavkulkarni/codellama-CodeLlama-7b-Instruct-hf-w4-g128-awq"
>>> completion = openai.ChatCompletion.create(model=model, messages=[{"role": "user", "content": "How are you?"}])
>>> print(completion)
{
  "object": "chat.completion",
  "choices": [
    {
      "finish_reason": "length",
      "index": 0,
      "message": {
        "content": "I'm fine, thanks. I'm glad to hear that.\n\nI'm",
        "role": "assistant",
        "logprobs": -18.19830319
      }
    }
  ],
  "id": "chatcmpl-7f8f5312-893a-4dab-aff5-3a97a354c2be",
  "created": 1695869575.316254,
  "model": "abhinavkulkarni/codellama-CodeLlama-7b-Instruct-hf-w4-g128-awq",
  "usage": {
    "prompt_tokens": 4,
    "completion_tokens": 15,
    "total_tokens": 19
  }
}
```

However, I am not able to obtain responses when using `prompt` keyword argument:

```python
>>> completion = openai.ChatCompletion.create(model=model, prompt="How are you?")
Traceback (most recent call last):
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/openai/api_requestor.py", line 403, in handle_error_response
    error_data = resp["error"]
TypeError: string indices must be integers
```

Here's how OpenAI uses it in the API: [link](https://platform.openai.com/docs/api-reference/completions/create)

Please note `messages` argument is used for chat models whereas `prompt` argument is used for instruct models.

Thanks!

**Comment by ghost** [comment]
Hey @abhinavkulkarni it looks like that's the openai.Completion endpoint.  (for text-davinci, etc.)

Thats: `v1/completions` 

is that what you're trying to proxy too?

**Comment by abhinavkulkarni** [comment]
Yes.

OpenAI (and all the other open-source models) have two versions - instruct and chat and we should support both of those.

Thanks!

**Comment by ghost** [comment]
Added here - d3340311084ac9512945fc088ff55e780f676a59

**Comment by ghost** [comment]
will update once this is in prod

**Comment by ghost** [comment]
This is now in prod - `0.1.793`

Can confirm this works as well: 
<img width="811" alt="Screenshot 2023-09-27 at 10 12 52 PM" src="https://github.com/BerriAI/litellm/assets/17561003/c7efa1fe-f4c3-4a7e-a02f-7be61b4a5d1a">


@abhinavkulkarni please feel free to reopen this issue if this doesn't work for you

**Comment by abhinavkulkarni** [comment]
Hey @krrishdholakia,

I re-installed `litellm` package from GitHub (`pip install --upgrade git+https://github.com/BerriAI/litellm.git`).

I get the following error if I try to start the proxy server:

```bash
$ litellm \
  --model huggingface/abhinavkulkarni/codellama-CodeLlama-7b-Instruct-hf-w4-g128-awq \
  --api_base http://localhost:8080
Traceback (most recent call last):
  File "/home/abhinav/miniconda3/envs/tgi/bin/litellm", line 8, in <module>
    sys.exit(run_server())
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/litellm/proxy/proxy_cli.py", line 11, in run_server
    from proxy_server import app, initialize
ModuleNotFoundError: No module named 'proxy_server'
```

I had to change the following two lines in `litellm/proxy/proxy_cli.py`

from

```python
    # from .proxy_server import app, initialize
    from proxy_server import app, initialize
```

to 

```python
    from .proxy_server import app, initialize
    # from proxy_server import app, initialize
```

and then I was able to bring proxy server up.

I tried the newly added `prompt` argument, but I get the following error:

```python
>>> import openai
>>> model = "huggingface/abhinavkulkarni/codellama-CodeLlama-7b-Instruct-hf-w4-g128-awq"
>>> openai.api_key = "xyz"
>>> openai.api_base = "http://0.0.0.0:8000"
>>> completion = openai.ChatCompletion.create(model=model, prompt="How are you?", temperature=0.)
Traceback (most recent call last):
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/openai/api_requestor.py", line 403, in handle_error_response
    error_data = resp["error"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 153, in create
    response, _, api_key = requestor.request(
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/openai/api_requestor.py", line 298, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/openai/api_requestor.py", line 700, in _interpret_response
    self._interpret_response_line(
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/openai/api_requestor.py", line 765, in _interpret_response_line
    raise self.handle_error_response(
  File "/home/abhinav/miniconda3/envs/tgi/lib/python3.9/site-packages/openai/api_requestor.py", line 405, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: 'Internal Server Error' (HTTP response code was 500)
```

Looking at `litellm` server logs, I can see it says:

```python
TypeError: completion() got an unexpected keyword argument 'prompt'
```

Please note, I am able to successfully get a completion using `messages` keyword argument.

If I install `litellm` using the latest tag `pip install --upgrade git+https://github.com/BerriAI/litellm.git@v0.1.738`, I get the following error:

```
$ litellm
bash: /home/abhinav/miniconda3/envs/tgi/bin/litellm: No such file or directory
```

Thanks!

**Comment by ghost** [comment]
following up via dm's
