### ISSUE TITLE
[Bug]: adding self-hosted OAI-compatible endpoint fails

### ISSUE THREAD

**Issue by arbi-dev** [BerriAI/litellm#4778]
### What happened?

Using the UI to add a self-hosted model with OAI compatible API.  The model is created selecting LLM provider as "OpenAI compatible endpoints provider", but calls to the model fail, supposedly due to the failure to specify LLM provider.  Indeed, looking at the /model/info json it only has the following, whereas other models had litellmprovider specified under model_info:
    {
      "model_name": "llama-3-70b",
      "litellm_params": {
        "custom_llm_provider": "openai",
        "api_base": "http://10.0.0.202:5000",
        "model": "llama-3-70b"
      },
      "model_info": {
        "id": "e57e2bc9-22f4-4495-bb7d-9cd58240943a",
        "db_model": true
      }
    }

### Relevant log output

```shell
litellm-litellm-1  | 18:54:19 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=llama-3-70b
litellm-litellm-1  |  Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
litellm-litellm-1  | 18:54:19 - LiteLLM Proxy:ERROR: proxy_server.py:2995 - litellm.proxy.proxy_server.chat_completion(): Exception occured - litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=llama-3-70b
litellm-litellm-1  |  Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
litellm-litellm-1  | Traceback (most recent call last):
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2891, in chat_completion
litellm-litellm-1  |     responses = await llm_responses
litellm-litellm-1  |                 ^^^^^^^^^^^^^^^^^^^
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 655, in acompletion
litellm-litellm-1  |     raise e
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 643, in acompletion
litellm-litellm-1  |     response = await self.async_function_with_fallbacks(**kwargs)
litellm-litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2484, in async_function_with_fallbacks
litellm-litellm-1  |     raise original_exception
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2346, in async_function_with_fallbacks
litellm-litellm-1  |     raise e
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2329, in async_function_with_fallbacks
litellm-litellm-1  |     response = await self.async_function_with_retries(*args, **kwargs)
litellm-litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2584, in async_function_with_retries
litellm-litellm-1  |     raise original_exception
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2506, in async_function_with_retries
litellm-litellm-1  |     response = await original_function(*args, **kwargs)
litellm-litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 785, in _acompletion
litellm-litellm-1  |     raise e
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 757, in _acompletion
litellm-litellm-1  |     response = await _response
litellm-litellm-1  |                ^^^^^^^^^^^^^^^
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1505, in wrapper_async
litellm-litellm-1  |     raise e
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1317, in wrapper_async
litellm-litellm-1  |     result = await original_function(*args, **kwargs)
litellm-litellm-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 338, in acompletion
litellm-litellm-1  |     _, custom_llm_provider, _, _ = get_llm_provider(
litellm-litellm-1  |                                    ^^^^^^^^^^^^^^^^^
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 4526, in get_llm_provider
litellm-litellm-1  |     raise e
litellm-litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 4503, in get_llm_provider
litellm-litellm-1  |     raise litellm.exceptions.BadRequestError(  # type: ignore
litellm-litellm-1  | litellm.exceptions.BadRequestError: litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=llama-3-70b
litellm-litellm-1  |  Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
litellm-litellm-1  | 
litellm-litellm-1  | 18:54:19 - LiteLLM Proxy:ERROR: _common.py:120 - Giving up chat_completion(...) after 1 tries (litellm.proxy._types.ProxyException)
litellm-litellm-1  | INFO:     10.0.0.100:57572 - "POST /chat/completions HTTP/1.1" 400 Bad Request
```

**Comment by devdev999** [comment]
Add openai/ as prefix for model name under litellm_params, `"model": "openai/llama-3-70b"`

**Comment by arbi-dev** [comment]
Thank you, that solved it!
