### ISSUE TITLE
Unexpcted Error

### ISSUE THREAD

**Issue by JingHai-Lingyun** [BerriAI/litellm#480]
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\litellm\main.py", line 250, in completion
    model, custom_llm_provider = get_llm_provider(model=model, custom_llm_provider=custom_llm_provider)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\litellm\utils.py", line 1224, in get_llm_provider
    raise e
  File "C:\Python311\Lib\site-packages\litellm\utils.py", line 1221, in get_llm_provider
    raise ValueError(f"LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/{model}',..)` Learn more: https://docs.litellm.ai/docs/providers")
ValueError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/gpt-4',..)` Learn more: https://docs.litellm.ai/docs/providers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Python311\Lib\site-packages\interpreter\core\core.py", line 21, in cli
    cli(self)
  File "C:\Python311\Lib\site-packages\interpreter\cli\cli.py", line 146, in cli
    interpreter.chat()
  File "C:\Python311\Lib\site-packages\interpreter\core\core.py", line 65, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Python311\Lib\site-packages\interpreter\core\core.py", line 86, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Python311\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 50, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Python311\Lib\site-packages\interpreter\core\core.py", line 94, in _streaming_chat
    yield from self._respond()
  File "C:\Python311\Lib\site-packages\interpreter\core\core.py", line 120, in _respond
    yield from respond(self)
  File "C:\Python311\Lib\site-packages\interpreter\core\respond.py", line 56, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Python311\Lib\site-packages\interpreter\llm\convert_to_coding_llm.py", line 19, in coding_llm
    for chunk in text_llm(messages):
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\interpreter\llm\setup_text_llm.py", line 119, in base_llm
    return litellm.completion(**params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\litellm\utils.py", line 691, in wrapper
    raise e
  File "C:\Python311\Lib\site-packages\litellm\utils.py", line 650, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Python311\Lib\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\litellm\main.py", line 1192, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\litellm\utils.py", line 2722, in exception_type
    raise e
  File "C:\Python311\Lib\site-packages\litellm\utils.py", line 2704, in exception_type
    raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/gpt-4',..)` Learn more: https://docs.litellm.ai/docs/providers

**Comment by MoYuan-CN** [comment]
Platform：Windows 10
Python：3.11.5

**Comment by ishaan-jaff** [comment]
hi @JingHai-Lingyun what model are you trying this with ? 

Can you show me the completion call you're making

**Comment by ishaan-jaff** [comment]
I can confirm GPT-4 works fine for me with this code:

```
import os 
from litellm import completion


## set ENV variables
os.environ["OPENAI_API_KEY"] = "" # [OPTIONAL] replace with your openai key

response = completion(
  model="gpt-4", 
  messages=[{ "content": "Hello, how are you?","role": "user"}]
)
response
```

**Comment by ghost** [comment]
this is a bug with openinterpreter - we need to see what they might be doing to cause this @ishaan-jaff
