### ISSUE TITLE
[Bug]: Error 422: drop_params Not Working with jamba-instruct Model in Azure AI

### ISSUE THREAD

**Issue by seonghobae** [BerriAI/litellm#4815]
### What happened?

# Bug Report: drop_params Not Working with jamba-instruct

## Description

When using the `jamba-instruct` model, the `drop_params` functionality is not working as expected. The following error messages are encountered:

```python
litellm.BadRequestError: Azure_aiException - Error code: 422 - {'error': ["Input should be 'user', 'assistant' or 'system'", 'Extra inputs are not permitted']}
```

```python
litellm.BadRequestError: Azure_aiException - Error code: 422 - {'error': ['Extra inputs are not permitted']}
```

It's simliar case of #4800 

## Steps to Reproduce

1. Attempt to use the **`jamba-instruct`** model with **`drop_params`** utilize with web-browser of LangGraph.
2. Observe the error message indicating that extra inputs are not permitted.

## Expected Behavior

The **`drop_params`** functionality should work without causing any errors, and the models should process the input as expected.

## Actual Behavior

The following error message is returned, indicating that extra inputs are not permitted:

```python
litellm.BadRequestError: Azure_aiException - Error code: 422 - {'error': ["Input should be 'user', 'assistant' or 'system'", 'Extra inputs are not permitted']}
```

```python
litellm.BadRequestError: Azure_aiException - Error code: 422 - {'error': ['Extra inputs are not permitted']}
```

## Environment

- Model: **`jamba-instruct`**
- Error Code: 422
- Error Message: Extra inputs are not permitted

Thank you for your attention to this matter.

### Relevant log output

```json
{
  "n": 1,
  "stop": [
    "<|eom|>"
  ],
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "route",
        "parameters": {
          "type": "object",
          "$schema": "http://json-schema.org/draft-07/schema#",
          "required": [
            "reasoning",
            "next",
            "instructions"
          ],
          "properties": {
            "next": {
              "enum": [
                "FINISH",
                "searxng",
                "search_keyword_generator",
                "synthetic_summarizer"
              ],
              "type": "string"
            },
            "reasoning": {
              "type": "string"
            },
            "instructions": {
              "type": "string",
              "description": "The specific instructions of the sub-task the next role should accomplish."
            }
          }
        },
        "description": "Select the worker to act next"
      }
    }
  ],
  "top_p": 1,
  "stream": true,
  "extra_body": {},
  "max_retries": 0,
  "temperature": 0.9,
  "presence_penalty": 0,
  "frequency_penalty": 0
}
```

Without stop sequences, I've got 500 error.
```json
{
  "n": 1,
  "tools": [
    {
      "type": "function",
      "function": {
        "name": "route",
        "parameters": {
          "type": "object",
          "$schema": "http://json-schema.org/draft-07/schema#",
          "required": [
            "reasoning",
            "next",
            "instructions"
          ],
          "properties": {
            "next": {
              "enum": [
                "FINISH",
                "searxng",
                "search_keyword_generator",
                "synthetic_summarizer"
              ],
              "type": "string"
            },
            "reasoning": {
              "type": "string"
            },
            "instructions": {
              "type": "string",
              "description": "The specific instructions of the sub-task the next role should accomplish."
            }
          }
        },
        "description": "Select the worker to act next"
      }
    }
  ],
  "top_p": 1,
  "stream": true,
  "extra_body": {},
  "max_retries": 0,
  "temperature": 0.9,
  "presence_penalty": 0,
  "frequency_penalty": 0
}
```
```python
litellm.APIConnectionError: APIConnectionError: Azure_aiException - 'list' object has no attribute 'get'
```
then, return this at next sequence.
```json
{
    "tool_calls": null,
    "function_call": null
}
```
```bash
03:11:42 - LiteLLM:ERROR: main.py:411 - litellm.acompletion(): Exception occured - 'list' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 1218, in async_streaming
    headers, response = await self.make_openai_chat_completion_request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 785, in make_openai_chat_completion_request
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 780, in make_openai_chat_completion_request
    response = await openai_aclient.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1214, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1790, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1493, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1584, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Error code: 422 - {'error': ['Extra inputs are not permitted']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 390, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 1234, in async_streaming
    if e.body is not None and e.body.get("detail"):  # type: ignore
                              ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'

03:11:42 - LiteLLM:ERROR: langfuse.py:565 - Langfuse Layer Error - Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 1218, in async_streaming
    headers, response = await self.make_openai_chat_completion_request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 785, in make_openai_chat_completion_request
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 780, in make_openai_chat_completion_request
    response = await openai_aclient.chat.completions.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1214, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1790, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1493, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1584, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.UnprocessableEntityError: Error code: 422 - {'error': ['Extra inputs are not permitted']}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 390, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 1234, in async_streaming
    if e.body is not None and e.body.get("detail"):  # type: ignore
                              ^^^^^^^^^^
AttributeError: 'list' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1336, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 418, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 8038, in exception_type
    raise e  # it's already mapped
    ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 6476, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: APIConnectionError: Azure_aiException - 'list' object has no attribute 'get'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/integrations/langfuse.py", line 321, in _log_langfuse_v2
    metadata = copy.deepcopy(
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 161, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle 'coroutine' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/integrations/langfuse.py", line 334, in _log_langfuse_v2
    new_metadata[key] = copy.deepcopy(value)
                        ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 206, in _deepcopy_list
    append(deepcopy(a, memo))
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 172, in deepcopy
    y = _reconstruct(x, memo, *rv)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 271, in _reconstruct
    state = deepcopy(state, memo)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 146, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 231, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/copy.py", line 161, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle 'coroutine' object

03:11:42 - LiteLLM Router:DEBUG: router.py:3199 - Attempting to add cb86e141-d8e1-4c5a-8dd2-89967b2c795a to cooldown list. updated_fails: 11; self.allowed_fails: 10
03:11:42 - LiteLLM Router:DEBUG: router.py:3233 - adding cb86e141-d8e1-4c5a-8dd2-89967b2c795a to cooldown models
03:11:42 - LiteLLM Proxy:DEBUG: parallel_request_limiter.py:24 - Inside Max Parallel Request Failure Hook
03:11:42 - LiteLLM Proxy:DEBUG: parallel_request_limiter.py:24 - user_api_key: 8f3c2a1a1b3c6d42a05ca18457e6a29b2a98dc812776d84a400effed2c767706
03:11:42 - LiteLLM Proxy:DEBUG: parallel_request_limiter.py:24 - updated_value in failure call: {'current_requests': 0, 'current_tpm': 0, 'current_rpm': 0}
03:11:42 - LiteLLM Proxy:DEBUG: proxy_server.py:593 - inside _PROXY_failure_handler kwargs=
03:11:42 - LiteLLM Router:INFO: router.py:787 - litellm.acompletion(model=azure_ai/jamba-instruct) Exception litellm.APIConnectionError: APIConnectionError: Azure_aiException - 'list' object has no attribute 'get'
03:11:42 - LiteLLM Router:DEBUG: router.py:3300 - retrieve cooldown models: [('cb86e141-d8e1-4c5a-8dd2-89967b2c795a', {'Exception Received': "litellm.APIConnectionError: APIConnectionError: Azure_aiException - 'list' object has no attribute 'get'", 'Status Code': '500'})]
```
![image](https://github.com/user-attachments/assets/9839177a-915b-4c45-9211-8ef258b56f26)

**Note: #4800 has same setting, I just changed a model. However, #4800 now doesn't try to use any tools in LangGraph settings.**

**Comment by ghost** [comment]
hey @seonghobae please can you give me a script to repro this error

**Comment by seonghobae** [comment]
> hey @seonghobae please can you give me a script to repro this error

Which script do you want? I ran this job on Flowise which backed LangGraph.js and Langchain.js framework. If you want to check this, can you give me a your email address to me to prevent security issues?

**Comment by ghost** [comment]
can you run litellm proxy with `--detailed_debug` and just share the server logs? 

Feel free to email me @ krrishdholakia@berri.ai

**Comment by ghost** [comment]
Hey @seonghobae i can see the error 

> openai.UnprocessableEntityError: Error code: 422 - {'error': ['Extra inputs are not permitted']}

the error returned from azure does not specify the parameters which are invalid. So we can't drop it. 

Looking at the request shared via email, it looks like tool calls are not supported by jamba instruct. 

How would you want this to be handled by us? @seonghobae

**Comment by seonghobae** [comment]
> Hey @seonghobae i can see the error
> 
> > openai.UnprocessableEntityError: Error code: 422 - {'error': ['Extra inputs are not permitted']}
> 
> the error returned from azure does not specify the parameters which are invalid. So we can't drop it.
> 
> Looking at the request shared via email, it looks like tool calls are not supported by jamba instruct.
> 
> How would you want this to be handled by us? @seonghobae

I see, but it doesn't fallback for 422 errors, even though I have fallback enabled in the settings. I think it would be much better if 422 errors were also fallbacked.

**Comment by ghost** [comment]
Hey @seonghobae your logs show a fallback did happen to `gpt-4o` 

```

POST Request Sent from LiteLLM:
curl -X POST \
https://hi-voc-gpt.openai.azure.com/openai/ \
-H 'Authorization: *****' \
<REDACTED>[0m

[92m00:36:33 - LiteLLM Proxy:DEBUG[0m: utils.py:2349 - End-User Spend transactions: 0
[92m00:36:33 - LiteLLM Proxy:DEBUG[0m: utils.py:2411 - KEY Spend transactions: 0
[92m00:36:33 - LiteLLM Proxy:DEBUG[0m: utils.py:2462 - Team Spend transactions: 0
[92m00:36:33 - LiteLLM Proxy:DEBUG[0m: utils.py:2614 - Spend Logs transactions: 0
[92m00:36:34 - LiteLLM Router:INFO[0m: router.py:779 - litellm.acompletion(model=azure/hi-gpt-4o)[32m 200 OK[0m
[92m00:36:34 - LiteLLM Router:DEBUG[0m: router.py:2337 - Async Response: <litellm.utils.CustomStreamWrapper object at 0x7f28a01ddf10>
[92m00:36:34 - LiteLLM Router:INFO[0m: router.py:2485 - Successful fallback b/w models.
```
