### ISSUE TITLE
[Feature]: Suppress "not found in completion cost map" error message?

### ISSUE THREAD

**Issue by paul-gauthier** [BerriAI/litellm#4818]
### The Feature

Is there any way to suppress this error message? Many of my users are confused by it and reporting it to me as a bug in aider.

```
LiteLLM:ERROR: litellm_logging.py:1265 - Model=deepseek-coder-v2 not found in completion cost map. Setting 'response_cost' to None?
```

### Motivation, pitch

This error confuses users and concerns litellm functionality that aider doesn't currently utilize.

**Comment by ghost** [comment]
hey @paul-gauthier are you on latest? this should no longer be getting raised as an error 

https://github.com/BerriAI/litellm/blob/a32a7af215dcde7162a0438ec7991fddc6ac00a5/litellm/litellm_core_utils/litellm_logging.py#L1271

**Comment by ghost** [comment]
closing for now as i believe this is already fixed. please reopen/bump me if not

**Comment by hemangjoshi37a** [comment]
getting same error with llama3.1:70B : `LiteLLM:ERROR: litellm_logging.py:1274 - Model=llama3.1:70b not found in completion cost map. Setting 'response_cost' to None`

**Comment by ghost** [comment]
@hemangjoshi37a you might be on an older version. 

The line being linked seems out of date - https://github.com/BerriAI/litellm/blob/9bdcef238bb8ffaf394ed8a522cad9adb9880e66/litellm/litellm_core_utils/litellm_logging.py#L1274

**Comment by ghost** [comment]
i can also see that, that message is now a warning - https://github.com/BerriAI/litellm/blob/9bdcef238bb8ffaf394ed8a522cad9adb9880e66/litellm/litellm_core_utils/litellm_logging.py#L1294

**Comment by hemangjoshi37a** [comment]
@krrishdholakia ok Bhai. Jai shree Ram ⛳

**Comment by paul-gauthier** [comment]
I am still seeing WARNINGs from this:

```
import litellm

litellm.suppress_debug_info = True
litellm.set_verbose = False
litellm.drop_params = True

model = "gemini/gemini-1.5-pro-exp-0801"
message = "hi"
messages=[{"role": "user", "content": message}]
comp = litellm.completion(model=model, messages=messages)
print(comp)
```

Produces this scary output:

```
16:15:49 - LiteLLM:WARNING: vertex_httpx.py:1052 - Unable to identify if system message supported. Defaulting to 'False'. Received error message - Model not in model_prices_and_context_window.json. You passed model=gemini-1.5-pro-exp-0801, custom_llm_provider=gemini.
Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json
16:15:50 - LiteLLM:WARNING: cost_calculator.py:738 - litellm.cost_calculator.py::response_cost_calculator - Returning None. Exception occurred - This model isn't mapped yet. model=gemini-1.5-pro-exp-0801, custom_llm_provider=gemini. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json/nTraceback (most recent call last):
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/utils.py", line 5042, in get_model_info
    raise ValueError(
ValueError: This model isn't mapped yet. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/cost_calculator.py", line 725, in response_cost_calculator
    response_cost = completion_cost(
                    ^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/cost_calculator.py", line 665, in completion_cost
    raise e
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/cost_calculator.py", line 648, in completion_cost
    ) = cost_per_token(
        ^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/cost_calculator.py", line 192, in cost_per_token
    return google_cost_per_token(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/llm_cost_calc/google.py", line 198, in cost_per_token
    model_info = litellm.get_model_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/utils.py", line 5090, in get_model_info
    raise Exception(
Exception: This model isn't mapped yet. model=gemini-1.5-pro-exp-0801, custom_llm_provider=gemini. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json

ModelResponse(id='chatcmpl-dfb6f2d7-9405-42c7-9e3a-0dce17aeb246', choices=[Choices(finish_reason='stop', index=0, message=Message(content='Hi there! How can I help you today? \n', role='assistant', tool_calls=[], function_call=None))], created=1722539749, model='gemini-1.5-pro-exp-0801', object='chat.completion', system_fingerprint=None, usage=Usage(prompt_tokens=2, completion_tokens=10, total_tokens=12))
16:15:50 - LiteLLM:WARNING: cost_calculator.py:738 - litellm.cost_calculator.py::response_cost_calculator - Returning None. Exception occurred - This model isn't mapped yet. model=gemini-1.5-pro-exp-0801, custom_llm_provider=gemini. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json/nTraceback (most recent call last):
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/utils.py", line 5042, in get_model_info
    raise ValueError(
ValueError: This model isn't mapped yet. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/cost_calculator.py", line 725, in response_cost_calculator
    response_cost = completion_cost(
                    ^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/cost_calculator.py", line 665, in completion_cost
    raise e
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/cost_calculator.py", line 648, in completion_cost
    ) = cost_per_token(
        ^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/cost_calculator.py", line 192, in cost_per_token
    return google_cost_per_token(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/llm_cost_calc/google.py", line 198, in cost_per_token
    model_info = litellm.get_model_info(
                 ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/utils.py", line 5090, in get_model_info
    raise Exception(
Exception: This model isn't mapped yet. model=gemini-1.5-pro-exp-0801, custom_llm_provider=gemini. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json
```

**Comment by paul-gauthier** [comment]
BTW, I am on latest:

```
$ pip freeze | grep litellm
litellm==1.42.8
```

**Comment by ghost** [comment]
Thanks @paul-gauthier - updated to respect `litellm.suppress_debug_info`

**Comment by aqeeb-warraich** [comment]
Your users reporting a cost-map error as an aider bug is the downstream version of a problem we care a lot about: when the cost numbers a tool shows drift from what the provider actually bills, the tool takes the blame. We published our approach to keeping per-request cost reconciled to the invoice: https://unitsense.ai/blog/smart-routing-pilot/
