### ISSUE TITLE
[Feature]: Add vertexAI/mistral-large-2

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#4874]
### The Feature

Mistral just launched on VertexAI - we will need to add support for this + cost tracking 

### Motivation, pitch

-

**Comment by ishaan-jaff** [comment]
https://cloud.google.com/blog/products/ai-machine-learning/codestral-and-mistral-large-v2-on-vertex-ai?e=48754805&hl=en

**Comment by ishaan-jaff** [comment]
https://mistral.ai/news/mistral-large-2407/

**Comment by grider-withourai** [comment]
Got the following error log for vertex mistral large model
```
[92m15:01:32 - LiteLLM Proxy:ERROR[0m: proxy_server.py:3012 - litellm.proxy.proxy_server.chat_completion(): Exception occured - litellm.InternalServerError: VertexAIException InternalServerError - 400 Request contains an invalid argument.
Received Model Group=mistral-large
Available Model Group Fallbacks=None LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/google/api_core/grpc_helpers_async.py", line 85, in __await__
    response = yield from self._call.__await__()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/grpc/aio/_call.py", line 327, in __await__
    raise _create_rpc_error(
grpc.aio._call.AioRpcError: <AioRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Request contains an invalid argument."
	debug_error_string = "UNKNOWN:Error received from peer ipv4:172.217.160.74:443 {created_time:"2024-07-25T15:01:30.932861217+00:00", grpc_status:3, grpc_message:"Request contains an invalid argument."}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_ai.py", line 1056, in async_completion
    response_obj = await llm_model.predict(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google/cloud/aiplatform_v1/services/prediction_service/async_client.py", line 404, in predict
    response = await rpc(
               ^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/google/api_core/grpc_helpers_async.py", line 88, in __await__
    raise exceptions.from_grpc_error(rpc_error) from rpc_error
google.api_core.exceptions.InvalidArgument: 400 Request contains an invalid argument.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 393, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_ai.py", line 1133, in async_completion
    raise VertexAIError(status_code=500, message=str(e))
litellm.llms.vertex_ai.VertexAIError: 400 Request contains an invalid argument.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2904, in chat_completion
    responses = await llm_responses
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 659, in acompletion
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 647, in acompletion
    response = await self.async_function_with_fallbacks(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2500, in async_function_with_fallbacks
    raise original_exception
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2336, in async_function_with_fallbacks
    response = await self.async_function_with_retries(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2600, in async_function_with_retries
    raise original_exception
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2522, in async_function_with_retries
    response = await original_function(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 792, in _acompletion
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 764, in _acompletion
    response = await _response
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1514, in wrapper_async
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1326, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 421, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 8050, in exception_type
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 7137, in exception_type
    raise litellm.InternalServerError(
litellm.exceptions.InternalServerError: litellm.InternalServerError: VertexAIException InternalServerError - 400 Request contains an invalid argument.
Received Model Group=mistral-large
Available Model Group Fallbacks=None LiteLLM Retried: 1 times, LiteLLM Max Retries: 2

[92m15:01:32 - LiteLLM Proxy:ERROR[0m: _common.py:120 - Giving up chat_completion(...) after 1 tries (litellm.proxy._types.ProxyException)
```
model_config:
```
      - model_name: mistral-large
        litellm_params: 
          vertex_location: europe-west4
          model: vertex_ai/mistralai/mistral-large@2407
```

It seems like some parameters are not supported by the model. Is there anyway to drop those unsupported params?

**Comment by ghost** [comment]
@grider-withourai vertex mistral is in a different format to gemini, so we need to manage that part first. 

Yes there's a way to drop unsupported params - https://docs.litellm.ai/docs/completion/drop_params#specify-params-to-drop

**Comment by allen-cook** [comment]
I'm getting this error when trying to use any of the mistral models on vertex with latest litellm/main

`Exception: This model isn't mapped yet. model=mistral-nemo, custom_llm_provider=vertex_ai. Add it here - https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json`

The model is in the prices as `mistral-nemo@2407`, for some reason when it's doing the cost lookup in `litellm_core_utils/llm_cost_calc/google.py` it's dropping the version number

**Comment by allen-cook** [comment]
Example code 

```
import litellm
model = "vertex_ai/mistral-nemo@2407"

messages = [
            {
                "role": "user",
                "content": "Hello how are you doing?",
            },
        ]

data = {
    "model": model,
    "messages": messages,
    "vertex_ai_project": "project",
    "vertex_ai_location": "us-central1",
}

print(litellm.completion(**data))
```

**Comment by allen-cook** [comment]
Also `codestral@2405` isn't correctly building the endpoint because it's[ looking for](https://github.com/BerriAI/litellm/blob/main/litellm/llms/vertex_ai_partner.py#L195) `mistral` in the name of the model

When the above script uses `"vertex_ai/codestral@2405"` for the model I get
```
litellm.exceptions.InternalServerError: litellm.InternalServerError: VertexAIException InternalServerError - 400 Invalid Endpoint name: projects/project-name/locations/us-central1/endpoints/codestral@2405.
```
The url should be similar to `projects/project-name/locations/us-central1/publishers/mistralai/models/codestral@2405:rawPredict`

**Comment by allen-cook** [comment]
I've submitted [a fix](https://github.com/BerriAI/litellm/pull/4983) for the codestral endpoint issues

**Comment by ghost** [comment]
Cost tracking fix for vertex ai mistral models added here - https://github.com/BerriAI/litellm/commit/1ffd96b348c2c0fd523640d0993a3523fa760b00 @allen-cook
