### ISSUE TITLE
[Bug]: logprobs=True with stream=True not working for vllm

### ISSUE THREAD

**Issue by JulietTeoh** [BerriAI/litellm#4898]
### What happened?

The bug was resolved in https://github.com/BerriAI/litellm/issues/3253 has reappeared in the current latest release.

Using the `image: ghcr.io/berriai/litellm:main-latest` docker image, when I run 

```
curl --location http://0.0.0.0:4000/v1/chat/completions
-H 'Content-Type: application/json' \
-H "Authorization: Bearer $LITELLM_MASTER_KEY" \
-d '{
        "model": "Meta-Llama-3-8B-Instruct",
        "messages": [
          {
            "role": "system",
            "content": "You are a helpful assistant."
          },
          {
            "role": "user",
            "content": "Say 10 random words in JSON format!"
          }
        ],
        "stream": true, 
        "logprobs": true, 
        "top_logprobs": 2
      }'
```

I get this error:

```
{
    "error": {
        "message": "Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'\n\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py\", line 2365, in async_data_generator\n    chunk = chunk.model_dump_json(exclude_none=True)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/site-packages/pydantic/main.py\", line 398, in model_dump_json\n    return self.__pydantic_serializer__.to_json(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\npydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'\n",
        "type": "None",
        "param": "None",
        "code": 500
    }
}
```

### Relevant log output

```shell
03:25:30 - LiteLLM Proxy:ERROR: proxy_server.py:2375 - litellm.proxy.proxy_server.async_data_generator(): Exception occured - Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
 Traceback (most recent call last):
   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2365, in async_data_generator
     chunk = chunk.model_dump_json(exclude_none=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 398, in model_dump_json
     return self.__pydantic_serializer__.to_json(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
 
 03:25:30 - LiteLLM Proxy:DEBUG: proxy_server.py:2385 - An error occurred: Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
```

**Comment by JulietTeoh** [comment]
the latest is v1.42.1

**Comment by Manouchehri** [comment]
What provider is Meta-Llama-3-8B-Instruct on? Bedrock?

**Comment by JulietTeoh** [comment]
the Llama3 model is a huggingface model (https://huggingface.co/meta-llama/Meta-Llama-3-8B) hosted on VLLM's OpenAI Compatible Server

it should give the same response as an OpenAI chat completion API

i think it cannot process the "[DONE]" chunk, at the end of a stream

**Comment by ghost** [comment]
hi @JulietTeoh, i can confirm this works fine on our end, and the test we added to ci/cd also passes 

<img width="1159" alt="Screenshot 2024-07-25 at 9 58 17 PM" src="https://github.com/user-attachments/assets/5ca11ad0-9fe9-4c2e-bc7e-281fa228d6dd">

can you please rerun your call with `--detailed_debug` and share the server logs + your config.yaml

**Comment by JulietTeoh** [comment]
here are some logs before the error occured. the last successful token is 'icopter'

```
06:52:39 - LiteLLM:DEBUG: utils.py:237 - Logging Details LiteLLM-Async Success Call
06:52:39 - LiteLLM:DEBUG: utils.py:237 - value of async chunk: ChatCompletionChunk(id='chat-f9bad6ec3c1146e99368682a0e7403fc', choices=[Choice(delta=ChoiceDelta(content='icopter', function_call=None, role=None, tool_calls=None), finish_reason=None, index=0, logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812, top_logprobs=[TopLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812), TopLogprob(token='ix', bytes=[105, 120], logprob=-5.509614944458008)])]))], created=1721976759, model='Meta-Llama-3-8B-Instruct', object='chat.completion.chunk', system_fingerprint=None, usage=None)
06:52:39 - LiteLLM:DEBUG: utils.py:237 - PROCESSED ASYNC CHUNK PRE CHUNK CREATOR: ChatCompletionChunk(id='chat-f9bad6ec3c1146e99368682a0e7403fc', choices=[Choice(delta=ChoiceDelta(content='icopter', function_call=None, role=None, tool_calls=None), finish_reason=None, index=0, logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812, top_logprobs=[TopLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812), TopLogprob(token='ix', bytes=[105, 120], logprob=-5.509614944458008)])]))], created=1721976759, model='Meta-Llama-3-8B-Instruct', object='chat.completion.chunk', system_fingerprint=None, usage=None)
06:52:39 - LiteLLM:DEBUG: utils.py:237 - 
Raw OpenAI Chunk
ChatCompletionChunk(id='chat-f9bad6ec3c1146e99368682a0e7403fc', choices=[Choice(delta=ChoiceDelta(content='icopter', function_call=None, role=None, tool_calls=None), finish_reason=None, index=0, logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812, top_logprobs=[TopLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812), TopLogprob(token='ix', bytes=[105, 120], logprob=-5.509614944458008)])]))], created=1721976759, model='Meta-Llama-3-8B-Instruct', object='chat.completion.chunk', system_fingerprint=None, usage=None)

06:52:39 - LiteLLM:DEBUG: utils.py:237 - completion obj content: icopter
06:52:39 - LiteLLM:DEBUG: utils.py:237 - model_response finish reason 3: None; response_obj={'text': 'icopter', 'is_finished': False, 'finish_reason': None, 'logprobs': ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812, top_logprobs=[TopLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812), TopLogprob(token='ix', bytes=[105, 120], logprob=-5.509614944458008)])]), 'original_chunk': ChatCompletionChunk(id='chat-f9bad6ec3c1146e99368682a0e7403fc', choices=[Choice(delta=ChoiceDelta(content='icopter', function_call=None, role=None, tool_calls=None), finish_reason=None, index=0, logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812, top_logprobs=[TopLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812), TopLogprob(token='ix', bytes=[105, 120], logprob=-5.509614944458008)])]))], created=1721976759, model='Meta-Llama-3-8B-Instruct', object='chat.completion.chunk', system_fingerprint=None, usage=None), 'usage': None}
06:52:39 - LiteLLM:DEBUG: utils.py:237 - original delta: {'content': 'icopter', 'function_call': None, 'role': None, 'tool_calls': None}
06:52:39 - LiteLLM:DEBUG: utils.py:237 - new delta: Delta(content='icopter', role=None, function_call=None, tool_calls=None)
06:52:39 - LiteLLM:DEBUG: utils.py:237 - model_response.choices[0].delta: Delta(content='icopter', role=None, function_call=None, tool_calls=None); completion_obj: {'content': 'icopter'}
06:52:39 - LiteLLM:DEBUG: utils.py:237 - self.sent_first_chunk: True
06:52:39 - LiteLLM:DEBUG: utils.py:237 - hold - False, model_response_str - icopter
06:52:39 - LiteLLM:DEBUG: utils.py:237 - choice_json: {'delta': {'content': 'icopter', 'function_call': None, 'role': None, 'tool_calls': None}, 'index': 0, 'logprobs': {'content': [{'token': 'icopter', 'bytes': [105, 99, 111, 112, 116, 101, 114], 'logprob': -0.009614944458007812, 'top_logprobs': [{'token': 'icopter', 'bytes': [105, 99, 111, 112, 116, 101, 114], 'logprob': -0.009614944458007812}, {'token': 'ix', 'bytes': [105, 120], 'logprob': -5.509614944458008}]}]}}
06:52:39 - LiteLLM:DEBUG: utils.py:237 - choices in streaming: [StreamingChoices(finish_reason=None, index=0, delta=Delta(content='icopter', role=None, function_call=None, tool_calls=None), logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812, top_logprobs=[TopLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812), TopLogprob(token='ix', bytes=[105, 120], logprob=-5.509614944458008)])]))]
06:52:39 - LiteLLM:DEBUG: utils.py:237 - self.sent_first_chunk: True
06:52:39 - LiteLLM:DEBUG: utils.py:237 - model_response.choices[0].delta: Delta(content='icopter', role=None, function_call=None, tool_calls=None)
06:52:39 - LiteLLM:DEBUG: utils.py:237 - returning model_response: ModelResponse(id='chat-f9bad6ec3c1146e99368682a0e7403fc', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='icopter', role=None, function_call=None, tool_calls=None), logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812, top_logprobs=[TopLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812), TopLogprob(token='ix', bytes=[105, 120], logprob=-5.509614944458008)])]))], created=1721976759, model='Meta-Llama-3-8B-Instruct', object='chat.completion.chunk', system_fingerprint=None)
06:52:39 - LiteLLM:DEBUG: utils.py:237 - PROCESSED ASYNC CHUNK POST CHUNK CREATOR: ModelResponse(id='chat-f9bad6ec3c1146e99368682a0e7403fc', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='icopter', role=None, function_call=None, tool_calls=None), logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812, top_logprobs=[TopLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812), TopLogprob(token='ix', bytes=[105, 120], logprob=-5.509614944458008)])]))], created=1721976759, model='Meta-Llama-3-8B-Instruct', object='chat.completion.chunk', system_fingerprint=None)
06:52:39 - LiteLLM:DEBUG: litellm_logging.py:576 - Logging Details LiteLLM-Success Call: Cache_hit=None
06:52:39 - LiteLLM:DEBUG: utils.py:237 - final returned processed chunk: ModelResponse(id='chat-f9bad6ec3c1146e99368682a0e7403fc', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='icopter', role=None, function_call=None, tool_calls=None), logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812, top_logprobs=[TopLogprob(token='icopter', bytes=[105, 99, 111, 112, 116, 101, 114], logprob=-0.009614944458007812), TopLogprob(token='ix', bytes=[105, 120], logprob=-5.509614944458008)])]))], created=1721976759, model='Meta-Llama-3-8B-Instruct', object='chat.completion.chunk', system_fingerprint=None)
06:52:39 - LiteLLM:DEBUG: litellm_logging.py:587 - success callbacks: [<litellm.proxy.hooks.parallel_request_limiter._PROXY_MaxParallelRequestsHandler object at 0x7fe0a08f5b10>, <litellm.proxy.hooks.max_budget_limiter._PROXY_MaxBudgetLimiter object at 0x7fe0a0a0b950>, <litellm.proxy.hooks.cache_control_check._PROXY_CacheControlCheck object at 0x7fe0a08f5b50>, <litellm._service_logger.ServiceLogging object at 0x7fe09ff934d0>]
06:52:39 - LiteLLM:DEBUG: utils.py:237 - Logging Details LiteLLM-Async Success Call
06:52:39 - LiteLLM:DEBUG: utils.py:237 - value of async chunk: ChatCompletionChunk(id='chat-f9bad6ec3c1146e99368682a0e7403fc', choices=[Choice(delta=ChoiceDelta(content='', function_call=None, role=None, tool_calls=None), finish_reason='stop', index=0, logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='', bytes=[], logprob=-0.00018153927521780133, top_logprobs=[TopLogprob(token='', bytes=[], logprob=-0.00018153927521780133), TopLogprob(token='\n\n', bytes=[10, 10], logprob=-9.062681198120117)])]), stop_reason=None)], created=1721976759, model='Meta-Llama-3-8B-Instruct', object='chat.completion.chunk', system_fingerprint=None, usage=None)
06:52:39 - LiteLLM:DEBUG: utils.py:237 - PROCESSED ASYNC CHUNK PRE CHUNK CREATOR: ChatCompletionChunk(id='chat-f9bad6ec3c1146e99368682a0e7403fc', choices=[Choice(delta=ChoiceDelta(content='', function_call=None, role=None, tool_calls=None), finish_reason='stop', index=0, logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='', bytes=[], logprob=-0.00018153927521780133, top_logprobs=[TopLogprob(token='', bytes=[], logprob=-0.00018153927521780133), TopLogprob(token='\n\n', bytes=[10, 10], logprob=-9.062681198120117)])]), stop_reason=None)], created=1721976759, model='Meta-Llama-3-8B-Instruct', object='chat.completion.chunk', system_fingerprint=None, usage=None)
06:52:39 - LiteLLM:DEBUG: utils.py:237 - 
Raw OpenAI Chunk
ChatCompletionChunk(id='chat-f9bad6ec3c1146e99368682a0e7403fc', choices=[Choice(delta=ChoiceDelta(content='', function_call=None, role=None, tool_calls=None), finish_reason='stop', index=0, logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='', bytes=[], logprob=-0.00018153927521780133, top_logprobs=[TopLogprob(token='', bytes=[], logprob=-0.00018153927521780133), TopLogprob(token='\n\n', bytes=[10, 10], logprob=-9.062681198120117)])]), stop_reason=None)], created=1721976759, model='Meta-Llama-3-8B-Instruct', object='chat.completion.chunk', system_fingerprint=None, usage=None)

06:52:39 - LiteLLM:DEBUG: utils.py:237 - completion obj content: 
06:52:39 - LiteLLM:DEBUG: utils.py:237 - model_response finish reason 3: stop; response_obj={'text': '', 'is_finished': True, 'finish_reason': 'stop', 'logprobs': ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='', bytes=[], logprob=-0.00018153927521780133, top_logprobs=[TopLogprob(token='', bytes=[], logprob=-0.00018153927521780133), TopLogprob(token='\n\n', bytes=[10, 10], logprob=-9.062681198120117)])]), 'original_chunk': ChatCompletionChunk(id='chat-f9bad6ec3c1146e99368682a0e7403fc', choices=[Choice(delta=ChoiceDelta(content='', function_call=None, role=None, tool_calls=None), finish_reason='stop', index=0, logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='', bytes=[], logprob=-0.00018153927521780133, top_logprobs=[TopLogprob(token='', bytes=[], logprob=-0.00018153927521780133), TopLogprob(token='\n\n', bytes=[10, 10], logprob=-9.062681198120117)])]), stop_reason=None)], created=1721976759, model='Meta-Llama-3-8B-Instruct', object='chat.completion.chunk', system_fingerprint=None, usage=None), 'usage': None}
06:52:39 - LiteLLM:DEBUG: utils.py:237 - original delta: {'content': '', 'function_call': None, 'role': None, 'tool_calls': None}
06:52:39 - LiteLLM:DEBUG: utils.py:237 - new delta: Delta(content='', role=None, function_call=None, tool_calls=None)
06:52:39 - LiteLLM:DEBUG: utils.py:237 - model_response.choices[0].delta: Delta(content='', role=None, function_call=None, tool_calls=None); completion_obj: {'content': ''}
06:52:39 - LiteLLM:DEBUG: utils.py:237 - self.sent_first_chunk: True
06:52:39 - LiteLLM:DEBUG: utils.py:237 - PROCESSED ASYNC CHUNK POST CHUNK CREATOR: ModelResponse(id='chat-f9bad6ec3c1146e99368682a0e7403fc', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='', role=None, function_call=None, tool_calls=None), logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='', bytes=[], logprob=-0.00018153927521780133, top_logprobs=[TopLogprob(token='', bytes=[], logprob=-0.00018153927521780133), TopLogprob(token='\n\n', bytes=[10, 10], logprob=-9.062681198120117)])]))], created=1721976759, model='Meta-Llama-3-8B-Instruct', object='chat.completion.chunk', system_fingerprint=None)
06:52:39 - LiteLLM:DEBUG: litellm_logging.py:576 - Logging Details LiteLLM-Success Call: Cache_hit=None
06:52:39 - LiteLLM:DEBUG: utils.py:237 - final returned processed chunk: ModelResponse(id='chat-f9bad6ec3c1146e99368682a0e7403fc', choices=[StreamingChoices(finish_reason=None, index=0, delta=Delta(content='', role=None, function_call=None, tool_calls=None), logprobs=ChoiceLogprobs(content=[ChatCompletionTokenLogprob(token='', bytes=[], logprob=-0.00018153927521780133, top_logprobs=[TopLogprob(token='', bytes=[], logprob=-0.00018153927521780133), TopLogprob(token='\n\n', bytes=[10, 10], logprob=-9.062681198120117)])]))], created=1721976759, model='Meta-Llama-3-8B-Instruct', object='chat.completion.chunk', system_fingerprint=None)
06:52:39 - LiteLLM:DEBUG: litellm_logging.py:587 - success callbacks: [<litellm.proxy.hooks.parallel_request_limiter._PROXY_MaxParallelRequestsHandler object at 0x7fe0a08f5b10>, <litellm.proxy.hooks.max_budget_limiter._PROXY_MaxBudgetLimiter object at 0x7fe0a0a0b950>, <litellm.proxy.hooks.cache_control_check._PROXY_CacheControlCheck object at 0x7fe0a08f5b50>, <litellm._service_logger.ServiceLogging object at 0x7fe09ff934d0>]
06:52:39 - LiteLLM Proxy:ERROR: proxy_server.py:2375 - litellm.proxy.proxy_server.async_data_generator(): Exception occured - Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2365, in async_data_generator
    chunk = chunk.model_dump_json(exclude_none=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 398, in model_dump_json
    return self.__pydantic_serializer__.to_json(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'

06:52:39 - LiteLLM Proxy:DEBUG: proxy_server.py:2385 - An error occurred: Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
06:52:39 - LiteLLM:DEBUG: utils.py:237 - Logging Details LiteLLM-Async Success Call
```

the curl sent is this:
```
curl --location 'http://0.0.0.0:4000/v1/chat/completions' \
-H 'Content-Type: application/json' \
-H "Authorization: Bearer $LITELLM_MASTER_KEY" \
-d '{
        "model": "Meta-Llama-3-8B-Instruct",
        "messages": [
          {
            "role": "system",
            "content": "You are a helpful assistant."
          },
          {
            "role": "user",
            "content": "Say 2 random words!"
          }
        ],
        "stream": true, 
        "logprobs": true, 
        "top_logprobs": 2
      }'

```

my litellm_config.yaml looks like this:
```
  - model_name: Meta-Llama-3-8B-Instruct  # user-facing model alias
    litellm_params:
      model: openai/Meta-Llama-3-8B-Instruct
      api_base: http://juju-vllm-meta-llama-3:8000/v1
    model_info: 
      metadata: "textgen"
```

**Comment by ghost** [comment]
Hey @JulietTeoh i was unable to repro, however  I: 

- set `exclude_unset=True` as suggested by this issue https://github.com/pydantic/pydantic/issues/7713 on pydantic
- added a new debug statement in async_data_gen to see what the actual chunk looks like before calling `.model_dump_json()` https://github.com/BerriAI/litellm/blob/1d6c39a6071b99c615b020e2adca34525923e011/litellm/proxy/proxy_server.py#L2374


Let me know if this fixes it! Please reopen/bump me if not!

**Comment by whalygood** [comment]
@krrishdholakia  Running into this issue again after upgrading to v1.44.22

```
litellm-octoai-1  | 15:51:33 - LiteLLM Proxy:ERROR: proxy_server.py:2598 - litellm.proxy.proxy_server.async_data_generator(): Exception occured - Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
litellm-octoai-1  | Traceback (most recent call last):
litellm-octoai-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2587, in async_data_generator
litellm-octoai-1  |     chunk = chunk.model_dump_json(exclude_none=True, exclude_unset=True)
litellm-octoai-1  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-octoai-1  |   File "/usr/local/lib/python3.11/site-packages/pydantic/main.py", line 398, in model_dump_json
litellm-octoai-1  |     return self.__pydantic_serializer__.to_json(
litellm-octoai-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-octoai-1  | pydantic_core._pydantic_core.PydanticSerializationError: Error serializing to JSON: TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
```

Contents of config.yaml is 

```
model_list:
  - model_name: meta-llama-3.1-70b-instruct
    litellm_params:
      model: openai/meta-llama-3.1-70b-instruct
      api_base: "https://text.octoai.run/v1"
      api_key: foo
      max_tokens: 4096
  - model_name: meta-llama-3.1-8b-instruct
    litellm_params:
      model: openai/meta-llama-3.1-8b-instruct
      api_base: "https://text.octoai.run/v1"
      api_key: foo
      max_tokens: 4096
  - model_name: meta-llama-3.1-405b-instruct
    litellm_params:
      model: openai/meta-llama-3.1-405b-instruct
      api_base: "https://text.octoai.run/v1"
      api_key: foo
      max_tokens: 4096

litellm_settings:
  drop_params: True
  set_verbose: True

general_settings:
  master_key: sk-1234
```

**Comment by liho00** [comment]
same issue here
