### ISSUE TITLE
[Bug]: Fix 400-status code streaming error message

### ISSUE THREAD

**Issue by ravi-katiyar** [BerriAI/litellm#4900]
### What happened?

I am using litellm as a proxy with my libre chat interface to build a chat bot using aws bedrock models. The anthropic haiku model is working fine. But I get a 400 error when using claude-3-5-sonnet model.

My Litellm config looks like this 

```
model_list:
  # https://litellm.vercel.app/docs/proxy/quick_start

  # AWS Bedrock - Anthropic
  - model_name: claude-3-haiku
    litellm_params:
      model: bedrock/anthropic.claude-3-haiku-20240307-v1:0
      aws_region_name: us-west-2
      aws_access_key_id: ...
      aws_secret_access_key: ...

  - model_name: sonnet
    litellm_params:
      model: bedrock/anthropic.claude-3-5-sonnet-20240620-v1:0
      aws_region_name: us-west-2
      aws_access_key_id: ...
      aws_secret_access_key: ...

litellm_settings:
  drop_params: true
```

### Relevant log output

```shell
INFO:     172.25.0.1:47332 - "POST /chat/completions HTTP/1.1" 200 OK

13:04:53 - LiteLLM Proxy:ERROR: proxy_server.py:2365 - litellm.proxy.proxy_server.async_data_generator(): Exception occured - litellm.BadRequestError: BedrockException - Client error '400 Bad Request' for url 'https://bedrock-runtime.us-west-2.amazonaws.com/model/anthropic.claude-3-5-sonnet-20240620-v1:0/converse-stream'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/bedrock_httpx.py", line 196, in make_call
    response = await client.post(api_base, headers=headers, data=data, stream=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 113, in post
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 90, in post
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://bedrock-runtime.us-west-2.amazonaws.com/model/anthropic.claude-3-5-sonnet-20240620-v1:0/converse-stream'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 9886, in __anext__
    await self.fetch_stream()
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 9876, in fetch_stream
    self.completion_stream = await self.make_call(
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/bedrock_httpx.py", line 215, in make_call
    raise BedrockError(status_code=error_code, message=str(err))
litellm.llms.bedrock.BedrockError: Client error '400 Bad Request' for url 'https://bedrock-runtime.us-west-2.amazonaws.com/model/anthropic.claude-3-5-sonnet-20240620-v1:0/converse-stream'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2348, in async_data_generator
    async for chunk in response:
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 10109, in __anext__
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 7873, in exception_type
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 6693, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: litellm.BadRequestError: BedrockException - Client error '400 Bad Request' for url 'https://bedrock-runtime.us-west-2.amazonaws.com/model/anthropic.claude-3-5-sonnet-20240620-v1:0/converse-stream'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
```

**Comment by ghost** [comment]
Hey @ravi-katiyar i suspect you might not have access to the model in that region. I'll update our error message to be more descriptive

**Comment by ghost** [comment]
Fixed our error message. Now you should see something like this - @ravi-katiyar 
<img width="1172" alt="Screenshot 2024-07-26 at 10 43 17 AM" src="https://github.com/user-attachments/assets/ed2b9a82-83e1-4e4f-b895-96693baa72d3">


i suspect if you made a non-streaming call to anthropic.claude-3-5-sonnet-20240620-v1:0, you'll see the error too
