### ISSUE TITLE
[Bug]: prisma cannot install in isolated environment

### ISSUE THREAD

**Issue by alecswan** [BerriAI/litellm#4915]
### What happened?

LiteLLM fails to start when run in an isolated environment, i.e. without internet access.
These are the two docker containers being used in my setup: litellm:v1.42.3-stable, postgres:16.3.

The root cause of the problem seems to be this part of the full log output which appears to be triggered from /usr/local/bin/prisma.
> urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
nodeenv installation failed; You may want to try installing `nodejs-bin` as it is more reliable.

I am not sure when this problem was introduced, but litellm:v1.40.9-stable docker container works fine.

### Relevant log output

```shell
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Installing Prisma CLI
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/local/lib/python3.11/http/client.py", line 1298, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1344, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1293, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.11/http/client.py", line 1052, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.11/http/client.py", line 990, in send
    self.connect()
  File "/usr/local/lib/python3.11/http/client.py", line 1463, in connect
    super().connect()
  File "/usr/local/lib/python3.11/http/client.py", line 956, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 851, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.11/socket.py", line 836, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/nodeenv.py", line 1548, in <module>
    main()
  File "/usr/local/lib/python3.11/site-packages/nodeenv.py", line 1119, in main
    args.node = get_last_stable_node_version()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nodeenv.py", line 1052, in get_last_stable_node_version
    return _get_versions_json()[0]['version'].lstrip('v')
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nodeenv.py", line 1028, in _get_versions_json
    response = urlopen('%s/index.json' % src_base_url)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/nodeenv.py", line 652, in urlopen
    return urllib2.urlopen(req)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 519, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 496, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
nodeenv installation failed; You may want to try installing `nodejs-bin` as it is more reliable.
Traceback (most recent call last):
  File "/usr/local/bin/prisma", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/cli/cli.py", line 39, in main
    sys.exit(prisma.run(args[1:]))
             ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/cli/prisma.py", line 36, in run
    entrypoint = ensure_cached().entrypoint
                 ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/cli/prisma.py", line 93, in ensure_cached
    proc = npm.run(
           ^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/_proxy.py", line 19, in __getattr__
    return getattr(self.__get_proxied__(), attr)
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/_proxy.py", line 35, in __get_proxied__
    self.__proxied = proxied = self.__load__()
                               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/cli/_node.py", line 406, in __load__
    return resolve(self.target)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/cli/_node.py", line 282, in resolve
    return NodeBinaryStrategy.resolve(target)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/cli/_node.py", line 161, in resolve
    return NodeBinaryStrategy.from_nodeenv(target)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/cli/_node.py", line 191, in from_nodeenv
    raise exc
  File "/usr/local/lib/python3.11/site-packages/prisma/cli/_node.py", line 174, in from_nodeenv
    subprocess.run(
  File "/usr/local/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/local/bin/python', '-m', 'nodeenv', '/root/.cache/prisma-python/nodeenv']' returned non-zero exit status 1.
INFO:     Started server process [1]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 873, in check_view_exists
    await self.db.query_raw(
  File "/usr/local/lib/python3.11/site-packages/prisma/client.py", line 421, in query_raw
    resp = await self._execute(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/client.py", line 525, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_response_errors(resp, errors_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/engine/utils.py", line 192, in handle_response_errors
    raise exc(error)
prisma.errors.RawQueryError: relation "LiteLLM_VerificationTokenView" does not exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 732, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 608, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 709, in startup
    await handler()
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2629, in startup_event
    create_view_response = await prisma_client.check_view_exists()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
    ret = await target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 879, in check_view_exists
    value = await self.health_check()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 1961, in health_check
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 1943, in health_check
    response = await self.db.query_raw(sql_query)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/client.py", line 421, in query_raw
    resp = await self._execute(
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/client.py", line 525, in _execute
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/engine/query.py", line 244, in query
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/engine/http.py", line 141, in request
    return utils.handle_response_errors(resp, errors_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/engine/utils.py", line 192, in handle_response_errors
    raise exc(error)
prisma.errors.RawQueryError: relation "LiteLLM_VerificationToken" does not exist

ERROR:    Application startup failed. Exiting.
```

**Comment by ghost** [comment]
hmm, i don't think there's been any changes to our build step either. Could this be related to a prisma version? @alecswan 

Any help debugging this would be appreciated

**Comment by ghost** [comment]
Can you try running the `litellm-database` dockerfile - https://github.com/BerriAI/litellm/pkgs/container/litellm-database

It pre-generates prisma, which i think might solve this issue

**Comment by alecswan** [comment]
@krrishdholakia, what Postgres versions are recommended to use with LiteLLM?

I tried running litellm-database:v1.42.4-stable without success. Please see the log attached 
[litellm-github-4915-litellm-database-1.42.4-log.txt](https://github.com/user-attachments/files/16401272/litellm-github-4915-litellm-database-1.42.4-log.txt)


The culprit, as before, appears to be

> urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>
> nodeenv installation failed; You may want to try installing `nodejs-bin` as it is more reliable.
> Traceback (most recent call last):
>   File "/usr/local/bin/prisma", line 8, in <module>
>     sys.exit(main())
>              ^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/prisma/cli/cli.py", line 39, in main
>     sys.exit(prisma.run(args[1:]))
>              ^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/lib/python3.11/site-packages/prisma/cli/prisma.py", line 36, in run
>     entrypoint = ensure_cached().entrypoint
>                  ^^^^^^^^^^^^^^^

>

**Comment by ghost** [comment]
>  File "/usr/local/lib/python3.11/site-packages/prisma/cli/prisma.py", line 36, in run
    entrypoint = ensure_cached().entrypoint
                 ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prisma/cli/prisma.py", line 93, in ensure_cached
    proc = npm.run(

it's weird - i'd assume `prisma generate` running in the dockerfile would ensure this is part of the docker image 

https://github.com/BerriAI/litellm/blob/c3ac6b098ee73a17baa63f3c6775d1c53e5d49ca/Dockerfile.database#L65

**Comment by ghost** [comment]
Hey @alecswan i was able to fix this by using litellm's dockerfile as a base image and running prisma generate as part of my dockerfile - 

```Dockerfile
# Use the provided base image
FROM ghcr.io/berriai/litellm:main-latest

# Set the working directory to /app
WORKDIR /app

### [👇 KEY STEP] ###
# Install Prisma CLI and generate Prisma client
RUN pip install prisma 
RUN prisma generate
### FIN #### 


# Expose the necessary port
EXPOSE 4000

# Override the CMD instruction with your desired command and arguments
# WARNING: FOR PROD DO NOT USE `--detailed_debug` it slows down response times, instead use the following CMD
# CMD ["--port", "4000", "--config", "config.yaml"]

# Define the command to run your app
ENTRYPOINT ["litellm"]

CMD ["--port", "4000"]
```

Docs: https://docs.litellm.ai/docs/proxy/deploy#litellm-without-internet-connection

---

This should be solved by dockerfile.database, but i was able to repro the same error as you. I'm unsure why the prisma generate files aren't stored correctly. It might be getting removed somehow. Any help debugging the issue would be great!

**Comment by karaketir16** [comment]
Dockerfile that you shared does not work for me, still gives the error. 

Probably latest stable version that does not give error is v1.41.2-stable. So I rollback to that version.

v1.42.0-stable gives that error.

**Comment by morandalex** [comment]
using virtual environment does not work

**Comment by ishaan-jaff** [comment]
+1 we had another user run into this, they had to fill the prisma migration engine and lib query engine for debian. 

Had to set a bunch of prisma env vars just to rollout

**Comment by yonghweee** [comment]
@ishaan-jaff hi, I ran into this issue again using v1.90.3. May I know what's the prisma env vars that were set? Also, for the prisma migration engine and lib query engine for debian, what needs to be set?
