### ISSUE TITLE
[Bug]: openai.openaiError: openai.openaiError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

### ISSUE THREAD

**Issue by royrajjyoti12** [BerriAI/litellm#4945]
### What happened?

I am using azure open ai still I am getting error to set the OPENAI_API_KEY environment variable

os.environ["AZURE_API_KEY"]= cred.api_key
os.environ["AZURE_API_BASE"]=cred.RESOURCE_ENDPOINT
os.environ["AZURE_API_VERSION"] = cred.api_version

litellm.set_verbose=True

from litellm import completion

response = completion(
    model = "gpt-4", 
    messages = [{ "content": "Hello, how are you?","role": "user"}]
)

### Relevant log output

```shell
Logging Details: logger_fn - None | callable(logger_fn) - False
Traceback (most recent call last):
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/llms/openai.py", line 963, in completion
    raise e
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/llms/openai.py", line 894, in completion
    openai_client = self._get_openai_client(
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/llms/openai.py", line 741, in _get_openai_client
    _new_client = OpenAI(
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/openai/_client.py", line 105, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/main.py", line 1360, in completion
    raise e
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/main.py", line 1333, in completion
    response = openai_chat_completions.completion(
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/llms/openai.py", line 971, in completion
    raise OpenAIError(status_code=500, message=traceback.format_exc())
litellm.llms.openai.OpenAIError: Traceback (most recent call last):
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/llms/openai.py", line 963, in completion
    raise e
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/llms/openai.py", line 894, in completion
    openai_client = self._get_openai_client(
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/llms/openai.py", line 741, in _get_openai_client
    _new_client = OpenAI(
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/openai/_client.py", line 105, in __init__
    raise OpenAIError(
openai.OpenAIError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Desktop/Route LLM/gpt_model_testing.py", line 20, in <module>
    response = completion(
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/utils.py", line 1022, in wrapper
    raise e
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/utils.py", line 902, in wrapper
    result = original_function(*args, **kwargs)
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/main.py", line 2648, in completion
    raise exception_type(
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/utils.py", line 8012, in exception_type
    raise e
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/utils.py", line 6349, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: litellm.AuthenticationError: AuthenticationError: OpenAIException - Traceback (most recent call last):
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/llms/openai.py", line 963, in completion
    raise e
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/llms/openai.py", line 894, in completion
    openai_client = self._get_openai_client(
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/llms/openai.py", line 741, in _get_openai_client
    _new_client = openai(
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/openai/_client.py", line 105, in __init__
    raise openaiError(
openai.openaiError: The api_key client option must be set either by passing api_key to the client or by setting the OPENAI_API_KEY environment variable


```

**Comment by ghost** [comment]
> model = "gpt-4",

your model name is incorrect. 

Pass in `model="azure/<your-deployment-name>"` instead 

Docs: https://docs.litellm.ai/docs/providers/azure#usage

**Comment by royrajjyoti12** [comment]
I tried but not working

`Logging Details: logger_fn - None | callable(logger_fn) - False
Traceback (most recent call last):
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/llms/azure.py", line 651, in completion
    response = azure_client.chat.completions.create(**data, timeout=timeout)  # type: ignore
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 646, in create
    return self._post(
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/openai/_base_client.py", line 1266, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/openai/_base_client.py", line 942, in request
    return self._request(
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/openai/_base_client.py", line 1046, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/main.py", line 1034, in completion
    response = azure_chat_completions.completion(
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/llms/azure.py", line 673, in completion
    raise AzureOpenAIError(status_code=e.status_code, message=str(e))
litellm.llms.azure.AzureOpenAIError: Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Desktop/Route LLM/gpt_model_testing.py", line 20, in <module>
    response = completion(
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/utils.py", line 1022, in wrapper
    raise e
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/utils.py", line 902, in wrapper
    result = original_function(*args, **kwargs)
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/main.py", line 2648, in completion
    raise exception_type(
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/utils.py", line 8012, in exception_type
    raise e
  File "/Users/Desktop/Route LLM/myenv/lib/python3.9/site-packages/litellm/utils.py", line 7846, in exception_type
    raise APIError(
litellm.exceptions.APIError: litellm.APIError: AzureException APIError - Error code: 404 - {'error': {'code': '404', 'message': 'Resource not found'}}`
