### ISSUE TITLE
[Bug]: httpcore.ConnectError: [Errno -2] Name or service not known on bedrock_httpx.py

### ISSUE THREAD

**Issue by Ichigo3766** [BerriAI/litellm#5038]
### What happened?

Hi, I just started getting errors after pulling the latest commits from last few days. I am using bedrock api. Used to work just fine.

### Relevant log output

```shell
"POST /completions HTTP/1.1" 200
litellm_1   | 22:03:26 - LiteLLM Proxy:ERROR: proxy_server.py:2409 - litellm.proxy.proxy_server.async_data_generator(): Exception occured - litellm.ServiceUnavailableError: BedrockException - [Errno -2] Name or service not known
litellm_1   | Traceback (most recent call last):
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
litellm_1   |     yield
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
litellm_1   |     resp = await self._pool.handle_async_request(req)
litellm_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
litellm_1   |     raise exc from None
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
litellm_1   |     response = await connection.handle_async_request(
litellm_1   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
litellm_1   |     raise exc
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
litellm_1   |     stream = await self._connect(request)
litellm_1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 122, in _connect
litellm_1   |     stream = await self._network_backend.connect_tcp(**kwargs)
litellm_1   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
litellm_1   |     return await self._backend.connect_tcp(
litellm_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
litellm_1   |     with map_exceptions(exc_map):
litellm_1   |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
litellm_1   |     self.gen.throw(typ, value, traceback)
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
litellm_1   |     raise to_exc(exc) from exc
litellm_1   | httpcore.ConnectError: [Errno -2] Name or service not known
litellm_1   | 
litellm_1   | The above exception was the direct cause of the following exception:
litellm_1   | 
litellm_1   | Traceback (most recent call last):
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/bedrock_httpx.py", line 206, in make_call
litellm_1   |     response = await client.post(
litellm_1   |                ^^^^^^^^^^^^^^^^^^
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 99, in post
litellm_1   |     return await self.single_connection_post_request(
litellm_1   |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
litellm_1   |     response = await self._send_handling_redirects(
litellm_1   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
litellm_1   |     response = await self._send_single_request(request)
litellm_1   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1763, in _send_single_request
litellm_1   |     response = await transport.handle_async_request(request)
litellm_1   |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
litellm_1   |     with map_httpcore_exceptions():
litellm_1   |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
litellm_1   |     self.gen.throw(typ, value, traceback)
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
litellm_1   |     raise mapped_exc(message) from exc
litellm_1   | httpx.ConnectError: [Errno -2] Name or service not known
litellm_1   | 
litellm_1   | During handling of the above exception, another exception occurred:
litellm_1   | 
litellm_1   | Traceback (most recent call last):
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 10252, in __anext__
litellm_1   |     await self.fetch_stream()
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 10236, in fetch_stream
litellm_1   |     self.completion_stream = await self.make_call(
litellm_1   |                              ^^^^^^^^^^^^^^^^^^^^^
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/bedrock_httpx.py", line 255, in make_call
litellm_1   |     raise BedrockError(status_code=500, message=str(e))
litellm_1   | litellm.llms.bedrock.BedrockError: [Errno -2] Name or service not known
litellm_1   | 
litellm_1   | During handling of the above exception, another exception occurred:
litellm_1   | 
litellm_1   | Traceback (most recent call last):
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2390, in async_data_generator
litellm_1   |     async for chunk in response:
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 10551, in __anext__
litellm_1   |     async for chunk in self.completion_stream:
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 436, in _async_streaming
litellm_1   |     raise e
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 432, in _async_streaming
litellm_1   |     async for line in response:
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 10483, in __anext__
litellm_1   |     raise exception_type(
litellm_1   |           ^^^^^^^^^^^^^^^
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 8168, in exception_type
litellm_1   |     raise e
litellm_1   |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 6967, in exception_type
litellm_1   |     raise ServiceUnavailableError(
litellm_1   | litellm.exceptions.ServiceUnavailableError: litellm.ServiceUnavailableError: BedrockException - [Errno -2] Name or service not known
```

**Comment by ghost** [comment]
hi @Ichigo3766 
- what version of litellm are you on?
- what does your config look like? 
- can you give me a curl to repro this? 
- can you run the proxy with `--detailed_debug` and share what the raw request from litellm looks like

This error looks like it's happening when litellm is trying to call bedrock 

> File "/usr/local/lib/python3.11/site-packages/litellm/llms/bedrock_httpx.py", line 206, in make_call
litellm_1   |     response = await client.post(
litellm_1   |                ^^^^^^^^^^^^^^^^^^

**Comment by ghost** [comment]
bump on this @Ichigo3766

**Comment by Ichigo3766** [comment]
Will be testing and report back soon hopefully. Have to rebuild since I went to older commit (mistral 2 release).

**Comment by ghost** [comment]
hi @Ichigo3766 following up on this?
