### ISSUE TITLE
[Bug]: Openrouter streaming fails

### ISSUE THREAD

**Issue by BearThreat** [BerriAI/litellm#5080]
### What happened?

It appears that litellm hasn't yet implemented streaming from Openrouter
litellm.exceptions.UnsupportedParamsError: litellm.UnsupportedParamsError: openrouter does not support parameters: {'stream': True}

### Relevant log output

```shell
from litellm import acompletion, completion
import asyncio, traceback
from dotenv import load_dotenv
load_dotenv()

class LLMEngine:
    def __init__(self):
        self.model = "openrouter/openai/gpt-4o-mini"
        # self.model = "openrouter/anthropic/claude-3.5-sonnet"
        # self.model = "gpt-4o-mini"

    async def get_response(self, user_message):
        messages = [{"content": user_message, "role": "user"}]
        response = await acompletion(model=self.model, messages=messages)
        return response
    
    def get_response_blocking_stream(self, user_message):
        messages = [{"content": user_message, "role": "user"}]
        response = completion(model=self.model, messages=messages, stream=True)
        for part in response:
            print(part.choices[0].delta.content or "")
    
    # add streaming support
    async def get_streaming_response(self, user_message):
        try:
            messages = [{"content": user_message, "role": "user"}]
            response = await acompletion(model=self.model, messages=messages, stream=True)
            async for part in response:
                print(part.choices[0].delta.content or "")
        except Exception as e:
            print(f"Error: {e}\n\nTraceback: {traceback.format_exc()}")
            return None


async def non_blocking_await():
    engine = LLMEngine()
    response = await engine.get_response("Hello")
    print(response)

def blocking_stream():
    engine = LLMEngine()
    response = engine.get_response_blocking_stream("Hello")

async def non_blocking_stream():
    # streaming response
    engine = LLMEngine()
    response = await engine.get_streaming_response("Hello")

if __name__ == "__main__":
    asyncio.run(non_blocking_await())
    print("*"*50)
    blocking_stream()
    print("*"*50)
    asyncio.run(non_blocking_stream())


ModelResponse(id='gen-aB2Fj7SYIrkh9L5iPXQ7Z3LjTqtF', choices=[Choices(finish_reason='stop', index=0, message=Message(content='Hello! How can I assist you today?', role='assistant', tool_calls=None, function_call=None))], created=1722994019, model='openrouter/openai/gpt-4o-mini', object='chat.completion', system_fingerprint='fp_48196bc67a', usage=Usage(completion_tokens=9, prompt_tokens=8, total_tokens=17), service_tier=None)
**************************************************
Traceback (most recent call last):
  File "/mnt/c/Users/BearThreat/Desktop/PromptChain/openrouter_stream_test.py", line 52, in <module>
    blocking_stream()
  File "/mnt/c/Users/BearThreat/Desktop/PromptChain/openrouter_stream_test.py", line 42, in blocking_stream
    response = engine.get_response_blocking_stream("Hello")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/Users/BearThreat/Desktop/PromptChain/openrouter_stream_test.py", line 19, in get_response_blocking_stream
    response = completion(model=self.model, messages=messages, stream=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bearwsl/miniconda3/envs/promptchain/lib/python3.11/site-packages/litellm/utils.py", line 1028, in wrapper
    raise e
  File "/home/bearwsl/miniconda3/envs/promptchain/lib/python3.11/site-packages/litellm/utils.py", line 908, in wrapper    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/bearwsl/miniconda3/envs/promptchain/lib/python3.11/site-packages/litellm/main.py", line 2761, in completion
    raise exception_type(
  File "/home/bearwsl/miniconda3/envs/promptchain/lib/python3.11/site-packages/litellm/main.py", line 927, in completion
    optional_params = get_optional_params(
                      ^^^^^^^^^^^^^^^^^^^^
  File "/home/bearwsl/miniconda3/envs/promptchain/lib/python3.11/site-packages/litellm/utils.py", line 3535, in get_optional_params
    _check_valid_arg(supported_params=supported_params)
  File "/home/bearwsl/miniconda3/envs/promptchain/lib/python3.11/site-packages/litellm/utils.py", line 2835, in _check_valid_arg
    raise UnsupportedParamsError(
litellm.exceptions.UnsupportedParamsError: litellm.UnsupportedParamsError: openrouter does not support parameters: {'stream': True}, for model=openai/gpt-4o-mini. To drop these, set `litellm.drop_params=True` or for proxy:

`litellm_settings:
 drop_params: true`
```

**Comment by ghost** [comment]
we do support streaming for openrouter

**Comment by ghost** [comment]
thanks for this issue - i'll see what caused the regression in optional param checking, and add a test for it
