### ISSUE TITLE
[Bug]: Tools + Streaming with Mistral Large

### ISSUE THREAD

**Issue by Clad3815** [BerriAI/litellm#5103]
### What happened?

I have this bug while streaming + tools call but i'm not sure about the problem. The same request work fine with all other providers 

### Relevant log output

```shell
litellm-1  | openai.UnprocessableEntityError: Error code: 422 - {'object': 'error', 'message': {'detail': [{'type': 'extra_forbidden', 'loc': ['body', 'messages', 2, 'assistant', 'tool_calls', 0, 'index'], 'msg': 'Extra inputs are not permitted', 'input': 0}]}, 'type': 'invalid_request_error', 'param': None, 'code': None}
litellm-1  | 
litellm-1  | During handling of the above exception, another exception occurred:
litellm-1  | 
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 401, in acompletion
litellm-1  |     response = await init_response
litellm-1  |                ^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/openai.py", line 1248, in async_streaming
litellm-1  |     if k not in invalid_params:
litellm-1  |        ^
litellm-1  | UnboundLocalError: cannot access local variable 'invalid_params' where it is not associated with a value
litellm-1  | 
litellm-1  | During handling of the above exception, another exception occurred:
litellm-1  | 
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 3032, in chat_completion
litellm-1  |     responses = await llm_responses
litellm-1  |                 ^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 674, in acompletion
litellm-1  |     raise e
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 662, in acompletion
litellm-1  |     response = await self.async_function_with_fallbacks(**kwargs)
litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2538, in async_function_with_fallbacks
litellm-1  |     raise original_exception
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2357, in async_function_with_fallbacks
litellm-1  |     response = await self.async_function_with_retries(*args, **kwargs)
litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2653, in async_function_with_retries
litellm-1  |     raise original_exception
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2575, in async_function_with_retries
litellm-1  |     response = await original_function(*args, **kwargs)
litellm-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 807, in _acompletion
litellm-1  |     raise e
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 779, in _acompletion
litellm-1  |     response = await _response
litellm-1  |                ^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1580, in wrapper_async
litellm-1  |     raise e
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1400, in wrapper_async
litellm-1  |     result = await original_function(*args, **kwargs)
litellm-1  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 424, in acompletion
litellm-1  |     raise exception_type(
litellm-1  |           ^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 8292, in exception_type
litellm-1  |     raise e  # it's already mapped
litellm-1  |     ^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 6713, in exception_type
litellm-1  |     raise APIConnectionError(
litellm-1  | litellm.exceptions.APIConnectionError: litellm.APIConnectionError: APIConnectionError: MistralException - cannot access local variable 'invalid_params' where it is not associated with a value
litellm-1  | Received Model Group=mistral/mistral-large-latest
litellm-1  | Available Model Group Fallbacks=None LiteLLM Retried: 2 times, LiteLLM Max Retries: 3
```

**Comment by ghost** [comment]
Hey @Clad3815 unable to repro this - i send an assistant message with tool_calls and it works. Can you share a call/script for repro? 

```python
from openai import OpenAI, AzureOpenAI, AsyncOpenAI
from datetime import datetime
import json

import openai
client = openai.OpenAI(
    api_key="sk-1234",
    base_url="http://0.0.0.0:4000"
)
# Simulate the order_id and delivery_date
order_id = "order_12345"
delivery_date = datetime.now()

# Simulate the tool call response
response = {
    "choices": [
        {
            "message": {
                "tool_calls": [
                    {"id": "toolcall1", "type": "function", "function": {
                        "name": "get_delivery_date",
                        "arguments": '{"order_id":"order_12345"}'
                    }}
                ]
            }
        }
    ]
}

# Create a message containing the result of the function call
function_call_result_message = {
    "role": "tool",
    "content": json.dumps({
        "order_id": order_id,
        "delivery_date": delivery_date.strftime('%Y-%m-%d %H:%M:%S')
    }),
    "tool_call_id": response['choices'][0]['message']['tool_calls'][0]['id']
}

# Prepare the chat completion call payload
completion_payload = {
    "model": "mistral/mistral-large-latest",
    "messages": [
        {"role": "system", "content": "You are a helpful customer support assistant. Use the supplied tools to assist the user."},
        {"role": "user", "content": "Hi, can you tell me the delivery date for my order?"},
        {"role": "assistant", "content": "Hi there! I can help with that. Can you please provide your order ID?"},
        {"role": "user", "content": "i think it is order_12345"},
        {"role": "assistant", **response['choices'][0]['message']},
        function_call_result_message
    ]
}

# Call the OpenAI API's chat completions endpoint to send the tool call result back to the model
response = client.chat.completions.create(
    model=completion_payload["model"],
    messages=completion_payload["messages"]
)

# Print the response from the API. In this case it will typically contain a message such as "The delivery date for your order #12345 is xyz. Is there anything else I can help you with?"
print(response)
```

Result: 
```
ChatCompletion(id='d1ae174f69b347bcae751c4aa779f629', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='Your order with ID order_12345 is scheduled to be delivered on August 10, 2024, at 09:42 AM.', refusal=None, role='assistant', function_call=None, tool_calls=None))], created=1723308138, model='mistral/mistral-large-latest', object='chat.completion', service_tier=None, system_fingerprint=None, usage=CompletionUsage(completion_tokens=37, prompt_tokens=162, total_tokens=199))
```

**Comment by Clad3815** [comment]
The problem is only while streaming, and when sending back the assistant message as we get for the tool_result call. I will try to give a code to reproduce

**Comment by Clad3815** [comment]
I mean sending back the assistant message we got from the API for the tool result, not creating an object ourself

**Comment by ghost** [comment]
> The problem is only while streaming, and when sending back the assistant message as we get for the tool_result call. I will try to give a code to reproduce


I tried my script with `stream=True` and that worked as well

**Comment by ghost** [comment]
> I mean sending back the assistant message we got from the API for the tool result, not creating an object ourself

Yup - i was following the openai example of mocking it, for testing
