### ISSUE TITLE
[Bug]: Groq stream tokenizer first request

### ISSUE THREAD

**Issue by Clad3815** [BerriAI/litellm#5104]
### What happened?

The first time we build the docker and run a groq model this error happen. I'm using `stream_options: { "include_usage": true }`

### Relevant log output

```shell
litellm-1  | 09:08:07 - LiteLLM Proxy:ERROR: proxy_server.py:2439 - litellm.proxy.proxy_server.async_data_generator(): Exception occured - list index out of range
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 10453, in __anext__
litellm-1  |     raise StopAsyncIteration
litellm-1  | StopAsyncIteration
litellm-1  | 
litellm-1  | During handling of the above exception, another exception occurred:
litellm-1  | 
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2418, in async_data_generator
litellm-1  |     async for chunk in response:
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 10501, in __anext__
litellm-1  |     complete_streaming_response = litellm.stream_chunk_builder(
litellm-1  |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 5010, in stream_chunk_builder
litellm-1  |     if chunks[0]._hidden_params.get("created_at", None):
litellm-1  |        ~~~~~~^^^
litellm-1  | IndexError: list index out of range
litellm-1  | 
Downloading tokenizer.json: 100%|██████████| 9.08M/9.08M [00:00<00:00, 13.9MB/s]
```

**Comment by ishaan-jaff** [comment]
what model did you try with @Clad3815 ?

**Comment by Clad3815** [comment]
@ishaan-jaff llama 3.1 70B Versatile, litellm in docker

**Comment by ishaan-jaff** [comment]
can i see a curl request to repro

**Comment by ghost** [comment]
Looks like we should safely fail if stream usage calculation doesn't work

**Comment by ghost** [comment]
working w/ pr 
<img width="1211" alt="Screenshot 2024-08-10 at 10 19 19 AM" src="https://github.com/user-attachments/assets/57d9fccc-d38c-4c62-a821-50fe6c8483b7">
