### ISSUE TITLE
[Bug]: Ollama proxy crashes when tools are not called

### ISSUE THREAD

**Issue by vertrue** [BerriAI/litellm#5160]
### What happened?

I am trying to call tools in ollama using langchain
when tools are not called (I guess) it crashes

tools are:
```
@tool("function_1")
def basic_tool_calling_tool_1(a: int, b: int) -> int:
    """uses function function_1 for arguments a and b."""
    return a * b

@tool("function_2")
def basic_tool_calling_tool_2(a: int, b: int) -> int:
    """uses function function_2 for arguments a and b."""
    return a // b
```

langchain logs are:
```
[llm/start] [chain:LangGraph > chain:runner > chain:AgentExecutor > chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a platform for code commenting and migration who can call tools\nHuman: What is function_1(10, 11)? Also what is function_2(10, 11)?"
  ]
}
[llm/end] [chain:LangGraph > chain:runner > chain:AgentExecutor > chain:RunnableSequence > llm:ChatOpenAI] [5.59s] Exiting LLM run with output:
{
  "generations": [
    [
      {
        "text": "",
        "generation_info": {
          "finish_reason": "tool_calls",
          "model_name": "llama3:70b"
        },
        "type": "ChatGenerationChunk",
        "message": {
          "lc": 1,
          "type": "constructor",
          "id": [
            "langchain",
            "schema",
            "messages",
            "AIMessageChunk"
          ],
          "kwargs": {
            "content": "",
            "additional_kwargs": {
              "tool_calls": [
                {
                  "index": 0,
                  "id": "call_a2fc9def-8456-4f0b-8449-781d4f287de1",
                  "function": {
                    "arguments": "{\"a\": 10, \"b\": 11}",
                    "name": "function_1"
                  },
                  "type": "function"
                }
              ]
            },
            "response_metadata": {
              "finish_reason": "tool_calls",
              "model_name": "llama3:70b"
            },
            "type": "AIMessageChunk",
            "id": "run-4d258804-514d-4d66-a2ea-0a5a9ac89eed",
            "tool_calls": [
              {
                "name": "function_1",
                "args": {
                  "a": 10,
                  "b": 11
                },
                "id": "call_a2fc9def-8456-4f0b-8449-781d4f287de1",
                "type": "tool_call"
              }
            ],
            "tool_call_chunks": [
              {
                "name": "function_1",
                "args": "{\"a\": 10, \"b\": 11}",
                "id": "call_a2fc9def-8456-4f0b-8449-781d4f287de1",
                "index": 0,
                "type": "tool_call_chunk"
              }
            ],
            "invalid_tool_calls": []
          }
        }
      }
    ]
  ],
  "llm_output": null,
  "run": null
}
[chain/start] [chain:LangGraph > chain:runner > chain:AgentExecutor > chain:RunnableSequence > parser:OpenAIToolsAgentOutputParser] Entering Parser run with input:
[inputs]
[chain/end] [chain:LangGraph > chain:runner > chain:AgentExecutor > chain:RunnableSequence > parser:OpenAIToolsAgentOutputParser] [0ms] Exiting Parser run with output:
[outputs]
[chain/end] [chain:LangGraph > chain:runner > chain:AgentExecutor > chain:RunnableSequence] [5.60s] Exiting Chain run with output:
[outputs]
[tool/start] [chain:LangGraph > chain:runner > chain:AgentExecutor > tool:function_1] Entering Tool run with input:
"{'a': 10, 'b': 11}"
[tool/end] [chain:LangGraph > chain:runner > chain:AgentExecutor > tool:function_1] [0ms] Exiting Tool run with output:
"110"
[chain/start] [chain:LangGraph > chain:runner > chain:AgentExecutor > chain:RunnableSequence] Entering Chain run with input:
{
  "input": ""
}
[chain/start] [chain:LangGraph > chain:runner > chain:AgentExecutor > chain:RunnableSequence > chain:RunnableAssign<agent_scratchpad>] Entering Chain run with input:
{
  "input": ""
}
[chain/start] [chain:LangGraph > chain:runner > chain:AgentExecutor > chain:RunnableSequence > chain:RunnableAssign<agent_scratchpad> > chain:RunnableParallel<agent_scratchpad>] Entering Chain run with input:
{
  "input": ""
}
[chain/start] [chain:LangGraph > chain:runner > chain:AgentExecutor > chain:RunnableSequence > chain:RunnableAssign<agent_scratchpad> > chain:RunnableParallel<agent_scratchpad> > chain:RunnableLambda] Entering Chain run with input:
{
  "input": ""
}
[chain/end] [chain:LangGraph > chain:runner > chain:AgentExecutor > chain:RunnableSequence > chain:RunnableAssign<agent_scratchpad> > chain:RunnableParallel<agent_scratchpad> > chain:RunnableLambda] [0ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:LangGraph > chain:runner > chain:AgentExecutor > chain:RunnableSequence > chain:RunnableAssign<agent_scratchpad> > chain:RunnableParallel<agent_scratchpad>] [1ms] Exiting Chain run with output:
[outputs]
[chain/end] [chain:LangGraph > chain:runner > chain:AgentExecutor > chain:RunnableSequence > chain:RunnableAssign<agent_scratchpad>] [3ms] Exiting Chain run with output:
[outputs]
[chain/start] [chain:LangGraph > chain:runner > chain:AgentExecutor > chain:RunnableSequence > prompt:ChatPromptTemplate] Entering Prompt run with input:
[inputs]
[chain/end] [chain:LangGraph > chain:runner > chain:AgentExecutor > chain:RunnableSequence > prompt:ChatPromptTemplate] [0ms] Exiting Prompt run with output:
[outputs]
[llm/start] [chain:LangGraph > chain:runner > chain:AgentExecutor > chain:RunnableSequence > llm:ChatOpenAI] Entering LLM run with input:
{
  "prompts": [
    "System: You are a platform for code commenting and migration who can call tools\nHuman: What is function_1(10, 11)? Also what is function_2(10, 11)?\nAI: \nTool: 110"
  ]
}
```

and it crashed. output with error is bellow:

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/yvitruk/Desktop/genbee/src/backend/benchmark/main.py", line 12, in <module>
    file_graph.app.invoke(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 1624, in invoke
    for chunk in self.stream(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 1110, in stream
    _panic_or_proceed(done, inflight, step)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langgraph/pregel/__init__.py", line 1713, in _panic_or_proceed
    raise exc
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langgraph/pregel/retry.py", line 72, in run_with_retry
    task.proc.invoke(task.input, task.config)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 2876, in invoke
    input = context.run(step.invoke, input, config, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langgraph/utils.py", line 103, in invoke
    ret = context.run(self.func, input, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yvitruk/Desktop/genbee/src/backend/benchmark/agents/runner.py", line 25, in execute_runner
    agent_result = agent.invoke({"input": prompt})["output"]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain/chains/base.py", line 166, in invoke
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain/chains/base.py", line 156, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain/agents/agent.py", line 1612, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain/agents/agent.py", line 1318, in _take_next_step
    [
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain/agents/agent.py", line 1346, in _iter_next_step
    output = self.agent.plan(
             ^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain/agents/agent.py", line 580, in plan
    for chunk in self.runnable.stream(inputs, config={"callbacks": callbacks}):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 3262, in stream
    yield from self.transform(iter([input]), config, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 3249, in transform
    yield from self._transform_stream_with_config(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 2054, in _transform_stream_with_config
    chunk: Output = context.run(next, iterator)  # type: ignore
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 3211, in _transform
    for output in final_pipeline:
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 1272, in transform
    for ichunk in input:
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 5301, in transform
    yield from self.bound.transform(
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain_core/runnables/base.py", line 1290, in transform
    yield from self.stream(final, config, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 418, in stream
    raise e
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain_core/language_models/chat_models.py", line 398, in stream
    for chunk in self._stream(messages, stop=stop, **kwargs):
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/langchain_openai/chat_models/base.py", line 524, in _stream
    for chunk in response:
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openai/_streaming.py", line 46, in __iter__
    for item in self._iterator:
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/openai/_streaming.py", line 72, in __stream__
    raise APIError(
openai.APIError: 'name'

Traceback (most recent call last):
  File "/usr/local/pyenv/versions/3.12.2/envs/3.12.2_litellm/lib/python3.12/site-packages/litellm/proxy/proxy_server.py", line 2358, in async_data_generator
    async for chunk in response:
  File "/usr/local/pyenv/versions/3.12.2/envs/3.12.2_litellm/lib/python3.12/site-packages/litellm/llms/ollama.py", line 432, in ollama_async_streaming
    raise e
  File "/usr/local/pyenv/versions/3.12.2/envs/3.12.2_litellm/lib/python3.12/site-packages/litellm/llms/ollama.py", line 410, in ollama_async_streaming
    "name": function_call["name"],
            ~~~~~~~~~~~~~^^^^^^^^
KeyError: 'name'
```

**Comment by ghost** [comment]
@vertrue tool calling with ollama is on their chat completion endpoint. use `ollama_chat/` for this. 

See example - https://docs.litellm.ai/docs/providers/ollama#example-usage---tool-calling

**Comment by synacktraa** [comment]
> @vertrue tool calling with ollama is on their chat completion endpoint. use `ollama_chat/` for this.
> 
> See example - https://docs.litellm.ai/docs/providers/ollama#example-usage---tool-calling

I checked the json file, it doesn't include any `ollama_chat/<model-name>`, so the `supports_function_calling` also returns False.
```
Exception: Model not in model_prices_and_context_window.json. You passed model=ollama_chat/mistral-nemo.
```
When called through `.completion` - first of all it takes more time compared to just calling it through ollama python api and second is that it always fails - 

```
ges\litellm\llms\ollama_chat.py", line 324, in get_ollama_response
    "name": function_call["name"],
KeyError: 'name'
```
