### ISSUE TITLE
[Bug]: 500 error with LiteLLM proxy and Sagemaker using mpt-7b-instruct model

### ISSUE THREAD

**Issue by gitravin** [BerriAI/litellm#5175]
### What happened?

Deployed mpt-7b-instruct model to sagemaker and inference works through LiteLLM for completions API. However we get 500 errors if the "stream" parameter is set as true.

Request

curl '<litellm endpoint>'   -H "Content-Type: application/json"  -H "Cache-Control: no-cache"  -d '{"model": "mpt-instruct-7b","messages": [{"role":"user","content":"what is the distance between NYC and Boston?"}],"temperature": 0.2,"top_p": 0.7,"max_tokens": 1024, "stream": true }'

Response

data: {"error": {"message": "litellm.APIConnectionError: Extra data: line 1 column 8 (char 7)\nTraceback (most recent call last):\n  File \"/usr/local/lib/python3.11/site-packages/litellm/utils.py\", line 10156, in __anext__\n    async for chunk in self.completion_stream:\n  File \"/usr/local/lib/python3.11/site-packages/litellm/llms/sagemaker.py\", line 84, in __anext__\n    line_data = json.loads(full_line.lstrip(\"data:\").rstrip(\"/n\"))\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/__init__.py\", line 346, in loads\n    return _default_decoder.decode(s)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/local/lib/python3.11/json/decoder.py\", line 340, in decode\n    raise JSONDecodeError(\"Extra data\", s, end)\njson.decoder.JSONDecodeError: Extra data: line 1 column 8 (char 7)\n", "type": null, "param": null, "code": 500}}

### Relevant log output

```shell
02:09:50 - LiteLLM Proxy:DEBUG: proxy_server.py:2795 - Request received by LiteLLM:
{
    "model": "mpt-instruct-7b",
    "messages": [
        {
            "role": "user",
            "content": "what is the distance between NYC and Boston?"
        }
    ],
    "temperature": 0.2,
    "top_p": 0.7,
    "max_tokens": 1024,
    "stream": true
}
02:09:50 - LiteLLM Proxy:DEBUG: litellm_pre_call_utils.py:95 - Request Headers: Headers({'host': '<lite llm endpoint>', 'user-agent': 'curl/8.6.0', 'accept': '*/*', 'content-type': 'application/json', 'cache-control': 'no-cache', 'content-length': '183', 'x-forwarded-for': '10.105.1.254', 'x-forwarded-proto': 'http', 'x-envoy-internal': 'true', 'x-request-id': '91b02dab-040f-4832-a8a0-32982bbad0cf', 'x-envoy-expected-rq-timeout-ms': '300000', 'l5d-dst-override': 'lite-llm.infra-dev.svc.cluster.local:4000', 'x-request-start': 't=1723514990.004', 'l5d-client-id': 'contour-envoy.public.serviceaccount.identity.linkerd.cluster.local'})
02:09:50 - LiteLLM Proxy:DEBUG: litellm_pre_call_utils.py:101 - receiving data: {'model': 'mpt-instruct-7b', 'messages': [{'role': 'user', 'content': 'what is the distance between NYC and Boston?'}], 'temperature': 0.2, 'top_p': 0.7, 'max_tokens': 1024, 'stream': True, 'proxy_server_request': {'url': 'http://<lite llm endpoint>/v1/chat/completions', 'method': 'POST', 'headers': {'host': '<lite llm endpoint>', 'user-agent': 'curl/8.6.0', 'accept': '*/*', 'content-type': 'application/json', 'cache-control': 'no-cache', 'content-length': '183', 'x-forwarded-for': '10.105.1.254', 'x-forwarded-proto': 'http', 'x-envoy-internal': 'true', 'x-request-id': '91b02dab-040f-4832-a8a0-32982bbad0cf', 'x-envoy-expected-rq-timeout-ms': '300000', 'l5d-dst-override': 'lite-llm.infra-dev.svc.cluster.local:4000', 'x-request-start': 't=1723514990.004', 'l5d-client-id': 'contour-envoy.public.serviceaccount.identity.linkerd.cluster.local'}, 'body': {'model': 'mpt-instruct-7b', 'messages': [{'role': 'user', 'content': 'what is the distance between NYC and Boston?'}], 'temperature': 0.2, 'top_p': 0.7, 'max_tokens': 1024, 'stream': True}}, 'ttl': None}
02:09:50 - LiteLLM Proxy:DEBUG: utils.py:73 - Inside Proxy Logging Pre-call hook!
NoneType: None

02:09:50 - LiteLLM Proxy:DEBUG: parallel_request_limiter.py:24 - Inside Max Parallel Request Pre-Call Hook
02:09:50 - LiteLLM:DEBUG: caching.py:29 - get cache: cache key: None_user_api_key_user_id; local_only: False
02:09:50 - LiteLLM:DEBUG: caching.py:29 - get cache: cache result: None
02:09:50 - LiteLLM:DEBUG: utils.py:237 - Initialized litellm callbacks, Async Success Callbacks: [<bound method Router.deployment_callback_on_success of <litellm.router.Router object at 0x7ff2778d1610>>, <litellm.proxy.hooks.parallel_request_limiter._PROXY_MaxParallelRequestsHandler object at 0x7ff276585410>, <litellm.proxy.hooks.max_budget_limiter._PROXY_MaxBudgetLimiter object at 0x7ff276585450>, <litellm.proxy.hooks.cache_control_check._PROXY_CacheControlCheck object at 0x7ff276ff0d50>, <litellm._service_logger.ServiceLogging object at 0x7ff275c364d0>, <bound method SlackAlerting.response_taking_too_long_callback of <litellm.integrations.slack_alerting.SlackAlerting object at 0x7ff276620050>>]
02:09:50 - LiteLLM:DEBUG: litellm_logging.py:205 - self.optional_params: {}
02:09:50 - LiteLLM Router:DEBUG: router.py:2507 - Inside async function with retries: args - (); kwargs - {'temperature': 0.2, 'top_p': 0.7, 'max_tokens': 1024, 'proxy_server_request': {'url': 'http://<lite llm endpoint>/v1/chat/completions', 'method': 'POST', 'headers': {'host': '<lite llm endpoint>', 'user-agent': 'curl/8.6.0', 'accept': '*/*', 'content-type': 'application/json', 'cache-control': 'no-cache', 'content-length': '183', 'x-forwarded-for': '10.105.1.254', 'x-forwarded-proto': 'http', 'x-envoy-internal': 'true', 'x-request-id': '91b02dab-040f-4832-a8a0-32982bbad0cf', 'x-envoy-expected-rq-timeout-ms': '300000', 'l5d-dst-override': 'lite-llm.infra-dev.svc.cluster.local:4000', 'x-request-start': 't=1723514990.004', 'l5d-client-id': 'contour-envoy.public.serviceaccount.identity.linkerd.cluster.local'}, 'body': {'model': 'mpt-instruct-7b', 'messages': [{'role': 'user', 'content': 'what is the distance between NYC and Boston?'}], 'temperature': 0.2, 'top_p': 0.7, 'max_tokens': 1024, 'stream': True}}, 'ttl': None, 'metadata': {'user_api_key': None, 'user_api_key_alias': None, 'user_api_end_user_max_budget': None, 'litellm_api_version': '1.42.3', 'global_max_parallel_requests': None, 'user_api_key_user_id': None, 'user_api_key_org_id': None, 'user_api_key_team_id': None, 'user_api_key_team_alias': None, 'user_api_key_team_max_budget': None, 'user_api_key_team_spend': None, 'user_api_key_spend': 0.0, 'user_api_key_max_budget': None, 'user_api_key_metadata': {}, 'headers': {'host': '<lite llm endpoint>', 'user-agent': 'curl/8.6.0', 'accept': '*/*', 'content-type': 'application/json', 'cache-control': 'no-cache', 'content-length': '183', 'x-forwarded-for': '10.105.1.254', 'x-forwarded-proto': 'http', 'x-envoy-internal': 'true', 'x-request-id': '91b02dab-040f-4832-a8a0-32982bbad0cf', 'x-envoy-expected-rq-timeout-ms': '300000', 'l5d-dst-override': 'lite-llm.infra-dev.svc.cluster.local:4000', 'x-request-start': 't=1723514990.004', 'l5d-client-id': 'contour-envoy.public.serviceaccount.identity.linkerd.cluster.local'}, 'endpoint': 'http://<lite llm endpoint>/v1/chat/completions', 'requester_ip_address': '', 'litellm_parent_otel_span': None, 'model_group': 'mpt-instruct-7b'}, 'request_timeout': 600, 'litellm_call_id': '388e449a-0e37-4073-913e-e917b182fdec', 'litellm_logging_obj': <litellm.litellm_core_utils.litellm_logging.Logging object at 0x7ff270c25750>, 'model': 'mpt-instruct-7b', 'messages': [{'role': 'user', 'content': 'what is the distance between NYC and Boston?'}], 'stream': True, 'original_function': <bound method Router._acompletion of <litellm.router.Router object at 0x7ff2778d1610>>, 'num_retries': 2}
02:09:50 - LiteLLM Router:DEBUG: router.py:2521 - async function w/ retries: original_function - <bound method Router._acompletion of <litellm.router.Router object at 0x7ff2778d1610>>, num_retries - 2
02:09:50 - LiteLLM Router:DEBUG: router.py:676 - Inside _acompletion()- model: mpt-instruct-7b; kwargs: {'temperature': 0.2, 'top_p': 0.7, 'max_tokens': 1024, 'proxy_server_request': {'url': 'http://<lite llm endpoint>/v1/chat/completions', 'method': 'POST', 'headers': {'host': '<lite llm endpoint>', 'user-agent': 'curl/8.6.0', 'accept': '*/*', 'content-type': 'application/json', 'cache-control': 'no-cache', 'content-length': '183', 'x-forwarded-for': '10.105.1.254', 'x-forwarded-proto': 'http', 'x-envoy-internal': 'true', 'x-request-id': '91b02dab-040f-4832-a8a0-32982bbad0cf', 'x-envoy-expected-rq-timeout-ms': '300000', 'l5d-dst-override': 'lite-llm.infra-dev.svc.cluster.local:4000', 'x-request-start': 't=1723514990.004', 'l5d-client-id': 'contour-envoy.public.serviceaccount.identity.linkerd.cluster.local'}, 'body': {'model': 'mpt-instruct-7b', 'messages': [{'role': 'user', 'content': 'what is the distance between NYC and Boston?'}], 'temperature': 0.2, 'top_p': 0.7, 'max_tokens': 1024, 'stream': True}}, 'ttl': None, 'metadata': {'user_api_key': None, 'user_api_key_alias': None, 'user_api_end_user_max_budget': None, 'litellm_api_version': '1.42.3', 'global_max_parallel_requests': None, 'user_api_key_user_id': None, 'user_api_key_org_id': None, 'user_api_key_team_id': None, 'user_api_key_team_alias': None, 'user_api_key_team_max_budget': None, 'user_api_key_team_spend': None, 'user_api_key_spend': 0.0, 'user_api_key_max_budget': None, 'user_api_key_metadata': {}, 'headers': {'host': '<lite llm endpoint>', 'user-agent': 'curl/8.6.0', 'accept': '*/*', 'content-type': 'application/json', 'cache-control': 'no-cache', 'content-length': '183', 'x-forwarded-for': '10.105.1.254', 'x-forwarded-proto': 'http', 'x-envoy-internal': 'true', 'x-request-id': '91b02dab-040f-4832-a8a0-32982bbad0cf', 'x-envoy-expected-rq-timeout-ms': '300000', 'l5d-dst-override': 'lite-llm.infra-dev.svc.cluster.local:4000', 'x-request-start': 't=1723514990.004', 'l5d-client-id': 'contour-envoy.public.serviceaccount.identity.linkerd.cluster.local'}, 'endpoint': 'http://<lite llm endpoint>/v1/chat/completions', 'requester_ip_address': '', 'litellm_parent_otel_span': None, 'model_group': 'mpt-instruct-7b'}, 'request_timeout': 600, 'litellm_call_id': '388e449a-0e37-4073-913e-e917b182fdec', 'litellm_logging_obj': <litellm.litellm_core_utils.litellm_logging.Logging object at 0x7ff270c25750>, 'stream': True}
02:09:50 - LiteLLM:DEBUG: main.py:4917 - initial list of deployments: [{'model_name': 'mpt-instruct-7b', 'litellm_params': {'model': 'sagemaker/mpt-instruct-deployment-2024-08-12-21-05-56-889'}, 'model_info': {'id': 'ddc28aec1118be274fa9cde3cb89949bdd5bcf69a60b29f64f21b4dec8818a93', 'db_model': False}}]
02:09:50 - LiteLLM:DEBUG: caching.py:29 - async get cache: cache key: 02-09:cooldown_models; local_only: False
02:09:50 - LiteLLM:DEBUG: caching.py:29 - in_memory_result: None
02:09:50 - LiteLLM:DEBUG: caching.py:29 - get cache: cache result: None
02:09:50 - LiteLLM Router:DEBUG: router.py:3304 - retrieve cooldown models: []
02:09:50 - LiteLLM Router:DEBUG: router.py:4469 - async cooldown deployments: []
02:09:50 - LiteLLM:DEBUG: caching.py:29 - get cache: cache key: ddc28aec1118be274fa9cde3cb89949bdd5bcf69a60b29f64f21b4dec8818a93; local_only: True
02:09:50 - LiteLLM:DEBUG: caching.py:29 - get cache: cache result: None
02:09:50 - LiteLLM:DEBUG: caching.py:29 - set cache: key: ddc28aec1118be274fa9cde3cb89949bdd5bcf69a60b29f64f21b4dec8818a93; value: 1
02:09:50 - LiteLLM:DEBUG: caching.py:29 - InMemoryCache: set_cache. current size= 6
02:09:50 - LiteLLM:DEBUG: caching.py:29 - get cache: cache key: ddc28aec1118be274fa9cde3cb89949bdd5bcf69a60b29f64f21b4dec8818a93_stream_async_client; local_only: True
02:09:50 - LiteLLM:DEBUG: caching.py:29 - get cache: cache result: None
02:09:50 - LiteLLM:DEBUG: caching.py:29 - get cache: cache key: ddc28aec1118be274fa9cde3cb89949bdd5bcf69a60b29f64f21b4dec8818a93_stream_async_client; local_only: True
02:09:50 - LiteLLM:DEBUG: caching.py:29 - get cache: cache result: None
02:09:50 - LiteLLM:DEBUG: caching.py:29 - get cache: cache key: ddc28aec1118be274fa9cde3cb89949bdd5bcf69a60b29f64f21b4dec8818a93_max_parallel_requests_client; local_only: True
02:09:50 - LiteLLM:DEBUG: caching.py:29 - get cache: cache result: None
02:09:50 - LiteLLM:DEBUG: utils.py:237 -

02:09:50 - LiteLLM:DEBUG: utils.py:237 - Request to litellm:
02:09:50 - LiteLLM:DEBUG: utils.py:237 - litellm.acompletion(model='sagemaker/mpt-instruct-deployment-2024-08-12-21-05-56-889', messages=[{'role': 'user', 'content': 'what is the distance between NYC and Boston?'}], caching=False, client=None, timeout=6000, temperature=0.2, top_p=0.7, max_tokens=1024, proxy_server_request={'url': 'http://<lite llm endpoint>/v1/chat/completions', 'method': 'POST', 'headers': {'host': '<lite llm endpoint>', 'user-agent': 'curl/8.6.0', 'accept': '*/*', 'content-type': 'application/json', 'cache-control': 'no-cache', 'content-length': '183', 'x-forwarded-for': '10.105.1.254', 'x-forwarded-proto': 'http', 'x-envoy-internal': 'true', 'x-request-id': '91b02dab-040f-4832-a8a0-32982bbad0cf', 'x-envoy-expected-rq-timeout-ms': '300000', 'l5d-dst-override': 'lite-llm.infra-dev.svc.cluster.local:4000', 'x-request-start': 't=1723514990.004', 'l5d-client-id': 'contour-envoy.public.serviceaccount.identity.linkerd.cluster.local'}, 'body': {'model': 'mpt-instruct-7b', 'messages': [{'role': 'user', 'content': 'what is the distance between NYC and Boston?'}], 'temperature': 0.2, 'top_p': 0.7, 'max_tokens': 1024, 'stream': True}}, ttl=None, metadata={'user_api_key': None, 'user_api_key_alias': None, 'user_api_end_user_max_budget': None, 'litellm_api_version': '1.42.3', 'global_max_parallel_requests': None, 'user_api_key_user_id': None, 'user_api_key_org_id': None, 'user_api_key_team_id': None, 'user_api_key_team_alias': None, 'user_api_key_team_max_budget': None, 'user_api_key_team_spend': None, 'user_api_key_spend': 0.0, 'user_api_key_max_budget': None, 'user_api_key_metadata': {}, 'headers': {'host': '<lite llm endpoint>', 'user-agent': 'curl/8.6.0', 'accept': '*/*', 'content-type': 'application/json', 'cache-control': 'no-cache', 'content-length': '183', 'x-forwarded-for': '10.105.1.254', 'x-forwarded-proto': 'http', 'x-envoy-internal': 'true', 'x-request-id': '91b02dab-040f-4832-a8a0-32982bbad0cf', 'x-envoy-expected-rq-timeout-ms': '300000', 'l5d-dst-override': 'lite-llm.infra-dev.svc.cluster.local:4000', 'x-request-start': 't=1723514990.004', 'l5d-client-id': 'contour-envoy.public.serviceaccount.identity.linkerd.cluster.local'}, 'endpoint': 'http://<lite llm endpoint>/v1/chat/completions', 'requester_ip_address': '', 'litellm_parent_otel_span': None, 'model_group': 'mpt-instruct-7b', 'deployment': 'sagemaker/mpt-instruct-deployment-2024-08-12-21-05-56-889', 'model_info': {'id': 'ddc28aec1118be274fa9cde3cb89949bdd5bcf69a60b29f64f21b4dec8818a93', 'db_model': False}, 'api_base': None, 'caching_groups': None}, request_timeout=600, litellm_call_id='388e449a-0e37-4073-913e-e917b182fdec', litellm_logging_obj=<litellm.litellm_core_utils.litellm_logging.Logging object at 0x7ff270c25750>, stream=True, model_info={'id': 'ddc28aec1118be274fa9cde3cb89949bdd5bcf69a60b29f64f21b4dec8818a93', 'db_model': False}, max_retries=0)
02:09:50 - LiteLLM:DEBUG: utils.py:237 -

02:09:50 - LiteLLM:DEBUG: utils.py:237 - ASYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache'): None
02:09:50 - LiteLLM:INFO: utils.py:2793 -
LiteLLM completion() model= mpt-instruct-deployment-2024-08-12-21-05-56-889; provider = sagemaker
02:09:50 - LiteLLM:DEBUG: utils.py:2796 -
LiteLLM: Params passed to completion() {'model': 'mpt-instruct-deployment-2024-08-12-21-05-56-889', 'functions': None, 'function_call': None, 'temperature': 0.2, 'top_p': 0.7, 'n': None, 'stream': True, 'stream_options': None, 'stop': None, 'max_tokens': 1024, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': None, 'custom_llm_provider': 'sagemaker', 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': 0, 'logprobs': None, 'top_logprobs': None, 'extra_headers': None, 'api_version': None, 'parallel_tool_calls': None, 'drop_params': None, 'additional_drop_params': None}
02:09:50 - LiteLLM:DEBUG: utils.py:2799 -
LiteLLM: Non-Default params passed to completion() {'temperature': 0.2, 'top_p': 0.7, 'stream': True, 'max_tokens': 1024, 'max_retries': 0}
02:09:50 - LiteLLM:DEBUG: utils.py:237 - Final returned optional params: {'temperature': 0.2, 'top_p': 0.7, 'stream': True, 'max_new_tokens': 1024}
02:09:50 - LiteLLM:DEBUG: litellm_logging.py:205 - self.optional_params: {'temperature': 0.2, 'top_p': 0.7, 'stream': True, 'max_new_tokens': 1024}
02:09:50 - LiteLLM:DEBUG: main.py:4917 - ENTERS SAGEMAKER CUSTOMSTREAMWRAPPER
02:09:50 - LiteLLM:DEBUG: utils.py:237 - RAW RESPONSE:
<litellm.utils.CustomStreamWrapper object at 0x7ff27723d5d0>


02:09:50 - LiteLLM Router:INFO: router.py:783 - litellm.acompletion(model=sagemaker/mpt-instruct-deployment-2024-08-12-21-05-56-889) 200 OK
02:09:50 - LiteLLM Router:DEBUG: router.py:2341 - Async Response: <litellm.utils.CustomStreamWrapper object at 0x7ff27723d5d0>
02:09:50 - LiteLLM Proxy:DEBUG: proxy_server.py:2370 - inside generator
INFO:     10.202.21.161:34088 - "POST /v1/chat/completions HTTP/1.1" 200 OK
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff271400210>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7ff2722d07d0>
02:09:50 - LiteLLM:DEBUG: utils.py:237 - value of async chunk: {'text': '\n', 'is_finished': False}
02:09:50 - LiteLLM:DEBUG: utils.py:237 - PROCESSED ASYNC CHUNK PRE CHUNK CREATOR: {'text': '\n', 'is_finished': False}
02:09:50 - LiteLLM:DEBUG: utils.py:237 - ENTERS SAGEMAKER STREAMING for chunk {'text': '\n', 'is_finished': False}
02:09:50 - LiteLLM:DEBUG: utils.py:237 - model_response finish reason 3: None; response_obj={'text': '\n', 'is_finished': False, 'finish_reason': ''}
02:09:50 - LiteLLM:DEBUG: utils.py:237 - model_response.choices[0].delta: Delta(content=None, role=None, function_call=None, tool_calls=None); completion_obj: {'content': '\n'}
02:09:50 - LiteLLM:DEBUG: utils.py:237 - self.sent_first_chunk: False
02:09:50 - LiteLLM:DEBUG: utils.py:237 - hold - True, model_response_str -
02:09:50 - LiteLLM:DEBUG: utils.py:237 - PROCESSED ASYNC CHUNK POST CHUNK CREATOR: None
02:09:50 - LiteLLM:DEBUG: litellm_logging.py:1498 - Logging Details LiteLLM-Failure Call: [<bound method Router.deployment_callback_on_failure of <litellm.router.Router object at 0x7ff2778d1610>>, <litellm.proxy.hooks.parallel_request_limiter._PROXY_MaxParallelRequestsHandler object at 0x7ff276585410>, <litellm.proxy.hooks.max_budget_limiter._PROXY_MaxBudgetLimiter object at 0x7ff276585450>, <litellm.proxy.hooks.cache_control_check._PROXY_CacheControlCheck object at 0x7ff276ff0d50>, <litellm._service_logger.ServiceLogging object at 0x7ff275c364d0>]
02:09:50 - LiteLLM:DEBUG: utils.py:3969 - Error occurred in getting api base - litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=mpt-instruct-deployment-2024-08-12-21-05-56-889
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
02:09:50 - LiteLLM Router:DEBUG: router.py:3203 - Attempting to add ddc28aec1118be274fa9cde3cb89949bdd5bcf69a60b29f64f21b4dec8818a93 to cooldown list. updated_fails: 1; self.allowed_fails: 0
02:09:50 - LiteLLM Router:DEBUG: router.py:3214 - Unable to cast exception status to int . Defaulting to status=500.
02:09:50 - LiteLLM:DEBUG: caching.py:29 - get cache: cache key: 02-09:cooldown_models; local_only: False
02:09:50 - LiteLLM:DEBUG: caching.py:29 - get cache: cache result: None
02:09:50 - LiteLLM Router:DEBUG: router.py:3237 - adding ddc28aec1118be274fa9cde3cb89949bdd5bcf69a60b29f64f21b4dec8818a93 to cooldown models
02:09:50 - LiteLLM:DEBUG: caching.py:29 - set cache: key: 02-09:cooldown_models; value: [('ddc28aec1118be274fa9cde3cb89949bdd5bcf69a60b29f64f21b4dec8818a93', {'Exception Received': 'Extra data: line 1 column 8 (char 7)', 'Status Code': '500'})]
02:09:50 - LiteLLM:DEBUG: caching.py:29 - InMemoryCache: set_cache. current size= 7
02:09:50 - LiteLLM:DEBUG: utils.py:237 - Logging Details: logger_fn - None | callable(logger_fn) - False
02:09:50 - LiteLLM Proxy:ERROR: proxy_server.py:2392 - litellm.proxy.proxy_server.async_data_generator(): Exception occured - litellm.APIConnectionError: Extra data: line 1 column 8 (char 7)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 10156, in __anext__
    async for chunk in self.completion_stream:
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/sagemaker.py", line 84, in __anext__
    line_data = json.loads(full_line.lstrip("data:").rstrip("/n"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 8 (char 7)

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 10156, in __anext__
    async for chunk in self.completion_stream:
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/sagemaker.py", line 84, in __anext__
    line_data = json.loads(full_line.lstrip("data:").rstrip("/n"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 8 (char 7)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2373, in async_data_generator
    async for chunk in response:
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 10354, in __anext__
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 8075, in exception_type
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 8048, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: Extra data: line 1 column 8 (char 7)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 10156, in __anext__
    async for chunk in self.completion_stream:
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/sagemaker.py", line 84, in __anext__
    line_data = json.loads(full_line.lstrip("data:").rstrip("/n"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 8 (char 7)


02:09:50 - LiteLLM Proxy:DEBUG: proxy_server.py:2402 - An error occurred: litellm.APIConnectionError: Extra data: line 1 column 8 (char 7)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 10156, in __anext__
    async for chunk in self.completion_stream:
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/sagemaker.py", line 84, in __anext__
    line_data = json.loads(full_line.lstrip("data:").rstrip("/n"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/json/decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 8 (char 7)


 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
02:09:50 - LiteLLM Proxy:DEBUG: parallel_request_limiter.py:24 - Inside Max Parallel Request Failure Hook
02:09:50 - LiteLLM Proxy:DEBUG: parallel_request_limiter.py:24 - user_api_key: None
```

**Comment by ishaan-jaff** [comment]
closing as resolved
