### ISSUE TITLE
[Bug]: Load Balancing Issue/Question

### ISSUE THREAD

**Issue by NEWbie0709** [BerriAI/litellm#5177]
### What happened?

I was trying to set up proxy routing for load balancing using litellm, and this is my code:
![image](https://github.com/user-attachments/assets/3a131e98-7fc1-493f-99af-2fcf561252cf)
After running it with llama3 twice per minute, it should have hit the rate limit and switched to the default model, which is claude. However, it failed and showed this error:
![image](https://github.com/user-attachments/assets/220edb89-ded5-4eda-8dab-5923b80f1f95)
Can you help me solve this issue?

### Relevant log output

```shell
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Router:ERROR: router.py:2482 - An exception occurred - No deployments available for selected model, Try again in 60 seconds. Passed model=claude-3-haiku-20240307. Try again in 60 seconds.      
15:02:00 - LiteLLM Proxy:ERROR: proxy_server.py:2989 - litellm.proxy.proxy_server.chat_completion(): Exception occured - No deployments available for selected model, Try again in 60 seconds. Passed model=groq/llama3-70b-8192. Try again in 60 seconds.
Traceback (most recent call last):
  File "C:\Users\i9-4090\miniconda3\lib\site-packages\litellm\proxy\proxy_server.py", line 2885, in chat_completion
    responses = await llm_responses
  File "C:\Users\i9-4090\miniconda3\lib\site-packages\litellm\router.py", line 655, in acompletion
    raise e
  File "C:\Users\i9-4090\miniconda3\lib\site-packages\litellm\router.py", line 643, in acompletion
    response = await self.async_function_with_fallbacks(**kwargs)
  File "C:\Users\i9-4090\miniconda3\lib\site-packages\litellm\router.py", line 2484, in async_function_with_fallbacks
    raise original_exception
  File "C:\Users\i9-4090\miniconda3\lib\site-packages\litellm\router.py", line 2329, in async_function_with_fallbacks
    response = await self.async_function_with_retries(*args, **kwargs)
  File "C:\Users\i9-4090\miniconda3\lib\site-packages\litellm\router.py", line 2584, in async_function_with_retries
    raise original_exception
  File "C:\Users\i9-4090\miniconda3\lib\site-packages\litellm\router.py", line 2506, in async_function_with_retries
    response = await original_function(*args, **kwargs)
  File "C:\Users\i9-4090\miniconda3\lib\site-packages\litellm\router.py", line 785, in _acompletion
    raise e
  File "C:\Users\i9-4090\miniconda3\lib\site-packages\litellm\router.py", line 672, in _acompletion
    deployment = await self.async_get_available_deployment(
  File "C:\Users\i9-4090\miniconda3\lib\site-packages\litellm\router.py", line 4405, in async_get_available_deployment
    return self.get_available_deployment(
  File "C:\Users\i9-4090\miniconda3\lib\site-packages\litellm\router.py", line 4602, in get_available_deployment
    healthy_deployments = self._pre_call_checks(
  File "C:\Users\i9-4090\miniconda3\lib\site-packages\litellm\router.py", line 4291, in _pre_call_checks
    raise ValueError(
ValueError: No deployments available for selected model, Try again in 60 seconds. Passed model=groq/llama3-70b-8192. Try again in 60 seconds.

Post-call failure hook triggered.
Exception: No deployments available for selected model, Try again in 60 seconds. Passed model=groq/llama3-70b-8192. Try again in 60 seconds.
User API key: null
15:02:00 - LiteLLM Proxy:ERROR: _common.py:120 - Giving up chat_completion(...) after 1 tries (litellm.proxy._types.ProxyException)
INFO:     127.0.0.1:64743 - "POST /chat/completions HTTP/1.1" 429 Too Many Requests
```

**Comment by NEWbie0709** [comment]
And this error also when i use the same group groq but different model
![image](https://github.com/user-attachments/assets/97500108-1b69-40d7-b9ba-3190f27f52c4)
![image](https://github.com/user-attachments/assets/45ceead7-b460-416b-ba9e-c000e7eb9f82)
![image](https://github.com/user-attachments/assets/7e120f94-8876-4632-ab59-2abacc6063d3)

**Comment by ghost** [comment]
Hey @NEWbie0709 what version of litellm is this? 

Line 2482 on router.py does not map to an exception line - https://github.com/BerriAI/litellm/blob/3a1b3227d80df5dfaaad7b06b86bf95160b16c3e/litellm/router.py#L2482

**Comment by ghost** [comment]
Can you please confirm you're on v`1.43.7`+ (can confirm by checking the version on your swagger 
<img width="620" alt="Screenshot 2024-08-13 at 3 25 01 PM" src="https://github.com/user-attachments/assets/70ec984a-a936-4921-96d9-0930449f702e">

**Comment by NEWbie0709** [comment]
![image](https://github.com/user-attachments/assets/67b3bc47-23a2-4bde-a0ff-0cd8980475e1)
i think im using the 1.41.21 version

**Comment by ghost** [comment]
can you please bump to latest, and see if the issue persists? 

You can mock a fallback error like this - 

```bash
curl -X POST 'http://0.0.0.0:4000/chat/completions' \
-H 'Content-Type: application/json' \
-H 'Authorization: Bearer sk-1234' \
-d '{
  "model": "llama-3...", # your model_name 
  "messages": [
        {"role": "user", "content": "Hi there!"}
    ],
    "mock_testing_fallbacks": true
}'
```

**Comment by NEWbie0709** [comment]
![image](https://github.com/user-attachments/assets/1c66a65e-3f4d-40c3-85ac-9f5d62688b66)
no error on this

**Comment by ghost** [comment]
i can see the fallback worked as expected (`'model': 'claude-3-haiku..'`)

**Comment by NEWbie0709** [comment]
yup thanks for the help!
