### ISSUE TITLE
[Bug]: team cannot access wildcard model

### ISSUE THREAD

**Issue by edwins** [BerriAI/litellm#5227]
### What happened?

Using litellm v1.43.9

I setup a team a wildcard model in my proxy config, like this:

```
  - model_name: openai/*
    litellm_params:
      model: openai/*
      api_key: "somekey"
```

I then updated my team with the following curl call:

```
curl --location 'https://example.com/team/update' --header "Authorization: Bearer $LITELLM_MASTER_KEY" \
--header 'Content-Type: application/json' \
--data-raw '{
  "team_id": "some-team-id",
   "models":["openai/*"]
}' 
```

There is a user who is a member of the team, but when I attempt to use a model from openai, I get an authentication error.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/mnt/d/working5/ansible-llm-stack/tests/langchain-openai.py", line 32, in <module>
    print(chat.invoke(messages))
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py", line 158, in invoke
    self.generate_prompt(
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py", line 560, in generate_prompt
    return self.generate(prompt_messages, stop=stop, callbacks=callbacks, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py", line 421, in generate
    raise e
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py", line 411, in generate
    self._generate_with_cache(
  File "/usr/local/lib/python3.10/dist-packages/langchain_core/language_models/chat_models.py", line 632, in _generate_with_cache
    result = self._generate(
  File "/usr/local/lib/python3.10/dist-packages/langchain_openai/chat_models/base.py", line 522, in _generate
    response = self.client.create(messages=message_dicts, **params)
  File "/home/edwin/.local/lib/python3.10/site-packages/openai/_utils/_utils.py", line 271, in wrapper
    return func(*args, **kwargs)
  File "/home/edwin/.local/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 643, in create
    return self._post(
  File "/home/edwin/.local/lib/python3.10/site-packages/openai/_base_client.py", line 1112, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/edwin/.local/lib/python3.10/site-packages/openai/_base_client.py", line 859, in request
    return self._request(
  File "/home/edwin/.local/lib/python3.10/site-packages/openai/_base_client.py", line 949, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'error': {'message': "Authentication Error, Team=some-team-id not allowed to call model=openai/gpt-4o. Allowed team models = ['openai/*']", 'type': 'auth_error', 'param': 'None', 'code': '401'}}
```

**Comment by ishaan-jaff** [comment]
working on this

**Comment by ishaan-jaff** [comment]
solved via: https://github.com/BerriAI/litellm/pull/5263
