### ISSUE TITLE
[Feature]: Support gemini 'function' param 

### ISSUE THREAD

**Issue by mshumer** [BerriAI/litellm#5344]
### What happened?

When using streaming (with gemini-pro), tool calls aren't captured/returned. But when stream=False, it works fine.

### Twitter / LinkedIn details

[Matt Shumer Twitter](https://x.com/mattshumer_)

**Comment by ishaan-jaff** [comment]
@mshumer - can you add a code snippet for us to repro

**Comment by mshumer** [comment]
# Working:
```
tools = [
        {   "type": "function",
            "function": {
            "name": "search",
            "description": "Executes searches.",
            "parameters": {
                "type": "object",
                "properties": {
                    "queries": {
                        "type": "array",
                        "description": "A list of queries to search for.",
                        "items": {"type": "string"},
                    },
                },
                "required": ["queries"],
            },
            },
        },
    ]

# Set up the messages
messages = [
    {
        "role": "system",
        "content": """Use search for most queries."""
    }, 
    {
        "role": "user",
        "content": """search for othersideai (use `search`)"""
    }
]


# Make the API call
response = completion(
    model="vertex_ai/gemini-1.5-pro",
    messages=messages,
    tools=tools,
    tool_choice="auto",
)

print("Model Response:")
print(response)
```

## This returns the following
`ModelResponse(id='chatcmpl-98918351-6806-4ce5-8d98-6f3e91f8c280', choices=[Choices(finish_reason='stop', index=0, message=Message(content=None, role='assistant', tool_calls=[ChatCompletionMessageToolCall(function=Function(arguments='{"queries": ["search:othersideai"]}', name='search'), id='call_be5124be-e311-4844-b805-fdd5c09eb489', type='function')], function_call=None))], created=1724443644, model='gemini-1.5-pro', object='chat.completion', system_fingerprint=None, usage=Usage(completion_tokens=8, prompt_tokens=385, total_tokens=393))`


# Not Working (stream=True)
```
tools = [
        {   "type": "function",
            "function": {
            "name": "search",
            "description": "Executes searches.",
            "parameters": {
                "type": "object",
                "properties": {
                    "queries": {
                        "type": "array",
                        "description": "A list of queries to search for.",
                        "items": {"type": "string"},
                    },
                },
                "required": ["queries"],
            },
            },
        },
    ]

# Set up the messages
messages = [
    {
        "role": "system",
        "content": """Use search for most queries."""
    }, 
    {
        "role": "user",
        "content": """search for othersideai (use `search`)"""
    }
]

# Make the API call
response_stream = completion(
    model="vertex_ai/gemini-1.5-pro",
    messages=messages,
    tools=tools,
    tool_choice="auto",
    stream=True # Enable streaming
)
print(response_stream)

full_response = ""
for chunk in response_stream:
    print(chunk)
```

## This returns the following (note there is no tool call)
`ModelResponse(id='chatcmpl-603bec78-2450-4a5b-9161-d929a5be18ba', choices=[StreamingChoices(finish_reason='stop', index=0, delta=Delta(content=None, role=None, function_call=None, tool_calls=None), logprobs=None)], created=1724444353, model='gemini-1.5-pro', object='chat.completion.chunk', system_fingerprint=None)`

**Comment by ishaan-jaff** [comment]
im able to repro - fixing

**Comment by ishaan-jaff** [comment]
oh I believe this is fixed already @mshumer can you try `model="vertex_ai_beta/gemini-1.5-pro"`. Let me know if this works for you 


This worked for me

```python
litellm.set_verbose = False
    tools = [
        {   "type": "function",
            "function": {
            "name": "search",
            "description": "Executes searches.",
            "parameters": {
                "type": "object",
                "properties": {
                    "queries": {
                        "type": "array",
                        "description": "A list of queries to search for.",
                        "items": {"type": "string"},
                    },
                },
                "required": ["queries"],
            },
            },
        },
    ]

    # Set up the messages
    messages = [
        {
            "role": "system",
            "content": """Use search for most queries."""
        }, 
        {
            "role": "user",
            "content": """search for othersideai (use `search`)"""
        }
    ]

    # Make the API call
    response_stream = litellm.completion(
        model="vertex_ai_beta/gemini-1.5-pro",
        messages=messages,
        tools=tools,
        tool_choice="auto",
        stream=True # Enable streaming
    )
    print(response_stream)

    full_response = ""
    for chunk in response_stream:
        print(chunk)

```

**Comment by ishaan-jaff** [comment]
context - we're in the process of migrating all `vertex_ai` calls to `vertex_ai_beta`. Migration should be done over the next 1-2 weeks

**Comment by mshumer** [comment]
Seems to work, thank you! By the way, is there any way to use the previous `functions` and `function_call` functionality, instead of `tools`?

**Comment by ghost** [comment]
i believe that should already work @mshumer with `vertex_ai_beta/`

**Comment by mshumer** [comment]
Unfortunately not :(:

```
UnsupportedParamsError: litellm.UnsupportedParamsError: vertex_ai_beta does not support parameters: {'functions': [{'name': 'search', 'description': 'Executes searches.', 'parameters': {'type': 'object', 'properties': {'queries': {'type': 'array', 'description': 'A list of queries to search for.', 'items': {'type': 'string'}}}, 'required': ['queries']}}], 'function_call': 'auto'}, for model=gemini-1.5-pro. To drop these, set `litellm.drop_params=True` or for proxy:
```

**Comment by ghost** [comment]
@mshumer 

it looks like you're making a 'function' call not a 'tool' call. Can you let me know if using the 'tools' param solves your problem?

**Comment by ghost** [comment]
Reopening issue to focus on adding 'function' param support to gemini

**Comment by mshumer** [comment]
@krrishdholakia unfortunately not... trying to migrate some old code without changing it from functions -> tools. Thanks for looking into this!

**Comment by mshumer** [comment]
Unfortunately I'm still having this issue w/ no functions support on v1.44.7.

**Comment by ghost** [comment]
hi @mshumer the commit isn't live on v1.44.7. 

It should be live in v1.44.8. 

You can tell by checking the top-left of the commit - 

<img width="880" alt="Screenshot 2024-08-28 at 8 17 09 AM" src="https://github.com/user-attachments/assets/91d65d8c-75bd-4fb8-ad7d-ade7793c8a98">

It should show the release tag, once it's out

**Comment by mshumer** [comment]
Great -- thank you. That seems to work. However I think it's still missing the ability to pass in a `function` role in the chat history.

**Comment by ghost** [comment]
can you share a test example? @mshumer

**Comment by mshumer** [comment]
```
tools = [
        {   "type": "function",
            "function": {
            "name": "search",
            "description": "Executes searches.",
            "parameters": {
                "type": "object",
                "properties": {
                    "queries": {
                        "type": "array",
                        "description": "A list of queries to search for.",
                        "items": {"type": "string"},
                    },
                },
                "required": ["queries"],
            },
            },
        },
    ]

# Set up the messages
messages = [
    {
        "role": "system",
        "content": """Use search for most queries."""
    },
    {
        "role": "user",
        "content": """search for weather in boston (use `search`)"""
    },
    {
        "role": "assistant",
        "content": None,
        "function_call": {
            "name": "search",
            "arguments": '{"queries": ["weather in boston"]}'
        }
    },
    {
        "role": "function",
        "name": "search",
        "content": "The current weather in Boston is 22°F."
    },
]

# Make the API call
response_stream = completion(
    model="vertex_ai_beta/gemini-1.5-pro",
    messages=messages,
    tools=tools,
    tool_choice="auto",
    stream=True # Enable streaming
)
print(response_stream)

full_response = ""
for chunk in response_stream:
    print(chunk)
```

**Comment by mshumer** [comment]
Just following up on this — thanks! @krrishdholakia

**Comment by ishaan-jaff** [comment]
does this not work on `v1.44.8.` for you ? @mshumer

**Comment by ishaan-jaff** [comment]
>  pass in a function role in the chat history.

Is this the current pending issue @mshumer ?

**Comment by mshumer** [comment]
Yeah, that's the current issue. It still doesn't work on `v1.44.8`.


```
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/litellm/main.py in completion(model, messages, timeout, temperature, top_p, n, stream, stream_options, stop, max_tokens, presence_penalty, frequency_penalty, logit_bias, user, response_format, seed, tools, tool_choice, logprobs, top_logprobs, parallel_tool_calls, deployment_id, extra_headers, functions, function_call, base_url, api_version, api_key, model_list, **kwargs)
   2020                 model_response=model_response,
-> 2021                 print_verbose=print_verbose,
   2022                 optional_params=new_params,

9 frames
Exception: Invalid Message passed in - {'role': 'function', 'name': 'search', 'content': 'The current weather in Boston is 22°F.'}. File an issue https://github.com/BerriAI/litellm/issues

During handling of the above exception, another exception occurred:

APIConnectionError                        Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/litellm/utils.py in exception_type(model, original_exception, custom_llm_provider, completion_kwargs, extra_kwargs)
   8495                 )
   8496             else:
-> 8497                 raise APIConnectionError(
   8498                     message="{}\n{}".format(
   8499                         str(original_exception), traceback.format_exc()

APIConnectionError: litellm.APIConnectionError: Invalid Message passed in - {'role': 'function', 'name': 'search', 'content': 'The current weather in Boston is 22°F.'}. File an issue https://github.com/BerriAI/litellm/issues
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litellm/main.py", line 2021, in completion
    print_verbose=print_verbose,
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/vertex_ai_and_google_ai_studio/gemini/vertex_and_google_ai_studio_gemini.py", line 1440, in completion
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/vertex_ai_and_google_ai_studio/gemini/vertex_and_google_ai_studio_gemini.py", line 1409, in completion
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/vertex_ai_and_google_ai_studio/vertex_ai_non_gemini.py", line 224, in _gemini_convert_messages_with_history
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/vertex_ai_and_google_ai_studio/vertex_ai_non_gemini.py", line 217, in _gemini_convert_messages_with_history
    raise Exception(
Exception: Invalid Message passed in - {'role': 'function', 'name': 'search', 'content': 'The current weather in Boston is 22°F.'}. File an issue https://github.com/BerriAI/litellm/issues
```

**Comment by ghost** [comment]
let's create a separate issue for that, as the original issue is now resolved
