### ISSUE TITLE
[Bug]: ValueError: You cannot set content to an empty string. We interpret empty strings as None in requests

### ISSUE THREAD

**Issue by Nivek92** [BerriAI/litellm#535]
### What happened?

I'm trying to run litellm with a ollama. 

Here's the code (I took it from the example at https://docs.litellm.ai/docs/providers/ollama)

```
import litellm

messages=[{ "content": "respond in 20 words. who are you?","role": "user"}]

response = litellm.completion(model='ollama/orca-mini', messages=messages, api_base="http://localhost:11434")

print(response)
```

I have confirmed that the ollama server is running and I get a response from it when I call it directly via the example python code they provide.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/kevin/.local/lib/python3.10/site-packages/litellm/main.py", line 1065, in completion
    model_response["choices"][0]["message"]["content"] = response_string
  File "/home/kevin/.local/lib/python3.10/site-packages/openai/openai_object.py", line 71, in __setitem__
    raise ValueError(
ValueError: You cannot set content to an empty string. We interpret empty strings as None in requests.You may set {
  "content": null,
  "logprobs": null,
  "role": "assistant"
}.content = None to delete the property

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kevin/code/autogen-playground/agentchat_auto_feedback_from_code_execution/main2.py", line 7, in <module>
    response = litellm.completion(model='ollama/orca-mini', messages=messages, api_base="http://localhost:11434", litellm_params={"force_timeout": 3600})
  File "/home/kevin/.local/lib/python3.10/site-packages/litellm/utils.py", line 718, in wrapper
    raise e
  File "/home/kevin/.local/lib/python3.10/site-packages/litellm/utils.py", line 677, in wrapper
    result = original_function(*args, **kwargs)
  File "/home/kevin/.local/lib/python3.10/site-packages/litellm/timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/kevin/.local/lib/python3.10/site-packages/litellm/timeout.py", line 42, in async_func
    return func(*args, **kwargs)
  File "/home/kevin/.local/lib/python3.10/site-packages/litellm/main.py", line 1196, in completion
    raise exception_type(
  File "/home/kevin/.local/lib/python3.10/site-packages/litellm/utils.py", line 2842, in exception_type
    raise e
  File "/home/kevin/.local/lib/python3.10/site-packages/litellm/utils.py", line 2824, in exception_type
    raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: You cannot set content to an empty string. We interpret empty strings as None in requests.You may set {
  "content": null,
  "logprobs": null,
  "role": "assistant"
}.content = None to delete the property
```

**Comment by Nivek92** [comment]
Ok I figured out the issue. (I'm an idiot)

I tried to use a model that haven't been downloaded by ollama before, assuming it would download it on-demand when not existing.

So if anyone sees the same issue, make sure the model has been downloaded with `ollama list`. If it's not downloaded you can do so using `ollama pull <model>`. After that everything should work.

**Comment by ghost** [comment]
glad that fixed it @Nivek92
