### ISSUE TITLE
[Bug]: Cannot import litellm (1.44.9)

### ISSUE THREAD

**Issue by au-to-pi-lot** [BerriAI/litellm#5424]
### What happened?

When importing litellm 1.44.9, it throws an ImportError. This should not happen.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/autopilot/.local/share/JetBrains/Toolbox/apps/pycharm-professional/plugins/python/helpers/pydev/pydevd.py", line 1534, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/autopilot/.local/share/JetBrains/Toolbox/apps/pycharm-professional/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "src/main.py", line 7, in <module>
    from src.bot import DiscordBot
  File "/home/autopilot/Projects/nexari/src/bot.py", line 7, in <module>
    import litellm
  File "/home/autopilot/.conda/envs/llm-discord-bot/lib/python3.12/site-packages/litellm/__init__.py", line 893, in <module>
    MistralEmbeddingConfig,
^^^^^^^^^^^^^^^^^^^
  File "/home/autopilot/.conda/envs/llm-discord-bot/lib/python3.12/site-packages/litellm/main.py", line 106, in <module>
    from .llms.cohere import chat as cohere_chat
ImportError: cannot import name 'chat' from 'litellm.llms.cohere' (/home/autopilot/.conda/envs/llm-discord-bot/lib/python3.12/site-packages/litellm/llms/cohere.py)
```

**Comment by ghost** [comment]
Hey @au-to-pi-lot i can see the `chat.py` file here - https://github.com/BerriAI/litellm/tree/main/litellm/llms/cohere

I suspect this issue might be fixed already on v1.44.10+ (might be transitional? as it passed all our cohere chat tests)
