### ISSUE TITLE
[Bug]: [CLI] Error instead of help message if --model is not passed

### ISSUE THREAD

**Issue by francisduvivier** [BerriAI/litellm#554]
### What happened?

If I do 
`litellm --api_base localhost:11434` then I get the error (TypeError: argument of type 'NoneType' is not iterable
). See the relevant log output below.
Would be better if the cli informs that the model cli parameter is missing in this case.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/fduvivier/.local/bin/litellm", line 8, in <module>
    sys.exit(run_server())
  File "/home/fduvivier/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/litellm/proxy/proxy_cli.py", line 91, in run_server
    if "ollama" in model: 
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by ghost** [comment]
hey @francisduvivier fixed here - f0c9c249251ff02b182996759b96d8cc6065c693

will update issue once this is in prod

**Comment by ghost** [comment]
in prod: 
```
View at:
https://pypi.org/project/litellm/0.5.2/
```

@francisduvivier just run `pip install --upgrade litellm` to get the latest version. Let me know if this fixes it for you.

**Comment by francisduvivier** [comment]
@krrishdholakia, so now I do not get an error anymore when doing 
`litellm --api_base localhost:11434` but for this particular usecase, this is actually worse, because now it has started a proxy that doesn't work since it's sending calls to the ollama endpoint but not using the correct api for ollama.
`litellm --test` now results in an internal server error.

I meant this bug ticket in the sense that guarding against and informing about invalid user input can be improved.

Full server logs:

```
fduvivier@T450:~$ litellm --api_base http://localhost:11434

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new


LiteLLM: Deployed Proxy Locally

LiteLLM: Test your local endpoint with: "litellm --test" [In a new terminal tab]

LiteLLM: Deploy your proxy using the following: "litellm --model claude-instant-1 --deploy" Get an https://api.litellm.ai/chat/completions endpoint 

INFO:     Started server process [1282801]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

INFO:     127.0.0.1:49298 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/fduvivier/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 413, in handle_error_response
    error_data = resp["error"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fduvivier/.local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/home/fduvivier/.local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/fastapi/applications.py", line 292, in __call__
    await super().__call__(scope, receive, send)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/fduvivier/.local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/fduvivier/.local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/fduvivier/.local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/fastapi/routing.py", line 273, in app
    raw_response = await run_endpoint_function(
  File "/home/fduvivier/.local/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 200, in chat_completion
    response = litellm.completion(**data)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/litellm/utils.py", line 741, in wrapper
    raise e
  File "/home/fduvivier/.local/lib/python3.10/site-packages/litellm/utils.py", line 700, in wrapper
    result = original_function(*args, **kwargs)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/litellm/timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/fduvivier/.local/lib/python3.10/site-packages/litellm/timeout.py", line 42, in async_func
    return func(*args, **kwargs)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/litellm/main.py", line 1139, in completion
    raise exception_type(
  File "/home/fduvivier/.local/lib/python3.10/site-packages/litellm/utils.py", line 2906, in exception_type
    raise e
  File "/home/fduvivier/.local/lib/python3.10/site-packages/litellm/utils.py", line 2325, in exception_type
    raise original_exception
  File "/home/fduvivier/.local/lib/python3.10/site-packages/litellm/main.py", line 409, in completion
    raise e
  File "/home/fduvivier/.local/lib/python3.10/site-packages/litellm/main.py", line 391, in completion
    response = openai.ChatCompletion.create(
  File "/home/fduvivier/.local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "/home/fduvivier/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/home/fduvivier/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/home/fduvivier/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
  File "/home/fduvivier/.local/lib/python3.10/site-packages/openai/api_requestor.py", line 415, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: '404 page not found' (HTTP response code was 404)


```

**Comment by ghost** [comment]
Hey @francisduvivier my apologies. Thanks for catching this. I'll test it more thoroughly and push a fix. Sorry for that.

**Comment by ghost** [comment]
Reopening this

**Comment by ghost** [comment]
<img width="1321" alt="Screenshot 2023-10-09 at 2 35 29 PM" src="https://github.com/BerriAI/litellm/assets/17561003/4e78d7a9-a15a-446e-82ae-0e1e49a84596">

**Comment by ghost** [comment]
closing as this is now pushed to prod. @francisduvivier let me know if you have suggestions to improve this!
