### ISSUE TITLE
[Bug]: None of the embeddings of AWS bedrock are working

### ISSUE THREAD

**Issue by aliabbasjp** [BerriAI/litellm#5588]
### What happened?

I have correctly configured the creds and even after trying various variations of "amazon.titan-embed-text-v1", as mentioned on the docuemntation website, none of it is working:

>>> response = embedding(
...     model="amazon.titan-embed-text-v1",
...     input=["good morning from litellm"],
... )

Attached log

### Relevant log output

```shell
warnings.warn(message, UserWarning)
>>> response = embedding(
...     model="amazon.titan-embed-text-v1",
...     input=["good morning from litellm"],
... )

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/litellm/main.py", line 3535, in embedding
    response = bedrock_embedding.embeddings(
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/bedrock/embed/embedding.py", line 422, in embeddings
    return self._single_func_embeddings(
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/bedrock/embed/embedding.py", line 194, in _single_func_embeddings
    response = self._make_sync_call(
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/bedrock/embed/embedding.py", line 109, in _make_sync_call
    response = client.post(url=api_base, headers=headers, data=json.dumps(data))  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/custom_httpx/http_handler.py", line 341, in post
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/custom_httpx/http_handler.py", line 324, in post
    response = self.client.send(req, stream=stream)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 1092, in wrapper
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 980, in wrapper
    result = original_function(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/litellm/main.py", line 3770, in embedding
    raise exception_type(
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 8189, in exception_type
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 8161, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/litellm/main.py", line 3535, in embedding
    response = bedrock_embedding.embeddings(
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/bedrock/embed/embedding.py", line 422, in embeddings
    return self._single_func_embeddings(
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/bedrock/embed/embedding.py", line 194, in _single_func_embeddings
    response = self._make_sync_call(
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/bedrock/embed/embedding.py", line 109, in _make_sync_call
    response = client.post(url=api_base, headers=headers, data=json.dumps(data))  # type: ignore
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/custom_httpx/http_handler.py", line 341, in post
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/llms/custom_httpx/http_handler.py", line 324, in post
    response = self.client.send(req, stream=stream)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 926, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 954, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 991, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1027, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 236, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 206, in connect_tcp
    sock = socket.create_connection(
  File "/usr/local/lib/python3.10/socket.py", line 824, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)
```

**Comment by ghost** [comment]
Hi @aliabbasjp unable to repro this issue. I just ran this script in a google colab - 
<img width="1656" alt="Screenshot 2024-09-09 at 2 49 36 PM" src="https://github.com/user-attachments/assets/6134fe43-b623-4ce4-b5a0-63294c1533ec">


```python
import os

os.environ["AWS_ACCESS_KEY_ID"] = ""
os.environ["AWS_SECRET_ACCESS_KEY"] = ""
os.environ["AWS_REGION_NAME"] = ""

from litellm import embedding
response = embedding(
    model="bedrock/amazon.titan-embed-text-v1",
    input=["good morning from litellm"],
)
print(response)
```

**Comment by ghost** [comment]
>   File "/usr/local/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
UnicodeError: encoding with 'idna' codec failed (UnicodeError: label empty or too long)


are you using some sort of proxy between litellm and bedrock? That might be what's causing the issue

**Comment by ghost** [comment]
try re-running with `litellm.set_verbose=True` and share your logs if possible, it might be that the url is invalid

**Comment by ghost** [comment]
https://chatgpt.com/share/2b483053-e45f-4aa6-98ad-e656316f9760
