### ISSUE TITLE
Error PLEASE HELP, I have the chatgpt 4 and i have entered the api key but i get this

### ISSUE THREAD

**Issue by baveensarwar** [BerriAI/litellm#559]
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/opt/homebrew/bin/interpreter", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/core.py", line 21, in cli
    cli(self)
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/cli/cli.py", line 168, in cli
    interpreter.chat()
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/core.py", line 66, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/core.py", line 87, in _streaming_chat
    yield from terminal_interface(self, message)
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/terminal_interface/terminal_interface.py", line 62, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/core.py", line 95, in _streaming_chat
    yield from self._respond()
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/core.py", line 121, in _respond
    yield from respond(self)
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/core/respond.py", line 57, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "/opt/homebrew/lib/python3.11/site-packages/interpreter/llm/setup_openai_coding_llm.py", line 94, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/utils.py", line 718, in wrapper
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/utils.py", line 677, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/main.py", line 1213, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/utils.py", line 2851, in exception_type
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/utils.py", line 2270, in exception_type
    raise original_exception
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/main.py", line 393, in completion
    raise e
  File "/opt/homebrew/lib/python3.11/site-packages/litellm/main.py", line 375, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/opt/homebrew/lib/python3.11/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

**Comment by ghost** [comment]
ChatGPT plus is not the same as openai api.

**Comment by ghost** [comment]
@baveensarwar your error message contains a documentation link to help with this. Might be worth starting with that.
