### ISSUE TITLE
[Bug]: LangChain agent not work using langchain openai package

### ISSUE THREAD

**Issue by elvis-cai** [BerriAI/litellm#5591]
### What happened?

Hi team

we found when using LangChain openai package, it reports pydantic error `pydantic.v1.error_wrappers.ValidationError: 2 validation errors for addSchema` 
however, it works when using `ChatLiteLLM` package.

🔴 not working code
```
from langchain_core.tools import tool


@tool
def multiply(first_int: int, second_int: int) -> int:
    """Multiply two integers together."""
    return first_int * second_int


@tool
def add(first_int: int, second_int: int) -> int:
    "Add two integers."
    return first_int + second_int


@tool
def exponentiate(base: int, exponent: int) -> int:
    "Exponentiate the base to the exponent power."
    return base**exponent


tools = [multiply, add, exponentiate]

from langchain import hub
from langchain.agents import AgentExecutor, create_tool_calling_agent

# Get the prompt to use - you can modify this!
prompt = hub.pull("hwchase17/openai-tools-agent")
prompt.pretty_print()

from langchain_openai import ChatOpenAI
llm = ChatOpenAI(
    model="gpt-4o",
    base_url="xxx",
    api_key="sk-1234",
)

agent = create_tool_calling_agent(llm, tools, prompt)

agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

agent_executor.invoke(
    {
        "input": "Take 3 to the fifth power and multiply that by the sum of twelve and three, then square the whole result"
    }
)
```
🟢  working code
```
from langchain_core.tools import tool


@tool
def multiply(first_int: int, second_int: int) -> int:
    """Multiply two integers together."""
    return first_int * second_int


@tool
def add(first_int: int, second_int: int) -> int:
    "Add two integers."
    return first_int + second_int


@tool
def exponentiate(base: int, exponent: int) -> int:
    "Exponentiate the base to the exponent power."
    return base**exponent


tools = [multiply, add, exponentiate]

from langchain import hub
from langchain.agents import AgentExecutor, create_tool_calling_agent

# Get the prompt to use - you can modify this!
prompt = hub.pull("hwchase17/openai-tools-agent")
prompt.pretty_print()

from langchain_community.chat_models import ChatLiteLLM
llm = ChatLiteLLM(
    model="gpt-4o",
    base_url="https://xxx",
    api_key="sk-1234",
)


agent = create_tool_calling_agent(llm, tools, prompt)

agent_executor = AgentExecutor(agent=agent, tools=tools, verbose=True)

agent_executor.invoke(
    {
        "input": "Take 3 to the fifth power and multiply that by the sum of twelve and three, then square the whole result"
    
```

### Relevant log output

```shell
🔴 not working

================================ System Message ================================

You are a helpful assistant

============================= Messages Placeholder =============================

{chat_history}

================================ Human Message =================================

{input}

============================= Messages Placeholder =============================

{agent_scratchpad}


> Entering new AgentExecutor chain...

Invoking: `add` with `{'base': 3, 'exponent': 5}`


Traceback (most recent call last):
  File "/opt/nihao/gcp/ai-platform/ai-gateway/litellm/langchain/tool-agent-openai.py", line 42, in <module>
    agent_executor.invoke(
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/chains/base.py", line 164, in invoke
    raise e
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/chains/base.py", line 154, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/agents/agent.py", line 1625, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/agents/agent.py", line 1331, in _take_next_step
    [
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/agents/agent.py", line 1416, in _iter_next_step
    yield self._perform_agent_action(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/agents/agent.py", line 1438, in _perform_agent_action
    observation = tool.run(
                  ^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/langchain_core/tools/base.py", line 586, in run
    raise error_to_raise
  File "/opt/homebrew/lib/python3.12/site-packages/langchain_core/tools/base.py", line 549, in run
    tool_args, tool_kwargs = self._to_args_and_kwargs(tool_input)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/langchain_core/tools/base.py", line 472, in _to_args_and_kwargs
    tool_input = self._parse_input(tool_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/langchain_core/tools/base.py", line 424, in _parse_input
    result = input_args.parse_obj(tool_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pydantic/v1/main.py", line 526, in parse_obj
    return cls(**obj)
           ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for addSchema
first_int
  field required (type=value_error.missing)
second_int
  field required (type=value_error.missing)
```
working 🟢
```
  prompt = loads(json.dumps(prompt_object.manifest))
================================ System Message ================================

You are a helpful assistant

============================= Messages Placeholder =============================

{chat_history}

================================ Human Message =================================

{input}

============================= Messages Placeholder =============================

{agent_scratchpad}


> Entering new AgentExecutor chain...

Invoking: `exponentiate` with `{'base': 3, 'exponent': 5}`


243
Invoking: `add` with `{'first_int': 12, 'second_int': 3}`


15
Invoking: `multiply` with `{'first_int': 243, 'second_int': 15}`


3645
Invoking: `exponentiate` with `{'base': 3645, 'exponent': 2}`


13286025The final result is \(13,286,025\).

> Finished chain.
```
```


### Twitter / LinkedIn details

_No response_

**Comment by ghost** [comment]
This works for me @elvis-cai on v`1.44.22`
<img width="976" alt="Screenshot 2024-09-09 at 4 22 24 PM" src="https://github.com/user-attachments/assets/d35c2307-5d72-45d6-89c1-02c79edd7152">

**Comment by ghost** [comment]
<img width="1211" alt="Screenshot 2024-09-09 at 4 22 34 PM" src="https://github.com/user-attachments/assets/d6927ff7-9c15-4728-b657-2f6799ff4f3f">

**Comment by ghost** [comment]
Works for azure gpt-4o as well 
<img width="985" alt="Screenshot 2024-09-09 at 4 23 36 PM" src="https://github.com/user-attachments/assets/0bf01695-6e93-4a26-86ba-3f6a1c0ede3e">
<img width="1565" alt="Screenshot 2024-09-09 at 4 23 32 PM" src="https://github.com/user-attachments/assets/32478caa-0ba6-4e53-8761-3e09e5b7460a">

**Comment by ghost** [comment]
@elvis-cai I suspect you're on an older version of litellm, which might be why you're seeing these issues.

**Comment by elvis-cai** [comment]
tested with latest `1.44.22` ,it works first time and failed afterwards 
```
/opt/nihao/gcp/ai-platform/ai-gateway/litellm/langchain % python3 tool-agent-openai.py 
/opt/homebrew/lib/python3.12/site-packages/langsmith/client.py:5434: LangChainBetaWarning: The function `loads` is in beta. It is actively being worked on, so the API may change.
  prompt = loads(json.dumps(prompt_object.manifest))
================================ System Message ================================

You are a helpful assistant

============================= Messages Placeholder =============================

{chat_history}

================================ Human Message =================================

{input}

============================= Messages Placeholder =============================

{agent_scratchpad}


> Entering new AgentExecutor chain...

Invoking: `exponentiate` with `{'base': 3, 'exponent': 5}`


243
Invoking: `add` with `{'first_int': 12, 'second_int': 3}`


15
Invoking: `multiply` with `{'first_int': 243, 'second_int': 15}`


3645
Invoking: `exponentiate` with `{'base': 3645, 'exponent': 2}`


13286025The final result is \( 13,286,025 \).

> Finished chain.

/opt/nihao/gcp/ai-platform/ai-gateway/litellm/langchain % python3 tool-agent-openai.py 
/opt/homebrew/lib/python3.12/site-packages/langsmith/client.py:5434: LangChainBetaWarning: The function `loads` is in beta. It is actively being worked on, so the API may change.
  prompt = loads(json.dumps(prompt_object.manifest))
================================ System Message ================================

You are a helpful assistant

============================= Messages Placeholder =============================

{chat_history}

================================ Human Message =================================

{input}

============================= Messages Placeholder =============================

{agent_scratchpad}


> Entering new AgentExecutor chain...

Invoking: `add` with `{'base': 3, 'exponent': 5}`


Traceback (most recent call last):
  File "/opt/nihao/gcp/ai-platform/ai-gateway/litellm/langchain/tool-agent-openai.py", line 42, in <module>
    agent_executor.invoke(
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/chains/base.py", line 164, in invoke
    raise e
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/chains/base.py", line 154, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/agents/agent.py", line 1625, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/agents/agent.py", line 1331, in _take_next_step
    [
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/agents/agent.py", line 1416, in _iter_next_step
    yield self._perform_agent_action(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/agents/agent.py", line 1438, in _perform_agent_action
    observation = tool.run(
                  ^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/langchain_core/tools/base.py", line 586, in run
    raise error_to_raise
  File "/opt/homebrew/lib/python3.12/site-packages/langchain_core/tools/base.py", line 549, in run
    tool_args, tool_kwargs = self._to_args_and_kwargs(tool_input)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/langchain_core/tools/base.py", line 472, in _to_args_and_kwargs
    tool_input = self._parse_input(tool_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/langchain_core/tools/base.py", line 424, in _parse_input
    result = input_args.parse_obj(tool_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pydantic/v1/main.py", line 526, in parse_obj
    return cls(**obj)
           ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for addSchema
first_int
  field required (type=value_error.missing)
second_int
  field required (type=value_error.missing)
/opt/nihao/gcp/ai-platform/ai-gateway/litellm/langchain % python3 tool-agent-openai.py
/opt/homebrew/lib/python3.12/site-packages/langsmith/client.py:5434: LangChainBetaWarning: The function `loads` is in beta. It is actively being worked on, so the API may change.
  prompt = loads(json.dumps(prompt_object.manifest))
================================ System Message ================================

You are a helpful assistant

============================= Messages Placeholder =============================

{chat_history}

================================ Human Message =================================

{input}

============================= Messages Placeholder =============================

{agent_scratchpad}


> Entering new AgentExecutor chain...

Invoking: `add` with `{'base': 3, 'exponent': 5}`


Traceback (most recent call last):
  File "/opt/nihao/gcp/ai-platform/ai-gateway/litellm/langchain/tool-agent-openai.py", line 42, in <module>
    agent_executor.invoke(
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/chains/base.py", line 164, in invoke
    raise e
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/chains/base.py", line 154, in invoke
    self._call(inputs, run_manager=run_manager)
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/agents/agent.py", line 1625, in _call
    next_step_output = self._take_next_step(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/agents/agent.py", line 1331, in _take_next_step
    [
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/agents/agent.py", line 1416, in _iter_next_step
    yield self._perform_agent_action(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/langchain/agents/agent.py", line 1438, in _perform_agent_action
    observation = tool.run(
                  ^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/langchain_core/tools/base.py", line 586, in run
    raise error_to_raise
  File "/opt/homebrew/lib/python3.12/site-packages/langchain_core/tools/base.py", line 549, in run
    tool_args, tool_kwargs = self._to_args_and_kwargs(tool_input)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/langchain_core/tools/base.py", line 472, in _to_args_and_kwargs
    tool_input = self._parse_input(tool_input)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/langchain_core/tools/base.py", line 424, in _parse_input
    result = input_args.parse_obj(tool_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pydantic/v1/main.py", line 526, in parse_obj
    return cls(**obj)
           ^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 2 validation errors for addSchema
first_int
  field required (type=value_error.missing)
second_int
  field required (type=value_error.missing)
```

**Comment by ghost** [comment]
Reopening as this happens when caching is enabled

**Comment by ghost** [comment]
This seems to be related to rebuilding the chunk when there's multiple tool calls

**Comment by ghost** [comment]
```
{
    "id": "chatcmpl-A5kLDlMkX2GRuZ2eCxmGD8cL3j5ST",
    "choices": [
        {
            "finish_reason": "tool_calls",
            "index": 0,
            "message": {
                "content": null,
                "role": "assistant",
                "tool_calls": [
                    {
                        "function": {
                            "arguments": "{\"base\": 3, \"exponent\": 5}",
                            "name": "exponentiate"
                        },
                        "id": "call_VQZdCKFsOKJq9EFNudPHebSt",
                        "type": "function"
                    },
                    {
                        "function": {
                            "arguments": "{\"first_int\": 12, \"second_int\": 3}",
                            "name": "add"
                        },
                        "id": "call_H63gPNEty9qok1OpXzhJoeu9",
                        "type": "function"
                    }
                ],
                "function_call": null
            }
        }
    ],
    "created": 1725933139,
    "model": "gpt-4o-2024-08-06",
    "object": "chat.completion",
    "system_fingerprint": "fp_b2ffeb16ee",
    "usage": {
        "completion_tokens": 55,
        "prompt_tokens": 127,
        "total_tokens": 182
    },
    "service_tier": null,
    "prompt_filter_results": [
        {
            "prompt_index": 0,
            "content_filter_results": {
                "hate": {
                    "filtered": false,
                    "severity": "safe"
                },
                "jailbreak": {
                    "filtered": false,
                    "detected": false
                },
                "self_harm": {
                    "filtered": false,
                    "severity": "safe"
                },
                "sexual": {
                    "filtered": false,
                    "severity": "safe"
                },
                "violence": {
                    "filtered": false,
                    "severity": "safe"
                }
            }
        }
    ]
}
```

**Comment by ghost** [comment]
currently storing: 

```
CACHING (FAILS)

new_chunk: {"id":"chatcmpl-A5k3rbbid1pW5kJ4XB9CeBT5Sj2Xo","choices":[{"index":0,"delta":{"role":"assistant","tool_calls":[{"id":"call_r0vEJvEBg0u3j2N42MKKXCkV","function":{"arguments":"{\"base\": 3, \"exponent\": 5}","name":"add"},"type":"function","index":0}]}}],"created":1725932525,"model":"gpt-4o","object":"chat.completion.chunk","system_fingerprint":"fp_b2ffeb16ee"}
```

**Comment by ghost** [comment]
raw langchain request: 

```
{
    "messages": [
        {
            "role": "system",
            "content": "You are a helpful assistant"
        },
        {
            "role": "user",
            "content": "Take 3 to the fifth power and multiply that by the sum of twelve and three, then square the whole result"
        }
    ],
    "model": "gpt-4o",
    "n": 1,
    // "stream": true,
    "temperature": 0.7,
    "tools": [
        {
            "type": "function",
            "function": {
                "name": "multiply",
                "description": "Multiply two integers together.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "first_int": {
                            "type": "integer"
                        },
                        "second_int": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "first_int",
                        "second_int"
                    ]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "add",
                "description": "Add two integers.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "first_int": {
                            "type": "integer"
                        },
                        "second_int": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "first_int",
                        "second_int"
                    ]
                }
            }
        },
        {
            "type": "function",
            "function": {
                "name": "exponentiate",
                "description": "Exponentiate the base to the exponent power.",
                "parameters": {
                    "type": "object",
                    "properties": {
                        "base": {
                            "type": "integer"
                        },
                        "exponent": {
                            "type": "integer"
                        }
                    },
                    "required": [
                        "base",
                        "exponent"
                    ]
                }
            }
        }
    ]
}
```
