### ISSUE TITLE
Issue with this open interpreter, I do have access to gpt-4 in chatGPT 

### ISSUE THREAD

**Issue by PkPawarat** [BerriAI/litellm#561]
C:\Users\popaw>interpreter

▌ Model set to GPT-4

Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.

Press CTRL-C to exit.
> litellm.set_verbose=True

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 21, in cli
    cli(self)
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\cli\cli.py", line 168, in cli
    interpreter.chat()
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 66, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 87, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 62, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 95, in _streaming_chat
    yield from self._respond()
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 121, in _respond
    yield from respond(self)
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\respond.py", line 57, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\llm\setup_openai_coding_llm.py", line 94, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 718, in wrapper
    raise e
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 677, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 1213, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 2851, in exception_type
    raise e
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 2270, in exception_type
    raise original_exception
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 393, in completion
    raise e
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 375, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "C:\Users\popaw\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.

**Comment by Winds0033** [comment]
I met a same bug on Windows 10

**Comment by ghost** [comment]
hey @PkPawarat @Winds0033 access via chatgpt plus is not the same as the openai api. Are you able to get this working via the openai api?

**Comment by Winds0033** [comment]
@krrishdholakia When I run 'interpreter' in my terminal,It directly shows：
“
 the Model set to GPT-4

Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.
”
So I can't use openai api because at this point, no matter what code I run,the terminals all report errors.

I found that after other users run  ‘interpreter’ in the terminal,it will show:
"Welcome to Open Interpreter.
OpenAI API key not found

To use GPT-4 (recommended) please provide an OpenAI API key.

To use Code-Llama (free but less capable) press enter.
OpenAI API key:
"
But it didn't show on my computer, i tried uninstalling and reinstalling open-interpreter and making sure it was installed,but the problem remains unsolved.

**Comment by ghost** [comment]
@Winds0033 i believe that's an issue for openinterpreter - https://github.com/KillianLucas/open-interpreter/
