### ISSUE TITLE
[Bug]: Error parsing chunk: Expecting property name enclosed in double quotes

### ISSUE THREAD

**Issue by phanminhtai** [BerriAI/litellm#5650]
### What happened?

Occasionally encountering this error when using the Gemini 1.5 Flash model

### Relevant log output

```shell
Streaming error: litellm.APIConnectionError: Error parsing chunk: Expecting property name enclosed in double quotes: line 1 column 2 (char 1),
Received chunk: {
Traceback (most recent call last):
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py", line 1565, in __next__
    return self._common_chunk_parsing_logic(chunk=chunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py", line 1541, in _common_chunk_parsing_logic
    return self.handle_valid_json_chunk(chunk=chunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py", line 1503, in handle_valid_json_chunk
    raise e
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py", line 1495, in handle_valid_json_chunk
    json_chunk = json.loads(chunk)
                 ^^^^^^^^^^^^^^^^^
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python312\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python312\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\utils.py", line 10017, in __next__      
    chunk = next(self.completion_stream)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Nice\AppData\Local\Programs\Python\Python312\Lib\site-packages\litellm\llms\vertex_ai_and_google_ai_studio\gemini\vertex_and_google_ai_studio_gemini.py", line 1569, in __next__
    raise RuntimeError(f"Error parsing chunk: {e},\nReceived chunk: {chunk}")
RuntimeError: Error parsing chunk: Expecting property name enclosed in double quotes: line 1 column 2 (char 1),
Received chunk: {
```

**Comment by ghost** [comment]
Seems like gemini will return invalid json / partial json mid-stream

similar to this - https://github.com/BerriAI/litellm/issues/5479

**Comment by ghost** [comment]
we need to update our test to cover this - https://github.com/BerriAI/litellm/blob/3e34edcff3f22db14239b7a87a9501dd237036a7/litellm/tests/test_streaming.py#L836

**Comment by AyrennC** [comment]
Encountering the same bug with gemini-2.0-thinking-exp in `litellm_stable_release_branch-v1.61.13-stable`

**Comment by paul-gauthier** [comment]
FYI, aider users are reporting this error with the new Gemini 2.5 Pro model. Are we sure this is bad json coming back from google?

**Comment by ghost** [comment]
> Streaming error: litellm.APIConnectionError: Error parsing chunk: Expecting property name enclosed in double quotes: line 1 column 2 (char 1),
Received chunk: {

Pretty confident, since we can see the received chunk in the stream as well. 

Are you seeing it on all requests? @paul-gauthier

**Comment by paul-gauthier** [comment]
I have not seen it personally, 2.5 Pro seems to work fine for me including multiple full benchmark runs.

See the linked aider issue, where it appears to be heavily affecting some users though.

**Comment by ghbalf** [comment]
Here is the error message I receive with aider v0.80.1 and gemini/gemini-2.5-pro-exp-03-25 with architect edit format:

`litellm.APIConnectionError: Error parsing chunk: Expecting property name enclosed in double quotes: line 1 column 2 (char 1),
Received chunk: {
Traceback (most recent call last):
  File "/home/alf/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1525, in __next__
    return self._common_chunk_parsing_logic(chunk=chunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alf/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1499, in 
_common_chunk_parsing_logic
    return self.handle_valid_json_chunk(chunk=chunk)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alf/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1459, in 
handle_valid_json_chunk
    raise e
  File "/home/alf/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1451, in 
handle_valid_json_chunk
    json_chunk = json.loads(chunk)
                 ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/alf/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/litellm/litellm_core_utils/streaming_handler.py", line 1560, in __next__
    chunk = next(self.completion_stream)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alf/.local/share/pipx/venvs/aider-chat/lib/python3.12/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1529, in __next__
    raise RuntimeError(f"Error parsing chunk: {e},\nReceived chunk: {chunk}")
RuntimeError: Error parsing chunk: Expecting property name enclosed in double quotes: line 1 column 2 (char 1),
Received chunk: {
`

**Comment by kinkyninja** [comment]
Same with me, getting frequently this error while streaming via LiteLLM with models: 

gemini/gemini-2.0-flash-thinking-exp-01-21
gemini/gemini-2.5-pro-exp-03-25

**Comment by cbrane** [comment]
i am getting this error every request i try to make with these models: 
gemini-2.5-pro-preview-03-25 & gemini-2.0-flash - using with claude-code-proxy to run gemini models inside claude code and getting every request that i try to send through. 

here's my error message:
POST /v1/messages ✓ 200 OK
claude-3-7-sonnet-20250219 → gemini-2.5-pro-preview-03-25 12 tools 22 messages

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm._turn_on_debug()'.


Provider List: https://docs.litellm.ai/docs/providers

2025-04-10 01:47:17,608 - ERROR - Error in streaming: litellm.APIConnectionError: Error parsing chunk: Expecting property name enclosed in double quotes: line 1 column 2 (char 1),
Received chunk: {
Traceback (most recent call last):
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1491, in __anext__
    return self._common_chunk_parsing_logic(chunk=chunk)
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1443, in _common_chunk_parsing_logic
    return self.handle_valid_json_chunk(chunk=chunk)
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1403, in handle_valid_json_chunk
    raise e
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1395, in handle_valid_json_chunk
    json_chunk = json.loads(chunk)
  File "/Users/connorraney/.local/share/uv/python/cpython-3.10.17-macos-aarch64-none/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/connorraney/.local/share/uv/python/cpython-3.10.17-macos-aarch64-none/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/connorraney/.local/share/uv/python/cpython-3.10.17-macos-aarch64-none/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/litellm_core_utils/streaming_handler.py", line 1671, in __anext__
    async for chunk in self.completion_stream:
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1495, in __anext__
    raise RuntimeError(f"Error parsing chunk: {e},\nReceived chunk: {chunk}")
RuntimeError: Error parsing chunk: Expecting property name enclosed in double quotes: line 1 column 2 (char 1),
Received chunk: {


Full traceback:
Traceback (most recent call last):
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1491, in __anext__
    return self._common_chunk_parsing_logic(chunk=chunk)
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1443, in _common_chunk_parsing_logic
    return self.handle_valid_json_chunk(chunk=chunk)
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1403, in handle_valid_json_chunk
    raise e
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1395, in handle_valid_json_chunk
    json_chunk = json.loads(chunk)
  File "/Users/connorraney/.local/share/uv/python/cpython-3.10.17-macos-aarch64-none/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/connorraney/.local/share/uv/python/cpython-3.10.17-macos-aarch64-none/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/connorraney/.local/share/uv/python/cpython-3.10.17-macos-aarch64-none/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/litellm_core_utils/streaming_handler.py", line 1671, in __anext__
    async for chunk in self.completion_stream:
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1495, in __anext__
    raise RuntimeError(f"Error parsing chunk: {e},\nReceived chunk: {chunk}")
RuntimeError: Error parsing chunk: Expecting property name enclosed in double quotes: line 1 column 2 (char 1),
Received chunk: {

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/connorraney/claude-code-openai/server.py", line 856, in handle_streaming
    async for chunk in response_generator:
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/litellm_core_utils/streaming_handler.py", line 1826, in __anext__
    raise exception_type(
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2214, in exception_type
    raise e
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2190, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: Error parsing chunk: Expecting property name enclosed in double quotes: line 1 column 2 (char 1),
Received chunk: {
Traceback (most recent call last):
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1491, in __anext__
    return self._common_chunk_parsing_logic(chunk=chunk)
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1443, in _common_chunk_parsing_logic
    return self.handle_valid_json_chunk(chunk=chunk)
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1403, in handle_valid_json_chunk
    raise e
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1395, in handle_valid_json_chunk
    json_chunk = json.loads(chunk)
  File "/Users/connorraney/.local/share/uv/python/cpython-3.10.17-macos-aarch64-none/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/Users/connorraney/.local/share/uv/python/cpython-3.10.17-macos-aarch64-none/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/connorraney/.local/share/uv/python/cpython-3.10.17-macos-aarch64-none/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/litellm_core_utils/streaming_handler.py", line 1671, in __anext__
    async for chunk in self.completion_stream:
  File "/Users/connorraney/claude-code-openai/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai/gemini/vertex_and_google_ai_studio_gemini.py", line 1495, in __anext__
    raise RuntimeError(f"Error parsing chunk: {e},\nReceived chunk: {chunk}")
RuntimeError: Error parsing chunk: Expecting property name enclosed in double quotes: line 1 column 2 (char 1),
Received chunk: {

**Comment by dirkpetersen** [comment]
Getting this as well reported it here: 

https://github.com/Aider-AI/aider/issues/3730

**Comment by florian-ernst-alan** [comment]
I keep having this error too. It seems to happen even more with Gemini's latest model (`gemini-2.5-pro-preview-05-06`), especially when there's a very large context at once (sending several files of code at once).

**Comment by ruidazeng** [comment]
> Same with me, getting frequently this error while streaming via LiteLLM with models:
> 
> gemini/gemini-2.0-flash-thinking-exp-01-21 gemini/gemini-2.5-pro-exp-03-25

I am still getting this error in 05/25/2025, I am using gemini-2.5-pro-preview-05-06

**Comment by azgo14** [comment]
@krrishdholakia getting this issue as well. On litellm 1.72.1 with gemini-2.5-pro-preview-05-06

this is a hard blocker pretty much for our litellm use-case. Is the hypothesis still that something is wrong with the gemini api and this isn't an issue on litellm side?

**Comment by azgo14** [comment]
so I dug in a little more here and printed out the chunks after the `Received chunk: {`

```
GEMINI CHUNK: {
GEMINI CHUNK:   "error": {
GEMINI CHUNK:     "code": 500,
GEMINI CHUNK:     "message": "An internal error has occurred. Please retry or report in https://developers.generativeai.google/guide/troubleshooting",
GEMINI CHUNK:     "status": "INTERNAL"
GEMINI CHUNK:   }
GEMINI CHUNK: }
```

so it does seem like a gemini api problem where for errors it returns this other format rather than `data: {...}`

**Comment by mickaelandrieu** [comment]
Hi @azgo14 do you mean we will always get this error every time Gemini is unavailable (as an exemple) ?

**Comment by syberkitten** [comment]
Can confirm it Happens to me as well with gemini-2.5-flash when providing long context window documents.
with gemini-2.0-flash the response simply never returns, I can wait up till 5 minutes or more, eventuall some kind of a network timeout happens. same for gemini-1.5-flash, can wait 5-10 minutes.

I'm uploading a 1000 pages PDF file (whole book) around 38mb size.
smaller chunks work but i didn't test or found exactly the threshold.

**Comment by stronk7** [comment]
Just for the records, I'm getting this with ALL gemini-2.5 models (via Vertex). And with all sort of requests, no matter their size. As soon as one tool call with parameters enters into the history, and the API request is sent, the error happens.

Also, I've tried with stream=false, just to see if that made any difference. Same behaviour and error.

So, I'm not sure the problem is happening with the returned (streamed or no) data. It seems to happen **before** actually sending anything to Vertex. In fact the error is raised in "convert_to_gemini_tool_call_invoke" , aka, OpenAI to Gemini conversion, not the opposite.


Anyway, that's all I've been able to analyse, locally and without debugging anything... but for sure it prevents the (tool) use of any of the Gemini (via Vertex) models.

Ciao :-)
