### ISSUE TITLE
[Bug]: TypeError: run_server() got an unexpected keyword argument 'drop_params'

### ISSUE THREAD

**Issue by CUexter** [BerriAI/litellm#566]
### What happened?

I just installed with `pip install litellm` and ran `litellm--test`

Version: 0.6.0
Python version: 3.11

### Relevant log output

```shell
Traceback (most recent call last):
  File "/home/username/.virtualenvs/autogen-testing-rgnl/bin/litellm", line 8, in <module>
    sys.exit(run_server())
             ^^^^^^^^^^^^
  File "/home/username/.virtualenvs/autogen-testing-rgnl/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/.virtualenvs/autogen-testing-rgnl/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/username/.virtualenvs/autogen-testing-rgnl/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/username/.virtualenvs/autogen-testing-rgnl/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: run_server() got an unexpected keyword argument 'drop_params'
```

**Comment by ishaan-jaff** [comment]
fix pushed in https://github.com/BerriAI/litellm/commit/4059f408d0fd4438f83cccaa26644fb282a10c86

**Comment by CUexter** [comment]
can confirmed it is fixed. Closing issue now
