### ISSUE TITLE
[Bug]: deepcopy Causes Error with pydantic_core._pydantic_core.SerializationIterator Object

### ISSUE THREAD

**Issue by noiji** [BerriAI/litellm#5684]
### What happened?

I encountered an error when calling completion with `tool_calls`. The error occurs during Pydantic validation, where the list temporarily becomes a ValidatorIterator. It seems that deepcopy is called during this validation process, throwing the  error attached below.

The root cause appears to be related to how Pydantic temporarily converts lists into a ValidatorIterator during validation. When deepcopy is called while the data is in this intermediate state, the ValidatorIterator object, which cannot be pickled, causes the error.

I found that replacing deepcopy with `copy.copy` in  [code 1](https://github.com/BerriAI/litellm/blob/cdd7cd4d69585525bc9aaa0e647cdbb38b3ae6c0/litellm/main.py#L749) and [code 2](https://github.com/BerriAI/litellm/blob/cd8d7ca9156a5fc2510db1ef0d43956d3239eccf/litellm/litellm_core_utils/litellm_logging.py#L187) resolves the issue. Since copy.copy performs a shallow copy, it does not attempt to copy the temporary ValidatorIterator, thus preventing the error.

### Relevant log output
```
01:02:08 - LiteLLM:ERROR: utils.py:614 - litellm.utils.py::function_setup() - [Non-Blocking] Traceback (most recent call last):
  File "/Users/noa/Library/Caches/pypoetry/virtualenvs/llm-router-kNmKto9W-py3.12/lib/python3.12/site-packages/litellm/utils.py", line 585, in function_setup
    logging_obj = litellm.litellm_core_utils.litellm_logging.Logging(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/noa/Library/Caches/pypoetry/virtualenvs/llm-router-kNmKto9W-py3.12/lib/python3.12/site-packages/litellm/litellm_core_utils/litellm_logging.py", line 186, in __init__
    self.messages = copy.deepcopy(messages)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 196, in _deepcopy_list
    append(deepcopy(a, memo))
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.4/Frameworks/Python.framework/Versions/3.12/lib/python3.12/copy.py", line 151, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^

TypeError: cannot pickle 'pydantic_core._pydantic_core.SerializationIterator' object
; args - (); kwargs - {'messages': [{'content': 'You are a helpful chatbot', 'role': 'system'}, {'content': 'how's the weather', 'role': 'user'}, {'role': 'assistant', 'content': '', 
'tool_calls': SerializationIterator(index=0, iterator=ValidatorIterator(index=0, schema=Some(TypedDict(TypedDictValidator { fields: [TypedDictField { name: "id", lookup_key: Simple { key: "id", py_key: Py(0x114fb29d0), path: LookupPath([S("id", Py(0x114fb2a00))]) }, name_py: Py(0x1054243f8), required: true, validator: Str(StrValidator { strict: false, coerce_numbers_to_str: false }) }, TypedDictField { name: "function", lookup_key: Simple { key: "function", py_key: Py(0x11548d970), path: LookupPath([S("function", Py(0x1154651b0))]) }, name_py: Py(0x1049b0630), required: true, validator: TypedDict(TypedDictValidator { fields: [TypedDictField { name: "arguments", lookup_key: Simple { key: "arguments", py_key: Py(0x11548d070), path: LookupPath([S("arguments", Py(0x11548cc70))]) }, name_py: Py(0x105421f58), required: true, validator: Str(StrValidator { strict: false, coerce_numbers_to_str: false }) }, TypedDictField { name: "name", lookup_key: Simple { key: "name", py_key: Py(0x114fb2a30), path: LookupPath([S("name", Py(0x114fb2a60))]) }, name_py: Py(0x1054256c0), required: true, validator: Str(StrValidator { strict: false, coerce_numbers_to_str: false }) }], extra_behavior: Forbid, extras_validator: None, strict: false, loc_by_alias: true }) }, TypedDictField { name: "type", lookup_key: Simple { key: "type", py_key: Py(0x114fb2a90), path: LookupPath([S("type", Py(0x114fb2ac0))]) }, name_py: Py(0x105427968), required: true, validator: Literal(LiteralValidator { lookup: LiteralLookup { expected_bool: None, expected_int: None, expected_str: Some({"function": 0}), expected_py_dict: None, expected_py_values: None, values: [Py(0x1049b0630)] }, expected_repr: "'function'", name: "literal['function']" }) }], extra_behavior: Forbid, extras_validator: None, strict: false, loc_by_alias: true }))))}, {'content': 'search result', 'tool_call_id': '55bb9050-a370-4cc8-b76c-aea593966726'}], 'model': 'openai/gpt-4o-2024-08-06', 'frequency_penalty': 0.0, 'logprobs': False, 'n': 1, 'presence_penalty': 0.0, 'stop': [], 'stream': True, 'temperature': 0.7, 'top_p': 1.0, 'api_base': 'https://api.openai.com/v1', 'api_key': 'sk-secret', 'litellm_call_id': 'd1c1'}
```

_No response_

**Comment by niko-nnkn** [comment]
@noiji , I got a similar issue. Have you resolved this one?

**Comment by gustavz** [comment]
We are also seeing this with 1.72.2

**Comment by gustavz** [comment]
@krrishdholakia pushing this issue. We see this issue with failed tool calls:

```
2025-06-27 09:47:26,022 ERROR [LiteLLM Router] [async_function_with_fallbacks] [router.py:3517] litellm.router.py::async_function_with_fallbacks() - Error occurred while trying to do fallbacks - cannot pickle 'pydantic_core._pydantic_core.ValidatorIterator' object
Traceback (most recent call last):
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router.py", line 3356, in async_function_with_fallbacks
    response = await self.async_function_with_retries(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router.py", line 3734, in async_function_with_retries
    raise original_exception
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router.py", line 3625, in async_function_with_retries
    response = await self.make_call(original_function, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router.py", line 3743, in make_call
    response = await response
               ^^^^^^^^^^^^^^
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router.py", line 1133, in _acompletion
    raise e
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router.py", line 1092, in _acompletion
    response = await _response
               ^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1494, in wrapper_async
    raise e
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1310, in wrapper_async
    logging_obj, kwargs = function_setup(
                          ^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/utils.py", line 802, in function_setup
    raise e
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/utils.py", line 769, in function_setup
    logging_obj = LiteLLMLogging(
                  ^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/litellm_logging.py", line 282, in __init__
    self.messages = copy.deepcopy(messages)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX.local/share/uv/python/cpython-3.12.9-macos-aarch64-none/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX.local/share/uv/python/cpython-3.12.9-macos-aarch64-none/lib/python3.12/copy.py", line 196, in _deepcopy_list
    append(deepcopy(a, memo))
           ^^^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX.local/share/uv/python/cpython-3.12.9-macos-aarch64-none/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX.local/share/uv/python/cpython-3.12.9-macos-aarch64-none/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX.local/share/uv/python/cpython-3.12.9-macos-aarch64-none/lib/python3.12/copy.py", line 151, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle 'pydantic_core._pydantic_core.ValidatorIterator' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router.py", line 3509, in async_function_with_fallbacks
    response = await run_async_fallback(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router_utils/fallback_event_handlers.py", line 161, in run_async_fallback
    raise error_from_fallbacks
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router_utils/fallback_event_handlers.py", line 139, in run_async_fallback
    response = await litellm_router.async_function_with_fallbacks(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router.py", line 3542, in async_function_with_fallbacks
    raise original_exception
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router.py", line 3500, in async_function_with_fallbacks
    raise original_exception
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router.py", line 3356, in async_function_with_fallbacks
    response = await self.async_function_with_retries(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router.py", line 3734, in async_function_with_retries
    raise original_exception
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router.py", line 3625, in async_function_with_retries
    response = await self.make_call(original_function, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router.py", line 3743, in make_call
    response = await response
               ^^^^^^^^^^^^^^
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router.py", line 1133, in _acompletion
    raise e
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/router.py", line 1092, in _acompletion
    response = await _response
               ^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1494, in wrapper_async
    raise e
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1310, in wrapper_async
    logging_obj, kwargs = function_setup(
                          ^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/utils.py", line 802, in function_setup
    raise e
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/utils.py", line 769, in function_setup
    logging_obj = LiteLLMLogging(
                  ^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/litellm_logging.py", line 282, in __init__
    self.messages = copy.deepcopy(messages)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX.local/share/uv/python/cpython-3.12.9-macos-aarch64-none/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX.local/share/uv/python/cpython-3.12.9-macos-aarch64-none/lib/python3.12/copy.py", line 196, in _deepcopy_list
    append(deepcopy(a, memo))
           ^^^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX.local/share/uv/python/cpython-3.12.9-macos-aarch64-none/lib/python3.12/copy.py", line 136, in deepcopy
    y = copier(x, memo)
        ^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX.local/share/uv/python/cpython-3.12.9-macos-aarch64-none/lib/python3.12/copy.py", line 221, in _deepcopy_dict
    y[deepcopy(key, memo)] = deepcopy(value, memo)
                             ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/XXX/XXX.local/share/uv/python/cpython-3.12.9-macos-aarch64-none/lib/python3.12/copy.py", line 151, in deepcopy
    rv = reductor(4)
         ^^^^^^^^^^^
TypeError: cannot pickle 'pydantic_core._pydantic_core.ValidatorIterator' object
```
