### ISSUE TITLE
[Bug]: Anthropic Text Completions API is No Longer Supported

### ISSUE THREAD

**Issue by JeremyEastham** [BerriAI/litellm#5701]
### What happened?

When using the `/chat/completions` API with the proxy server, I expect this to proxy to Anthropic's `/v1/messages` endpoint. These requests are currently being proxied to `/v1/complete`, which is unsupported for all of Anthropic's latest models (Claude 3 Haiku, Claude 3 Sonnet, Claude 3 Opus, and Claude 3.5 Sonnet) and is considered a legacy endpoint. The Messages API is supported for all of Anthropic's models (including legacy models), so making this change should not break any workflows.

### Relevant Anthropic Documentation:
- [Model List (Including Supported Endpoints)](https://docs.anthropic.com/en/docs/about-claude/models#model-comparison-table)
- [Completions to Messages Migration Guide](https://docs.anthropic.com/en/api/migrating-from-text-completions-to-messages)
- [Completions API](https://docs.anthropic.com/en/api/complete)
- [Messages API](https://docs.anthropic.com/en/api/messages)

### Relevant log output

```shell
litellm_settings:
  drop_params: true
  set_verbose: true

model_list:
  - model_name: "claude-3-haiku"
    litellm_params:
      model: anthropic/claude-3-haiku-20240307
      api_key: os.environ/ANTHROPIC_API_KEY

(venv) C:\Users\User\LiteLLM>curl -X POST -H "Content-Type: application/json" -d "{ "model": "claude-3-haiku", "messages": [ { "role": "user", "content": "Hello?" } ] }" localhost:8000/chat/completions
{"detail":"AnthropicException - AnthropicException - {"type":"error","error":{"type":"invalid_request_error","message":"\"claude-3-haiku-20240307\" is not supported on this API. Please use the Messages API instead."}}

Traceback (most recent call last):
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\main.py", line 743, in completion
    model_response = anthropic.completion(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\llms\anthropic.py", line 138, in completion
    raise AnthropicError(status_code=response.status_code, message=response.text)
litellm.llms.anthropic.AnthropicError: {"type":"error","error":{"type":"invalid_request_error","message":"\"claude-3-haiku-20240307\" is not supported on this API. Please use the Messages API instead."}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\main.py", line 188, in acompletion
    response =  await loop.run_in_executor(None, func_with_context)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Python311\Lib\concurrent\futures\thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\utils.py", line 1364, in wrapper
    raise e
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\utils.py", line 1293, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\main.py", line 1424, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\utils.py", line 4631, in exception_type
    raise e
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\utils.py", line 3826, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: AnthropicException - {"type":"error","error":{"type":"invalid_request_error","message":"\"claude-3-haiku-20240307\" is not supported on this API. Please use the Messages API instead."}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\proxy\proxy_server.py", line 741, in chat_completion
    response = await llm_router.acompletion(**data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\router.py", line 212, in acompletion
    raise e
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\router.py", line 208, in acompletion
    response = await self.async_function_with_fallbacks(**kwargs)

     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\router.py", line 392, in async_function_with_fallbacks
    raise original_exception
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\router.py", line 344, in async_function_with_fallbacks
    response = await self.async_function_with_retries(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\router.py", line 421, in async_function_with_retries
    raise original_exception
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\router.py", line 404, in async_function_with_retries
    response = await original_function(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\router.py", line 245, in _acompletion
    raise e
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\router.py", line 239, in _acompletion
    response = await litellm.acompletion(**{**data, "messages": messages, "caching": self.cache_responses, "client": model_client, **kwargs})
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\utils.py", line 1460, in wrapper_async
    raise e
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\utils.py", line 1406, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\main.py", line 195, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\utils.py", line 4631, in exception_type
    raise e
  File "C:\Users\User\LiteLLM\venv\Lib\site-packages\litellm\utils.py", line 3826, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: AnthropicException - AnthropicException - {"type":"error","error":{"type":"invalid_request_error","message":"\"claude-3-haiku-20240307\" is not supported on this API. Please use the Messages API instead."}}
"}
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/jeremyeastham/

**Comment by ishaan-jaff** [comment]
hi @JeremyEastham  - based on your stacktrace I can tell you're on an older version of litellm. Please bump to latest and retry, this is already supported 

code logic here: https://github.com/BerriAI/litellm/blob/2efdd2a6a4723616b9dea62594560b4094c08373/litellm/main.py#L1511
