### ISSUE TITLE
[Bug]: Prisma trying to write to read-only `site-packages/prisma` in non_root image

### ISSUE THREAD

**Issue by simonhir** [BerriAI/litellm#5838]
### What happened?

Using the non_root image prisma tries to write to `/usr/local/lib/python3.11/site-packages/prisma/schema.prisma` which is read only and therefore following exception is thrown during startup.
There is already [an according issue for prisma-client-py](https://github.com/RobertCraigie/prisma-client-py/issues/916) which links to [the according prisma docs](https://www.prisma.io/docs/orm/prisma-schema/overview/generators) to change the generation output dir to another location.

### Relevant log output

```shell
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/prisma/generator/generator.py",
line 112, in run
self._on_request(request)
File "/usr/local/lib/python3.11/site-packages/prisma/generator/generator.py",
line 170, in _on_request
self.generate(data)
File "/usr/local/lib/python3.11/site-packages/prisma/generator/generator.py",
line 255, in generate
shutil.copy(data.schema_path, packaged_schema)
File "/usr/local/lib/python3.11/shutil.py", line 431, in copy
copyfile(src, dst, follow_symlinks=follow_symlinks)
File "/usr/local/lib/python3.11/shutil.py", line 258, in copyfile
with open(dst, 'wb') as fdst:
^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.11/site-p
ackages/prisma/schema.prisma'
```

**Comment by ishaan-jaff** [comment]
hi @simonhir can we hop on a call to debug this issue and understand what you need / how to repro this  ? The non_root image should work/start even with that warning 


- my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
- my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/

**Comment by simonhir** [comment]
Hi @ishaan-jaff,
thanks for your fast answer.
To clarify, the image starts in the end successfully and the endpoints are reachable. If you say the error is just some side-effect and can be ignored that would be fine for me.
For me the exception just looked like this prevents some models from generation and can lead to some bugs (didn't find any for now, but just scratched the surface of the features of the application).

**Comment by juan-carvajal** [comment]
Hello @ishaan-jaff Same issue over here, tested models seem to be responding as expected tho
