### ISSUE TITLE
[Bug]: CompletionTokensDetails is not JSON serializable

### ISSUE THREAD

**Issue by mathd** [BerriAI/litellm#5847]
### What happened?

When I use GPT-4o-mini as model, I have an error in the proxy and the request is not logged in the database.
Since, it's not logged, it's not showing in the statistics or in the UI.

### Relevant log output

```shell
14:52:37 - LiteLLM Proxy:ERROR: spend_tracking_utils.py:158 - Error creating spendlogs object - Object of type CompletionTokensDetails is not JSON serializable
Traceback (most recent call last):
  File "/Users/user/litellm/.venv/lib/python3.12/site-packages/litellm/proxy/spend_tracking/spend_tracking_utils.py", line 138, in get_logging_payload
    metadata=json.dumps(clean_metadata),
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
```

**Comment by mathd** [comment]
I've included a pull request for this issue: https://github.com/BerriAI/litellm/pull/5848

**Comment by ghost** [comment]
Hey @mathd this should now be fixed with - https://github.com/BerriAI/litellm/blob/ab153c3e8dab6be093eba3726ada19da176ee8cc/litellm/proxy/spend_tracking/spend_tracking_utils.py#L110
