### ISSUE TITLE
[Bug]: Error when using router with RedisCluster

### ISSUE THREAD

**Issue by Kakadus** [BerriAI/litellm#5882]
### What happened?

We really want to use litellm routers with a RedisCluster, like in this minimal reproduction:

```py
import asyncio

import litellm
from litellm import Router


async def connect_client():
    router = Router(
        model_list=[
            {
                "model_name": "anthropic/claude-3-5-sonnet-20240620",
                "litellm_params": {
                    "model": "anthropic/claude-3-5-sonnet-20240620",
                    "api_key": "...",
                },
            },
        ],
        cache_kwargs={"namespace": "litellm", "db": 1, "startup_nodes": '[{"host": "localhost", "port": 6379}]'},
        redis_host="localhost",
        redis_port=6379,
        redis_password="bitnami",
        cooldown_time=180,
    )

    res = await router.acompletion(
        model="anthropic/claude-3-5-sonnet-20240620",
        messages=[{"content": "what is 10+10?", "role": "user"}],
        stream=False,
    )
    print(res)


litellm.set_verbose = True

if __name__ == "__main__":
    asyncio.run(connect_client())
```

 However, this fails currently fails with the following error. Note that the result is returned correctly, but the two errors indicate that the router functionality is not working properly.

### Relevant log output

```shell
Exception ignored in: <coroutine object RedisCache.ping at 0x77b074d728a0>
Traceback (most recent call last):
  File "/home/.../venv/lib/python3.12/site-packages/litellm/caching.py", line 873, in ping
    async with _redis_client as redis_client:
               ^^^^^^^^^^^^^
  File "/home/.../venv/lib/python3.12/site-packages/redis/asyncio/cluster.py", line 431, in __aenter__
    return await self.initialize()
           ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine ignored GeneratorExit
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<RedisCache.ping() done, defined at /home/.../venv/lib/python3.12/site-packages/litellm/caching.py:870> wait_for=<Future pending cb=[Task.task_wakeup()]>>
get cache: cache key: acab204976b7890b76c21e6fc88cd6491e147f91b53c8c4d675ce72457219382; local_only: True
get cache: cache result: None
set cache: key: acab204976b7890b76c21e6fc88cd6491e147f91b53c8c4d675ce72457219382; value: 1
InMemoryCache: set_cache. current size= 0
get cache: cache key: acab204976b7890b76c21e6fc88cd6491e147f91b53c8c4d675ce72457219382_async_client; local_only: True
get cache: cache result: None
get cache: cache key: acab204976b7890b76c21e6fc88cd6491e147f91b53c8c4d675ce72457219382_async_client; local_only: True
get cache: cache result: None
get cache: cache key: acab204976b7890b76c21e6fc88cd6491e147f91b53c8c4d675ce72457219382_max_parallel_requests_client; local_only: True
get cache: cache result: None


Request to litellm:
litellm.acompletion(api_key='...', model='anthropic/claude-3-5-sonnet-20240620', messages=[{'content': 'what is 10+10?', 'role': 'user'}], caching=False, client=None, timeout=6000, stream=False, metadata={'model_group': 'anthropic/claude-3-5-sonnet-20240620', 'model_group_size': 1, 'deployment': 'anthropic/claude-3-5-sonnet-20240620', 'model_info': {'id': 'acab204976b7890b76c21e6fc88cd6491e147f91b53c8c4d675ce72457219382', 'db_model': False}, 'api_base': None, 'caching_groups': None}, model_info={'id': 'acab204976b7890b76c21e6fc88cd6491e147f91b53c8c4d675ce72457219382', 'db_model': False}, max_retries=0)


08:59:48 - LiteLLM:WARNING: utils.py:351 - `litellm.set_verbose` is deprecated. Please set `os.environ['LITELLM_LOG'] = 'DEBUG'` for debug logs.
ASYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache'): None
Final returned optional params: {}


POST Request Sent from LiteLLM:
curl -X POST \
https://api.anthropic.com/v1/messages \
-H 'accept: *****' -H 'anthropic-version: *****' -H 'content-type: *****' -H 'x-api-key: '...' \
-d '{'messages': [{'role': 'user', 'content': [{'type': 'text', 'text': 'what is 10+10?'}]}], 'max_tokens': 4096, 'model': 'claude-3-5-sonnet-20240620'}'


_is_function_call: False
RAW RESPONSE:
<coroutine object AnthropicChatCompletion.acompletion_function at 0x77b074f3fc10>


RAW RESPONSE:
{"id":"msg_01S1xAYuB75hnGqYEYZ9ovrZ","type":"message","role":"assistant","model":"claude-3-5-sonnet-20240620","content":[{"type":"text","text":"10 + 10 = 20\n\nThe sum of 10 and 10 is 20."}],"stop_reason":"end_turn","stop_sequence":null,"usage":{"input_tokens":14,"output_tokens":28}}


raw model_response: {"id":"msg_01S1xAYuB75hnGqYEYZ9ovrZ","type":"message","role":"assistant","model":"claude-3-5-sonnet-20240620","content":[{"type":"text","text":"10 + 10 = 20\n\nThe sum of 10 and 10 is 20."}],"stop_reason":"end_turn","stop_sequence":null,"usage":{"input_tokens":14,"output_tokens":28}}
Looking up model=claude-3-5-sonnet-20240620 in model_cost_map
Async Wrapper: Completed Call, calling async_success_handler: <bound method Logging.async_success_handler of <litellm.litellm_core_utils.litellm_logging.Logging object at 0x77b075f346b0>>
Logging Details LiteLLM-Success Call: Cache_hit=None
Result: ModelResponse(id='chatcmpl-d3e3539e-1b55-484b-a5e8-a1849925eecc', choices=[Choices(finish_reason='stop', index=0, message=Message(content='10 + 10 = 20\n\nThe sum of 10 and 10 is 20.', role='assistant', tool_calls=None, function_call=None))], created=1727247589, model='claude-3-5-sonnet-20240620', object='chat.completion', system_fingerprint=None, usage=Usage(completion_tokens=28, prompt_tokens=14, total_tokens=42, completion_tokens_details=None))
Looking up model=claude-3-5-sonnet-20240620 in model_cost_map
Logging Details LiteLLM-Async Success Call, cache_hit=None
Looking up model=claude-3-5-sonnet-20240620 in model_cost_map
InMemoryCache: set_cache. current size= 1
Custom Logger Error - Traceback (most recent call last):
  File "/home/.../venv/lib/python3.12/site-packages/litellm/integrations/custom_logger.py", line 226, in async_log_event
    await callback_func(
  File "/home/.../venv/lib/python3.12/site-packages/litellm/router.py", line 3553, in deployment_callback_on_success
    await self.cache.async_increment_cache(
  File "/home/.../venv/lib/python3.12/site-packages/litellm/caching.py", line 2062, in async_increment_cache
    result = await self.redis_cache.async_increment(key, value, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../venv/lib/python3.12/site-packages/litellm/caching.py", line 621, in async_increment
    async with _redis_client as redis_client:
               ^^^^^^^^^^^^^
  File "/home/.../venv/lib/python3.12/site-packages/redis/asyncio/cluster.py", line 431, in __aenter__
    return await self.initialize()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../venv/lib/python3.12/site-packages/redis/asyncio/cluster.py", line 403, in initialize
    await self.nodes_manager.initialize()
  File "/home/.../venv/lib/python3.12/site-packages/redis/asyncio/cluster.py", line 1230, in initialize
    cluster_slots = await startup_node.execute_command("CLUSTER SLOTS")
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/.../venv/lib/python3.12/site-packages/redis/asyncio/cluster.py", line 1048, in execute_command
    await connection.send_packed_command(connection.pack_command(*args), False)
  File "/home/.../venv/lib/python3.12/site-packages/redis/asyncio/connection.py", line 459, in send_packed_command
    await self.connect()
  File "/home/.../venv/lib/python3.12/site-packages/redis/asyncio/connection.py", line 276, in connect
    await self.retry.call_with_retry(
  File "/home/.../venv/lib/python3.12/site-packages/redis/asyncio/retry.py", line 59, in call_with_retry
    return await do()
           ^^^^^^^^^^
  File "/home/.../venv/lib/python3.12/site-packages/redis/asyncio/connection.py", line 682, in _connect
    reader, writer = await asyncio.open_connection(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/streams.py", line 48, in open_connection
    transport, _ = await loop.create_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1103, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 1006, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
asyncio.exceptions.CancelledError
```

**Comment by ghost** [comment]
picking this up. 

---
@Kakadus 

> litellm routers

you just need 1 router, why are you initializing multiple (that's bad, as it creates multiple http clients - more memory utilization)

**Comment by Kakadus** [comment]
Thank you!
> you just need 1 router, why are you initializing multiple (that's bad, as it creates multiple http clients - more memory utilization)

Depending on our use case, we want to have different fallbacks, so we just create a router for each use case. With the memory footprint in mind, I will check our code again..

**Comment by ghost** [comment]
> Depending on our use case, we want to have different fallbacks, so we just create a router for each use case. With the memory footprint in mind, I will check our code again..

Can you share the code for 'different fallbacks'? 

Curious if you just want to be able to set this dynamically - e.g. like this `.completion(..,fallbacks=[..])`

**Comment by Kakadus** [comment]
> Can you share the code for 'different fallbacks'?

sadly, it's behind IP (and the code there is quite nested), but we set the fallbacks argument when constructing the routers like

```py
router1 = Router(..., fallbacks=[..])
router2 = Router(..., fallbacks=[..])
```

> Curious if you just want to be able to set this dynamically - e.g. like this .completion(..,fallbacks=[..])

yes, that should work in our case! We have overlooked the fallbacks kwarg in `async_function_with_fallbacks` - we should be able to use this. Thanks <:

**Comment by Kakadus** [comment]
Coming back to this bug: Note that the traceback logged with `Custom Logger Error` is happening because the event loop is closed when the script ends. Adding a `asyncio.run(asyncio.sleep(10))` in the end waits that all events are finished.

I see the problem in 
```py
Exception ignored in: <coroutine object RedisCache.ping at 0x77b074d728a0>
Traceback (most recent call last):
  File "/home/.../venv/lib/python3.12/site-packages/litellm/caching.py", line 873, in ping
    async with _redis_client as redis_client:
               ^^^^^^^^^^^^^
  File "/home/.../venv/lib/python3.12/site-packages/redis/asyncio/cluster.py", line 431, in __aenter__
    return await self.initialize()
           ^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine ignored GeneratorExit
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<RedisCache.ping() done, defined at /home/.../venv/lib/python3.12/site-packages/litellm/caching.py:870> wait_for=<Future pending cb=[Task.task_wakeup()]>>
```

and 
```py
InMemoryCache: set_cache. current size= 1
```

which indicates to me that the redis cluster is not used.

**Comment by ghost** [comment]
> which indicates to me that the redis cluster is not used.

this is an incorrect conclusion to draw, based on the error trace. redis cluster initialization returns the redis client. 

@Kakadus now that the issue is isolated to being related to just how tasks/scripts work, i'm going to close this out - as this isn't an issue i'm seeing when running litellm on a server 

let me know if you feel differently.

**Comment by john-groves-bread** [comment]
@krrishdholakia - I am seeing the same task error related to the Redis Cluster when running a moderate level of concurrent requests (~30) on the Litellm Proxy:
> RuntimeError: coroutine ignored GeneratorExit
Task was destroyed but it is pending!
