### ISSUE TITLE
[Bug]: Bad Request for Vertex AI Studio with LiteLLM Proxy.

### ISSUE THREAD

**Issue by js8544** [BerriAI/litellm#5888]
### What happened?

LiteLLM Proxy server puts an extra `max_retries` argument in generation_config.
```
23:18:16 - LiteLLM Proxy:ERROR: proxy_server.py:3324 - litellm.proxy.proxy_server.chat_completion(): Exception occured - litellm.BadRequestError: VertexAIException BadRequestError - {
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"max_retries\" at 'generation_config': Cannot find field.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "generation_config",
            "description": "Invalid JSON payload received. Unknown name \"max_retries\" at 'generation_config': Cannot find field."
          }
        ]
      }
    ]
  }
}
Traceback (most recent call last):
  File "/opt/anaconda3/envs/project/lib/python3.12/site-packages/litellm/llms/vertex_ai_and_google_ai_studio/gemini/vertex_and_google_ai_studio_gemini.py", line 1209, in async_completion
    response = await client.post(api_base, headers=headers, json=request_body)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/project/lib/python3.12/site-packages/litellm/llms/custom_httpx/http_handler.py", line 149, in post
    raise e
  File "/opt/anaconda3/envs/project/lib/python3.12/site-packages/litellm/llms/custom_httpx/http_handler.py", line 113, in post
    response.raise_for_status()
  File "/opt/anaconda3/envs/project/lib/python3.12/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://us-central1-aiplatform.googleapis.com/v1/projects/project/locations/us-central1/publishers/google/models/gemini-flash-experimental:generateContent'
```
I sent the request using openai library
```python
import openai

client = openai.OpenAI(api_key="anything", base_url="http://0.0.0.0:4000")
response = client.chat.completions.create(
        model="gemini-flash-experimental",
        messages=[{"role": "user", "content": "Hello, who are you?"}],
    )
    print(response)
```
It works if I manually remove the `max_retires` argument from optional_params in `litellm/llms/vertex_ai_and_google_ai_studio/gemini/transformation.py`
```python
# litellm/llms/vertex_ai_and_google_ai_studio/gemini/transformation.py: 61
remove_keys = []
    for k, v in optional_params.items():
        if k.startswith("litellm_param_"):
            litellm_params.update({k: v})
            remove_keys.append(k)
        if k == "max_retries": # manually removing max_retries works
            litellm_params.update({"max_retries": v})
            remove_keys.append(k)
    optional_params = {k: v for k, v in optional_params.items() if k not in remove_keys}
```

### Relevant log output

```shell
23:18:16 - LiteLLM Proxy:ERROR: proxy_server.py:3324 - litellm.proxy.proxy_server.chat_completion(): Exception occured - litellm.BadRequestError: VertexAIException BadRequestError - {
  "error": {
    "code": 400,
    "message": "Invalid JSON payload received. Unknown name \"max_retries\" at 'generation_config': Cannot find field.",
    "status": "INVALID_ARGUMENT",
    "details": [
      {
        "@type": "type.googleapis.com/google.rpc.BadRequest",
        "fieldViolations": [
          {
            "field": "generation_config",
            "description": "Invalid JSON payload received. Unknown name \"max_retries\" at 'generation_config': Cannot find field."
          }
        ]
      }
    ]
  }
}
Traceback (most recent call last):
  File "/opt/anaconda3/envs/project/lib/python3.12/site-packages/litellm/llms/vertex_ai_and_google_ai_studio/gemini/vertex_and_google_ai_studio_gemini.py", line 1209, in async_completion
    response = await client.post(api_base, headers=headers, json=request_body)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/project/lib/python3.12/site-packages/litellm/llms/custom_httpx/http_handler.py", line 149, in post
    raise e
  File "/opt/anaconda3/envs/project/lib/python3.12/site-packages/litellm/llms/custom_httpx/http_handler.py", line 113, in post
    response.raise_for_status()
  File "/opt/anaconda3/envs/project/lib/python3.12/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://us-central1-aiplatform.googleapis.com/v1/projects/project/locations/us-central1/publishers/google/models/gemini-flash-experimental:generateContent'
```

**Comment by superpoussin22** [comment]
@ishaan-jaff : can reproduce it with flash-002 and pro-002 models but not with 001 models  didn't try with experimental
