### ISSUE TITLE
[Bug]: Anthropic tool calls fail when tool is a pydantic object

### ISSUE THREAD

**Issue by bachya** [BerriAI/litellm#6084]
### What happened?

This is using `litellm` 1.48.16. I am attempting a streaming `acompletion` call to Anthropic.

This is my prompt:

```
Summarize the contents of this URL: https://www.cnn.com/2024/10/05/weather/tropical-depression-florida-gulf-of-mexico/index.html. Also, do the same for this URL: https://www.espn.com/nfl/story/_/id/41624618/dolphins-activate-odell-beckham-jr-ahead-game-vs-pats.
```

...and this is my tool definition:

```json
"tools": [
    {
        "type": "function",
        "function": {
            "name": "web_scraper",
            "description": "Scrape the contents of a URL",
            "parameters": {
                "type": "object",
                "properties": {
                    "url": {
                        "type": "string",
                        "description": "The fully-qualified URL"
                    }
                },
                "required": [
                    "url"
                ]
            }
        }
    }
]
```

### Relevant log output

```shell
test-app  | Request to litellm:
test-app  | litellm.acompletion(stream=True, temperature=0.7, timeout=30.0, tools=[Tool(type='function', function=Function(description='Scrape the contents of a URL', name='web_scraper', parameters={'type': 'object', 'properties': {'url': {'type': 'string', 'description': 'The fully-qualified URL'}}, 'required': ['url']}, strict=False))], api_key='REDACTED', stream_options={'include_usage': True}, messages=[{'role': <MessageRole.USER: 'user'>, 'content': 'Summarize the contents of this URL: https://www.cnn.com/2024/10/05/weather/tropical-depression-florida-gulf-of-mexico/index.html. Also, do the same for this URL: https://www.espn.com/nfl/story/_/id/41624618/dolphins-activate-odell-beckham-jr-ahead-game-vs-pats.'}], model='anthropic/claude-3-5-sonnet-20240620', drop_params=True)
test-app  |
test-app  |
test-app  | ASYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache'): None
test-app  | Final returned optional params: {'temperature': 0.7, 'stream': True, 'tools': [Tool(type='function', function=Function(description='Scrape the contents of a URL', name='web_scraper', parameters={'type': 'object', 'properties': {'url': {'type': 'string', 'description': 'The fully-qualified URL'}}, 'required': ['url']}, strict=False))]}
test-app  |
test-app  | Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
test-app  | LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.
test-app  |
test-app  | Traceback (most recent call last):
test-app  |   File "/app/.venv/lib/python3.12/site-packages/litellm/main.py", line 1658, in completion
test-app  |     response = anthropic_chat_completions.completion(
test-app  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test-app  |   File "/app/.venv/lib/python3.12/site-packages/litellm/llms/anthropic/chat/handler.py", line 447, in completion
test-app  |     data = AnthropicConfig()._transform_request(
test-app  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
test-app  |   File "/app/.venv/lib/python3.12/site-packages/litellm/llms/anthropic/chat/transformation.py", line 285, in _transform_request
test-app  |     new_tool = tool["function"]
test-app  |                ~~~~^^^^^^^^^^^^
test-app  | TypeError: 'Tool' object is not subscriptable
test-app  |
```

**Comment by ghost** [comment]
> Tool' object is not subscriptable

Is this some sort of pydantic object that's being passed in? @bachya

**Comment by ghost** [comment]
> tools': [Tool(type='function

looks like it

**Comment by bachya** [comment]
Ah, yes, good find—I'm parsing the input as that Pydantic object. I'll make sure to render it out as a dict.
