### ISSUE TITLE
[Bug]: DB Connection Failed

### ISSUE THREAD

**Issue by BeylasanRuzaiqi** [BerriAI/litellm#6099]
### What happened?

Upon connecting postgres database and litellm, i got this error.

Litellm.yaml file attached.

We also validated login details of postgres and it works.
[litellm.txt](https://github.com/user-attachments/files/17278694/litellm.txt)

### Relevant log output

```shell
warnings.warn(
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_spend" has conflict with protected namespace "model_".
 
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_aliases" has conflict with protected namespace "model_".
 
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_group" has conflict with protected namespace "model_".
 
You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
Prisma schema loaded from schema.prisma
Datasource "client": PostgreSQL database "litellm", schema "public" at "10.0.128.182:5432"
 
Error: P1000: Authentication failed against database server at `10.0.128.182`, the provided database credentials for `litellm` are not valid.
 
Please make sure to provide valid database credentials for the database server at `10.0.128.182`.
INFO:     Started server process [1]
INFO:     Waiting for application startup.
{"is_panic":false,"message":"Authentication failed against database server at `10.0.128.182`, the provided database credentials for `litellm` are not valid.\n\nPlease make sure to provide valid database credentials for the database server at `10.0.128.182`.","meta":{"database_user":"litellm","database_host":"10.0.128.182"},"error_code":"P1000"}
12:40:17 - LiteLLM Proxy:ERROR: proxy_server.py:2344 - litellm.proxy_server.py::add_deployment() - Error getting new models from DB - All connection attempts failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 122, in _connect
```

**Comment by jruokola** [comment]
Test with the new docker image litellm-database and check your connect string

**Comment by BryceAmackerLE** [comment]
I am also getting this error randomly every couple of days. We are using RDS but do not have any models configured in the DB, just the config file. We're getting this same error from our ECS hosted LiteLLM Service, which results in the service being marked unhealthy and killed by the health checker. Is there any way to configure LiteLLM to not exit on a failed DB connection, or stop checking for DB models when none are configured?

**Comment by rromanchuk** [comment]
@BryceAmackerLE were you using RDS with IAM?  I'm randomly getting these  `All connection attempts failed` but related error messages are getting swallowed.  It only happens after sometime after startup, and it's clearly reading and writing. 

I would have guessed something like this https://github.com/BerriAI/litellm/issues/5896
