### ISSUE TITLE
How to deal with this?

### ISSUE THREAD

**Issue by Ran2909** [BerriAI/litellm#610]
Traceback (most recent call last):
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 256, in completion
    model, custom_llm_provider = get_llm_provider(model=model, custom_llm_provider=custom_llm_provider, api_base=api_base)
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 1483, in get_llm_provider
    raise e
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 1480, in get_llm_provider
    raise ValueError(f"LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/{model}',..)` Learn more: https://docs.litellm.ai/docs/providers")
ValueError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/gpt-4',..)` Learn more: https://docs.litellm.ai/docs/providers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\core.py", line 26, in cli
    cli(self)
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\cli\cli.py", line 254, in cli
    interpreter.chat()
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\core.py", line 88, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\core.py", line 109, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 62, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\core.py", line 117, in _streaming_chat
    yield from self._respond()
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\core.py", line 143, in _respond
    yield from respond(self)
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\core\respond.py", line 44, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\llm\convert_to_coding_llm.py", line 19, in coding_llm
    for chunk in text_llm(messages):
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\interpreter\llm\setup_text_llm.py", line 117, in base_llm
    return litellm.completion(**params)
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 792, in wrapper
    raise e
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 751, in wrapper
    result = original_function(*args, **kwargs)
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\main.py", line 1183, in completion
    raise exception_type(
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 2959, in exception_type
    raise e
  File "C:\Users\29098\AppData\Local\Programs\Python\Python310\lib\site-packages\litellm\utils.py", line 2941, in exception_type
    raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/gpt-4',..)` Learn more: https://docs.litellm.ai/docs/providers

**Comment by ghost** [comment]
@Ran2909 this is a known bug on open interpreter - cc: @ericallren
