### ISSUE TITLE
[Bug]: Schema migrations are not backwards compatible

### ISSUE THREAD

**Issue by micahjsmith** [BerriAI/litellm#6124]
### What happened?

I updated a running llmproxy deployment to a new version. The deployment creates a new container with the new version, verifies its health, and then deletes the old container. In the moment that both containers exist, schema migrations are applied that seem to be incompatible with the old container. I get `The column LiteLLM_UserTable.metadata does not exist in the current database.` on the *old* version, which shortly after is killed. The new version has no errors. However any existing connections connected to the old version would potentially experience errors.

In general, schema migrations should be backwards compatible and there should be a paved path for applying schema migrations that take some destructive action like deleting a column. (For example, an upgrade to version X followed by an upgrade to version Y.)

* Old version: litellm-database:main-v1.47.2
* New version: litellm-database:main-v1.48.6
* Database: postgres 15

Suggestions
* make schema migrations more carefully
* include a doc page on https://docs.litellm.ai/docs/proxy/prod about any recommended procedure to perform version upgrades

### Relevant log output

```shell
Uncaught signal: 2, pid=106, tid=106, fault_addr=0.
prisma.errors.DataError: The column `LiteLLM_UserTable.metadata` does not exist in the current database.
raise prisma_errors.DataError(data[0])
File "/usr/local/lib/python3.11/site-packages/prisma/engine/utils.py", line 200, in handle_response_errors
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return utils.handle_response_errors(resp, errors_data)
File "/usr/local/lib/python3.11/site-packages/prisma/engine/http.py", line 141, in request
           ^^^^^^^^^^^^^^^^^^^
    return await self.request(
File "/usr/local/lib/python3.11/site-packages/prisma/engine/query.py", line 244, in query
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return await self._engine.query(builder.build(), tx_id=self._tx_id)
File "/usr/local/lib/python3.11/site-packages/prisma/client.py", line 525, in _execute
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    resp = await self._client._execute(
File "/usr/local/lib/python3.11/site-packages/prisma/actions.py", line 5614, in find_many
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    response = await self.db.litellm_usertable.find_many(
File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 1587, in get_data
    raise e
File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 1787, in get_data
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    result = await func(*args, **kwargs)
File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 133, in wrapper
    raise e
File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 206, in wrapper
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ret = await target(*args, **kwargs)
File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    users_to_reset = await prisma_client.get_data(
File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 2690, in reset_budget
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
"Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/apscheduler/executors/base_py3.py", line 30, in run_coroutine_job
    retval = await job.func(*job.args, **job.kwargs)"
Job "reset_budget (trigger: interval[0:09:57], next run at: 2024-10-08 18:29:11 UTC)" raised an exception
```

**Comment by ghost** [comment]
Hey @micahjsmith if i understand the issue correctly

- a column was added (not deleted)

what does 'backwards compatible' mean in this context? 

We did introduce a way to disable automatic schema updates - https://docs.litellm.ai/docs/proxy/configs#general_settings---reference

<img width="1026" alt="Screenshot 2024-10-11 at 11 37 12 PM" src="https://github.com/user-attachments/assets/e46080ae-9167-44bd-8bf2-2ebcf2fe45b2">

**Comment by micahjsmith** [comment]
can't reproduce further
