### ISSUE TITLE
[Bug]: litellm.types.guardrails.GuardrailItem() argument after ** must be a mapping

### ISSUE THREAD

**Issue by elvis-cai** [BerriAI/litellm#6127]
### What happened?

A bug happened!
can not start with following config according to the doc https://docs.litellm.ai/docs/proxy/guardrails/pii_masking_v2
```
      guardrails:
        - guardrail_name: "presidio-pre-guard"
          litellm_params:
            guardrail: presidio
            mode: "pre_call"
```

### Relevant log output

```shell
{"message": "error initializing guardrails litellm.types.guardrails.GuardrailItem() argument after ** must be a mapping, not str", "level": "ERROR", "timestamp": "2024-10-09T00:10:36.771482"}
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 732, in lifespan
async with self.lifespan_context(app) as maybe_state:
File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 608, in __aenter__
await self._router.startup()
File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 709, in startup
await handler()
File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2782, in startup_event
await initialize(**worker_config)
File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2465, in initialize
) = await proxy_config.load_config(router=llm_router, config_file_path=config)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 1631, in load_config
guardrail_name_config_map = initialize_guardrails(
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/litellm/proxy/guardrails/init_guardrails.py", line 79, in initialize_guardrails
raise e
File "/usr/local/lib/python3.11/site-packages/litellm/proxy/guardrails/init_guardrails.py", line 41, in initialize_guardrails
guardrail_item = GuardrailItem(**v, guardrail_name=k)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: litellm.types.guardrails.GuardrailItem() argument after ** must be a mapping, not str
Application startup failed. Exiting.
[1;37m#------------------------------------------------------------#[0m
[1;37m# #[0m
[1;37m# 'This product would be better if...' #[0m
[1;37m# https://github.com/BerriAI/litellm/issues/new #[0m
[1;37m# #[0m
[1;37m#------------------------------------------------------------#[0m
Thank you for using LiteLLM! - Krrish & Ishaan
[1;31mGive Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new[0m
[94m
Setting Cache on Proxy
[94m Initialized Failure Callbacks - ['prometheus'] [0m
```
```


### Twitter / LinkedIn details

_No response_

**Comment by elvis-cai** [comment]
it works using v1 config in callback btw

**Comment by elvis-cai** [comment]
close the issue since it's the format issue in litellm config setting
