### ISSUE TITLE
[Bug]: Drop 'strict' / 'additionalProperties' from tools schema when it's not OpenAI

### ISSUE THREAD

**Issue by Clad3815** [BerriAI/litellm#6136]
### What happened?

When we use structured output for the tools schema it's will raise an error with some provider (Example with gemini).

My tool format:
```js
                {
                    "name": "internet_search",
                    "description": "This function performs an internet search. It takes a detailed search query or question as input and returns relevant, up-to-date information from the web. For best results, provide a complete, specific question or search phrase rather than just keywords. The more precise and contextual the query, the more accurate and useful the search results will be.",
                    "parameters": {
                        "type": "object",
                        "properties": {
                            "query": {
                                "type": "string",
                                "description": "A detailed search query or question. This should be a complete sentence or phrase that clearly expresses what information you're looking for. The more specific and contextual the query, the better the results.",
                            },
                            "relatedQueries": {
                                "type": "array",
                                "items": {
                                    "type": "string"
                                },
                                "description": "An optional list of related queries or questions that provide additional context or background information for the main query. These can help narrow down the search results or provide more specific details.",
                            }
                        },
                        "required": ["query"],
                        "additionalProperties": false,
                        "strict": true
                    }
                },

```

Will be cool to keep the feature of OpenAI and just drop it when a provider don't allow it

### Relevant log output

```shell
APIError: litellm.BadRequestError: VertexAIException BadRequestError - b'{\n  "error": {\n    "code": 400,\n    "message": "Invalid JSON payload received. Unknown name \\"additionalProperties\\" at \'tools[0].function_declarations[0].parameters.properties[3].value\': Cannot find field.\\nInvalid JSON payload received. Unknown name \\"strict\\" at \'tools[0].function_declarations[0].parameters.properties[3].value\': Cannot find field.\\nInvalid JSON payload received. Unknown name \\"additionalProperties\\" at \'tools[0].function_declarations[0].parameters\': Cannot find field.\\nInvalid JSON payload received. Unknown name \\"strict\\" at \'tools[0].function_declarations[0].parameters\': Cannot find field.",\n    "status": "INVALID_ARGUMENT",\n    "details": [\n      {\n        "@type": "type.googleapis.com/google.rpc.BadRequest",\n        "fieldViolations": [\n          {\n            "field": "tools[0].function_declarations[0].parameters.properties[3].value",\n            "description": "Invalid JSON payload received. Unknown name \\"additionalProperties\\" at \'tools[0].function_declarations[0].parameters.properties[3].value\': Cannot find field."\n          },\n          {\n            "field": "tools[0].function_declarations[0].parameters.properties[3].value",\n            "description": "Invalid JSON payload received. Unknown name \\"strict\\" at \'tools[0].function_declarations[0].parameters.properties[3].value\': Cannot find field."\n          },\n          {\n            "field": "tools[0].function_declarations[0].parameters",\n            "description": "Invalid JSON payload received. Unknown name \\"additionalProperties\\" at \'tools[0].function_declarations[0].parameters\': Cannot find field."\n          },\n          {\n            "field": "tools[0].function_declarations[0].parameters",\n            "description": "Invalid JSON payload received. Unknown name \\"strict\\" at \'tools[0].function_declarations[0].parameters\': Cannot find field."\n          }\n        ]\n      }\n    ]\n  }\n}\n'
    at Stream.iterator (C:\Clad_Work\local-artefacts\node_modules\openai\streaming.js:39:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async MessageHandler.processStream (C:\Clad_Work\local-artefacts\server\server.js:1368:26)
    at async MessageHandler.handleMessage (C:\Clad_Work\local-artefacts\server\server.js:1166:13) {
  status: undefined,
  headers: undefined,
  request_id: undefined,
  error: {
    message: `litellm.BadRequestError: VertexAIException BadRequestError - b'{\\n  "error": {\\n    "code": 400,\\n    "message": "Invalid JSON payload received. Unknown name \\\\"additionalProperties\\\\" at \\'tools[0].function_declarations[0].parameters.properties[3].value\\': Cannot find field.\\\\nInvalid JSON payload received. Unknown name \\\\"strict\\\\" at \\'tools[0].function_declarations[0].parameters.properties[3].value\\': Cannot find field.\\\\nInvalid JSON payload received. Unknown name \\\\"additionalProperties\\\\" at \\'tools[0].function_declarations[0].parameters\\': Cannot find field.\\\\nInvalid JSON payload received. Unknown name \\\\"strict\\\\" at \\'tools[0].function_declarations[0].parameters\\': Cannot find field.",\\n    "status": "INVALID_ARGUMENT",\\n    "details": [\\n      {\\n        "@type": "type.googleapis.com/google.rpc.BadRequest",\\n        "fieldViolations": [\\n          {\\n            "field": "tools[0].function_declarations[0].parameters.properties[3].value",\\n            "description": "Invalid JSON payload received. Unknown name \\\\"additionalProperties\\\\" at \\'tools[0].function_declarations[0].parameters.properties[3].value\\': Cannot find field."\\n          },\\n          {\\n            "field": "tools[0].function_declarations[0].parameters.properties[3].value",\\n            "description": "Invalid JSON payload received. Unknown name \\\\"strict\\\\" at \\'tools[0].function_declarations[0].parameters.properties[3].value\\': Cannot find field."\\n          },\\n          {\\n            "field": "tools[0].function_declarations[0].parameters",\\n            "description": "Invalid JSON payload received. Unknown name \\\\"additionalProperties\\\\" at \\'tools[0].function_declarations[0].parameters\\': Cannot find field."\\n          },\\n          {\\n            "field": "tools[0].function_declarations[0].parameters",\\n            "description": "Invalid JSON payload received. Unknown name \\\\"strict\\\\" at \\'tools[0].function_declarations[0].parameters\\': Cannot find field."\\n          }\\n        ]\\n      }\\n    ]\\n  }\\n}\\n'`,
    type: null,
    param: null,
    code: '400'
  },
  code: '400',
  param: null,
  type: null
}
```

**Comment by ghost** [comment]
Hey @Clad3815 i'm assuming this is for vllm? we already support this - https://docs.litellm.ai/docs/providers/vllm#usage---litellmcompletion-calling-vllm-endpoint

use the `hosted_vllm/` route.

**Comment by ghost** [comment]
Nevermind, this is for vertex. 

@Clad3815 can i see your config? We already do this for vertex - https://github.com/BerriAI/litellm/blob/60baa65e0ec4827d27c3b15c14a4f921b1e66121/litellm/utils.py#L3026

**Comment by Clad3815** [comment]
Here is my config, using last stable docker version:

```
  - model_name: gemini-1.5-flash-002
    litellm_params:
      model: gemini/gemini-1.5-flash-002

  - model_name: gemini-1.5-pro-002
    litellm_params:
      model: gemini/gemini-1.5-pro-002
```

**Comment by ghost** [comment]
> My tool format:


can you share the complete curl? @Clad3815 i'll add a test against this. I can see our logic should already handle this

**Comment by ghost** [comment]
fixed, i realized we were doing this for only vertex response_schema not tool calls.

**Comment by ghost** [comment]
Curious - how did you run into this issue? @Clad3815 

was there a client library passing 'additionalProperties' to vertex?

**Comment by Clad3815** [comment]
@krrishdholakia 

![image](https://github.com/user-attachments/assets/389f6364-f4e5-4c44-87e4-c4af82a4ef1e)

I'm building my own chat app and I use litellm to enable access to all LLM

**Comment by ghost** [comment]
Nice ui - let me know once it's live, happy to include here - https://docs.litellm.ai/docs/project

**Comment by Clad3815** [comment]
Thanks @krrishdholakia I will, the main goal is to have an interface fully optimised for the artefact stuff
![image](https://github.com/user-attachments/assets/dd122ae0-f62d-4c0a-bbc7-a6f38f05adf2)

The UI still in beta 😄
