### ISSUE TITLE
[Bug]: Parallel Request Limiter: Error getting user object

### ISSUE THREAD

**Issue by xingyaoww** [BerriAI/litellm#6206]
### What happened?

LiteLLM doesn't respond to certain requests - especially requests that input longer context - while shorter one have no error and throw the following errors.

I've attached [litellm-bug-reproduce.txt](https://github.com/user-attachments/files/17359035/litellm-bug-reproduce.txt) for code to reproduce this bug on my llm-proxy running `main-v1.49.2`

### Relevant log output

```shell
litellm-deployment-66669684bd-27fzq litellm 03:15:42 - LiteLLM Proxy:DEBUG: parallel_request_limiter.py:40 - current: None
litellm-deployment-66669684bd-27fzq litellm --- Logging error ---
litellm-deployment-66669684bd-27fzq litellm Traceback (most recent call last):
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/auth/auth_checks.py", line 426, in get_user_object
litellm-deployment-66669684bd-27fzq litellm     raise Exception
litellm-deployment-66669684bd-27fzq litellm Exception
litellm-deployment-66669684bd-27fzq litellm
litellm-deployment-66669684bd-27fzq litellm During handling of the above exception, another exception occurred:
litellm-deployment-66669684bd-27fzq litellm
litellm-deployment-66669684bd-27fzq litellm Traceback (most recent call last):
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/hooks/parallel_request_limiter.py", line 740, in get_internal_user_object
litellm-deployment-66669684bd-27fzq litellm     _user_id_rate_limits = await get_user_object(
litellm-deployment-66669684bd-27fzq litellm                            ^^^^^^^^^^^^^^^^^^^^^^
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 219, in wrapper
litellm-deployment-66669684bd-27fzq litellm     raise e
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 146, in wrapper
litellm-deployment-66669684bd-27fzq litellm     result = await func(*args, **kwargs)
litellm-deployment-66669684bd-27fzq litellm              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/auth/auth_checks.py", line 448, in get_user_object
litellm-deployment-66669684bd-27fzq litellm     raise ValueError(
litellm-deployment-66669684bd-27fzq litellm ValueError: User doesn't exist in db. 'user_id'=admin. Create user via `/user/new` call. Got error -
litellm-deployment-66669684bd-27fzq litellm
litellm-deployment-66669684bd-27fzq litellm During handling of the above exception, another exception occurred:
litellm-deployment-66669684bd-27fzq litellm
litellm-deployment-66669684bd-27fzq litellm Traceback (most recent call last):
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/logging/__init__.py", line 1110, in emit
litellm-deployment-66669684bd-27fzq litellm     msg = self.format(record)
litellm-deployment-66669684bd-27fzq litellm           ^^^^^^^^^^^^^^^^^^^
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/logging/__init__.py", line 953, in format
litellm-deployment-66669684bd-27fzq litellm     return fmt.format(record)
litellm-deployment-66669684bd-27fzq litellm            ^^^^^^^^^^^^^^^^^^
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/logging/__init__.py", line 687, in format
litellm-deployment-66669684bd-27fzq litellm     record.message = record.getMessage()
litellm-deployment-66669684bd-27fzq litellm                      ^^^^^^^^^^^^^^^^^^^
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/logging/__init__.py", line 377, in getMessage
litellm-deployment-66669684bd-27fzq litellm     msg = msg % self.args
litellm-deployment-66669684bd-27fzq litellm           ~~~~^~~~~~~~~~~
litellm-deployment-66669684bd-27fzq litellm TypeError: not all arguments converted during string formatting
litellm-deployment-66669684bd-27fzq litellm Call stack:
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/bin/litellm", line 8, in <module>
litellm-deployment-66669684bd-27fzq litellm     sys.exit(run_server())
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
litellm-deployment-66669684bd-27fzq litellm     return self.main(*args, **kwargs)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
litellm-deployment-66669684bd-27fzq litellm     rv = self.invoke(ctx)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
litellm-deployment-66669684bd-27fzq litellm     return ctx.invoke(self.callback, **ctx.params)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
litellm-deployment-66669684bd-27fzq litellm     return __callback(*args, **kwargs)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_cli.py", line 711, in run_server
litellm-deployment-66669684bd-27fzq litellm     uvicorn.run(app, host=host, port=port)  # run uvicorn
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 575, in run
litellm-deployment-66669684bd-27fzq litellm     server.run()
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 65, in run
litellm-deployment-66669684bd-27fzq litellm     return asyncio.run(self.serve(sockets=sockets))
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
litellm-deployment-66669684bd-27fzq litellm     return runner.run(main)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
litellm-deployment-66669684bd-27fzq litellm     return self._loop.run_until_complete(task)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi
litellm-deployment-66669684bd-27fzq litellm     result = await app(  # type: ignore[func-returns-value]
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
litellm-deployment-66669684bd-27fzq litellm     return await self.app(scope, receive, send)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
litellm-deployment-66669684bd-27fzq litellm     await super().__call__(scope, receive, send)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
litellm-deployment-66669684bd-27fzq litellm     await self.middleware_stack(scope, receive, send)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
litellm-deployment-66669684bd-27fzq litellm     await self.app(scope, receive, _send)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__
litellm-deployment-66669684bd-27fzq litellm     await self.app(scope, receive, send)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
litellm-deployment-66669684bd-27fzq litellm     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
litellm-deployment-66669684bd-27fzq litellm     await app(scope, receive, sender)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__
litellm-deployment-66669684bd-27fzq litellm     await self.middleware_stack(scope, receive, send)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app
litellm-deployment-66669684bd-27fzq litellm     await route.handle(scope, receive, send)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle
litellm-deployment-66669684bd-27fzq litellm     await self.app(scope, receive, send)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
litellm-deployment-66669684bd-27fzq litellm     await wrap_app_handling_exceptions(app, request)(scope, receive, send)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
litellm-deployment-66669684bd-27fzq litellm     await app(scope, receive, sender)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 72, in app
litellm-deployment-66669684bd-27fzq litellm     response = await func(request)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
litellm-deployment-66669684bd-27fzq litellm     raw_response = await run_endpoint_function(
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
litellm-deployment-66669684bd-27fzq litellm     return await dependant.call(**values)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/backoff/_async.py", line 151, in retry
litellm-deployment-66669684bd-27fzq litellm     ret = await target(*args, **kwargs)
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 3158, in chat_completion
litellm-deployment-66669684bd-27fzq litellm     data = await proxy_logging_obj.pre_call_hook(  # type: ignore
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 586, in pre_call_hook
litellm-deployment-66669684bd-27fzq litellm     response = await _callback.async_pre_call_hook(
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/hooks/parallel_request_limiter.py", line 307, in async_pre_call_hook
litellm-deployment-66669684bd-27fzq litellm     _user_id_rate_limits = await self.get_internal_user_object(
litellm-deployment-66669684bd-27fzq litellm   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/hooks/parallel_request_limiter.py", line 754, in get_internal_user_object
litellm-deployment-66669684bd-27fzq litellm     verbose_proxy_logger.debug(
litellm-deployment-66669684bd-27fzq litellm Message: 'Parallel Request Limiter: Error getting user object'
litellm-deployment-66669684bd-27fzq litellm Arguments: ("User doesn't exist in db. 'user_id'=admin. Create user via `/user/new` call. Got error - ",)
```

**Comment by ghost** [comment]
Calling deepseek directly, i can see the request does actually take a while. 

The user doesn't exist in db isn't a blocking error - this might be a backend llm api hanging/timeout error. @xingyaoww 

testing further.

**Comment by ghost** [comment]
This request works for me - both via litellm sdk and litellm sdk + proxy @xingyaoww 
<img width="1649" alt="Screenshot 2024-10-14 at 8 21 14 PM" src="https://github.com/user-attachments/assets/88c454c6-9e4f-4c5f-ad79-f9c711ee710a">

**Comment by ghost** [comment]
Found the cause of the noisy user object debug error - it happens if the admin creates a key on the ui

**Comment by yuyuma** [comment]
I just wanted to add that I see this same (non-blocking) error on v1.49.2 when proxying to other endpoints like openai.

In my case I never deployed ui or created a key via the ui. Just the most basic proxy setup without database or any other dependencies. Hopefully the same fix implemented is applicable.

**Comment by xingyaoww** [comment]
> Calling deepseek directly, i can see the request does actually take a while.

Would the timeout triggers error on the log when LITELLM_LOG=DEBUG? I cannot seem to find the error except the one error reported in this issue.

Also, I am able to get response from deepseek directly, but not when have the request going through the proxy

**Comment by ghost** [comment]
> Would the timeout triggers error on the log 

@xingyaoww can you share the complete debug log? feel free to share via slack/email 

a timeout would show up on the stacktrace

it would also help to know what the error you see client-side is

**Comment by ghost** [comment]
> I just wanted to add that I see this same (non-blocking) error on v1.49.2 when proxying to other endpoints like openai.

@yuyuma what does your error say, i assume it's not 'user_id='admin'' 

the error is caused when a user_id is set for the key, but the corresponding id doesn't exist in the litellm user table. 

i assume you created a key w/ user_id, but the id wasn't in the user id table? 

I think the debug log can be made clearer, to avoid confusion

**Comment by xingyaoww** [comment]
@krrishdholakia thanks! I've shared the server-side and client-side log over slack - i didn't see a timeout error there 🤔

**Comment by yuyuma** [comment]
@krrishdholakia i've attached my (redacted) logs here
[redacted_logs.txt](https://github.com/user-attachments/files/17382432/redacted_logs.txt)

I'm not sure what user ids or keys you're referring to. My local setup is nothing more than the https://docs.litellm.ai/docs/proxy/deploy#quick-start instructions except rather than using docker I'm running `litellm --config config.yaml`.  The only thing in my env that could be a key is the LITELLM_MASTER_KEY as specified in the quick-start.
