### ISSUE TITLE
[Bug]: AutoGen response error 

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#622]
### What happened?

 I am able to run group chat with several agents for a while before this error shows, but it does show almost every time. I am not sure if this is an autoagent, litellm, or ollama issue. Thought I would start here to see if it might be an litellm issue. 

### Relevant log output

```shell
Traceback (most recent call last):
  File "/autogen/autoagent_ollama_master.py", line 108, in <module>
    user_proxy.initiate_chat(
  File "/autogen/autoagent-om-env/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 531, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/autogen/autoagent-om-env/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 334, in send
    recipient.receive(message, self, request_reply, silent)
  File "/autogen/autoagent-om-env/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 462, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/autogen/autoagent-om-env/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 779, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/autogen/autoagent-om-env/lib/python3.11/site-packages/autogen/agentchat/groupchat.py", line 127, in run_chat
    speaker = groupchat.select_speaker(speaker, self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/autogen/autoagent-om-env/lib/python3.11/site-packages/autogen/agentchat/groupchat.py", line 56, in select_speaker
    final, name = selector.generate_oai_reply(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/autogen/autoagent-om-env/lib/python3.11/site-packages/autogen/agentchat/conversable_agent.py", line 606, in generate_oai_reply
    response = oai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/autogen/autoagent-om-env/lib/python3.11/site-packages/autogen/oai/completion.py", line 789, in create
    response = cls.create(
               ^^^^^^^^^^^
  File "/autogen/autoagent-om-env/lib/python3.11/site-packages/autogen/oai/completion.py", line 820, in create
    return cls._get_response(params, raise_on_ratelimit_or_timeout=raise_on_ratelimit_or_timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/autogen/autoagent-om-env/lib/python3.11/site-packages/autogen/oai/completion.py", line 259, in _get_response
    cls._book_keeping(config, response)
  File "/autogen/autoagent-om-env/lib/python3.11/site-packages/autogen/oai/completion.py", line 153, in _book_keeping
    response["cost"] = cls.cost(response)
                       ^^^^^^^^^^^^^^^^^^
  File "/autogen/autoagent-om-env/lib/python3.11/site-packages/autogen/oai/completion.py", line 1019, in cost
    model = response["model"]
            ~~~~~~~~^^^^^^^^^
TypeError: list indices must be integers or slices, not str
```

**Comment by ghost** [comment]
i'm able to repro this error
<img width="931" alt="Screenshot 2023-10-16 at 4 37 37 PM" src="https://github.com/BerriAI/litellm/assets/17561003/60c5a6fb-bf38-47ea-bd13-5f701d416760">

Looks like this is being caused due to ollama being overloaded: 
<img width="932" alt="Screenshot 2023-10-16 at 4 38 30 PM" src="https://github.com/BerriAI/litellm/assets/17561003/65d99c55-7649-4d27-82ab-58c2a728872a">

**Comment by ghost** [comment]
figured the error. 

Works when you do: `litellm --model ollama/mistral` and then make your call
when i ran `litellm` without a model and not starting ollama, i saw the same error as ollama isn't turned on and so isn't serving models at the required endpoint
i'll also add some reliability logic to the call to check for this issue and run ollama serve in the background if this happens

**Comment by ghost** [comment]
closing as cli is deprecated.
