### ISSUE TITLE
[Bug]: hosted_vllm throws error for completions without tools

### ISSUE THREAD

**Issue by michielree** [BerriAI/litellm#6228]
### What happened?

Simple example:

```
import litellm
litellm.set_verbose = True

if __name__ == "__main__":
    messages = [{"role": "user", "content": "Hello!"}]
    base_url = "http://localhost:8353/v1"

    completion = litellm.completion(
        "openai/mistralai/Mistral-Nemo-Instruct-2407",
        messages=messages,
        api_base=base_url,
    )  # OK
    print(completion.choices[0].message)

    completion = litellm.completion(
        "hosted_vllm/mistralai/Mistral-Nemo-Instruct-2407",
        messages=messages,
        api_base=base_url,
    )  # fails
    print(completion.choices[0].message)
```
I did some digging and I think the default value for `_tools` [here](https://github.com/BerriAI/litellm/blob/main/litellm/llms/hosted_vllm/chat/transformation.py#L25) might need to be `litellm.types.llms.openai.NOT_GIVEN` instead of `None`. Would open up a PR but couldn't get the tests to work locally yet.

### Relevant log output

```shell
Request to litellm:
litellm.completion('openai/mistralai/Mistral-Nemo-Instruct-2407', messages=[{'role': 'user', 'content': 'Hello!'}], api_base='http://localhost:8353/v1')


10:42:41 - LiteLLM:WARNING: utils.py:335 - `litellm.set_verbose` is deprecated. Please set `os.environ['LITELLM_LOG'] = 'DEBUG'` for debug logs.
SYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache')['no-cache']: False
Final returned optional params: {'extra_body': {}}


POST Request Sent from LiteLLM:
curl -X POST \
http://localhost:8353/v1/ \
-d '{'model': 'mistralai/Mistral-Nemo-Instruct-2407', 'messages': [{'role': 'user', 'content': 'Hello!'}], 'extra_body': {}}'


RAW RESPONSE:
{"id": "chat-3dd36dbb5afe448abb234c43d5faa237", "choices": [{"finish_reason": "stop", "index": 0, "logprobs": null, "message": {"content": "Hello! \ud83c\udf1e How can I assist you today? Let me know if you have any questions or just want to chat! \ud83d\ude0a", "refusal": null, "role": "assistant", "function_call": null, "tool_calls": []}, "stop_reason": null}], "created": 1728981761, "model": "mistralai/Mistral-Nemo-Instruct-2407", "object": "chat.completion", "service_tier": null, "system_fingerprint": null, "usage": {"completion_tokens": 30, "prompt_tokens": 6, "total_tokens": 36, "completion_tokens_details": null, "prompt_tokens_details": null}, "prompt_logprobs": null}


Logging Details LiteLLM-Success Call: Cache_hit=None
Looking up model=mistralai/Mistral-Nemo-Instruct-2407 in model_cost_map, custom_llm_provider=openai, call_type=completion
Looking up model=mistralai/Mistral-Nemo-Instruct-2407 in model_cost_map, custom_llm_provider=openai, call_type=completion
Message(content='Hello! 🌞 How can I assist you today? Let me know if you have any questions or just want to chat! 😊', role='assistant', tool_calls=None, function_call=None)


Request to litellm:
litellm.completion('hosted_vllm/mistralai/Mistral-Nemo-Instruct-2407', messages=[{'role': 'user', 'content': 'Hello!'}], api_base='http://localhost:8353/v1')


10:42:42 - LiteLLM:WARNING: utils.py:335 - `litellm.set_verbose` is deprecated. Please set `os.environ['LITELLM_LOG'] = 'DEBUG'` for debug logs.
SYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache')['no-cache']: False
Final returned optional params: {'tools': None, 'extra_body': {}}


POST Request Sent from LiteLLM:
curl -X POST \
http://localhost:8353/v1/ \
-d '{'model': 'mistralai/Mistral-Nemo-Instruct-2407', 'messages': [{'role': 'user', 'content': 'Hello!'}], 'tools': None, 'extra_body': {}}'


openai.py: Received openai error - Error code: 400 - {'object': 'error', 'message': "[{'type': 'value_error', 'loc': ('body',), 'msg': 'Value error, When using `tool_choice`, `tools` must be set.', 'input': {'messages': [{'role': 'user', 'content': 'Hello!'}], 'model': 'mistralai/Mistral-Nemo-Instruct-2407', 'tools': None, 'tool_choice': 'auto'}, 'ctx': {'error': ValueError('When using `tool_choice`, `tools` must be set.')}}]", 'type': 'BadRequestError', 'param': None, 'code': 400}
RAW RESPONSE:
Error code: 400 - {'object': 'error', 'message': "[{'type': 'value_error', 'loc': ('body',), 'msg': 'Value error, When using `tool_choice`, `tools` must be set.', 'input': {'messages': [{'role': 'user', 'content': 'Hello!'}], 'model': 'mistralai/Mistral-Nemo-Instruct-2407', 'tools': None, 'tool_choice': 'auto'}, 'ctx': {'error': ValueError('When using `tool_choice`, `tools` must be set.')}}]", 'type': 'BadRequestError', 'param': None, 'code': 400}



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 810, in completion
    raise e
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 746, in completion
    self.make_sync_openai_chat_completion_request(
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 605, in make_sync_openai_chat_completion_request
    raise e
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 594, in make_sync_openai_chat_completion_request
    raw_response = openai_client.chat.completions.with_raw_response.create(
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/openai/_legacy_response.py", line 353, in wrapped
    return cast(LegacyAPIResponse[R], func(*args, **kwargs))
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/openai/_utils/_utils.py", line 274, in wrapper
    return func(*args, **kwargs)
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 742, in create
    return self._post(
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/openai/_base_client.py", line 1270, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/openai/_base_client.py", line 947, in request
    return self._request(
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/openai/_base_client.py", line 1051, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'object': 'error', 'message': "[{'type': 'value_error', 'loc': ('body',), 'msg': 'Value error, When using `tool_choice`, `tools` must be set.', 'input': {'messages': [{'role': 'user', 'content': 'Hello!'}], 'model': 'mistralai/Mistral-Nemo-Instruct-2407', 'tools': None, 'tool_choice': 'auto'}, 'ctx': {'error': ValueError('When using `tool_choice`, `tools` must be set.')}}]", 'type': 'BadRequestError', 'param': None, 'code': 400}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/litellm/main.py", line 1543, in completion
    raise e
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/litellm/main.py", line 1516, in completion
    response = openai_chat_completions.completion(
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 820, in completion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError: Error code: 400 - {'object': 'error', 'message': "[{'type': 'value_error', 'loc': ('body',), 'msg': 'Value error, When using `tool_choice`, `tools` must be set.', 'input': {'messages': [{'role': 'user', 'content': 'Hello!'}], 'model': 'mistralai/Mistral-Nemo-Instruct-2407', 'tools': None, 'tool_choice': 'auto'}, 'ctx': {'error': ValueError('When using `tool_choice`, `tools` must be set.')}}]", 'type': 'BadRequestError', 'param': None, 'code': 400}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/michiel/Repos/rugllm/quick_test.py", line 19, in <module>
    completion = litellm.completion(
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/litellm/utils.py", line 1090, in wrapper
    raise e
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/litellm/utils.py", line 979, in wrapper
    result = original_function(*args, **kwargs)
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/litellm/main.py", line 2955, in completion
    raise exception_type(
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2116, in exception_type
    raise e
  File "/home/michiel/.virtualenvs/litellm/lib/python3.10/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 334, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: litellm.BadRequestError: Hosted_vllmException - Error code: 400 - {'object': 'error', 'message': "[{'type': 'value_error', 'loc': ('body',), 'msg': 'Value error, When using `tool_choice`, `tools` must be set.', 'input': {'messages': [{'role': 'user', 'content': 'Hello!'}], 'model': 'mistralai/Mistral-Nemo-Instruct-2407', 'tools': None, 'tool_choice': 'auto'}, 'ctx': {'error': ValueError('When using `tool_choice`, `tools` must be set.')}}]", 'type': 'BadRequestError', 'param': None, 'code': 400}
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/michiel-van-der-ree-8669482a

**Comment by ghost** [comment]
> Error code: 400 - {'object': 'error', 'message': "[{'type': 'value_error', 'loc': ('body',), 'msg': 'Value error, When using `tool_choice`, `tools` must be set.', 'input': {'messages': [{'role': 'user', 'content': 'Hello!'}], 'model': 'mistralai/Mistral-Nemo-Instruct-2407', 'tools': None, 'tool_choice': 'auto'}, 'ctx': {'error': ValueError('When using `tool_choice`, `tools` must be set.')}}]", 'type': 'BadRequestError', 'param': None, 'code': 400}

it looks like the tool_choice value is somehow being automatically set

**Comment by ghost** [comment]
i suspect they set it to 'auto' because they see the key of tools
