### ISSUE TITLE
[Help]: Bedrock invalid auth error

### ISSUE THREAD

**Issue by yarimarchetti** [BerriAI/litellm#6260]
### What happened?

Just tested the vanilla example of Bedrock model, reported [here](https://docs.litellm.ai/docs/providers/bedrock), and I keep on getting invalid credentials for all the calls, even if the credentials are valid (I tested them via AWS CLI and they work).

LiteLLM==1.49.5
boto3==1.35.41

`import os
from litellm import completion

os.environ["AWS_ACCESS_KEY_ID"] = "<access_key_id>"
os.environ["AWS_SECRET_ACCESS_KEY"] = "<secret_access_key>"
os.environ["AWS_REGION_NAME"] = "us-west-2"

response = completion(
  model="bedrock/anthropic.claude-3-sonnet-20240229-v1:0",
  messages=[{ "content": "Hello, how are you?","role": "user"}]
)`

### Relevant log output

```shell
raise AuthenticationError(
litellm.exceptions.AuthenticationError: litellm.AuthenticationError: BedrockException Invalid Authentication - {"message":"The security token included in the request is invalid."}
```

**Comment by ghost** [comment]
@yarimarchetti can you run it with `litellm.set_verbose=True` and confirm the correct credentials are being used?

**Comment by ghost** [comment]
Unable to repro, this works for me. Just tested on a google colab instance
<img width="1683" alt="Screenshot 2024-10-16 at 8 49 47 AM" src="https://github.com/user-attachments/assets/ef768988-78e7-4f38-9cfd-6fb795e7a035">

**Comment by yarimarchetti** [comment]
> @yarimarchetti can you run it with `litellm.set_verbose=True` and confirm the correct credentials are being used?

I did and, even if the aws_secret_access_key is not visible, the aws_access_key_id is the right one (the one I'm able to use to access Bedrock via AWS CLI).

What I forgot to mention is that I'm running this test on Mac Sonoma 14.7 with Python 3.11.1

**Comment by ghost** [comment]
does the issue persist for you on a google colab? (which is a clean vm) 

https://colab.research.google.com/?utm_source=scs-index

@yarimarchetti

**Comment by yangching2** [comment]
thank you for looking into this issue. I got the same error, I am running litellm from docker compose.  with docker image
ghcr.io/berriai/litellm:main-stable, SHA: 90bb07f4d7cf that is built 3 days ago. 

have tried multiple times on different machines, and also checked that my AWS access key, secret and region are both valid from a different bedrock client. 

```
litellm-litellm-1     | Traceback (most recent call last):
litellm-litellm-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 438, in acompletion
litellm-litellm-1     |     response = await init_response
litellm-litellm-1     |                ^^^^^^^^^^^^^^^^^^^
litellm-litellm-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/bedrock/chat/converse_handler.py", line 133, in async_streaming
litellm-litellm-1     |     completion_stream = await make_call(
litellm-litellm-1     |                         ^^^^^^^^^^^^^^^^
litellm-litellm-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/bedrock/chat/invoke_handler.py", line 236, in make_call
litellm-litellm-1     |     raise BedrockError(status_code=error_code, message=err.response.text)
litellm-litellm-1     | litellm.llms.bedrock.common_utils.BedrockError: {"message":"The security token included in the request is invalid."}
```

**Comment by ghost** [comment]
https://stackoverflow.com/questions/34582318/how-can-i-resolve-the-error-the-security-token-included-in-the-request-is-inval

this seems to be from some sort of expired session token (not litellm related)
