### ISSUE TITLE
[Bug]: Keyword arguments are used before arguments in caching.py

### ISSUE THREAD

**Issue by fidoriel** [BerriAI/litellm#6264]
### What happened?

If accomplete is used with arguments that are not keyword arguments and caching is enabled, client decorator will call caching and caching will fail, because args is not empty.
args[0] is interpreted as result and `TypeError: Cache._add_cache_logic() got multiple values for argument 'result'` is thrown.
This error can occur on all caching functions using this pattern:
```python
self._add_cache_logic(
    result=result, *args, **kwargs
)
```

Example to reproduce:
```python
import asyncio
import os
from litellm import acompletion
import litellm

litellm.cache = litellm.Cache(type="redis", host="localhost", password="", port=6379)

async def main():
    
    await acompletion("gpt-3.5-turbo", messages=[{"role": "user", "content": "42HHey, how's it going?"}], api_key=os.getenv("OPENAI_API_KEY"), caching=True)
    asyncio.sleep(10)
asyncio.run(main())
```

### Relevant log output

```shell
ERROR:LiteLLM:LiteLLM Cache: Excepton add_cache: Cache._add_cache_logic() got multiple values for argument 'result'
Traceback (most recent call last):
  File "/home/user/git/project/.venv/lib/python3.12/site-packages/litellm/caching/caching.py", line 540, in async_add_cache
    cache_key, cached_data, kwargs = self._add_cache_logic(
                                     ^^^^^^^^^^^^^^^^^^^^^^
TypeError: Cache._add_cache_logic() got multiple values for argument 'result'
```

**Comment by ghost** [comment]
patch for now would be to fix this on the cache input stage

root cause is due to not accept both result + *args 

cc: @ishaan-jaff i think this is one of those parts of caching that need to be refactored for stability

**Comment by fidoriel** [comment]
Now the exception is not thrown anymore, but caching is now broken. Dont get a hit.

```python
import asyncio
import os
from litellm import acompletion
import litellm

litellm.cache = litellm.Cache(type="redis", host="localhost", password="", port=6379)

async def main():
    
    await acompletion(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hey, how's it going?"}], api_key=os.getenv("OPENAI_API_KEY"), caching=True)
    await acompletion(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hey, how's it going?"}], api_key=os.getenv("OPENAI_API_KEY"), caching=True)
    asyncio.sleep(10)
asyncio.run(main())
```

**Comment by ishaan-jaff** [comment]
try this 

```python
import asyncio
import os
from litellm import acompletion
import litellm
litellm.set_verbose=True

litellm.cache = litellm.Cache(type="redis", host="localhost", password="", port=6379)

async def main():
    
    await acompletion(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hey, how's it going?"}], api_key=os.getenv("OPENAI_API_KEY"), caching=True)
    await asyncio.sleep(2)
    await acompletion(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hey, how's it going?"}], api_key=os.getenv("OPENAI_API_KEY"), caching=True)
    asyncio.sleep(10)
asyncio.run(main())
```

**Comment by ishaan-jaff** [comment]
@fidoriel - can you send the verbose logs you see in this case

**Comment by fidoriel** [comment]
Never mind.

```python
import asyncio
import os
from litellm import acompletion
import litellm

litellm.cache = litellm.Cache(type="redis", host="localhost", password="", port=6379)

async def main():
    
    await acompletion(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hey, how's it going today?"}], api_key=os.getenv("OPENAI_API_KEY"), caching=True)
    await asyncio.sleep(10)
    await acompletion(model="gpt-3.5-turbo", messages=[{"role": "user", "content": "Hey, how's it going today?"}], api_key=os.getenv("OPENAI_API_KEY"), caching=True)
    await asyncio.sleep(10)
asyncio.run(main())
```

works but 

```python
import asyncio
import os
from litellm import acompletion
import litellm

litellm.cache = litellm.Cache(type="redis", host="localhost", password="", port=6379)

async def main():
    
    await acompletion("gpt-3.5-turbo", messages=[{"role": "user", "content": "Hey, how's it going today?"}], api_key=os.getenv("OPENAI_API_KEY"), caching=True)
    await asyncio.sleep(10)
    await acompletion("gpt-3.5-turbo", messages=[{"role": "user", "content": "Hey, how's it going today?"}], api_key=os.getenv("OPENAI_API_KEY"), caching=True)
    await asyncio.sleep(10)
asyncio.run(main())
```

is still broken. Its confusing, sorry. I do not feel comfortable to post verbose logs. There are so many secrets in, I fear that I will not be able to catch all before posting.

**Comment by Kakadus** [comment]
@ishaan-jaff. I'm running into the same issue.

```py
import asyncio
import os

import litellm
from litellm import acompletion
from litellm.types.caching import LiteLLMCacheType

litellm.set_verbose = True

litellm.cache = litellm.Cache(type=LiteLLMCacheType.LOCAL)


async def main() -> None:
    await acompletion(
        "anthropic/claude-3-5-sonnet-20240620",
        messages=[{"role": "user", "content": "Hey, how's it going?"}],
        api_key=os.getenv("ANTHROPIC_API_KEY"),
        caching=True,
    )
    await acompletion(
        "anthropic/claude-3-5-sonnet-20240620",
        messages=[{"role": "user", "content": "Hey, how's it going?"}],
        api_key=os.getenv("ANTHROPIC_API_KEY"),
        caching=True,
    )
    await asyncio.sleep(10)


asyncio.run(main())
```
runs into
```py
Request to litellm:
litellm.acompletion('anthropic/claude-3-5-sonnet-20240620', messages=[{'role': 'user', 'content': "Hey, how's it going?"}], api_key='...', caching=True)


17:52:52 - LiteLLM:WARNING: utils.py:339 - `litellm.set_verbose` is deprecated. Please set `os.environ['LITELLM_LOG'] = 'DEBUG'` for debug logs.
ASYNC kwargs[caching]: True; litellm.cache: <litellm.caching.caching.Cache object at 0x7925dd88de50>; kwargs.get('cache'): None
An exception occurred: Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/litellm/caching/caching.py", line 575, in async_get_cache
    cached_result = await self.cache.async_get_cache(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: InMemoryCache.async_get_cache() takes 2 positional arguments but 3 were given

Final returned optional params: {}


POST Request Sent from LiteLLM:
curl -X POST \
https://api.anthropic.com/v1/messages \
-H 'accept: *****' -H 'anthropic-version: *****' -H 'content-type: *****' -H 'x-api-key: ...' \
-d '{'messages': [{'role': 'user', 'content': [{'type': 'text', 'text': "Hey, how's it going?"}]}], 'max_tokens': 4096, 'model': 'claude-3-5-sonnet-20240620'}'


_is_function_call: False
RAW RESPONSE:
<coroutine object AnthropicChatCompletion.acompletion_function at 0x7925d692eec0>


RAW RESPONSE:
{"id":"msg_01TuPifzP8nVcKhtTBARzqv5","type":"message","role":"assistant","model":"claude-3-5-sonnet-20240620","content":[{"type":"text","text":"Hello! I'm doing well, thank you for asking. How can I assist you today? Is there anything specific you'd like to chat about or any questions you have?"}],"stop_reason":"end_turn","stop_sequence":null,"usage":{"input_tokens":14,"output_tokens":38}}


raw model_response: {"id":"msg_01TuPifzP8nVcKhtTBARzqv5","type":"message","role":"assistant","model":"claude-3-5-sonnet-20240620","content":[{"type":"text","text":"Hello! I'm doing well, thank you for asking. How can I assist you today? Is there anything specific you'd like to chat about or any questions you have?"}],"stop_reason":"end_turn","stop_sequence":null,"usage":{"input_tokens":14,"output_tokens":38}}
Looking up model=claude-3-5-sonnet-20240620 in model_cost_map, custom_llm_provider=anthropic, call_type=acompletion
Async Wrapper: Completed Call, calling async_success_handler: <bound method Logging.async_success_handler of <litellm.litellm_core_utils.litellm_logging.Logging object at 0x7925d6876210>>
Logging Details LiteLLM-Success Call: Cache_hit=None
Looking up model=claude-3-5-sonnet-20240620 in model_cost_map, custom_llm_provider=anthropic, call_type=acompletion


Request to litellm:
litellm.acompletion('anthropic/claude-3-5-sonnet-20240620', messages=[{'role': 'user', 'content': "Hey, how's it going?"}], api_key='...', caching=True)


17:52:53 - LiteLLM:WARNING: utils.py:339 - `litellm.set_verbose` is deprecated. Please set `os.environ['LITELLM_LOG'] = 'DEBUG'` for debug logs.
ASYNC kwargs[caching]: True; litellm.cache: <litellm.caching.caching.Cache object at 0x7925dd88de50>; kwargs.get('cache'): None
An exception occurred: Traceback (most recent call last):
  File "/venv/lib/python3.12/site-packages/litellm/caching/caching.py", line 575, in async_get_cache
    cached_result = await self.cache.async_get_cache(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: InMemoryCache.async_get_cache() takes 2 positional arguments but 3 were given

Logging Details LiteLLM-Async Success Call, cache_hit=None
Looking up model=claude-3-5-sonnet-20240620 in model_cost_map, custom_llm_provider=anthropic, call_type=acompletion
Final returned optional params: {}


POST Request Sent from LiteLLM:
curl -X POST \
https://api.anthropic.com/v1/messages \
-H 'accept: *****' -H 'anthropic-version: *****' -H 'content-type: *****' -H 'x-api-key: ...' \
-d '{'messages': [{'role': 'user', 'content': [{'type': 'text', 'text': "Hey, how's it going?"}]}], 'max_tokens': 4096, 'model': 'claude-3-5-sonnet-20240620'}'


_is_function_call: False
RAW RESPONSE:
<coroutine object AnthropicChatCompletion.acompletion_function at 0x7925d692f870>


RAW RESPONSE:
{"id":"msg_01NvXc5d8ajUZRTDdwXtQQyN","type":"message","role":"assistant","model":"claude-3-5-sonnet-20240620","content":[{"type":"text","text":"Hello! I'm doing well, thank you for asking. How are you doing today? Is there anything I can help you with or would you like to chat about something in particular?"}],"stop_reason":"end_turn","stop_sequence":null,"usage":{"input_tokens":14,"output_tokens":40}}


raw model_response: {"id":"msg_01NvXc5d8ajUZRTDdwXtQQyN","type":"message","role":"assistant","model":"claude-3-5-sonnet-20240620","content":[{"type":"text","text":"Hello! I'm doing well, thank you for asking. How are you doing today? Is there anything I can help you with or would you like to chat about something in particular?"}],"stop_reason":"end_turn","stop_sequence":null,"usage":{"input_tokens":14,"output_tokens":40}}
Looking up model=claude-3-5-sonnet-20240620 in model_cost_map, custom_llm_provider=anthropic, call_type=acompletion
Async Wrapper: Completed Call, calling async_success_handler: <bound method Logging.async_success_handler of <litellm.litellm_core_utils.litellm_logging.Logging object at 0x7925d6877770>>
Logging Details LiteLLM-Success Call: Cache_hit=None
Looking up model=claude-3-5-sonnet-20240620 in model_cost_map, custom_llm_provider=anthropic, call_type=acompletion
Logging Details LiteLLM-Async Success Call, cache_hit=None
Looking up model=claude-3-5-sonnet-20240620 in model_cost_map, custom_llm_provider=anthropic, call_type=acompletion
```

the same for RedisCache and consorts.
