### ISSUE TITLE
 'str' object has no attribute 'parse' when using OpenAI 

### ISSUE THREAD

**Issue by danivpv** [BerriAI/litellm#6272]
### Stacktrace

Traceback (most recent call last):
  File "C:\Users\daniv\miniforge-pypy3\envs\podcast-AI\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 810, in completion
    raise e
  File "C:\Users\daniv\miniforge-pypy3\envs\podcast-AI\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 746, in completion
    self.make_sync_openai_chat_completion_request(
  File "C:\Users\daniv\miniforge-pypy3\envs\podcast-AI\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 605, in make_sync_openai_chat_completion_request
    raise e
  File "C:\Users\daniv\miniforge-pypy3\envs\podcast-AI\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 602, in make_sync_openai_chat_completion_request
    response = raw_response.parse()
               ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'parse'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\daniv\miniforge-pypy3\envs\podcast-AI\Lib\site-packages\litellm\main.py", line 1547, in completion
    raise e
  File "C:\Users\daniv\miniforge-pypy3\envs\podcast-AI\Lib\site-packages\litellm\main.py", line 1520, in completion
    response = openai_chat_completions.completion(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daniv\miniforge-pypy3\envs\podcast-AI\Lib\site-packages\litellm\llms\OpenAI\openai.py", line 820, in completion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError: 'str' object has no attribute 'parse'

**Comment by ghost** [comment]
@danivpv how can we repro this error? 

also please share the openai sdk version you have

**Comment by C-monC** [comment]
Hi does the commit https://github.com/BerriAI/litellm/commit/38a9a106d2ba9bacfffd45e81c3f88b45bdfc65f fix the issue?

**Comment by ghost** [comment]
Hi Simon,

It just adds some debugging around this to see what’s being received.

**Comment by danivpv** [comment]
Hello. The issue seems to have been resolved. I think it had to do with some temporary breaking change in openai's gpt-4o-mini structured response api. Sorry for the lack of information in the issue report, I was eager to implement some changes. I attach a working snippet that was giving me issues yesterday. For future reference, in case it happens again, adding a try except clause to switch to gemini for structured output works if gpt-4o-mini fails.


```python
import litellm
from pydantic import BaseModel
from typing import List
from pprint import pprint

class Lines(BaseModel):
    line: str
    syllable_count: int

class Haiku(BaseModel):
    haiku: List[Lines]

def main():
    response = litellm.completion(
        model='gpt-4o-mini',#gemini/gemini-1.5-flash',
        messages=[{"role": "user", "content": "Write a haiku"}],
        response_format=Haiku
    )
    haiku = Haiku.model_validate_json(response.choices[0].message.content)
    pprint(haiku.model_dump())


if __name__ == "__main__":
    main()
```
