### ISSUE TITLE
[Bug]: simple-shuffle load balancer setup can maximally handle 504 concurrent requests

### ISSUE THREAD

**Issue by us58** [BerriAI/litellm#6284]
### What happened?

My use case is that I have a node running 3 llama.cpp server instances which I want to load balance with litellm. For the load balancer, I want the most simple setup possible. This works so far, with one exception. But first my litellm setup:

My litellm load balancer config:
```
model_list:
  - model_name: llama3.1-70b-8192
    litellm_params:
      model: openai/llama3.1-70b-8192
      api_base: http://localhost:8081/v1
      api_key: none
  - model_name: llama3.1-70b-8192
    litellm_params:
      model: openai/llama3.1-70b-8192
      api_base: http://localhost:8082/v1
      api_key: none
  - model_name: llama3.1-70b-8192
    litellm_params:
      model: openai/llama3.1-70b-8192
      api_base: http://localhost:8083/v1
      api_key: none

litellm_settings:
  telemetry: False
  set_verbose: False
  cache: True
  cache_params:
    type: local
    supported_call_types: []

router_settings:
  model_group_alias: {"llama3.1-70b-8192": "llama3.1-70b-8192"}
  routing_strategy: simple-shuffle
  timeout: 86400  # requests timeout after 24 hours
  num_retries: 0
```

How I start the load balancer: `litellm --config litellm_load_balancer_config_random_shuffle.yaml --host 0.0.0.0 --port 8080`

This works as expected with the exception that the load balancer cannot handle more than 504 concurrent requests.
At exactly 505 concurrent requests, exactly one request returns the error

`Error code: 500 - {'error': {'message': 'litellm.APIError: APIError: OpenAIException - Connection error.\nReceived Model Group=llama3.1-70b-8192\nAvailable Model Group Fallbacks=None', 'type': None, 'param': None, 'code': '500'}}`

At 506+ requests, I also start getting

`Error code: 429 - {'error': {'message': "No deployments available for selected model, Try again in 5 seconds. Passed model=llama3.1-70b-8192. pre-call-checks=False, cooldown_list=['171ea340fbe1d96188cf76b14d3cfdf6a78da0c827352fa136fe10b500382b43', '6350da1d76950639dab095fe9326c5b0ba4c1d2b33a017c74daff602e99f520c', 'ae8059458393e6394b11ff26572b97bf13cc0bcaa032368f764f8e58d248118c']", 'type': 'None', 'param': 'None', 'code': '429'}}`

Note: I am on the latest litellm version.

### Relevant log output

```shell
Setting Cache on Proxy
LiteLLM: Proxy initialized with Config, Set models:
    llama3.1-70b-8192
    llama3.1-70b-8192
    llama3.1-70b-8192
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
15:34:00 - LiteLLM Proxy:ERROR: proxy_server.py:3312 - litellm.proxy.proxy_server.chat_completion(): Exception occured - litellm.APIError: APIError: OpenAIException - Connection error.
Received Model Group=llama3.1-70b-8192
Available Model Group Fallbacks=None
Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection.py", line 122, in _connect
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_base_client.py", line 1571, in _request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_client.py", line 1674, in send
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_client.py", line 1776, in _send_single_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
httpx.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 875, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 580, in make_openai_chat_completion_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 568, in make_openai_chat_completion_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_legacy_response.py", line 373, in wrapped
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1490, in create
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_base_client.py", line 1838, in post
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_base_client.py", line 1532, in request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_base_client.py", line 1605, in _request
openai.APIConnectionError: Connection error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/main.py", line 442, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 906, in acompletion
litellm.llms.OpenAI.openai.OpenAIError: Connection error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 3201, in chat_completion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 782, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 770, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 2731, in async_function_with_fallbacks
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 2589, in async_function_with_fallbacks
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 2814, in async_function_with_retries
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 2907, in make_call
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 886, in _acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 858, in _acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/utils.py", line 1220, in wrapper_async
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/utils.py", line 1076, in wrapper_async
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/main.py", line 464, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2116, in exception_type
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 404, in exception_type
litellm.exceptions.APIError: litellm.APIError: APIError: OpenAIException - Connection error.
Received Model Group=llama3.1-70b-8192
Available Model Group Fallbacks=None
15:34:00 - LiteLLM Proxy:ERROR: _common.py:120 - Giving up chat_completion(...) after 1 tries (litellm.proxy._types.ProxyException)
INFO:     127.0.0.1:55940 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
15:34:01 - LiteLLM Proxy:ERROR: proxy_server.py:3312 - litellm.proxy.proxy_server.chat_completion(): Exception occured - litellm.APIError: APIError: OpenAIException - Connection error.
Received Model Group=llama3.1-70b-8192
Available Model Group Fallbacks=None
Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection.py", line 122, in _connect
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
httpcore.ConnectError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_base_client.py", line 1571, in _request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_client.py", line 1674, in send
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_client.py", line 1776, in _send_single_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
httpx.ConnectError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 875, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 580, in make_openai_chat_completion_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 568, in make_openai_chat_completion_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_legacy_response.py", line 373, in wrapped
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1490, in create
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_base_client.py", line 1838, in post
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_base_client.py", line 1532, in request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_base_client.py", line 1605, in _request
openai.APIConnectionError: Connection error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/main.py", line 442, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 906, in acompletion
litellm.llms.OpenAI.openai.OpenAIError: Connection error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 3201, in chat_completion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 782, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 770, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 2731, in async_function_with_fallbacks
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 2589, in async_function_with_fallbacks
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 2814, in async_function_with_retries
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 2907, in make_call
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 886, in _acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 858, in _acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/utils.py", line 1220, in wrapper_async
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/utils.py", line 1076, in wrapper_async
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/main.py", line 464, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2116, in exception_type
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 404, in exception_type
litellm.exceptions.APIError: litellm.APIError: APIError: OpenAIException - Connection error.
Received Model Group=llama3.1-70b-8192
Available Model Group Fallbacks=None
15:34:01 - LiteLLM Proxy:ERROR: _common.py:120 - Giving up chat_completion(...) after 1 tries (litellm.proxy._types.ProxyException)
INFO:     127.0.0.1:55946 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
15:34:03 - LiteLLM Proxy:ERROR: proxy_server.py:3312 - litellm.proxy.proxy_server.chat_completion(): Exception occured - litellm.APIError: APIError: OpenAIException - Connection error.
Received Model Group=llama3.1-70b-8192
Available Model Group Fallbacks=None
Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_transports/default.py", line 72, in map_httpcore_exceptions
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_transports/default.py", line 377, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection.py", line 122, in _connect
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
httpcore.ConnectError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_base_client.py", line 1571, in _request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_client.py", line 1674, in send
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_client.py", line 1776, in _send_single_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
httpx.ConnectError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 875, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 580, in make_openai_chat_completion_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 568, in make_openai_chat_completion_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_legacy_response.py", line 373, in wrapped
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1490, in create
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_base_client.py", line 1838, in post
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_base_client.py", line 1532, in request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_base_client.py", line 1605, in _request
openai.APIConnectionError: Connection error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/main.py", line 442, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 906, in acompletion
litellm.llms.OpenAI.openai.OpenAIError: Connection error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 3201, in chat_completion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 782, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 770, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 2731, in async_function_with_fallbacks
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 2589, in async_function_with_fallbacks
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 2814, in async_function_with_retries
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 2907, in make_call
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 886, in _acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/router.py", line 858, in _acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/utils.py", line 1220, in wrapper_async
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/utils.py", line 1076, in wrapper_async
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/main.py", line 464, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2116, in exception_type
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 404, in exception_type
litellm.exceptions.APIError: litellm.APIError: APIError: OpenAIException - Connection error.
Received Model Group=llama3.1-70b-8192
Available Model Group Fallbacks=None
15:34:03 - LiteLLM Proxy:ERROR: _common.py:120 - Giving up chat_completion(...) after 1 tries (litellm.proxy._types.ProxyException)
INFO:     127.0.0.1:55950 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
INFO:     127.0.0.1:51740 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51950 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51800 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51804 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51846 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51848 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51890 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51924 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51610 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51772 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51728 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51788 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51764 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51858 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51904 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51964 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:51994 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:52060 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:52044 - "POST /v1/chat/completions HTTP/1.1" 200 OK
INFO:     127.0.0.1:53680 - "POST /v1/chat/completions HTTP/1.1" 200 OK
... from here on all good
```

**Comment by ghost** [comment]
This is not a litellm issue @us58 

it looks like your llama.cpp calls can only handle a certain number of requests at once.

**Comment by us58** [comment]
@krrishdholakia Reasons I believe it's more related to litellm:
1. In my llama.cpp server logs there are no errors when the errors occur in litellm.
2. If I send the requests directly to the llama.cpp server, there is no error sending >10000 requests concurrently at the same time.
3. The exactly same happens when I only set up a single llama.cpp server instance in the litellm config yaml.

From my point of view, it looks like the requests error out before being sent to the llama.cpp server.
Is this maybe something timeout related?

**Comment by ghost** [comment]
I'm not sure what `llama_server` is, but it's pretty clear the error is happening during a network call - see the httpcore error 

If the error was from litellm, we'd be seeing it happen on every request, and since the call is being made via the openai sdk - we can assume that's reliable too, this leaves me with the conclusion that it's the backend server unable to handle the higher load

```
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_async/connection.py", line 122, in _connect
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_backends/auto.py", line 30, in connect_tcp
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 114, in connect_tcp
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
httpcore.ConnectError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_base_client.py", line 1571, in _request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_client.py", line 1674, in send
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_client.py", line 1702, in _send_handling_auth
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_client.py", line 1739, in _send_handling_redirects
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_client.py", line 1776, in _send_single_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_transports/default.py", line 376, in handle_async_request
  File "/usr/lib/python3.10/contextlib.py", line 153, in __exit__
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/httpx/_transports/default.py", line 89, in map_httpcore_exceptions
httpx.ConnectError: [Errno 22] Invalid argument

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 875, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 580, in make_openai_chat_completion_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 568, in make_openai_chat_completion_request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_legacy_response.py", line 373, in wrapped
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/resources/chat/completions.py", line 1490, in create
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_base_client.py", line 1838, in post
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_base_client.py", line 1532, in request
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/openai/_base_client.py", line 1605, in _request
openai.APIConnectionError: Connection error.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/main.py", line 442, in acompletion
  File "/work/llama_server/llama_server/lib/python3.10/site-packages/litellm/llms/OpenAI/openai.py", line 906, in acompletion
litellm.llms.OpenAI.openai.OpenAIError: Connection error.

During handling of the above exception, another exception occurred:
```

**Comment by us58** [comment]
Hey @krrishdholakia, thanks for looking at this.
After I encountered the exact same behavior with a VLLM server as backend, I built a reproducible example with a fake openai endpoint.
What I observed:
1. The problem seems to be related to the number of active/pending requests that litellm is handling. I could not reliably reproduce this with the locust load test. I think this is because there is no way to keep a request active for some amount of time. In my fake openai endpoint, I delay each request for 10 seconds before they get answered.
2. When sending requests directly to my fake openai endpoint, there is also a limit of max active requests, which is 1000 (vs the 500 I observed in litellm). But there is a difference in behavior vs litellm: If for example 1500 requests are sent, the first 1000 requests are handled immediately. After they are done, the remaining 500 requests are handled. In the end, no request errors out.

With litellm, ~500 requests get send out immediately. After the these 500 are answered, another 500 request get send out. But in the whole process, several requests are sent back with an error.

Here is the code to reprocuce it:

fake_openai_endpoint.py
```
from fastapi import FastAPI
from pydantic import BaseModel
from typing import List
import asyncio
import logging

app = FastAPI()

logging.basicConfig(level=logging.INFO)

request_counter = 0
counter_lock = asyncio.Lock()


class Message(BaseModel):
    role: str
    content: str


class ChatCompletionRequest(BaseModel):
    model: str
    messages: List[Message]


@app.post("/v1/chat/completions")
async def fake_openai_chat_completion(request: ChatCompletionRequest):
    global request_counter

    async with counter_lock:
        request_counter += 1
        logging.info(f"Request count: {request_counter}")

    # Simulate a delay
    logging.info("Received request - Start processing")
    await asyncio.sleep(10)  # <----------------------------------- Important 

    return {
        "id": "fake-chat-id",
        "object": "chat.completion",
        "created": 1234567890,
        "model": request.model,
        "choices": [
            {
                "index": 0,
                "message": {
                    "role": "assistant",
                    "content": "This is a fake chat response."
                },
                "finish_reason": "stop"
            }
        ],
        "usage": {
            "prompt_tokens": 10,
            "completion_tokens": 7,
            "total_tokens": 17
        }
    }


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=5000)

```

load_test_active_requests.py
```
import asyncio
import openai

# Port 8090: litellm load balancer
# Port 5000: direct openai fake endpoint
port = 8090

client = openai.AsyncOpenAI(
    base_url=f"http://localhost:{port}/v1",
    api_key="no-key-needed"
)


def main():
    """
    """

    # Change number of concurrent requests here
    # 504 requests -> no problem
    # 505+ requests -> some requests error out
    num_concurrent_requests = 504

    prompt = "This is a sentence to test something."
    prompts = [prompt for i in range(num_concurrent_requests)]
    asyncio.run(send_requests(prompts))


async def send_requests(data):
    """
    """

    await asyncio.gather(*[openai_chat_endpoint(en_text) for en_text in data])


async def openai_chat_endpoint(data: str) -> str:
    """
    """

    try:
        chat_completion = await client.chat.completions.create(
            messages=[
                {"role": "system", "content": "You are a helpful assistant."},
                {"role": "user", "content": data}
            ],
            model="openai_fake",
            temperature=0,
            top_p=0.95,
            stream=False,
            stop=None
        )
    except Exception as e:
        chat_completion = str(e)
        print(e)

    return chat_completion


if __name__ == "__main__":
    main()

```

litellm_load_balancer_config.yaml
```
model_list:
  - model_name: openai_fake
    litellm_params:
      model: openai/openai_fake
      api_base: http://localhost:5000/v1
      api_key: none

litellm_settings:
  telemetry: False
  set_verbose: False
  cache: True
  cache_params:
    type: local
    supported_call_types: []

router_settings:
  model_group_alias: {"openai_fake": "openai_fake"}
  routing_strategy: simple-shuffle

```

Then start:
`python fake_openai_endpoint.py`
`litellm --config litellm_load_balancer_config.yaml --host 0.0.0.0 --port 8090`
`python load_test_active_requests.py`

In load_test_active_requests.py you can change the port to directly send to the fake openai endpoint and change the number of active/concurrent requests.

**Comment by us58** [comment]
Found the issue. The Ubuntu default value of 1024 for the number of file descriptors caused this. No more errors after increasing it.

I guess litellm internally uses an additional request of some type for every request to the proxy server, since I observed maximally ~500 requests before an error. Still kind of unexpected behavior with the errors since directly sending to the backend servers did work fine with >1024 requests (I think the openai client uses a queue for more than 1000 requests).

**Comment by ghost** [comment]
it shouldn't be. 

- is a file descriptor only created for http calls (wondering if a new thread could cause this) 
- are you able to see what creates a new file descriptor ?

**Comment by us58** [comment]
Sorry I have no idea how to monitor this. If you can explain how to do this, I'm happy to help

**Comment by ishaan-jaff** [comment]
Hi @us58 , thanks for using LiteLLM. Any chance we can hop on a call to learn how we can improve LiteLLM Proxy for you ? 

We’re planning roadmap and I’d love to get your feedback 

my cal for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
my linkedin if you prefer DMs: https://www.linkedin.com/in/reffajnaahsi/
