### ISSUE TITLE
[Bug]: Image Handling with litellm Proxy for qwen-vl-plus

### ISSUE THREAD

**Issue by NEWbie0709** [BerriAI/litellm#6307]
### What happened?

 I’m experiencing an issue when using litellm proxy to communicate with the qwen-vl-plus model for multimodal interactions. When I send an image URL directly to qwen-vl-plus, it processes the image as expected. However, when I configure litellm to handle the request and forward it to the qwen-vl-plus model, the same request fails. This is my config.yaml
![image](https://github.com/user-attachments/assets/8033e728-7bf2-44fe-b0d5-7f8ebe163d3b)
and this is the code for testing the litellm proxy
![image](https://github.com/user-attachments/assets/3a6ab0dc-ffa4-4d9b-81ba-997b75cf460f)

Other than that, I also tried using the ollama/llava model. When using the litellm proxy to send the request, it returns an error saying that it can't open the image.
![image](https://github.com/user-attachments/assets/c8e272fa-c144-4e12-bac5-f0e37b394707)
![image](https://github.com/user-attachments/assets/09435bd4-fcc6-4923-a305-11200dee3403)
But when I directly ask the model using ollama, it can answer it.
![image](https://github.com/user-attachments/assets/514dbd42-d98c-4951-aa9c-5334a72edca4)

**Comment by ghost** [comment]
What is the error? @NEWbie0709 
<img width="897" alt="Screenshot 2024-10-22 at 1 03 05 PM" src="https://github.com/user-attachments/assets/81fe774b-8e0e-4edb-8978-a43b75f73387">

**Comment by ghost** [comment]
Your ollama call fails because you put the image url in the content string

**Comment by NEWbie0709** [comment]
this is the error 
```
10:47:24 - LiteLLM Proxy:ERROR: proxy_server.py:3311 - litellm.proxy.proxy_server.chat_completion(): Exception occurred - litellm.BadRequestError: OpenAIException - Error code: 400 - {'error': {'code': 'invalid_parameter_error', 'param': None, 'message': '<400> InternalError.Algo.InvalidParameter: Failed to download multimodal content', 'type': 'invalid_request_error'}, 'id': 'chatcmpl-002b7740-5383-960d-ae34-3568053a0965'}
Received Model Group=qwen-vl-plus
Available Model Group Fallbacks=None LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
Traceback (most recent call last):
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\llms\OpenAI\openai.py", line 875, in acompletion
    headers, response = await self.make_openai_chat_completion_request(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\llms\OpenAI\openai.py", line 580, in make_openai_chat_completion_request
    raise e
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\llms\OpenAI\openai.py", line 568, in make_openai_chat_completion_request
    await openai_aclient.chat.completions.with_raw_response.create(
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\openai\_legacy_response.py", line 373, in wrapped
    return cast(LegacyAPIResponse[R], await func(*args, **kwargs))
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\openai\resources\chat\completions.py", line 1633, in create
    return await self._post(
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\openai\_base_client.py", line 1838, in post
    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\openai\_base_client.py", line 1532, in request
    return await self._request(
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\openai\_base_client.py", line 1633, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'code': 'invalid_parameter_error', 'param': None, 'message': '<400> InternalError.Algo.InvalidParameter: Failed to download multimodal content', 'type': 'invalid_request_error'}, 'id': 'chatcmpl-002b7740-5383-960d-ae34-3568053a0965'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\main.py", line 447, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\llms\OpenAI\openai.py", line 906, in acompletion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError: Error code: 400 - {'error': {'code': 'invalid_parameter_error', 'param': None, 'message': '<400> InternalError.Algo.InvalidParameter: Failed to download multimodal content', 'type': 'invalid_request_error'}, 'id': 'chatcmpl-002b7740-5383-960d-ae34-3568053a0965'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\proxy\proxy_server.py", line 3192, in chat_completion
    responses = await llm_responses
                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 783, in acompletion
    raise e
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 771, in acompletion
    response = await self.async_function_with_fallbacks(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 2732, in async_function_with_fallbacks
    raise original_exception
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 2590, in async_function_with_fallbacks
    response = await self.async_function_with_retries(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 2901, in async_function_with_retries
    raise original_exception
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 2815, in async_function_with_retries
    response = await self.make_call(original_function, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 2908, in make_call
    response = await original_function(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 887, in _acompletion
    raise e
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 859, in _acompletion
    response = await _response
               ^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 1221, in wrapper_async
    raise e
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 1077, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\main.py", line 469, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\litellm_core_utils\exception_mapping_utils.py", line 2116, in exception_type
    raise e
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\litellm_core_utils\exception_mapping_utils.py", line 282, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: litellm.BadRequestError: OpenAIException - Error code: 400 - {'error': {'code': 'invalid_parameter_error', 'param': None, 'message': '<400> InternalError.Algo.InvalidParameter: Failed to download multimodal content', 'type': 'invalid_request_error'}, 'id': 'chatcmpl-002b7740-5383-960d-ae34-3568053a0965'}
Received Model Group=qwen-vl-plus
```

But for the Ollama API, when I put the image inside the image_url string, it still shows the error below

```
- litellm.APIConnectionError: Ollama_chatException - {"error":"json: cannot unmarshal array into Go struct field ChatRequest.messages of type string"}
Received Model Group=llava
Available Model Group Fallbacks=None LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
Traceback (most recent call last):
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\main.py", line 447, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\llms\ollama_chat.py", line 608, in ollama_acompletion
    raise e  # don't use verbose_logger.exception, if exception is raised
    ^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\llms\ollama_chat.py", line 547, in ollama_acompletion
    raise OllamaError(status_code=resp.status, message=text)
litellm.llms.ollama_chat.OllamaError: {"error":"json: cannot unmarshal array into Go struct field ChatRequest.messages of type string"}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\proxy\proxy_server.py", line 3192, in chat_completion
    responses = await llm_responses
                ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 783, in acompletion
    raise e
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 771, in acompletion
    response = await self.async_function_with_fallbacks(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 2732, in async_function_with_fallbacks
    raise original_exception
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 2590, in async_function_with_fallbacks
    response = await self.async_function_with_retries(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 2901, in async_function_with_retries
    raise original_exception
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 2815, in async_function_with_retries
    response = await self.make_call(original_function, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 2908, in make_call
    response = await original_function(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 887, in _acompletion
    raise e
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\router.py", line 859, in _acompletion
    response = await _response
               ^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 1221, in wrapper_async
    raise e
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\utils.py", line 1077, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\main.py", line 469, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\litellm_core_utils\exception_mapping_utils.py", line 2116, in exception_type
    raise e
  File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\litellm\litellm_core_utils\exception_mapping_utils.py", line 2085, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: Ollama_chatException - {"error":"json: cannot unmarshal array into Go struct field ChatRequest.messages of type string"}
Received Model Group=llava
```

**Comment by ghost** [comment]
>   File "C:\Users\Tianyi\AppData\Roaming\Python\Python311\site-packages\openai\_base_client.py", line 1633, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.BadRequestError: Error code: 400 - {'error': {'code': 'invalid_parameter_error', 'param': None, 'message': '<400> InternalError.Algo.InvalidParameter: Failed to download multimodal content', 'type': 'invalid_request_error'}, 'id': 'chatcmpl-002b7740-5383-960d-ae34-3568053a0965'}

the error is from qwen. 


can you share a curl of a working request sending the image url to qwen on dashscope, vs. the failed request via proxy

**Comment by NEWbie0709** [comment]
Sorry for the late reply. Here is the code for the proxy and Dashcope.
![image](https://github.com/user-attachments/assets/cd68ba47-7138-428d-9444-eef6ff45e941)
![image](https://github.com/user-attachments/assets/7c3c5858-b0d7-4c6e-860c-1fb69e1156d9)

**Comment by NEWbie0709** [comment]
Any follow-up? @krrishdholakia 😃

**Comment by johannesboyne** [comment]
QQ: did anyone find a solution for this e.g., with a workaround or other structural changes?
