### ISSUE TITLE
[Bug]: Error calculating cost using Llama 3.1 on Azure

### ISSUE THREAD

**Issue by joch** [BerriAI/litellm#6310]
### What happened?

Hi team!

Getting an error doing cost calculation using Llama 3.1 on Azure.

Test call:

```python
litellm.set_verbose = True

response = litellm.completion(
    model="azure_ai/Meta-Llama-31-70B-Instruct",
    api_base="https://Meta-Llama-3-1-70B-Instruct-mydeployment.myregion.models.ai.azure.com/v1",
    api_version="2024-02-01",
    api_key="mykey",
    messages=[{"role": "user", "content": "tell me a linux related joke"}],
)
cost = litellm.completion_cost(completion_response=response)
```

### Relevant log output

```shell
RAW RESPONSE:
{"id": "cmpl-55db75e0b05344058b0bd8ee4e00bf84", "choices": [{"finish_reason": "stop", "index": 0, "logprobs": null, "message": {"content": "Here's one:\n\nWhy did the Linux kernel go to therapy?\n\nBecause it had a lot of \"core\" issues!\n\nHope that one made you laugh!", "refusal": null, "role": "assistant", "audio": null, "function_call": null, "tool_calls": []}}], "created": 1729243714, "model": "Meta-Llama-3.1-70B-Instruct", "object": "chat.completion", "service_tier": null, "system_fingerprint": null, "usage": {"completion_tokens": 32, "prompt_tokens": 16, "total_tokens": 48, "completion_tokens_details": null, "prompt_tokens_details": null}}


Logging Details LiteLLM-Success Call: Cache_hit=None
Looking up model=azure_ai/Meta-Llama-3.1-70B-Instruct in model_cost_map, custom_llm_provider=azure_ai, call_type=completion
Looking up model=azure_ai/Meta-Llama-3.1-70B-Instruct in model_cost_map, custom_llm_provider=azure_ai, call_type=completion
Looking up model=azure_ai/Meta-Llama-3.1-70B-Instruct in model_cost_map, custom_llm_provider=azure_ai, call_type=completion
Traceback (most recent call last):
  File "app.py", line 298, in <module>
    cost = litellm.completion_cost(completion_response=response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/litellm/cost_calculator.py", line 769, in completion_cost
    raise e
  File ".venv/lib/python3.12/site-packages/litellm/cost_calculator.py", line 750, in completion_cost
    ) = cost_per_token(
        ^^^^^^^^^^^^^^^
  File ".venv/lib/python3.12/site-packages/litellm/cost_calculator.py", line 416, in cost_per_token
    raise litellm.exceptions.NotFoundError(  # type: ignore
litellm.exceptions.NotFoundError: litellm.NotFoundError: Model not in model_prices_and_context_window.json. You passed model=azure_ai/Meta-Llama-3.1-70B-Instruct, custom_llm_provider=azure_ai. Register pricing for model - https://docs.litellm.ai/docs/proxy/custom_pricing
```

**Comment by krrishdholakia** [comment]
@joch this isn't a bug - the model isn't mapped yet. 
https://github.com/BerriAI/litellm/blob/main/model_prices_and_context_window.json

Looking into adding now. In the future, it would be helpful to call that out in the title like - https://github.com/BerriAI/litellm/issues/6377

**Comment by joch** [comment]
Thanks, will do! 

The reason why I added it as a bug was because the pricing was already in the json, but the model name was a bit incorrect. I see it's fixed now. Great work! :)
