### ISSUE TITLE
[Bug]: when configuring to use litellm_proxy, api_base silently defaults to azure.com if environment variable isn't set

### ISSUE THREAD

**Issue by thams** [BerriAI/litellm#6332]
### What happened?

configured like below, the system silently routes proxy requests to azure.com if there is no value for os.environ/SUPER_ENGINE_HOST

This is confusing. Seems like system should give a better error message.

config.yaml
```
  - model_name: SuperEngine
    litellm_params:
      model: litellm_proxy/SuperEngine
      api_base: os.environ/SUPER_ENGINE_HOST
      api_key: unused
```

### Relevant log output

```shell
'api_base': 'https://models.inference.ai.azure.com', 'acompletion': True, 'complete_input_dict': {'model': 'SuperEngine', 'messages': [{'role': 'user', 'content': 'Who is Abacab10'}], 'stream': True, 'extra_body': {}}}, 'log_event_type': 'failed_api_call', 'api_call_start_time': datetime.datetime(2024, 10, 20, 14, 2, 43, 885150), 'exception': litellm.AuthenticationError: AuthenticationError: Litellm_proxyException - Error code: 401 - {'error': {'code': 'unauthorized', 'message': 'Bad credentials', 'details': None}}, 'traceback_exception': 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/litellm/llms/OpenAI/openai.py", line 1021, in async_streaming\n    headers, response = await self.make_openai_chat_completion_request(\n                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/litellm/llms/OpenAI/openai.py", line 603, in make_openai_chat_completion_request\n    raise e\n  File "/usr/local/lib/python3.11/site-packages/litellm/llms/OpenAI/openai.py", line 591, in make_openai_chat_completion_request\n    await openai_aclient.chat.completions.with_raw_response.create(\n  File "/usr/local/lib/python3.11/site-packages/openai/_legacy_response.py", line 373, in wrapped\n    return cast(LegacyAPIResponse[R], await func(*args, **kwargs))\n                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 1633, in create\n    return await self._post(\n           ^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1838, in post\n    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1532, in request\n    return await self._request(\n           ^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/openai/_base_client.py", line 1633, in _request\n    raise self._make_status_error_from_response(err.response) from None\nopenai.AuthenticationError: Error code: 401 - {\'error\': {\'code\': \'unauthorized\', \'message\': \'Bad credentials\', \'details\': None}}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 455, in acompletion\n    response = await init_response\n               ^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/litellm/llms/OpenAI/openai.py", line 1066, in async_streaming\n    raise OpenAIError(\nlitellm.llms.OpenAI.openai.OpenAIError: Error code: 401 - {\'error\': {\'code\': \'unauthorized\', \'message\': \'Bad credentials\', \'details\': None}}\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1077, in wrapper_async\n    result = await original_function(*args, **kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 477, in acompletion\n    raise exception_type(\n          ^^^^^^^^^^^^^^^\n  File "/usr/local/lib/python3.11/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2116, in exception_type\n    raise e\n  File "/usr/local/lib/python3.11/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 343, in exception_type\n    raise AuthenticationError(\nlitellm.exceptions.AuthenticationError: litellm.AuthenticationError: AuthenticationError: Litellm_proxyException - Error code: 401 - {\'error\': {\'code\': \'unauthorized\', \'message\': \'Bad credentials\', \'details\': None}}\n', 'end_time': datetime.datetime(2024, 10, 20, 14, 2, 43, 983041), 'response_cost': 0, 'standard_logging_object': {'id': '9591452a-5e7f-4578-9b8c-26c9fa962c01', 'call_type': 'acompletion', 'cache_hit': False, 'status': 'failure', 'saved_cache_cost': 0.0, 'startTime': 1729432963.875129, 'endTime': 1729432963.983041, 'completionStartTime': 1729432963.983041, 'model': 'SuperEngine', 'metadata': {'user_api_key_alias': None, 'user_api_key_team_id': None, 'user_api_key_user_id': None, 'user_api_key_team_alias': None, 'requester_ip_address': '', 'requester_metadata': {}}, 'cache_key': None, 'response_cost': 0.0, 'total_tokens': 0, 'prompt_tokens': 0, 'completion_tokens': 0, 'request_tags': [], 'end_user': '', 'api_base': 'https://models.inference.ai.azure.com', 'model_group': 'SuperEngine', 'model_id': '469c87d496f257a5904f32c74c54fffdce999c1335d7c9d87481c4c9886a6fd5', 'requester_ip_address': '', 'messages': [{'role': 'user', 'content': 'Who is Abacab10'}], 'response': {}, 'model_parameters': {'stream': True, 'max_retries': 0, 'extra_body': {}}, 'hidden_params': {'model_id': None, 'cache_key': None, 'api_base': None, 'response_cost': None, 'additional_headers': {'date': 'Sun, 20 Oct 2024 14:02:43 GMT', 'content-type': 'application/json; charset=utf-8', 'transfer-encoding': 'chunked', 'connection': 'keep-alive', 'x-ms-error-code': 'unauthorized', 'request-context': 'appId=', 'strict-transport-security': 'max-age=31536000; includeSubDomains; preload', 'x-content-type-options': 'nosniff', 'x-aml-cluster': 'vienna-eastus2-02', 'x-request-time': '0.031'}}, 'model_map_information': {'model_map_key': '', 'model_map_value': None}, 'error_str': "litellm.AuthenticationError: AuthenticationError: Litellm_proxyException - Error code: 401 - {'error': {'code': 'unauthorized', 'message': 'Bad credentials', 'details': None}}", 'response_cost_failure_debug_info': None}}
```

**Comment by ghost** [comment]
able to repro - fixing now

**Comment by ghost** [comment]
it was an error in the default api base value. Fixed + added testing to prevent future regressions.
