### ISSUE TITLE
[Bug]: not running Python

### ISSUE THREAD

**Issue by marciovictoria** [BerriAI/litellm#641]
### What happened?

A bug happened! When try to run any python script

### Relevant log output

```shell
Traceback (most recent call last):
    File
  "C:\Users\marci\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\code_interpreters\subprocess_c
  ode_interpreter.py", line 65, in run
      self.start_process()
    File
  "C:\Users\marci\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\code_interpreters\subprocess_c
  ode_interpreter.py", line 43, in start_process
      self.process = subprocess.Popen(self.start_cmd.split(),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Users\marci\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1026, in __init__
      self._execute_child(args, executable, preexec_fn, close_fds,
    File "C:\Users\marci\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 1538, in _execute_child
      hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by ghost** [comment]
@marciovictoria this is an open interpreter issue - https://github.com/KillianLucas/open-interpreter/
