### ISSUE TITLE
[Bug]: Structured outputs example in documentation fails

### ISSUE THREAD

**Issue by KevinJBoyer** [BerriAI/litellm#6438]
### What happened?

https://docs.litellm.ai/docs/completion/json_mode#pass-in-json_schema

Running the provided code, which is at time of writing:
```
import os
from litellm import completion 
from pydantic import BaseModel

# add to env var 
os.environ["OPENAI_API_KEY"] = ""

messages = [{"role": "user", "content": "List 5 important events in the XIX century"}]

class CalendarEvent(BaseModel):
  name: str
  date: str
  participants: list[str]

class EventsList(BaseModel):
    events: list[CalendarEvent]

resp = completion(
    model="gpt-4o-2024-08-06",
    messages=messages,
    response_format=EventsList
)

print("Received={}".format(resp))
```

fails with `Object of type ModelMetaclass is not JSON serializable`

For context the relevant versions I'm running are:
```
 name         : pydantic
 version      : 2.7.4

 name         : litellm
 version      : 1.50.4

 name         : openai
 version      : 1.52.2
```

### Relevant log output

```shell
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/litellm/llms/openai.py:825, in OpenAIChatCompletion.completion(self, model_response, timeout, optional_params, model, messages, print_verbose, api_key, api_base, acompletion, logging_obj, litellm_params, logger_fn, headers, custom_prompt_dict, client, organization, custom_llm_provider)
    824             else:
--> 825                 raise e
    826 except OpenAIError as e:

File ~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/litellm/llms/openai.py:784, in OpenAIChatCompletion.completion(self, model_response, timeout, optional_params, model, messages, print_verbose, api_key, api_base, acompletion, logging_obj, litellm_params, logger_fn, headers, custom_prompt_dict, client, organization, custom_llm_provider)
    773 logging_obj.pre_call(
    774     input=messages,
    775     api_key=openai_client.api_key,
   (...)
    781     },
    782 )
--> 784 response = openai_client.chat.completions.create(**data, timeout=timeout)  # type: ignore
    785 stringified_response = response.model_dump()

File ~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/_utils/_utils.py:277, in required_args.<locals>.inner.<locals>.wrapper(*args, **kwargs)
    276     raise TypeError(msg)
--> 277 return func(*args, **kwargs)

File ~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/resources/chat/completions.py:640, in Completions.create(self, messages, model, frequency_penalty, function_call, functions, logit_bias, logprobs, max_tokens, n, parallel_tool_calls, presence_penalty, response_format, seed, service_tier, stop, stream, stream_options, temperature, tool_choice, tools, top_logprobs, top_p, user, extra_headers, extra_query, extra_body, timeout)
    606 @required_args(["messages", "model"], ["messages", "model", "stream"])
    607 def create(
    608     self,
   (...)
    638     timeout: float | httpx.Timeout | None | NotGiven = NOT_GIVEN,
    639 ) -> ChatCompletion | Stream[ChatCompletionChunk]:
--> 640     return self._post(
    641         "/chat/completions",
    642         body=maybe_transform(
    643             {
    644                 "messages": messages,
    645                 "model": model,
    646                 "frequency_penalty": frequency_penalty,
    647                 "function_call": function_call,
    648                 "functions": functions,
    649                 "logit_bias": logit_bias,
    650                 "logprobs": logprobs,
    651                 "max_tokens": max_tokens,
    652                 "n": n,
    653                 "parallel_tool_calls": parallel_tool_calls,
    654                 "presence_penalty": presence_penalty,
    655                 "response_format": response_format,
    656                 "seed": seed,
    657                 "service_tier": service_tier,
    658                 "stop": stop,
    659                 "stream": stream,
    660                 "stream_options": stream_options,
    661                 "temperature": temperature,
    662                 "tool_choice": tool_choice,
    663                 "tools": tools,
    664                 "top_logprobs": top_logprobs,
    665                 "top_p": top_p,
    666                 "user": user,
    667             },
    668             completion_create_params.CompletionCreateParams,
    669         ),
    670         options=make_request_options(
    671             extra_headers=extra_headers, extra_query=extra_query, extra_body=extra_body, timeout=timeout
    672         ),
    673         cast_to=ChatCompletion,
    674         stream=stream or False,
    675         stream_cls=Stream[ChatCompletionChunk],
    676     )

File ~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/_base_client.py:1250, in SyncAPIClient.post(self, path, cast_to, body, options, files, stream, stream_cls)
   1247 opts = FinalRequestOptions.construct(
   1248     method="post", url=path, json_data=body, files=to_httpx_files(files), **options
   1249 )
-> 1250 return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))

File ~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/_base_client.py:931, in SyncAPIClient.request(self, cast_to, options, remaining_retries, stream, stream_cls)
    922 def request(
    923     self,
    924     cast_to: Type[ResponseT],
   (...)
    929     stream_cls: type[_StreamT] | None = None,
    930 ) -> ResponseT | _StreamT:
--> 931     return self._request(
    932         cast_to=cast_to,
    933         options=options,
    934         stream=stream,
    935         stream_cls=stream_cls,
    936         remaining_retries=remaining_retries,
    937     )

File ~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/_base_client.py:952, in SyncAPIClient._request(self, cast_to, options, remaining_retries, stream, stream_cls)
    951 retries = self._remaining_retries(remaining_retries, options)
--> 952 request = self._build_request(options)
    953 self._prepare_request(request)

File ~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/_base_client.py:485, in BaseClient._build_request(self, options)
    484 # TODO: report this error to httpx
--> 485 return self._client.build_request(  # pyright: ignore[reportUnknownMemberType]
    486     headers=headers,
    487     timeout=self.timeout if isinstance(options.timeout, NotGiven) else options.timeout,
    488     method=options.method,
    489     url=self._prepare_url(options.url),
    490     # the `Query` type that we use is incompatible with qs'
    491     # `Params` type as it needs to be typed as `Mapping[str, object]`
    492     # so that passing a `TypedDict` doesn't cause an error.
    493     # https://github.com/microsoft/pyright/issues/3526#event-6715453066
    494     params=self.qs.stringify(cast(Mapping[str, Any], params)) if params else None,
    495     json=json_data,
    496     files=options.files,
    497     **kwargs,
    498 )

File ~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/httpx/_client.py:357, in BaseClient.build_request(self, method, url, content, data, files, json, params, headers, cookies, timeout, extensions)
    356     extensions = dict(**extensions, timeout=timeout.as_dict())
--> 357 return Request(
    358     method,
    359     url,
    360     content=content,
    361     data=data,
    362     files=files,
    363     json=json,
    364     params=params,
    365     headers=headers,
    366     cookies=cookies,
    367     extensions=extensions,
    368 )

File ~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/httpx/_models.py:340, in Request.__init__(self, method, url, params, headers, cookies, content, data, files, json, stream, extensions)
    339 content_type: str | None = self.headers.get("content-type")
--> 340 headers, stream = encode_request(
    341     content=content,
    342     data=data,
    343     files=files,
    344     json=json,
    345     boundary=get_multipart_boundary_from_content_type(
    346         content_type=content_type.encode(self.headers.encoding)
    347         if content_type
    348         else None
    349     ),
    350 )
    351 self._prepare(headers)

File ~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/httpx/_content.py:212, in encode_request(content, data, files, json, boundary)
    211 elif json is not None:
--> 212     return encode_json(json)
    214 return {}, ByteStream(b"")

File ~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/httpx/_content.py:175, in encode_json(json)
    174 def encode_json(json: Any) -> tuple[dict[str, str], ByteStream]:
--> 175     body = json_dumps(json).encode("utf-8")
    176     content_length = str(len(body))

File /usr/local/lib/python3.12/json/__init__.py:231, in dumps(obj, skipkeys, ensure_ascii, check_circular, allow_nan, cls, indent, separators, default, sort_keys, **kw)
    227 if (not skipkeys and ensure_ascii and
    228     check_circular and allow_nan and
    229     cls is None and indent is None and separators is None and
    230     default is None and not sort_keys and not kw):
--> 231     return _default_encoder.encode(obj)
    232 if cls is None:

File /usr/local/lib/python3.12/json/encoder.py:200, in JSONEncoder.encode(self, o)
    197 # This doesn't pass the iterator directly to ''.join() because the
    198 # exceptions aren't as detailed.  The list call should be roughly
    199 # equivalent to the PySequence_Fast that ''.join() would do.
--> 200 chunks = self.iterencode(o, _one_shot=True)
    201 if not isinstance(chunks, (list, tuple)):

File /usr/local/lib/python3.12/json/encoder.py:258, in JSONEncoder.iterencode(self, o, _one_shot)
    254     _iterencode = _make_iterencode(
    255         markers, self.default, _encoder, self.indent, floatstr,
    256         self.key_separator, self.item_separator, self.sort_keys,
    257         self.skipkeys, _one_shot)
--> 258 return _iterencode(o, 0)

File /usr/local/lib/python3.12/json/encoder.py:180, in JSONEncoder.default(self, o)
    162 """Implement this method in a subclass such that it returns
    163 a serializable object for ``o``, or calls the base implementation
    164 (to raise a ``TypeError``).
   (...)
    178 
    179 """
--> 180 raise TypeError(f'Object of type {o.__class__.__name__} '
    181                 f'is not JSON serializable')

TypeError: Object of type ModelMetaclass is not JSON serializable

During handling of the above exception, another exception occurred:

OpenAIError                               Traceback (most recent call last)
File ~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/litellm/main.py:1244, in completion(model, messages, timeout, temperature, top_p, n, stream, stream_options, stop, max_tokens, presence_penalty, frequency_penalty, logit_bias, user, response_format, seed, tools, tool_choice, logprobs, top_logprobs, deployment_id, extra_headers, functions, function_call, base_url, api_version, api_key, model_list, **kwargs)
   1238     logging.post_call(
   1239         input=messages,
   1240         api_key=api_key,
   1241         original_response=str(e),
   1242         additional_args={"headers": headers},
   1243     )
-> 1244     raise e
   1246 if optional_params.get("stream", False):
   1247     ## LOGGING

File ~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/litellm/main.py:1217, in completion(model, messages, timeout, temperature, top_p, n, stream, stream_options, stop, max_tokens, presence_penalty, frequency_penalty, logit_bias, user, response_format, seed, tools, tool_choice, logprobs, top_logprobs, deployment_id, extra_headers, functions, function_call, base_url, api_version, api_key, model_list, **kwargs)
   1216 try:
-> 1217     response = openai_chat_completions.completion(
   1218         model=model,
   1219         messages=messages,
   1220         headers=headers,
   1221         model_response=model_response,
   1222         print_verbose=print_verbose,
   1223         api_key=api_key,
   1224         api_base=api_base,
   1225         acompletion=acompletion,
   1226         logging_obj=logging,
   1227         optional_params=optional_params,
   1228         litellm_params=litellm_params,
   1229         logger_fn=logger_fn,
   1230         timeout=timeout,  # type: ignore
   1231         custom_prompt_dict=custom_prompt_dict,
   1232         client=client,  # pass AsyncOpenAI, OpenAI client
   1233         organization=organization,
   1234         custom_llm_provider=custom_llm_provider,
   1235     )
   1236 except Exception as e:
   1237     ## LOGGING - log the original exception returned

File ~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/litellm/llms/openai.py:833, in OpenAIChatCompletion.completion(self, model_response, timeout, optional_params, model, messages, print_verbose, api_key, api_base, acompletion, logging_obj, litellm_params, logger_fn, headers, custom_prompt_dict, client, organization, custom_llm_provider)
    832 else:
--> 833     raise OpenAIError(status_code=500, message=traceback.format_exc())

OpenAIError: Traceback (most recent call last):
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/litellm/llms/openai.py", line 825, in completion
    raise e
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/litellm/llms/openai.py", line 784, in completion
    response = openai_client.chat.completions.create(**data, timeout=timeout)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 640, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1250, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 931, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 952, in _request
    request = self._build_request(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 485, in _build_request
    return self._client.build_request(  # pyright: ignore[reportUnknownMemberType]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/httpx/_client.py", line 357, in build_request
    return Request(
           ^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/httpx/_models.py", line 340, in __init__
    headers, stream = encode_request(
                      ^^^^^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/httpx/_content.py", line 212, in encode_request
    return encode_json(json)
           ^^^^^^^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/httpx/_content.py", line 175, in encode_json
    body = json_dumps(json).encode("utf-8")
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ModelMetaclass is not JSON serializable


During handling of the above exception, another exception occurred:

APIError                                  Traceback (most recent call last)
/tmp/ipykernel_481/913765497.py in ?()
     14 
     15 class EventsList(BaseModel):
     16     events: list[CalendarEvent]
     17 
---> 18 resp = completion(
     19     model="gpt-4o-2024-08-06",
     20     messages=messages,
     21     response_format=EventsList

~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/litellm/utils.py in ?(*args, **kwargs)
    952                     if (
    953                         liteDebuggerClient and liteDebuggerClient.dashboard_url != None
    954                     ):  # make it easy to get to the debugger logs if you've initialized it
    955                         e.message += f"\n Check the log in your dashboard - {liteDebuggerClient.dashboard_url}"
--> 956             raise e

~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/litellm/utils.py in ?(*args, **kwargs)
    952                     if (
    953                         liteDebuggerClient and liteDebuggerClient.dashboard_url != None
    954                     ):  # make it easy to get to the debugger logs if you've initialized it
    955                         e.message += f"\n Check the log in your dashboard - {liteDebuggerClient.dashboard_url}"
--> 956             raise e

~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/litellm/main.py in ?(model, messages, timeout, temperature, top_p, n, stream, stream_options, stop, max_tokens, presence_penalty, frequency_penalty, logit_bias, user, response_format, seed, tools, tool_choice, logprobs, top_logprobs, deployment_id, extra_headers, functions, function_call, base_url, api_version, api_key, model_list, **kwargs)
   2579             )
   2580         return response
   2581     except Exception as e:
   2582         ## Map to OpenAI Exception
-> 2583         raise exception_type(
   2584             model=model,
   2585             custom_llm_provider=custom_llm_provider,
   2586             original_exception=e,

~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/litellm/utils.py in ?(model, original_exception, custom_llm_provider, completion_kwargs, extra_kwargs)
   7466         ):
   7467             threading.Thread(target=get_all_keys, args=(e.llm_provider,)).start()
   7468         # don't let an error with mapping interrupt the user from receiving an error from the llm api calls
   7469         if exception_mapping_worked:
-> 7470             raise e
   7471         else:
   7472             for error_type in litellm.LITELLM_EXCEPTION_TYPES:
   7473                 if isinstance(e, error_type):

~/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/litellm/utils.py in ?(model, original_exception, custom_llm_provider, completion_kwargs, extra_kwargs)
   7466         ):
   7467             threading.Thread(target=get_all_keys, args=(e.llm_provider,)).start()
   7468         # don't let an error with mapping interrupt the user from receiving an error from the llm api calls
   7469         if exception_mapping_worked:
-> 7470             raise e
   7471         else:
   7472             for error_type in litellm.LITELLM_EXCEPTION_TYPES:
   7473                 if isinstance(e, error_type):

APIError: litellm.APIError: APIError: OpenAIException - Traceback (most recent call last):
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/litellm/llms/openai.py", line 825, in completion
    raise e
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/litellm/llms/openai.py", line 784, in completion
    response = openai_client.chat.completions.create(**data, timeout=timeout)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/resources/chat/completions.py", line 640, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 1250, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 931, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 952, in _request
    request = self._build_request(options)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/openai/_base_client.py", line 485, in _build_request
    return self._client.build_request(  # pyright: ignore[reportUnknownMemberType]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/httpx/_client.py", line 357, in build_request
    return Request(
           ^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/httpx/_models.py", line 340, in __init__
    headers, stream = encode_request(
                      ^^^^^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/httpx/_content.py", line 212, in encode_request
    return encode_json(json)
           ^^^^^^^^^^^^^^^^^
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/httpx/_content.py", line 175, in encode_json
    body = json_dumps(json).encode("utf-8")
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 258, in iterencode
    return _iterencode(o, 0)
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/encoder.py", line 180, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type ModelMetaclass is not JSON serializable
```

**Comment by ghost** [comment]
Unable to repro. This works in a clean vm (google colab) + passes on ci/cd as well - https://github.com/BerriAI/litellm/blob/38708a355a066027a5d251b6199fc70946c62157/tests/local_testing/test_completion.py#L2248
<img width="1666" alt="Screenshot 2024-10-25 at 3 51 41 PM" src="https://github.com/user-attachments/assets/a09fa771-beaa-48c8-8d8a-d0b26b2d6b4f">


@KevinJBoyer your not on the latest version of litellm. I can tell this from your stacktrace as litellm no longer has an `openai.py` file - it's a folder 

```
  File "/home/kevinboyer/.cache/pypoetry/virtualenvs/decision-support-tool-9TtSrW0h-py3.12/lib/python3.12/site-packages/litellm/llms/openai.py", line 784, in completion
    response = openai_client.chat.completions.create(**data, timeout=timeout)  # type: ignore
```

**Comment by KevinJBoyer** [comment]
@krrishdholakia you're correct -- something about my dev environment set up is off, even though I thought I was on the latest. I forced an update and it works now. Thank you!
