### ISSUE TITLE
[Bug]: Unable to call custom embed model deployed on VertexAI

### ISSUE THREAD

**Issue by suresiva** [BerriAI/litellm#6482]
### What happened?

We have custom trained embedding model deployed on VertexAI Model Garden through Custom Prediction Routine deployment steps.

We are able to make prediction calls on this custom embed model endpoint and get response as expected,
```
curl -X POST -H "Authorization: Bearer $(gcloud auth print-access-token)" -H "Content-Type: application/json" \
"https://us-central1-aiplatform.googleapis.com/v1/projects/${PROJECT_ID}/locations/us-central1/endpoints/${ENDPOINT_ID}:predict" \
-d '{"instances": [ {"inputs": ["hi", "bye"]}]}'
```

Response format,
```
{
 "predictions": [
   [
     [
       [
         0.4029706120491028,
         -0.1908158808946609,
         -0.9642080068588257,
..
   ]]]],
  "deployedModelId": "xxxxxx",
  "model": "projects/xxxx/locations/us-central1/models/xxxxx",
  "modelDisplayName": "snowflake-artic-embed-m-long-finetuned",
  "modelVersionId": "1"
}
```
We are using LiteLLM v1.50.0-stable version and we tried to configure above custom embedding model on LiteLLM as below,
```
{
  "model_name": "vertex_ai/snowflake-artic-embed-finetuned",
  "litellm_params": {
    "vertex_project": "xxxxxx",
    "vertex_location": "us-central1",
    "model": "vertex_ai/121113514773xxxxxx"
  },
....
}
```
We are getting below HTTP 404 error while calling this configured model through `embedding` endpoint,

```
curl --location 'http://0.0.0.0:4000/embeddings' \
--header 'Authorization: Bearer xxxx' --header 'Content-Type: application/json' \
--data '{ "input": ["hi", "bye"] , "model": "vertex_ai/snowflake-artic-embed-finetuned"}'
```

`{"error":{"message":"litellm.NotFoundError: VertexAIException - {\n  \"error\": {\n    \"code\": 404,\n    \"message\": \"Publisher Model `projects/xxxxxx/locations/us-central1/publishers/google/models/121113514773xxxxx` not found.\",\n    \"status\": \"NOT_FOUND\"\n  }\n}\n\nReceived Model Group=vertex_ai/snowflake-artic-embed-finetuned\nAvailable Model Group Fallbacks=None","type":null,"param":null,"code":"404"}}`

### Relevant log output

```shell
Received Model Group=vertex_ai/snowflake-artic-embed-finetuned
Available Model Group Fallbacks=None
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_ai_and_google_ai_studio/vertex_embeddings/embedding_handler.py", line 216, in async_embedding
    response = await client.post(api_base, headers=headers, json=vertex_request)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 149, in post
    raise e
INFO:     10.50.5.45:44658 - "POST /embeddings HTTP/1.1" 404 Not Found
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 113, in post
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://us-central1-aiplatform.googleapis.com/v1/projects/xxxxxxx/locations/us-central1/publishers/google/models/1211135147739xxxxx:predict'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 3127, in aembedding
    response = await init_response  # type: ignore
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/vertex_ai_and_google_ai_studio/vertex_embeddings/embedding_handler.py", line 220, in async_embedding
    raise VertexAIError(status_code=error_code, message=err.response.text)
litellm.llms.vertex_ai_and_google_ai_studio.vertex_ai_non_gemini.VertexAIError: {
  "error": {
    "code": 404,
    "message": "Publisher Model `projects/xxxxxxx/locations/us-central1/publishers/google/models/1211135147739xxxxxx` not found.",
    "status": "NOT_FOUND"
  }
}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 3769, in embeddings
    responses = await llm_responses
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2126, in aembedding
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2115, in aembedding
    response = await self.async_function_with_fallbacks(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2732, in async_function_with_fallbacks
    raise original_exception
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2590, in async_function_with_fallbacks
    response = await self.async_function_with_retries(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2832, in async_function_with_retries
    self.should_retry_this_error(
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2977, in should_retry_this_error
    raise error
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2815, in async_function_with_retries
    response = await self.make_call(original_function, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2908, in make_call
    response = await original_function(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2192, in _aembedding
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2179, in _aembedding
    response = await response
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1221, in wrapper_async
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1077, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 3145, in aembedding
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2116, in exception_type
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 1154, in exception_type
    raise NotFoundError(
litellm.exceptions.NotFoundError: litellm.NotFoundError: VertexAIException - {
  "error": {
    "code": 404,
    "message": "Publisher Model `projects/xxxxxxxxxx/locations/us-central1/publishers/google/models/1211135147739xxxxxxx` not found.",
    "status": "NOT_FOUND"
  }
}

Received Model Group=vertex_ai/snowflake-artic-embed-finetuned
Available Model Group Fallbacks=None
```

**Comment by suresiva** [comment]
The embedding used in this case was a custom deployed one on VertexAI model registry, and we are able to invoke it directly using the URL similar to `https://us-central1-aiplatform.googleapis.com/v1/projects/$PROJECT_ID/locations/us-central1/endpoints/$ENDPOINT_ID:predict`.

But when this model is configured and accessed through LiteLLM, it assumes that given is google provided and composes the api_base url as `https://us-central1-aiplatform.googleapis.com/v1/projects/$PROJECT_ID/locations/us-central1/publishers/google/models/$ENDPOINT_ID:predict` in https://github.com/BerriAI/litellm/blob/27e18358abcbcb973356cb067451a22f70b8daef/litellm/llms/vertex_ai_and_google_ai_studio/common_utils.py#L91

This causes the model not found 404 error when it assumes the given model is google provided instead of considering it as a custom deploy model.

**Comment by ishaan-jaff** [comment]
done here @suresiva https://github.com/BerriAI/litellm/pull/6749
