### ISSUE TITLE
[Bug]: Bad input type detection in amazon_titan_multimodal_transformation.py when running litellm.aembedding

### ISSUE THREAD

**Issue by pvachon-ivadolabs** [BerriAI/litellm#6515]
### What happened?

**Observed**
```
response = await litellm.aembedding(
      model="bedrock/amazon.titan-embed-image-v1"
      input = "sled",
      dimensions=1024
  )
```
Returns a 400 Bad Request error from Bedrock because LiteLLM interprets "sled" as an image and calls Bedrock with "inputImage" instead of "inputText"

- https://github.com/BerriAI/litellm/blob/03c56804a02f32dfd465e1ecd8ccbce453062082/litellm/llms/bedrock/embed/amazon_titan_multimodal_transformation.py#L48
- https://github.com/BerriAI/litellm/blob/03c56804a02f32dfd465e1ecd8ccbce453062082/litellm/utils.py#L8606

**Expected**
```
response = await litellm.aembedding(
      model="bedrock/amazon.titan-embed-image-v1"
      input = "sled",
      dimensions=1024
  )
```
Should call bedrock with "inputText"

### Relevant log output

```shell
request to litellm:
litellm.aembedding(model='bedrock/amazon.titan-embed-image-v1', input='sled', dimensions=1024, timeout=60)


ASYNC kwargs[caching]: False; litellm.cache: None; kwargs.get('cache'): None


POST Request Sent from LiteLLM:
curl -X POST \
https://bedrock-runtime.ca-central-1.amazonaws.com/model/amazon.titan-embed-image-v1/invoke \
-H 'Content-Type: *****' -H 'X-Amz-Date: *****' -H 'X-Amz-Security-Token: *****' -H 'Content-Length: *****' \
-d '{'inputImage': 'sled', 'embeddingConfig': {'outputEmbeddingLength': 1024}}'



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.


Failed to get query embedding for `sled`: litellm.BadRequestError: BedrockException - {"message":"400 Bad Request: Unable to process provided image. "}
```

**Comment by pvachon-ivadolabs** [comment]
@krrishdholakia I see you added a fix 2 weeks ago to prevent false positives (https://github.com/BerriAI/litellm/blame/main/litellm/utils.py#L6059), so thank you! 

However, this now forces the image strings to have the "data:" prefix, and Bedrock Titan G1 doesn't seem to support URIs with the data: prefix. Every request I make now gets a 400 Error: 400 Bad Request: Unable to decode base64 image string. from Bedrock.

```
Traceback (most recent call last):
  File "/Users/philippe.vachon.rivard/Projects/bookclub/.venv/lib/python3.11/site-packages/litellm/llms/bedrock/embed/embedding.py", line 140, in _make_async_call
    response = await client.post(url=api_base, headers=headers, data=json.dumps(data))  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/philippe.vachon.rivard/Projects/bookclub/.venv/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 162, in post
    raise e
  File "/Users/philippe.vachon.rivard/Projects/bookclub/.venv/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 122, in post
    response.raise_for_status()
  File "/Users/philippe.vachon.rivard/Projects/bookclub/.venv/lib/python3.11/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://bedrock-runtime.ca-central-1.amazonaws.com/model/amazon.titan-embed-image-v1/invoke'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/philippe.vachon.rivard/Projects/bookclub/.venv/lib/python3.11/site-packages/litellm/main.py", line 3168, in aembedding
    response = await init_response  # type: ignore
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/philippe.vachon.rivard/Projects/bookclub/.venv/lib/python3.11/site-packages/litellm/llms/bedrock/embed/embedding.py", line 287, in _async_single_func_embeddings
    response = await self._make_async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/philippe.vachon.rivard/Projects/bookclub/.venv/lib/python3.11/site-packages/litellm/llms/bedrock/embed/embedding.py", line 144, in _make_async_call
    raise BedrockError(status_code=error_code, message=err.response.text)
litellm.llms.bedrock.common_utils.BedrockError: {"message":"400 Bad Request: Unable to decode base64 image string. "}
```

**Comment by linznin** [comment]
same issue
