### ISSUE TITLE
[Bug]: litellm.text_completion raises an error on simple usage

### ISSUE THREAD

**Issue by okhat** [BerriAI/litellm#6537]
### What happened?

On latest pypi:

```python
import litellm
litellm.text_completion(
        model=f"text-completion-openai/gpt-3.5-turbo-instruct",
        prompt="2323"
    )
```

### Relevant log output

```shell
11:58:38 - LiteLLM:ERROR: main.py:4166 - LiteLLM non blocking exception: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py310_sept24_user/lib/python3.10/site-packages/litellm/main.py", line 4164, in text_completion
    transformed_logprobs = litellm.utils.transform_logprobs(raw_response)
  File "/opt/anaconda3/envs/py310_sept24_user/lib/python3.10/site-packages/litellm/utils.py", line 8366, in transform_logprobs
    for response in hf_response:
TypeError: 'NoneType' object is not iterable
```

**Comment by ishaan-jaff** [comment]
@okhat to confirm you are getting the ModelResponse but the debug log is showing the error correct ? 


This is what I see in the response with your example 

```shell
11:11:43 - LiteLLM:ERROR: main.py:4215 - LiteLLM non blocking exception: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Users/ishaanjaffer/Github/litellm/litellm/main.py", line 4213, in text_completion
    transformed_logprobs = litellm.utils.transform_logprobs(raw_response)
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 8366, in transform_logprobs
    for response in hf_response:
TypeError: 'NoneType' object is not iterable
TextCompletionResponse(id='cmpl-AOehjKggn2npSJ4oQ9ru88ZfftFHj', object='text_completion', created=1730439703, model='gpt-3.5-turbo-instruct', choices=[TextChoices(finish_reason='length', index=0, text=' Views\n\nHello, I am interested in starting a restaurant. What are some things', logprobs=None)], usage=Usage(completion_tokens=16, prompt_tokens=2, total_tokens=18, completion_tokens_details=None, prompt_tokens_details=None), system_fingerprint=None)
```

**Comment by ishaan-jaff** [comment]
but there is still a response 
```
TextCompletionResponse(id='cmpl-AOehjKggn2npSJ4oQ9ru88ZfftFHj', object='text_completion', created=1730439703, model='gpt-3.5-turbo-instruct', choices=[TextChoices(finish_reason='length', index=0, text=' Views\n\nHello, I am interested in starting a restaurant. What are some things', logprobs=None)], usage=Usage(completion_tokens=16, prompt_tokens=2, total_tokens=18, completion_tokens_details=None, prompt_tokens_details=None), system_fingerprint=None)
```

**Comment by ishaan-jaff** [comment]
warning is fixed here @okhat https://github.com/BerriAI/litellm/pull/6546
