### ISSUE TITLE
[Question]: How to run tests

### ISSUE THREAD

**Issue by linediconsine** [BerriAI/litellm#654]
### What happened?

I see this error 
`E   ModuleNotFoundError: No module named 'litellm'`

running `pytest`

### Relevant log output

```shell
`_____________ ERROR collecting litellm/tests/test_token_counter.py _____________
ImportError while importing test module '/Users/linediconsine/Desktop/litellm/litellm/tests/test_token_counter.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
litellm/tests/test_token_counter.py:11: in <module>
    from litellm import token_counter
E   ModuleNotFoundError: No module named 'litellm'
_________________ ERROR collecting litellm/tests/test_utils.py _________________
ImportError while importing test module '/Users/linediconsine/Desktop/litellm/litellm/tests/test_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
litellm/tests/test_utils.py:3: in <module>
    from dotenv import load_dotenv
E   ModuleNotFoundError: No module named 'dotenv'
_________ ERROR collecting litellm/tests/test_validate_environment.py __________
ImportError while importing test module '/Users/linediconsine/Desktop/litellm/litellm/tests/test_validate_environment.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
litellm/tests/test_validate_environment.py:11: in <module>
    import litellm
E   ModuleNotFoundError: No module named 'litellm'
=========================== short test summary info ============================
ERROR litellm/tests/test_api_key_param.py
ERROR litellm/tests/test_async_fn.py
ERROR litellm/tests/test_bad_params.py
ERROR litellm/tests/test_batch_completions.py
ERROR litellm/tests/test_caching.py
ERROR litellm/tests/test_client.py
ERROR litellm/tests/test_completion.py
ERROR litellm/tests/test_config.py
ERROR litellm/tests/test_custom_logger.py
ERROR litellm/tests/test_embedding.py
ERROR litellm/tests/test_exceptions.py
ERROR litellm/tests/test_get_model_cost_map.py
ERROR litellm/tests/test_get_model_list.py
ERROR litellm/tests/test_helicone_integration.py
ERROR litellm/tests/test_hf_prompt_templates.py
ERROR litellm/tests/test_litedebugger_integration.py
ERROR litellm/tests/test_llmonitor_integration.py
ERROR litellm/tests/test_load_test_model.py
ERROR litellm/tests/test_logging.py
ERROR litellm/tests/test_longer_context_fallback.py
ERROR litellm/tests/test_mock_request.py
ERROR litellm/tests/test_model_alias_map.py
ERROR litellm/tests/test_model_fallback.py
ERROR litellm/tests/test_no_client.py
ERROR litellm/tests/test_promptlayer_integration.py
ERROR litellm/tests/test_split_test.py
ERROR litellm/tests/test_stream_chunk_builder.py
ERROR litellm/tests/test_streaming.py
ERROR litellm/tests/test_timeout.py
ERROR litellm/tests/test_token_counter.py
ERROR litellm/tests/test_utils.py
ERROR litellm/tests/test_validate_environment.py
!!!!!!!!!!!!!!!!!!! Interrupted: 32 errors during collection !!!!!!!!!!!!!!!!!!!
============================== 32 errors in 1.70s ==============================
(litellm-py3.10) ➜  litellm git:(commetize) ✗ `
```

**Comment by ghost** [comment]
@linediconsine you need to run pytest from within the tests directory

**Comment by ghost** [comment]
@linediconsine let me know if that fixed your issue

**Comment by linediconsine** [comment]
For now it does not seem to solve it


Last commit 

``` 
commit f3c00a0e372c8479b482570c2486b1b015df0658 (HEAD -> main, origin/main, origin/HEAD)
Author: Krrish Dholakia <krrishdholakia@gmail.com>
Date:   Sat Oct 21 18:28:30 2023 -0700

    docs(openai-proxy-docs): cleanupo
```

``` 
$ poetry install 

$ cd litellm/tests/

$ (litellm-py3.10) ➜  tests git:(main) pytest
```

Here is the complete log, thanks for any feedback

```
============================= test session starts ==============================
platform darwin -- Python 3.9.16, pytest-7.0.1, pluggy-1.0.0
rootdir: /Users/linediconsine/Desktop/litellm/litellm/tests
plugins: anyio-3.5.0, celery-4.4.7
collected 0 items / 43 errors                                                  

==================================== ERRORS ====================================
_______________ ERROR collecting test_add_function_to_prompt.py ________________
ImportError while importing test module '/Users/linediconsine/Desktop/litellm/litellm/tests/test_add_function_to_prompt.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/local/Cellar/python@3.9/3.9.16/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
test_add_function_to_prompt.py:10: in <module>
    import litellm
../__init__.py:315: in <module>
    from .utils import (
../utils.py:11: in <module>
    import dotenv, json, traceback, threading
E   ModuleNotFoundError: No module named 'dotenv'

**[...]**

=========================== short test summary info ============================
ERROR test_add_function_to_prompt.py
ERROR test_api_key_param.py
ERROR test_async_fn.py
ERROR test_bad_params.py
ERROR test_batch_completions.py
ERROR test_caching.py
ERROR test_client.py
ERROR test_completion.py
ERROR test_config.py
ERROR test_custom_logger.py
ERROR test_embedding.py
ERROR test_exceptions.py
ERROR test_get_model_cost_map.py
ERROR test_get_model_file.py
ERROR test_get_model_list.py
ERROR test_helicone_integration.py
ERROR test_hf_prompt_templates.py
ERROR test_langchain_ChatLiteLLM.py
ERROR test_langfuse.py
ERROR test_langsmith.py
ERROR test_litedebugger_integration.py
ERROR test_llmonitor_integration.py
ERROR test_load_test_model.py
ERROR test_longer_context_fallback.py
ERROR test_mock_request.py
ERROR test_model_alias_map.py
ERROR test_model_fallback.py
ERROR test_multiple_deployments.py
ERROR test_no_client.py
ERROR test_prompt_factory.py
ERROR test_promptlayer_integration.py
ERROR test_provider_specific_config.py
ERROR test_rate_limit_manager.py
ERROR test_register_model.py
ERROR test_router.py
ERROR test_stream_chunk_builder.py
ERROR test_streaming.py
ERROR test_supabase_integration.py
ERROR test_timeout.py
ERROR test_token_counter.py
ERROR test_utils.py
ERROR test_validate_environment.py
ERROR test_wandb_logger.py
!!!!!!!!!!!!!!!!!!! Interrupted: 43 errors during collection !!!!!!!!!!!!!!!!!!!
============================== 43 errors in 9.92s ==============================
(litellm-py3.10) ➜  tests git:(main) 
```
Complete error visible [here](https://pastebin.com/HJm2nVTP) 

this error seem related to dotenv 


``` 
 poetry add dotenv
Using version ^0.0.5 for dotenv

Updating dependencies
Resolving dependencies... (38.5s)

Package operations: 1 install, 0 updates, 0 removals

  • Installing dotenv (0.0.5): Failed

[...]

Note: This error originates from the build backend, and is likely not a problem with poetry but with dotenv (0.0.5) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "dotenv (==0.0.5)"'.

```

**Comment by ghost** [comment]
I believe the initial error seems resolved. The new one implies no 'dotenv' module. It seems like this is caused by a failure during installing dotenv. 

Maybe try running `pip install dotenv`? 

Since this is working in our local + ci pipeline, it's hard for me to repro your error.

**Comment by linediconsine** [comment]
Thanks,

this is the log of `pip install dotenv`

```
(litellm-py3.10) ➜  tests git:(main) pip install dotenv
Collecting dotenv
  Using cached dotenv-0.0.5.tar.gz (2.4 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [81 lines of output]
      /Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-jdFcSznC-py3.10/lib/python3.10/site-packages/setuptools/__init__.py:80: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
        error: subprocess-exited-with-error
      
        × python setup.py egg_info did not run successfully.
        │ exit code: 1
        ╰─> [21 lines of output]
            Traceback (most recent call last):
              File "<string>", line 2, in <module>
              File "<pip-setuptools-caller>", line 14, in <module>
              File "/private/var/folders/1v/z1mcnx9d7mn_cdb5s7ppll_r0000gn/T/pip-wheel-6gd4jzz2/distribute_c9e5caf4550b4149a9c41761abd3ae2c/setuptools/__init__.py", line 2, in <module>
                from setuptools.extension import Extension, Library
              File "/private/var/folders/1v/z1mcnx9d7mn_cdb5s7ppll_r0000gn/T/pip-wheel-6gd4jzz2/distribute_c9e5caf4550b4149a9c41761abd3ae2c/setuptools/extension.py", line 5, in <module>
                from setuptools.dist import _get_unpatched
              File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
              File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
              File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
              File "/Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-jdFcSznC-py3.10/lib/python3.10/site-packages/_virtualenv.py", line 90, in exec_module
                old(module)
              File "/private/var/folders/1v/z1mcnx9d7mn_cdb5s7ppll_r0000gn/T/pip-wheel-6gd4jzz2/distribute_c9e5caf4550b4149a9c41761abd3ae2c/setuptools/dist.py", line 7, in <module>
                from setuptools.command.install import install
              File "/private/var/folders/1v/z1mcnx9d7mn_cdb5s7ppll_r0000gn/T/pip-wheel-6gd4jzz2/distribute_c9e5caf4550b4149a9c41761abd3ae2c/setuptools/command/__init__.py", line 8, in <module>
                from setuptools.command import install_scripts
              File "/private/var/folders/1v/z1mcnx9d7mn_cdb5s7ppll_r0000gn/T/pip-wheel-6gd4jzz2/distribute_c9e5caf4550b4149a9c41761abd3ae2c/setuptools/command/install_scripts.py", line 3, in <module>
                from pkg_resources import Distribution, PathMetadata, ensure_directory
              File "/private/var/folders/1v/z1mcnx9d7mn_cdb5s7ppll_r0000gn/T/pip-wheel-6gd4jzz2/distribute_c9e5caf4550b4149a9c41761abd3ae2c/pkg_resources.py", line 1518, in <module>
                register_loader_type(importlib_bootstrap.SourceFileLoader, DefaultProvider)
            AttributeError: module 'importlib._bootstrap' has no attribute 'SourceFileLoader'
            [end of output]
      
        note: This error originates from a subprocess, and is likely not a problem with pip.
      error: metadata-generation-failed
      
      × Encountered error while generating package metadata.
      ╰─> See above for output.
      
      note: This is an issue with the package mentioned above, not pip.
      hint: See above for details.
      Traceback (most recent call last):
        File "/Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-jdFcSznC-py3.10/lib/python3.10/site-packages/setuptools/installer.py", line 101, in _fetch_build_egg_no_warn
          subprocess.check_call(cmd)
        File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/subprocess.py", line 369, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['/Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-jdFcSznC-py3.10/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/1v/z1mcnx9d7mn_cdb5s7ppll_r0000gn/T/tmp2e_1bgq6', '--quiet', 'distribute']' returned non-zero exit status 1.
      
      The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/private/var/folders/1v/z1mcnx9d7mn_cdb5s7ppll_r0000gn/T/pip-install-wyyw8tff/dotenv_d32858e0cb464fb0bb62ce1fbedcb669/setup.py", line 13, in <module>
          setup(name='dotenv',
        File "/Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-jdFcSznC-py3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 102, in setup
          _install_setup_requires(attrs)
        File "/Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-jdFcSznC-py3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 75, in _install_setup_requires
          _fetch_build_eggs(dist)
        File "/Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-jdFcSznC-py3.10/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _fetch_build_eggs
          dist.fetch_build_eggs(dist.setup_requires)
        File "/Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-jdFcSznC-py3.10/lib/python3.10/site-packages/setuptools/dist.py", line 662, in fetch_build_eggs
          return _fetch_build_eggs(self, requires)
        File "/Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-jdFcSznC-py3.10/lib/python3.10/site-packages/setuptools/installer.py", line 38, in _fetch_build_eggs
          resolved_dists = pkg_resources.working_set.resolve(
        File "/Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-jdFcSznC-py3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 829, in resolve
          dist = self._resolve_dist(
        File "/Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-jdFcSznC-py3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
          dist = best[req.key] = env.best_match(
        File "/Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-jdFcSznC-py3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1135, in best_match
          return self.obtain(req, installer)
        File "/Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-jdFcSznC-py3.10/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1147, in obtain
          return installer(requirement)
        File "/Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-jdFcSznC-py3.10/lib/python3.10/site-packages/setuptools/installer.py", line 103, in _fetch_build_egg_no_warn
          raise DistutilsError(str(e)) from e
      distutils.errors.DistutilsError: Command '['/Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-jdFcSznC-py3.10/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/1v/z1mcnx9d7mn_cdb5s7ppll_r0000gn/T/tmp2e_1bgq6', '--quiet', 'distribute']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
(litellm-py3.10) ➜  tests git:(main) 
```

**Comment by linediconsine** [comment]
@krrishdholakia which python version is used in your local + ci pipeline ?

I see in the configuration 
`python = "^3.8"`

**Comment by linediconsine** [comment]
```
✗ poetry env info

Virtualenv
Python:         3.10.9
Implementation: CPython
Path:           /Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-mqEl_cTk-py3.10
Executable:     /Users/linediconsine/Library/Caches/pypoetry/virtualenvs/litellm-mqEl_cTk-py3.10/bin/python
Valid:          True

System
Platform:   darwin
OS:         posix
Python:     3.10.9
Path:       /usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10
Executable: /usr/local/opt/python@3.10/Frameworks/Python.framework/Versions/3.10/bin/python3.10
```

**Comment by ghost** [comment]
@linediconsine i believe you need to install python-dotenv https://pypi.org/project/python-dotenv/

**Comment by ghost** [comment]
@linediconsine did this resolve your issue?

**Comment by ishaan-jaff** [comment]
closing due to inactivity - feel free to reopen @linediconsine
