### ISSUE TITLE
[Bug]: LiteLLM API Connection Error Issue (Aider, Amazon Bedrock, Claude 3.5 Sonnet v2)

### ISSUE THREAD

**Issue by ldavis9000aws** [BerriAI/litellm#6559]
### What happened?

When working with Aider & the new Claude Connet 3.5 v2 model in Bedrock, Litellm will sometimes hang for about 5 minutes or so and then give me the following error about 10 - 15 minutes into an Aider session (tried updating litellm to v1.5.3 as well from v1.5.1, same issue).  Has anyone else experienced this? 

litellm.APIConnectionError: Bad response code, expected 200: {'status_code': 400, 'headers': {':exception-type': 'internalServerException', ':content-type': 'application/json', ':message-type': 'exception'}, 'body': b'{"message":"The
system encountered an unexpected error during processing. Try your request again."}'}
Traceback (most recent call last):
  File "C:\Users\Lawrence\miniconda3\envs\aider\Lib\site-packages\litellm\utils.py", line 7514, in __next__
    chunk = next(self.completion_stream)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lawrence\miniconda3\envs\aider\Lib\site-packages\litellm\llms\bedrock\chat\invoke_handler.py", line 1233, in iter_bytes
    message = self._parse_message_from_event(event)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lawrence\miniconda3\envs\aider\Lib\site-packages\litellm\llms\bedrock\chat\invoke_handler.py", line 1259, in _parse_message_from_event
    raise ValueError(f"Bad response code, expected 200: {response_dict}")
ValueError: Bad response code, expected 200: {'status_code': 400, 'headers': {':exception-type': 'internalServerException', ':content-type': 'application/json', ':message-type': 'exception'}, 'body': b'{"message":"The system encountered
an unexpected error during processing. Try your request again."}'}

### Relevant log output

```shell
litellm.APIConnectionError: Bad response code, expected 200: {'status_code': 400, 'headers': {':exception-type': 'internalServerException', ':content-type': 'application/json', ':message-type': 'exception'}, 'body': b'{"message":"The
system encountered an unexpected error during processing. Try your request again."}'}
Traceback (most recent call last):
  File "C:\Users\Lawrence\miniconda3\envs\aider\Lib\site-packages\litellm\utils.py", line 7514, in __next__
    chunk = next(self.completion_stream)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lawrence\miniconda3\envs\aider\Lib\site-packages\litellm\llms\bedrock\chat\invoke_handler.py", line 1233, in iter_bytes
    message = self._parse_message_from_event(event)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lawrence\miniconda3\envs\aider\Lib\site-packages\litellm\llms\bedrock\chat\invoke_handler.py", line 1259, in _parse_message_from_event
    raise ValueError(f"Bad response code, expected 200: {response_dict}")
ValueError: Bad response code, expected 200: {'status_code': 400, 'headers': {':exception-type': 'internalServerException', ':content-type': 'application/json', ':message-type': 'exception'}, 'body': b'{"message":"The system encountered
an unexpected error during processing. Try your request again."}'}
```

**Comment by pvachon-ivadolabs** [comment]
Sounds more like an API error than a LiteLLM bug. Did you try setting a lower timeout value and a retry strategy so you can catch the hangs and retry appropriately?

**Comment by schaveyt** [comment]
I am getting this example same error when using the Cline vcode plugin with the same LiteLLM and Sonnet configuration. The weird thing is that this was working just for up until now.

**Comment by schaveyt** [comment]
FYI - when I switch to use claude-3-opus, this just worked 🙃

**Comment by schaveyt** [comment]
When using Aider or Cline I will intermittently get this. Now I will consistently using Aider get a big pause waiting for the LLM response...then after about 30sec...the exception is thrown...Aider catches it then retries....and the LLM finally responses in full.

My chat has there token stats:
`Tokens: 49k sent, 130 received.`

However when switch to the older sonnet model things are fine
