### ISSUE TITLE
issue when trying to use openrouter key on windows 

### ISSUE THREAD

**Issue by buzman92** [BerriAI/litellm#658]
setx OPENROUTER_API_KEY "sk-or-v1-55d5492da8XXXXXXXX6eb2879f56298dabb0cd"

then run 
interpreter --model openrouter/openai/gpt-3.5-turbo

▌ Model set to OPENROUTER/OPENAI/GPT-3.5-TURBO

Open Interpreter will require approval before running code.

Use interpreter -y to bypass this.

Press CTRL-C to exit.

>

We were unable to determine the context window of this model. Defaulting to 3000.
If your model can handle more, run interpreter --context_window {token limit} or interpreter.context_window = {token limit}.
Also, please set max_tokens: interpreter --max_tokens {max tokens per response} or interpreter.max_tokens = {max tokens per response}

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\interpreter\core\respond.py", line 44, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\interpreter\llm\convert_to_coding_llm.py", line 19, in coding_llm
    for chunk in text_llm(messages):
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\interpreter\llm\setup_text_llm.py", line 117, in base_llm
    return litellm.completion(**params)
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\litellm\utils.py", line 798, in wrapper
    raise e
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\litellm\utils.py", line 757, in wrapper
    result = original_function(*args, **kwargs)
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "C:\Users\buzma\miniconda3\envs\stab\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\buzma\miniconda3\envs\stab\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\litellm\main.py", line 1195, in completion
    raise exception_type(
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\litellm\utils.py", line 3173, in exception_type
    raise e
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\litellm\utils.py", line 2530, in exception_type
    raise original_exception
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\litellm\main.py", line 815, in completion
    response = openai.ChatCompletion.create(
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 151, in create
    ) = cls.__prepare_create_request(
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 108, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\openai\api_requestor.py", line 139, in __init__
    self.api_key = key or util.default_api_key()
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\openai\util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\buzma\miniconda3\envs\stab\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\buzma\miniconda3\envs\stab\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\buzma\miniconda3\envs\stab\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\interpreter\core\core.py", line 26, in cli
    cli(self)
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\interpreter\cli\cli.py", line 254, in cli
    interpreter.chat()
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\interpreter\core\core.py", line 88, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\interpreter\core\core.py", line 109, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 62, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\interpreter\core\core.py", line 117, in _streaming_chat
    yield from self._respond()
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\interpreter\core\core.py", line 143, in _respond
    yield from respond(self)
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\interpreter\core\respond.py", line 91, in respond
    raise Exception(f"{output}\n\nThere might be an issue with your API key(s).\n\nTo reset your API key (we'll use OPENAI_API_KEY for this example, but you may need to reset your ANTHROPIC_API_KEY, HUGGINGFACE_API_KEY, etc):\n        Mac/Linux: 'export OPENAI_API_KEY=your-key-here',\n        Windows: 'setx OPENAI_API_KEY your-key-here' then restart terminal.\n\n")
Exception: Traceback (most recent call last):
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\interpreter\core\respond.py", line 44, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\interpreter\llm\convert_to_coding_llm.py", line 19, in coding_llm
    for chunk in text_llm(messages):
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\interpreter\llm\setup_text_llm.py", line 117, in base_llm
    return litellm.completion(**params)
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\litellm\utils.py", line 798, in wrapper
    raise e
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\litellm\utils.py", line 757, in wrapper
    result = original_function(*args, **kwargs)
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "C:\Users\buzma\miniconda3\envs\stab\lib\concurrent\futures\_base.py", line 458, in result
    return self.__get_result()
  File "C:\Users\buzma\miniconda3\envs\stab\lib\concurrent\futures\_base.py", line 403, in __get_result
    raise self._exception
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\litellm\main.py", line 1195, in completion
    raise exception_type(
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\litellm\utils.py", line 3173, in exception_type
    raise e
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\litellm\utils.py", line 2530, in exception_type
    raise original_exception
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\litellm\main.py", line 815, in completion
    response = openai.ChatCompletion.create(
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 151, in create
    ) = cls.__prepare_create_request(
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 108, in __prepare_create_request
    requestor = api_requestor.APIRequestor(
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\openai\api_requestor.py", line 139, in __init__
    self.api_key = key or util.default_api_key()
  File "C:\Users\buzma\miniconda3\envs\stab\lib\site-packages\openai\util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(
openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.

There might be an issue with your API key(s).

To reset your API key (we'll use OPENAI_API_KEY for this example, but you may need to reset your ANTHROPIC_API_KEY, HUGGINGFACE_API_KEY, etc):
        Mac/Linux: 'export OPENAI_API_KEY=your-key-here',
        Windows: 'setx OPENAI_API_KEY your-key-here' then restart terminal.

**Comment by ghost** [comment]
Hey @buzman92 can you run this snippet and let me know if that works - 

```python
import os
from litellm import completion
os.environ["OPENROUTER_API_KEY"] = ""

response = completion(
            model="openrouter/openai/gpt-3.5-turbo",
            messages=[{"role":"user", "content":"Hey, how's it going?"}],
        )
print(response) 
```

**Comment by ghost** [comment]
closing as this is working during my testing, @buzman92 please re-open if the snippet doesn't work for you.
