### ISSUE TITLE
22:13:10 - LiteLLM Router:ERROR: router.py:2811 - litellm.router.py::async_function_with_fallbacks() - Error occurred while trying to do fallbacks - litellm.APIConnectionError: Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)]

### ISSUE THREAD

**Issue by shuvo881** [BerriAI/litellm#6580]
Traceback (most recent call last):
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1091, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 104, in start_connection
    raise first_exception
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 82, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 174, in _connect_sock
    await loop.sock_connect(sock, address)
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 691, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 11434)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/main.py", line 469, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/llms/ollama.py", line 564, in ollama_acompletion
    raise e  # don't use verbose_logger.exception, if exception is raised
    ^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/llms/ollama.py", line 505, in ollama_acompletion
    resp = await session.post(url, json=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/client.py", line 663, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 563, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1032, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1366, in _create_direct_connection
    raise last_exc
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1335, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1106, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)]
No fallback model group found for original model_group=reliable. Fallbacks=[{'instant': ['fast', 'reliable']}, {'accurate': ['accurate-medium', 'accurate-slow', 'reliable']}] LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
Traceback (most recent call last):
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1091, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 104, in start_connection
    raise first_exception
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 82, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 174, in _connect_sock
    await loop.sock_connect(sock, address)
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 691, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 11434)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/main.py", line 469, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/llms/ollama.py", line 564, in ollama_acompletion
    raise e  # don't use verbose_logger.exception, if exception is raised
    ^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/llms/ollama.py", line 505, in ollama_acompletion
    resp = await session.post(url, json=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/client.py", line 663, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 563, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1032, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1366, in _create_direct_connection
    raise last_exc
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1335, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1106, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/router.py", line 2795, in async_function_with_fallbacks
    raise original_exception
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/router.py", line 2672, in async_function_with_fallbacks
    response = await self.async_function_with_retries(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/router.py", line 3008, in async_function_with_retries
    raise original_exception
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/router.py", line 2920, in async_function_with_retries
    response = await self.make_call(original_function, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/router.py", line 3017, in make_call
    response = await response
               ^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/router.py", line 947, in _acompletion
    raise e
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/router.py", line 915, in _acompletion
    response = await _response
               ^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/utils.py", line 1227, in wrapper_async
    raise e
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/utils.py", line 1083, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/main.py", line 491, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2116, in exception_type
    raise e
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2092, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)]
Traceback (most recent call last):
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1091, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 104, in start_connection
    raise first_exception
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 82, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 174, in _connect_sock
    await loop.sock_connect(sock, address)
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 691, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 11434)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/main.py", line 469, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/llms/ollama.py", line 564, in ollama_acompletion
    raise e  # don't use verbose_logger.exception, if exception is raised
    ^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/llms/ollama.py", line 505, in ollama_acompletion
    resp = await session.post(url, json=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/client.py", line 663, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 563, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1032, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1366, in _create_direct_connection
    raise last_exc
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1335, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1106, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)]
No fallback model group found for original model_group=reliable. Fallbacks=[{'instant': ['fast', 'reliable']}, {'accurate': ['accurate-medium', 'accurate-slow', 'reliable']}] LiteLLM Retried: 1 times, LiteLLM Max Retries: 2

Debug Information:
Cooldown Deployments=[]
Error calling router.acompletion: litellm.APIConnectionError: Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)]
Traceback (most recent call last):
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1091, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 104, in start_connection
    raise first_exception
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 82, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 174, in _connect_sock
    await loop.sock_connect(sock, address)
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 691, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 11434)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/main.py", line 469, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/llms/ollama.py", line 564, in ollama_acompletion
    raise e  # don't use verbose_logger.exception, if exception is raised
    ^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/llms/ollama.py", line 505, in ollama_acompletion
    resp = await session.post(url, json=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/client.py", line 663, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 563, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1032, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1366, in _create_direct_connection
    raise last_exc
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1335, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1106, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)]
No fallback model group found for original model_group=reliable. Fallbacks=[{'instant': ['fast', 'reliable']}, {'accurate': ['accurate-medium', 'accurate-slow', 'reliable']}]
Received Model Group=reliable
Available Model Group Fallbacks=None
Error doing the fallback: litellm.APIConnectionError: Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)]
Traceback (most recent call last):
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1091, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 104, in start_connection
    raise first_exception
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 82, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 174, in _connect_sock
    await loop.sock_connect(sock, address)
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect
    return await fut
           ^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/selector_events.py", line 691, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
ConnectionRefusedError: [Errno 111] Connect call failed ('127.0.0.1', 11434)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/main.py", line 469, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/llms/ollama.py", line 564, in ollama_acompletion
    raise e  # don't use verbose_logger.exception, if exception is raised
    ^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/llms/ollama.py", line 505, in ollama_acompletion
    resp = await session.post(url, json=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/client.py", line 663, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 563, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1032, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1366, in _create_direct_connection
    raise last_exc
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1335, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1106, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:11434 ssl:default [Connect call failed ('127.0.0.1', 11434)]
No fallback model group found for original model_group=reliable. Fallbacks=[{'instant': ['fast', 'reliable']}, {'accurate': ['accurate-medium', 'accurate-slow', 'reliable']}] LiteLLM Retried: 1 times, LiteLLM Max Retries: 2 LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
Error type: <class 'litellm.exceptions.APIConnectionError'>
Error args: ('litellm.APIConnectionError: Cannot connect to host localhost:11434 ssl:default [Connect call failed (\'127.0.0.1\', 11434)]\nTraceback (most recent call last):\n  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1091, in _wrap_create_connection\n    sock = await aiohappyeyeballs.start_connection(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 104, in start_connection\n    raise first_exception\n  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 82, in start_connection\n    sock = await _connect_sock(\n           ^^^^^^^^^^^^^^^^^^^^\n  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohappyeyeballs/impl.py", line 174, in _connect_sock\n    await loop.sock_connect(sock, address)\n  File "/usr/lib/python3.12/asyncio/selector_events.py", line 651, in sock_connect\n    return await fut\n           ^^^^^^^^^\n  File "/usr/lib/python3.12/asyncio/selector_events.py", line 691, in _sock_connect_cb\n    raise OSError(err, f\'Connect call failed {address}\')\nConnectionRefusedError: [Errno 111] Connect call failed (\'127.0.0.1\', 11434)\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/main.py", line 469, in acompletion\n    response = await init_response\n               ^^^^^^^^^^^^^^^^^^^\n  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/llms/ollama.py", line 564, in ollama_acompletion\n    raise e  # don\'t use verbose_logger.exception, if exception is raised\n    ^^^^^^^\n  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/litellm/llms/ollama.py", line 505, in ollama_acompletion\n    resp = await session.post(url, json=data)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/client.py", line 663, in _request\n    conn = await self._connector.connect(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 563, in connect\n    proto = await self._create_connection(req, traces, timeout)\n            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1032, in _create_connection\n    _, proto = await self._create_direct_connection(req, traces, timeout)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1366, in _create_direct_connection\n    raise last_exc\n  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1335, in _create_direct_connection\n    transp, proto = await self._wrap_create_connection(\n                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/home/shuvo/Documents/ML Project/remote/triumv/env/lib/python3.12/site-packages/aiohttp/connector.py", line 1106, in _wrap_create_connection\n    raise client_error(req.connection_key, exc) from exc\naiohttp.client_exceptions.ClientConnectorError: Cannot connect to host localhost:11434 ssl:default [Connect call failed (\'127.0.0.1\', 11434)]\n',)

**Comment by ishaan-jaff** [comment]
this is not helpful, please add details of the issue you're seeing with clear instructions on how to repro

**Comment by shuvo881** [comment]
@ishaan-jaff Thanks,  I solved the problem. When a model or model does not available, that time gives this error.
