### ISSUE TITLE
[Bug]: File uploads with purpose=batch error out with 'Invalid value for purpose.'

### ISSUE THREAD

**Issue by siddhantgawsane** [BerriAI/litellm#6582]
### What happened?

I'm trying to use the batch APIs on my litellm deployment, but when I try to upload a file for batch inference I get 
``` 
{"error":{"message":"Error code: 400 - {'error': {'code': 'invalidPayload', 'message': 'Invalid value for purpose.'}}","type":null,"param":null,"code":"400"}}
```

### Relevant log output

```shell
openai-batch-test-py3.12➜  openai-batch-test curl -X 'POST' \
  'https://my-url.com/v1/files?provider=azure' \
  -H 'accept: application/json' \
  -H 'x-api-key: sk-dummy' \
  -H 'Content-Type: multipart/form-data' \
  -F 'purpose=batch' \
  -F 'custom_llm_provider=azure' \
  -F 'file=@data/test_run.jsonl'
{"error":{"message":"Error code: 400 - {'error': {'code': 'invalidPayload', 'message': 'Invalid value for purpose.'}}","type":null,"param":null,"code":"400"}}
```

**Comment by jaiv2303** [comment]
Seeing a similar issue. I was trying to get Batch requests to work with local LiteLLM instance. The following CURL request worked but using LiteLLM is failing.

LiteLLM Proxy version: 1.59.3
LiteLLM SDK: 1.59.1

config.yaml
```yaml
files_settings:
  - custom_llm_provider: azure
    api_base: https://<internal-endpoint>
    api_key: <api-key>
    api_version: "2024-10-21"
```

CURL works fine:
![Image](https://github.com/user-attachments/assets/b1bba416-61fd-45a3-bc4c-16acff7af0e7)


LiteLLM SDK doesn't:
```python
import os

import litellm

os.environ["LITELLM_LOG"] = "DEBUG"
litellm.set_verbose = True

file = litellm.create_file(
    api_base="http://localhost:4000",
    api_key="sk-PQOtv2YlZ2de_l83xbV5Ow",
    api_version="2024-10-21",
    file=open("data/request.jsonl", "rb"),
    purpose="batch",
    custom_llm_provider="azure",
)
print(file)
```

```logs
[2025-01-24 14:49:37 - httpx:82 - DEBUG] load_ssl_context verify=True cert=None trust_env=True http2=False
[2025-01-24 14:49:37 - httpx:148 - DEBUG] load_verify_locations cafile='/Users/jvepura/cert.pem'
[2025-01-24 14:49:37 - httpx:82 - DEBUG] load_ssl_context verify=True cert=None trust_env=True http2=False
[2025-01-24 14:49:37 - httpx:148 - DEBUG] load_verify_locations cafile='/Users/jvepura/cert.pem'
[2025-01-24 14:49:37 - httpx:82 - DEBUG] load_ssl_context verify=True cert=None trust_env=True http2=False
[2025-01-24 14:49:37 - httpx:148 - DEBUG] load_verify_locations cafile='/Users/jvepura/cert.pem'
[2025-01-24 14:49:38 - httpx:1038 - INFO] HTTP Request: GET https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json "HTTP/1.1 200 OK"
/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/pydantic/_internal/_config.py:345: UserWarning: Valid config keys have changed in V2:
* 'fields' has been removed
  warnings.warn(message, UserWarning)
[2025-01-24 14:49:38 - httpx:82 - DEBUG] load_ssl_context verify=True cert=None trust_env=True http2=False
[2025-01-24 14:49:38 - httpx:148 - DEBUG] load_verify_locations cafile='/Users/jvepura/cert.pem'
[2025-01-24 14:49:38 - httpx:82 - DEBUG] load_ssl_context verify=True cert=None trust_env=True http2=False
[2025-01-24 14:49:38 - httpx:148 - DEBUG] load_verify_locations cafile='/Users/jvepura/cert.pem'
[2025-01-24 14:49:38 - httpx:82 - DEBUG] load_ssl_context verify=True cert=None trust_env=True http2=False
[2025-01-24 14:49:38 - httpx:148 - DEBUG] load_verify_locations cafile='/Users/jvepura/cert.pem'
[2025-01-24 14:49:38 - httpx:82 - DEBUG] load_ssl_context verify=True cert=None trust_env=True http2=False
[2025-01-24 14:49:38 - httpx:148 - DEBUG] load_verify_locations cafile='/Users/jvepura/cert.pem'
[2025-01-24 14:49:38 - httpx:82 - DEBUG] load_ssl_context verify=True cert=None trust_env=True http2=False
[2025-01-24 14:49:38 - httpx:148 - DEBUG] load_verify_locations cafile='/Users/jvepura/cert.pem'
[2025-01-24 14:49:38 - openai._base_client:453 - DEBUG] Request options: {'method': 'post', 'url': '/files', 'headers': {'Content-Type': 'multipart/form-data', 'api-key': '<redacted>'}, 'files': [('file', SerializationIterator(index=0, iterator=SerializationIterator(index=0, iterator=<_io.BufferedReader name='/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/data/request.jsonl'>)))], 'json_data': {'purpose': 'batch'}}
[2025-01-24 14:49:38 - openai._base_client:993 - DEBUG] Sending HTTP Request: POST http://localhost:4000/openai/files?api-version=2024-10-21
[2025-01-24 14:49:38 - httpx:1038 - INFO] HTTP Request: POST http://localhost:4000/openai/files?api-version=2024-10-21 "HTTP/1.1 500 Internal Server Error"
[2025-01-24 14:49:38 - openai._base_client:1032 - DEBUG] HTTP Response: POST http://localhost:4000/openai/files?api-version=2024-10-21 "500 Internal Server Error" Headers({'date': 'Fri, 24 Jan 2025 19:49:38 GMT', 'server': 'uvicorn', 'content-length': '116', 'content-type': 'application/json'})
[2025-01-24 14:49:38 - openai._base_client:1040 - DEBUG] request_id: None
[2025-01-24 14:49:38 - openai._base_client:1045 - DEBUG] Encountered httpx.HTTPStatusError
Traceback (most recent call last):
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1043, in _request
    response.raise_for_status()
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://localhost:4000/openai/files?api-version=2024-10-21'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
[2025-01-24 14:49:38 - openai._base_client:740 - DEBUG] Retrying due to status code 500
[2025-01-24 14:49:38 - openai._base_client:1089 - DEBUG] 2 retries left
[2025-01-24 14:49:38 - openai._base_client:1092 - INFO] Retrying request to /files in 0.401860 seconds
[2025-01-24 14:49:39 - openai._base_client:453 - DEBUG] Request options: {'method': 'post', 'url': '/files', 'headers': {'Content-Type': 'multipart/form-data', 'api-key': '<redacted>'}, 'files': [('file', SerializationIterator(index=0, iterator=SerializationIterator(index=0, iterator=<_io.BufferedReader name='/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/data/request.jsonl'>)))], 'json_data': {'purpose': 'batch'}}
[2025-01-24 14:49:39 - openai._base_client:993 - DEBUG] Sending HTTP Request: POST http://localhost:4000/openai/files?api-version=2024-10-21
[2025-01-24 14:49:39 - httpx:1038 - INFO] HTTP Request: POST http://localhost:4000/openai/files?api-version=2024-10-21 "HTTP/1.1 500 Internal Server Error"
[2025-01-24 14:49:39 - openai._base_client:1032 - DEBUG] HTTP Response: POST http://localhost:4000/openai/files?api-version=2024-10-21 "500 Internal Server Error" Headers({'date': 'Fri, 24 Jan 2025 19:49:38 GMT', 'server': 'uvicorn', 'content-length': '116', 'content-type': 'application/json'})
[2025-01-24 14:49:39 - openai._base_client:1040 - DEBUG] request_id: None
[2025-01-24 14:49:39 - openai._base_client:1045 - DEBUG] Encountered httpx.HTTPStatusError
Traceback (most recent call last):
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1043, in _request
    response.raise_for_status()
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://localhost:4000/openai/files?api-version=2024-10-21'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1043, in _request
    response.raise_for_status()
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://localhost:4000/openai/files?api-version=2024-10-21'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
[2025-01-24 14:49:39 - openai._base_client:740 - DEBUG] Retrying due to status code 500
[2025-01-24 14:49:39 - openai._base_client:1087 - DEBUG] 1 retry left
[2025-01-24 14:49:39 - openai._base_client:1092 - INFO] Retrying request to /files in 0.832584 seconds
[2025-01-24 14:49:39 - openai._base_client:453 - DEBUG] Request options: {'method': 'post', 'url': '/files', 'headers': {'Content-Type': 'multipart/form-data', 'api-key': '<redacted>'}, 'files': [('file', SerializationIterator(index=0, iterator=SerializationIterator(index=0, iterator=<_io.BufferedReader name='/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/data/request.jsonl'>)))], 'json_data': {'purpose': 'batch'}}
[2025-01-24 14:49:39 - openai._base_client:993 - DEBUG] Sending HTTP Request: POST http://localhost:4000/openai/files?api-version=2024-10-21
[2025-01-24 14:49:39 - httpx:1038 - INFO] HTTP Request: POST http://localhost:4000/openai/files?api-version=2024-10-21 "HTTP/1.1 500 Internal Server Error"
[2025-01-24 14:49:39 - openai._base_client:1032 - DEBUG] HTTP Response: POST http://localhost:4000/openai/files?api-version=2024-10-21 "500 Internal Server Error" Headers({'date': 'Fri, 24 Jan 2025 19:49:39 GMT', 'server': 'uvicorn', 'content-length': '116', 'content-type': 'application/json'})
[2025-01-24 14:49:39 - openai._base_client:1040 - DEBUG] request_id: None
[2025-01-24 14:49:39 - openai._base_client:1045 - DEBUG] Encountered httpx.HTTPStatusError
Traceback (most recent call last):
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1043, in _request
    response.raise_for_status()
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://localhost:4000/openai/files?api-version=2024-10-21'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1043, in _request
    response.raise_for_status()
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://localhost:4000/openai/files?api-version=2024-10-21'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1043, in _request
    response.raise_for_status()
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'http://localhost:4000/openai/files?api-version=2024-10-21'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
[2025-01-24 14:49:39 - openai._base_client:1063 - DEBUG] Re-raising status error
Traceback (most recent call last):
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/bulk_request.py", line 8, in <module>
    file = litellm.create_file(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/litellm/files/main.py", line 675, in create_file
    raise e
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/litellm/files/main.py", line 625, in create_file
    response = azure_files_instance.create_file(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/litellm/llms/azure/files/handler.py", line 73, in create_file
    response = openai_client.files.create(**create_file_data)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/openai/resources/files.py", line 127, in create
    return self._post(
           ^^^^^^^^^^^
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1283, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 960, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1049, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1098, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1049, in _request
    return self._retry_request(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1098, in _retry_request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/Users/jvepura/jai_workspace/dev/genai/spikes/litellm-batch-api/.venv/lib/python3.12/site-packages/openai/_base_client.py", line 1064, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.InternalServerError: Error code: 500 - {'error': {'message': 'Object of type UploadFile is not JSON serializable', 'type': 'None', 'param': 'None', 'code': '500'}}
```

**Comment by ishaan-jaff** [comment]
hi @jaivep2323 - can you try this with the OpenAI SDK like this 

```python
from openai import OpenAI

# Initialize the client
client = OpenAI(
    base_url="http://localhost:4000",
    api_key="your-api-key"
)

batch_input_file = client.files.create(
    file=open("mydata.jsonl", "rb"),
    purpose="batch",
    extra_body={"custom_llm_provider": "azure"}
)
file_id = batch_input_file.id
```

**Comment by jaiv2303** [comment]
Hi @ishaan-jaff , thanks for looking into it. Following is the output of the code you shared. Its working using OpenAI SDK and was able to upload the file.

```bash
[2025-01-27 12:38:50 - httpx:82 - DEBUG] load_ssl_context verify=True cert=None trust_env=True http2=False
[2025-01-27 12:38:50 - httpx:148 - DEBUG] load_verify_locations cafile='/Users/jvepura/cert.pem'
[2025-01-27 12:38:50 - openai._base_client:453 - DEBUG] Request options: {'method': 'post', 'url': '/files', 'headers': {'Content-Type': 'multipart/form-data'}, 'files': [('file', SerializationIterator(index=0, iterator=SerializationIterator(index=0, iterator=<_io.BufferedReader name='data/request.jsonl'>)))], 'json_data': {'purpose': 'batch'}, 'extra_json': {'custom_llm_provider': 'azure'}}
[2025-01-27 12:38:51 - openai._base_client:993 - DEBUG] Sending HTTP Request: POST http://localhost:4000/files
[2025-01-27 12:38:53 - httpx:1038 - INFO] HTTP Request: POST http://localhost:4000/files "HTTP/1.1 200 OK"
[2025-01-27 12:38:53 - openai._base_client:1032 - DEBUG] HTTP Response: POST http://localhost:4000/files "200 OK" Headers({'date': 'Mon, 27 Jan 2025 17:38:50 GMT', 'server': 'uvicorn', 'content-length': '187', 'content-type': 'application/json', 'x-litellm-version': '1.59.3', 'x-litellm-response-cost': 'None', 'x-litellm-key-tpm-limit': 'None', 'x-litellm-key-rpm-limit': 'None', 'x-litellm-key-max-budget': 'None', 'x-litellm-key-spend': '0.0005115', 'x-litellm-response-duration-ms': 'None', 'x-litellm-overhead-duration-ms': 'None'})
[2025-01-27 12:38:53 - openai._base_client:1040 - DEBUG] request_id: None
file-72a8bcc824084e25b6773f1155ff4911
FileObject(id='file-72a8bcc824084e25b6773f1155ff4911', bytes=1159, created_at=1737999532, filename='request.jsonl', object='file', purpose='batch', status='processed', status_details=None)
```

**Comment by ishaan-jaff** [comment]
can we mark as closed ?

**Comment by jaiv2303** [comment]
Sorry @ishaan-jaff , I wasn't clear before. What I meant was I was able to upload using OpenAI SDK but still not using LiteLLM SDK.

I am using LiteLLM Proxy v1.59.3 and LiteLLM SDK v1.59.1
