### ISSUE TITLE
[Bug]: ollama

### ISSUE THREAD

**Issue by Pipboyguy** [BerriAI/litellm#659]
### What happened?

```litellm --model ollama/zephyr```

Package versions:
```
litellm            0.11.1
ollama version 0.1.3
```

### Relevant log output

```shell
'Router' object has no attribute 'model_names'
LiteLLM.Exception: 'Router' object has no attribute 'model_names'
INFO:     127.0.0.1:57310 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/litellm/proxy/llm.py", line 138, in litellm_completion
    if model_router and data["model"] in model_router.get_model_names():
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/litellm/router.py", line 100, in get_model_names
    return self.model_names
           ^^^^^^^^^^^^^^^^
AttributeError: 'Router' object has no attribute 'model_names'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/fastapi/applications.py", line 1115, in __call__
    await super().__call__(scope, receive, send)
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 515, in chat_completion
    return litellm_completion(data, type="chat_completion", user_model=user_model,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/litellm/proxy/llm.py", line 148, in litellm_completion
    handle_llm_exception(e=e, user_api_base=user_api_base)
  File "/home/marcel/mambaforge/envs/web-scraper/lib/python3.11/site-packages/litellm/proxy/llm.py", line 92, in handle_llm_exception
    raise UnknownLLMError from e
litellm.proxy.llm.UnknownLLMError```
```

### Twitter / LinkedIn details

https://www.linkedin.com/in/marcel-coetzee/

**Comment by ishaan-jaff** [comment]
fix is here: https://github.com/BerriAI/litellm/commit/220935c3cc308f71fdb97f2075249336a57d2d11 

waiting for a new deploy of the package

**Comment by Pipboyguy** [comment]
awesome thanks!

**Comment by chiefMarlin** [comment]
Confirmed fix working

**Comment by ishaan-jaff** [comment]
@chiefMarlin @Pipboyguy we're trying to make the proxy cli better. **Why do you use the proxy cli ?**
