### ISSUE TITLE
[Bug]: Can't use Anthropic's new text_editor_20241022/str_replace_editor tool

### ISSUE THREAD

**Issue by paul-gauthier** [BerriAI/litellm#6608]
### What happened?

See the attached simple code to use Anthropics new `text_editor_20241022/str_replace_editor` tool. It works when calling anthropic's SDK directly but crashes when calling via litellm.

The [demo code for the `computer_20241022/computer` tool](https://docs.litellm.ai/docs/providers/anthropic#computer-tools) works fine.

So this is something special about `text_editor_20241022/str_replace_editor`. I'm guessing it is because it doesn't take any `parameters`?

Tested against `litellm==1.52.0`.

### Relevant log output

```shell
import anthropic
import litellm

kwargs = dict(
    tools = [
        {
            "type": "text_editor_20241022",
            "name": "str_replace_editor",
        }
    ],
    model = "claude-3-5-sonnet-20241022",
    max_tokens=4096,
    betas= ["computer-use-2024-10-22"],
    messages = [{"role": "user", "content": "Make a python program that prints hello world."}\
],
)

anthropic_client = anthropic.Anthropic()
anthropic_resp = anthropic_client.beta.messages.create(**kwargs)
print("Anthropic:")
print(anthropic_resp)

print()
print("LiteLLM:")
litellm_resp = litellm.completion(**kwargs)
print(litellm_resp)

### Output: ##############

Anthropic:
BetaMessage(id='msg_012c4CsriKF1i62th56yaBD4', content=[BetaTextBlock(text='I\'ll help you create a simple Python program that prints "Hello World". I\'ll use the str_replace_editor to create this file.', type='text'), BetaToolUseBlock(id='toolu_01CjZzSAvum3HTJX1LeB6CqD', input={'command': 'create', 'path': '/repo/hello.py', 'file_text': 'print("Hello World")'}, name='str_replace_editor', type='tool_use')], model='claude-3-5-sonnet-20241022', role='assistant', stop_reason='tool_use', stop_sequence=None, type='message', usage=BetaUsage(cache_creation_input_tokens=None, cache_read_input_tokens=None, input_tokens=1184, output_tokens=137))

LiteLLM:

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.


Provider List: https://docs.litellm.ai/docs/providers


Provider List: https://docs.litellm.ai/docs/providers

Traceback (most recent call last):
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/main.py", line 992, in completion
    optional_params = get_optional_params(
                      ^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/utils.py", line 2818, in get_optional_params
    optional_params = litellm.AnthropicConfig().map_openai_params(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/llms/anthropic/chat/transformation.py", line 255, in map_openai_params
    optional_params["tools"] = self._map_tools(value)
                               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/llms/anthropic/chat/transformation.py", line 238, in _map_tools
    new_tool = self._map_tool_helper(tool)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/llms/anthropic/chat/transformation.py", line 207, in _map_tool_helper
    function_name = tool["function"].get("name")
                    ~~~~^^^^^^^^^^^^
KeyError: 'function'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/gauthier/Projects/aider/./tmp.py", line 72, in <module>
    litellm_resp = litellm.completion(**kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/utils.py", line 1014, in wrapper
    raise e
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/utils.py", line 904, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/main.py", line 3006, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2126, in exception_type
    raise e
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2102, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: litellm.APIConnectionError: 'function'
Traceback (most recent call last):
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/main.py", line 992, in completion
    optional_params = get_optional_params(
                      ^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/utils.py", line 2818, in get_optional_params
    optional_params = litellm.AnthropicConfig().map_openai_params(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/llms/anthropic/chat/transformation.py", line 255, in map_openai_params
    optional_params["tools"] = self._map_tools(value)
                               ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/llms/anthropic/chat/transformation.py", line 238, in _map_tools
    new_tool = self._map_tool_helper(tool)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/llms/anthropic/chat/transformation.py", line 207, in _map_tool_helper
    function_name = tool["function"].get("name")
                    ~~~~^^^^^^^^^^^^
KeyError: 'function'
```

**Comment by paul-gauthier** [comment]
I forgot to say, if I mimic the way the docs use the computer tool with a `function` dict added in:

```
    tools = [
        {
            "type": "text_editor_20241022",
            "function" : {
                "name": "str_replace_editor",
            }
        }
    ],
```

I get a different error:

```
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2122, in exception_type
    raise e
  File "/Users/gauthier/Projects/aider/.venv/lib/python3.12/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 469, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: litellm.BadRequestError: AnthropicException - {"type":"error","error":{"type":"invalid_request_error","message":"tools.0.type: Extra inputs are not permitted"}}
```

**Comment by paul-gauthier** [comment]
Nevermind, I got this working. I think the `betas` parameter was not effective. I had to add `extra_headers={"anthropic-beta": "computer-use-2024-10-22"}`.
