### ISSUE TITLE
[Bug]:  Autogen:You cannot set content to an empty string

### ISSUE THREAD

**Issue by chiefMarlin** [BerriAI/litellm#661]
### What happened?

Hi,
Im trying to use latest autogen with litellm via ollama `litellm --model ollama/codellama --api_base http://localhost:11434 --temperature 0.3 --max_tokens 2048`

Not sure whether this is an issue with autogen or litellm as the issue seems to be 
`LiteLLM.Exception: You cannot set content to an empty string. We interpret empty strings as None in requests.You may set {
  "content": null,
  "role": "assistant"
}.content = None to delete the property`

Here is the autogen config used:
[
    {
        "model": "ollama/codellama",
        "api_key": "sk-111111111111111111111111111111111111111111111111",
        "api_type": "open_ai",
        "api_base": "http://127.0.0.1:8000/v1"
    }
]

### Relevant log output

```shell
#################################### LiteLLM Error: ####################################
[GIN] 2023/10/21 - 02:19:36 | 404 |     668.619µs |       127.0.0.1 | POST     "/api/generate"

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

You cannot set content to an empty string. We interpret empty strings as None in requests.You may set {
  "content": null,
  "role": "assistant"
}.content = None to delete the property
LiteLLM.Exception: You cannot set content to an empty string. We interpret empty strings as None in requests.You may set {
  "content": null,
  "role": "assistant"
}.content = None to delete the property
[GIN] 2023/10/21 - 02:19:39 | 404 |     386.322µs |       127.0.0.1 | POST     "/api/generate"

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

You cannot set content to an empty string. We interpret empty strings as None in requests.You may set {
  "content": null,
  "role": "assistant"
}.content = None to delete the property
LiteLLM.Exception: You cannot set content to an empty string. We interpret empty strings as None in requests.You may set {
  "content": null,
  "role": "assistant"
}.content = None to delete the property
[GIN] 2023/10/21 - 02:19:39 | 404 |      90.449µs |       127.0.0.1 | POST     "/api/generate"

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

You cannot set content to an empty string. We interpret empty strings as None in requests.You may set {
  "content": null,
  "role": "assistant"
}.content = None to delete the property
LiteLLM.Exception: You cannot set content to an empty string. We interpret empty strings as None in requests.You may set {
  "content": null,
  "role": "assistant"
}.content = None to delete the property
INFO:     172.17.0.1:56002 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/litellm/main.py", line 1122, in completion
    model_response["choices"][0]["message"]["content"] = response_string
  File "/usr/local/lib/python3.10/site-packages/openai/openai_object.py", line 71, in __setitem__
    raise ValueError(
ValueError: You cannot set content to an empty string. We interpret empty strings as None in requests.You may set {
  "content": null,
  "role": "assistant"
}.content = None to delete the property

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/litellm/proxy/llm.py", line 141, in litellm_completion
    response = litellm.completion(**data)
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 827, in wrapper
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 786, in wrapper
    result = original_function(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/litellm/timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/litellm/timeout.py", line 42, in async_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/litellm/main.py", line 1259, in completion
    raise exception_type(
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 3303, in exception_type
    raise e
  File "/usr/local/lib/python3.10/site-packages/litellm/utils.py", line 3285, in exception_type
    raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: You cannot set content to an empty string. We interpret empty strings as None in requests.You may set {
  "content": null,
  "role": "assistant"
}.content = None to delete the property

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 1115, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.10/site-packages/litellm/proxy/proxy_server.py", line 515, in chat_completion
    return litellm_completion(data, type="chat_completion", user_model=user_model,
  File "/usr/local/lib/python3.10/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/backoff/_sync.py", line 105, in retry
    ret = target(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/litellm/proxy/llm.py", line 148, in litellm_completion
    handle_llm_exception(e=e, user_api_base=user_api_base)
  File "/usr/local/lib/python3.10/site-packages/litellm/proxy/llm.py", line 76, in handle_llm_exception
    raise RetryConstantError from e
litellm.proxy.llm.RetryConstantError
########################################################################



############################## AUTOGEN Error ##################################
user_proxy (to assistant):

Tell me the min, max and avg of td bank stock for past year

--------------------------------------------------------------------------------
[autogen.oai.completion: 10-21 02:19:39] {234} INFO - retrying in 10 seconds...
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 413, in handle_error_response
    error_data = resp["error"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/autogen/oai/completion.py", line 220, in _get_response
    response = openai_completion.create(request_timeout=request_timeout, **config)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 415, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: 'Internal Server Error' (HTTP response code was 500)
^CTraceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 413, in handle_error_response
    error_data = resp["error"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/autogen/oai/completion.py", line 220, in _get_response
    response = openai_completion.create(request_timeout=request_timeout, **config)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
  File "/usr/local/lib/python3.10/site-packages/openai/api_requestor.py", line 415, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: 'Internal Server Error' (HTTP response code was 500)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/main.py", line 9, in <module>
    user_proxy.initiate_chat(assistant, message="Tell me the min, max and avg of td bank stock for past year")
  File "/usr/local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 531, in initiate_chat
    self.send(self.generate_init_message(**context), recipient, silent=silent)
  File "/usr/local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 334, in send
    recipient.receive(message, self, request_reply, silent)
  File "/usr/local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 462, in receive
    reply = self.generate_reply(messages=self.chat_messages[sender], sender=sender)
  File "/usr/local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 781, in generate_reply
    final, reply = reply_func(self, messages=messages, sender=sender, config=reply_func_tuple["config"])
  File "/usr/local/lib/python3.10/site-packages/autogen/agentchat/conversable_agent.py", line 606, in generate_oai_reply
    response = oai.ChatCompletion.create(
  File "/usr/local/lib/python3.10/site-packages/autogen/oai/completion.py", line 799, in create
    response = cls.create(
  File "/usr/local/lib/python3.10/site-packages/autogen/oai/completion.py", line 830, in create
    return cls._get_response(params, raise_on_ratelimit_or_timeout=raise_on_ratelimit_or_timeout)
  File "/usr/local/lib/python3.10/site-packages/autogen/oai/completion.py", line 235, in _get_response
    sleep(retry_wait_time)
KeyboardInterrupt
```

**Comment by chiefMarlin** [comment]
🤦 Looks like as others have reported, model must be correct.
Not an issue

**Comment by ishaan-jaff** [comment]
@chiefMarlin did you only use codellama with the proxy or did you try other llms ?
