### ISSUE TITLE
[Bug]: Can't send emails to non-authenticated server

### ISSUE THREAD

**Issue by tkg61** [BerriAI/litellm#6625]
### What happened?

Emails won't work unless you have a username/password but on-premise email servers don't always require auth...

Need to support SMTP servers that don't require login. 

need an `if username and password` here: https://github.com/BerriAI/litellm/blob/45ff74ae81e331412370cd7436816559fd6298da/litellm/proxy/utils.py#L2496 

### Relevant log output

```shell
20:44:16 - LiteLLM Proxy:DEBUG: utils.py:108 - An error occurred while sending the email:SMTP AUTH extension not supported by server.
litellm-litellm-1     | Traceback (most recent call last):
litellm-litellm-1     |   File "/usr/local/lib/python3.11/site-packages/litellm/proxy/utils.py", line 2494, in send_email
litellm-litellm-1     |     server.login(smtp_username, smtp_password)  # type: ignore
litellm-litellm-1     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-litellm-1     |   File "/usr/local/lib/python3.11/smtplib.py", line 716, in login
litellm-litellm-1     |     raise SMTPNotSupportedError(
litellm-litellm-1     | smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.
```

**Comment by schnaker85** [comment]
we do face the same problem, not having an smtp with auth (mostly in corporates ip whitelisting is used to allow senders not an particular auth)

is there any update on this @krrishdholakia?

**Comment by gebele** [comment]
same issue here any updates on this ?  We have no auth and port 25, current litellm v1.88.1

```
12:08:19 - LiteLLM Proxy:ERROR: utils.py:5096 - An error occurred while sending the email:(535, b'5.7.8 Error: authentication failed: (reason unavailable)')
Traceback (most recent call last):
  File "/app/.venv/lib/python3.13/site-packages/litellm/proxy/utils.py", line 5083, in send_email
    server.login(
    ~~~~~~~~~~~~^
        user=smtp_username,
        ^^^^^^^^^^^^^^^^^^^
        REDACTED,
        ^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/lib/python3.13/smtplib.py", line 764, in login
    raise last_exception
  File "/usr/lib/python3.13/smtplib.py", line 753, in login
    (code, resp) = self.auth(
                   ~~~~~~~~~^
        authmethod, getattr(self, method_name),
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        initial_response_ok=initial_response_ok)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/smtplib.py", line 671, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.8 Error: authentication failed: (reason unavailable)')
```

**Comment by teddythinh** [comment]
If the credential doesn't specify it in the environment field, it should be clearly mentioned as optional in the document, right? As I read the document, it still appears to be mandatory. 

<img width="461" height="494" alt="Image" src="https://github.com/user-attachments/assets/912f417c-8e90-4fcf-ac56-2d20acc25ea4" />
