### ISSUE TITLE
[Bug]: OpenAI v1/audio/transcriptions  Invalid proxy server token passed. valid_token=None.","type":"auth_error","param":"None","code":"401"

### ISSUE THREAD

**Issue by kiaev** [BerriAI/litellm#6638]
### What happened?

curl https://my-litellm.io/v1/audio/transcriptions \
  -H "Authorization: Bearer XXXXXXXXXXXXXXXX" \
  -H "Content-Type: multipart/form-data" \
  -F file="@./mono.mp3" \
  -F model="whisper-1"
  I receive error
  Invalid proxy server token passed. valid_token=None.","type":"auth_error","param":"None","code":"401"
  when i sent directly it's all work normal
  curl https://api.openai.com/v1/audio/transcriptions \
>   -H "Authorization: Bearer XXXXXXXXXXXXX" \
>   -H "Content-Type: multipart/form-data" \
>   -F file="@./mono.mp3" \
>   -F model="whisper-1"
{
  "text": "This is some speech transcription to text"
  could you assist with this
  litellm version v1.51.3

**Comment by ishaan-jaff** [comment]
please try sending the correct proxy auth token, the error it's raising is self explanatory. This is not a bug from your logs

**Comment by kiaev** [comment]
@ishaan-jaff , thanks for you answer. I already have released more 10 tokens, but same error. I use 4 model gpt-4o, gpt-3.5-turbo,gpt-4o-mini, these models work with these tokens. Only whisper don't work with any tokens. 
I tried OPENAI_API_KEY instead token , same issue 3 model work , whisper don't work

**Comment by kiaev** [comment]
in logs litellm
`127.0.0.6:58493 - "POST /v1/audio/transcriptions HTTP/1.1" 401
09:01:48 - LiteLLM Proxy:ERROR: user_api_key_auth.py:1176 - litellm.proxy.proxy_server.user_api_key_auth(): Exception occured - Stream consumed
Requester IP Address:127.0.0.6
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/auth/user_api_key_auth.py", line 836, in user_api_key_auth
    data = await request.json()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/requests.py", line 251, in json
    body = await self.body()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/starlette/requests.py", line 244, in body
    async for chunk in self.stream():
  File "/usr/local/lib/python3.11/site-packages/starlette/requests.py", line 227, in stream
    raise RuntimeError("Stream consumed")
RuntimeError: Stream consumed`

**Comment by kiaev** [comment]
@ishaan-jaff we found workarround in this issue https://github.com/BerriAI/litellm/issues/6161
we used token for all models. Is it work for us

**Comment by kiaev** [comment]
@ishaan-jaff and also could you add in UI form data `-F 'model="whisper-1"'`
to this request
`curl -X 'POST' \
  'https://lite-llm.xxx.xxx.xxxx/v1/audio/transcriptions' \
  -H 'accept: application/json' \
  -H 'x-api-key: sk-XXXXXXXXXXX' \
  -H 'Content-Type: multipart/form-data' \
  -F 'file=@mono.mp3;type=audio/mpeg'`

**Comment by ishaan-jaff** [comment]
do you still see this on latest @kiaev ?

**Comment by hollamad** [comment]
I'm taking a look at this

**Comment by hollamad** [comment]
Issue is not reproducible on the latest codebase
Here's what I did:
1) Setup a proxy with the latest docker image built from `main`
2) Add `whisper-1` model using UI and create a virtual key
3) Call the API using curl with multipart data of audio file and model parameter

Request works fine with both `All model` key and key created for the specific model.
