### ISSUE TITLE
[Bug]: AzureOpenAI dall-e 3 image response throws 500 internal server error TypeError: unexpected keyword argument 'content_filter_results'

### ISSUE THREAD

**Issue by UlfEberle** [BerriAI/litellm#6643]
### What happened?

When generating an image with Azure OpenAI dall-e 3 endpoint I'm running into a 500 internal server error. This behavior started after upgrading to accommodate for Azure o1-preview model capabilities.
Dockerimage https://github.com/berriai/litellm/pkgs/container/litellm/297940220?tag=main-v1.51.2

### Relevant log output

```shell
[92m17:12:57 - LiteLLM Proxy:ERROR[0m: proxy_server.py:4013 - litellm.proxy.proxy_server.image_generation(): Exception occured - litellm.APIConnectionError: AzureException APIConnectionError - Invalid response object Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/litellm_core_utils/llm_response_utils/convert_dict_to_response.py", line 453, in convert_to_model_response_object
    return LiteLLMResponseObjectHandler.convert_to_image_response(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/litellm_core_utils/llm_response_utils/convert_dict_to_response.py", line 235, in convert_to_image_response
    model_response_object = ImageResponse(**model_response_dict)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/types/utils.py", line 1207, in __init__
    _data.append(ImageObject(**d))
                 ^^^^^^^^^^^^^^^^
TypeError: ImageObject.__init__() got an unexpected keyword argument 'content_filter_results'
```

**Comment by ishaan-jaff** [comment]
please retry on https://github.com/BerriAI/litellm/releases/tag/v1.52.1 

it's fixed already
