### ISSUE TITLE
[Bug]: coroutine ignored GeneratorExit when using Redis with multiple parallel requests

### ISSUE THREAD

**Issue by yuriykuzin** [BerriAI/litellm#6707]
### What happened?

When using LiteLLM Router with Redis and multiple parallel requests, sometimes (within current code, I see it from the second run) I see `coroutine ignored GeneratorExit` errors. These errors appear during the shutdown phase when Redis connections are being closed.

### Minimal reproduction:
```
import asyncio
from litellm import Router
import os


MODEL_NAME = "azure/gpt-4o"  # Change to your deployment name
API_BASE = "..."  # Insert your api base

API_VERSION = "2023-12-01-preview"
API_KEY = os.getenv("AZURE_API_KEY")

REDIS_URL = "redis://localhost:6379"


async def main():
    router = Router(
        model_list=[
            {
                "model_name": MODEL_NAME,
                "litellm_params": {
                    "model": MODEL_NAME,
                    "api_base": API_BASE,
                    "api_key": API_KEY,
                    "api_version": API_VERSION,
                },
            }
        ],
        redis_url=REDIS_URL,
    )

    messages = [
        {
            "role": "user",
            "content": "Return a random name, 1 word",
        }
    ]

    # Create parallel requests for reproduction
    tasks = []
    for i in range(200):
        task = router.acompletion(
            model=MODEL_NAME,
            messages=messages,
        )
        tasks.append(task)

    responses = await asyncio.gather(*tasks)
    for i, response in enumerate(responses, 1):
        print(f"Attempt {i} succeeded: {response.choices[0].message.content}")

if __name__ == "__main__":
    asyncio.run(main())

```

### Steps to reproduce:
1. Install dependencies:
```bash
pip install litellm redis
```

2. Start Redis:
```bash
docker run --name redis -d -p 6379:6379 redis
```

3. Set Azure AZURE_API_KEY as environment variables, and replace this code with your deployment name and api base:
```
MODEL_NAME = "azure/gpt-4o"
API_BASE = "..."    # insert your api base
```

4. Run the script.

### Current behavior:
- Program executes all requests successfully
- On exit, multiple errors appear:
```
13:25:28 - LiteLLM Router:ERROR: router.py:3336 - litellm.router.Router::deployment_callback_on_success(): Exception occured - coroutine ignored GeneratorExit
Traceback (most recent call last):
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/router.py", line 3321, in deployment_callback_on_success
    await self.cache.async_increment_cache(
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/caching/dual_cache.py", line 373, in async_increment_cache
    raise e  # don't log if exception is raised
    ^^^^^^^
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/caching/dual_cache.py", line 364, in async_increment_cache
    result = await self.redis_cache.async_increment(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine ignored GeneratorExit
Task was destroyed but it is pending!
```

And:
```
task: <Task pending name='Task-1283' coro=<Logging.async_success_handler() running at /Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/litellm_core_utils/litellm_logging.py:1601> wait_for=<Future pending cb=[Task.task_wakeup()]>>
```

### Expected behavior:
- Program should cleanly shut down without coroutine errors
- All Redis connections should be properly closed

### Relevant log output

```shell
python reproduce2.py

13:30:50 - LiteLLM Router:ERROR: router.py:3336 - litellm.router.Router::deployment_callback_on_success(): Exception occured - coroutine ignored GeneratorExit
Traceback (most recent call last):
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/router.py", line 3321, in deployment_callback_on_success
    await self.cache.async_increment_cache(
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/caching/dual_cache.py", line 373, in async_increment_cache
    raise e  # don't log if exception is raised
    ^^^^^^^
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/caching/dual_cache.py", line 364, in async_increment_cache
    result = await self.redis_cache.async_increment(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine ignored GeneratorExit
Task was destroyed but it is pending!
task: <Task pending name='Task-1421' coro=<Logging.async_success_handler() done, defined at /Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/litellm_core_utils/litellm_logging.py:1386> wait_for=<Future pending cb=[Task.task_wakeup()]>>
13:30:50 - LiteLLM Router:ERROR: router.py:3336 - litellm.router.Router::deployment_callback_on_success(): Exception occured - coroutine ignored GeneratorExit
Traceback (most recent call last):
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/router.py", line 3321, in deployment_callback_on_success
    await self.cache.async_increment_cache(
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/caching/dual_cache.py", line 373, in async_increment_cache
    raise e  # don't log if exception is raised
    ^^^^^^^
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/caching/dual_cache.py", line 364, in async_increment_cache
    result = await self.redis_cache.async_increment(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine ignored GeneratorExit
Task was destroyed but it is pending!
task: <Task pending name='Task-1423' coro=<Logging.async_success_handler() done, defined at /Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/litellm_core_utils/litellm_logging.py:1386> wait_for=<Future pending cb=[Task.task_wakeup()]>>
13:30:50 - LiteLLM Router:ERROR: router.py:3336 - litellm.router.Router::deployment_callback_on_success(): Exception occured - coroutine ignored GeneratorExit
Traceback (most recent call last):
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/router.py", line 3321, in deployment_callback_on_success
    await self.cache.async_increment_cache(
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/caching/dual_cache.py", line 373, in async_increment_cache
    raise e  # don't log if exception is raised
    ^^^^^^^
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/caching/dual_cache.py", line 364, in async_increment_cache
    result = await self.redis_cache.async_increment(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine ignored GeneratorExit
Task was destroyed but it is pending!
task: <Task pending name='Task-1431' coro=<Logging.async_success_handler() done, defined at /Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/litellm_core_utils/litellm_logging.py:1386> wait_for=<Future pending cb=[Task.task_wakeup()]>>
13:30:50 - LiteLLM Router:ERROR: router.py:3336 - litellm.router.Router::deployment_callback_on_success(): Exception occured - coroutine ignored GeneratorExit
Traceback (most recent call last):
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/router.py", line 3321, in deployment_callback_on_success
    await self.cache.async_increment_cache(
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/caching/dual_cache.py", line 373, in async_increment_cache
    raise e  # don't log if exception is raised
    ^^^^^^^
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/caching/dual_cache.py", line 364, in async_increment_cache
    result = await self.redis_cache.async_increment(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine ignored GeneratorExit
Task was destroyed but it is pending!
task: <Task pending name='Task-1433' coro=<Logging.async_success_handler() done, defined at /Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/litellm_core_utils/litellm_logging.py:1386> wait_for=<Future pending cb=[Task.task_wakeup()]>>
13:30:50 - LiteLLM Router:ERROR: router.py:3336 - litellm.router.Router::deployment_callback_on_success(): Exception occured - coroutine ignored GeneratorExit
Traceback (most recent call last):
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/router.py", line 3321, in deployment_callback_on_success
    await self.cache.async_increment_cache(
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/caching/dual_cache.py", line 373, in async_increment_cache
    raise e  # don't log if exception is raised
    ^^^^^^^
  File "/Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/caching/dual_cache.py", line 364, in async_increment_cache
    result = await self.redis_cache.async_increment(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: coroutine ignored GeneratorExit
Task was destroyed but it is pending!
task: <Task pending name='Task-1435' coro=<Logging.async_success_handler() done, defined at /Users/studytube/studytube/skills-ontology/.conda/lib/python3.12/site-packages/litellm/litellm_core_utils/litellm_logging.py:1386> wait_for=<Future pending cb=[Task.task_wakeup()]>>
Attempt 1 succeeded: Liam
Attempt 2 succeeded: Ava
Attempt 3 succeeded: Sophia
Attempt 4 succeeded: Liam
Attempt 5 succeeded: Aiden
Attempt 6 succeeded: Alex
Attempt 7 succeeded: Lydia
Attempt 8 succeeded: Jasper
Attempt 9 succeeded: Liam
Attempt 10 succeeded: Lila
Attempt 11 succeeded: Avery
Attempt 12 succeeded: Celeste
Attempt 13 succeeded: Elena
Attempt 14 succeeded: Chloe
Attempt 15 succeeded: Liam
Attempt 16 succeeded: Liam
Attempt 17 succeeded: Aiden
Attempt 18 succeeded: Liam
Attempt 19 succeeded: Aria
Attempt 20 succeeded: Alex
Attempt 21 succeeded: Ava
Attempt 22 succeeded: Liam
Attempt 23 succeeded: Ariana
Attempt 24 succeeded: Sophia
Attempt 25 succeeded: Liam
Attempt 26 succeeded: Aiden
Attempt 27 succeeded: Olivia
Attempt 28 succeeded: Liam
Attempt 29 succeeded: Liam
Attempt 30 succeeded: Ella
Attempt 31 succeeded: Eleanor
Attempt 32 succeeded: Lucas
Attempt 33 succeeded: Ava
Attempt 34 succeeded: Avery
Attempt 35 succeeded: Harper
Attempt 36 succeeded: Liam
Attempt 37 succeeded: Sophia
Attempt 38 succeeded: Liam
Attempt 39 succeeded: Oliver
Attempt 40 succeeded: Aiden
Attempt 41 succeeded: Alex
Attempt 42 succeeded: Alex
Attempt 43 succeeded: Ava
Attempt 44 succeeded: Elena
Attempt 45 succeeded: Alexa
Attempt 46 succeeded: Liam
Attempt 47 succeeded: Liam
Attempt 48 succeeded: Aiden
Attempt 49 succeeded: Aurora
Attempt 50 succeeded: Aria
Attempt 51 succeeded: Ashley
Attempt 52 succeeded: Liam
Attempt 53 succeeded: Oliver
Attempt 54 succeeded: Lydia
Attempt 55 succeeded: Liam
Attempt 56 succeeded: Oliver
Attempt 57 succeeded: Sophia
Attempt 58 succeeded: Aurora
Attempt 59 succeeded: Aiden
Attempt 60 succeeded: Alex
Attempt 61 succeeded: Sophia
Attempt 62 succeeded: Aria
Attempt 63 succeeded: Liam
Attempt 64 succeeded: Jasper
Attempt 65 succeeded: Jasper
Attempt 66 succeeded: Liam
Attempt 67 succeeded: Eleanor
Attempt 68 succeeded: Julian
Attempt 69 succeeded: Aurora
Attempt 70 succeeded: Ava
Attempt 71 succeeded: Aiden
Attempt 72 succeeded: Caden
Attempt 73 succeeded: Elena
Attempt 74 succeeded: Aiden
Attempt 75 succeeded: A random name: Emily
Attempt 76 succeeded: Liam
Attempt 77 succeeded: Aria
Attempt 78 succeeded: Samantha
Attempt 79 succeeded: Liam
Attempt 80 succeeded: Liam
Attempt 81 succeeded: Hannah
Attempt 82 succeeded: Logan
Attempt 83 succeeded: Liam
Attempt 84 succeeded: Liam
Attempt 85 succeeded: Liam
Attempt 86 succeeded: Aurora
Attempt 87 succeeded: Aiden
Attempt 88 succeeded: Sophia
Attempt 89 succeeded: Liam
Attempt 90 succeeded: Lia
Attempt 91 succeeded: Ava
Attempt 92 succeeded: Liam
Attempt 93 succeeded: Liam
Attempt 94 succeeded: Liam
Attempt 95 succeeded: Ava
Attempt 96 succeeded: Liam
Attempt 97 succeeded: Liana
Attempt 98 succeeded: Liam
Attempt 99 succeeded: Alex
Attempt 100 succeeded: Alex
Attempt 101 succeeded: Liam
Attempt 102 succeeded: Liam
Attempt 103 succeeded: Liam
Attempt 104 succeeded: Liam
Attempt 105 succeeded: Ella
Attempt 106 succeeded: Liam
Attempt 107 succeeded: Sophia
Attempt 108 succeeded: Aiden
Attempt 109 succeeded: Alex
Attempt 110 succeeded: Jasmine
Attempt 111 succeeded: Alex.
Attempt 112 succeeded: Aiden
Attempt 113 succeeded: Aiden
Attempt 114 succeeded: Liam
Attempt 115 succeeded: Liam
Attempt 116 succeeded: Harper
Attempt 117 succeeded: Marcus
Attempt 118 succeeded: Skye
Attempt 119 succeeded: Sophia
Attempt 120 succeeded: Emma
Attempt 121 succeeded: Liam
Attempt 122 succeeded: Aiden
Attempt 123 succeeded: Aria
Attempt 124 succeeded: Liam
Attempt 125 succeeded: Aria
Attempt 126 succeeded: Liam
Attempt 127 succeeded: Elara
Attempt 128 succeeded: Lydia
Attempt 129 succeeded: Nova
Attempt 130 succeeded: Liam
Attempt 131 succeeded: Cameron
Attempt 132 succeeded: Luna
Attempt 133 succeeded: Sophia
Attempt 134 succeeded: Evelyn
Attempt 135 succeeded: Evelyn
Attempt 136 succeeded: Liam
Attempt 137 succeeded: Alex
Attempt 138 succeeded: Aiden
Attempt 139 succeeded: Luna
Attempt 140 succeeded: Emily
Attempt 141 succeeded: Ava
Attempt 142 succeeded: Sophia
Attempt 143 succeeded: Aiden
Attempt 144 succeeded: Chloe
Attempt 145 succeeded: Liam
Attempt 146 succeeded: Ava
Attempt 147 succeeded: Aiden
Attempt 148 succeeded: Elena
Attempt 149 succeeded: Alex.
Attempt 150 succeeded: Lila
Attempt 151 succeeded: Lydia
Attempt 152 succeeded: Liam
Attempt 153 succeeded: Liam
Attempt 154 succeeded: Sophia
Attempt 155 succeeded: Alex
Attempt 156 succeeded: Luna
Attempt 157 succeeded: Elena
Attempt 158 succeeded: Zara
Attempt 159 succeeded: Ava
Attempt 160 succeeded: Liam
Attempt 161 succeeded: Liam
Attempt 162 succeeded: Liam
Attempt 163 succeeded: Liam
Attempt 164 succeeded: Aiden
Attempt 165 succeeded: Aidan
Attempt 166 succeeded: Liam
Attempt 167 succeeded: Luna
Attempt 168 succeeded: Evelyn
Attempt 169 succeeded: Alex
Attempt 170 succeeded: Alexa
Attempt 171 succeeded: Aiden
Attempt 172 succeeded: Liam
Attempt 173 succeeded: Lily
Attempt 174 succeeded: Lydia
Attempt 175 succeeded: Jasper
Attempt 176 succeeded: Liam
Attempt 177 succeeded: Liam
Attempt 178 succeeded: Liam
Attempt 179 succeeded: Liam
Attempt 180 succeeded: Sure, here's a random name for you: Alex
Attempt 181 succeeded: Jackson
Attempt 182 succeeded: Liam
Attempt 183 succeeded: Alex.
Attempt 184 succeeded: Liam
Attempt 185 succeeded: Luna
Attempt 186 succeeded: Liam
Attempt 187 succeeded: Liam
Attempt 188 succeeded: Alex
Attempt 189 succeeded: Sophia
Attempt 190 succeeded: Liam
Attempt 191 succeeded: Avery
Attempt 192 succeeded: Liam
Attempt 193 succeeded: Liam
Attempt 194 succeeded: Marcus
Attempt 195 succeeded: Jasper
Attempt 196 succeeded: Aurora
Attempt 197 succeeded: Aiden
Attempt 198 succeeded: Liam
Attempt 199 succeeded: Alex
Attempt 200 succeeded: Alex
```

**Comment by john-groves-bread** [comment]
I am also seeing this issue, using a Redis Cluster as a cache

**Comment by Robert-Cunningham** [comment]
Also seeing this with a redis cache.
