### ISSUE TITLE
[Bug]: OpenTelemetry logging error in set_attributes 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by pimlock** [BerriAI/litellm#6717]
### What happened?

Invalid `.get()` call in [here](https://github.com/BerriAI/litellm/blob/bac2ac2a49102c91dea475c42891f463b60744bd/litellm/integrations/opentelemetry.py#L508) causes:
```
OpenTelemetry logging error in set_attributes 'NoneType' object has no attribute 'get'
```

Scenario:
- OTEL is turned on for LiteLLM.
- The call to the LLM fails and there is no response (e.g. validation error from the LLM provider). 
- `OpenTelemetry.set_attributes()` is called with `response_obj = None`.
- `response_obj.get()` causes `'NoneType' object has no attribute 'get'` [here](https://github.com/BerriAI/litellm/blob/bac2ac2a49102c91dea475c42891f463b60744bd/litellm/integrations/opentelemetry.py#L508)

Extra context:
- Other than error message being logged, this issue also causes prompt missing from the `litellm_request` spans (the `gen_ai.prompt...` attributes).
- This `set_attributes` method already guards against `request_obj` being `None`, but in a different place: https://github.com/BerriAI/litellm/blob/v1.51.3/litellm/integrations/opentelemetry.py#L576

### Relevant log output

```shell
Traceback (most recent call last):
  File "python3.9/site-packages/litellm/llms/OpenAI/openai.py", line 854, in completion
    raise e
  File "python3.9/site-packages/litellm/llms/OpenAI/openai.py", line 790, in completion
    self.make_sync_openai_chat_completion_request(
  File "python3.9/site-packages/litellm/llms/OpenAI/openai.py", line 649, in make_sync_openai_chat_completion_request
    raise e
  File "python3.9/site-packages/litellm/llms/OpenAI/openai.py", line 631, in make_sync_openai_chat_completion_request
    raw_response = openai_client.chat.completions.with_raw_response.create(
  File "python3.9/site-packages/openai/_legacy_response.py", line 356, in wrapped
    return cast(LegacyAPIResponse[R], func(*args, **kwargs))
  File "python3.9/site-packages/openai/_utils/_utils.py", line 275, in wrapper
    return func(*args, **kwargs)
  File "python3.9/site-packages/openai/resources/chat/completions.py", line 829, in create
    return self._post(
  File "python3.9/site-packages/openai/_base_client.py", line 1278, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "python3.9/site-packages/openai/_base_client.py", line 955, in request
    return self._request(
  File "python3.9/site-packages/openai/_base_client.py", line 1059, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.NotFoundError: Error code: 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python3.9/site-packages/litellm/main.py", line 1586, in completion
    raise e
  File "python3.9/site-packages/litellm/main.py", line 1559, in completion
    response = openai_chat_completions.completion(
  File "python3.9/site-packages/litellm/llms/OpenAI/openai.py", line 864, in completion
    raise OpenAIError(
litellm.llms.OpenAI.openai.OpenAIError: Error code: 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python3.9/site-packages/litellm/utils.py", line 903, in wrapper
    result = original_function(*args, **kwargs)
  File "python3.9/site-packages/litellm/main.py", line 2998, in completion
    raise exception_type(
  File "python3.9/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2116, in exception_type
    raise e
  File "python3.9/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 352, in exception_type
    raise NotFoundError(
litellm.exceptions.NotFoundError: litellm.NotFoundError: NotFoundError: OpenAIException - Error code: 404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "python3.9/site-packages/litellm/integrations/opentelemetry.py", line 508, in set_attributes
    if response_obj.get("id"):
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by ishaan-jaff** [comment]
<img width="695" alt="Screenshot 2024-11-12 at 6 18 31 PM" src="https://github.com/user-attachments/assets/bf9c9507-48d3-499a-8637-ba05ced839f1">

already fixed on main latest

**Comment by ishaan-jaff** [comment]
https://github.com/BerriAI/litellm/blob/4192d7ec6f75849eeb79b3455558493fcebc447e/litellm/integrations/opentelemetry.py#L524

**Comment by ishaan-jaff** [comment]
pls re-open if not fixed

also sent you a linkedin DM to setup a support channel @pimlock - could you accept ?

**Comment by pimlock** [comment]
Thanks for a quick response! 

You're right, it was already fixed and in the next version from what I was using, I missed that.

**Comment by ishaan-jaff** [comment]
hi @pimlock - curious do you use LiteLLM Proxy in production or are you evaluating it ?

If yes, we'd love to hop on a call to get your feedback on how we can improve. Sharing our calendly for your convenience https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
