### ISSUE TITLE
[Bug]: Starting with v1.52.0 logging with Langfuse leads to error: "team_id missing from team"

### ISSUE THREAD

**Issue by CalabiYau14** [BerriAI/litellm#6787]
### What happened?

First of all thanks for the great work. Unfortunately I encounter a small bug starting with v1.52.0

I need to log to Langfuse and for this I use the following config:

litellm_settings: 
  default_team_settings: 
    - team_id: c91e32bb-0f2a-4aa1-86c4-307ca2e03ea3 
      success_callback: ["langfuse"]
      failure_callback: ["langfuse"]
      langfuse_public_key: ***
      langfuse_secret: ***
      
This then leads to the following error (see also added Stacktrace):
Exception: team_id missing from team

Do you have any ideas why this happens? Thanks in advance and cheers

### Relevant log output

```shell
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 3295, in chat_completion
    data = await add_litellm_data_to_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/litellm_pre_call_utils.py", line 512, in add_litellm_data_to_request
    team_config = await proxy_config.load_team_config(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 1472, in load_team_config
    raise Exception(f"team_id missing from team: {team}")
Exception: team_id missing from team: {'success_callback': ['langfuse'], 'failure_callback': ['langfuse'], 'langfuse_public_key': 'pk-lf-008c75dc-f7a6-4e8b-8f3a-3fa8631cedf6', 'langfuse_secret': 'sk-lf-64ca0c4b-8a4f-4c81-896f-7e59864d057c'}
07:38:24 - LiteLLM Proxy:ERROR: _common.py:120 - Giving up chat_completion(...) after 1 tries (litellm.proxy._types.ProxyException)
INFO:     10.13.0.29:36316 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
07:38:24 - LiteLLM Proxy:ERROR: proxy_server.py:3482 - litellm.proxy.proxy_server.chat_completion(): Exception occured - team_id missing from team: {'success_callback': ['langfuse'], 'failure_callback': ['langfuse'], 'langfuse_public_key': 'pk-lf-008c75dc-f7a6-4e8b-8f3a-3fa8631cedf6', 'langfuse_secret': 'sk-lf-64ca0c4b-8a4f-4c81-896f-7e59864d057c'}
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 3295, in chat_completion
    data = await add_litellm_data_to_request(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/litellm_pre_call_utils.py", line 512, in add_litellm_data_to_request
    team_config = await proxy_config.load_team_config(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 1472, in load_team_config
    raise Exception(f"team_id missing from team: {team}")
Exception: team_id missing from team
```

**Comment by nomarek** [comment]
I've also encountered this issue. It seems that the team_id is being removed from the dictionary, which is apparent in the error message reported by the CalabiYau14.

`07:38:24 - LiteLLM Proxy:ERROR: proxy_server.py:3482 - litellm.proxy.proxy_server.chat_completion(): Exception occured - team_id missing from team: {'success_callback': ['langfuse'], 'failure_callback': ['langfuse'], 'langfuse_public_key': '***', 'langfuse_secret': '***'}`

**Comment by nomarek** [comment]
I think the bug might be in `ProxyConfig.load_team_config`. [This assignment](https://github.com/BerriAI/litellm/blob/ddfe687b13e9f31db2fb2322887804e3d01dd467/litellm/proxy/proxy_server.py#L1489):
```python
team_config = team
```
Should be a dictionary copy instead:
```python
team_config = team.copy()
```
This is necessary because `add_litellm_data_to_request` pops `team_id` from `team_config` [here](https://github.com/BerriAI/litellm/blob/ddfe687b13e9f31db2fb2322887804e3d01dd467/litellm/proxy/litellm_pre_call_utils.py#L537):
```python
team_id = team_config.pop("team_id", None)
```
As a result, `team_id` is missing in subsequent calls to `load_team_config`.

**Comment by kgrovor** [comment]
We are still facing this issue with v1.54.0

**Comment by CalabiYau14** [comment]
Also tried to fix it with the above, but did not work ... :-(

**Comment by Manouchehri** [comment]
I've managed to finally fix this in #7114.

**Comment by ghost** [comment]
sorry all - just seeing this, will review #7114 and make sure this is fixed

**Comment by langgg0511** [comment]
@krrishdholakia  In version v1.55.8-stable, the issue still persists.

**Comment by ghost** [comment]
@langgg0511 what is the value of `litellm_settings` in your db config table? 

the initial issue was caused due to a simple override b/w db and config settings. I modified it to be more careful on how it updates the dictionary 

```
    def _update_config_fields(
        self,
        current_config: dict,
        param_name: str,
        db_param_value: Any,
    ) -> dict:
        if isinstance(current_config[param_name], dict):
            # if dict exists (e.g. litellm_settings),
            # go through each key and value,
            # and update if new value is not None/empty dict
            for key, value in db_param_value.items():
                if value:
                    current_config[param_name][key] = value
        else:
            current_config[param_name] = db_param_value
        return current_config
```

**Comment by Manouchehri** [comment]
I've been using #7114 for a while and it seems to be working. I was nervous about applying the other fix that was in main, so I haven't updated yet.

**Comment by ghost** [comment]
@Manouchehri i've left comments on the pr - let's address that there


if you'd like to help resolve the issue, this information would be good to know: 

> what is the value of litellm_settings in your db config table?

**Comment by themrzmaster** [comment]
i still face this issue. my config:
```
litellm_settings:
  num_retries: 2
  fallbacks: [{"llama-v3-70b-instruct-hf": ["llama-v3-70b-instruct-together"]}, {"gemini-1.5-flash": ["gemini-1.5-flash-studio"]}, {"gemini-1.5-flash-002": ["gemini-1.5-flash-002-vertex"]}, {"gpt-4o-mini-azure": ["gpt-4o-mini"]}, {"gpt-4o-mini": ["gpt-4o-mini-azure"]}]
  success_callback: ["prometheus"]
  failure_callback: ["prometheus"]
  default_team_settings: 
    - team_id: test
      success_callback: ["langfuse"]
      langfuse_public_key: os.environ/LANGFUSE_PUBLIC_KEY
      langfuse_secret: os.environ/LANGFUSE_SECRET_KEY

```

**Comment by langgg0511** [comment]
@krrishdholakia config table has no data.
![image](https://github.com/user-attachments/assets/a374a618-0ef3-417b-b320-eb7a071b870c)

**Comment by langgg0511** [comment]
litellm config
```yaml
general_settings:
  master_key: "sk-123"
  alerting: ["slack"]
  alert_types: ["llm_exceptions", "llm_requests_hanging"]
  database_url: "postgresql://postgres:123456@localhost:5432/litellm"
  database_connection_pool_limit: 2
  database_connection_timeout: 60
  proxy_batch_write_at: 60
  store_model_in_db: false

litellm_settings:
  ssl_verify: false
  json_logs: false
  cache: True
  cache_params:
    type: redis
    namespace: "litellm_caching"
    host: "redis.db"
    port: 6379
    ttl: 86400
    supported_call_types: ["acompletion", "atext_completion", "aembedding", "atranscription"]

  drop_params: true
  num_retries: 0
  redact_user_api_key_info: true
  default_team_settings:
    - team_id: "team_1"
      success_callback: ["langfuse"]
      langfuse_public_key: "fake-key"
      langfuse_secret: "fake-secret"
      langfuse_host: "http://localhost:30005.com"
    - team_id: "team_2"
      success_callback: ["langfuse"]
      langfuse_public_key: "fake-key-2"
      langfuse_secret: "fake-secret-2"
      langfuse_host: "http://localhost:30005.com"

router_settings:
  routing_strategy: simple-shuffle
  num_retries: 0
  allowed_fails: 20 # cooldown model if it fails > 1 call in a minute.
  cooldown_time: 5 # how long to cooldown model if fails/min > allowed_fails
```

first request:
![image](https://github.com/user-attachments/assets/7bdbbcc2-bc5e-48e1-800e-c7351d521017)

second request
![image](https://github.com/user-attachments/assets/9f165553-fe03-4d80-823f-8ce00c30684c)

**Comment by ghost** [comment]
this is the relevant code block overriding the config w/ db values - 

```python
    async def _update_config_from_db(
        self,
        prisma_client: PrismaClient,
        config: dict,
        store_model_in_db: Optional[bool],
    ):

        if store_model_in_db is not True:
            verbose_proxy_logger.info(
                "'store_model_in_db' is not True, skipping db updates"
            )
            return config

        _tasks = []
        keys = [
            "general_settings",
            "router_settings",
            "litellm_settings",
            "environment_variables",
        ]
        for k in keys:
            response = prisma_client.get_generic_data(
                key="param_name", value=k, table_name="config"
            )
            _tasks.append(response)

        responses = await asyncio.gather(*_tasks)
        for response in responses:
            if response is not None:
                param_name = getattr(response, "param_name", None)
                verbose_proxy_logger.info(f"loading {param_name} settings from db")
                if param_name == "litellm_settings":
                    verbose_proxy_logger.info(
                        f"litellm_settings: {response.param_value}"
                    )
                param_value = getattr(response, "param_value", None)
                if param_name is not None and param_value is not None:
                    # check if param_name is already in the config
                    if param_name in config:
                        config = self._update_config_fields(
                            current_config=config,
                            param_name=param_name,
                            db_param_value=param_value,
                        )
                    else:
                        # if it's not in the config - then add it
                        config[param_name] = param_value

        return config

```

do you see any of these in your debug logs when running litellm proxy with `--detailed_debug` @langgg0511 / @themrzmaster ?

**Comment by langgg0511** [comment]
@krrishdholakia There will be a large number of this debug logs.
![image](https://github.com/user-attachments/assets/30c19b8a-5340-44a2-802e-f46427a0598a)

**Comment by langgg0511** [comment]
@krrishdholakia sorry，the previous error was store_model_in_db=false. When this value is set to true, the request is successful, but Langfuse has no logs.

**Comment by ghost** [comment]
Was able to repro the issue. Overlapping issues, but initial issue was caused by the team_id being popped from config. Since we moved to using the `self.config` instead of making potential db calls each time, this issue where state was being mutated, was exposed. 

Erroring line: https://github.com/BerriAI/litellm/blob/bd4ab1449e78a2d4bc209ef7c781c018add9f8e1/litellm/proxy/litellm_pre_call_utils.py#L562

This should be fixed here - https://github.com/BerriAI/litellm/pull/7400/commits/8e3a54dae3e3b6faf5afefaa5e4e3db078ec75b8#diff-cb47ff448a23857ca19cd50f8baa9aea47ee5cdefb475803fdc022449dc10d7e

by creating a `get_config_state()` and returning a deepcopy of the config, to prevent this + any future helper utils from modifying the base config state

**Comment by ghost** [comment]
This should be fixed in v1.55.12 

Please bump and let me know if you see this too @themrzmaster @langgg0511

**Comment by langgg0511** [comment]
The problem still seems to persist. @krrishdholakia 

If store_model_in_db=true, the model can return successfully, but Langfuse does not log.

![image](https://github.com/user-attachments/assets/709793c3-8750-4043-9770-db5cd0eed3b4)


If store_model_in_db=false

![image](https://github.com/user-attachments/assets/8e72c94b-5ca8-45d3-b6b9-956395a0bb00)

**Comment by ghost** [comment]
@langgg0511 please use v1.55.12 

i saw your issue - identified it was caused due to the initialization of the new langfuse prompt management custom logger class, and fixed it there

let me know if this still persists on that version

**Comment by langgg0511** [comment]
@krrishdholakia I am sure I am using v1.55.12, and the issue still persists. The results can be returned, but Langfuse still has no logs. My Langfuse version is v3.5.0.

**Comment by themrzmaster** [comment]
Still having problems. Any update?

**Comment by ghost** [comment]
@langgg0511 reading your error trace, it seems outdated 

for eg. line 1379 in proxy_server.py no longer has `load_team_config` - https://github.com/BerriAI/litellm/blob/406b7f43a8ba9312b2831fca4aeddcced54f3009/litellm/proxy/proxy_server.py#L1379


it should be on line 1556 - https://github.com/BerriAI/litellm/blob/406b7f43a8ba9312b2831fca4aeddcced54f3009/litellm/proxy/proxy_server.py#L1556

this is important as the change was to return a deepcopy of the config (similar to @Manouchehri's approach) to prevent the pop happening in litellm_pre_call_utils.py

https://github.com/BerriAI/litellm/blob/406b7f43a8ba9312b2831fca4aeddcced54f3009/litellm/proxy/litellm_pre_call_utils.py#L366

from impacting subsequent calls

**Comment by ghost** [comment]
@themrzmaster if you're seeing a similar issue on the latest version of litellm, can you please share the stacktrace?

**Comment by stephaneminisini** [comment]
built: FROM ghcr.io/berriai/litellm-database:main-v1.55.12 docker image

I'm getting the same error at the same line # as @langgg0511:

{
    "message": "litellm.proxy.proxy_server.chat_completion(): Exception occured - team_id missing from team: {'success_callback': ['langfuse'], 'langfuse_public_key': 'pk-lf-1111111111111111111', 'langfuse_secret': 'sk-lf-1111111111111111111111', 'langfuse_host': 'https://xxxxxxxxxxxxxxxx'}",
    "level": "ERROR",
    "timestamp": "2024-12-30T04:09:10.423947",
    "stacktrace": "Traceback (most recent call last):\n  File \"/usr/local/lib/python3.13/site-packages/litellm/proxy/proxy_server.py\", line 3242, in chat_completion\n    data = await add_litellm_data_to_request(\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    ...<6 lines>...\n    )\n    ^\n  File \"/usr/local/lib/python3.13/site-packages/litellm/proxy/litellm_pre_call_utils.py\", line 556, in add_litellm_data_to_request\n    team_config = await proxy_config.load_team_config(\n                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n        team_id=user_api_key_dict.team_id\n        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n    )\n    ^\n  File \"/usr/local/lib/python3.13/site-packages/litellm/proxy/proxy_server.py\", line 1379, in load_team_config\n    team_config = self._get_team_config(\n        team_id=team_id, all_teams_config=all_teams_config\n    )\n  File \"/usr/local/lib/python3.13/site-packages/litellm/proxy/proxy_server.py\", line 1356, in _get_team_config\n    raise Exception(f\"team_id missing from team: {team}\")\nException: team_id missing from team: {'success_callback': ['langfuse'], 'langfuse_public_key': 'pk-lf-1111111111111111111', 'langfuse_secret': 'sk-lf-11111111111111111111', 'langfuse_host': 'https://xxxxxxxxxxxxxxxxxxxxxxxxx'}"
}

In 1.56.4, there is a success message built from ghcr.io/berriai/litellm-database:main-v1.56.4

{
    "message": "Langfuse Layer Logging - logging success",
    "level": "INFO",
    "timestamp": "2024-12-30T04:25:12.650487"
}

However, nothing is logged. I tried with the us.cloud.langfuse.com at v3.5.0 and a self hosted langfuse of 2.92.0. 

Thanks

**Comment by ghost** [comment]
@stephaneminisini can you enable langfuse debug, i believe their sdk (which we use) does some batch logging which might be causing the error to be swalled 

`LANGFUSE_DEBUG = "True"`

**Comment by stephaneminisini** [comment]
Langfuse is complaining about invalid credentials, "No key for public key". I triple checked the keys in the config.yaml and they are correct. I would suspect that litellm may not be sending the key correctly. 
The langfuse log doesn't give me the key that was passed.

**Comment by ghost** [comment]
that's really helpful. Similar to @langgg0511's issue. Weird since i didn't see this. 

Let me add better debug logging and follow up here @stephaneminisini 

thanks for the quick revert

**Comment by Manouchehri** [comment]
This sounds like https://github.com/BerriAI/litellm/issues/4944 now.

**Comment by ghost** [comment]
@Manouchehri not really - your saying it's being mislogged. The error here seems to be credentials not being passed in (if it was mislogged it would be going to another project altogether)

**Comment by ghost** [comment]
tomorrow i'll work on qa'ing this flow more and see if i'm able to repro some of the errors mentioned

thank you everyone for the feedback so far - sorry for the ongoing issue
