### ISSUE TITLE
[Bug]: LiteLLM not working with Langfuse

### ISSUE THREAD

**Issue by FaresKi** [BerriAI/litellm#682]
### What happened?

A bug happened!
I've been experimenting with LiteLLM and Langfuse and for some strange reason I run into the following errors:
```
LiteLLM: [Non-Blocking] Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/litellm/integrations/langfuse.py", line 15, in __init__
    from langfuse import Langfuse
ImportError: cannot import name 'Langfuse' from 'langfuse'
```
Langfuse is installed and all but it's doing as if it wasn't.

**Comment by ghost** [comment]
Seems like a python environment issue. 

Can you try:

`pip install langfuse`

`python -m pip install langfuse`

`poetry add langfuse`

**Comment by ghost** [comment]
Is this for our openai-proxy? @FaresKi

**Comment by FaresKi** [comment]
No Langfuse is installed and I can see so when checking my venv.
And no it's not for the openai-proxy but I'm using it with Azure OpenAI

**Comment by ghost** [comment]
@FaresKi agreed. Sometimes this can occur because there's different things running our code (i.e. if you pip installed it but didn't python -m pip install..). 

Can you try running the other 2 commands i shared, and let me know if that helps. If not - happy to do a live debug. I'm unable to repro the problem on our end (either local or in our CI/CD pipeline).

**Comment by FaresKi** [comment]
So I confirm having ran pip & python -m pip.
I'm using a virtual env and I can confirm (check below), that langfuse is installed
<img width="1005" alt="image" src="https://github.com/BerriAI/litellm/assets/46092308/74813fb9-eb3f-4b70-aa32-a90ce9a45f46">
Here's the full error log:
```
Langfuse not installed, try running 'pip install langfuse' to fix this error

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/litellm/main.py", line 308, in completion
    logging.update_environment_variables(model=model, user=user, optional_params=optional_params, litellm_params=litellm_params)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'update_environment_variables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/venv/lib/python3.11/site-packages/litellm/utils.py", line 786, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/litellm/timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.5/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/B242PN/Documents/CC/unit8-experimental/venv/lib/python3.11/site-packages/litellm/timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/B242PN/Documents/CC/unit8-experimental/venv/lib/python3.11/site-packages/litellm/main.py", line 1259, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/venv/lib/python3.11/site-packages/litellm/utils.py", line 3303, in exception_type
    raise e
  File "/venv/lib/python3.11/site-packages/litellm/utils.py", line 3285, in exception_type
    raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: 'NoneType' object has no attribute 'update_environment_variables'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/test/litellm/monitor/langfuse.py", line 18, in <module>
    response = litellm.completion("azure/PDFtoCCwithOpenAI", messages)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "venv/lib/python3.11/site-packages/litellm/utils.py", line 816, in wrapper
    threading.Thread(target=logging_obj.failure_handler, args=(e, traceback_exception, start_time, end_time)).start()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'failure_handler'
```
Somehow the lib fetching isn't working as expected.

**Comment by ishaan-jaff** [comment]
@FaresKi can you share your code snippet where you're initializing langfuse and making the llm api call ? I'm trying to repro it

**Comment by FaresKi** [comment]
Sure:
```py
import litellm
import os
from dotenv import load_dotenv
load_dotenv()

os.environ["AZURE_API_KEY"] = os.getenv("AZURE_OPEN_AI_KEY")
os.environ["AZURE_API_BASE"] = os.getenv("OPENAI_API_BASE")
os.environ["AZURE_API_VERSION"] = os.getenv("OPENAI_API_VERSION")
os.environ["LANGFUSE_HOST"]="https://cloud.langfuse.com"
litellm.success_callback = ["langfuse"] 
messages = [
    {
        "content": "Tell me a joke about an elephant and a flying saucer",
        "role": "user"
    }
]

response = litellm.completion("azure/<model_name>", messages)
```

My .env looks like this:
```
LANGFUSE_SECRET_KEY=sk-***
LANGFUSE_PUBLIC_KEY=pk-***
```

And my `pip freeze` returns this:
```
aiohttp==3.8.6
aiosignal==1.3.1
anyio==3.7.1
appdirs==1.4.4
async-timeout==4.0.3
attrs==23.1.0
backoff==2.2.1
certifi==2023.7.22
charset-normalizer==3.3.1
click==8.1.7
dataclasses-json==0.6.1
fastapi==0.104.0
filelock==3.12.4
frozenlist==1.4.0
fsspec==2023.10.0
h11==0.14.0
httpcore==0.17.3
httpx==0.24.1
huggingface-hub==0.17.3
idna==3.4
importlib-metadata==6.8.0
Jinja2==3.1.2
jsonpatch==1.33
jsonpointer==2.4
langchain==0.0.321
langfuse==1.0.33
langsmith==0.0.51
litellm==0.11.1
MarkupSafe==2.1.3
marshmallow==3.20.1
multidict==6.0.4
mypy-extensions==1.0.0
numpy==1.24.2
openai==0.28.1
packaging==23.2
pandas==2.1.1
phoenix==0.9.1
pydantic==1.10.13
python-dateutil==2.8.2
python-dotenv==1.0.0
pytz==2023.3.post1
PyYAML==6.0.1
regex==2023.10.3
requests==2.31.0
six==1.16.0
sniffio==1.3.0
SQLAlchemy==2.0.22
starlette==0.27.0
tenacity==8.2.3
tiktoken==0.5.1
tokenizers==0.14.1
tqdm==4.66.1
typing-inspect==0.9.0
typing_extensions==4.8.0
tzdata==2023.3
urllib3==2.0.7
yarl==1.9.2
zipp==3.17.0
```

**Comment by ishaan-jaff** [comment]
taking a look at this

**Comment by ishaan-jaff** [comment]
@FaresKi I'm unable to repro your issue, I pushed a dev version of litellm, can you try the following:

- `pip install litellm==0.12.5.dev1`
- re run your code 

- it should print the exception right after 'Langfuse not installed, try running 'pip install langfuse' to fix this error" 

lets see what shows up

**Comment by ishaan-jaff** [comment]
- can you also verify you're able to run the following in a python file in your venv

```python
from langfuse import Langfuse
```

**Comment by ishaan-jaff** [comment]
closing based on discord discussion, this was an issue because the the users file was called `langfuse.py` which raised an error when litellm was trying to run `from langfuse import Langfuse` 

feel free to re open if I missed anything @FaresKi
