### ISSUE TITLE
proxy-server + petals?

### ISSUE THREAD

**Issue by johnd0e** [BerriAI/litellm#687]
Is it possible?

What have I tried:
- run proxy as usual: `python main.py`
- request with curl, with this payload:
```json
{
  "model": "petals/petals-team/StableBeluga2",
  "messages": [
    {
      "content": "Hello, whats the weather in San Francisco??",
      "role": "user"
    }
  ]
}
```

Unfortunately this does not work

_Originally posted by @johnd0e in https://github.com/BerriAI/litellm/issues/141#issuecomment-1714093903_

**Comment by ishaan-jaff** [comment]
what's the error @johnd0e ?

**Comment by johnd0e** [comment]
At first I see this in server terminal:
<details>

```
Either an env variable `SLACK_BOT_TOKEN` or `token` argument in the constructor is required.

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

got error'NoneType' object has no attribute 'failure_handler'
calling model gpt-3.5-turbo

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

calling model command-nightly

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

calling model claude-2

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.
```
</details>
Then (after a minute or so) there appears the error message

```
ERROR:main:Exception on /chat/completions [POST]
Traceback (most recent call last):
  File "D:\AI\litellm\proxy-server\venv\lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\AI\litellm\proxy-server\venv\lib\site-packages\flask\app.py", line 870, in full_dispatch_request
    return self.finalize_request(rv)
  File "D:\AI\litellm\proxy-server\venv\lib\site-packages\flask\app.py", line 889, in finalize_request
    response = self.make_response(rv)
  File "D:\AI\litellm\proxy-server\venv\lib\site-packages\flask\app.py", line 1161, in make_response
    raise TypeError(
TypeError: The view function for 'api_completion' did not return a valid response. The function either returned None or ended without a return statement.
```

After that in curl console I see this:
```
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```

**Comment by ghost** [comment]
can you confirm if your proxy is running?
