### ISSUE TITLE
[Bug]: Can't use preview model codechat-bison-32k

### ISSUE THREAD

**Issue by rhysviz** [BerriAI/litellm#694]
### What happened?

I would like to use the vertex ai codechat-bison-32k model but it is in preview at the moment and seems to error.

Example:
```
from litellm import completion
response = completion(model="vertex_ai/codechat-bison-32k", messages=[{'role': 'user', 'content': 'hi'}])
print(response)
```

(As an aside, why does `codechat-bison` require the `vertex_ai/` prefix but `chat-bison` does not?)

### Relevant log output

```shell
❯ python test.py

Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/home/workspace/pr-agent/venv/lib/python3.11/site-packages/litellm/main.py", line 954, in completion
    model_response = vertex_ai.completion(
                     ^^^^^^^^^^^^^^^^^^^^^
  File "/home/workspace/pr-agent/venv/lib/python3.11/site-packages/litellm/llms/vertex_ai.py", line 93, in completion
    chat_model = ChatModel.from_pretrained(model)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/workspace/pr-agent/venv/lib/python3.11/site-packages/vertexai/_model_garden/_model_garden_models.py", line 316, in from_pretrained
    return _from_pretrained(interface_class=cls, model_name=model_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/workspace/pr-agent/venv/lib/python3.11/site-packages/vertexai/_model_garden/_model_garden_models.py", line 218, in _from_pretrained
    model_info = _get_model_info(
                 ^^^^^^^^^^^^^^^^
  File "/home/workspace/pr-agent/venv/lib/python3.11/site-packages/vertexai/_model_garden/_model_garden_models.py", line 180, in _get_model_info
    raise ValueError(
ValueError: Unknown model publishers/google/models/codechat-bison-32k; {'gs://google-cloud-aiplatform/schema/predict/instance/chat_generation_1.0.0.yaml': <class 'vertexai.preview.language_models._PreviewChatModel'>}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/workspace/pr-agent/test.py", line 3, in <module>
    response = completion(model="vertex_ai/codechat-bison-32k", messages=[{'role': 'user', 'content': 'hi'}])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/workspace/pr-agent/venv/lib/python3.11/site-packages/litellm/utils.py", line 828, in wrapper
    raise e
  File "/home/workspace/pr-agent/venv/lib/python3.11/site-packages/litellm/utils.py", line 787, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/workspace/pr-agent/venv/lib/python3.11/site-packages/litellm/timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/workspace/.asdf/installs/python/3.11.5/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/home/workspace/.asdf/installs/python/3.11.5/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/workspace/pr-agent/venv/lib/python3.11/site-packages/litellm/timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/workspace/pr-agent/venv/lib/python3.11/site-packages/litellm/main.py", line 1266, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/home/workspace/pr-agent/venv/lib/python3.11/site-packages/litellm/utils.py", line 3328, in exception_type
    raise e
  File "/home/workspace/pr-agent/venv/lib/python3.11/site-packages/litellm/utils.py", line 3310, in exception_type
    raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: Unknown model publishers/google/models/codechat-bison-32k; {'gs://google-cloud-aiplatform/schema/predict/instance/chat_generation_1.0.0.yaml': <class 'vertexai.preview.language_models._PreviewChatModel'>}
```

**Comment by rhysviz** [comment]
I can fix this by editing the model lists:

```
from litellm import completion

litellm.vertex_chat_models = ['chat-bison', 'chat-bison@001', 'chat-bison-32k', 'code-gecko@001', 'code-gecko@latest']
litellm.vertex_code_chat_models = ['codechat-bison-32k']

response = completion(model="vertex_ai/codechat-bison-32k", messages=[{'role': 'user', 'content': 'hi'}])
print(response)
```

The problem seems to be in `llms/vertex_ai.py:91` where it selects `ChatModel` for `codechat-bison-32k` when I think it should select `CodeChatModel`.

**Comment by ghost** [comment]
Hey @rhysviz just register the model like this - https://docs.litellm.ai/docs/completion/token_usage#8-register_model

I'll add it to our model list 

```

from litellm import register_model

litellm.register_model({
        "gpt-4": {
        "max_tokens": 8192, 
        "input_cost_per_token": 0.00002, 
        "output_cost_per_token": 0.00006, 
        "litellm_provider": "openai", 
        "mode": "chat"
    },
})

```

**Comment by ghost** [comment]
actually no, that wouldn't fix the issue. and i think we already have it saved. let me look into this a bit more @rhysviz. 

Will also set up a direct support channel for any feature requests / issues / etc. DM'ed on linkedin, let me know if another channel works better. 

Here are my details: 
LinkedIn: https://www.linkedin.com/in/krish-d/
Discord: Krrish#8748

**Comment by ghost** [comment]
ok, i'm able to repro this error locally.

**Comment by ghost** [comment]
fixed! this was previously incorrectly set

<img width="459" alt="Screenshot 2023-10-25 at 8 31 26 AM" src="https://github.com/BerriAI/litellm/assets/17561003/03bed365-216e-4799-8d89-09981ce7889f">

**Comment by ghost** [comment]
@rhysviz let me know if it works for you now. Can confirm it works for me locally. 
<img width="827" alt="Screenshot 2023-10-25 at 8 33 01 AM" src="https://github.com/BerriAI/litellm/assets/17561003/bf04df10-cb82-49d6-90aa-ac7ba2f5fd6e">

**Comment by rhysviz** [comment]
I updated to `0.12.5` and it appears to work now. Thank you!

**Comment by ghost** [comment]
@rhysviz No need to update for this, as the model list is pulled on initialization 

Glad that it worked out though!

**Comment by ghost** [comment]
Hey @rhysviz would love to understand how your using litellm. Can you chat for ~10 minutes this week? 

Attaching my calendly if that helps - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
