### ISSUE TITLE
[Bug]: Exception calling Gemini reveals API secret key in logs

### ISSUE THREAD

**Issue by psjamesh** [BerriAI/litellm#6963]
### What happened?

We received a 400 response code back from Gemini. The logs include the URL and, as Gemini has the API key as a query parameter, it is exposed in the logs.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/{PROJECT_DIR}/.venv/lib/python3.9/site-packages/litellm/main.py", line 3598, in embedding
    response = google_batch_embeddings.batch_embeddings(  # type: ignore
  File "/{PROJECT_DIR}/.venv/lib/python3.9/site-packages/litellm/llms/vertex_ai_and_google_ai_studio/gemini_embeddings/batch_embed_content_handler.py", line 113, in batch_embeddings
    response = sync_handler.post(
  File "/{PROJECT_DIR}/.venv/lib/python3.9/site-packages/litellm/llms/custom_httpx/http_handler.py", line 406, in post
    raise e
  File "/{PROJECT_DIR}/.venv/lib/python3.9/site-packages/litellm/llms/custom_httpx/http_handler.py", line 392, in post
    response.raise_for_status()
  File "/{PROJECT_DIR}/.venv/lib/python3.9/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://generativelanguage.googleapis.com/v1beta/models/text-embedding-004:batchEmbedContents?key={API_KEY_EXPOSED_HERE}}'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
```

**Comment by ghost** [comment]
can you share a minimal script to repro this?

**Comment by psjamesh** [comment]
Thanks @krrishdholakia for resolving this so quickly.

Do you know when the change will make it into the Docker image?

**Comment by ishaan-jaff** [comment]
hi @psjamesh - curious do you use LiteLLM Proxy in production or are you evaluating it ?

If yes, we'd love to hop on a call to get your feedback on how we can improve. Sharing our calendly for your convenience https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by psjamesh** [comment]
@ishaan-jaff We're just evaluating it at the moment, not actively using it in production yet.
