### ISSUE TITLE
[Bug]: ModuleNotFoundError: No module named 'mlflow'

### ISSUE THREAD

**Issue by tengerye** [BerriAI/litellm#6986]
### What happened?

I executed `poetry run pytest .` following the instruction from the README.md.

And I expect the tests pass.

### Relevant log output

```shell
The following is the output:

=========================================== test session starts ============================================
platform linux -- Python 3.12.7, pytest-7.4.4, pluggy-1.5.0
rootdir: /home/ubuntu/workspace/litellm/litellm/tests
plugins: anyio-4.5.0, mock-3.14.0
collected 2 items                                                                                          

test_mlflow.py Fs                                                                                    [100%]

================================================= FAILURES =================================================
___________________________________________ test_mlflow_logging ____________________________________________

    def test_mlflow_logging():
        litellm.success_callback = ["mlflow"]
        litellm.failure_callback = ["mlflow"]
    
>       litellm.completion(
            model="gpt-4o-mini",
            messages=[{"role": "user", "content": "what llm are u"}],
            max_tokens=10,
            temperature=0.2,
            user="test-user",
        )

test_mlflow.py:10: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../utils.py:960: in wrapper
    raise e
../utils.py:742: in wrapper
    logging_obj, kwargs = function_setup(
../utils.py:557: in function_setup
    raise e
../utils.py:366: in function_setup
    callback_class = litellm.litellm_core_utils.litellm_logging._init_custom_logger_compatible_class(  # type: ignore
../litellm_core_utils/litellm_logging.py:2319: in _init_custom_logger_compatible_class
    _mlflow_logger = MlflowLogger()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <litellm.integrations.mlflow.MlflowLogger object at 0x7b9b01be57f0>

    def __init__(self):
>       from mlflow.tracking import MlflowClient
E       ModuleNotFoundError: No module named 'mlflow'

../integrations/mlflow.py:11: ModuleNotFoundError
------------------------------------------- Captured stderr call -------------------------------------------
18:04:50 - LiteLLM:ERROR: utils.py:554 - litellm.utils.py::function_setup() - [Non-Blocking] Traceback (most recent call last):
  File "/home/ubuntu/workspace/litellm/litellm/utils.py", line 366, in function_setup
    callback_class = litellm.litellm_core_utils.litellm_logging._init_custom_logger_compatible_class(  # type: ignore
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/workspace/litellm/litellm/litellm_core_utils/litellm_logging.py", line 2319, in _init_custom_logger_compatible_class
    _mlflow_logger = MlflowLogger()
                     ^^^^^^^^^^^^^^
  File "/home/ubuntu/workspace/litellm/litellm/integrations/mlflow.py", line 11, in __init__
    from mlflow.tracking import MlflowClient
ModuleNotFoundError: No module named 'mlflow'
; args - (); kwargs - {'model': 'gpt-4o-mini', 'messages': [{'role': 'user', 'content': 'what llm are u'}], 'max_tokens': 10, 'temperature': 0.2, 'user': 'test-user', 'litellm_call_id': 'f17de539-3641-4e1d-affc-88ded1b07863'}
-------------------------------------------- Captured log call ---------------------------------------------
ERROR    LiteLLM:utils.py:554 litellm.utils.py::function_setup() - [Non-Blocking] Traceback (most recent call last):
  File "/home/ubuntu/workspace/litellm/litellm/utils.py", line 366, in function_setup
    callback_class = litellm.litellm_core_utils.litellm_logging._init_custom_logger_compatible_class(  # type: ignore
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/workspace/litellm/litellm/litellm_core_utils/litellm_logging.py", line 2319, in _init_custom_logger_compatible_class
    _mlflow_logger = MlflowLogger()
                     ^^^^^^^^^^^^^^
  File "/home/ubuntu/workspace/litellm/litellm/integrations/mlflow.py", line 11, in __init__
    from mlflow.tracking import MlflowClient
ModuleNotFoundError: No module named 'mlflow'
; args - (); kwargs - {'model': 'gpt-4o-mini', 'messages': [{'role': 'user', 'content': 'what llm are u'}], 'max_tokens': 10, 'temperature': 0.2, 'user': 'test-user', 'litellm_call_id': 'f17de539-3641-4e1d-affc-88ded1b07863'}
============================================= warnings summary =============================================
../../../../anaconda3/envs/litellm/lib/python3.12/site-packages/pydantic/_internal/_config.py:291
  /home/ubuntu/anaconda3/envs/litellm/lib/python3.12/site-packages/pydantic/_internal/_config.py:291: PydanticDeprecatedSince20: Support for class-based `config` is deprecated, use ConfigDict instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.9/migration/
    warnings.warn(DEPRECATION_MESSAGE, DeprecationWarning)

../utils.py:134
  /home/ubuntu/workspace/litellm/litellm/utils.py:134: DeprecationWarning: open_text is deprecated. Use files() instead. Refer to https://importlib-resources.readthedocs.io/en/latest/using.html#migrating-from-legacy for migration advice.
    with resources.open_text("litellm.llms.tokenizers", "anthropic_tokenizer.json") as f:

test_mlflow.py:18
  /home/ubuntu/workspace/litellm/litellm/tests/test_mlflow.py:18: PytestUnknownMarkWarning: Unknown pytest.mark.asyncio - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.asyncio()

test_mlflow.py::test_async_mlflow_logging
  /home/ubuntu/anaconda3/envs/litellm/lib/python3.12/site-packages/_pytest/python.py:183: PytestUnhandledCoroutineWarning: async def functions are not natively supported and have been skipped.
  You need to install a suitable plugin for your async framework, for example:
    - anyio
    - pytest-asyncio
    - pytest-tornasync
    - pytest-trio
    - pytest-twisted
    warnings.warn(PytestUnhandledCoroutineWarning(msg.format(nodeid)))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================= short test summary info ==========================================
FAILED test_mlflow.py::test_mlflow_logging - ModuleNotFoundError: No module named 'mlflow'
================================= 1 failed, 1 skipped, 4 warnings in 2.29s =================================
```
```


### Twitter / LinkedIn details

_No response_

**Comment by tengerye** [comment]
When I executed `poetry add mlflow`, I got the following:
```
Using version ^2.18.0 for mlflow

Updating dependencies
Resolving dependencies... (0.0s)

The current project's supported Python range (>=3.8.1,<3.9.7 || >3.9.7,<4.0) is not compatible with some of the required packages Python requirement:
  - mlflow requires Python >=3.9, so it will not be satisfied for Python >=3.8.1,<3.9

Because no versions of mlflow match >2.18.0,<3.0.0
 and mlflow (2.18.0) requires Python >=3.9, mlflow is forbidden.
So, because litellm depends on mlflow (^2.18.0), version solving failed.

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties
    
    For mlflow, a possible solution would be to set the `python` property to ">=3.9,<3.9.7 || >3.9.7,<4.0"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

However, my python version meets the requirement. When I executed `poetry run python --version`, I got the following:
```
Python 3.12.7
```

**Comment by ghost** [comment]
> The current project's supported Python range (>=3.8.1,<3.9.7 || >3.9.7,<4.0) is not compatible with some of the required packages Python requirement:
  - mlflow requires Python >=3.9, so it will not be satisfied for Python >=3.8.1,<3.9

this seems like an issue within your environment. 

Can you try pip installing mlflow and see if that fixes it?

**Comment by tengerye** [comment]
> > The current project's supported Python range (>=3.8.1,<3.9.7 || >3.9.7,<4.0) is not compatible with some of the required packages Python requirement:
> 
> * mlflow requires Python >=3.9, so it will not be satisfied for Python >=3.8.1,<3.9
> 
> this seems like an issue within your environment.
> 
> Can you try pip installing mlflow and see if that fixes it?

Thank you for your kind reply, but may I ask why please? The pip environment is different from that of poetry, I suppose.

**Comment by ghost** [comment]
Not sure. Closing the ticket as mlflow being installed separately is intended behavior
