### ISSUE TITLE
issue while running interpreter

### ISSUE THREAD

**Issue by sonti123l** [BerriAI/litellm#707]
check it because of it .i can't do anything

**Comment by sonti123l** [comment]
Provider List: https://docs.litellm.ai/docs/providers


Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 244, in completion
    model, custom_llm_provider = get_llm_provider(model=model, custom_llm_provider=custom_llm_provider)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 1350, in get_llm_provider
    raise e
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 1347, in get_llm_provider
    raise ValueError(f"LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/{model}',..)` Learn more: https://docs.litellm.ai/docs/providers")
ValueError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/gpt-4',..)` Learn more: https://docs.litellm.ai/docs/providers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 21, in cli
    cli(self)
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\cli\cli.py", line 168, in cli
    interpreter.chat()
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 66, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 87, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 62, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 95, in _streaming_chat
    yield from self._respond()
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 121, in _respond
    yield from respond(self)
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\respond.py", line 57, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\llm\convert_to_coding_llm.py", line 19, in coding_llm
    for chunk in text_llm(messages):
                 ^^^^^^^^^^^^^^^^^^
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\llm\setup_text_llm.py", line 119, in base_llm
    return litellm.completion(**params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 718, in wrapper
    raise e
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 677, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 1213, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 2851, in exception_type
    raise e
  File "C:\Users\saitr\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 2833, in exception_type
    raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/gpt-4',..)` Learn more: https://docs.litellm.ai/docs/providers

**Comment by ghost** [comment]
Hey @sonti123l this seems like a known issue on openinterpreter's github - i'd recommend checking that out: https://github.com/KillianLucas/open-interpreter
