### ISSUE TITLE
[Bug]: Pass Through reports "RuntimeError: Response content longer than Content-Length"

### ISSUE THREAD

**Issue by wy96f** [BerriAI/litellm#7108]
### What happened?

We create pass through endpoint to proxy pass to triton server. Configs like below:
Path: /v2/models/asr_ensemble/infer
Target:  http://triton/v2/models/asr_ensemble/infer

Triton server has received request and ran sucessfully. But errors occur in litellm.

### Relevant log output

```shell
2024-12-09 INFO:     10.0.247.219:44408 - "POST /v2/models/asr_ensemble/infer HTTP/1.1" 200 OK

2024-12-09 ERROR:    Exception in ASGI application

2024-12-09 Traceback (most recent call last):

2024-12-09   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 411, in run_asgi

2024-12-09     result = await app(  # type: ignore[func-returns-value]

2024-12-09              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-12-09   File "/usr/local/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__

2024-12-09     return await self.app(scope, receive, send)

2024-12-09            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

2024-12-09   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__

2024-12-09     await super().__call__(scope, receive, send)

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__

2024-12-09     await self.middleware_stack(scope, receive, send)

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__

2024-12-09     raise exc

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__

2024-12-09     await self.app(scope, receive, _send)

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/cors.py", line 85, in __call__

2024-12-09     await self.app(scope, receive, send)

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__

2024-12-09     await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app

2024-12-09     raise exc

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

2024-12-09     await app(scope,receive, sender)

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__

2024-12-09     await self.middleware_stack(scope, receive, send)

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app

2024-12-09     await route.handle(scope, receive, send)

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 297, in handle

2024-12-09     await self.app(scope, receive, send)

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 77, in app

2024-12-09     await wrap_app_handling_exceptions(app, request)(scope, receive, send)

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app

2024-12-09     raise exc

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app

2024-12-09     await app(scope, receive, sender)

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 75, in app

2024-12-09     await response(scope, receive, send)

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 159, in __call__

2024-12-09     await send({"type": prefix + "http.response.body", "body": self.body})

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 50, in sender

2024-12-09     await send(message)

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/_exception_handler.py", line 50, in sender

2024-12-09     await send(message)

2024-12-09   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 161, in _send

2024-12-09     await send(message)

2024-12-09   File "/usr/local/lib/python3.11/site-packages/uvicorn/protocols/http/httptools_impl.py", line 541, in send

2024-12-09     raise RuntimeError("Response content longer than Content-Length")

2024-12-09 RuntimeError: Response content longer than Content-Length
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.52.10

**Comment by riyajatar37003** [comment]
whats status,is it resolved
