### ISSUE TITLE
[Bug]: Langfuse callbacks no longer work with Langfuse v3

### ISSUE THREAD

**Issue by samling** [BerriAI/litellm#7128]
### What happened?

After updating to Langfuse v3, callbacks configured in both the proxy service and SDK fail with `httpx.ConnectError: [Errno -2] Name or service not known` despite verifying that the proxy or the service using the SDK can reach Langfuse.

### Relevant log output

```shell
litellm-6b795d5f77-xs2dr litellm Giving up execute_task_with_backoff(...) after 3 tries (httpx.ConnectError: [Errno -2] Name or service not known)
litellm-6b795d5f77-xs2dr litellm Giving up execute_task_with_backoff(...) after 3 tries (httpx.ConnectError: [Errno -2] Name or service not known)
litellm-6b795d5f77-xs2dr litellm Giving up execute_task_with_backoff(...) after 3 tries (httpx.ConnectError: [Errno -2] Name or service not known)
litellm-6b795d5f77-xs2dr litellm error uploading: [Errno -2] Name or service not known
litellm-6b795d5f77-xs2dr litellm Traceback (most recent call last):
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
litellm-6b795d5f77-xs2dr litellm     yield
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 233, in handle_request
litellm-6b795d5f77-xs2dr litellm     resp = self._pool.handle_request(req)
litellm-6b795d5f77-xs2dr litellm            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 256, in handle_request
litellm-6b795d5f77-xs2dr litellm     raise exc from None
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection_pool.py", line 236, in handle_request
litellm-6b795d5f77-xs2dr litellm     response = connection.handle_request(
litellm-6b795d5f77-xs2dr litellm                ^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
litellm-6b795d5f77-xs2dr litellm     raise exc
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 78, in handle_request
litellm-6b795d5f77-xs2dr litellm     stream = self._connect(request)
litellm-6b795d5f77-xs2dr litellm              ^^^^^^^^^^^^^^^^^^^^^^
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpcore/_sync/connection.py", line 124, in _connect
litellm-6b795d5f77-xs2dr litellm     stream = self._network_backend.connect_tcp(**kwargs)
litellm-6b795d5f77-xs2dr litellm              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/sync.py", line 207, in connect_tcp
litellm-6b795d5f77-xs2dr litellm     with map_exceptions(exc_map):
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
litellm-6b795d5f77-xs2dr litellm     self.gen.throw(typ, value, traceback)
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
litellm-6b795d5f77-xs2dr litellm     raise to_exc(exc) from exc
litellm-6b795d5f77-xs2dr litellm httpcore.ConnectError: [Errno -2] Name or service not known
litellm-6b795d5f77-xs2dr litellm
litellm-6b795d5f77-xs2dr litellm The above exception was the direct cause of the following exception:
litellm-6b795d5f77-xs2dr litellm
litellm-6b795d5f77-xs2dr litellm Traceback (most recent call last):
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/langfuse/task_manager.py", line 204, in upload
litellm-6b795d5f77-xs2dr litellm     self._upload_batch(batch)
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/langfuse/task_manager.py", line 244, in _upload_batch
litellm-6b795d5f77-xs2dr litellm     execute_task_with_backoff(batch)
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/backoff/_sync.py", line 105, in retry
litellm-6b795d5f77-xs2dr litellm     ret = target(*args, **kwargs)
litellm-6b795d5f77-xs2dr litellm           ^^^^^^^^^^^^^^^^^^^^^^^
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/langfuse/task_manager.py", line 242, in execute_task_with_backoff
litellm-6b795d5f77-xs2dr litellm     raise e
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/langfuse/task_manager.py", line 230, in execute_task_with_backoff
litellm-6b795d5f77-xs2dr litellm     self._client.batch_post(batch=batch, metadata=metadata)
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/langfuse/request.py", line 55, in batch_post
litellm-6b795d5f77-xs2dr litellm     res = self.post(**kwargs)
litellm-6b795d5f77-xs2dr litellm           ^^^^^^^^^^^^^^^^^^^
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/langfuse/request.py", line 67, in post
litellm-6b795d5f77-xs2dr litellm     res = self._session.post(
litellm-6b795d5f77-xs2dr litellm           ^^^^^^^^^^^^^^^^^^^
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1145, in post
litellm-6b795d5f77-xs2dr litellm     return self.request(
litellm-6b795d5f77-xs2dr litellm            ^^^^^^^^^^^^^
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 827, in request
litellm-6b795d5f77-xs2dr litellm     return self.send(request, auth=auth, follow_redirects=follow_redirects)
litellm-6b795d5f77-xs2dr litellm            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 914, in send
litellm-6b795d5f77-xs2dr litellm     response = self._send_handling_auth(
litellm-6b795d5f77-xs2dr litellm                ^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 942, in _send_handling_auth
litellm-6b795d5f77-xs2dr litellm     response = self._send_handling_redirects(
litellm-6b795d5f77-xs2dr litellm                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
litellm-6b795d5f77-xs2dr litellm     response = self._send_single_request(request)
litellm-6b795d5f77-xs2dr litellm                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1015, in _send_single_request
litellm-6b795d5f77-xs2dr litellm     response = transport.handle_request(request)
litellm-6b795d5f77-xs2dr litellm                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 232, in handle_request
litellm-6b795d5f77-xs2dr litellm     with map_httpcore_exceptions():
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__
litellm-6b795d5f77-xs2dr litellm     self.gen.throw(typ, value, traceback)
litellm-6b795d5f77-xs2dr litellm   File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
litellm-6b795d5f77-xs2dr litellm     raise mapped_exc(message) from exc
litellm-6b795d5f77-xs2dr litellm httpx.ConnectError: [Errno -2] Name or service not known
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.54.1

### Twitter / LinkedIn details

https://www.linkedin.com/in/skboynton/

**Comment by samling** [comment]
Never mind, this was a configuration error on my part, there were some conflicting environment variables set elsewhere that I'd forgotten about.
