### ISSUE TITLE
[Feature Request]: Add Fireworks' Whisper V3 

### ISSUE THREAD

**Issue by TranHung92** [BerriAI/litellm#7134]
### What happened?

I have the model configured as below
```
  - model_name: whisper-v3
    litellm_params:
      model: fireworks_ai/accounts/fireworks/models/whisper-v3
      api_base: https://api.fireworks.ai/inference/v1
      api_key: os.environ/FIREWORKS_API_KEY
    model_info:
      mode: audio_transcription
```

When making a request
```
curl --location 'http//localhost:4000/v1/audio/transcriptions' \
--header 'Authorization: Bearer sk-xxxx' \
--form 'file=@"/path/to/file"' \
--form 'model="whisper-v3"'
```

I receive the error below on the litellm server
```
09:04:22 - LiteLLM Proxy:ERROR: http_parsing_utils.py:45 - Unexpected error reading request body - Stream consumed

Traceback (most recent call last):

  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/common_utils/http_parsing_utils.py", line 26, in _read_request_body

    body = await request.body()

           ^^^^^^^^^^^^^^^^^^^^

  File "/usr/local/lib/python3.11/site-packages/starlette/requests.py", line 244, in body

    async for chunk in self.stream():

  File "/usr/local/lib/python3.11/site-packages/starlette/requests.py", line 227, in stream

    raise RuntimeError("Stream consumed")

RuntimeError: Stream consumed
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.53.5

**Comment by buildgreatthings** [comment]
I have the same issue. Groq seems to work fine, but they're more expensive, and actually slower unless turbo is used. @ishaan-jaff any chance a fix can be prioritized here? Thanks!

**Comment by ishaan-jaff** [comment]
yes - currently working on improving code quality in the repo, can add it this week @buildgreatthings

**Comment by buildgreatthings** [comment]
Hi @ishaan-jaff, thanks so much! Please let us all know when this release is out.

**Comment by TranHung92** [comment]
Hi @ishaan-jaff , is there any update on this?

**Comment by ghost** [comment]
Acknowledging this. thanks for the bump @TranHung92 

will add it today

**Comment by ghost** [comment]
Closing as this is now live
