### ISSUE TITLE
[Bug]: SDK call failure with VertexAI custom embedding model

### ISSUE THREAD

**Issue by suresiva** [BerriAI/litellm#7141]
### What happened?

LiteLLM version used: 1.52.12

We have few custom embedding model deployed on VertexAI and configured them on LiteLLM. 

```
{
  "model_name": "vertex_ai/multi-qa-minilm-l6-cos-v1-embed",
  "litellm_params": {
    "vertex_project": "**********",
    "vertex_location": "us-central1",
    "model": "vertex_ai/405896812021415936",
    "model_id": "65b623ab-658e-4010-872d-62a1bcb67155"
  },
  "model_info": {
    "id": "65b623ab-658e-4010-872d-62a1bcb67155",
    "db_model": true
  },
  "provider": "vertex_ai",
  "litellm_model_name": "vertex_ai/405896812021415936",
  "cleanedLitellmParams": {
    "vertex_project": "****************",
    "vertex_location": "us-central1",
    "model_id": "65b623ab-658e-4010-872d-62a1bcb67155"
  }
}
```

The embedding calls made to LiteLLM through HTTP/cURL are working as expected. 
```curl --location 'http://0.0.0.0:4000/embeddings' --header 'Authorization: Bearer sk-1234' --header 'Content-Type: application/json' --data '{ "input": ["good morning"] , "model": "vertex_ai/multi-qa-minilm-l6-cos-v1-sdk-1"}'```

But when we invoke the same embedding call through LiteLLM SDK, we get model not found error (404).
```
import litellm
os.environ['LITELLM_LOG'] = 'DEBUG'
response = embedding(
                model='vertex_ai/multi-qa-minilm-l6-cos-v1-sdk-1', 
                api_base= "http//0.0.0.0:4000/embeddings",
                api_key= "sk-1234",
                api_type = "vertex_ai",
                input=["good morning from litellm"]
            )
print(response)
```
The error message we get is,
```
litellm.llms.vertex_ai_and_google_ai_studio.vertex_ai_non_gemini.VertexAIError: {
  "error": {
    "code": 404,
    "message": "Publisher Model `projects/*******/locations/us-central1/publishers/google/models/multi-qa-minilm-l6-cos-v1-sdk-1` not found.",
    "status": "NOT_FOUND"
  }
}
```

We believe that the LiteLLM SDK composes the model endpoint url assuming the given custom model as a Google published and miss to create the intended custom model endpoint url. On the other side cURL command invocation works correctly and compose the custom endpoint URL correctly.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/ssiva3/Source/vscode/genai-3/litellm-trtllm-integration/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai_and_google_ai_studio/vertex_embeddings/embedding_handler.py", line 125, in embedding
    response = client.post(api_base, headers=headers, json=vertex_request)  # type: ignore
  File "/Users/ssiva3/Source/vscode/genai-3/litellm-trtllm-integration/.venv/lib/python3.10/site-packages/litellm/llms/custom_httpx/http_handler.py", line 406, in post
    raise e
  File "/Users/ssiva3/Source/vscode/genai-3/litellm-trtllm-integration/.venv/lib/python3.10/site-packages/litellm/llms/custom_httpx/http_handler.py", line 392, in post
    response.raise_for_status()
  File "/Users/ssiva3/Source/vscode/genai-3/litellm-trtllm-integration/.venv/lib/python3.10/site-packages/httpx/_models.py", line 763, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '404 Not Found' for url 'https://us-central1-aiplatform.googleapis.com/v1/projects/************/locations/us-central1/publishers/google/models/multi-qa-minilm-l6-cos-v1-sdk-1:predict'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ssiva3/Source/vscode/genai-3/litellm-trtllm-integration/.venv/lib/python3.10/site-packages/litellm/main.py", line 3658, in embedding
    response = vertex_embedding.embedding(
  File "/Users/ssiva3/Source/vscode/genai-3/litellm-trtllm-integration/.venv/lib/python3.10/site-packages/litellm/llms/vertex_ai_and_google_ai_studio/vertex_embeddings/embedding_handler.py", line 129, in embedding
    raise VertexAIError(status_code=error_code, message=err.response.text)
litellm.llms.vertex_ai_and_google_ai_studio.vertex_ai_non_gemini.VertexAIError: {
  "error": {
    "code": 404,
    "message": "Publisher Model `projects/***********/locations/us-central1/publishers/google/models/multi-qa-minilm-l6-cos-v1-sdk-1` not found.",
    "status": "NOT_FOUND"
  }
}


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ssiva3/Source/vscode/genai-3/litellm-trtllm-integration/embed_liteLLM_call_1.py", line 27, in <module>
    response = embedding(
  File "/Users/ssiva3/Source/vscode/genai-3/litellm-trtllm-integration/.venv/lib/python3.10/site-packages/litellm/utils.py", line 960, in wrapper
    raise e
  File "/Users/ssiva3/Source/vscode/genai-3/litellm-trtllm-integration/.venv/lib/python3.10/site-packages/litellm/utils.py", line 849, in wrapper
    result = original_function(*args, **kwargs)
  File "/Users/ssiva3/Source/vscode/genai-3/litellm-trtllm-integration/.venv/lib/python3.10/site-packages/litellm/main.py", line 3850, in embedding
    raise exception_type(
  File "/Users/ssiva3/Source/vscode/genai-3/litellm-trtllm-integration/.venv/lib/python3.10/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2136, in exception_type
    raise e
  File "/Users/ssiva3/Source/vscode/genai-3/litellm-trtllm-integration/.venv/lib/python3.10/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 1163, in exception_type
    raise NotFoundError(
litellm.exceptions.NotFoundError: litellm.NotFoundError: VertexAIException - {
  "error": {
    "code": 404,
    "message": "Publisher Model `projects/***********/locations/us-central1/publishers/google/models/multi-qa-minilm-l6-cos-v1-sdk-1` not found.",
    "status": "NOT_FOUND"
  }
}
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.52.12

**Comment by ishaan-jaff** [comment]
this is not a bug, you're using the litellm SDK incorrectly with the proxy 

Doc: https://docs.litellm.ai/docs/providers/litellm_proxy
You should do this 
```python
import litellm
os.environ['LITELLM_LOG'] = 'DEBUG'
response = embedding(
                model='litellm_proxy/multi-qa-minilm-l6-cos-v1-sdk-1', 
                api_base= "http//0.0.0.0:4000/embeddings",
                api_key= "sk-1234",
                input=["good morning from litellm"]
            )
print(response)
```
