### ISSUE TITLE
[Bug]: AWS Bedrock Nova error

### ISSUE THREAD

**Issue by jleatham** [BerriAI/litellm#7181]
### What happened?

LiteLLM proxy setup with a few models: 
```
Public Model Name:     amazon.nova-pro-v1:0                                Provider: bedrock_converse 
Public Model Name:     us.anthropic.claude-3-5-sonnet-20241022-v2:0        Provider: bedrock
...
```

Other models work, but Nova is not.
Error is the same with python litellm script as well as using open-webui.
Not sure why the provider is different.  I added them the sameway using the Add Model UI.

### Relevant log output

```shell
Uh-oh! There was an issue connecting to amazon.nova-pro-v1:0.
litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=amazon.nova-pro-v1:0
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
Received Model Group=amazon.nova-pro-v1:0
Available Model Group Fallbacks=None
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.54.1

**Comment by CrazyShipOne** [comment]
Try replacing model name to 'us.amazon.nova-pro-v1:0'

**Comment by jleatham** [comment]
The Amazon model (TMK) is different than Anthropic and Llama in that the modelId does not use the `us.` prefix.  I tried anyway and got the following error:
```
Uh-oh! There was an issue connecting to us.amazon.nova-pro-v1:0.
{'error': '/chat/completions: Invalid model name passed in model=us.amazon.nova-pro-v1:0. Call `/v1/models` to view available models for your key.'}
  ```

Here is the model API guidance from AWS Console:
```
{
  "modelId": "amazon.nova-pro-v1:0",
  "contentType": "application/json",
  "accept": "application/json",
  "body": {
    "inferenceConfig": {
      "max_new_tokens": 1000
    },
    "messages": [
      {
        "role": "user",
        "content": [
          {
            "text": "this is where you place your input text"
          }
        ]
      }
    ]
  }
}
```

The above was ran on litellm version 1.56.4.  I tried with the regular `amazon.nova-pro-v1:0` model and got this error from the proxy server:

```
17:41:42 - LiteLLM Proxy:ERROR: proxy_server.py:3492 - litellm.proxy.proxy_server.chat_completion(): Exception occured - litellm.BadRequestError: LLM Provider NOT provided. Pass in the LLM provider you are trying to call. You passed model=amazon.nova-pro-v1:0
 Pass model as E.g. For 'Huggingface' inference endpoints pass in `completion(model='huggingface/starcoder',..)` Learn more: https://docs.litellm.ai/docs/providers
Received Model Group=amazon.nova-pro-v1:0
Available Model Group Fallbacks=None LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/litellm/proxy/proxy_server.py", line 3381, in chat_completion
    responses = await llm_responses
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/litellm/router.py", line 833, in acompletion
    raise e
  File "/usr/local/lib/python3.13/site-packages/litellm/router.py", line 809, in acompletion
    response = await self.async_function_with_fallbacks(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/litellm/router.py", line 2803, in async_function_with_fallbacks
    raise original_exception
  File "/usr/local/lib/python3.13/site-packages/litellm/router.py", line 2619, in async_function_with_fallbacks
    response = await self.async_function_with_retries(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        *args, **kwargs, mock_timeout=mock_timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/litellm/router.py", line 2981, in async_function_with_retries
    raise original_exception
  File "/usr/local/lib/python3.13/site-packages/litellm/router.py", line 2887, in async_function_with_retries
    response = await self.make_call(original_function, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/litellm/router.py", line 2990, in make_call
    response = await response
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/litellm/router.py", line 958, in _acompletion
    raise e
  File "/usr/local/lib/python3.13/site-packages/litellm/router.py", line 926, in _acompletion
    response = await _response
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/litellm/utils.py", line 1202, in wrapper_async
    raise e
  File "/usr/local/lib/python3.13/site-packages/litellm/utils.py", line 1056, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/litellm/main.py", line 411, in acompletion
    _, custom_llm_provider, _, _ = get_llm_provider(
                                   ~~~~~~~~~~~~~~~~^
        model=model, api_base=completion_kwargs.get("base_url", None)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/litellm/litellm_core_utils/get_llm_provider_logic.py", line 353, in get_llm_provider
    raise e
  File "/usr/local/lib/python3.13/site-packages/litellm/litellm_core_utils/get_llm_provider_logic.py", line 330, in get_llm_provider
    raise litellm.exceptions.BadRequestError(  # type: ignore
    ...<8 lines>...
    )
```

**Comment by Maxch3306** [comment]
- model_name: amazon.nova-pro-v1:0
    litellm_params:
      model: bedrock/amazon.nova-pro-v1:0
      aws_access_key_id: aws_access_key_id
      aws_secret_access_key: aws_secret_access_key
    model_info:
      base_model: amazon.nova-pro-v1:0

getting "error": "litellm.BadRequestError: BedrockException - {\"message\":\"Invocation of model ID amazon.nova-pro-v1:0 with on-demand throughput isn’t supported. Retry your request with the ID or ARN of an inference profile that contains this model.\"}\nHave you set 'mode' - https://docs.litellm.ai/docs/proxy/health#embedding-models\nstack trace: Traceback (most recent call last):\n  File \"/usr/lib/python3.13/site-packages/litellm/llms/bedrock/chat/converse_handler.py\", line 165, in async_completion\n    response = await client.post(url=api_base, headers=headers, data=data)  # type: ignore\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"/usr/lib/python3.13/site-packages/litellm/llms/custom_httpx/http_handler.py\", line 219, in post\n    raise e\n  File \"/usr/lib/python3.13/site-packages/litellm/llms/custom_httpx/http_handler.py\", line 177, in post\n    response.raise_for_status()\n    ~~~~~~~~~~~~~~~~~~~~~~~~~^^\n  File \"/usr/lib/python3.13/site-packages/httpx/_models.py\", line 761, in raise_for_status\n    raise HTTPStatusError(message, request=request, response=self)\nhttpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://bedrock-runtime.us-west-2.amazonaws.com/model/amazon.nova-pro-v1:0/converse'\nFor more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400\n"

**Comment by ghost** [comment]
Hey @jleatham can you please bump to latest and let me know if your issue persists?

**Comment by Maxch3306** [comment]
> Hey @jleatham can you please bump to latest and let me know if your issue persists? 

Thanks, I find the issue fixed

**Comment by ghost** [comment]
Great, thanks @Maxch3306

**Comment by jleatham** [comment]
Working.  Appreciate it!

**Comment by ghost** [comment]
Hi @jleatham curious - are you using LiteLLM to give other developers LLM Access?

**Comment by gustavz** [comment]
@Maxch3306 I face a similar error like you, how did you solve it?

```
litellm.BadRequestError: BedrockException - {"message":"Invocation of model ID amazon.nova-pro-v1:0 with on-demand throughput isn't supported. Retry your request with the ID or ARN of an inference profile that contains this model."}. Received Model Group=bedrock/amazon.nova-pro-v1:0
```
I am on litellm `1.65.1`

Update: it can be fixed by prepending the region to the model, e.g. `bedrock/us.amazon.nova-pro-v1:0`.
Is there a chance litellm solves this, so we can just call `bedrock/amazon.nova-pro-v1:0` and litellm will prepend the right prefix depending on the provided credentials?

**Comment by ghost** [comment]
> Invocation of model ID amazon.nova-pro-v1:0 with on-demand throughput isn't supported. Retry your request with the ID or ARN of an inference profile that contains this model

Use a cross-region inferencing model name
