### ISSUE TITLE
[Bug]: Unable to use Bedrock Nova Canvas model (Image Generation Model)

### ISSUE THREAD

**Issue by MarcusRosen-Rio** [BerriAI/litellm#7190]
### What happened?

Unable to proxy requests via LiteLLM to Amazon Nova Canvas (Image Generator) model. I had disabled streaming as this is not supported by the model. The other text based Nova models are working fine.

config.yaml
```yaml
  - model_name: amazon-nova-canvas
    litellm_params:
      model: bedrock/amazon.nova-canvas-v1:0
      aws_region_name: us-east-1

````

### Relevant log output

```shell
"Malformed input request: #: required key [messages] not found, please reformat your input and try again."

Full Stack Trace:

`
01:17:58 - LiteLLM Proxy:ERROR: proxy_server.py:3487 - litellm.proxy.proxy_server.chat_completion(): Exception occured - litellm.BadRequestError: BedrockException - {"message":"Malformed input request: #: required key [messages] not found, please reformat your input and try again."}
Received Model Group=amazon-nova-canvas
Available Model Group Fallbacks=None LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/bedrock/chat/invoke_handler.py", line 982, in async_completion
    response = await client.post(api_base, headers=headers, data=data)  # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 224, in post
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/custom_httpx/http_handler.py", line 181, in post
    response.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/httpx/_models.py", line 761, in raise_for_status
    raise HTTPStatusError(message, request=request, response=self)
httpx.HTTPStatusError: Client error '400 Bad Request' for url 'https://bedrock-runtime.us-east-1.amazonaws.com/model/amazon.nova-canvas-v1:0/invoke'
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
litellm-1    |
During handling of the above exception, another exception occurred:
litellm-1    |
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 483, in acompletion
    response = await init_response
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/llms/bedrock/chat/invoke_handler.py", line 986, in async_completion
    raise BedrockError(status_code=error_code, message=err.response.text)
litellm.llms.bedrock.common_utils.BedrockError: {"message":"Malformed input request: #: required key [messages] not found, please reformat your input and try again."}
litellm-1    |
During handling of the above exception, another exception occurred:
litellm-1    |
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 3376, in chat_completion
    responses = await llm_responses
                ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 835, in acompletion
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 811, in acompletion
    response = await self.async_function_with_fallbacks(**kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2810, in async_function_with_fallbacks
    raise original_exception
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2646, in async_function_with_fallbacks
    response = await self.async_function_with_retries(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2984, in async_function_with_retries
    raise original_exception
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2894, in async_function_with_retries
    response = await self.make_call(original_function, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 2993, in make_call
    response = await response
               ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 965, in _acompletion
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 933, in _acompletion
    response = await _response
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1175, in wrapper_async
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/utils.py", line 1031, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 505, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 2137, in exception_type
    raise e
  File "/usr/local/lib/python3.11/site-packages/litellm/litellm_core_utils/exception_mapping_utils.py", line 758, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: litellm.BadRequestError: BedrockException - {"message":"Malformed input request: #: required key [messages] not found, please reformat your input and try again."}
Received Model Group=amazon-nova-canvas
Available Model Group Fallbacks=None LiteLLM Retried: 1 times, LiteLLM Max Retries: 2
01:17:58 - LiteLLM Proxy:ERROR: _common.py:120 - Giving up chat_completion(...) after 1 tries (litellm.proxy._types.ProxyException)
INFO:     172.18.0.5:58940 - "POST /v1/chat/completions HTTP/1.1" 400 Bad Request
````
```


### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.53.5

### Twitter / LinkedIn details

_No response_

**Comment by omrishiv** [comment]
Can you try #7838 please? I have gotten responses with it using that PR
