### ISSUE TITLE
[Bug]: Taking too long to call fallback

### ISSUE THREAD

**Issue by DanielAmorimAraujo** [BerriAI/litellm#7303]
### What happened?

When calling the `completion` method from the Python library with a specified timeout, the call sometimes takes **over a minute** and then throws an exception `exception litellm.Timeout: APITimeoutError - Request timed out.`, despite the specified timeout being 20 seconds. Ideally, it would terminate the first call once the specified timeout lapses and move to the fallback.

```
try:
    response = completion(
        messages=[
            {'role': message.role, 'content': message.content}
            for message in messages
        ],
        model='gpt-4o',
        fallbacks=['claude-3-sonnet-20240229'],
        num_retries=0,
        timeout=20,
        temperature=0,
        top_p=1,
        model_list=[
            { 'model_name': 'gpt-4o', 'litellm_params': { 'model': 'gpt-4o', 'api_key': '...' } },
            { 'model_name': 'claude-3-sonnet-20240229', 'litellm_params': { 'model': 'claude-3-sonnet-20240229', 'api_key': '...' } }
        ],
    )
except Exception as e:
    logger.error(f'LiteLLM call failed; exception {str(e)}')
    return {}
```

Additionally, a second exception is also thrown: `exception 'NoneType' object has no attribute '_response_ms'`

### Relevant log output

```shell
LiteLLM call failed; exception litellm.Timeout: APITimeoutError - Request timed out. 
error_str: Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/connection.py", line 101, in handle_request
    return self._connection.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 143, in handle_request
    raise exc
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 113, in handle_request
    ) = self._receive_response_headers(**kwargs)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 186, in _receive_response_headers
    event = self._receive_event(timeout=timeout)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_sync/http11.py", line 224, in _receive_event
    data = self._network_stream.read(
  File "/usr/local/lib/python3.9/site-packages/httpcore/_backends/sync.py", line 126, in read
    return self._sock.recv(max_bytes)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 952, in _request
    response = self._client.send(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 914, in send
    response = self._send_handling_auth(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 942, in _send_handling_auth
    response = self._send_handling_redirects(
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 979, in _send_handling_redirects
    response = self._send_single_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_client.py", line 1015, in _send_single_request
    response = transport.handle_request(request)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/litellm/llms/openai.py", line 1026, in completion
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/llms/openai.py", line 944, in completion
    self.make_sync_openai_chat_completion_request(
  File "/usr/local/lib/python3.9/site-packages/litellm/llms/openai.py", line 809, in make_sync_openai_chat_completion_request
    raise e
  File "/usr/local/lib/python3.9/site-packages/litellm/llms/openai.py", line 804, in make_sync_openai_chat_completion_request
    response = openai_client.chat.completions.create(
  File "/usr/local/lib/python3.9/site-packages/openai/_utils/_utils.py", line 277, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/openai/resources/chat/completions.py", line 590, in create
    return self._post(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1240, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 921, in request
    return self._request(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 961, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1053, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 961, in _request
    return self._retry_request(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 1053, in _retry_request
    return self._request(
  File "/usr/local/lib/python3.9/site-packages/openai/_base_client.py", line 971, in _request
    raise APITimeoutError(request=request) from err
openai.APITimeoutError: Request timed out.
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

v1.55.0

**Comment by ghost** [comment]
> File "/usr/local/lib/python3.9/site-packages/litellm/llms/openai.py", line 804, in make_sync_openai_chat_completion_request
    response = openai_client.chat.completions.create(

@DanielAmorimAraujo i don't think this is a later version of litellm. 

Since v1.48.18 we've been using `openai_client.chat.completions.with_raw_response.create` for making the openai call

i can also see in our code, that we do pass the timeout given 

https://github.com/BerriAI/litellm/blob/c7f14e936a59586b0b4fe215dfea03650ad9b0cf/litellm/llms/openai/openai.py#L378

i suspect you're on an older version of litellm (not the v1.55.0, but pre: 1.48.18). 

try testing this in a venv or colab instance and see if that works

**Comment by ghost** [comment]
Closing for now as this seems to be a version issue. Please reopen/bump me if you see this in a clean env 

if so, feel free to share the google colab for easier repro. Happy to look into this
