### ISSUE TITLE
[Bug]: Errors in LiteLLM When Using Embeddings Model with Usage-Based Routing

### ISSUE THREAD

**Issue by afrozsh19** [BerriAI/litellm#7308]
### Summary
Encountering issues when using routing_strategy as `usage-based-routing` or `usage-based-routing-v2` along with embedding models in the model list.

### Environment Details:
- Kubernetes: 1.28.15
- LiteLLM Tag: v1.55.2
- Redis: opstree/redis: v7.0.15

### Deployment Details
Using helm charts for the deployment with Redis for cache database. 

Below are the configurations in config.yaml:
```
litellm_settings:
  cache: true
  cache_params:
    host: os.environ/REDIS_HOST
    password: os.environ/REDIS_PASSWORD
    port: os.environ/REDIS_PORT
    type: redis
  callbacks:
  - otel
  forward_traceparent_to_llm_provider: false
  set_verbose: false
model_list:
- litellm_params:
    api_base: <Azure API BASE>
    api_key: os.environ/AZURE_01_KEY
    model: azure/gpt_35_turbo
    rpm: 1440
    tpm: 240000
    base_model: azure/gpt-35-turbo-0613
- litellm_params:
    api_base: <Azure API BASE>
    api_key: os.environ/AZURE_01_KEY
    api_version: "2024-10-21"
    model: azure/gpt_4_turbo
    base_model: azure/gpt-4-0125-preview
    rpm: 480
    tpm: 80000
  model_info:
    mode: chat
  model_name: gpt_4_turbo
- litellm_params:
    api_key: os.environ/GEMINI_01_KEY
    model: gemini/*
  model_info:
    mode: chat
  model_name: gemini/*
- litellm_params:
    api_base: <Azure API BASE>
    api_key: os.environ/AZURE_02_KEY
    api_version: "2024-10-21"
    model: azure/gpt_35_turbo
    base_model: azure/gpt-35-turbo-0613
    rpm: 1800
    tpm: 300000
  model_info:
    mode: chat
  model_name: gpt_35_turbo
- litellm_params:
    api_base: <Azure API BASE>
    api_key: os.environ/AZURE_01_KEY
    api_version: "2024-10-21"
    model: azure/text_embedding_ada_002
    base_model: azure/text-embedding-ada-002
  model_name: text_embedding_ada_002
- litellm_params:
    api_base: <Azure API BASE>
    api_key: os.environ/AZURE_01_KEY
    api_version: "2024-10-21"
    model: azure/text_embedding_3_large
    base_model: azure/text-embedding-3-large
  model_name: text_embedding_3_large
- litellm_params:
    api_base: <Azure API BASE>
    api_key: os.environ/AZURE_01_KEY
    model: azure/text_embedding_ada_002
    base_model: azure/text-embedding-ada-002
  model_info:
    mode: embedding
  model_name: text_embedding_ada_002
router_settings:
  enable_pre_call_checks: true
  redis_host: os.environ/REDIS_HOST
  redis_password: os.environ/REDIS_PASSWORD
  redis_port: os.environ/REDIS_PORT
  retry_policy:
    AuthenticationErrorRetries: 3
    ContentPolicyViolationErrorRetries: 4
    InternalServerErrorRetries: 4
    RateLimitErrorRetries: 3
    TimeoutErrorRetries: 3
  routing_strategy: usage-based-routing-v2
```

### Relevant log output

```shell
## When an embeddings model is added to the model_list, the following errors occur on the console:
09:48:08 - LiteLLM Router:ERROR: lowest_tpm_rpm.py:153 - litellm.router_strategy.lowest_tpm_rpm.py::async_log_success_event(): Exception occured - 'NoneType' object has no attribute 'get'
09:48:08 - LiteLLM Router:DEBUG: lowest_tpm_rpm.py:158 - Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/router_strategy/lowest_tpm_rpm.py", line 109, in async_log_success_event
    id = kwargs["litellm_params"].get("model_info", {}).get("id", None)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'



## On calling an embeddings endpoint, additional errors are observed:
10:25:50 - LiteLLM:ERROR: opentelemetry.py:640 - OpenTelemetry logging error in set_attributes 'str' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/integrations/opentelemetry.py", line 531, in set_attributes
    if response_obj and response_obj.get("id"):
                        ^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'

10:25:50 - LiteLLM Router:ERROR: lowest_tpm_rpm.py:153 - litellm.router_strategy.lowest_tpm_rpm.py::async_log_success_event(): Exception occured - string indices must be integers, not 'str'
10:25:50 - LiteLLM Router:DEBUG: lowest_tpm_rpm.py:158 - Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/router_strategy/lowest_tpm_rpm.py", line 115, in async_log_success_event
    total_tokens = response_obj["usage"]["total_tokens"]
                   ~~~~~~~~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.55.2

**Comment by ishaan-jaff** [comment]
picking this up today

**Comment by ishaan-jaff** [comment]
hi @afrozsh19  can you share the stacktrace / error you see with `usage-based-routing-v2` ? 

Your stacktrace you shared above is from `usage-based-routing`

**Comment by afrozsh19** [comment]
Hi @ishaan-jaff - It's a similar error on `usage-based-routing-v2`.

Error on container startup:
```
19:08:11 - LiteLLM:ERROR: lowest_tpm_rpm_v2.py:317 - litellm.proxy.hooks.prompt_injection_detection.py::async_pre_call_hook(): Exception occured - 'NoneType' object has no attribute 'get'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/litellm/router_strategy/lowest_tpm_rpm_v2.py", line 283, in async_log_success_event
    id = kwargs["litellm_params"].get("model_info", {}).get("id", None)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by ishaan-jaff** [comment]
what embedding model were you calling @afrozsh19 ? Unable to repro the stack trace

**Comment by ishaan-jaff** [comment]
fixes for this added here @afrozsh19 https://github.com/BerriAI/litellm/pull/7390

@afrozsh19 can we hop on a call to confirm this is resolved + get your feedback on LiteLLM ? 

Sharing a link to my calendly for your convenience: https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat
