### ISSUE TITLE
[Bug]: Invalid double await in ollama embeddings in Proxy (fix in report)

### ISSUE THREAD

**Issue by aguadoenzo** [BerriAI/litellm#7366]
### What happened?

Using OpenAI sdk, LiteLLM proxy. When creating embeddings using Ollama `nomic-embed-text`, the proxy throws the following error.
```
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 3070, in aembedding
litellm-1  |     response = await init_response  # type: ignore
litellm-1  |                ^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/ollama/completion/handler.py", line 77, in ollama_aembeddings
litellm-1  |     response_json = await response.json()
litellm-1  |                     ^^^^^^^^^^^^^^^^^^^^^
litellm-1  | TypeError: object dict can't be used in 'await' expression
```

This issue comes from here, the `response` object is already awaited before, so there's no need for a second `await`.
https://github.com/BerriAI/litellm/blob/8b1ea40e7b651a4fdc302d8b6e9f00c13b43d0af/litellm/llms/ollama/completion/handler.py#L55

The following change fixes the issue (tested locally):
```python
response_json = response.json() 
```

I'm submitting an issue and not a PR because I'm not familiar enough with the code base and the impact this change might have. Also I can't really write tests for a PR

### Relevant log output

```shell
litellm-1  | Traceback (most recent call last):
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/main.py", line 3070, in aembedding
litellm-1  |     response = await init_response  # type: ignore
litellm-1  |                ^^^^^^^^^^^^^^^^^^^
litellm-1  |   File "/usr/local/lib/python3.11/site-packages/litellm/llms/ollama/completion/handler.py", line 77, in ollama_aembeddings
litellm-1  |     response_json = await response.json()
litellm-1  |                     ^^^^^^^^^^^^^^^^^^^^^
litellm-1  | TypeError: object dict can't be used in 'await' expression
```

### Are you a ML Ops Team?

No

### What LiteLLM version are you on ?

ghcr.io/berriai/litellm:main-latest which at time of writing would be v1.55.8-stable

**Comment by datGryphon** [comment]
I also experienced this bug on 1.55.9

**Comment by hermanmak** [comment]
Also experiencing this issue 

Obsidian copilot -> OpenWebui's Openai Proxy Endpoint -> LiteLLM Ollama Proxy -> Ollama snowflake-arctic-embed2

litellm       |   File "/usr/local/lib/python3.13/site-packages/litellm/llms/ollama/completion/handler.py", line 55, in ollama_aembeddings
litellm       |     response_json = await response.json()
litellm       |                     ^^^^^^^^^^^^^^^^^^^^^
litellm       | TypeError: object dict can't be used in 'await' expression

**Comment by papipsycho** [comment]
i having the same issue with the version 1.56.4

**Comment by papipsycho** [comment]
So i just made a quick fix on my local version 


```
import inspect


if inspect.iscoroutinefunction(response) == False:
    response_json = response.json()
else:
    response_json = await response.json()
```

but is not really a good practice 
should check deeper into litellm.module_level_aclient.post to understand if is AsyncClient or Client

**Comment by aguadoenzo** [comment]
Seems to be fixed in 833bf1da2220df4585937ea9201bd608300c52db
Tested in v1.59.8 and it works fine
