### ISSUE TITLE
Error loading ASGI app. Could not import module "proxy_server".

### ISSUE THREAD

**Issue by DebajitKumarPhukan** [BerriAI/litellm#738]
### What happened?

**Problem**
I tried out the below code using hugging face `mistralai/Mistral-7B-Instruct-v0.1` model and as per my observation, I see the interactions but there is no final output to it. I halts automatically without any error. Have you guys tried out the below code yourself which you have documented ?.

```
from autogen import AssistantAgent, UserProxyAgent, oai
config_list=[
    {
        "model": "my-fake-model",
        "api_base": "http://0.0.0.0:8000",  #litellm compatible endpoint
        "api_type": "open_ai",
        "api_key": "NULL", # just a placeholder
    }
]

response = oai.Completion.create(config_list=config_list, prompt="Hi")
print(response) # works fine

llm_config={
    "config_list": config_list,
}

assistant = AssistantAgent("assistant", llm_config=llm_config)
user_proxy = UserProxyAgent("user_proxy")
user_proxy.initiate_chat(assistant, message="Plot a chart of META and TESLA stock price change YTD.", config_list=config_list)
```

### Relevant log output

```shell
## Output Logs ##

user_proxy (to assistant):

Plot a chart of META and TESLA stock price change YTD.

--------------------------------------------------------------------------------
assistant (to user_proxy):

 To plot a chart of META and TESLA stock price change YTD, you can

--------------------------------------------------------------------------------
Provide feedback to assistant. Press enter to skip and use auto-reply, or type 'exit' to end the conversation:  

>>>>>>>> NO HUMAN INPUT RECEIVED.

>>>>>>>> USING AUTO REPLY...
user_proxy (to assistant):



--------------------------------------------------------------------------------
assistant (to user_proxy):

 To plot a chart of META and TESLA stock price change YTD, you can

--------------------------------------------------------------------------------
Provide feedback to assistant. Press enter to skip and use auto-reply, or type 'exit' to end the conversation:  use any python library of your choice
user_proxy (to assistant):

use any python library of your choice

--------------------------------------------------------------------------------
assistant (to user_proxy):

 To plot a chart of META and TESLA stock price change YTD, you can

--------------------------------------------------------------------------------
Provide feedback to assistant. Press enter to skip and use auto-reply, or type 'exit' to end the conversation:  use Matplotlib python library
user_proxy (to assistant):

use Matplotlib python library

--------------------------------------------------------------------------------
assistant (to user_proxy):

 To plot a chart of META and TESLA stock price change YTD using Matplot

--------------------------------------------------------------------------------
Provide feedback to assistant. Press enter to skip and use auto-reply, or type 'exit' to end the conversation:  auto-reply
user_proxy (to assistant):

auto-reply

--------------------------------------------------------------------------------
assistant (to user_proxy):

 To plot a chart of META and TESLA stock price change YTD using Matplot

--------------------------------------------------------------------------------
Provide feedback to assistant. Press enter to skip and use auto-reply, or type 'exit' to end the conversation:  auto-reply
user_proxy (to assistant):

auto-reply

--------------------------------------------------------------------------------
[autogen.oai.completion: 11-01 07:33:18] {238} INFO - retrying in 10 seconds...
Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/openai/api_requestor.py", line 413, in handle_error_response
    error_data = resp["error"]
TypeError: string indices must be integers

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.10/site-packages/autogen/oai/completion.py", line 222, in _get_response
    response = openai_completion.create(**config)
  File "/opt/conda/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "/opt/conda/lib/python3.10/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/opt/conda/lib/python3.10/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/opt/conda/lib/python3.10/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
  File "/opt/conda/lib/python3.10/site-packages/openai/api_requestor.py", line 415, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: 'Internal Server Error' (HTTP response code was 500)
```

**Comment by DebajitKumarPhukan** [comment]
Probably this is the reason -> `https://github.com/microsoft/autogen/pull/95` ?

**Comment by ghost** [comment]
Hey @DebajitKumarPhukan, there seems to be an internal server error - you should check the logs of your proxy server (on the terminal you spun it up in). 

I'm closing the issue as it's not clear how this is a bug. Please re-open once you've identified the issue.

**Comment by DebajitKumarPhukan** [comment]
@krrishdholakia There are intermittent issues in LIteLLM. Below is a sample log snippet for your reference:

```
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new

Docs: https://docs.litellm.ai/docs/proxy_server

LiteLLM: Test your local endpoint with: "litellm --test" [In a new terminal tab]

LiteLLM: View available endpoints for this server on: http://0.0.0.0:8000

LiteLLM: Self-host your proxy using the following: https://docs.litellm.ai/docs/proxy_server#deploy-proxy 

ERROR:    Error loading ASGI app. Could not import module "proxy_server".
```

**Comment by ghost** [comment]
thanks for raising this @DebajitKumarPhukan  - fixing now.

**Comment by ghost** [comment]
fix pushed in v`0.13.1`. Should be live in the next 10-15 minutes. Thanks for this catch @DebajitKumarPhukan

**Comment by ishaan-jaff** [comment]
Hi @DebajitKumarPhukan did you use the proxy server only with mistral ? 

(i'm the co -maintainer of LiteLLM)

**Comment by MikeBirdTech** [comment]
I'm experiencing this error when trying to have litellm run the `command-nightly` model from Cohere. I'm on litellm version `0.14.1`

`litellm --model command-nightly`

`ERROR:    Error loading ASGI app. Could not import module "proxy_server".`

Any advice? Thanks!
cc: @krrishdholakia @ishaan-jaff

**Comment by ishaan-jaff** [comment]
hi @Arrendy taking a look at this - sorry for the issue

**Comment by ishaan-jaff** [comment]
i was able to run this on 14.1
<img width="783" alt="Screenshot 2023-11-12 at 9 53 05 AM" src="https://github.com/BerriAI/litellm/assets/29436595/fba1ce9e-9113-414f-84c4-73fc95146d87">

**Comment by ishaan-jaff** [comment]
@Arrendy another option here is you can git clone https://github.com/BerriAI/litellm

**Comment by ishaan-jaff** [comment]
cd into this dir: https://github.com/BerriAI/litellm/tree/main/litellm/proxy 

`cd litellm/litellm/proxy`
`python3 proxy_cli.py --local --model command-nightly`


let me know if that works?
