### ISSUE TITLE
[Bug]: run locally without internet connection

### ISSUE THREAD

**Issue by ttio2tech** [BerriAI/litellm#739]
### What happened?

I was trying to run litellm with WIFI turned off for a local model, but it wasn't able to run with failure connecting to openai server? Is it expected?

**Comment by ghost** [comment]
@ttio2tech please attach code for repro and the stacktrace.

**Comment by ttio2tech** [comment]
code: import statement gave error. 
from litellm import completion


Traceback (most recent call last):
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/urllib3/util/connection.py", line 60, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/socket.py", line 955, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -3] Temporary failure in name resolution

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 791, in urlopen
    response = self._make_request(
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 492, in _make_request
    raise new_e
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 468, in _make_request
    self._validate_conn(conn)
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1097, in _validate_conn
    conn.connect()
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/urllib3/connection.py", line 611, in connect
    self.sock = sock = self._new_conn()
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/urllib3/connection.py", line 210, in _new_conn
    raise NameResolutionError(self.host, self, e) from e
urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPSConnection object at 0x7f2ad2526f80>: Failed to resolve 'openaipublic.blob.core.windows.net' ([Errno -3] Temporary failure in name resolution)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/urllib3/connectionpool.py", line 845, in urlopen
    retries = retries.increment(
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f2ad2526f80>: Failed to resolve 'openaipublic.blob.core.windows.net' ([Errno -3] Temporary failure in name resolution)"))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/litellm/__init__.py", line 314, in <module>
    from .utils import (
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/litellm/utils.py", line 27, in <module>
    encoding = tiktoken.get_encoding("cl100k_base")
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/tiktoken/registry.py", line 73, in get_encoding
    enc = Encoding(**constructor())
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/tiktoken_ext/openai_public.py", line 64, in cl100k_base
    mergeable_ranks = load_tiktoken_bpe(
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/tiktoken/load.py", line 116, in load_tiktoken_bpe
    contents = read_file_cached(tiktoken_bpe_file)
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/tiktoken/load.py", line 48, in read_file_cached
    contents = read_file(blobpath)
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/tiktoken/load.py", line 24, in read_file
    resp = requests.get(blobpath)
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/home/ti/miniconda3/envs/py310torch2nvda/lib/python3.10/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='openaipublic.blob.core.windows.net', port=443): Max retries exceeded with url: /encodings/cl100k_base.tiktoken (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x7f2ad2526f80>: Failed to resolve 'openaipublic.blob.core.windows.net' ([Errno -3] Temporary failure in name resolution)"))

**Comment by sudhamjayanthi** [comment]
I get the same error: 

`encoding = tiktoken.get_encoding("cl100k_base")` is the line causing error. it's ultimately trying to make a request to [openaipublic.blob.core.windows.net](openaipublic.blob.core.windows.net)

**Comment by ghost** [comment]
what's the suggested fix here? token encoding is pretty important for ensuring standardized usage responses. We have a cached version for anthropic, is cl100k_base available?

**Comment by sudhamjayanthi** [comment]
i'm afraid. i'm not sure i understand the under the hood workings of litellm yet, just wanted to provide context that might be useful

**Comment by ttio2tech** [comment]
> what's the suggested fix here? token encoding is pretty important for ensuring standardized usage responses. We have a cached version for anthropic, is cl100k_base available? 

Can I suggest to use cache? Similar to huggingface model. Download to local and can be used in future.

**Comment by shessenauer** [comment]
Does it need to be the cl100k encoding? Other encoding options can be pip-installed and do not require external network access to use. Fixing this would greatly increase the usability for litellm in private/offline environments which is a major compelling use case for a lot of organizations right now.

**Comment by Manouchehri** [comment]
LiteLLM should probably run CI/CD tests in a container without a network connection.

I'm assuming DARPA's AIxCC infrastructure is gonna be firewalled off heavily, and I really don't want to tempt DARPA to maintain an out-of-date fork with patches. 😅
