### ISSUE TITLE
[Bug]: Errors with LiteLLM and ollama (Fresh Install)

### ISSUE THREAD

**Issue by georgeliamcampbell** [BerriAI/litellm#7465]
### What happened?

I have installed a fresh instance of the LiteLLM docker container as I have done previously (had a test instance running a few weeks ago working). I was presented with a 500 error on initial login related to NoneType. I configured my ollama model as I had in the test instance and when attempting to test the model I am presented with "Error occurred while generating model response. Please try again. Error: Error: All connection attempts failed". I have provided the stack trace below. 

Please advise as I need to integrate with our internal NextCloud instance.

### Relevant log output

```shell
Error occurred while generating model response. Please try again. Error: Error: All connection attempts failed Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions yield File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 373, in handle_async_request resp = await self._pool.handle_async_request(req) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 256, in handle_async_request raise exc from None File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 236, in handle_async_request response = await connection.handle_async_request( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request raise exc File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 78, in handle_async_request stream = await self._connect(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 124, in _connect stream = await self._network_backend.connect_tcp(**kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/auto.py", line 31, in connect_tcp return await self._backend.connect_tcp( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpcore/_backends/anyio.py", line 113, in connect_tcp with map_exceptions(exc_map): File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__ self.gen.throw(typ, value, traceback) File "/usr/local/lib/python3.11/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions raise to_exc(exc) from exc httpcore.ConnectError: All connection attempts failed The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/usr/local/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 2672, in async_data_generator async for chunk in response: File "/usr/local/lib/python3.11/site-packages/litellm/llms/ollama/completion/handler.py", line 314, in ollama_async_streaming raise e # don't use verbose_logger.exception, if exception is raised ^^^^^^^ File "/usr/local/lib/python3.11/site-packages/litellm/llms/ollama/completion/handler.py", line 251, in ollama_async_streaming async with client.stream( File "/usr/local/lib/python3.11/contextlib.py", line 210, in __aenter__ return await anext(self.gen) ^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1617, in stream response = await self.send( ^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1661, in send response = await self._send_handling_auth( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1689, in _send_handling_auth response = await self._send_handling_redirects( ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects response = await self._send_single_request(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1763, in _send_single_request response = await transport.handle_async_request(request) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 372, in handle_async_request with map_httpcore_exceptions(): File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__ self.gen.throw(typ, value, traceback) File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions raise mapped_exc(message) from exc httpx.ConnectError: All connection attempts failed
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.56.4

**Comment by georgeliamcampbell** [comment]
Resolved: Internal networking issue resolved by DevOps team

**Comment by luanpo1234** [comment]
> Resolved: Internal networking issue resolved by DevOps team

I have a very similar problem. I created a proxy using the Docker image in `ghcr.io/berriai/litellm-database:main-latest`, I'm running the container, and when I try to connect with CURL or llama_index, I get

```{"error":{"message":"litellm.APIConnectionError: OllamaException - All connection attempts failed\nReceived Model Group=proxy-test\nAvailable Model Group Fallbacks=None","type":null,"param":null,"code":"500"}}
```.

The traceback of the exception is the same as the one you posted above. Could you tell me how you solved this? Or point me in the right direction? The Ollama endpoint is working fine otherwise.
