### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by Gageperrin** [BerriAI/litellm#7486]
### What happened?

Router strategy `usage-based-routing-v2` fails to successfully log embedding event.

This seems to be due to a Type Error here - https://github.com/BerriAI/litellm/blob/main/litellm/router_strategy/lowest_tpm_rpm_v2.py#L237

This could potentially be resolved with a pattern like:
```
if isinstance(response_obj, str):
    total_tokens = standard_logging_object.get("total_tokens", 0)
else:
    total_tokens = response_obj.get("usage", {}).get("total_tokens", 0)
```

### Relevant log output

```shell
19:54:39 - LiteLLM:ERROR: dual_cache.py:264 - LiteLLM Cache: Excepton async add_cache: coroutine ignored GeneratorExit
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/litellm/caching/dual_cache.py", line 260, in async_batch_set_cache
await self.redis_cache.async_set_cache_pipeline(
RuntimeError: coroutine ignored GeneratorExit
Task was destroyed but it is pending!
task: <Task pending name='Task-33656' coro=<Logging.async_success_handler() done, defined at /usr/local/lib/python3.11/site-packages/litellm/litellm_core_utils/litellm_logging.py:1445> wait_for=<Future pending cb=[Task.task_wakeup()]>>
19:54:39 - LiteLLM Router:ERROR: router.py:3342 - litellm.router.Router::deployment_callback_on_success(): Exception occured - 'str' object has no attribute 'get'
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 3312, in deployment_callback_on_success
_usage_obj = completion_response.get("usage")
^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
19:54:39 - LiteLLM:ERROR: lowest_tpm_rpm_v2.py:314 - litellm.proxy.hooks.prompt_injection_detection.py::async_pre_call_hook(): Exception occured - string indices must be integers, not 'str'
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/litellm/router_strategy/lowest_tpm_rpm_v2.py", line 289, in async_log_success_event
total_tokens = response_obj["usage"]["total_tokens"]
~~~~~~~~~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'
INFO: 10.224.0.33:51838 - "POST /openai/deployments/embedding-primary/embeddings?api-version=2024-05-01-preview HTTP/1.1" 200 OK
19:54:39 - LiteLLM Router:ERROR: router.py:3342 - litellm.router.Router::deployment_callback_on_success(): Exception occured - 'str' object has no attribute 'get'
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/litellm/router.py", line 3312, in deployment_callback_on_success
_usage_obj = completion_response.get("usage")
^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
```

### Are you a ML Ops Team?

Yes

### What LiteLLM version are you on ?

v1.50.2

**Comment by superpoussin22** [comment]
Perhaps you should edit and add a title :-)

**Comment by ghost** [comment]
This code is outdated. Please bump to latest. I can see that this works 

1. Client-side request w/ token usage 

<img width="1007" alt="Screenshot 2025-01-01 at 4 19 18 PM" src="https://github.com/user-attachments/assets/cfba6860-c661-42c4-a49b-a2bb4baf377b" />

2. print statement inside usage-based routing v2 to show total tokens being tracked
<img width="1090" alt="Screenshot 2025-01-01 at 4 19 35 PM" src="https://github.com/user-attachments/assets/2ef92d77-fc9b-4333-bcbe-e51a3dbdab43" />

3. console logs with correct output 
<img width="1235" alt="Screenshot 2025-01-01 at 4 19 26 PM" src="https://github.com/user-attachments/assets/50dc8651-a803-4578-a473-11bfb714c3c6" />

**Comment by ghost** [comment]
Happy to hop on a call and help debug if you still see issues @Gageperrin 

Attaching my calendar here, for convenience - https://calendly.com/d/4mp-gd3-k5k/litellm-1-1-onboarding-chat

**Comment by Gageperrin** [comment]
Hey thanks for the quick follow up. Wanted to close loop on this, looks like we're good on this. (Added that missing title.)
