### ISSUE TITLE
[Bug]: petals fail

### ISSUE THREAD

**Issue by CodeAKrome** [BerriAI/litellm#753]
### What happened?

Hey ;) Show me what I'm doing wrong , please.

Expected: 0 exit code
Got: 1

```sh
pip install git+https://github.com/bigscience-workshop/petals
cat > sam_petals.py
```
```python
from litellm import completion

response = completion(
    model="petals/petals-team/StableBeluga2", 
    messages=[{ "content": "Hello, how are you?","role": "user"}]
)

print(response)
```
```sh
python ./sam_petals.py
```
```
Nov 02 23:57:50.411 [INFO] Route found: 0:26 via …j7T7Bt => 26:52 via …GRRyKw => 52:80 via …2mj7xE
```
```
Traceback (most recent call last):
  File "/home/kyle/src/github/open-interpreter/.venv/lib/python3.11/site-packages/litellm/main.py", line 1107, in completion
    model_response = petals.completion(
                     ^^^^^^^^^^^^^^^^^^
  File "/home/kyle/src/github/open-interpreter/.venv/lib/python3.11/site-packages/litellm/llms/petals.py", line 155, in completion
    outputs = model_obj.generate(inputs, **optional_params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyle/src/github/open-interpreter/.venv/lib/python3.11/site-packages/petals/client/remote_generation.py", line 116, in generate
    result = super().generate(inputs, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyle/src/github/open-interpreter/.venv/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyle/src/github/open-interpreter/.venv/lib/python3.11/site-packages/transformers/generation/utils.py", line 1673, in generate
    return self.greedy_search(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/kyle/src/github/open-interpreter/.venv/lib/python3.11/site-packages/transformers/generation/utils.py", line 2518, in greedy_search
    model_inputs = self.prepare_inputs_for_generation(input_ids, **model_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyle/src/github/open-interpreter/.venv/lib/python3.11/site-packages/petals/client/remote_generation.py", line 37, in prepare_inputs_for_generation
    return super().prepare_inputs_for_generation(input_ids, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kyle/src/github/open-interpreter/.venv/lib/python3.11/site-packages/transformers/models/llama/modeling_llama.py", line 1084, in prepare_inputs_for_generation
    past_length = past_key_values[0][0].shape[2]
                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: tuple index out of range
```

**Comment by ghost** [comment]
Hey @CodeAKrome investigated this further. When I run this same query by calling the petals infra endpoint, it works: 

```python
import litellm
from litellm import completion
response = completion(
    model="petals/petals-team/StableBeluga2", 
    messages=[{ "content": "Hello, how are you?","role": "user"}],
    api_base="https://chat.petals.dev/api/v1/generate"
)

print(response)
```

**Comment by ghost** [comment]
Yet, when I run the same query via petals' quick start - i hit the same error as the one you mentioned: 
```python
from transformers import AutoTokenizer
from petals import AutoDistributedModelForCausalLM

# Choose any model available at https://health.petals.dev
model_name = "petals-team/StableBeluga2"  # This one is fine-tuned Llama 2 (70B)

# Connect to a distributed network hosting model layers
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoDistributedModelForCausalLM.from_pretrained(model_name)

# Run the model as if it were on your computer
inputs = tokenizer("A cat sat", return_tensors="pt")["input_ids"]
outputs = model.generate(inputs, max_new_tokens=5)
print(tokenizer.decode(outputs[0]))  # A cat sat on a mat...
```
<img width="1062" alt="Screenshot 2023-11-05 at 9 08 51 PM" src="https://github.com/BerriAI/litellm/assets/17561003/6c5a3eb5-7edf-4132-9a1e-2c7dabc1c648">

This doesn't look like a litellm issue but a petals one. I'd recommend filing an issue here - https://github.com/bigscience-workshop/petals

**Comment by ghost** [comment]
Closing for now. Please re-open if you discover otherwise @CodeAKrome
