### ISSUE TITLE
[Bug]: When using Anyscale models, unwanted print happens

### ISSUE THREAD

**Issue by sebderhy** [BerriAI/litellm#754]
### What happened?

Code to replicate: 

```
response = completion(
    model = 'anyscale/mistralai/Mistral-7B-Instruct-v0.1', 
    messages = [{ "content": "Hello, how are you?","role": "user"}],
    stream=True
)
for chunk in response:
  print(chunk["choices"][0]["delta"].get("content", ""), end="")
```

Print:
```
delta content: {'role': 'assistant'}
completion obj content: 
completion obj content: 
delta content: {'content': ' Hello'}
completion obj content:  Hello
 Hello
completion obj content: 
delta content: {'content': '!'}
completion obj content: !
!
completion obj content: 
delta content: {'content': ' I'}
completion obj content:  I
 I
completion obj content: 
delta content: {'content': "'"}
completion obj content: '
'
completion obj content: 
delta content: {'content': 'm'}
completion obj content: m
m
completion obj content: 
delta content: {'content': ' an'}
completion obj content:  an
 an
completion obj content: 
delta content: {'content': ' AI'}
completion obj content:  AI
 AI
completion obj content: 
delta content: {'content': ' language'}
completion obj content:  language
 language
completion obj content: 
delta content: {'content': ' model'}
completion obj content:  model
 model
completion obj content: 
delta content: {'content': ' here'}
completion obj content:  here
 here
completion obj content: 
delta content: {'content': ' to'}
completion obj content:  to
 to
completion obj content: 
delta content: {'content': ' assist'}
completion obj content:  assist
 assist
completion obj content: 
delta content: {'content': ' you'}
completion obj content:  you
 you
completion obj content: 
delta content: {'content': ' with'}
completion obj content:  with
 with
completion obj content: 
delta content: {'content': ' any'}
completion obj content:  any
 any
completion obj content: 
delta content: {'content': ' questions'}
completion obj content:  questions
 questions
completion obj content: 
delta content: {'content': ' or'}
completion obj content:  or
 or
completion obj content: 
delta content: {'content': ' concerns'}
completion obj content:  concerns
 concerns
completion obj content: 
delta content: {'content': ' you'}
completion obj content:  you
 you
completion obj content: 
delta content: {'content': ' may'}
completion obj content:  may
 may
completion obj content: 
delta content: {'content': ' have'}
completion obj content:  have
 have
completion obj content: 
delta content: {'content': '.'}
completion obj content: .
.
completion obj content: 
delta content: {'content': ' I'}
completion obj content:  I
 I
completion obj content: 
delta content: {'content': "'"}
completion obj content: '
'
completion obj content: 
delta content: {'content': 'm'}
completion obj content: m
m
completion obj content: 
delta content: {'content': ' program'}
completion obj content:  program
 program
completion obj content: 
delta content: {'content': 'med'}
completion obj content: med
med
completion obj content: 
delta content: {'content': ' to'}
completion obj content:  to
 to
completion obj content: 
delta content: {'content': ' respond'}
completion obj content:  respond
 respond
completion obj content: 
delta content: {'content': ' with'}
completion obj content:  with
 with
completion obj content: 
delta content: {'content': ' care'}
completion obj content:  care
 care
completion obj content: 
delta content: {'content': ','}
completion obj content: ,
,
completion obj content: 
delta content: {'content': ' respect'}
completion obj content:  respect
 respect
completion obj content: 
delta content: {'content': ','}
completion obj content: ,
,
completion obj content: 
delta content: {'content': ' and'}
completion obj content:  and
 and
completion obj content: 
delta content: {'content': ' truth'}
completion obj content:  truth
 truth
completion obj content: 
delta content: {'content': ','}
completion obj content: ,
,
completion obj content: 
delta content: {'content': ' and'}
completion obj content:  and
 and
completion obj content: 
delta content: {'content': ' always'}
completion obj content:  always
 always
completion obj content: 
delta content: {'content': ' promote'}
completion obj content:  promote
 promote
completion obj content: 
delta content: {'content': ' fair'}
completion obj content:  fair
 fair
completion obj content: 
delta content: {'content': 'ness'}
completion obj content: ness
ness
completion obj content: 
delta content: {'content': ' and'}
completion obj content:  and
 and
completion obj content: 
delta content: {'content': ' posit'}
completion obj content:  posit
 posit
completion obj content: 
delta content: {'content': 'ivity'}
completion obj content: ivity
ivity
completion obj content: 
delta content: {'content': ' in'}
completion obj content:  in
 in
completion obj content: 
delta content: {'content': ' my'}
completion obj content:  my
 my
completion obj content: 
delta content: {'content': ' responses'}
completion obj content:  responses
 responses
completion obj content: 
delta content: {'content': '.'}
completion obj content: .
.
completion obj content: 
delta content: {'content': ' Is'}
completion obj content:  Is
 Is
completion obj content: 
delta content: {'content': ' there'}
completion obj content:  there
 there
completion obj content: 
delta content: {'content': ' anything'}
completion obj content:  anything
 anything
completion obj content: 
delta content: {'content': ' specific'}
completion obj content:  specific
 specific
completion obj content: 
delta content: {'content': ' you'}
completion obj content:  you
 you
completion obj content: 
delta content: {'content': "'"}
completion obj content: '
'
completion obj content: 
delta content: {'content': 'd'}
completion obj content: d
d
completion obj content: 
delta content: {'content': ' like'}
completion obj content:  like
 like
completion obj content: 
delta content: {'content': ' to'}
completion obj content:  to
 to
completion obj content: 
delta content: {'content': ' discuss'}
completion obj content:  discuss
 discuss
completion obj content: 
delta content: {'content': ' today'}
completion obj content:  today
 today
completion obj content: 
delta content: {'content': '?'}
completion obj content: ?
?
completion obj content: 
delta content: {'content': ''}
completion obj content: 
completion obj content: 
delta content: {}
completion obj content: 

completion obj content: 
```

In contrast, when using Openai LLMs such as "gpt-3.5-turbo", things work smoothly. I get the answer `Hello! As an AI language model, I don't have feelings, but I'm here and ready to assist you. How can I help you today?`

**Comment by ghost** [comment]
Looks like we have some errant print statements. Will clean up and update ticket.

**Comment by ishaan-jaff** [comment]
fixed: https://github.com/BerriAI/litellm/commit/539bdae3648f13f8e66ff6c69a330132533b89c4

**Comment by ghost** [comment]
@ishaan-jaff can we close this then?

**Comment by ishaan-jaff** [comment]
lets wait for a re deploy and for @sebderhy to confirm this works

**Comment by ishaan-jaff** [comment]
the latest version 0.12.12 should have the fix @sebderhy - lmk if this works for you

**Comment by sebderhy** [comment]
Hi, I tried the new version, and while it does stream OK at the beginning, it throws an error at the end: 

```
 Hello! I'm here to help with information, guidance, and support. How can I help you today?
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Traceback (most recent call last):
  File "/home/sebderhy/mambaforge/envs/kipod/lib/python3.11/site-packages/litellm/utils.py", line 3725, in handle_custom_openai_chat_completion_chunk
    data_json = json.loads(str_line[5:])
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sebderhy/mambaforge/envs/kipod/lib/python3.11/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sebderhy/mambaforge/envs/kipod/lib/python3.11/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sebderhy/mambaforge/envs/kipod/lib/python3.11/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 3 (char 2)
Traceback (most recent call last):
  File "/home/sebderhy/mambaforge/envs/kipod/lib/python3.11/site-packages/litellm/utils.py", line 3955, in __next__
    completion_obj["content"] = response_obj["text"]
                                ~~~~~~~~~~~~^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
File ~/mambaforge/envs/kipod/lib/python3.11/site-packages/litellm/utils.py:3955, in CustomStreamWrapper.__next__(self)
   3954 response_obj = self.handle_custom_openai_chat_completion_chunk(chunk)
-> 3955 completion_obj["content"] = response_obj["text"]
   3956 print_verbose(f"completion obj content: {completion_obj['content']}")

TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

APIError                                  Traceback (most recent call last)
Cell In[21], line 6
      1 response = completion(
      2     model = 'anyscale/mistralai/Mistral-7B-Instruct-v0.1', 
      3     messages = [{ "content": "Hello, how are you?","role": "user"}],
      4     stream=True
      5 )
----> 6 for chunk in response:
      7     print(chunk["choices"][0]["delta"].get("content", ""), end="")

File ~/mambaforge/envs/kipod/lib/python3.11/site-packages/litellm/utils.py:3987, in CustomStreamWrapper.__next__(self)
   3985  # LOG FAILURE - handle streaming failure logging in the _next_ object, remove `handle_failure` once it's deprecated
   3986 threading.Thread(target=self.logging_obj.failure_handler, args=(e, traceback_exception)).start()
-> 3987 return exception_type(model=self.model, custom_llm_provider=self.custom_llm_provider, original_exception=e)

File ~/mambaforge/envs/kipod/lib/python3.11/site-packages/litellm/utils.py:3453, in exception_type(model, original_exception, custom_llm_provider, completion_kwargs)
   3451 # don't let an error with mapping interrupt the user from receiving an error from the llm api calls
   3452 if exception_mapping_worked:
-> 3453     raise e
   3454 else:
   3455     raise original_exception

File ~/mambaforge/envs/kipod/lib/python3.11/site-packages/litellm/utils.py:3435, in exception_type(model, original_exception, custom_llm_provider, completion_kwargs)
   3429         raise InvalidRequestError(
   3430             message=f"OpenAIException: This can happen due to missing AZURE_API_VERSION: {str(original_exception)}",
   3431             model=model, 
   3432             llm_provider=custom_llm_provider
   3433         )
   3434     else:
-> 3435         raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
   3436 except Exception as e:
   3437     # LOGGING
   3438     exception_logging(
   3439         logger_fn=user_logger_fn,
   3440         additional_args={
   (...)
   3444         exception=e,
   3445     )

APIError: 'NoneType' object is not subscriptable
```

**Comment by sebderhy** [comment]
Actually, now that I think about it, it's possible that this error was also there previously.

**Comment by ishaan-jaff** [comment]
looking into this - will repro on my side and see what's going on

**Comment by ishaan-jaff** [comment]
@sebderhy thanks for raising this - it looks like anyscale returns a special [DONE] char for their mistral stream which was raising an exception

pushed a fix here: https://github.com/BerriAI/litellm/commit/56ba58b35bda7c2ff7e161bdd4a95edd3fb3137c 

it was working locally for me with streaming

**Comment by ghost** [comment]
@sebderhy Re: print statements, 

we've also just pushed commits cleaning up all existing print statements + adding pre-commit and flake8 in our ci/cd pipelines to prevent future regressions - https://github.com/BerriAI/litellm/commit/6b40546e59f9dc9747ba886002fe06f34f5fe3cf

Please let me know if you have suggestions for how we can further improve.

**Comment by ghost** [comment]
Resolved from v`0.13.0` onwards.

**Comment by ghost** [comment]
Closing as this should be fixed. @sebderhy please re-open if the issue persists.

**Comment by sebderhy** [comment]
Thanks problem solved indeed :).
