### ISSUE TITLE
[Bug]: Litellm isnt working with ollama

### ISSUE THREAD

**Issue by chethankumar** [BerriAI/litellm#755]
### What happened?

I am trying to run litellm with ollama

I have started litellm using the command

`litellm --model ollama/codellama`

Then, in another terminal I ran 

`litellm --test`

And it crashes.

### Relevant log output

```shell
litellm
 --test

#------------------------------------------------------------#
#                                                            #
#       'This feature doesn't meet my needs because...'       #
#        https://github.com/BerriAI/litellm/issues/new        #
#                                                            #
#------------------------------------------------------------#

 Thank you for using LiteLLM! - Krrish & Ishaan



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new

Docs: https://docs.litellm.ai/docs/proxy_server

LiteLLM: Making a test ChatCompletions request to your proxy
http://0.0.0.0:8000
Traceback (most recent call last):
  File "<projectpath>/.venv/lib/python3.11/site-packages/openai/api_requestor.py", line 413, in handle_error_response
    error_data = resp["error"]
                 ~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<projectpath>/.venv/bin/litellm", line 8, in <module>
    sys.exit(run_server())
             ^^^^^^^^^^^^
  File "<projectpath>/.venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<projectpath>/.venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "<projectpath>/.venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<projectpath>/.venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<projectpath>/.venv/lib/python3.11/site-packages/litellm/proxy/proxy_cli.py", line 178, in run_server
    response = openai.ChatCompletion.create(model="gpt-3.5-turbo", messages = [
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<projectpath>/.venv/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<projectpath>/.venv/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "<projectpath>/.venv/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<projectpath>/.venv/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "<projectpath>/.venv/lib/python3.11/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<projectpath>/.venv/lib/python3.11/site-packages/openai/api_requestor.py", line 415, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: 'Internal Server Error' (HTTP response code was 500)
```

**Comment by ghost** [comment]
@chethankumar please check your terminal with `litellm --model ollama/..` 

It looks like that server had an error (probably caused by ollama). I'm closing this issue for now as this doesn't seem to be a litellm-specific bug, please reopen if you see otherwise on your server.

**Comment by chethankumar** [comment]
@krrishdholakia I see the below output for the command you suggested. It doesnt report any errors there.
```
litellm --model ollama/..                               

#------------------------------------------------------------#
#                                                            #
#            'This product would be better if...'             #
#        https://github.com/BerriAI/litellm/issues/new        #
#                                                            #
#------------------------------------------------------------#

 Thank you for using LiteLLM! - Krrish & Ishaan



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new

Docs: https://docs.litellm.ai/docs/proxy_server

ollama called
LiteLLM: Test your local endpoint with: "litellm --test" [In a new terminal tab]

LiteLLM: View available endpoints for this server on: http://0.0.0.0:8000

LiteLLM: Self-host your proxy using the following: https://docs.litellm.ai/docs/proxy_server#deploy-proxy 

INFO:     Started server process [38313]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
```

**Comment by ghost** [comment]
@chethankumar `litellm --model ollama/..` was stubbed. Please run the actual command you shared - `litellm --model ollama/codellama`. Run `litellm --test` and see what your terminal running ollama prints out.

**Comment by ishaan-jaff** [comment]
Hi @chethankumar did this issue get resolved ? 

I can hop on a call and help resolve this 1:1
sharing my cal for your convenience: https://calendly.com/ishaan-berri/30min?month=2023-11
