### ISSUE TITLE
text-davinci bug

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#76]
```
model call details: {'model': 'text-davinci-003', 'additional_args': {'error_str': 'list indices must be integers or slices, not str', 'exception_type': 'TypeError', 'original_exception': TypeError('list indices must be integers or slices, not str')}}
model call details: {'exception': TypeError('list indices must be integers or slices, not str'), 'additional_args': {'exception_mapping_worked': False, 'original_exception': TypeError('list indices must be integers or slices, not str')}}
{'model': 'text-davinci-003', 'prompt': "Hey, how's it going?", 'azure': False}
Traceback (most recent call last):
  File "main.py", line 41, in api_completion
    response = completion(model=model, messages=messages, deployment_id=deployment_id, azure=azure, logger_fn=logger_fn)
  File "/usr/local/lib/python3.8/site-packages/litellm/utils.py", line 131, in wrapper
    raise e
  File "/usr/local/lib/python3.8/site-packages/litellm/utils.py", line 120, in wrapper
    result = original_function(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/litellm/timeout.py", line 44, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/litellm/timeout.py", line 35, in async_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/litellm/main.py", line 314, in completion
    raise exception_type(model=model, original_exception=e)
  File "/usr/local/lib/python3.8/site-packages/litellm/utils.py", line 480, in exception_type
    raise original_exception
  File "/usr/local/lib/python3.8/site-packages/litellm/utils.py", line 471, in exception_type
    raise original_exception # base case - return the original exception
  File "/usr/local/lib/python3.8/site-packages/litellm/main.py", line 143, in completion
    completion_response = response["choices"]["text"]
TypeError: list indices must be integers or slices, not str
```

**Comment by ishaan-jaff** [comment]
fixed
