### ISSUE TITLE
[Bug]: 'CustomStreamWrapper' object has no attribute '_hidden_params'

### ISSUE THREAD

**Issue by Nikita-Sherstnev** [BerriAI/litellm#782]
### What happened?

I am running litellm with following command:
`litellm --model ollama/phind-codellama:34b-v2-q6_K --debug --drop_params`
and expect to get async stream response. But I get error 'CustomStreamWrapper' object has no attribute '_hidden_params'.

### Relevant log output

```shell
'optional_params': {'num_predict': 256, 'stream': True, 'temperature': 0.1, 'top_p': 1, 'repeat_penalty': 0.5}, 'litellm_params': {'return_async': False, 'api_key': None, 'force_timeout': 600, 'logger_fn': None, 'verbose': False, 'custom_llm_provider': 'ollama', 'api_base': None, 'litellm_call_id': '446fd53f-ba91-48ca-89f1-dd6b5f17acf4', 'model_alias_map': {}, 'completion_call_id': None, 'metadata': None, 'stream_response': {}}, 'start_time': datetime.datetime(2023, 11, 8, 17, 39, 59, 774200), 'input': None, 'api_key': None, 'additional_args': {}, 'log_event_type': 'post_api_call', 'original_response': "<class 'generator'>"}

Logging Details Post-API Call: logger_fn - None | callable(logger_fn) - False
LiteLLM non blocking exception: 'CustomStreamWrapper' object has no attribute '_hidden_params'
```

**Comment by ishaan-jaff** [comment]
hi @Nikita-Sherstnev taking a look at this

**Comment by ishaan-jaff** [comment]
@Nikita-Sherstnev are you calling ChatCompletion or Completion ?

**Comment by Nikita-Sherstnev** [comment]
@ishaan-jaff I call it with openai through langchain, request itself:
`INFO:     94.189.160.205:0 - "POST /completions HTTP/1.1" 200 OK`

**Comment by ishaan-jaff** [comment]
im finding it hard to repro your error, can you send me the langchain call ? 

Why not use our langchain integration - ChatLiteLLM https://docs.litellm.ai/docs/langchain/

**Comment by Nikita-Sherstnev** [comment]
Here is my client side traceback:

```
Traceback (most recent call last):
  File "/home/sher/Dev/Enfint/chat-bot/colllector/main.py", line 49, in <module>
    asyncio.run(streaming_main())
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/main.py", line 44, in streaming_main
    await ft
  File "/home/sher/Dev/Enfint/chat-bot/colllector/runloop.py", line 49, in arun_chat
    answer = await stm.arun("Hello")
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/statemachine.py", line 116, in arun
    return self._initial_run(input_string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/statemachine.py", line 50, in _initial_run
    answer = self.direct_state_run(input_string, self.current_state_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/statemachine.py", line 45, in direct_state_run
    answer = next_state_chain.conversation_step({"input": input_string,
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/factories/states.py", line 89, in conversation_step
    answer = self.conversation_chain.run(inputs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 505, in run
    return self(args[0], callbacks=callbacks, tags=tags, metadata=metadata)[
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 310, in __call__
    raise e
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/langchain/chains/base.py", line 304, in __call__
    self._call(inputs, run_manager=run_manager)
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/langchain/chains/llm.py", line 93, in _call
    response = self.generate([inputs], run_manager=run_manager)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/langchain/chains/llm.py", line 103, in generate
    return self.llm.generate_prompt(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/langchain/llms/base.py", line 497, in generate_prompt
    return self.generate(prompt_strings, stop=stop, callbacks=callbacks, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/langchain/llms/base.py", line 646, in generate
    output = self._generate_helper(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/langchain/llms/base.py", line 534, in _generate_helper
    raise e
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/langchain/llms/base.py", line 521, in _generate_helper
    self._generate(
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/langchain/llms/openai.py", line 383, in _generate
    for chunk in self._stream(_prompts[0], stop, run_manager, **kwargs):
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/langchain/llms/openai.py", line 308, in _stream
    for stream_resp in completion_with_retry(
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/langchain/llms/openai.py", line 115, in completion_with_retry
    return _completion_with_retry(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 289, in wrapped_f
    return self(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 379, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 314, in iter
    return fut.result()
           ^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/tenacity/__init__.py", line 382, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/langchain/llms/openai.py", line 113, in _completion_with_retry
    return llm.client.create(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/openai/api_resources/completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sher/Dev/Enfint/chat-bot/colllector/venv/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 167, in create
    assert not isinstance(response, OpenAIResponse)
AssertionError
```


I tried ChatLiteLLM, it gives me error NotImplementedError: SentenceStreamingHandler does not implement `on_chat_model_start`

UPD:
I am using method langchain.llms.openai.completion_with_retry.

**Comment by ishaan-jaff** [comment]
@Nikita-Sherstnev does `litellm -test` work for you ?

**Comment by ishaan-jaff** [comment]
I can repro your problem when I make a Completion() request with streaming, ChatCompletion with streaming works fine 

```
response = openai.Completion.create(model="gpt-3.5-turbo", prompt='this is a test request, write a short poem', stream=True)
```

@Nikita-Sherstnev can you verify langhcain is calling openai.Completion.create on your side ?

**Comment by Nikita-Sherstnev** [comment]
@ishaan-jaff `litellm -test` works for me. Looks like it calls openai.Completion.create:

```
def completion_with_retry(
    llm: Union[BaseOpenAI, OpenAIChat],
    run_manager: Optional[CallbackManagerForLLMRun] = None,
    **kwargs: Any,
) -> Any:
    """Use tenacity to retry the completion call."""
    retry_decorator = _create_retry_decorator(llm, run_manager=run_manager)

    @retry_decorator
    def _completion_with_retry(**kwargs: Any) -> Any:
        return llm.client.create(**kwargs)

    return _completion_with_retry(**kwargs)
```

llm.client is apparently an openai.Completion.

**Comment by ishaan-jaff** [comment]
sounds good i can repro the issue - will push a fix from my side

**Comment by ishaan-jaff** [comment]
@Nikita-Sherstnev pushed a fix for this: https://github.com/BerriAI/litellm/commit/2a751c277fc3c325c4ce505c0f6a70f15be9973e 

feel free to pull the latest changes from github and try 


our ci/cd pipeline is having some issues will lyk once the latest version of litellm is deployed

**Comment by Nikita-Sherstnev** [comment]
I tried this fix and it worked! Thanks!
But another problem of similar fashion has raised. This async function returns None:

```
async def acompletion_with_retry(
    llm: Union[BaseOpenAI, OpenAIChat],
    run_manager: Optional[AsyncCallbackManagerForLLMRun] = None,
    **kwargs: Any,
) -> Any:
    """Use tenacity to retry the async completion call."""
    retry_decorator = _create_retry_decorator(llm, run_manager=run_manager)

    @retry_decorator
    async def _completion_with_retry(**kwargs: Any) -> Any:
        # Use OpenAI's async api https://github.com/openai/openai-python#async-api
        return await llm.client.acreate(**kwargs)

    return await _completion_with_retry(**kwargs)
```

**Comment by ishaan-jaff** [comment]
ooooffff sorry about that - it looks it's calling an async text_completion which i believe we don't support as yet. Going to add this now

**Comment by ishaan-jaff** [comment]
@Nikita-Sherstnev looks like it works fine for me:

I'm running it with this code here:

```python
import openai

openai.api_base = "http://0.0.0.0:8000"
openai.api_key = "temp-key"
print(openai.api_base)

async def test_async_completion():
    response = await openai.Completion.acreate(
        model="gpt-3.5-turbo", 
        prompt='this is a test request, write a short poem',
    )
    print(response)

    print("test_streaming")
    response = await openai.Completion.acreate(
        model="gpt-3.5-turbo", 
        prompt='this is a test request, write a short poem',
        stream=True
    )
    print(response)
    async for chunk in response:
        print(chunk)


import asyncio
asyncio.run(test_async_completion())
```

**Comment by ishaan-jaff** [comment]
can you confirm it's calling `openai.Completion.acreate`

**Comment by Nikita-Sherstnev** [comment]
@ishaan-jaff It's calling either openai.Completion.acreate or openai.ChatCompletion.acreate, I'm not sure. Can you try with ChatCompletion, please?
Also maybe problem is that LangChain not handling stream response properly.
Here is the method from LangChain that I am using. `await acompletion_with_retry` returns None.

```
async def _agenerate(
        self,
        prompts: List[str],
        stop: Optional[List[str]] = None,
        run_manager: Optional[AsyncCallbackManagerForLLMRun] = None,
        **kwargs: Any,
    ) -> LLMResult:
        """Call out to OpenAI's endpoint async with k unique prompts."""
        params = self._invocation_params
        params = {**params, **kwargs}
        sub_prompts = self.get_sub_prompts(params, prompts, stop)
        choices = []
        token_usage: Dict[str, int] = {}
        # Get the token usage from the response.
        # Includes prompt, completion, and total tokens used.
        _keys = {"completion_tokens", "prompt_tokens", "total_tokens"}
        for _prompts in sub_prompts:
            if self.streaming:
                if len(_prompts) > 1:
                    raise ValueError("Cannot stream results with multiple prompts.")

                generation: Optional[GenerationChunk] = None
                async for chunk in self._astream(
                    _prompts[0], stop, run_manager, **kwargs
                ):
                    if generation is None:
                        generation = chunk
                    else:
                        generation += chunk
                assert generation is not None
                choices.append(
                    {
                        "text": generation.text,
                        "finish_reason": generation.generation_info.get("finish_reason")
                        if generation.generation_info
                        else None,
                        "logprobs": generation.generation_info.get("logprobs")
                        if generation.generation_info
                        else None,
                    }
                )
            else:
                response = await acompletion_with_retry(
                    self, prompt=_prompts, run_manager=run_manager, **params
                )
                choices.extend(response["choices"])
                update_token_usage(_keys, response, token_usage)
        return self.create_llm_result(choices, prompts, token_usage)
```

**Comment by ishaan-jaff** [comment]
closing this is resolved - heard from @Nikita-Sherstnev on DMs
