### ISSUE TITLE
[Bug]: Replicate timeout errors / cold boot errors not mapped 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#784]
### What happened?

Try this :
```python
    litellm.set_verbose=True
    model_name = "replicate/vicuna-13b:6282abe6a492de4145d7bb601023762212f9ddbbe78278bd6771c8b3b2f2a13b"
    try:
        response = completion(
            model=model_name, 
            messages=messages, 
            temperature=0.5,
            top_k=20,
            repetition_penalty=1,
            min_tokens=1,
            seed=-1,
            max_tokens=20,
        )
```

it looks like replicate just has a long cold boot time for some llms and we don't map the error correctly, our users thought litellm never made the call for replicate. 

- we should probably check if we ever get a chunk back for replicate within the first 20s else we should timeout

### Relevant log output

```shell
with verbose on logs look like this:



https://api.replicate.com/v1/predictions/flcbcxbb2skbascs3n6iu4yp7e
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
making request
```
```


### Twitter / LinkedIn details

_No response_

**Comment by ishaan-jaff** [comment]
after using our replicate integration more - exception mapping needs to be handled way better. Try sending `seed=4` - we don't map the exception at all

**Comment by ishaan-jaff** [comment]
improved:

```
Failed: Error occurred: ReplicateException - Error: Seed must be between 0 and 2**32 - 1,
Replicate logs:Your formatted prompt is:
[INST] Write a short poem about the sky [/INST]
Disabling loras
No loras were ever loaded, nothing to disable.
Not using LoRA
Setting seed to -1
Traceback (most recent call last):
File "/root/.pyenv/versions/3.11.5/lib/python3.11/site-packages/cog/server/worker.py", line 222, in _predict
for r in result:
File "/src/predict.py", line 200, in predict
numpy.random.seed(seed)
File "mtrand.pyx", line 4789, in numpy.random.mtrand.seed
File "mtrand.pyx", line 250, in numpy.random.mtrand.RandomState.seed
File "_mt19937.pyx", line 166, in numpy.random._mt19937.MT19937._legacy_seeding
File "_mt19937.pyx", line 180, in numpy.random._mt19937.MT19937._legacy_seeding
ValueError: Seed must be between 0 and 2**32 - 1
```

**Comment by ishaan-jaff** [comment]
done
