### ISSUE TITLE
[Feature]: Support for LATEST OpenAI package (version: 1.2.3)

### ISSUE THREAD

**Issue by solyarisoftware** [BerriAI/litellm#799]
### The Feature

Hi 
it could be great if liteLLM woul support latest Openai Python module

```
$ pip show openai
Name: openai
Version: 1.2.3
Summary: The official Python library for the openai API
Home-page:
Author:
Author-email: OpenAI <support@openai.com>
License:
Location: /home/giorgio/.local/lib/python3.11/site-packages
Requires: anyio, distro, httpx, pydantic, tqdm, typing-extensions
Required-by: litellm, llama-index
```

Otherwhise LiteLLM can't be used:

```
$ py completion.py
Traceback (most recent call last):
  File "/home/giorgio/gpt/litellm/completion.py", line 5, in <module>
    from litellm import completion
  File "/home/giorgio/.local/lib/python3.11/site-packages/litellm/__init__.py", line 332, in <module>
    from .timeout import timeout
  File "/home/giorgio/.local/lib/python3.11/site-packages/litellm/timeout.py", line 20, in <module>
    from openai.error import Timeout
ModuleNotFoundError: No module named 'openai.error'
```

where the script is just:  

```python
$ cat completion.py
# !pip install litellm openai
# https://docs.litellm.ai/docs/tutorials/azure_openai
# https://docs.litellm.ai/docs/tutorials/text_completion

from litellm import completion
#from litellm import model_cost

user_message_content = "Hello, how are you?"


response = completion(
    model="azure/***********",
    messages=[{"content": user_message_content, "role": "user"}]
)

print(user_message_content)
print("Azure response")
print(response)
print(response["choices"][0]["message"]["content"])
```

---

BTW all run smoothly with previous stable OpenAI version: 

```
$ pip show openai
Name: openai
Version: 0.28.1
Summary: Python client library for the OpenAI API
Home-page: https://github.com/openai/openai-python
Author: OpenAI
Author-email: support@openai.com
License:
Location: /home/giorgio/.local/lib/python3.11/site-packages
Requires: aiohttp, requests, tqdm
Required-by: litellm, llama-index
```
```
$ py completion.py
Hello, how are you?
Azure response
{
  "object": "chat.completion",
  "choices": [
    {
      "finish_reason": "stop",
      "index": 0,
      "message": {
        "content": "As an AI language model, I do not have feelings, but I'm functioning properly. How can I assist you today?",
        "role": "assistant"
      }
    }
  ],
  "id": "chatcmpl-*****************************",
  "created": 1699789391,
  "model": "*********",
  "usage": {
    "prompt_tokens": 14,
    "completion_tokens": 25,
    "total_tokens": 39
  }
}
As an AI language model, I do not have feelings, but I'm functioning properly. How can I assist you today?
```

I guess this issue is related to: https://github.com/BerriAI/litellm/issues/774

Thanks
Giorgio

### Motivation, pitch

- I would use latest OpenAI package features (exception handling, etc.)
- I want to enable latest llamaindex version too: 
  ```
  ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behavior is the 
  source of the following dependency conflicts.
  llama-index 0.8.67 requires openai>=1.1.0, but you have openai 0.28.1 which is incompatible.
  ```

### Twitter / LinkedIn details

twitter: @solyarisoftare linkedin: www.linkedin.com/in/giorgiorobino

**Comment by EsoCoding** [comment]
Ah So its not just me, i'm already stuck for 24 hours, thought i had usual python dependency issues. Even changed from pipenv to poetry, but same error. Anyone knows a fast way to fix it? Look like openai changed lots.

**Comment by ishaan-jaff** [comment]
Hi @EsoCoding so sorry for the issues - we have a dev release of litellm here https://pypi.org/project/litellm/1.0.0.dev1/ 

this should be openai 1.0.0+ compatible

**Comment by ishaan-jaff** [comment]
cc @solyarisoftware

**Comment by ishaan-jaff** [comment]
we're actively working on this and you can track this here: https://github.com/BerriAI/litellm/issues/774 

ETA on full migration is Monday Nov 13 EOD

**Comment by ishaan-jaff** [comment]
this is done @solyarisoftware
