### ISSUE TITLE
[Bug]: EmbeddingResponse Failing

### ISSUE THREAD

**Issue by canada4663** [BerriAI/litellm#800]
### What happened?

When running tests associated with #765, getting failures when running embedding test functions, specifically:

```
During handling of the above exception, another exception occurred:

    def test_openai_embedding():
        try:
            response = embedding(
                model="text-embedding-ada-002", input=["good morning from litellm", "this is another item"]
            )
            print(response)
            # Add any assertions here to check the response
            # print(f"response: {str(response)}")
        except Exception as e:
>           pytest.fail(f"Error occurred: {e}")
E           Failed: Error occurred: 'EmbeddingResponse' object has no attribute '__pydantic_extra__'
```

To fix this, I add `super` method into EmbeddingResponse:

```
class EmbeddingResponse(OpenAIObject):
    def __init__(self, id=None, choices=None, created=None, model=None, usage=None, stream=False, response_ms=None, **params):
        super(EmbeddingResponse, self).__init__(**params)
        self.object = "list"
        if response_ms:
            self._response_ms = response_ms
        else:
            self._response_ms = None
        self.data = []
        self.model = model
```

This results in Pydantic failures as below:

```
During handling of the above exception, another exception occurred:

    def test_openai_embedding():
        try:
            response = embedding(
                model="text-embedding-ada-002", input=["good morning from litellm", "this is another item"]
            )
            print(response)
            # Add any assertions here to check the response
            # print(f"response: {str(response)}")
        except Exception as e:
>           pytest.fail(f"Error occurred: {e}")
E           Failed: Error occurred: Traceback (most recent call last):
E             File "/Users/x/litellm/litellm/llms/openai.py", line 357, in embedding
E               model_response["object"] = "list"
E               ~~~~~~~~~~~~~~^^^^^^^^^^
E           TypeError: 'EmbeddingResponse' object does not support item assignment
```

I am using the following dependency versions; I started with the contents of poetry.lock and things were not working properly so upgraded openai, etc:

```
aiohttp==3.8.6
aiosignal==1.3.1
annotated-types==0.6.0
anthropic==0.6.0
anyio==3.7.1
appdirs==1.4.4
async-timeout==4.0.3
attrs==23.1.0
backoff==2.2.1
baseten==0.8.1
blake3==0.3.3
boto3==1.28.84
botocore==1.31.84
cachetools==5.3.2
certifi==2023.7.22
charset-normalizer==3.3.2
click==8.1.7
cloudpickle==2.2.1
cohere==4.34
colorama==0.4.6
coolname==2.2.0
distro==1.8.0
fastapi==0.95.2
fastavro==1.8.2
filelock==3.13.1
frozenlist==1.4.0
fsspec==2023.10.0
google-api-core==2.14.0
google-auth==2.23.4
google-cloud-core==2.3.3
google-cloud-storage==2.10.0
google-crc32c==1.5.0
google-resumable-media==2.6.0
googleapis-common-protos==1.61.0
gptcache==0.1.42
h11==0.14.0
halo==0.0.31
httpcore==0.17.3
httpx==0.24.1
huggingface-hub==0.16.4
idna==3.4
importlib-metadata==6.8.0
iniconfig==2.0.0
inquirerpy==0.3.4
Jinja2==3.1.2
jmespath==1.0.1
joblib==1.3.2
log-symbols==0.0.14
markdown-it-py==3.0.0
MarkupSafe==2.1.3
mdurl==0.1.2
msgpack==1.0.7
msgpack-numpy==0.4.8
multidict==6.0.4
numpy==1.23.5
openai==1.2.3
packaging==23.2
pfzy==0.3.4
Pillow==9.5.0
pluggy==1.3.0
prompt-toolkit==3.0.40
protobuf==4.25.0
psutil==5.9.6
pyasn1==0.5.0
pyasn1-modules==0.3.0
pydantic==2.5.0b1
pydantic_core==2.14.1
Pygments==2.16.1
pytest==7.4.3
python-dateutil==2.8.2
python-dotenv==1.0.0
python-json-logger==2.0.7
python-on-whales==0.46.0
pytz==2022.7.1
PyYAML==6.0.1
redis==5.0.1
regex==2023.10.3
replicate==0.18.1
requests==2.31.0
requests-toolbelt==0.9.1
rich==13.6.0
rich-click==1.7.1
rsa==4.9
s3transfer==0.7.0
semantic-version==2.10.0
single-source==0.3.0
six==1.16.0
sniffio==1.3.0
spinners==0.0.24
starlette==0.27.0
tenacity==8.2.3
termcolor==2.3.0
tiktoken==0.5.1
tokenizers==0.14.1
tqdm==4.66.1
truss==0.6.4
typer==0.9.0
types-docutils==0.20.0.3
types-Pillow==9.5.0.6
types-pytz==2022.7.1.2
types-PyYAML==6.0.12.12
types-requests==2.31.0.10
types-setuptools==65.7.0.4
typing_extensions==4.8.0
urllib3==2.0.7
uvicorn==0.21.1
watchfiles==0.19.0
wcwidth==0.2.9
yarl==1.9.2
zipp==3.17.0
```

### Relevant log output

```shell
During handling of the above exception, another exception occurred:

    def test_openai_embedding():
        try:
            response = embedding(
                model="text-embedding-ada-002", input=["good morning from litellm", "this is another item"]
            )
            print(response)
            # Add any assertions here to check the response
            # print(f"response: {str(response)}")
        except Exception as e:
>           pytest.fail(f"Error occurred: {e}")
E           Failed: Error occurred: Traceback (most recent call last):
E             File "/Users/x/litellm/litellm/llms/openai.py", line 357, in embedding
E               model_response["object"] = "list"
E               ~~~~~~~~~~~~~~^^^^^^^^^^
E           TypeError: 'EmbeddingResponse' object does not support item assignment
```

**Comment by canada4663** [comment]
was running tests associated with attempts to merge #765

**Comment by ryanh-ai** [comment]
I can work toward fixing this, however, its a fairly broad reaching change where EmbeddingResponse objects are used, so I wanted to check in before I looked deeper.

**Comment by ryanh-ai** [comment]
Suspect related to #774 in progress, will try again after I can pull all related updates from that effort in

**Comment by ghost** [comment]
yup this is related. i'm working on this today @canada4663

**Comment by ishaan-jaff** [comment]
this is fixed on the latest version for me @canada4663

**Comment by ishaan-jaff** [comment]
feel free to re-open this issue if it's not fixed for you @canada4663
