### ISSUE TITLE
[Bug]: AttributeError in llama-index LiteLLM class

### ISSUE THREAD

**Issue by SeeknnDestroy** [BerriAI/litellm#816]
### What happened?

When running the provided example code, I receive an `AttributeError` related to the `pop` method on a `Message` object.

```python
import os
from llama_index.llms import LiteLLM, ChatMessage
from dotenv import load_dotenv

load_dotenv()

message = ChatMessage(role="user", content="Hey! how's it going?")

# llm params
model = "gpt-3.5-turbo"
temperature = 0.9
max_tokens = 512
# openai call
llm = LiteLLM(model=model, temperature=temperature, max_tokens=max_tokens)
chat_response = llm.chat([message])

print(chat_response)
```

### Additional Context
- This issue seems to be linked to the compatibility of litellm with the latest updates of llama-index and OpenAI's API version 1.0.0+.
- I have opened a related issue in the llama-index repository, which can be found here: https://github.com/run-llama/llama_index/issues/8906
- I am using the latest versions of both litellm (1.0.0) and llama-index (0.8.68).

I would appreciate any assistance or guidance on resolving this integration issue, as it is critical for our use case involving both litellm and llama-index.

### Relevant log output

```shell
/home/seekndestroy/mambaforge/envs/autollm/lib/python3.10/site-packages/pydantic/main.py:308: UserWarning: Pydantic serializer warnings:
  Expected `Usage` but got `dict` - serialized value may not be as expected
  return self.__pydantic_serializer__.to_python(
message_dict: Message(content="Hello! I'm an AI language model, so I don't have feelings, but I'm here to help you. How can I assist you today?", role='assistant')
additional_kwargs: Message(content="Hello! I'm an AI language model, so I don't have feelings, but I'm here to help you. How can I assist you today?", role='assistant')
Traceback (most recent call last):
  File "/home/seekndestroy/mambaforge/envs/autollm/lib/python3.10/site-packages/pydantic/main.py", line 751, in __getattr__
    return pydantic_extra[item]
KeyError: 'pop'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/seekndestroy/safeVideo/github/autollm/testing.py", line 15, in <module>
    chat_response = llm.chat([message])
  File "/home/seekndestroy/mambaforge/envs/autollm/lib/python3.10/site-packages/llama_index/llms/base.py", line 187, in wrapped_llm_chat
    f_return_val = f(_self, messages, **kwargs)
  File "/home/seekndestroy/mambaforge/envs/autollm/lib/python3.10/site-packages/llama_index/llms/litellm.py", line 123, in chat
    return chat_fn(messages, **kwargs)
  File "/home/seekndestroy/mambaforge/envs/autollm/lib/python3.10/site-packages/llama_index/llms/litellm.py", line 195, in _chat
    message = from_openai_message_dict(message_dict)
  File "/home/seekndestroy/mambaforge/envs/autollm/lib/python3.10/site-packages/llama_index/llms/litellm_utils.py", line 169, in from_openai_message_dict
    additional_kwargs.pop("role")
  File "/home/seekndestroy/mambaforge/envs/autollm/lib/python3.10/site-packages/pydantic/main.py", line 753, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
AttributeError: 'Message' object has no attribute 'pop'
```

**Comment by ishaan-jaff** [comment]
Hi @SeeknnDestroy acknowledging this - will work on making a PR to Llama index

**Comment by fcakyon** [comment]
@ishaan-jaff amazing news! Thank you 🚀

**Comment by fcakyon** [comment]
@ishaan-jaff @krrishdholakia This issue has been blocking our autollm package (600+ stars on github) development heavily for 12 days. If you could guide us on where to make the necessary changes, I am willing to try the llama-index PR. Can you please help on this matter?

Bests

**Comment by ishaan-jaff** [comment]
fix is merged
