### ISSUE TITLE
APIConnectionError

### ISSUE THREAD

**Issue by lantiannb** [BerriAI/litellm#821]
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

        Python Version: 3.11.6
        Pip Version: 23.2.1
        Open-interpreter Version: cmd:Interpreter, pkg: 0.1.15
        OS Version and Architecture: Windows-10-10.0.22621-SP0
        CPU Info: Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
        RAM Info: 63.82 GB, used: 19.57, free: 44.24

        Interpreter Info
        Vision: False
        Model: gpt-3.5-turbo
        Function calling: True
        Context window: None
        Max tokens: None

        Auto run: True
        API base: None
        Local: False

        Curl output: Not local

urllib3.exceptions.SSLError: [SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 874, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 874, in urlopen
    return self.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\urllib3\util\retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.nova-oss.com', port=443): Max retries exceeded with url: /v1/chat/completions/chat/completions (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 606, in request_raw
    result = _thread_context.session.request(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\adapters.py", line 517, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.nova-oss.com', port=443): Max retries exceeded with url: /v1/chat/completions/chat/completions (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Scripts\interpreter.exe\__main__.py", line 7, in <module>
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 24, in cli
    cli(self)
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\cli\cli.py", line 268, in cli
    interpreter.chat()
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 86, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 106, in _streaming_chat
    yield from terminal_interface(self, message)
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\terminal_interface\terminal_interface.py", line 115, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 127, in _streaming_chat
    yield from self._respond()
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\core.py", line 162, in _respond
    yield from respond(self)
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\core\respond.py", line 49, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\interpreter\llm\setup_openai_coding_llm.py", line 114, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 962, in wrapper
    raise e
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 899, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 1403, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 3574, in exception_type
    raise e
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\utils.py", line 2885, in exception_type
    raise original_exception
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 509, in completion
    raise e
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\litellm\main.py", line 491, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_resources\abstract\engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 289, in request
    result = self.request_raw(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\LT\AppData\Local\Programs\Python\Python311\Lib\site-packages\openai\api_requestor.py", line 619, in request_raw
    raise error.APIConnectionError(
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.nova-oss.com', port=443): Max retries exceeded with url: /v1/chat/completions/chat/completions (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))

**Comment by ghost** [comment]
Hey @lantiannb - this looks like the openai is raising an error when it's trying to connect to your proxy endpoint. 

see: 

> openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.nova-oss.com', port=443): Max retries exceeded with url: /v1/chat/completions/chat/completions (Caused by SSLError(SSLEOFError(8, '[SSL: UNEXPECTED_EOF_WHILE_READING] EOF occurred in violation of protocol (_ssl.c:1006)')))

I would test the endpoint via curl to see if it's working. 

If this call (chat completions) works with the openai-python sdk, let me know. 

Closing for now as this issue doesn't look litellm-related. Please re-open if you discover otherwise.

**Comment by Undertone0809** [comment]
I often meet this error.
