### ISSUE TITLE
[Bug]: Receive AzureException when making function calling on gpt-3.5-16k in Azure

### ISSUE THREAD

**Issue by paulpierre** [BerriAI/litellm#824]
### What happened?

Background: [Azure function calling has been available](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling?tabs=python)  in `api_version` since `2023-07-01-preview` compatible with:
- `gpt-35-turbo`
- `gpt-35-turbo-16k`
- `gpt-4`
- `gpt-4-32k`

Example URL: `https://xxxx.openai.azure.com/openai/deployments/gpt35turbo16k/chat/completions?api-version=2023-08-01-preview`

[Expected output](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/function-calling?tabs=python) from Azure: 

```json
{
  "role": "assistant",
  "function_call": {
    "name": "search_hotels",
    "arguments": "{\n  \"location\": \"San Diego\",\n  \"max_price\": 300,\n  \"features\": \"beachfront,free breakfast\"\n}"
  }
}
```

Issue: litellm version `0.14.1` incorrectly expects "content" in a `function_call` ChatCompletion JSON response, despite function calling not providing one per API specs. A `KeyError` -> `AzureException` is thrown. See attached output log

### Relevant log output

```shell
AzureException - Traceback (most recent call last):
llm-service-celery-worker-1  |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2620, in convert_to_model_response_object
llm-service-celery-worker-1  |     message = Message(content=choice["message"]["content"], role=choice["message"]["role"], function_call=choice["message"].get("function_call", None))
llm-service-celery-worker-1  | KeyError: 'content'
llm-service-celery-worker-1  |
llm-service-celery-worker-1  | During handling of the above exception, another exception occurred:
llm-service-celery-worker-1  |
llm-service-celery-worker-1  | Traceback (most recent call last):
llm-service-celery-worker-1  |   File "/usr/local/lib/python3.9/site-packages/litellm/llms/azure.py", line 150, in completion
llm-service-celery-worker-1  |     return convert_to_model_response_object(response_object=response.json(), model_response_object=model_response)
llm-service-celery-worker-1  |   File "/usr/local/lib/python3.9/site-packages/litellm/utils.py", line 2639, in convert_to_model_response_object
llm-service-celery-worker-1  |     raise Exception(f"Invalid response object {e}")
llm-service-celery-worker-1  | Exception: Invalid response object 'content'
```
```


### Twitter / LinkedIn details

@paulpierre

**Comment by ghost** [comment]
fixed - https://github.com/BerriAI/litellm/commit/8c104e9c6a7dfa768950ed9f6af185e07dd9fcce

**Comment by ghost** [comment]
will update ticket with release
