### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lzfhy** [BerriAI/litellm#828]
What should I do to figure it out? I gave a requirement but it showed like this blew:

```
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.


        Python Version: 3.10.13
        Pip Version: 23.3.1
        Open-interpreter Version: cmd:Interpreter, pkg: 0.1.15
        OS Version and Architecture: macOS-14.0-arm64-arm-64bit
        CPU Info: arm
        RAM Info: 8.00 GB, used: 2.90, free: 0.21
        

        Interpreter Info
        Vision: False
        Model: gpt-4
        Function calling: True
        Context window: None
        Max tokens: None

        Auto run: False
        API base: None
        Local: False

        Curl output: Not local
    
    
Traceback (most recent call last):
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/bin/interpreter", line 8, in <module>
    sys.exit(cli())
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/interpreter/core/core.py", line 24, in cli
    cli(self)
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/interpreter/cli/cli.py", line 268, in cli
    interpreter.chat()
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/interpreter/core/core.py", line 86, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/interpreter/core/core.py", line 106, in _streaming_chat
    yield from terminal_interface(self, message)
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/interpreter/terminal_interface/terminal_interface.py", line 115, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/interpreter/core/core.py", line 127, in _streaming_chat
    yield from self._respond()
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/interpreter/core/core.py", line 162, in _respond
    yield from respond(self)
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/interpreter/core/respond.py", line 49, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/interpreter/llm/setup_openai_coding_llm.py", line 114, in coding_llm
    response = litellm.completion(**params)
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/litellm/utils.py", line 962, in wrapper
    raise e
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/litellm/utils.py", line 899, in wrapper
    result = original_function(*args, **kwargs)
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/litellm/timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/litellm/timeout.py", line 42, in async_func
    return func(*args, **kwargs)
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/litellm/main.py", line 1403, in completion
    raise exception_type(
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/litellm/utils.py", line 3574, in exception_type
    raise e
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/litellm/utils.py", line 2885, in exception_type
    raise original_exception
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/litellm/main.py", line 509, in completion
    raise e
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/litellm/main.py", line 491, in completion
    response = openai.ChatCompletion.create(
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/Users/zengyuxin/.pyenv/versions/3.10.13/lib/python3.10/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
openai.error.InvalidRequestError: The model `gpt-4` does not exist or you do not have access to it. Learn more: https://help.openai.com/en/articles/7102672-how-can-i-access-gpt-4.
```

**Comment by ishaan-jaff** [comment]
@lzfhy looks like you do not have access to gpt-4 

can you try making a request to gpt-4 with https://github.com/openai/openai-python

**Comment by ghost** [comment]
closing this issue as it seems like @lzfhy doesn't have gpt-4 access not litellm related. 

please re-open if this works with the openai sdk.
