### ISSUE TITLE
[Bug]: Langfuse callback handler doesn't handles properly streaming response

### ISSUE THREAD

**Issue by IvanProgramming** [BerriAI/litellm#829]
### What happened?

This issue happened on usage of openai-proxy, but I'm sure, that this bug happens in library

### How to replay
1. Setup openai-proxy with at least one openai model (or any streming model I guess)
2. Add `langfuse` to `success_callback` config
3. Make example OpenAI request
```bash
curl --location 'https://openai-proxy/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data '{
    "model": "gpt-3.5-turbo",
    "messages": [
        {
            "role": "user",
            "content": "Who won the world series in 2020?"
        },
        {
            "role": "assistant",
            "content": "The Los Angeles Dodgers won the World Series in 2020."
        },
        {
            "role": "user",
            "content": "Where was it played?"
        }
    ],
    "temperature": 1,
    "top_p": 1,
    "n": 1,
    "stream": false,
    "max_tokens": 250,
    "presence_penalty": 0,
    "frequency_penalty": 0
}'
```
Everything would be logged in Langfuse
4. Create exact same request with `stream: true`

```bash
curl --location 'https://openai-proxy/v1/chat/completions' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--data '{
    "model": "gpt-3.5-turbo",
    "messages": [
        {
            "role": "user",
            "content": "Who won the world series in 2020?"
        },
        {
            "role": "assistant",
            "content": "The Los Angeles Dodgers won the World Series in 2020."
        },
        {
            "role": "user",
            "content": "Where was it played?"
        }
    ],
    "temperature": 1,
    "top_p": 1,
    "n": 1,
    "stream": true,
    "max_tokens": 250,
    "presence_penalty": 0,
    "frequency_penalty": 0
}'
```
Expected SSE would be responded in console, and openai-proxy would raise KeyError

### Relevant log output

```shell
Langfuse Layer Error - Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 753, in __getattr__
    return pydantic_extra[item]
KeyError: 'message'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litellm/integrations/langfuse.py", line 57, in log_event
    completion=response_obj['choices'][0]['message'],
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 249, in __getitem__
    return getattr(self, key)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 755, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
AttributeError: 'StreamingChoices' object has no attribute 'message'
```

### Twitter / LinkedIn details

@ivanisplaying

**Comment by ishaan-jaff** [comment]
@IvanProgramming thanks for trying this - will take a look at this and fix it today

**Comment by ishaan-jaff** [comment]
this is fixed - waiting for a new deploy to go through

**Comment by IvanProgramming** [comment]
Checked new version (v1.1.1), now all streaming responses has this exception

```bash
Custom Logger - Enters logging function for model {'model': 'gpt-3.5-turbo', 'messages': [{'role': 'user', 'content': 'Who won the worl
d series in 2020?'}, {'role': 'assistant', 'content': 'The Los Angeles Dodgers won the World Series in 2020.'}, {'role': 'user', 'conte
nt': 'Where was it played?'}], 'optional_params': {'temperature': 1, 'top_p': 1, 'stream': True, 'max_tokens': 250, 'presence_penalty':
 0, 'frequency_penalty': 0, 'n': 1}, 'litellm_params': {'return_async': False, 'api_key': None, 'force_timeout': 600, 'logger_fn': None
, 'verbose': False, 'custom_llm_provider': 'openai', 'api_base': None, 'litellm_call_id': 'f645fe36-5c8f-4d15-83bd-9a917ad44499', 'mode
l_alias_map': {}, 'completion_call_id': None, 'metadata': None, 'stream_response': {}}, 'start_time': datetime.datetime(2023, 11, 20, 1
2, 4, 4, 517738), 'input': None, 'api_key': None, 'additional_args': {}, 'log_event_type': 'successful_api_call', 'original_response': 
"<class 'openai.Stream'>", 'end_time': datetime.datetime(2023, 11, 20, 12, 4, 5, 602156)}   
Custom Logger Error - Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 753, in __getattr__ 
    return pydantic_extra[item]
KeyError: 'total_tokens'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litellm/integrations/custom_logger.py", line 59, in log_event
    callback_func(
  File "/usr/local/lib/python3.10/dist-packages/litellm/router.py", line 334, in deployment_callback
    total_tokens = completion_response['usage']['total_tokens']
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 234, in __getitem__ 
    return getattr(self, key)
  File "/usr/local/lib/python3.10/dist-packages/pydantic/main.py", line 755, in __getattr__ 
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}') from exc
AttributeError: 'Usage' object has no attribute 'total_tokens'
```

No traces are logged into LLM logging tool

**Comment by ghost** [comment]
will work on testing + fixing this today, sorry about that @IvanProgramming

**Comment by ishaan-jaff** [comment]
is this fixed @krrishdholakia ?

**Comment by IvanProgramming** [comment]
Fixed! Thank you ❤️
