### ISSUE TITLE
[Bug]: GPT-3.5 Function calling with streaming not working 

### ISSUE THREAD

**Issue by ishaan-jaff** [BerriAI/litellm#843]
### What happened?

```python
function1 = [
        {
            "name": "get_current_weather",
            "description": "Get the current weather in a given location",
            "parameters": {
                "type": "object",
                "properties": {
                    "location": {
                        "type": "string",
                        "description": "The city and state, e.g. San Francisco, CA",
                    },
                    "unit": {"type": "string", "enum": ["celsius", "fahrenheit"]},
                },
                "required": ["location"],
            },
        }
    ]
    try:
        response = completion(
            model="gpt-3.5-turbo", 
            messages= [
                {
                    "role": "user",
                    "content": "what is the weather in India"
                }
            ],
            functions=function1, 
            stream=True,
        )
        # Add any assertions here to check the response
        print(response)
        for chunk in response:
            print(chunk)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "/Users/ishaanjaffer/Github/litellm/litellm/tests/test_streaming.py", line 992, in <module>
    test_completion_openai_with_functions()
  File "/Users/ishaanjaffer/Github/litellm/litellm/tests/test_streaming.py", line 991, in test_completion_openai_with_functions
    pytest.fail(f"Error occurred: {e}")
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/_pytest/outcomes.py", line 198, in fail
    raise Failed(msg=reason, pytrace=pytrace)
Failed: Error occurred: 'Delta' object has no attribute 'content'
LiteLLM.LoggingError: [Non-Blocking] Exception occurred while success logging Traceback (most recent call last):
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 717, in success_handler
    complete_streaming_response = litellm.stream_chunk_builder(self.streaming_chunks)
  File "/Users/ishaanjaffer/Github/litellm/litellm/main.py", line 2063, in stream_chunk_builder
    role = chunks[0]["choices"][0]["delta"]["role"]
  File "/Users/ishaanjaffer/Github/litellm/litellm/utils.py", line 180, in __getitem__
    return getattr(self, key)
AttributeError: 'Delta' object has no attribute 'role'
```
```


### Twitter / LinkedIn details

_No response_

**Comment by ishaan-jaff** [comment]
fixed
