### ISSUE TITLE
[Bug]: Unable to serve multiple LLMs with Ollama models

### ISSUE THREAD

**Issue by wtlow003** [BerriAI/litellm#857]
### What happened?

Based on my understanding on the current support for Ollama, we are able to start an OpenAI proxy server for Ollama models using the following command:

```bash
litellm --model ollama/codellama:13b --debug
```

Launching a single model for Ollama model works perfectly as expected, where the [proxy_cli.py](https://github.com/BerriAI/litellm/blob/main/litellm/proxy/proxy_cli.py) script runs the ollama server in a separate worker, with the following command:

```bash
curl --location 'http://0.0.0.0:8000/chat/completions' \
--header 'Content-Type: application/json' \
--data ' {
      "model": "ollama/codellama:13b",
      "messages": [
        {
          "role": "user",
          "content": "what llm are you"
        }
      ],
    }
'
```

However, when I am looking to deploy multiple Ollama models through a config file:

```yaml
model_list:
  - model_name: deepseek-coder:latest
    litellm_params:
      model: ollama/deepseek-coder:latest
  - model_name: codellama:13b
    litellm_params:
      model: ollama/codellama:13b
```
and through the following command:
```bash
litellm --config config.yaml
```
 
Litellm returns an error as show in the relevant log output, where it seems that there's no connection to the `ollama serve`'s server at http://localhost:11434, using the same command as above. This issue only resolves when I start my own Ollama server at the side with `ollama serve`. I am assuming that when running with the config file, we are somehow not triggering the ollama serve like how it was done with a single model using the `--model` flag.

### Relevant log output

```shell
┌───────────────────
│ 📁 ~/code/litellm-proxy                                                                                                                      via 🐍 v3.11.6 is 📦 v0.1.0 took 1m9s  65%
└─❯  poetry run litellm --config config.yaml --debug
INFO:     Started server process [36759]
INFO:     Waiting for application startup.

#------------------------------------------------------------#
#                                                            #
#            'This product would be better if...'             #
#        https://github.com/BerriAI/litellm/issues/new        #
#                                                            #
#------------------------------------------------------------#

 Thank you for using LiteLLM! - Krrish & Ishaan



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new

Docs: https://docs.litellm.ai/docs/simple_proxy

LiteLLM: Test your local endpoint with: "litellm --test" [In a new terminal tab]


Loaded config YAML:
{
  "model_list": [
    {
      "model_name": "deepseek-coder:latest",
      "litellm_params": {
        "model": "ollama/deepseek-coder:latest"
      }
    },
    {
      "model_name": "codellama:13b",
      "litellm_params": {
        "model": "ollama/codellama:13b"
      }
    }
  ]
}
LiteLLM: Proxy initialized with Config, Set models:
    deepseek-coder:latest
    codellama:13b
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
callback: <bound method Router.deployment_callback of <litellm.router.Router object at 0x105c34890>>
callback: cache
litellm.caching: False; litellm.caching_with_models: False; litellm.cache: None
kwargs[caching]: False; litellm.cache: None

LiteLLM completion() model= codellama:13b

LiteLLM: Params passed to completion() {'functions': [], 'function_call': '', 'temperature': None, 'top_p': None, 'n': None, 'stream': None, 'stop': None, 'max_tokens': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': {}, 'user': '', 'model': 'codellama:13b', 'custom_llm_provider': 'ollama', 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None}

LiteLLM: Non-Default params passed to completion() {}
self.optional_params: {}
PRE-API-CALL ADDITIONAL ARGS: {'api_base': 'http://localhost:11434/api/generate', 'complete_input_dict': {'model': 'codellama:13b', 'prompt': 'what llm are you'}}


POST Request Sent from LiteLLM:
curl -X POST \
http://localhost:11434/api/generate \
-d '{'model': 'codellama:13b', 'prompt': 'what llm are you'}'


Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
self.failure_callback: []
An error occurred: 'NoneType' object has no attribute 'request'

 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
INFO:     127.0.0.1:55963 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 203, in _new_conn
    sock = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 85, in create_connection
    raise err
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 496, in _make_request
    conn.request(
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 395, in request
    self.endheaders()
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1281, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1041, in _send_output
    self.send(msg)
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 979, in send
    self.connect()
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 243, in connect
    self.sock = self._new_conn()
                ^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/urllib3/connection.py", line 218, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x102f137d0>: Failed to establish a new connection: [Errno 61] Connection refused

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/urllib3/util/retry.py", line 515, in increment
    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102f137d0>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/main.py", line 1242, in completion
    for chunk in generator:
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/llms/ollama.py", line 143, in get_ollama_response_stream
    with session.post(url, json=data, stream=True) as resp:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=11434): Max retries exceeded with url: /api/generate (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102f137d0>: Failed to establish a new connection: [Errno 61] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 513, in chat_completion
    return litellm_completion(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 403, in litellm_completion
    raise e
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 399, in litellm_completion
    response = litellm.completion(*args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/utils.py", line 1262, in wrapper
    raise e
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/utils.py", line 1196, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/main.py", line 1383, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/utils.py", line 4276, in exception_type
    raise e
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/utils.py", line 4151, in exception_type
    raise ServiceUnavailableError(
          ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/exceptions.py", line 91, in __init__
    super().__init__(
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/openai/_exceptions.py", line 79, in __init__
    super().__init__(message, response.request, body=body)
                              ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'request'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 521, in chat_completion
    status = e.status_code # type: ignore
             ^^^^^^^^^^^^^
AttributeError: 'AttributeError' object has no attribute 'status_code'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jensen/code/litellm-proxy/.venv/lib/python3.11/site-packages/litellm/proxy/proxy_server.py", line 523, in chat_completion
    status = status.HTTP_500_INTERNAL_SERVER_ERROR,
             ^^^^^^
UnboundLocalError: cannot access local variable 'status' where it is not associated with a value
```

**Comment by ghost** [comment]
Hey @wtlow003 you're correct - we check for ollama in the --model  cli arg, and run ollama in a separate thread when that happens. 

https://github.com/BerriAI/litellm/blob/c4f9ef86c987499898ca514c0e8c98afddbf8a1f/litellm/proxy/proxy_cli.py#L108

Is the idea here to trigger this run for config.yaml too?

**Comment by ghost** [comment]
fix pushed: https://github.com/BerriAI/litellm/commit/846a824c4741871dfb3c4e95958c6abb59eda5a8

**Comment by ghost** [comment]
can confirm this works for me
<img width="1133" alt="Screenshot 2023-11-21 at 8 35 37 AM" src="https://github.com/BerriAI/litellm/assets/17561003/e4339645-4496-4c3c-88c1-d1261d31420d">

**Comment by ghost** [comment]
should be live in v`1.3.2` soon.

**Comment by wtlow003** [comment]
Thanks for the hardwork @krrishdholakia! The fix is exactly what I expected in terms of functionality for Ollama backend. 

Forked and tested on my end and works perfectly!
<img width="1512" alt="Screenshot 2023-11-22 at 12 50 13 AM" src="https://github.com/BerriAI/litellm/assets/61908161/9efe2a10-950a-4b99-8605-ec6fc3d654f4">

**Comment by ghost** [comment]
great - closing for now.
