### ISSUE TITLE
[Bug]: TGI + Llama2-13B-chat-awq fails but works fine with 7B 

### ISSUE THREAD

**Issue by kulbinderdio** [BerriAI/litellm#889]
### What happened?

I set up TGI and pointed pointed litellm to use it. I used the following model
TheBloke/Llama-2-13B-Chat-AWQ

started litellm with
litellm --model huggingface/TheBloke/Llama-2-13B-Chat-AWQ --api_base http://0.0.0.0:8080/generate --host 0.0.0.0 --port 6789 --debug

used litellm --test
and got the errors detailed below

I used same setup with model
TheBloke/Llama-2-7B-Chat-AWQ and everything worked correctly

### Relevant log output

```shell
litellm.caching: False; litellm.caching_with_models: False; litellm.cache: None
kwargs[caching]: False; litellm.cache: None

LiteLLM completion() model= TheBloke/Llama-2-13B-Chat-AWQ; provider = huggingface

LiteLLM: Params passed to completion() {'functions': [], 'function_call': '', 'temperature': None, 'top_p': None, 'n': None, 'stream': None, 'stop': None, 'max_tokens': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': {}, 'user': '', 'model': 'TheBloke/Llama-2-13B-Chat-AWQ', 'custom_llm_provider': 'huggingface', 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': None}

LiteLLM: Non-Default params passed to completion() {}
self.optional_params: {}
TheBloke/Llama-2-13B-Chat-AWQ, text-generation-inference
PRE-API-CALL ADDITIONAL ARGS: {'complete_input_dict': {'inputs': 'this is a test request, write a short poem', 'parameters': {'details': True, 'return_full_text': False}, 'stream': False}, 'task': 'text-generation-inference', 'headers': {'content-type': 'application/json'}, 'api_base': 'http://0.0.0.0:8080/generate', 'acompletion': False}


POST Request Sent from LiteLLM:
curl -X POST \
http://0.0.0.0:8080/generate \
-H 'content-type: application/json' \
-d '{'inputs': 'this is a test request, write a short poem', 'parameters': {'details': True, 'return_full_text': False}, 'stream': False}'


RAW RESPONSE:
{"error":"Input validation error: one of `max_new_tokens` or `truncate` must be set if a fast tokenizer is not in use","error_type":"validation"}


Logging Details Post-API Call: logger_fn - None | callable(logger_fn) - False
response: [{'error': 'Input validation error: one of `max_new_tokens` or `truncate` must be set if a fast tokenizer is not in use', 'error_type': 'validation'}]
Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
self.failure_callback: []
An error occurred: HuggingfaceException - Traceback (most recent call last):
  File "/media/dio/e7f4e44f-ec98-4ef5-9db0-7e3f7a6ef8d0/home/dio/dev/litellm/venv/lib/python3.11/site-packages/litellm/llms/huggingface_restapi.py", line 423, in completion
    return self.convert_to_model_response_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/dio/e7f4e44f-ec98-4ef5-9db0-7e3f7a6ef8d0/home/dio/dev/litellm/venv/lib/python3.11/site-packages/litellm/llms/huggingface_restapi.py", line 173, in convert_to_model_response_object
    if len(completion_response[0]["generated_text"]) > 0:
          ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'generated_text'


 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
INFO:     127.0.0.1:45142 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
litellm.caching: False; litellm.caching_with_models: False; litellm.cache: None
kwargs[caching]: False; litellm.cache: None

LiteLLM completion() model= TheBloke/Llama-2-13B-Chat-AWQ; provider = huggingface

LiteLLM: Params passed to completion() {'functions': [], 'function_call': '', 'temperature': None, 'top_p': None, 'n': None, 'stream': None, 'stop': None, 'max_tokens': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': {}, 'user': '', 'model': 'TheBloke/Llama-2-13B-Chat-AWQ', 'custom_llm_provider': 'huggingface', 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': None}

LiteLLM: Non-Default params passed to completion() {}
self.optional_params: {}
TheBloke/Llama-2-13B-Chat-AWQ, text-generation-inference
PRE-API-CALL ADDITIONAL ARGS: {'complete_input_dict': {'inputs': 'this is a test request, write a short poem', 'parameters': {'details': True, 'return_full_text': False}, 'stream': False}, 'task': 'text-generation-inference', 'headers': {'content-type': 'application/json'}, 'api_base': 'http://0.0.0.0:8080/generate', 'acompletion': False}


POST Request Sent from LiteLLM:
curl -X POST \
http://0.0.0.0:8080/generate \
-H 'content-type: application/json' \
-d '{'inputs': 'this is a test request, write a short poem', 'parameters': {'details': True, 'return_full_text': False}, 'stream': False}'


RAW RESPONSE:
{"error":"Input validation error: one of `max_new_tokens` or `truncate` must be set if a fast tokenizer is not in use","error_type":"validation"}


Logging Details Post-API Call: logger_fn - None | callable(logger_fn) - False
response: [{'error': 'Input validation error: one of `max_new_tokens` or `truncate` must be set if a fast tokenizer is not in use', 'error_type': 'validation'}]
Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
self.failure_callback: []
An error occurred: HuggingfaceException - Traceback (most recent call last):
  File "/media/dio/e7f4e44f-ec98-4ef5-9db0-7e3f7a6ef8d0/home/dio/dev/litellm/venv/lib/python3.11/site-packages/litellm/llms/huggingface_restapi.py", line 423, in completion
    return self.convert_to_model_response_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/dio/e7f4e44f-ec98-4ef5-9db0-7e3f7a6ef8d0/home/dio/dev/litellm/venv/lib/python3.11/site-packages/litellm/llms/huggingface_restapi.py", line 173, in convert_to_model_response_object
    if len(completion_response[0]["generated_text"]) > 0:
          ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'generated_text'


 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
INFO:     127.0.0.1:45142 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
litellm.caching: False; litellm.caching_with_models: False; litellm.cache: None
kwargs[caching]: False; litellm.cache: None

LiteLLM completion() model= TheBloke/Llama-2-13B-Chat-AWQ; provider = huggingface

LiteLLM: Params passed to completion() {'functions': [], 'function_call': '', 'temperature': None, 'top_p': None, 'n': None, 'stream': None, 'stop': None, 'max_tokens': None, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': {}, 'user': '', 'model': 'TheBloke/Llama-2-13B-Chat-AWQ', 'custom_llm_provider': 'huggingface', 'response_format': None, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': None}

LiteLLM: Non-Default params passed to completion() {}
self.optional_params: {}
TheBloke/Llama-2-13B-Chat-AWQ, text-generation-inference
PRE-API-CALL ADDITIONAL ARGS: {'complete_input_dict': {'inputs': 'this is a test request, write a short poem', 'parameters': {'details': True, 'return_full_text': False}, 'stream': False}, 'task': 'text-generation-inference', 'headers': {'content-type': 'application/json'}, 'api_base': 'http://0.0.0.0:8080/generate', 'acompletion': False}


POST Request Sent from LiteLLM:
curl -X POST \
http://0.0.0.0:8080/generate \
-H 'content-type: application/json' \
-d '{'inputs': 'this is a test request, write a short poem', 'parameters': {'details': True, 'return_full_text': False}, 'stream': False}'


RAW RESPONSE:
{"error":"Input validation error: one of `max_new_tokens` or `truncate` must be set if a fast tokenizer is not in use","error_type":"validation"}


Logging Details Post-API Call: logger_fn - None | callable(logger_fn) - False
response: [{'error': 'Input validation error: one of `max_new_tokens` or `truncate` must be set if a fast tokenizer is not in use', 'error_type': 'validation'}]
Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
self.failure_callback: []
An error occurred: HuggingfaceException - Traceback (most recent call last):
  File "/media/dio/e7f4e44f-ec98-4ef5-9db0-7e3f7a6ef8d0/home/dio/dev/litellm/venv/lib/python3.11/site-packages/litellm/llms/huggingface_restapi.py", line 423, in completion
    return self.convert_to_model_response_object(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/media/dio/e7f4e44f-ec98-4ef5-9db0-7e3f7a6ef8d0/home/dio/dev/litellm/venv/lib/python3.11/site-packages/litellm/llms/huggingface_restapi.py", line 173, in convert_to_model_response_object
    if len(completion_response[0]["generated_text"]) > 0:
          ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
KeyError: 'generated_text'


 Debug this by setting `--debug`, e.g. `litellm --model gpt-3.5-turbo --debug`
INFO:     127.0.0.1:45142 - "POST /chat/completions HTTP/1.1" 500 Internal Server Error
```

**Comment by krrishdholakia** [comment]
hey @kulbinderdio which version of litellm are you using?

**Comment by ghost** [comment]
the raw response shows your TGI server failed: 


RAW RESPONSE:
{"error":"Input validation error: one of `max_new_tokens` or `truncate` must be set if a fast tokenizer is not in use","error_type":"validation"}

**Comment by kulbinderdio** [comment]
sorry, i should have also said that if I call directly into TGI it works
curl 127.0.0.1:8080/generate     -X POST     -d '{"inputs":"What is Deep Learning?","parameters":{"max_new_tokens":1000}}'     -H 'Content-Type: application/json'
that works

**Comment by ghost** [comment]
that's because you're passing in max_new_tokens. By default the test call doesn't pass that in. If you made a similar curl request to your proxy, that would work

```curl
curl --location 'http://0.0.0.0:6789/chat/completions' \
--header 'Content-Type: application/json' \
--data ' {
      "model": "gpt-3.5-turbo",
      "messages": [
        {
          "role": "user",
          "content": "what llm are you"
        }
      ],
    "max_tokens": 1000
    }
'
```

**Comment by kulbinderdio** [comment]
thanks Krrish

**Comment by ghost** [comment]
closing
