### ISSUE TITLE
[Bug]: Bad Error when accessing different Azure OpenAI deployments

### ISSUE THREAD

**Issue by solyarisoftware** [BerriAI/litellm#939]
### What happened?

Hi 
I discovered an important issue, due maybe to some unexpected litellm storage of an API_KEY :(

History / Use case :
I'm using TWO different Azure Openai deployments.  Let's call them DEPLOYMENT_A and DEPLOYMENT_B.

A week ago I used DEPLOYMENT_A (whit his Litellm compliant env vars setting):

```bash
export AZURE_API_BASE="https://AAAAAAAAAAAAA.openai.azure.com/"
export AZURE_OPENAI_API_KEY="AAAAAAAAAAAAAAAAAAAAAAAca4"
```

Today, I used DEPLOYMENT_B,  (whit his DIFFERENT Litellm compliant env vars setting); 
```bash
export AZURE_API_BASE="https://BBBBBBBBBBBBBBB.openai.azure.com/"
export AZURE_OPENAI_API_KEY="BBBBBBBBBBBBBBBBBBBBBBBBBB91e"
```

Of course AAA... and  BBB... are placeholders, but please note the last 3 chars: 
- in DEPLOYMENT_A are "ca4", 
- where instead in DEPLOYMENT_B are "91e".

So I set DEPLOYMENT_B vars and I run the follwing program using directly OpenAI API:

```python
# azure_openai_chat_completion.py
# https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/migration?tabs=python-new%2Cdalle-fix#chat-completions
import os
from openai import AzureOpenAI

client = AzureOpenAI(
    azure_endpoint=os.getenv("AZURE_API_BASE"),
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version=os.getenv("AZURE_API_VERSION")
)

response = client.chat.completions.create(
    model="gpt-35-turbo-0613",  # model = "deployment_name".
    messages=[ {"role": "user", "content": "Hello, how are you?"} ]
)

print(response.choices[0].message.content)
```

This work successfully demonstrating that env vars are valid endpoint and key.

```
$ py azure_openai_chat_completion.py
Hello! I'm an AI language model, so I don't have feelings, but I'm here to help you. How can I assist you today?```
```

---

Well, Afterward I run a very similar program using liteLLM, again with DEPLOYMENT_B env vars settings, same deployment name "azure/gpt-35-turbo-0613":

```python
# litellm_completion.py
from litellm import completion, litellm

user_message_content = "Hello, how are you?"

response = completion(
    model="azure/gpt-35-turbo-0613",
    messages=[{"content": user_message_content, "role": "user"}]
)

print(response["choices"][0]["message"]["content"])
```

I got a runtime exception: 

`litellm.exceptions.AuthenticationError: AzureException - Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}
`

Here below I copied the obfuscated debug-mode log.

IMMO The problem seems related to the section:

```
PRE-API-CALL ADDITIONAL ARGS: {'headers': {'api_key': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAca4', 'azure_ad_token': None}, 'api_version': '2023-09-01-preview', 'api_base': 'https:/
/openai-convai-fr.openai.azure.com/', 'complete_input_dict': {'model': 'gpt-35-turbo-0613', 'messages': [{'content': 'Hello, how are you?', 'role': 'user'}]}}
```

Here, for some reason I do not understant, the api_key is set to 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAca4', that's the API_KEY of  DEPLOYMENT_A, instead it could be "BBBBBBBBBBBBBBBBBBBBBBBBBB91e", the API_KEY of DEPLOYMENT_B! :( Why?
It seems to me that the DEPLOYMENT_A API_KEY is stored and used erronously for DEPLOYMENT_B.

---

Additional note:   
It seems to me that the problem arise with latest litellm version 1.7, because last week I tested succesfully with litellm version 1.6.x

```$ pip show litellm
Name: litellm
Version: 1.7.7
```
Looking forward for your feedback.
Thanks
giorgio

### Relevant log output

```shell
$ py litellm_completion.p
Traceback (most recent call last):
litellm.caching: False; litellm.caching_with_models: False; litellm.cache: None
  File "/home/giorgio/.local/lib/python3.11/site-packages/litellm/main.py", line 481, in completion
kwargs[caching]: False; litellm.cache: None

LiteLLM completion() model= gpt-35-turbo-0613; provider = azure

LiteLLM: Params passed to completion() {'functions': [], 'function_call': '', 'temperature': None, 'top_p': None, 'n': None, 'stream': None, 'stop': None, 'max_tokens': Non
e, 'presence_penalty': None, 'frequency_penalty': None, 'logit_bias': None, 'user': '', 'model': 'gpt-35-turbo-0613', 'custom_llm_provider': 'azure', 'response_format': Non
e, 'seed': None, 'tools': None, 'tool_choice': None, 'max_retries': None}

LiteLLM: Non-Default params passed to completion() {}
self.optional_params: {}
PRE-API-CALL ADDITIONAL ARGS: {'headers': {'api_key': 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAca4', 'azure_ad_token': None}, 'api_version': '2023-09-01-preview', 'api_base': 'https:/
/openai-convai-fr.openai.azure.com/', 'complete_input_dict': {'model': 'gpt-35-turbo-0613', 'messages': [{'content': 'Hello, how are you?', 'role': 'user'}]}}


POST Request Sent from LiteLLM:
curl -X POST \
https://BBBBBBBBBBBBBB.openai.azure.com/ \
-H 'api_key: BBBBBBBBBBBBBBBBBBBBBBBB***' -H 'azure_ad_token: None' \
-d '{'model': 'gpt-35-turbo-0613', 'messages': [{'content': 'Hello, how are you?', 'role': 'user'}]}'



Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.
    response = azure_chat_completions.completion(

Logging Details: logger_fn - None | callable(logger_fn) - False
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Logging Details LiteLLM-Failure Call
  File "/home/giorgio/.local/lib/python3.11/site-packages/litellm/llms/azure.py", line 166, in completion
self.failure_callback: []
    raise e
  File "/home/giorgio/.local/lib/python3.11/site-packages/litellm/llms/azure.py", line 159, in completion
    response = azure_client.chat.completions.create(**data) # type: ignore
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giorgio/.local/lib/python3.11/site-packages/openai/_utils/_utils.py", line 299, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/giorgio/.local/lib/python3.11/site-packages/openai/resources/chat/completions.py", line 598, in create
    return self._post(
           ^^^^^^^^^^^
  File "/home/giorgio/.local/lib/python3.11/site-packages/openai/_base_client.py", line 1063, in post
    return cast(ResponseT, self.request(cast_to, opts, stream=stream, stream_cls=stream_cls))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giorgio/.local/lib/python3.11/site-packages/openai/_base_client.py", line 842, in request
    return self._request(
           ^^^^^^^^^^^^^^
  File "/home/giorgio/.local/lib/python3.11/site-packages/openai/_base_client.py", line 885, in _request
    raise self._make_status_error_from_response(err.response) from None
openai.AuthenticationError: Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/giorgio/gpt/litellm/litellm_completion.py", line 11, in <module>
    response = completion(
               ^^^^^^^^^^^
  File "/home/giorgio/.local/lib/python3.11/site-packages/litellm/utils.py", line 1361, in wrapper
    raise e
  File "/home/giorgio/.local/lib/python3.11/site-packages/litellm/utils.py", line 1292, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/giorgio/.local/lib/python3.11/site-packages/litellm/main.py", line 1392, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/home/giorgio/.local/lib/python3.11/site-packages/litellm/utils.py", line 4548, in exception_type
    raise e
  File "/home/giorgio/.local/lib/python3.11/site-packages/litellm/utils.py", line 4468, in exception_type
    raise AuthenticationError(
litellm.exceptions.AuthenticationError: AzureException - Error code: 401 - {'statusCode': 401, 'message': 'Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.'}
```

### Twitter / LinkedIn details

twitter: @solyarisoftare linkedin: www.linkedin.com/in/giorgiorobino

**Comment by ishaan-jaff** [comment]
litellm reads the following Azure env variables 

```
os.environ["AZURE_API_KEY"] = ""
os.environ["AZURE_API_BASE"] = ""
os.environ["AZURE_API_VERSION"] = ""
```

it looks like you set

```

    api_key=os.getenv("AZURE_OPENAI_API_KEY"),

```

**Comment by ishaan-jaff** [comment]
perhaps what we can do here is read `AZURE_OPENAI_API_KEY` instead of `AZURE_API_KEY`

**Comment by ishaan-jaff** [comment]
added support for `AZURE_OPENAI_API_KEY` as an env variable  @solyarisoftware 
https://github.com/BerriAI/litellm/commit/224a028ab6b3fa8e26922ee0fcdc95856792df0a

**Comment by ishaan-jaff** [comment]
closing this issue - let me know if this is not fixed

**Comment by solyarisoftware** [comment]
Thanks @ishaan-jaff 

> perhaps what we can do here is read `AZURE_OPENAI_API_KEY` instead of `AZURE_API_KEY`

Oh! My mistake. Setting `AZURE_API_KEY`, all works as expected. 
It was my typo (using multiple libraries: litellm, Openai APIs, langachain...).

Maybe there is no need to support  `AZURE_OPENAI_API_KEY`. The important thing IMMO is thaa t documenattion is aligned with the code. 

Thanks again
giorgio
