### ISSUE TITLE
[Feature]: Allow setting Bedrock region

### ISSUE THREAD

**Issue by Manouchehri** [BerriAI/litellm#941]
### The Feature

```yaml
model_list:
  - model_name: command
    litellm_params:
      model: bedrock/cohere.command-text-v14
      aws_region: us-west-2
```

### Motivation, pitch

I want to be able to round-robin/load balance across different AWS regions.

### Twitter / LinkedIn details

https://www.linkedin.com/in/davidmanouchehri/

**Comment by ghost** [comment]
noted, i'm picking up this issue today @Manouchehri

**Comment by ghost** [comment]
@Manouchehri i believe this is already supported as the `aws_region_name` argument 

<img width="1075" alt="Screenshot 2023-11-28 at 5 33 41 PM" src="https://github.com/BerriAI/litellm/assets/17561003/cfe93465-feeb-4848-baee-de1f9f471d24">

**Comment by ghost** [comment]
please let me know if that solves your issue.

**Comment by Manouchehri** [comment]
Oh nice, one moment while I test it.

**Comment by Manouchehri** [comment]
This is my config:

```

litellm_settings:
  set_verbose: True
  drop_params: True

general_settings: 
  master_key: os.environ/LITELLM_MASTER_KEY

model_list:
  - model_name: claude-v2
    litellm_params:
      model: bedrock/anthropic.claude-v2
      aws_region_name: us-east-1
  - model_name: claude-v2
    litellm_params:
      model: bedrock/anthropic.claude-v2
      aws_region_name: us-west-2
  - model_name: claude-v2
    litellm_params:
      model: bedrock/anthropic.claude-v2
      aws_region_name: eu-central-1
```

```
LiteLLM.Router: Model bedrock/anthropic.claude-v2-ModelID-bedrock/anthropic.claude-v2us-west-2 had 2 exception
LiteLLM.Router: Model bedrock/anthropic.claude-v2-ModelID-bedrock/anthropic.claude-v2eu-central-1 had 2 exception
LiteLLM.Router: Model bedrock/anthropic.claude-v2-ModelID-bedrock/anthropic.claude-v2us-east-1 had 2 exception
Custom Logger Error - Traceback (most recent call last):
  File "/Users/dave/Work/litellm/litellm/llms/bedrock.py", line 410, in completion
    response = client.invoke_model_with_response_stream(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/botocore/client.py", line 983, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the InvokeModelWithResponseStream operation: Malformed input request: extraneous key [client] is not permitted, please reformat your input and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dave/Work/litellm/litellm/main.py", line 1172, in completion
    model_response = bedrock.completion(
                     ^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Work/litellm/litellm/llms/bedrock.py", line 505, in completion
    raise BedrockError(status_code=500, message=traceback.format_exc())
litellm.llms.bedrock.BedrockError: Traceback (most recent call last):
  File "/Users/dave/Work/litellm/litellm/llms/bedrock.py", line 410, in completion
    response = client.invoke_model_with_response_stream(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/botocore/client.py", line 983, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the InvokeModelWithResponseStream operation: Malformed input request: extraneous key [client] is not permitted, please reformat your input and try again.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dave/Work/litellm/litellm/main.py", line 188, in acompletion
    response =  await loop.run_in_executor(None, func_with_context)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Work/litellm/litellm/utils.py", line 1362, in wrapper
    raise e
  File "/Users/dave/Work/litellm/litellm/utils.py", line 1293, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Work/litellm/litellm/main.py", line 1397, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/dave/Work/litellm/litellm/utils.py", line 4632, in exception_type
    raise e
  File "/Users/dave/Work/litellm/litellm/utils.py", line 3959, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: BedrockException - Traceback (most recent call last):
  File "/Users/dave/Work/litellm/litellm/llms/bedrock.py", line 410, in completion
    response = client.invoke_model_with_response_stream(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/botocore/client.py", line 983, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the InvokeModelWithResponseStream operation: Malformed input request: extraneous key [client] is not permitted, please reformat your input and try again.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dave/Work/litellm/litellm/utils.py", line 1404, in wrapper_async
    result = await original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/dave/Work/litellm/litellm/main.py", line 195, in acompletion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/dave/Work/litellm/litellm/utils.py", line 4632, in exception_type
    raise e
  File "/Users/dave/Work/litellm/litellm/utils.py", line 3959, in exception_type
    raise BadRequestError(
litellm.exceptions.BadRequestError: BedrockException - BedrockException - Traceback (most recent call last):
  File "/Users/dave/Work/litellm/litellm/llms/bedrock.py", line 410, in completion
    response = client.invoke_model_with_response_stream(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/botocore/client.py", line 983, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the InvokeModelWithResponseStream operation: Malformed input request: extraneous key [client] is not permitted, please reformat your input and try again.


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dave/Work/litellm/litellm/integrations/custom_logger.py", line 53, in log_event
    callback_func(
  File "/Users/dave/Work/litellm/litellm/router.py", line 610, in deployment_callback_on_failure
    raise e
  File "/Users/dave/Work/litellm/litellm/router.py", line 605, in deployment_callback_on_failure
    self.print_verbose()
TypeError: Router.print_verbose() missing 1 required positional argument: 'print_statement'
```

**Comment by ghost** [comment]
hmm - i believe this might be related to this - https://github.com/BerriAI/litellm/issues/943

does the problem persist on the newer commit? Will repro on my end tomorrow

**Comment by ghost** [comment]
@Manouchehri  can confirm this works for me:
<img width="893" alt="Screenshot 2023-11-28 at 9 42 59 PM" src="https://github.com/BerriAI/litellm/assets/17561003/30afa0d0-7000-465b-96e6-3aebc4731c5e">


my config: 
```yaml
- model_name: "bedrock-cohere"
    litellm_params:
      model: "bedrock/cohere.command-text-v14"
      aws_region_name: "us-east-1"
  - model_name: "bedrock-cohere"
    litellm_params:
      model: "bedrock/cohere.command-text-v14"
      aws_region_name: "us-west-2"
```

**Comment by Manouchehri** [comment]
Thanks, confirmed it works for me now too!
