### ISSUE TITLE
[Bug]: Azure text-embedding-ada-002 embeddings generation

### ISSUE THREAD

**Issue by Extremys** [BerriAI/litellm#944]
### What happened?

Hello!
Commit used: 094144de58de7604deb47c525bd3ae72576560d4
Trying to generate embedding from Azure text-embedding-ada-002 I get error. 

Code to reproduce:
```

import openai
openai.api_key = 'mykey' 
openai.api_base = "https://mylitellm.com/v1"

model = "text-embedding-ada-002"

embedding = openai.Embedding.create(
    input="Your text goes here", model=model )["data"][0]["embedding"]
len(embedding)
print(embedding)
print(len(embedding))
```

LiteLLM configuration:
```
model_list:
  - model_name: text-embedding-ada-002
    litellm_params:
      model: azure/text-embedding-ada-002
      api_version: "2023-05-15"

litellm_settings:
  drop_params: True
  success_callback: ["langfuse"]
  set_verbose: True

environment_variables:
  LANGFUSE_PUBLIC_KEY: 
  LANGFUSE_SECRET_KEY: 
  LANGFUSE_HOST:
  AZURE_API_KEY: 
  AZURE_API_BASE: 

general_settings: 
  master_key: 
```

Could you help? Thanks.

### Relevant log output

```shell
Traceback (most recent call last):
  File "/code/litellm/litellm/llms/azure.py", line 319, in embedding
    response = azure_client.embeddings.create(**data) # type: ignore
TypeError: Embeddings.create() got an unexpected keyword argument 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/litellm/litellm/main.py", line 1747, in embedding
    response = azure_chat_completions.embedding(
  File "/code/litellm/litellm/llms/azure.py", line 351, in embedding
    raise AzureOpenAIError(status_code=500, message=traceback.format_exc())
litellm.llms.azure.AzureOpenAIError: Traceback (most recent call last):
  File "/code/litellm/litellm/llms/azure.py", line 319, in embedding
    response = azure_client.embeddings.create(**data) # type: ignore
TypeError: Embeddings.create() got an unexpected keyword argument 'metadata'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/litellm/litellm/proxy/proxy_server.py", line 827, in embeddings
    response = await llm_router.aembedding(**data)
  File "/code/litellm/litellm/router.py", line 267, in aembedding
    return await litellm.aembedding(**{**data, "input": input, "caching": self.cache_responses, **kwargs})
  File "/code/litellm/litellm/main.py", line 1669, in aembedding
    response =  await loop.run_in_executor(None, func_with_context)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/code/litellm/litellm/utils.py", line 1316, in wrapper
    raise e
  File "/code/litellm/litellm/utils.py", line 1247, in wrapper
    result = original_function(*args, **kwargs)
  File "/code/litellm/litellm/main.py", line 1848, in embedding
    raise exception_type(
  File "/code/litellm/litellm/utils.py", line 4471, in exception_type
    raise e
  File "/code/litellm/litellm/utils.py", line 4441, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: Traceback (most recent call last):
  File "/code/litellm/litellm/llms/azure.py", line 319, in embedding
    response = azure_client.embeddings.create(**data) # type: ignore
TypeError: Embeddings.create() got an unexpected keyword argument 'metadata'

data: {'input': 'Your text goes here', 'model': 'text-embedding-ada-002', 'encoding_format': 'base64'}
get cache: cache key: 19-21:cooldown_models
get cache: cache result: None
LiteLLM.Router: retrieve cooldown models: []
LiteLLM.Router: cooldown deployments: []
LiteLLM.Router: healthy deployments: [{'model_name': 'text-embedding-ada-002', 'litellm_params': {'model': 'azure/text-embedding-ada-002', 'api_version': '2023-05-15', 'timeout': None}}]
litellm.caching: False; litellm.caching_with_models: False; litellm.cache: None
kwargs[caching]: False; litellm.cache: None
self.optional_params: {}
PRE-API-CALL ADDITIONAL ARGS: {'complete_input_dict': {'model': 'text-embedding-ada-002', 'input': 'Your text goes here', 'encoding_format': 'base64', 'metadata': {'user_api_key': 'XXXXXX'}}, 'headers': {'api_key': 'XXXXXXXX', 'azure_ad_token': None}}
{'model': 'text-embedding-ada-002', 'messages': 'Your text goes here', 'optional_params': {}, 'litellm_params': {'timeout': None, 'azure': None, 'litellm_call_id': 'e478893d-d3f9-42b5-843d-8938ccf04096', 'logger_fn': None}, 'start_time': datetime.datetime(2023, 11, 28, 19, 21, 44, 42279), 'stream': False, 'input': 'Your text goes here', 'api_key': 'XXXXXXXX', 'additional_args': {'complete_input_dict': {'model': 'text-embedding-ada-002', 'input': 'Your text goes here', 'encoding_format': 'base64', 'metadata': {'user_api_key': 'XXXXXX'}}, 'headers': {'api_key': 'XXXXXX', 'azure_ad_token': None}}, 'log_event_type': 'pre_api_call'}

RAW RESPONSE:
Traceback (most recent call last):
  File "/code/litellm/litellm/llms/azure.py", line 319, in embedding
    response = azure_client.embeddings.create(**data) # type: ignore
TypeError: Embeddings.create() got an unexpected keyword argument 'metadata'



Logging Details Post-API Call: logger_fn - None | callable(logger_fn) - False
Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
get cache: cache key: 19-21:cooldown_models
get cache: cache result: None
LiteLLM.Router: adding text-embedding-ada-002 to cooldown models
set cache: key: 19-21:cooldown_models; value: ['text-embedding-ada-002']
Custom Logger - final response object: None
self.failure_callback: [<bound method Router.deployment_callback_on_failure of <litellm.router.Router object at 0x7f9c84344130>>]
INFO:      - "POST /v1/embeddings HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/code/litellm/litellm/llms/azure.py", line 319, in embedding
    response = azure_client.embeddings.create(**data) # type: ignore
TypeError: Embeddings.create() got an unexpected keyword argument 'metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/code/litellm/litellm/main.py", line 1747, in embedding
    response = azure_chat_completions.embedding(
  File "/code/litellm/litellm/llms/azure.py", line 351, in embedding
    raise AzureOpenAIError(status_code=500, message=traceback.format_exc())
litellm.llms.azure.AzureOpenAIError: Traceback (most recent call last):
  File "/code/litellm/litellm/llms/azure.py", line 319, in embedding
    response = azure_client.embeddings.create(**data) # type: ignore
TypeError: Embeddings.create() got an unexpected keyword argument 'metadata'


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/code/litellm/litellm/proxy/proxy_server.py", line 833, in embeddings
    raise e
  File "/code/litellm/litellm/proxy/proxy_server.py", line 827, in embeddings
    response = await llm_router.aembedding(**data)
  File "/code/litellm/litellm/router.py", line 267, in aembedding
    return await litellm.aembedding(**{**data, "input": input, "caching": self.cache_responses, **kwargs})
  File "/code/litellm/litellm/main.py", line 1669, in aembedding
    response =  await loop.run_in_executor(None, func_with_context)
  File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/code/litellm/litellm/utils.py", line 1316, in wrapper
    raise e
  File "/code/litellm/litellm/utils.py", line 1247, in wrapper
    result = original_function(*args, **kwargs)
  File "/code/litellm/litellm/main.py", line 1848, in embedding
    raise exception_type(
  File "/code/litellm/litellm/utils.py", line 4471, in exception_type
    raise e
  File "/code/litellm/litellm/utils.py", line 4441, in exception_type
    raise APIConnectionError(
litellm.exceptions.APIConnectionError: Traceback (most recent call last):
  File "/code/litellm/litellm/llms/azure.py", line 319, in embedding
    response = azure_client.embeddings.create(**data) # type: ignore
TypeError: Embeddings.create() got an unexpected keyword argument 'metadata'
```

**Comment by ishaan-jaff** [comment]
this should be fixed on 1.7.7 + @Extremys. can you try `pip install litellm -U`

**Comment by Extremys** [comment]
thanks for your answer, you mean 1.7.1 or really 1.7.7?
Actually currently I am cloning the repo and
git checkout 094144de58de7604deb47c525bd3ae72576560d4
then 
pip install -e .
Am I doing something wrong ?

**Comment by ghost** [comment]
Hey @Extremys not sure about that approach but i just put out a release v`1.7.8`

Any reason you're using the cloned repo vs. the package? 

Btw - why're you using the proxy?

**Comment by ishaan-jaff** [comment]
@Extremys 
can you verify your clone has this section:

https://github.com/BerriAI/litellm/blob/094144de58de7604deb47c525bd3ae72576560d4/litellm/main.py#L1718 


this filters out the metadata

**Comment by ishaan-jaff** [comment]
@Extremys this commit onwards should have support for Azure OpenAI embeddings 

https://github.com/BerriAI/litellm/commit/3891462b296e7c0aee45c16fc0e7955f21391587 

Can you confirm it works for you ?

**Comment by ishaan-jaff** [comment]
@Extremys this is fixed and it should be using the OpenAI async client

**Comment by ishaan-jaff** [comment]
here's my config I used

```yaml
model_list:
  - model_name: text-embedding-ada-002
    litellm_params:
      model: azure/azure-embedding-model
      api_key:  *********
      api_base: https://openai-gpt-4-test-v-1.openai.azure.com/
```

**Comment by ghost** [comment]
@Extremys did this resolve your issue? 

Would love to set up a direct support channel, as we improve the proxy. 

- Discord: Krrish#8748
- LinkedIn: https://www.linkedin.com/in/krish-d/

**Comment by Extremys** [comment]
Hello, thanks for the fix I can confirm tested on commit ID 9331f67c6912092a0165d27d1d105c63401f9bb1 I tried on the last one 69a449755050ed19eb274cb3d65a3c35ebfc548e but too many things has changed in term of config and I think you may introduced another bug but that is fine I will update for a stable version. Thanks you!

**Comment by ghost** [comment]
Hey @Extremys I don't recall introducing a change in the config. What changed?

Re: stable version, I would recommend waiting on releases. All releases run through ci/cd before being published.

**Comment by ishaan-jaff** [comment]
added tests for this too @Extremys 
https://github.com/BerriAI/litellm/issues/988 

the config should be a lot more stable for you.
