### ISSUE TITLE
[Bug]: router streaming azure tool calling stream chunk builder none error

### ISSUE THREAD

**Issue by krrishdholakia** [BerriAI/litellm#950]
### What happened?

messages is being passed as none for stream chunk builder for tool calling with router azure streaming.

### Relevant log output

```shell
LiteLLM.LoggingError: [Non-Blocking] Exception occurred while success logging Traceback (most recent call last):
  File "/Users/T961977/miniconda3/envs/openai/lib/python3.11/site-packages/litellm/utils.py", line 757, in success_handler
    complete_streaming_response = litellm.stream_chunk_builder(self.streaming_chunks, messages=self.model_call_details.get("messages", None))
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/T961977/miniconda3/envs/openai/lib/python3.11/site-packages/litellm/main.py", line 2190, in stream_chunk_builder
    response["usage"]["prompt_tokens"] = token_counter(model=model, messages=messages)
                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/T961977/miniconda3/envs/openai/lib/python3.11/site-packages/litellm/utils.py", line 1616, in token_counter
    text = "".join([message["content"] for message in messages])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 4: expected str instance, NoneType found
```

**Comment by ghost** [comment]
this is now fixed.
