### ISSUE TITLE
Petals does not support stream

### ISSUE THREAD

**Issue by juanfadev** [BerriAI/litellm#951]
Although in the docs is stated that it works with stream, you can try in the colab or in you local envs that it is clearly not supported:

```python
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.

Logging Details: logger_fn - None | callable(logger_fn) - False
Logging Details LiteLLM-Failure Call
self.failure_callback: []
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/litellm/main.py", line 1315, in completion
    model_response = petals.completion(
  File "/usr/local/lib/python3.10/dist-packages/litellm/llms/petals.py", line 155, in completion
    outputs = model_obj.generate(inputs, **optional_params)
  File "/usr/local/lib/python3.10/dist-packages/petals/client/remote_generation.py", line 116, in generate
    result = super().generate(inputs, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1433, in generate
    self._validate_model_kwargs(model_kwargs.copy())
  File "/usr/local/lib/python3.10/dist-packages/transformers/generation/utils.py", line 1249, in _validate_model_kwargs
    raise ValueError(
ValueError: The following `model_kwargs` are not used by the model: ['stream'] (note: typos in the generate arguments will also show up in this list)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/app/test.py", line 8, in <module>
    response = litellm.completion(model="petals/petals-team/StableBeluga2", messages=[{ "content": "Hello, how are you?","role": "user"}], stream=True)
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 962, in wrapper
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 899, in wrapper
    result = original_function(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/litellm/timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/dist-packages/litellm/timeout.py", line 42, in async_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/litellm/main.py", line 1403, in completion
    raise exception_type(
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 3574, in exception_type
    raise e
  File "/usr/local/lib/python3.10/dist-packages/litellm/utils.py", line 3556, in exception_type
    raise APIError(status_code=500, message=str(original_exception), llm_provider=custom_llm_provider, model=model)
litellm.exceptions.APIError: The followin
```

**Comment by ghost** [comment]
hi @juanfadev - acknowledging the issue. Something must've changed as this was working on last test. 

Will repro + push a fix by EOD tomorrow.

**Comment by ghost** [comment]
fix pushed - https://github.com/BerriAI/litellm/commit/c312ac4ca88029725bd57edffc9aa681187c9d71.
