### ISSUE TITLE
Error asking Interpreter to create a hello_world python app

### ISSUE THREAD

**Issue by biosopher** [BerriAI/litellm#968]
Interpreter was working great until I asked it to execute this seemingly simple request

Request:
```Create a python file in my downloads directory called test.py.  Add a main method that calls another method, hello_world(), that prints "hello world"```

Error:
```Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new
LiteLLM.Info: If you need to debug this error, use `litellm.set_verbose=True'.


        Python Version: 3.11.4
        Pip Version: 23.1.2
        Open-interpreter Version: cmd:Interpreter, pkg: 0.1.16
        OS Version and Architecture: macOS-14.0-x86_64-i386-64bit
        CPU Info: i386
        RAM Info: 32.00 GB, used: 16.06, free: 1.42
        

        Interpreter Info
        Vision: False
        Model: gpt-4-1106-preview
        Function calling: True
        Context window: 128000
        Max tokens: 4096

        Auto run: False
        API base: None
        Local: False

        Curl output: Not local
    
    
Traceback (most recent call last):
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/openai/api_requestor.py", line 413, in handle_error_response
    error_data = resp["error"]
                 ~~~~^^^^^^^^^
TypeError: string indices must be integers, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/bin/interpreter", line 8, in <module>
    sys.exit(start_terminal_interface())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/interpreter/core/core.py", line 21, in start_terminal_interface
    start_terminal_interface(self)
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/interpreter/terminal_interface/start_terminal_interface.py", line 305, in start_terminal_interface
    interpreter.chat()
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/interpreter/core/core.py", line 77, in chat
    for _ in self._streaming_chat(message=message, display=display):
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/interpreter/core/core.py", line 92, in _streaming_chat
    yield from terminal_interface(self, message)
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/interpreter/terminal_interface/terminal_interface.py", line 115, in terminal_interface
    for chunk in interpreter.chat(message, display=False, stream=True):
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/interpreter/core/core.py", line 113, in _streaming_chat
    yield from self._respond()
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/interpreter/core/core.py", line 148, in _respond
    yield from respond(self)
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/interpreter/core/respond.py", line 49, in respond
    for chunk in interpreter._llm(messages_for_llm):
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/interpreter/core/llm/setup_openai_coding_llm.py", line 118, in coding_llm
    response = litellm.completion(**params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/litellm/utils.py", line 962, in wrapper
    raise e
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/litellm/utils.py", line 899, in wrapper
    result = original_function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/litellm/timeout.py", line 53, in wrapper
    result = future.result(timeout=local_timeout_duration)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/litellm/timeout.py", line 42, in async_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/litellm/main.py", line 1403, in completion
    raise exception_type(
          ^^^^^^^^^^^^^^^
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/litellm/utils.py", line 3574, in exception_type
    raise e
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/litellm/utils.py", line 2885, in exception_type
    raise original_exception
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/litellm/main.py", line 509, in completion
    raise e
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/litellm/main.py", line 491, in completion
    response = openai.ChatCompletion.create(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/openai/api_resources/chat_completion.py", line 25, in create
    return super().create(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/openai/api_resources/abstract/engine_api_resource.py", line 155, in create
    response, _, api_key = requestor.request(
                           ^^^^^^^^^^^^^^^^^^
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/openai/api_requestor.py", line 299, in request
    resp, got_stream = self._interpret_response(result, stream)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/openai/api_requestor.py", line 710, in _interpret_response
    self._interpret_response_line(
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/openai/api_requestor.py", line 775, in _interpret_response_line
    raise self.handle_error_response(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/anthonystevens/Documents/Development/Python.venv/py311-open-interpreter/lib/python3.11/site-packages/openai/api_requestor.py", line 415, in handle_error_response
    raise error.APIError(
openai.error.APIError: Invalid response object from API: '400 Bad Request' (HTTP response code was 400)```

**Comment by biosopher** [comment]
Maybe there was a temporary issue with OpenAI?  I got the above error twice.  However being persistent, I ran a 3rd time and it worked:

```^[[A                                                                                                                                                                                                                                                                                                                                                                                                            
  Plan:                                                                                                                                                                                                 
                                                                                                                                                                                                        
   1 Write the Python code that defines a main method and a hello_world method.                                                                                                                         
   2 Use the functions.execute with language set to "shell" to create the file test.py in the Downloads directory.                                                                                      
   3 Write the Python code into test.py.                                                                                                                                                                
                                                                                                                                                                                                        
  Let's start with step 1 by writing the Python code.                                                                                                                                                   
                                                                                                                                                                                                        
  Recap: I will write the Python code for the main and hello_world methods.                                                                                                                             
                                                                                                                                                                                                        

                                                                                                                                                                                                        
  echo 'def hello_world():\n    print("hello world")\n\ndef main():\n    hello_world()\n\nif __name__ == "__main__":\n    main()' > ~/Downloads/test.py                                                 
                                                                                                                                                                                                        

  Would you like to run this code? (y/n)```

**Comment by ghost** [comment]
closing as this seems like an openai error, not litellm. 

@biosopher please reopen if that isn't the case.
