### ISSUE TITLE
[Bug]: /key/generate API endpoint broken

### ISSUE THREAD

**Issue by morgendigital** [BerriAI/litellm#996]
### What happened?

When trying to generate a key through API with the latest litellm version (1.10.2), I get an error.

**Call:**
`curl 'https://api.localmind.ai/key/generate' --header 'Content-Type: application/json' --header "Authorization: Bearer HERE_I_INSERT_MY_MASTER_KEY" --data '{ }'`

**Response:**
```
{"detail":[{"type":"missing","loc":["body","user_id"],"msg":"Field required","input":{},"url":"https://errors.pydantic.dev/2.5/v/missing"}]}
```

The error message suggests that I need to enter a user_id, which I did:

**Call with User ID:**
`curl 'https://api.localmind.ai/key/generate' --header 'Content-Type: application/json' --header "Authorization: Bearer HERE_I_INSERT_MY_MASTER_KEY" --data '{"user_id":"123"}'`

**Response:**
Internal Server Error happens, and this is the Python error:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/usr/local/lib/python3.10/dist-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/applications.py", line 1106, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/applications.py", line 122, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/cors.py", line 83, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/usr/local/lib/python3.10/dist-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 20, in __call__
    raise e
  File "/usr/local/lib/python3.10/dist-packages/fastapi/middleware/asyncexitstack.py", line 17, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 718, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/dist-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 274, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/lib/python3.10/dist-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/usr/local/lib/python3.10/dist-packages/litellm/proxy/proxy_server.py", line 994, in generate_key_fn
    duration_str = data.duration  # Default to 1 hour if duration is not provided
**AttributeError: 'dict' object has no attribute 'duration'**
```

I just used `pip install litellm` and then start it with my config.yaml file as --config parameter. The endpoint worked a few days before, I have already tested it successfully multiple times with my PostgreSQL database and it was doing well.

### Twitter / LinkedIn details

https://www.linkedin.com/in/ivandukic

**Comment by ghost** [comment]
Acknowledging this issue @morgendigital. I'll fix this and add testing in our ci/cd pipeline to prevent future regressions.

**Comment by morgendigital** [comment]
Thanks @krrishdholakia! Hope it's not a complicated one.

**Comment by ghost** [comment]
just pushed a fix + added ci/cd testing for this endpoint to prevent future regressions @morgendigital https://github.com/BerriAI/litellm/commit/63e55f1865ec0a0d02348c2d2b26811d1b6291ca

Will update once this is in prod. 

Would love to start a direct support channel. Attaching my linkedin + discord, please dm on whatever works best: 

- Discord: Krrish#8748
- LinkedIn: https://www.linkedin.com/in/krish-d/

**Comment by morgendigital** [comment]
@krrishdholakia you guys are incredible, thank you. Will test it in a bit.

**Comment by ghost** [comment]
@morgendigital litellm v`1.10.4` should have the fix. let me know if it solves your problem.

**Comment by morgendigital** [comment]
It's fixed now, thank you very much!
